// Viṣṇu Sahasranāma — stotra verses 1–36 (names 1–335), English.
// IAST follows the Mahābhārata Anuśāsana-Parva text (sanskritdocuments
// edition cross-checked against the Satyabhāṣyam PDF's readings);
// translations and commentaries are this project's own paraphrases in the
// Śaṅkara–Satyabhāṣyam lineage. See vishnu-sahasranama-source-provenance.ts.
export const vsStotraA: any[] = [
  {
    id: "vs-001",
    number: "Stotra 1 (names 1–9)",
    section: "Stotra · The all-pervading ground",
    iast: "oṃ viśvaṃ viṣṇur vaṣaṭkāro bhūta-bhavya-bhavat-prabhuḥ । bhūta-kṛd bhūta-bhṛd bhāvo bhūtātmā bhūta-bhāvanaḥ",
    conceptIds: ["vs-nama-001", "vs-nama-002", "vs-nama-003", "vs-nama-004", "vs-nama-005", "vs-nama-006", "vs-nama-007", "vs-nama-008", "vs-nama-009"],
    translation: "He who is the universe itself; He who pervades all; He who is invoked with the cry vaṣaṭ at the oblation; the Lord of past, future and present; the maker of beings; the bearer of beings; pure existence; the Self of beings; the nourisher of beings.",
    commentary: "The hymn opens with the whole in nine words: Viṣṇu is both the world (viśva) and its pervader (viṣṇu), both the sacrifice (vaṣaṭkāra) and the time in which sacrifice happens. Creator, sustainer and indweller are named together so that no later name can be read as anything but Brahman. Begin recitation by holding all three times at once.",
    keyPoints: ["Names 1–9: Viśvam — Bhūtabhāvanaḥ.", "World and pervader are one reality seen two ways.", "Contemplate past, present and future as His single body."],
  },
  {
    id: "vs-002",
    number: "Stotra 2 (names 10–17)",
    section: "Stotra · The all-pervading ground",
    iast: "pūtātmā paramātmā ca muktānāṃ paramā gatiḥ । avyayaḥ puruṣaḥ sākṣī kṣetrajño 'kṣara eva ca",
    conceptIds: ["vs-nama-010", "vs-nama-011", "vs-nama-012", "vs-nama-013", "vs-nama-014", "vs-nama-015", "vs-nama-016", "vs-nama-017"],
    translation: "He whose self is ever pure; the supreme Self; the highest goal of the liberated; the undecaying; the Person; the witness; the knower of the field; the imperishable.",
    commentary: "From cosmos the hymn turns inward: the same Lord is the pure Self within, the goal the freed attain, and the changeless witness of the body-field He knows but never becomes. Purity here means untouchedness — sin cannot stick to Him, and therefore cannot ultimately stick to the knower. Rest attention on the witness rather than the field.",
    keyPoints: ["Names 10–17: Pūtātmā — Akṣaraḥ.", "The Gītā's field-knower doctrine in eight names.", "Ask in sitting: am I the field or its knower?"],
  },
  {
    id: "vs-003",
    number: "Stotra 3 (names 18–24)",
    section: "Stotra · Descent and sovereignty",
    iast: "yogo yoga-vidāṃ netā pradhāna-puruṣeśvaraḥ । nārasiṃha-vapuḥ śrīmān keśavaḥ puruṣottamaḥ",
    conceptIds: ["vs-nama-018", "vs-nama-019", "vs-nama-020", "vs-nama-021", "vs-nama-022", "vs-nama-023", "vs-nama-024"],
    translation: "He who is union itself; the leader of knowers of yoga; Lord of nature and spirit; He of man-lion form; the glorious; the dark-haired; the supreme Person.",
    commentary: "The abstract Lord takes a leader's role and then a lion's claws: Nārasiṃha proves the witness can tear through empire when devotion is threatened. Yoga is named as both His nature and His gift — He is the path, its knowers' guide, and the Person beyond both nature and soul. Recall one moment when help arrived in terrible form.",
    keyPoints: ["Names 18–24: Yogaḥ — Puruṣottamaḥ.", "First avatāra name: the man-lion.", "Yoga is His being before it is our practice."],
  },
  {
    id: "vs-004",
    number: "Stotra 4 (names 25–36)",
    section: "Stotra · Descent and sovereignty",
    iast: "sarvaḥ śarvaḥ śivaḥ sthāṇur bhūtādir nidhiravyayaḥ । sambhavo bhāvano bhartā prabhavaḥ prabhur īśvaraḥ",
    conceptIds: ["vs-nama-025", "vs-nama-026", "vs-nama-027", "vs-nama-028", "vs-nama-029", "vs-nama-030", "vs-nama-031", "vs-nama-032", "vs-nama-033", "vs-nama-034", "vs-nama-035", "vs-nama-036"],
    translation: "He who is all; the destroyer of sin; the ever-auspicious; the pillar; the origin of beings; the imperishable treasure; the self-born; the giver of fruits; the bearer; the source; the mighty; the ruler.",
    commentary: "Twelve names chant the three cosmic acts without dividing them: Śiva the auspicious and Śarva the destroyer are Viṣṇu's own faces here, and the treasure (nidhi) never depletes no matter how much creation spends. Sovereignty is not domination but bearing — He carries what He rules. Offer one burden upward instead of carrying it alone.",
    keyPoints: ["Names 25–36: Sarvaḥ — Īśvaraḥ.", "Auspiciousness and destruction are one Lord's two hands.", "Nidhi: the treasure creation cannot exhaust."],
  },
  {
    id: "vs-005",
    number: "Stotra 5 (names 37–45)",
    section: "Stotra · Descent and sovereignty",
    iast: "svayambhūḥ śambhur ādityaḥ puṣkarākṣo mahāsvanaḥ । anādi-nidhano dhātā vidhātā dhātur uttamaḥ",
    conceptIds: ["vs-nama-037", "vs-nama-038", "vs-nama-039", "vs-nama-040", "vs-nama-041", "vs-nama-042", "vs-nama-043", "vs-nama-044", "vs-nama-045"],
    translation: "The self-born; the giver of joy; the golden one in the sun; the lotus-eyed; He of the thunder-voice; without beginning or end; the supporter; the ordainer; the finest essence.",
    commentary: "Self-existence flowers into senses: lotus eyes to see the devotee, thunder-voice (the Veda) to instruct, sunlight to warm. Dhātā holds the worlds up while Vidhātā portions out each being's due — support and justice as one function. Gaze at the sun once as His eye rather than a ball of fire.",
    keyPoints: ["Names 37–45: Svayambhūḥ — Dhāturuttamaḥ.", "From formless self-being to lotus eyes.", "Support (dhātā) and apportioning (vidhātā) never separate."],
  },
  {
    id: "vs-006",
    number: "Stotra 6 (names 46–54)",
    section: "Stotra · Measure, senses and time",
    iast: "aprameyo hṛṣīkeśaḥ padmanābho 'mara-prabhuḥ । viśvakarmā manus tvaṣṭā sthaviṣṭhaḥ sthaviro dhruvaḥ",
    conceptIds: ["vs-nama-046", "vs-nama-047", "vs-nama-048", "vs-nama-049", "vs-nama-050", "vs-nama-051", "vs-nama-052", "vs-nama-053", "vs-nama-054"],
    translation: "Beyond all measure; Lord of the senses; lotus-navelled; Lord of immortals; maker of the universe; the thinker; the fashioner; the vastest; the ancient and firm.",
    commentary: "The immeasurable gives Himself organs to be grasped by: a navel from which Brahmā's lotus grows, senses He lends us and then rules as Hṛṣīkeśa. Maker (viśvakarmā), thinker (manu) and cutter (tvaṣṭā) are the craftsman's three gestures, closed by the ancient firmness that never shifts. Surrender one unruly sense to its Lord today.",
    keyPoints: ["Names 46–54: Aprameyaḥ — Sthavirodhruvaḥ.", "Hṛṣīkeśa: He lends the senses, then governs them.", "The lotus navel: creation as His outward breath."],
  },
  {
    id: "vs-007",
    number: "Stotra 7 (names 55–63)",
    section: "Stotra · Measure, senses and time",
    iast: "agrāhyaḥ śāśvataḥ kṛṣṇo lohitākṣaḥ pratardanaḥ । prabhūtas trikakub-dhāma pavitraṃ maṅgalaṃ param",
    conceptIds: ["vs-nama-055", "vs-nama-056", "vs-nama-057", "vs-nama-058", "vs-nama-059", "vs-nama-060", "vs-nama-061", "vs-nama-062", "vs-nama-063"],
    translation: "Ungraspable; eternal; the dark one; the red-eyed; the destroyer at the end; the abundant; the support of the three worlds; purity itself; supreme auspiciousness.",
    commentary: "He who cannot be seized (agrāhya) lets Himself be loved as dark Kṛṣṇa with dawn-red eyes; He who dissolves all (pratardana) is Himself the purifier (pavitra). Auspiciousness is not luck but His nature — contact with Him is what makes anything maṅgala. When grasping fails, switch from seizing to singing.",
    keyPoints: ["Names 55–63: Agrāhyaḥ — Maṅgalamparam.", "Kṛṣṇa appears: darkness that attracts.", "The destroyer and the purifier are one act."],
  },
  {
    id: "vs-008",
    number: "Stotra 8 (names 64–73)",
    section: "Stotra · Measure, senses and time",
    iast: "īśānaḥ prāṇadaḥ prāṇo jyeṣṭhaḥ śreṣṭhaḥ prajāpatiḥ । hiraṇya-garbho bhū-garbho mādhavo madhu-sūdanaḥ",
    conceptIds: ["vs-nama-064", "vs-nama-065", "vs-nama-066", "vs-nama-067", "vs-nama-068", "vs-nama-069", "vs-nama-070", "vs-nama-071", "vs-nama-072", "vs-nama-073"],
    translation: "The ruler; giver of breath; breath itself; the eldest; the most excellent; lord of creatures; the golden womb; bearer of earth in His womb; Mādhava; slayer of Madhu.",
    commentary: "Rule is exercised as breathing: He gives the breath, is the breath, and outlives every breather as eldest and best. The golden womb holds creation before birth; Madhu's slaying keeps sweetness (madhava's honey) from rotting into the demon of delusion. Breathe once consciously as receiving, not taking.",
    keyPoints: ["Names 64–73: Īśānaḥ — Madhusūdanaḥ.", "Prāṇa given, prāṇa itself, prāṇa's Lord.", "Hiraṇyagarbha: creation gestating in gold."],
  },
  {
    id: "vs-009",
    number: "Stotra 9 (names 74–84)",
    section: "Stotra · Refuge and strength",
    iast: "īśvaro vikramī dhanvī medhāvī vikramaḥ kramaḥ । anuttamo durādharṣaḥ kṛtajñaḥ kṛtir ātmavān",
    conceptIds: ["vs-nama-074", "vs-nama-075", "vs-nama-076", "vs-nama-077", "vs-nama-078", "vs-nama-079", "vs-nama-080", "vs-nama-081", "vs-nama-082", "vs-nama-083", "vs-nama-084"],
    translation: "The controller; the valorous; the bowman; the greatly intelligent; the mighty stride; the step; beyond whom none; unassailable; mindful of deeds; action itself; self-established.",
    commentary: "The three strides of Trivikrama echo through vikrama and krama: His valour is measured in worlds crossed, yet His memory (kṛtajña) stoops to record the smallest offering. Action (kṛti) subsides into the self-established (ātmavān) — doing rooted in being, never in need. Walk one errand today as His stride, not your scramble.",
    keyPoints: ["Names 74–84: Īśvaraḥ — Ātmavān.", "Kṛti + ātmavān: action dissolving into selfhood.", "Kṛtajña: no sincere act goes unregistered."],
  },
  {
    id: "vs-010",
    number: "Stotra 10 (names 85–94)",
    section: "Stotra · Refuge and strength",
    iast: "sureśaḥ śaraṇaṃ śarma viśva-retāḥ prajā-bhavaḥ । ahaḥ saṃvatsaro vyālaḥ pratyayaḥ sarva-darśanaḥ",
    conceptIds: ["vs-nama-085", "vs-nama-086", "vs-nama-087", "vs-nama-088", "vs-nama-089", "vs-nama-090", "vs-nama-091", "vs-nama-092", "vs-nama-093", "vs-nama-094"],
    translation: "Lord of gods; the refuge; bliss itself; seed of the universe; source of creatures; the day; the year; the elusive serpent; conviction; the all-seeing.",
    commentary: "Refuge (śaraṇa) is placed before bliss (śarma): safety first, then joy. He is seed and source, then day and year — time itself becomes a form of shelter, and even the serpent-elusive (vyāla) is all-seeing, never blind. When evasive and ungraspable, remember the same verse calls Him refuge.",
    keyPoints: ["Names 85–94: Sureśaḥ — Sarvadarśanaḥ.", "Refuge precedes bliss: order matters.", "Day and year: time as sanctuary."],
  },
  {
    id: "vs-011",
    number: "Stotra 11 (names 95–103)",
    section: "Stotra · Refuge and strength",
    iast: "ajaḥ sarveśvaraḥ siddhaḥ siddhiḥ sarvādir acyutaḥ । vṛṣākapir ameyātmā sarva-yoga-viniḥsṛtaḥ",
    conceptIds: ["vs-nama-095", "vs-nama-096", "vs-nama-097", "vs-nama-098", "vs-nama-099", "vs-nama-100", "vs-nama-101", "vs-nama-102", "vs-nama-103"],
    translation: "The unborn; Lord of all; the perfect; perfection itself; beginning of all; the unfailing; the boar of dharma; the immeasurable self; attained by every yoga.",
    commentary: "The unborn (aja) needs no becoming to be perfect (siddha) — perfection is His starting point, not our finish line. Vṛṣākapi recalls the boar that lifted the earth from the waters: dharma submerged will always be raised. Every yoga, the verse insists, surfaces at the same Lord. Practice the day as rescue, not escape.",
    keyPoints: ["Names 95–103: Ajaḥ — Sarvayogaviniḥsṛtaḥ.", "Siddha and siddhi: He is both path and fruit.", "Vṛṣākapi: dharma lifted from the flood."],
  },
  {
    id: "vs-012",
    number: "Stotra 12 (names 104–113)",
    section: "Stotra · Dharma, Rudra and Veda",
    iast: "vasur vasumanāḥ satyaḥ samātmā sammitaḥ samaḥ । amoghaḥ puṇḍarīkākṣo vṛṣa-karmā vṛṣākṛtiḥ",
    conceptIds: ["vs-nama-104", "vs-nama-105", "vs-nama-106", "vs-nama-107", "vs-nama-108", "vs-nama-109", "vs-nama-110", "vs-nama-111", "vs-nama-112", "vs-nama-113"],
    translation: "The dweller; the good-minded; truth; the same self in all; the boundless; the equal; never in vain; lotus-eyed; righteous in deed; righteous in form.",
    commentary: "Vasu dwells in all beings as their wealth, and sameness (sama) is repeated four ways lest we mistake equality for sameness of bodies — it is sameness of Self. His acts never misfire (amogha), and lotus eyes see the mud without condemnation. Meet one adversary today as the same Self in different dress.",
    keyPoints: ["Names 104–113: Vasuḥ — Vṛṣākṛtiḥ.", "Fourfold sameness: self, not circumstance.", "Amogha: no divine act ever fails."],
  },
  {
    id: "vs-013",
    number: "Stotra 13 (names 114–122)",
    section: "Stotra · Dharma, Rudra and Veda",
    iast: "rudro bahu-śirā babhrur viśva-yonir śuci-śravāḥ । amṛtaḥ śāśvata-sthāṇur varāroho mahā-tapāḥ",
    conceptIds: ["vs-nama-114", "vs-nama-115", "vs-nama-116", "vs-nama-117", "vs-nama-118", "vs-nama-119", "vs-nama-120", "vs-nama-121", "vs-nama-122"],
    translation: "The remover of sorrow; many-headed; the bearer; womb of the universe; of holy fame; deathless; eternal pillar; the highest ascent; of great austerity.",
    commentary: "Rudra's fierceness is re-read as surgery: He removes (rudra) sorrow by cutting, carries (babhru) what He cuts away from, and stands as the pillar the storm cannot bend. Fame itself is purified — śuciśravāḥ means only holy things are heard of Him. Let one grief be removed rather than nursed.",
    keyPoints: ["Names 114–122: Rudraḥ — Mahātapāḥ.", "Rudra here: sorrow's remover, not its maker.", "Many heads: every face turned toward sufferers."],
  },
  {
    id: "vs-014",
    number: "Stotra 14 (names 123–132)",
    section: "Stotra · Dharma, Rudra and Veda",
    iast: "sarvagaḥ sarva-vid-bhānur viṣvak-seno janārdanaḥ । vedo veda-vid avyaṅgo vedāṅgo veda-vit kaviḥ",
    conceptIds: ["vs-nama-123", "vs-nama-124", "vs-nama-125", "vs-nama-126", "vs-nama-127", "vs-nama-128", "vs-nama-129", "vs-nama-130", "vs-nama-131", "vs-nama-132"],
    translation: "Everywhere-going; all-knowing radiance; He whose army faces all quarters; churner of men; the Veda; knower of the Veda; flawless; limb of the Veda; reflector on the Veda; the seer-poet.",
    commentary: "Knowing collapses into being known: He is the Veda, its knower, its limb and its reflective reader — scripture studying itself through us. Viṣvaksena's armies face every direction because protection has no blind side; Janārdana churns men the way curds are churned, to bring the butter up. Read one verse as His self-reading.",
    keyPoints: ["Names 123–132: Sarvagaḥ — Kaviḥ.", "Veda, vedavit, vedāṅga: scripture entire.", "Kavi: the seer who makes, not only sees."],
  },
  {
    id: "vs-015",
    number: "Stotra 15 (names 133–140)",
    section: "Stotra · The fourfold and the hidden",
    iast: "lokādhyakṣaḥ surādhyakṣo dharmādhyakṣaḥ kṛtākṛtaḥ । catur-ātmā catur-vyūhaś catur-daṃṣṭraś catur-bhujaḥ",
    conceptIds: ["vs-nama-133", "vs-nama-134", "vs-nama-135", "vs-nama-136", "vs-nama-137", "vs-nama-138", "vs-nama-139", "vs-nama-140"],
    translation: "Overseer of worlds; overseer of gods; overseer of dharma; both the made and unmade; four-souled; fourfold in manifestation; four-tusked; four-armed.",
    commentary: "Oversight triples — worlds, gods, dharma — then folds into fours: the vyūha doctrine of four divine emanations, four arms holding conch, discus, mace and lotus. Kṛtākṛta holds effect and cause together so that providence covers both what happens and what merely could. Count four breaths as His four arms around you.",
    keyPoints: ["Names 133–140: Lokādhyakṣaḥ — Caturbhujaḥ.", "Three overseerships, one overseer.", "Caturvyūha: emanation without division."],
  },
  {
    id: "vs-016",
    number: "Stotra 16 (names 141–150)",
    section: "Stotra · The fourfold and the hidden",
    iast: "bhrājiṣṇur bhojanaṃ bhoktā sahiṣṇur jagad-ādijaḥ । anagho vijayo jetā viśva-yoniḥ punar-vasuḥ",
    conceptIds: ["vs-nama-141", "vs-nama-142", "vs-nama-143", "vs-nama-144", "vs-nama-145", "vs-nama-146", "vs-nama-147", "vs-nama-148", "vs-nama-149", "vs-nama-150"],
    translation: "The radiant; the food; the eater; the forbearing; born before the world; sinless; victory; the conqueror; womb of the universe; dweller-again.",
    commentary: "Eater and eaten are one: bhojana and bhoktā name the cosmos as His meal and Himself as its enjoyer, with forbearance (sahiṣṇu) as the digestive fire. Victory needs no enemy — anagha conquers by sinlessness, and punarvasu returns each dawn to dwell again in the renewed world. Eat one meal aware of being eaten and eating.",
    keyPoints: ["Names 141–150: Bhrājiṣṇuḥ — Punarvasuḥ.", "Bhojana/bhoktā: food and eater reconciled.", "Punarvasu: the daily return of grace."],
  },
  {
    id: "vs-017",
    number: "Stotra 17 (names 151–162)",
    section: "Stotra · The fourfold and the hidden",
    iast: "upendro vāmanaḥ prāṃśur amoghaḥ śucir ūrjitaḥ । atīndraḥ saṃgrahaḥ sargo dhṛtātmā niyamo yamaḥ",
    conceptIds: ["vs-nama-151", "vs-nama-152", "vs-nama-153", "vs-nama-154", "vs-nama-155", "vs-nama-156", "vs-nama-157", "vs-nama-158", "vs-nama-159", "vs-nama-160", "vs-nama-161", "vs-nama-162"],
    translation: "Indra's younger brother; the dwarf; the tall; unfailing; the pure; the exalted; beyond Indra; the holder-together; creation; self-possessed; restraint; the controller.",
    commentary: "The dwarf who became the Tall (Vāmana–Trivikrama) teaches scale: smallness assumed, cosmos covered in three steps. Holding-together (saṃgraha) precedes creation (sarga) because unity comes before multiplicity, and restraint (niyama) matures into control (yama). Grow tall inwardly while staying small outwardly.",
    keyPoints: ["Names 151–162: Upendraḥ — Yamaḥ.", "Vāmana: littleness as strategy of grace.", "Saṃgraha before sarga: union before number."],
  },
  {
    id: "vs-018",
    number: "Stotra 18 (names 163–172)",
    section: "Stotra · The fourfold and the hidden",
    iast: "vedyo vaidyaḥ sadā-yogī vīrahā mādhavo madhuḥ । atīndriyo mahā-māyo mahotsāho mahā-balaḥ",
    conceptIds: ["vs-nama-163", "vs-nama-164", "vs-nama-165", "vs-nama-166", "vs-nama-167", "vs-nama-168", "vs-nama-169", "vs-nama-170", "vs-nama-171", "vs-nama-172"],
    translation: "The knowable; the knower of wisdom; ever-yoked; slayer of heroes (of evil); Mādhava; honey; beyond the senses; wielder of great illusion; greatly enthusiastic; greatly strong.",
    commentary: "Knowable (vedya) yet beyond senses (atīndriya): He is found by knowing, not by grasping. Honey (madhu) sweetens the slaying (vīrahā) — even destruction serves nourishment — and great illusion (mahāmāyā) is wielded, never suffered. Enthusiasm (mahotsāha) is listed as strength: zeal itself is power. Taste one duty as honey today.",
    keyPoints: ["Names 163–172: Vedyaḥ — Mahābalaḥ.", "Vedya yet atīndriya: known, never caught.", "Mahāmāyā wielded, not undergone."],
  },
  {
    id: "vs-019",
    number: "Stotra 19 (names 173–180)",
    section: "Stotra · The fourfold and the hidden",
    iast: "mahā-buddhir mahā-vīryo mahā-śaktir mahā-dyutiḥ । anirdeśya-vapuḥ śrīmān ameyātmā mahādri-dhṛk",
    conceptIds: ["vs-nama-173", "vs-nama-174", "vs-nama-175", "vs-nama-176", "vs-nama-177", "vs-nama-178", "vs-nama-179", "vs-nama-180"],
    translation: "Great in wisdom; great in valour; great in power; great in splendour; of indescribable form; glorious; of immeasurable self; lifter of the great mountain.",
    commentary: "Four greatnesses (wisdom, valour, power, splendour) converge on a form words cannot pin (anirdeśyavapuḥ) — magnitude inverting into mystery. Then the mountain-lifting (Govardhana) proves indescribable does not mean inactive. When description fails, switch to lifting: do the impossible chore.",
    keyPoints: ["Names 173–180: Mahābuddhiḥ — Mahādridhṛk.", "Four mahās crowned by indescribability.", "Govardhana: mystery that lifts mountains."],
  },
  {
    id: "vs-020",
    number: "Stotra 20 (names 181–188)",
    section: "Stotra · The fourfold and the hidden",
    iast: "maheṣvāso mahī-bhartā śrī-nivāsaḥ satāṃ gatiḥ । aniruddhaḥ surānando govindo govindāṃ-patiḥ",
    conceptIds: ["vs-nama-181", "vs-nama-182", "vs-nama-183", "vs-nama-184", "vs-nama-185", "vs-nama-186", "vs-nama-187", "vs-nama-188"],
    translation: "Wielder of the great bow; bearer of the earth; abode of Śrī; goal of the good; unobstructed; bliss of the gods; cowherd; lord of the wise.",
    commentary: "The warrior's bow and the cowherd's flute share one hand: earth borne up (mahībhartā) and gods delighted (surānanda) by the same Lord who is the good men's destination. Unobstructed (aniruddha) means no karma dams His flow toward devotees. Aim one action like an arrow, then tend one creature gently.",
    keyPoints: ["Names 181–188: Maheṣvāsaḥ — Govidāmpatiḥ.", "Bow and cowherd: one hand, two instruments.", "Satāṃ gatiḥ: goodness has a destination."],
  },
  {
    id: "vs-021",
    number: "Stotra 21 (names 189–197)",
    section: "Stotra · Light, lion and teacher",
    iast: "marīcirdamano haṃsaḥ suparṇo bhuja-gottamaḥ । hiraṇya-nābhaḥ sutapāḥ padma-nābhaḥ prajā-patiḥ",
    conceptIds: ["vs-nama-189", "vs-nama-190", "vs-nama-191", "vs-nama-192", "vs-nama-193", "vs-nama-194", "vs-nama-195", "vs-nama-196", "vs-nama-197"],
    translation: "Ray of light; the subduer; the swan; fair-winged; best of serpents; golden-navelled; of great austerity; lotus-navelled; lord of creatures.",
    commentary: "Light takes winged forms: ray, swan (the soul that separates milk from water), fair-winged Garuḍa, and even serpent-best — every vehicle of sky and underworld yoked to Him. Austerity (sutapas) is His, yet its fruit is a navel-lotus that creates. Discriminate once today like the swan: keep the milk, leave the water.",
    keyPoints: ["Names 189–197: Marīciḥ — Prajāpatiḥ.", "Swan-discrimination amid serpent company.", "Padmanābha again: creation re-blooming."],
  },
  {
    id: "vs-022",
    number: "Stotra 22 (names 198–208)",
    section: "Stotra · Light, lion and teacher",
    iast: "amṛtyuḥ sarva-dṛk siṃhaḥ sandhātā sandhimān sthiraḥ । ajo durmarṣaṇaḥ śāstā viśrutātmā surārihā",
    conceptIds: ["vs-nama-198", "vs-nama-199", "vs-nama-200", "vs-nama-201", "vs-nama-202", "vs-nama-203", "vs-nama-204", "vs-nama-205", "vs-nama-206", "vs-nama-207", "vs-nama-208"],
    translation: "Deathless; all-seeing; the lion; the joiner; the joined; the firm; the unborn; the irresistible; the ruler; famed in the Vedas; slayer of foes of gods.",
    commentary: "The lion (siṃha, Narasiṃha remembered) joins (sandhātā) what fear splits: He is both the joint and the joined, firmness that reconciles. Unborn yet ruler, irresistible yet Veda-famed — power legitimated by scripture and mercy. Join two estranged parties, or two halves of yourself.",
    keyPoints: ["Names 198–208: Amṛtyuḥ — Surārihā.", "Sandhātā/sandhimān: joint and joined.", "Lion-power bound to Veda-fame."],
  },
  {
    id: "vs-023",
    number: "Stotra 23 (names 209–217)",
    section: "Stotra · Light, lion and teacher",
    iast: "gurur gurutamo dhāma satyaḥ satya-parākramaḥ । nimiṣo 'nimiṣaḥ sragvī vācas-patir-udāra-dhīḥ",
    conceptIds: ["vs-nama-209", "vs-nama-210", "vs-nama-211", "vs-nama-212", "vs-nama-213", "vs-nama-214", "vs-nama-215", "vs-nama-216", "vs-nama-217"],
    translation: "The teacher; the greatest teacher; the abode; truth; truly valorous; the winking; the unwinking; garlanded; lord of speech with noble mind.",
    commentary: "Teaching peaks here: guru of gurus, abode where lessons lodge, truth whose valour never bluffs. He winks (nimiṣa, time blinking through creatures) yet never winks (animiṣa, the gods' sleepless gaze) — temporality and eternity worn together, garlanded. Speech (vācaspati) flows from nobility of mind, never from cunning. Teach one thing truly today.",
    keyPoints: ["Names 209–217: Guruḥ — Vācaspati-udāradhīḥ.", "Nimiṣa/animiṣa: blinking time, sleepless Lord.", "Garlanded teacher: learning as festival."],
  },
  {
    id: "vs-024",
    number: "Stotra 24 (names 218–227)",
    section: "Stotra · Light, lion and teacher",
    iast: "agraṇīr grāmaṇīḥ śrīmān nyāyo netā samīraṇaḥ । sahasra-mūrdhā viśvātmā sahasrākṣaḥ sahasra-pāt",
    conceptIds: ["vs-nama-218", "vs-nama-219", "vs-nama-220", "vs-nama-221", "vs-nama-222", "vs-nama-223", "vs-nama-224", "vs-nama-225", "vs-nama-226", "vs-nama-227"],
    translation: "The foremost guide; leader of hosts; glorious; justice; the leader; the wind; thousand-headed; soul of the universe; thousand-eyed; thousand-footed.",
    commentary: "Leadership descends from guide (agraṇī) to host-leader (grāmaṇī) to wind (samīraṇa) that moves unseen, then explodes into the cosmic Person of a thousand heads, eyes and feet. Justice (nyāya) is sandwiched between glories: fairness is splendour, not machinery. Follow the foremost guide one step past comfort.",
    keyPoints: ["Names 218–227: Agraṇīḥ — Sahasrapāt.", "Puruṣa-sūkta cosmos in four names.", "Nyāya as glory, not procedure."],
  },
  {
    id: "vs-025",
    number: "Stotra 25 (names 228–235)",
    section: "Stotra · The turning wheel",
    iast: "āvartano nivṛttātmā saṃvṛtaḥ sampra-mardanaḥ । ahaḥ-saṃvartako vahnir anilo dharaṇī-dharaḥ",
    conceptIds: ["vs-nama-228", "vs-nama-229", "vs-nama-230", "vs-nama-231", "vs-nama-232", "vs-nama-233", "vs-nama-234", "vs-nama-235"],
    translation: "The turner; the withdrawn self; the concealed; the crusher; turner of day; fire; wind; bearer of earth.",
    commentary: "He turns (āvartana) the wheel of becoming while standing withdrawn (nivṛttātmā) and concealed (saṃvṛta) within it — transcendence operating the machine it never gets caught in. Day-turner, fire and wind are His levers; earth-bearing His patience. Crushing (sampramardana) is maintenance, not malice: weeds pulled so crops breathe. Let one old pattern be crushed.",
    keyPoints: ["Names 228–235: Āvartanaḥ — Dharaṇīdharaḥ.", "Turner yet withdrawn: action without capture.", "Fire, wind, earth: elements as levers."],
  },
  {
    id: "vs-026",
    number: "Stotra 26 (names 236–246)",
    section: "Stotra · The turning wheel",
    iast: "suprasādaḥ prasannātmā viśva-dhṛg viśva-bhug vibhuḥ । sat-kartā sat-kṛtaḥ sādhuḥ jahnuḥ nārāyaṇo naraḥ",
    conceptIds: ["vs-nama-236", "vs-nama-237", "vs-nama-238", "vs-nama-239", "vs-nama-240", "vs-nama-241", "vs-nama-242", "vs-nama-243", "vs-nama-244", "vs-nama-245", "vs-nama-246"],
    translation: "Most gracious; serene-souled; supporter of the universe; enjoyer of the universe; the pervader; honourer of the good; honoured by the good; the righteous; leader (Jahnu); Nārāyaṇa; man.",
    commentary: "Grace (suprasāda) opens and honour circulates: He honours the good (satkartā) and is honoured by them (satkṛtaḥ) — devotion as mutual garlanding. Nārāyaṇa, waters' abode, closes into nara, man: the cosmic ends in the human, authorizing human birth as His address. Honour one good person concretely today.",
    keyPoints: ["Names 236–246: Suprasādaḥ — Naraḥ.", "Satkartā/satkṛtaḥ: honour circulating.", "Nārāyaṇa into nara: cosmos in man."],
  },
  {
    id: "vs-027",
    number: "Stotra 27 (names 247–255)",
    section: "Stotra · The turning wheel",
    iast: "asaṅkhyeyo 'prameyātmā viśiṣṭaḥ śiṣṭa-kṛc chuciḥ । siddhārthaḥ siddha-saṅkalpaḥ siddhi-daḥ siddhi-sādhanaḥ",
    conceptIds: ["vs-nama-247", "vs-nama-248", "vs-nama-249", "vs-nama-250", "vs-nama-251", "vs-nama-252", "vs-nama-253", "vs-nama-254", "vs-nama-255"],
    translation: "Numberless; of unknowable self; the distinguished; maker of law; the pure; whose aims are accomplished; whose resolves succeed; giver of success; means of success.",
    commentary: "Numberlessness (asaṅkhyeya) founds law (śiṣṭakṛt): because He exceeds count, His ordinances bind every counter. Resolve, gift and means of success are all claimed — prayer's whole economy in four names — yet purity (śuci) keeps grace from becoming favouritism. Resolve one good aim and take the first step.",
    keyPoints: ["Names 247–255: Asaṅkhyeyaḥ — Siddhisādhanaḥ.", "Siddhi given and siddhi as means.", "Law from numberlessness: boundless, yet binding."],
  },
  {
    id: "vs-028",
    number: "Stotra 28 (names 256–264)",
    section: "Stotra · The turning wheel",
    iast: "vṛṣāhī vṛṣabho viṣṇur vṛṣa-parvā vṛṣodaraḥ । vardhano vardhamānaś ca viviktaḥ śruti-sāgaraḥ",
    conceptIds: ["vs-nama-256", "vs-nama-257", "vs-nama-258", "vs-nama-259", "vs-nama-260", "vs-nama-261", "vs-nama-262", "vs-nama-263", "vs-nama-264"],
    translation: "Imbiber of dharma's rain; bull of dharma; Viṣṇu; ladder of dharma; womb of dharma; the increaser; the ever-growing; the apart; ocean of scripture.",
    commentary: "Five vṛṣa-names chant dharma as rain, bull, ladder and womb — righteousness as climate, beast of burden, ascent and gestation at once. Growth (vardhana/vardhamāna) pairs with apartness (vivikta): He expands without entangling, and scripture's ocean never overflows its shore. Climb one rung of the dharma-ladder deliberately.",
    keyPoints: ["Names 256–264: Vṛṣāhī — Śrutisāgaraḥ.", "Vṛṣa five ways: dharma as weather and beast.", "Growth with apartness: expand, don't tangle."],
  },
  {
    id: "vs-029",
    number: "Stotra 29 (names 265–274)",
    section: "Stotra · The turning wheel",
    iast: "subhujo durdharo vāgmī mahendro vasudo vasuḥ । naika-rūpo bṛhad-rūpaḥ śipi-viṣṭaḥ prakāśanaḥ",
    conceptIds: ["vs-nama-265", "vs-nama-266", "vs-nama-267", "vs-nama-268", "vs-nama-269", "vs-nama-270", "vs-nama-271", "vs-nama-272", "vs-nama-273", "vs-nama-274"],
    translation: "Fair-armed; hard to hold; eloquent; great Indra; giver of wealth; wealth itself; of many forms; of vast form; pervader of rays; the revealer.",
    commentary: "Arms fair yet hard to hold (durdhar): grace is shapely but never seizable. Speech (vāgmī) is His weapon beside wealth-giving — eloquence that enriches — and many forms (naikarūpa) resolve into vastness (bṛhadrūpa), multiplicity into magnitude. Speak one true sentence beautifully today.",
    keyPoints: ["Names 265–274: Subhujaḥ — Prakāśanaḥ.", "Fair-armed yet hard to hold.", "Many forms resolving into vast form."],
  },
  {
    id: "vs-030",
    number: "Stotra 30 (names 275–282)",
    section: "Stotra · Fire, sun and sacrifice",
    iast: "ojas-tejo-dyuti-dharaḥ prakāśātmā pratāpanaḥ । ṛddhaḥ spaṣṭākṣaro mantraś candrāṃśur bhāskara-dyutiḥ",
    conceptIds: ["vs-nama-275", "vs-nama-276", "vs-nama-277", "vs-nama-278", "vs-nama-279", "vs-nama-280", "vs-nama-281", "vs-nama-282"],
    translation: "Bearer of vigour, brilliance and splendour; luminous self; the scorcher; the prosperous; clear-syllabled; the sacred formula; moon-rayed; sun-splendoured.",
    commentary: "Light graduates from vigour (ojas) to brilliance (tejas) to splendour (dyuti), then condenses into clear syllables (spaṣṭākṣara) and mantra — radiance you can pronounce. Moon-ray cools what sun-splendour kindles; scorching (pratāpana) is ripening, not cruelty. Chant one mantra slowly, tasting each syllable.",
    keyPoints: ["Names 275–282: Ojastejodyutidharaḥ — Bhāskaradyutiḥ.", "Radiance condensing into pronounceable mantra.", "Moon cooling, sun kindling: both His."],
  },
  {
    id: "vs-031",
    number: "Stotra 31 (names 283–289)",
    section: "Stotra · Fire, sun and sacrifice",
    iast: "amṛtāṃśūdbhavo bhānuḥ śaśa-binduḥ sureśvaraḥ । auṣadhaṃ jagataḥ setuḥ satya-dharma-parākramaḥ",
    conceptIds: ["vs-nama-283", "vs-nama-284", "vs-nama-285", "vs-nama-286", "vs-nama-287", "vs-nama-288", "vs-nama-289"],
    translation: "Born of the nectar-rayed moon; the sun; moon-marked; lord of gods; medicine of the world; bridge; truly valorous in dharma.",
    commentary: "He rises from moon-nectar yet shines as sun (bhānu): coolness gestating heat. Medicine (auṣadha) and bridge (setu) name the two salvations — healing what is sick, spanning what is sundered — sealed by valour that never deserts dharma. Be someone's bridge across one small gulf today.",
    keyPoints: ["Names 283–289: Amṛtāṃśūdbhavaḥ — Satyadharmaparākramaḥ.", "Moon-born sun: coolness gestating heat.", "Medicine and bridge: two salvations."],
  },
  {
    id: "vs-032",
    number: "Stotra 32 (names 290–299)",
    section: "Stotra · Fire, sun and sacrifice",
    iast: "bhūta-bhavya-bhavan-nāthaḥ pavanaḥ pāvano 'nalaḥ । kāmahā kāmaka-kāntaḥ kāmaḥ kāma-pradaḥ prabhuḥ",
    conceptIds: ["vs-nama-290", "vs-nama-291", "vs-nama-292", "vs-nama-293", "vs-nama-294", "vs-nama-295", "vs-nama-296", "vs-nama-297", "vs-nama-298", "vs-nama-299"],
    translation: "Lord of beings past, future and becoming; the wind; the purifier; fire; destroyer of desire; maker of desire; beloved; desire itself; giver of desire; the Lord.",
    commentary: "Desire is handled five ways in one breath: destroyed, made, beloved, embodied and granted — renunciation and fulfilment held by one Lord (prabhu). Wind (pavana) and fire (anala) purify by motion and flame; the three-times Lord oversees wanting itself. Examine one desire: is it to be destroyed, made, or granted?",
    keyPoints: ["Names 290–299: Bhūtabhavyabhavannāthaḥ — Prabhuḥ.", "Kāma five ways: a complete psychology.", "Wind and fire: purification by motion, flame."],
  },
  {
    id: "vs-033",
    number: "Stotra 33 (names 300–307)",
    section: "Stotra · Fire, sun and sacrifice",
    iast: "yugādi-kṛd yugāvarto naika-māyo mahāśanaḥ । adṛśyo vyakta-rūpaśca sahasra-jid ananta-jit",
    conceptIds: ["vs-nama-300", "vs-nama-301", "vs-nama-302", "vs-nama-303", "vs-nama-304", "vs-nama-305", "vs-nama-306", "vs-nama-307"],
    translation: "Maker of yugas' dawns; turner of yugas; wielder of manifold illusion; the great devourer; the unseen; of manifest form; conqueror of thousands; conqueror of the endless.",
    commentary: "He starts the ages, turns them, eats them (mahāśana, time devouring all) — and stays unseen (adṛśya) while wearing manifest form (vyaktarūpa). Illusion (māyā) is wielded manifoldly, never suffered singly; conquest scales from thousands to the endless. Face one ending as His turning, not your failure.",
    keyPoints: ["Names 300–307: Yugādikṛt — Anantajit.", "Adṛśya yet vyaktarūpa: hidden in display.", "Ages started, turned, devoured: time's master."],
  },
  {
    id: "vs-034",
    number: "Stotra 34 (names 308–317)",
    section: "Stotra · Fire, sun and sacrifice",
    iast: "iṣṭo 'viśiṣṭaḥ śiṣṭeṣṭaḥ śikhaṇḍī nahuṣo vṛṣaḥ । krodhahā krodha-kṛt-kartā viśva-bāhur mahī-dharaḥ",
    conceptIds: ["vs-nama-308", "vs-nama-309", "vs-nama-310", "vs-nama-311", "vs-nama-312", "vs-nama-313", "vs-nama-314", "vs-nama-315", "vs-nama-316", "vs-nama-317"],
    translation: "The worshipped; the undifferentiated; beloved of the good; peacock-crested; the binder; the bull; destroyer of anger; maker-and-doer concerning anger; universe-armed; bearer of earth.",
    commentary: "Worship (iṣṭa) ripens into belovedness (śiṣṭeṣṭa): ritual becomes affection. Anger is both destroyed and administered (krodhakṛtkartā) — wrath has its maker, measure and master — while peacock crest and universe-arms keep terror beautiful. Hand one anger upward to its maker.",
    keyPoints: ["Names 308–317: Iṣṭaḥ — Mahīdharaḥ.", "Krodhakṛtkartā: anger with a master.", "From worshipped to beloved: ritual ripening."],
  },
  {
    id: "vs-035",
    number: "Stotra 35 (names 318–326)",
    section: "Stotra · Fire, sun and sacrifice",
    iast: "acyutaḥ prathitaḥ prāṇaḥ prāṇado vāsavānujaḥ । apāṃ-nidhir adhiṣṭhānam apramattaḥ pratiṣṭhitaḥ",
    conceptIds: ["vs-nama-318", "vs-nama-319", "vs-nama-320", "vs-nama-321", "vs-nama-322", "vs-nama-323", "vs-nama-324", "vs-nama-325", "vs-nama-326"],
    translation: "The unfailing; the famed; breath; giver of breath; Indra's younger brother; ocean's treasure; the foundation; ever-vigilant; the firmly established.",
    commentary: "The unfailing (acyuta) stoops to be younger brother (vāsavānuja, Vāmana beside Indra) — infallibility expressing as humility. Breath given and breath itself frame vigilance (apramatta): His sleeplessness is our oxygen, His establishment (pratiṣṭhita) our ground. Rest on the foundation instead of building on sand.",
    keyPoints: ["Names 318–326: Acyutaḥ — Pratiṣṭhitaḥ.", "Acyuta as younger brother: might as humility.", "Apāṃnidhi: treasure hidden in waters."],
  },
  {
    id: "vs-036",
    number: "Stotra 36 (names 327–335)",
    section: "Stotra · Lotus, measure and resolve",
    iast: "skandaḥ skanda-dharo dhuryo varado vāyu-vāhanaḥ । vāsudevo bṛhad-bhānur ādi-devaḥ purandaraḥ",
    conceptIds: ["vs-nama-327", "vs-nama-328", "vs-nama-329", "vs-nama-330", "vs-nama-331", "vs-nama-332", "vs-nama-333", "vs-nama-334", "vs-nama-335"],
    translation: "The commander; bearer of the commander; bearer of the yoke; giver of boons; wind-borne; Vāsudeva; vastly radiant; first god; breaker of citadels.",
    commentary: "Command (skanda) and yoke-bearing (dhurya) pair: authority that pulls its weight. Vāsudeva — indweller of all — shines vastly (bṛhadbhānu) yet breaks citadels (purandara): indwelling tenderness with fortress-breaking force. Boons (varada) are given, never sold. Pull one yoke cheerfully as His.",
    keyPoints: ["Names 327–335: Skandaḥ — Purandaraḥ.", "Command paired with yoke-bearing.", "Vāsudeva: indweller who breaks citadels."],
  },
]