// Viṣṇu Sahasranāma — stotra verses 37–72 (names 336–678), English.
// Same provenance and conventions as vs-stotra-a.ts.
export const vsStotraB: any[] = [
  {
    id: "vs-037",
    number: "Stotra 37 (names 336–345)",
    section: "Stotra · Lotus, measure and resolve",
    iast: "aśokas tāraṇas tāraḥ śūraḥ śaurir janeśvaraḥ । anukūlaḥ śatāvartaḥ padmī padma-nibhekṣaṇaḥ",
    conceptIds: ["vs-nama-336", "vs-nama-337", "vs-nama-338", "vs-nama-339", "vs-nama-340", "vs-nama-341", "vs-nama-342", "vs-nama-343", "vs-nama-344", "vs-nama-345"],
    translation: "Sorrowless; the ferryman; the star; the hero; Śūra's son; lord of men; the favourable; hundred-turned; lotus-holder; lotus-petal-eyed.",
    commentary: "Sorrowlessness (aśoka) ferries (tāraṇa) like a star (tāra) guiding night boats: grief removed, passage given, direction shown. Hundred-turned (śatāvarta) means He has met every plight before; lotus eyes see without staining. Steer by the star instead of staring at the waves.",
    keyPoints: ["Names 336–345: Aśokaḥ — Padmanibhekṣaṇaḥ.", "Ferryman, star, hero: rescue in triplicate.", "Śatāvarta: no plight surprises Him."],
  },
  {
    id: "vs-038",
    number: "Stotra 38 (names 346–354)",
    section: "Stotra · Lotus, measure and resolve",
    iast: "padmanābho 'ravindākṣaḥ padma-garbhaḥ śarīra-bhṛt । maharddhir ṛddho vṛddhātmā mahākṣo garuḍa-dhvajaḥ",
    conceptIds: ["vs-nama-346", "vs-nama-347", "vs-nama-348", "vs-nama-349", "vs-nama-350", "vs-nama-351", "vs-nama-352", "vs-nama-353", "vs-nama-354"],
    translation: "Lotus-navelled; lotus-eyed; lotus-wombed; body-bearer; greatly prosperous; grown; ancient-souled; great-eyed; Garuḍa-bannered.",
    commentary: "Three lotuses — navel, eye, womb — make His body a blooming: creation (navel), compassion (eye), gestation (womb). Prosperity (maharddhi) is growth with age (vṛddhātmā), never novelty; Garuḍa's banner carries the Veda's wings into battle. Tend your body as His lotus-pond.",
    keyPoints: ["Names 346–354: Padmanābhaḥ — Garuḍadhvajaḥ.", "Navel, eye, womb: three lotuses.", "Prosperity as ripening, not novelty."],
  },
  {
    id: "vs-039",
    number: "Stotra 39 (names 355–362)",
    section: "Stotra · Lotus, measure and resolve",
    iast: "atulaḥ śarabho bhīmaḥ samaya-jño havir hariḥ । sarva-lakṣaṇa-lakṣaṇyo lakṣmī-vān samiti-ñjayaḥ",
    conceptIds: ["vs-nama-355", "vs-nama-356", "vs-nama-357", "vs-nama-358", "vs-nama-359", "vs-nama-360", "vs-nama-361", "vs-nama-362"],
    translation: "Incomparable; the destroyer (Śarabha); the terrible; knower of occasions; the oblation; the remover; marked by every mark; Lakṣmī's lord; victor in assemblies.",
    commentary: "Incomparable (atula) yet precisely marked (sarvalakṣaṇalakṣaṇya): beyond compare, within recognition — every auspicious mark present, no scale that holds Him. Terror (bhīma) serves occasion-wisdom (samayajña); assemblies (samiti) are won by presence, not debate. Stop comparing; start recognizing marks.",
    keyPoints: ["Names 355–362: Atulaḥ — Samitiñjayaḥ.", "Beyond compare, yet fully marked.", "Victory in assemblies by presence."],
  },
  {
    id: "vs-040",
    number: "Stotra 40 (names 363–372)",
    section: "Stotra · Lotus, measure and resolve",
    iast: "vikṣaro rohito mārgo hetur dāmodaraḥ sahaḥ । mahīdharo mahā-bhāgo vegavān amitāśanaḥ",
    conceptIds: ["vs-nama-363", "vs-nama-364", "vs-nama-365", "vs-nama-366", "vs-nama-367", "vs-nama-368", "vs-nama-369", "vs-nama-370", "vs-nama-371", "vs-nama-372"],
    translation: "Undecaying; the red one; the path; the cause; rope-bellied (Dāmodara); the patient; earth-bearer; greatly fortunate; swift; of endless appetite.",
    commentary: "Dāmodara's rope-mark recalls the mother who bound the boundless: love's rope leaves its trace on omnipotence forever. Path (mārga) and cause (hetu) frame patience (saha): direction, reason and endurance travelling together, swiftly (vegavān) yet never hurried. Let love bind you once without resentment.",
    keyPoints: ["Names 363–372: Vikṣaraḥ — Amitāśanaḥ.", "Dāmodara: omnipotence rope-marked by love.", "Path, cause, patience: travel complete."],
  },
  {
    id: "vs-041",
    number: "Stotra 41 (names 373–383)",
    section: "Stotra · Lotus, measure and resolve",
    iast: "udbhavaḥ kṣobhaṇo devaḥ śrī-garbhaḥ parameśvaraḥ । karaṇaṃ kāraṇaṃ kartā vikartā gahano guhaḥ",
    conceptIds: ["vs-nama-373", "vs-nama-374", "vs-nama-375", "vs-nama-376", "vs-nama-377", "vs-nama-378", "vs-nama-379", "vs-nama-380", "vs-nama-381", "vs-nama-382", "vs-nama-383"],
    translation: "The origin; the churner; the shining; womb of Śrī; supreme Lord; instrument; cause; maker; unmaker; the deep; the cave.",
    commentary: "Causation is anatomized whole: instrument, cause, maker, unmaker — the complete toolkit claimed by one hand, ending in depth (gahana) and cave (guha) where tools dissolve into mystery. Churning (kṣobhaṇa) precedes shining (deva): agitation is creation's method. Enter the cave: sit with one unanswerable.",
    keyPoints: ["Names 373–383: Udbhavaḥ — Guhaḥ.", "Karaṇa/kāraṇa/kartā/vikartā: causation entire.", "Toolkit dissolving into cave-mystery."],
  },
  {
    id: "vs-042",
    number: "Stotra 42 (names 384–393)",
    section: "Stotra · Lotus, measure and resolve",
    iast: "vyavasāyo vyavasthānaḥ saṃsthānaḥ sthāna-do dhruvaḥ । pararddhiḥ parama-spaṣṭas tuṣṭaḥ puṣṭaḥ śubhekṣaṇaḥ",
    conceptIds: ["vs-nama-384", "vs-nama-385", "vs-nama-386", "vs-nama-387", "vs-nama-388", "vs-nama-389", "vs-nama-390", "vs-nama-391", "vs-nama-392", "vs-nama-393"],
    translation: "Resolve; the foundation; the abode; giver of place; the firm; supreme prosperity; supremely clear; content; nourished; of auspicious gaze.",
    commentary: "Resolve (vyavasāya) hardens into foundation, abode, place-giving and firmness: decisions becoming dwellings. Clarity (paramaspaṣṭa) ripens into contentment (tuṣṭa) and nourishment (puṣṭa) — clear seeing feeds, and His gaze (śubhekṣaṇa) feeds auspiciously. Resolve one thing and give it a place.",
    keyPoints: ["Names 384–393: Vyavasāyaḥ — Śubhekṣaṇaḥ.", "Resolve hardening into dwelling.", "Clarity ripening into nourishment."],
  },
  {
    id: "vs-043",
    number: "Stotra 43 (names 394–404)",
    section: "Stotra · Lotus, measure and resolve",
    iast: "rāmo virāmo virajo mārgo neyo nayo 'nayaḥ । vīraḥ śakti-matāṃ śreṣṭho dharmo dharmavid-uttamaḥ",
    conceptIds: ["vs-nama-394", "vs-nama-395", "vs-nama-396", "vs-nama-397", "vs-nama-398", "vs-nama-399", "vs-nama-400", "vs-nama-401", "vs-nama-402", "vs-nama-403", "vs-nama-404"],
    translation: "Rāma; rest; dustless; the path; the led; the leader; the unleaded; the hero; best of the strong; dharma; best knower of dharma.",
    commentary: "Rāma's name opens rest (virāma) and dustlessness (viraja): the prince who steadies and cleanses. Path, led, leader and unleaded map guidance complete — even the unguided are His charge — closing in dharma known perfectly, not merely ruled. Walk one stretch of path without raising dust.",
    keyPoints: ["Names 394–404: Rāmaḥ — Dharmaviduttamaḥ.", "Rāma: delight that steadies and cleanses.", "Led, leader, unleaded: guidance entire."],
  },
  {
    id: "vs-044",
    number: "Stotra 44 (names 405–415)",
    section: "Stotra · Lotus, measure and resolve",
    iast: "vaikuṇṭhaḥ puruṣaḥ prāṇaḥ prāṇadaḥ praṇavaḥ pṛthuḥ । hiraṇya-garbhaḥ śatru-ghno vyāpto vāyur adhokṣajaḥ",
    conceptIds: ["vs-nama-405", "vs-nama-406", "vs-nama-407", "vs-nama-408", "vs-nama-409", "vs-nama-410", "vs-nama-411", "vs-nama-412", "vs-nama-413", "vs-nama-414", "vs-nama-415"],
    translation: "Vaikuṇṭha; the Person; breath; giver of breath; the syllable Om; the vast; golden-wombed; slayer of foes; the pervader; wind; beyond the senses' reach.",
    commentary: "Vaikuṇṭha — the flawless expanse — narrows to breath and Om (praṇava), then widens past sense-reach (adhokṣaja): the whole journey of meditation in eleven names. Foe-slaying (śatrughna) guards vastness (pṛthu) so openness never means exposure. Sound Om once as address, not syllable.",
    keyPoints: ["Names 405–415: Vaikuṇṭhaḥ — Adhokṣajaḥ.", "Expanse narrowing to Om, widening past sense.", "Pṛthu guarded by śatrughna: open, not exposed."],
  },
  {
    id: "vs-045",
    number: "Stotra 45 (names 416–425)",
    section: "Stotra · Season, altar and grace",
    iast: "ṛtuḥ sudarśanaḥ kālaḥ parameṣṭhī parigrahaḥ । ugraḥ saṃvatsaro dakṣo viśrāmo viśva-dakṣiṇaḥ",
    conceptIds: ["vs-nama-416", "vs-nama-417", "vs-nama-418", "vs-nama-419", "vs-nama-420", "vs-nama-421", "vs-nama-422", "vs-nama-423", "vs-nama-424", "vs-nama-425"],
    translation: "The season; fair to see; time; the highest seat; the embracer; the terrible; the year; the deft; rest; skilled toward all.",
    commentary: "Time wears two faces: season's fairness (sudarśana) and terror (ugra), year measured and rest (viśrāma) beyond measure. The highest seat (parameṣṭhī) embraces (parigraha) rather than excludes; skill toward all (viśvadakṣiṇa) means competence with compassion. Keep one season's rhythm as worship.",
    keyPoints: ["Names 416–425: Ṛtuḥ — Viśvadakṣiṇaḥ.", "Fair season and terrible time: both His.", "Highest seat that embraces: height as shelter."],
  },
  {
    id: "vs-046",
    number: "Stotra 46 (names 426–434)",
    section: "Stotra · Season, altar and grace",
    iast: "vistāraḥ sthāvara-sthāṇuḥ pramāṇaṃ bījam-avyayam । artho 'nartho mahā-kośo mahā-bhogo mahā-dhanaḥ",
    conceptIds: ["vs-nama-426", "vs-nama-427", "vs-nama-428", "vs-nama-429", "vs-nama-430", "vs-nama-431", "vs-nama-432", "vs-nama-433", "vs-nama-434"],
    translation: "Expanse; the immovable's pillar; the measure; the undecaying seed; purpose; purposelessness; the great treasury; great enjoyment; great wealth.",
    commentary: "Expanse (vistāra) steadies into pillar (sthāvarasthāṇu), then seeds (bīja) what measure (pramāṇa) portions: vastness, stability, germination. Purpose (artha) and its absence (anartha) are both held — even meaningless stretches belong — and treasury, enjoyment and wealth close as abundance with roots. Plant one seed-purpose patiently.",
    keyPoints: ["Names 426–434: Vistāraḥ — Mahādhanaḥ.", "Artha and anartha both held: nothing wasted.", "Bījamavyayam: seed that never decays."],
  },
  {
    id: "vs-047",
    number: "Stotra 47 (names 435–444)",
    section: "Stotra · Season, altar and grace",
    iast: "anirviṇṇaḥ sthaviṣṭho 'bhūr dharma-yūpo mahā-makhaḥ । nakṣatra-nemir nakṣatrī kṣamaḥ kṣāmaḥ samīhanaḥ",
    conceptIds: ["vs-nama-435", "vs-nama-436", "vs-nama-437", "vs-nama-438", "vs-nama-439", "vs-nama-440", "vs-nama-441", "vs-nama-442", "vs-nama-443", "vs-nama-444"],
    translation: "Never dejected; the massive; the unborn; dharma's sacrificial post; the great sacrifice; nave of stars; star-clad; the patient; the thin; the yearner.",
    commentary: "Never-dejected (anirviṇṇa) anchors a verse of contraries: massive yet thin (kṣāma), post yet sacrifice, patient yet yearning (samīhana). The stars wheel on His nave (nakṣatranemi) while He yearns — cosmic stability that still longs for devotees. Yearn once without dejection.",
    keyPoints: ["Names 435–444: Anirviṇṇaḥ — Samīhanaḥ.", "Massive yet thin: contraries reconciled.", "Stars wheeling, Lord yearning: stability that longs."],
  },
  {
    id: "vs-048",
    number: "Stotra 48 (names 445–454)",
    section: "Stotra · Season, altar and grace",
    iast: "yajña ijyo mahejyaśca kratuḥ satraṃ satāṃ gatiḥ । sarva-darśī vimuktātmā sarva-jño jñānam-uttamam",
    conceptIds: ["vs-nama-445", "vs-nama-446", "vs-nama-447", "vs-nama-448", "vs-nama-449", "vs-nama-450", "vs-nama-451", "vs-nama-452", "vs-nama-453", "vs-nama-454"],
    translation: "Sacrifice; the worshipped; the greatly worshipped; the rite; the session; goal of the good; all-seeing; freed-souled; all-knowing; supreme knowledge.",
    commentary: "Sacrifice entire — act, object, rite, session — resolves into knowledge supreme (jñānamuttamam): ritual ripening into wisdom, the Vedic arc in ten names. All-seeing (sarvadarśī) frees rather than spies; the freed-souled (vimuktātmā) is sacrifice's graduate. Offer one act as knowledge, not bargaining.",
    keyPoints: ["Names 445–454: Yajñaḥ — Jñānamuttamam.", "Yajña ripening into jñāna: ritual's arc.", "All-seeing that frees, never spies."],
  },
  {
    id: "vs-049",
    number: "Stotra 49 (names 455–464)",
    section: "Stotra · Season, altar and grace",
    iast: "suvrataḥ sumukhaḥ sūkṣmaḥ sughoṣaḥ sukhadaḥ suhṛt । manoharo jita-krodho vīra-bāhur vidāraṇaḥ",
    conceptIds: ["vs-nama-455", "vs-nama-456", "vs-nama-457", "vs-nama-458", "vs-nama-459", "vs-nama-460", "vs-nama-461", "vs-nama-462", "vs-nama-463", "vs-nama-464"],
    translation: "Fair-vowed; fair-faced; subtle; sweet-voiced; giver of joy; the friend; mind-captivating; anger-conquered; hero-armed; the cleaver.",
    commentary: "Six su- names (fair, sweet, joy-giving) melt into friendship (suhṛt): auspiciousness becoming intimacy. Anger conquered (jitakrodha) arms heroism (vīrabāhu) — strength with its temper mastered — and cleaving (vidāraṇa) cuts knots, not throats. Befriend one person without agenda today.",
    keyPoints: ["Names 455–464: Suvrataḥ — Vidāraṇaḥ.", "Sixfold su-: auspiciousness melting to friendship.", "Anger conquered before arms are used."],
  },
  {
    id: "vs-050",
    number: "Stotra 50 (names 465–474)",
    section: "Stotra · Season, altar and grace",
    iast: "svāpanaḥ svavaśo vyāpī naikātmā naika-karma-kṛt । vatsaro vatsalo vatsī ratna-garbho dhaneśvaraḥ",
    conceptIds: ["vs-nama-465", "vs-nama-466", "vs-nama-467", "vs-nama-468", "vs-nama-469", "vs-nama-470", "vs-nama-471", "vs-nama-472", "vs-nama-473", "vs-nama-474"],
    translation: "The luller to sleep; self-controlled; the pervader; many-souled; doer of many deeds; the calf-year; the tender; calf-possessing; jewel-wombed; lord of wealth.",
    commentary: "He lulls (svāpana) the weary yet stays self-ruled (svavaśa): rest given by One who needs none. Many souls, many deeds — multiplicity administered from unity — softening into calf-tenderness (vatsala), the cowherd's affection in metaphysical dress. Rest once without guilt; tend one small thing.",
    keyPoints: ["Names 465–474: Svāpanaḥ — Dhaneśvaraḥ.", "Luller who needs no sleep: rest as gift.", "Vatsala: metaphysics in cowherd dress."],
  },
  {
    id: "vs-051",
    number: "Stotra 51 (names 475–485)",
    section: "Stotra · Season, altar and grace",
    iast: "dharma-gup dharma-kṛd dharmī sadasat-kṣaram-akṣaram । avijñātā sahasrāṃśur vidhātā kṛta-lakṣaṇaḥ",
    conceptIds: ["vs-nama-475", "vs-nama-476", "vs-nama-477", "vs-nama-478", "vs-nama-479", "vs-nama-480", "vs-nama-481", "vs-nama-482", "vs-nama-483", "vs-nama-484", "vs-nama-485"],
    translation: "Guard of dharma; maker of dharma; dharmic; being and non-being; the perishable; the imperishable; the unrecognized; thousand-rayed; the ordainer; marked with purpose.",
    commentary: "Guarding, making and embodying dharma (dharmagup/kṛt/dharmī) precede the great antitheses — being and non-being, perishable and imperishable — because law outranks logic's pairs. Unrecognized (avijñātā) yet thousand-rayed: hiddenness blazing. Every mark (kṛtalakṣaṇa) on Him is purposeful; read one event as marked.",
    keyPoints: ["Names 475–485: Dharmagup — Kṛtalakṣaṇaḥ.", "Dharma guarding, making, embodying.", "Sat/asat/kṣara/akṣara: antitheses held."],
  },
  {
    id: "vs-052",
    number: "Stotra 52 (names 486–493)",
    section: "Stotra · Lion, king and witness",
    iast: "gabhasti-nemir sattva-sthaḥ siṃho bhūta-maheśvaraḥ । ādi-devo mahā-devo deveśo deva-bhṛd-guruḥ",
    conceptIds: ["vs-nama-486", "vs-nama-487", "vs-nama-488", "vs-nama-489", "vs-nama-490", "vs-nama-491", "vs-nama-492", "vs-nama-493"],
    translation: "Ray-naved; abiding in sattva; the lion; great lord of beings; first god; great god; lord of gods; bearer and teacher of gods.",
    commentary: "Abiding in sattva (sattvastha) yet roaring as lion (siṃha): clarity with teeth. First god, great god, god's lord, god's bearer-and-teacher — hierarchy folding into service, the highest carrying (devabhṛt) and teaching (guru) its own. Stand in sattva once: clear, kind, unafraid.",
    keyPoints: ["Names 486–493: Gabhastinemiḥ — Devabhṛdguruḥ.", "Sattvastha yet siṃha: clarity with teeth.", "Highest rank expressing as bearing, teaching."],
  },
  {
    id: "vs-053",
    number: "Stotra 53 (names 494–502)",
    section: "Stotra · Lion, king and witness",
    iast: "uttaro gopatir goptā jñāna-gamyaḥ purātanaḥ । śarīra-bhūta-bhṛd bhoktā kapīndro bhūri-dakṣiṇaḥ",
    conceptIds: ["vs-nama-494", "vs-nama-495", "vs-nama-496", "vs-nama-497", "vs-nama-498", "vs-nama-499", "vs-nama-500", "vs-nama-501", "vs-nama-502"],
    translation: "The uplifter; cowherd; protector; reached by knowledge; the ancient; bearer of embodied beings; enjoyer; monkey-lord; richly giving.",
    commentary: "Uplifter (uttara) and cowherd (gopati) frame protection (goptā): rescue, tending, guarding. Reached by knowledge (jñānagamya) yet ancient (purātana) — new to each knower, old as time — and monkey-lord (kapīndra, Rāma's ally-form) seals royal power with forest friendship. Protect one dependent creature today.",
    keyPoints: ["Names 494–502: Uttaraḥ — Bhūridakṣiṇaḥ.", "Rescue, tending, guarding: protection triple.", "Kapīndra: royalty in forest friendship."],
  },
  {
    id: "vs-054",
    number: "Stotra 54 (names 503–512)",
    section: "Stotra · Lion, king and witness",
    iast: "somapo 'mṛtapaḥ somaḥ purujit puru-sattamaḥ । vinayo jayaḥ satya-sandho dāśārhaḥ sātvatāṃ-patiḥ",
    conceptIds: ["vs-nama-503", "vs-nama-504", "vs-nama-505", "vs-nama-506", "vs-nama-507", "vs-nama-508", "vs-nama-509", "vs-nama-510", "vs-nama-511", "vs-nama-512"],
    translation: "Drinker of soma; drinker of nectar; the moon; conqueror of many; best of men; humility; victory; true of resolve; worthy of gifts; lord of the Sātvatas.",
    commentary: "Drinking soma and nectar, He is the moon (soma) that feeds gods and minds: intake transmuted into glow. Humility (vinaya) precedes victory (jaya) — lowliness as strategy of conquest — and true resolve (satyasandha) never breaks its given word. Win once by humility, not force.",
    keyPoints: ["Names 503–512: Somapaḥ — Sātvatāmpatiḥ.", "Soma drunk, soma embodied: intake to glow.", "Vinaya before jaya: lowliness conquering."],
  },
  {
    id: "vs-055",
    number: "Stotra 55 (names 513–520)",
    section: "Stotra · Lion, king and witness",
    iast: "jīvo vinayitā sākṣī mukundo 'mita-vikramaḥ । ambho-nidhir anantātmā mahodadhi-śayo 'ntakaḥ",
    conceptIds: ["vs-nama-513", "vs-nama-514", "vs-nama-515", "vs-nama-516", "vs-nama-517", "vs-nama-518", "vs-nama-519", "vs-nama-520"],
    translation: "The living; the humble witness; Mukunda; of boundless stride; ocean; endless self; ocean-recliner; the ender.",
    commentary: "The living (jīva) is named first, then witnessed humbly (vinayitāsākṣī): your own aliveness, watched without pride, is His doorway. Mukunda grants release (mukti) while reclining on waters (mahodadhiśaya) — liberation administered from rest — and ender (antaka) closes what the living began. Watch your breathing once as witness.",
    keyPoints: ["Names 513–520: Jīvaḥ — Antakaḥ.", "Vinayitāsākṣī: humility witnessing.", "Release administered from ocean-rest."],
  },
  {
    id: "vs-056",
    number: "Stotra 56 (names 521–530)",
    section: "Stotra · Lion, king and witness",
    iast: "ajo mahārhaḥ svābhāvyo jitāmitraḥ pramodanaḥ । ānando nandano nandaḥ satya-dharmā trivikramaḥ",
    conceptIds: ["vs-nama-521", "vs-nama-522", "vs-nama-523", "vs-nama-524", "vs-nama-525", "vs-nama-526", "vs-nama-527", "vs-nama-528", "vs-nama-529", "vs-nama-530"],
    translation: "Unborn; greatly worthy; rooted in own nature; conqueror of foes; the delighter; bliss; the gladdener; joy; true-dharmed; triple-strider.",
    commentary: "Unborn (aja) yet greatly worthy (mahārha): worth without origin, honour without beginning. Bliss triples — ānanda, nandana, nanda — being, giving and embodying joy, then strides thrice (trivikrama) to deliver it across worlds. True-dharma (satyadharmā) keeps joy honest. Gladden one person without reason.",
    keyPoints: ["Names 521–530: Ajaḥ — Trivikramaḥ.", "Ānanda/nandana/nanda: joy in triplicate.", "Worth without origin: honour unbegun."],
  },
  {
    id: "vs-057",
    number: "Stotra 57 (names 531–537)",
    section: "Stotra · Lion, king and witness",
    iast: "maharṣiḥ kapilācāryaḥ kṛtajño medinī-patiḥ । tri-padas tridaśādhyakṣo mahā-śṛṅgaḥ kṛtānta-kṛt",
    conceptIds: ["vs-nama-531", "vs-nama-532", "vs-nama-533", "vs-nama-534", "vs-nama-535", "vs-nama-536", "vs-nama-537"],
    translation: "The great seer Kapila; mindful of deeds; lord of earth; triple-stepped; overseer of the thirty gods; greatly horned; maker of the end.",
    commentary: "Kapila the enumerator (Sāṅkhya's father) is claimed as His own: philosophy itself is avatāra. Triple-stepped (tripada) recalls the three strides in cosmic grammar — past, present, future crossed — while earth-lordship (medinīpati) grounds metaphysics in soil. End-making (kṛtāntakṛt) is mercy: stories must close. Count one blessing thrice.",
    keyPoints: ["Names 531–537: Maharṣikapilācāryaḥ — Kṛtāntakṛt.", "Kapila claimed: philosophy as avatāra.", "Kṛtānta: endings as mercy."],
  },
  {
    id: "vs-058",
    number: "Stotra 58 (names 538–546)",
    section: "Stotra · Lion, king and witness",
    iast: "mahā-varāho govindaḥ suṣeṇaḥ kanaka-aṅgadī । guhyo gabhīro gahano guptaś cakra-gadā-dharaḥ",
    conceptIds: ["vs-nama-538", "vs-nama-539", "vs-nama-540", "vs-nama-541", "vs-nama-542", "vs-nama-543", "vs-nama-544", "vs-nama-545", "vs-nama-546"],
    translation: "The great boar; cow-finder; fair-armed; golden-braceleted; the secret; the profound; the deep; the guarded; bearer of discus and mace.",
    commentary: "The boar (mahāvarāha) who dived for drowned earth wears golden bracelets: rescue dressed for festival. Secret, profound, deep, guarded (guhya/gabhīra/gahana/gupta) — hiddenness in four degrees — yet discus and mace are carried openly: mystery armed. Dive once for something drowning.",
    keyPoints: ["Names 538–546: Mahāvarāhaḥ — Cakragadādharaḥ.", "Boar-rescue dressed for festival.", "Hiddenness fourfold, weapons open."],
  },
  {
    id: "vs-059",
    number: "Stotra 59 (names 547–557)",
    section: "Stotra · Dark-blue, gold and peace",
    iast: "vedhāḥ svāṅgo 'jitaḥ kṛṣṇo dṛḍhaḥ saṅkarṣaṇo 'cyutaḥ । varuṇo vāruṇo vṛkṣaḥ puṣkarākṣo mahā-manāḥ",
    conceptIds: ["vs-nama-547", "vs-nama-548", "vs-nama-549", "vs-nama-550", "vs-nama-551", "vs-nama-552", "vs-nama-553", "vs-nama-554", "vs-nama-555", "vs-nama-556", "vs-nama-557"],
    translation: "The ordainer; fair-limbed; unconquered; Kṛṣṇa; the firm; the withdrawer; the unfailing; Varuṇa; Varuṇa's son; the tree; lotus-eyed; great-minded.",
    commentary: "Kṛṣṇa stands centre between unconquered (ajita) and firm (dṛḍha): darkness ringed by invincibility. Withdrawer (saṅkarṣaṇa, Balarāma's plough-force) gathers what Varuṇa's waters and the tree (vṛkṣa, the aśvattha of the Gītā) sustain — harvest after watering. Great-mindedness (mahāmanā) closes: vast thought, lotus gaze. Stand firm once in darkness.",
    keyPoints: ["Names 547–557: Vedhāḥ — Mahāmanāḥ.", "Kṛṣṇa ringed by invincibility.", "Tree, waters, withdrawal: harvest's order."],
  },
  {
    id: "vs-060",
    number: "Stotra 60 (names 558–566)",
    section: "Stotra · Dark-blue, gold and peace",
    iast: "bhagavān bhagahānandī vana-mālī halāyudhaḥ । ādityo jyotir-ādityaḥ sahiṣṇur gati-sattamaḥ",
    conceptIds: ["vs-nama-558", "vs-nama-559", "vs-nama-560", "vs-nama-561", "vs-nama-562", "vs-nama-563", "vs-nama-564", "vs-nama-565", "vs-nama-566"],
    translation: "The glorious; bliss in glory; forest-garlanded; plough-weaponed; the sun; light of lights; the forbearing; the highest course.",
    commentary: "Glory (bhaga) is not hoarded but enjoyed (bhagahānandī): opulence as bliss, not burden. Forest-garland (vanamālā) scents the plough-weapon (halāyudha): wildflowers with the farmer's tool — tenderness tilled. Light of lights (jyotirāditya) outshines the sun it names. Wear one wildflower of joy in work.",
    keyPoints: ["Names 558–566: Bhagavān — Gatisattamaḥ.", "Glory enjoyed, not hoarded.", "Garland with plough: tenderness tilled."],
  },
  {
    id: "vs-061",
    number: "Stotra 61 (names 567–573)",
    section: "Stotra · Dark-blue, gold and peace",
    iast: "sudhanvā khaṇḍa-paraśur dāruṇo draviṇa-pradaḥ । divas-pṛk sarva-dṛg-vyāso vācaspati-rayonijaḥ",
    conceptIds: ["vs-nama-567", "vs-nama-568", "vs-nama-569", "vs-nama-570", "vs-nama-571", "vs-nama-572", "vs-nama-573"],
    translation: "Fair-bowed; axe-wielding (Paraśurāma); the severe; giver of wealth; heaven-touching; all-seeing Vyāsa; lord of speech, womb-unborn.",
    commentary: "Paraśurāma's axe (khaṇḍaparaśu) and Vyāsa's arrangement (sarvadṛgvyāsa) frame severity (dāruṇa) that gives wealth (draviṇaprada): the terrible teacher endowing. Heaven-touching (divaspṛk) yet womb-unborn (ayonija): height without birth. Speech's lord (vācaspati) needs no mother's mouth. Accept one severe teaching as wealth.",
    keyPoints: ["Names 567–573: Sudhanvā — Vācaspatirayonijaḥ.", "Axe and arrangement: severity endowing.", "Unborn, yet lord of all speech."],
  },
  {
    id: "vs-062",
    number: "Stotra 62 (names 574–585)",
    section: "Stotra · Dark-blue, gold and peace",
    iast: "trisāmā sāmagaḥ sāma nirvāṇaṃ bheṣajaṃ bhiṣak । sannyāsa-kṛc chamaḥ śānto niṣṭhā śāntiḥ parāyaṇam",
    conceptIds: ["vs-nama-574", "vs-nama-575", "vs-nama-576", "vs-nama-577", "vs-nama-578", "vs-nama-579", "vs-nama-580", "vs-nama-581", "vs-nama-582", "vs-nama-583", "vs-nama-584", "vs-nama-585"],
    translation: "Chanted in three Sāmans; singer of Sāman; Sāman itself; extinction; medicine; physician; maker of renunciation; calm; peace; establishment; tranquillity; the final goal.",
    commentary: "The longest verse (twelve names) sings Sāman three ways — chanted, singer, song — then heals: extinction (nirvāṇa) of fever, medicine (bheṣaja) and physician (bhiṣak) together. Renunciation made (sannyāsakṛt) settles through calm, peace, establishment, tranquillity into the final goal (parāyaṇa): quitting as arriving. Sing one thing instead of saying it.",
    keyPoints: ["Names 574–585: Trisāmā — Parāyaṇam.", "Chanted, singer, song: music entire.", "Physician with His own medicine."],
  },
  {
    id: "vs-063",
    number: "Stotra 63 (names 586–595)",
    section: "Stotra · Dark-blue, gold and peace",
    iast: "śubhāṅgaḥ śānti-daḥ sraṣṭā kumudaḥ kuvale-śayaḥ । gohito gopatir goptā vṛṣabhākṣo vṛṣa-priyaḥ",
    conceptIds: ["vs-nama-586", "vs-nama-587", "vs-nama-588", "vs-nama-589", "vs-nama-590", "vs-nama-591", "vs-nama-592", "vs-nama-593", "vs-nama-594", "vs-nama-595"],
    translation: "Fair-limbed; giver of peace; creator; lotus-delight; water-lily-dweller; cows' friend; cowherd; protector; bull-eyed; bull-loving.",
    commentary: "Fair limbs (śubhāṅga) give peace (śāntida) before creating (sraṣṭā): beauty first, then making — aesthetics preceding work. Water-dwelling (kuvaleśaya) and cow-tending (gohita/gopati/goptā) root the creator in pond and pasture, not abstraction. Bull-eyed (vṛṣabhākṣa) sees dharma steadily. Beautify one act before doing it.",
    keyPoints: ["Names 586–595: Śubhāṅgaḥ — Vṛṣapriyaḥ.", "Beauty before making: aesthetics first.", "Creator rooted in pond and pasture."],
  },
  {
    id: "vs-064",
    number: "Stotra 64 (names 596–604)",
    section: "Stotra · Dark-blue, gold and peace",
    iast: "anivartī nivṛttātmā saṅkṣeptā kṣema-kṛc chivaḥ । śrī-vatsa-vakṣāḥ śrī-vāsaḥ śrī-patiḥ śrī-matāṃ-varaḥ",
    conceptIds: ["vs-nama-596", "vs-nama-597", "vs-nama-598", "vs-nama-599", "vs-nama-600", "vs-nama-601", "vs-nama-602", "vs-nama-603", "vs-nama-604"],
    translation: "Never retreating; withdrawn-souled; the condenser; maker of safety; the gracious; Śrīvatsa-chested; abode of Śrī; lord of Śrī; best of the glorious.",
    commentary: "Never retreating (anivartī) yet withdrawn-souled (nivṛttātmā): advance without entanglement, engagement without capture. Condensing (saṅkṣeptā) the vast into the Śrīvatsa curl on His chest — infinity wearing a locket — He makes safety (kṣemakṛt) graciously (śiva). Carry infinity in one small locket-act.",
    keyPoints: ["Names 596–604: Anivartī — Śrīmatāṃvaraḥ.", "Advance without entanglement.", "Śrīvatsa: infinity in a locket."],
  },
  {
    id: "vs-065",
    number: "Stotra 65 (names 605–614)",
    section: "Stotra · Dark-blue, gold and peace",
    iast: "śrī-daḥ śrīśaḥ śrī-nivāsaḥ śrī-nidhiḥ śrī-vibhāvanaḥ । śrī-dharaḥ śrī-karaḥ śreyaḥ śrī-mān loka-trayāśrayaḥ",
    conceptIds: ["vs-nama-605", "vs-nama-606", "vs-nama-607", "vs-nama-608", "vs-nama-609", "vs-nama-610", "vs-nama-611", "vs-nama-612", "vs-nama-613", "vs-nama-614"],
    translation: "Giver of Śrī; lord of Śrī; abode of Śrī; treasure of Śrī; manifester of Śrī; bearer of Śrī; maker of Śrī; the highest good; glorious; shelter of three worlds.",
    commentary: "Nine Śrī-names ring every relation — giving, lording, abiding, treasuring, manifesting, bearing, making — then resolve into the highest good (śreyaḥ) and world-shelter: prosperity with every grammar, goodness as its sum. Lakṣmī is not His accessory but His activity. Receive one prosperity as relationship.",
    keyPoints: ["Names 605–614: Śrīdaḥ — Lokatrayāśrayaḥ.", "Śrī in every grammar: prosperity entire.", "Goodness as prosperity's sum."],
  },
  {
    id: "vs-066",
    number: "Stotra 66 (names 615–623)",
    section: "Stotra · Dark-blue, gold and peace",
    iast: "svakṣaḥ svaṅgaḥ śatānando nandir jyotir-gaṇeśvaraḥ । vijitātmā 'vidheyātmā sat-kīrtiś chinna-saṃśayaḥ",
    conceptIds: ["vs-nama-615", "vs-nama-616", "vs-nama-617", "vs-nama-618", "vs-nama-619", "vs-nama-620", "vs-nama-621", "vs-nama-622", "vs-nama-623"],
    translation: "Fair-eyed; fair-limbed; hundred-blissed; joy; lord of luminous hosts; self-conquered; of ungovernable self; truly famed; doubt-severed.",
    commentary: "Fair eyes and limbs flower into hundredfold bliss (śatānanda): beauty maturing into joy. Self-conquered (vijitātmā) yet ungovernable (avidheyātmā) — mastered from within, unmastered from without — with fame (satkīrti) that severs doubt (chinnasaṃśaya) instead of feeding it. Master one impulse from within today.",
    keyPoints: ["Names 615–623: Svakṣaḥ — Chinnasaṃśayaḥ.", "Conquered within, ungovernable without.", "Fame that severs doubt."],
  },
  {
    id: "vs-067",
    number: "Stotra 67 (names 624–632)",
    section: "Stotra · Rise, praise and Brahman",
    iast: "udīrṇaḥ sarvataś-cakṣur anīśaḥ śāśvata-sthiraḥ । bhū-śayo bhūṣaṇo bhūtir viśokaḥ śoka-nāśanaḥ",
    conceptIds: ["vs-nama-624", "vs-nama-625", "vs-nama-626", "vs-nama-627", "vs-nama-628", "vs-nama-629", "vs-nama-630", "vs-nama-631", "vs-nama-632"],
    translation: "The exalted; all-eyed; lordless; eternally firm; earth-recliner; the adorner; prosperity; sorrowless; destroyer of sorrow.",
    commentary: "Exalted (udīrṇa) yet earth-reclining (bhūśaya): height that lies down with the lowly. All-eyed (sarvataścakṣu) with no lord above (anīśa): vision answerable to none, yet spent adorning (bhūṣaṇa) and prospering (bhūti) others. Sorrowlessness overflows into sorrow-destroying. Adorn one plain thing beautifully.",
    keyPoints: ["Names 624–632: Udīrṇaḥ — Śokanāśanaḥ.", "Exalted yet earth-reclining.", "Lordless vision spent on adorning."],
  },
  {
    id: "vs-068",
    number: "Stotra 68 (names 633–641)",
    section: "Stotra · Rise, praise and Brahman",
    iast: "arciṣmān arcitaḥ kumbho viśuddhātmā viśodhanaḥ । aniruddho 'prati-rathaḥ pradyumno 'mita-vikramaḥ",
    conceptIds: ["vs-nama-633", "vs-nama-634", "vs-nama-635", "vs-nama-636", "vs-nama-637", "vs-nama-638", "vs-nama-639", "vs-nama-640", "vs-nama-641"],
    translation: "Radiant; worshipped; the pot (of plenitude); pure-souled; the purifier; unobstructed; matchless-charioted; vastly wealthy; boundlessly striding.",
    commentary: "Radiance (arciṣmān) invites worship (arcita): shining that asks to be honoured. The pot (kumbha) holds plenitude unspilled; purity (viśuddhātmā) purifies (viśodhanaḥ) by contact, not effort. Matchless-charioted (apratiratha, Arjuna's peerless car recalled) strides boundlessly toward devotees. Worship once with plenitude, not lack.",
    keyPoints: ["Names 633–641: Arciṣmān — Amitavikramaḥ.", "Shining that asks to be honoured.", "Purity purifying by contact."],
  },
  {
    id: "vs-069",
    number: "Stotra 69 (names 642–650)",
    section: "Stotra · Rise, praise and Brahman",
    iast: "kāla-neminihā vīraḥ śauriḥ śūra-janeśvaraḥ । tri-lokātmā tri-lokeśaḥ keśavaḥ keśi-hā hariḥ",
    conceptIds: ["vs-nama-642", "vs-nama-643", "vs-nama-644", "vs-nama-645", "vs-nama-646", "vs-nama-647", "vs-nama-648", "vs-nama-649", "vs-nama-650"],
    translation: "Slayer of Kālanemi; the hero; Śūra's son; lord of heroic men; soul of three worlds; lord of three worlds; Keśava; slayer of Keśī; the remover.",
    commentary: "Demon-slaying (Kālanemi, Keśī) alternates with world-soulhood (trilokātmā): destruction serving indwelling. Hero (vīra) among heroic men (śūrajaneśvara) — courage leading courage — and Hari removes (harati) what the slayings loosen. Face one Kālanemi-habit with heroic company.",
    keyPoints: ["Names 642–650: Kālaneminihā — Hariḥ.", "Slaying serving soulhood.", "Hari: removal completing destruction."],
  },
  {
    id: "vs-070",
    number: "Stotra 70 (names 651–660)",
    section: "Stotra · Rise, praise and Brahman",
    iast: "kāma-devaḥ kāma-pālaḥ kāmī kāntaḥ kṛtāgamaḥ । anirdeśya-vapur viṣṇur vīro 'nanto dhanañ-jayaḥ",
    conceptIds: ["vs-nama-651", "vs-nama-652", "vs-nama-653", "vs-nama-654", "vs-nama-655", "vs-nama-656", "vs-nama-657", "vs-nama-658", "vs-nama-659", "vs-nama-660"],
    translation: "God of love; guardian of love; loving; beloved; author of scriptures; of indescribable form; Viṣṇu; hero; endless; winner of wealth.",
    commentary: "Love quadruples — god, guardian, lover, beloved — then scripture (kṛtāgama) authors it: desire legitimated by revelation. Indescribable form (anirdeśyavapu) keeps love from idolizing its object; endlessness (ananta) wins wealth (dhanañjaya) worth having. Love once without describing its object.",
    keyPoints: ["Names 651–660: Kāmadevaḥ — Dhanañjayaḥ.", "Love fourfold, then scriptured.", "Indescribable: love without idols."],
  },
  {
    id: "vs-071",
    number: "Stotra 71 (names 661–670)",
    section: "Stotra · Rise, praise and Brahman",
    iast: "brahmaṇyo brahma-kṛd brahmā brahma brahma-vivardhanaḥ । brahma-vid brāhmaṇo brahmī brahma-jño brāhmaṇa-priyaḥ",
    conceptIds: ["vs-nama-661", "vs-nama-662", "vs-nama-663", "vs-nama-664", "vs-nama-665", "vs-nama-666", "vs-nama-667", "vs-nama-668", "vs-nama-669", "vs-nama-670"],
    translation: "Friend of Brahman; maker of Brahman (Veda); Brahmā; Brahman; increaser of Brahman; knower of Brahman; the Brāhmaṇa; possessed of Brahman; knower of Brahman; lover of Brāhmaṇas.",
    commentary: "Ten brahma-names ring every case: friend, maker, being, increaser, knower, embodiment, possession and love of the sacred — the Absolute declined like a noun through devotion's grammar. Lover of Brāhmaṇas (brāhmaṇapriya) grounds metaphysics in hospitality. Honour one keeper of wisdom concretely.",
    keyPoints: ["Names 661–670: Brahmaṇyaḥ — Brāhmaṇapriyaḥ.", "Brahman declined through devotion's cases.", "Metaphysics grounded in hospitality."],
  },
  {
    id: "vs-072",
    number: "Stotra 72 (names 671–678)",
    section: "Stotra · Rise, praise and Brahman",
    iast: "mahā-kramo mahā-karmā mahā-tejā mahoragaḥ । mahā-kratur mahā-yajvā mahā-yajño mahā-haviḥ",
    conceptIds: ["vs-nama-671", "vs-nama-672", "vs-nama-673", "vs-nama-674", "vs-nama-675", "vs-nama-676", "vs-nama-677", "vs-nama-678"],
    translation: "Great-striding; great-acting; greatly radiant; the great serpent; the great rite; great sacrificer; the great sacrifice; the great oblation.",
    commentary: "Eight mahās march stride, act, radiance, serpent (mahoraga, the cosmic coils), rite, sacrificer, sacrifice, oblation: greatness swallowing the whole sacrifice — agent, act and offering all magnified past measure. Serpent-energy (kuṇḍalinī remembered) coils at ritual's heart. Enlarge one offering past measure.",
    keyPoints: ["Names 671–678: Mahākramaḥ — Mahāhaviḥ.", "Sacrifice swallowed by greatness.", "Agent, act, offering all magnified."],
  },
]