// Viṣṇu Sahasranāma — stotra verses 73–107 (names 679–1000), English.
// Same provenance and conventions as vs-stotra-a.ts.
export const vsStotraC: any[] = [
  {
    id: "vs-073",
    number: "Stotra 73 (names 679–689)",
    section: "Stotra · Rise, praise and Brahman",
    iast: "stavyaḥ stava-priyaḥ stotraṃ stutiḥ stotā raṇa-priyaḥ । pūrṇaḥ pūrayitā puṇyaḥ puṇya-kīrtir anāmayaḥ",
    conceptIds: ["vs-nama-679", "vs-nama-680", "vs-nama-681", "vs-nama-682", "vs-nama-683", "vs-nama-684", "vs-nama-685", "vs-nama-686", "vs-nama-687", "vs-nama-688", "vs-nama-689"],
    translation: "The praiseworthy; lover of praise; the hymn; the praise; the praiser; lover of battle; the full; the fulfiller; the holy; of holy fame; the disease-free.",
    commentary: "Praise quintuples — worthy, lover, hymn, act, praiser — God as the whole economy of worship, then battle-lover (raṇapriya) startles: He relishes the good fight. Full (pūrṇa) fulfilling (pūrayitā), holy (puṇya) famed holy, disease-free (anāmaya) closing as health itself. Praise once as the praiser He indwells.",
    keyPoints: ["Names 679–689: Stavyaḥ — Anāmayaḥ.", "Praise entire: worthy, lover, hymn, act, agent.", "Raṇapriya: He relishes the good fight."],
  },
  {
    id: "vs-074",
    number: "Stotra 74 (names 690–698)",
    section: "Stotra · Rise, praise and Brahman",
    iast: "manojavas tīrtha-karo vasuretā vasu-pradaḥ । vasu-prado vāsudevo vasur vasumanā haviḥ",
    conceptIds: ["vs-nama-690", "vs-nama-691", "vs-nama-692", "vs-nama-693", "vs-nama-694", "vs-nama-695", "vs-nama-696", "vs-nama-697", "vs-nama-698"],
    translation: "Swift as mind; maker of fords; seed of wealth; giver of wealth; giver of wealth; Vāsudeva; wealth; good-minded; the oblation.",
    commentary: "Mind-swift (manojavah) yet ford-making (tīrthakara): speed that builds crossings, haste serving pilgrims. Wealth (vasu) repeats four ways — seed, gift twice-given, being itself — generosity with grammar, closing in oblation (haviḥ): all wealth finally offered. Build one ford for another's crossing.",
    keyPoints: ["Names 690–698: Manojavaḥ — Haviḥ.", "Speed serving pilgrims: haste with fords.", "Vasu fourfold: wealth's grammar."],
  },
  {
    id: "vs-075",
    number: "Stotra 75 (names 699–707)",
    section: "Stotra · Abode, one and many",
    iast: "sadgatiḥ satkṛtiḥ sattā sadbhūtiḥ sat-parāyaṇaḥ । śūraseno yadu-śreṣṭhaḥ sannivāsaḥ suyāmunaḥ",
    conceptIds: ["vs-nama-699", "vs-nama-700", "vs-nama-701", "vs-nama-702", "vs-nama-703", "vs-nama-704", "vs-nama-705", "vs-nama-706", "vs-nama-707"],
    translation: "Good course; good deed; being; good becoming; refuge of the good; Śūrasena's pride; best of Yadus; right-dwelling; Yamunā-dweller.",
    commentary: "Five sat- names (good course, deed, being, becoming, refuge) root goodness in being (sattā) before doing: ontology before ethics. Then Yadu-best (yaduśreṣṭha) and Yamunā-dweller (suyāmuna) localize the good on a riverbank — metaphysics with an address in Vraja. Dwell rightly in one place today.",
    keyPoints: ["Names 699–707: Sadgatiḥ — Suyāmunaḥ.", "Being before doing: ontology first.", "Goodness with a Yamunā address."],
  },
  {
    id: "vs-076",
    number: "Stotra 76 (names 708–716)",
    section: "Stotra · Abode, one and many",
    iast: "bhūtāvāso vāsudevaḥ sarvāsu-nilayo 'nalaḥ । darpahā darpado dṛpto durdharo 'thāparājitaḥ",
    conceptIds: ["vs-nama-708", "vs-nama-709", "vs-nama-710", "vs-nama-711", "vs-nama-712", "vs-nama-713", "vs-nama-714", "vs-nama-715", "vs-nama-716"],
    translation: "Abode of beings; Vāsudeva; nest of all breaths; fire; destroyer of pride; giver of pride; the proud; hard to hold; the undefeated.",
    commentary: "Abode of beings (bhūtāvāsa) yet fire (anala): shelter that burns — safety with an edge. Pride is destroyed (darpahā), given (darpada) and worn (dṛpta): self-regard dismantled, granted and transcended by turns, closing in undefeated (aparājita). Nest one breath in Him today.",
    keyPoints: ["Names 708–716: Bhūtāvāsaḥ — Aparājitaḥ.", "Shelter that burns: safety with edge.", "Pride dismantled, granted, transcended."],
  },
  {
    id: "vs-077",
    number: "Stotra 77 (names 717–724)",
    section: "Stotra · Abode, one and many",
    iast: "viśva-mūrtir mahā-mūrtir dīpta-mūrtir amūrtimān । aneka-mūrtir avyaktaḥ śata-mūrtiḥ śatānanaḥ",
    conceptIds: ["vs-nama-717", "vs-nama-718", "vs-nama-719", "vs-nama-720", "vs-nama-721", "vs-nama-722", "vs-nama-723", "vs-nama-724"],
    translation: "Universe-formed; vastly formed; blazing-formed; the formless; many-formed; the unmanifest; hundred-formed; hundred-faced.",
    commentary: "Form multiplies then cancels: universe, vast, blazing, formless, many, unmanifest, hundred, hundred-faced — the iconography of infinity collapsing into avyakta at the centre like a held breath. Faces (ānana) are for beholding; formlessness for being. Behold one face; rest in the formless.",
    keyPoints: ["Names 717–724: Viśvamūrtiḥ — Śatānanaḥ.", "Forms multiplying into formlessness.", "Avyakta at the centre: held breath."],
  },
  {
    id: "vs-078",
    number: "Stotra 78 (names 725–736)",
    section: "Stotra · Abode, one and many",
    iast: "eko naikaḥ savaḥ kaḥ kiṃ yat tat padam-anuttamam । loka-bandhur loka-nātho mādhavo bhakta-vatsalaḥ",
    conceptIds: ["vs-nama-725", "vs-nama-726", "vs-nama-727", "vs-nama-728", "vs-nama-729", "vs-nama-730", "vs-nama-731", "vs-nama-732", "vs-nama-733", "vs-nama-734", "vs-nama-735", "vs-nama-736"],
    translation: "The one; the many; the sacrificer; who; what; which; that; the peerless state; kinsman of worlds; lord of worlds; Mādhava; tender to devotees.",
    commentary: "The Upaniṣadic pronouns arrive — kaḥ, kiṃ, yat, tat: who, what, which, that — metaphysics as interrogation, the Lord as grammar's mystery (even savaḥ, the pressing of soma, joins). One (eka) and many (naika) reconcile in peerless state (padamanuttamam), closing in devotee-tenderness (bhaktavatsala): speculation ending in love. Ask 'who?' once and listen.",
    keyPoints: ["Names 725–736: Ekaḥ — Bhaktavatsalaḥ.", "Kaḥ/kiṃ/yat/tat: God as grammar's mystery.", "One and many reconciled in tenderness."],
  },
  {
    id: "vs-079",
    number: "Stotra 79 (names 737–746)",
    section: "Stotra · Abode, one and many",
    iast: "suvarṇa-varṇo hemāṅgo varāṅgaś candanāṅgadī । vīrahā viṣamaḥ śūnyo ghṛtāśīr acalaś calaḥ",
    conceptIds: ["vs-nama-737", "vs-nama-738", "vs-nama-739", "vs-nama-740", "vs-nama-741", "vs-nama-742", "vs-nama-743", "vs-nama-744", "vs-nama-745", "vs-nama-746"],
    translation: "Golden-hued; golden-limbed; fair-limbed; sandal-braceleted; slayer of heroes (of evil); the uneven; the void; ghee-aspired; the still; the moving.",
    commentary: "Gold (suvarṇavarṇa/hemāṅga) gives way to void (śūnya): splendour preparing emptiness, fullness authorizing vacuity. Uneven (viṣama) refuses symmetry's idol; still (acala) and moving (cala) close as the final pair — rest and motion one reality. Ghee-aspired (ghṛtāśī) keeps sacrifice cooking. Sit still once, then move well.",
    keyPoints: ["Names 737–746: Suvarṇavarṇaḥ — Calaḥ.", "Gold preparing void: fullness to emptiness.", "Acala and cala: rest and motion one."],
  },
  {
    id: "vs-080",
    number: "Stotra 80 (names 747–756)",
    section: "Stotra · Abode, one and many",
    iast: "amānī mānado mānyo loka-svāmī tri-loka-dhṛk । sumedhā medhajo dhanyaḥ satya-medhā dharādharaḥ",
    conceptIds: ["vs-nama-747", "vs-nama-748", "vs-nama-749", "vs-nama-750", "vs-nama-751", "vs-nama-752", "vs-nama-753", "vs-nama-754", "vs-nama-755", "vs-nama-756"],
    translation: "Without pride; giver of honour; honourable; lord of worlds; bearer of three worlds; fair-minded; mind-born; fortunate; truly wise; bearer of earth.",
    commentary: "Without pride (amānī) yet giving honour (mānada): Humility that honours — egolessness distributing dignity. Mind-born (medhaja) wisdom (sumedhā/satyamedhā) bears worlds (trilokadhṛk) and earth (dharādhara): thought as Atlas. Fortunate (dhanya) is the devotee claimed by such a Lord. Honour one person while claiming nothing.",
    keyPoints: ["Names 747–756: Amānī — Dharādharaḥ.", "Egolessness distributing dignity.", "Thought as Atlas: mind bearing worlds."],
  },
  {
    id: "vs-081",
    number: "Stotra 81 (names 757–764)",
    section: "Stotra · Abode, one and many",
    iast: "tejo-vṛṣo dyuti-dharaḥ sarva-śastra-bhṛtāṃ-varaḥ । pragraho nigraho vyagro naika-śṛṅgo gadāgrajaḥ",
    conceptIds: ["vs-nama-757", "vs-nama-758", "vs-nama-759", "vs-nama-760", "vs-nama-761", "vs-nama-762", "vs-nama-763", "vs-nama-764"],
    translation: "Rainer of radiance; bearer of splendour; best of weapon-bearers; the grasp; the restraint; the intent; many-horned; mace-first.",
    commentary: "Radiance rains (tejovṛṣa): splendour as weather, not possession. Grasp (pragraha) and restraint (nigraha) are His reins on beings — guidance and check as one harness — while many-horned (naikaśṛṅga) keeps omnipotence strange. Mace-first (gadāgraja) leads with the blunt instrument of grace. Accept one restraint as guidance.",
    keyPoints: ["Names 757–764: Tejovṛṣaḥ — Gadāgrajaḥ.", "Splendour as weather, not possession.", "Grasp and restraint: one harness."],
  },
  {
    id: "vs-082",
    number: "Stotra 82 (names 765–772)",
    section: "Stotra · The hard-won and the radiant",
    iast: "catur-mūrtiś catur-bāhuś catur-vyūhaś catur-gatiḥ । catur-ātmā catur-bhāvaś catur-veda-vid ekapāt",
    conceptIds: ["vs-nama-765", "vs-nama-766", "vs-nama-767", "vs-nama-768", "vs-nama-769", "vs-nama-770", "vs-nama-771", "vs-nama-772"],
    translation: "Four-formed; four-armed; four-arrayed; four-coursed; four-souled; four-natured; knower of four Vedas; one-footed.",
    commentary: "Seven fours march — form, arms, arrays, courses, souls, natures, Vedas — then halt at one-footed (ekapāt): multiplicity collapsing to the single support, Aja Ekapād remembered. Knowing four Vedas ends in standing on one foot: learning condensed to poise. Stand on one conviction today.",
    keyPoints: ["Names 765–772: Caturmūrtiḥ — Ekapāt.", "Seven fours halting at one foot.", "Learning condensing to poise."],
  },
  {
    id: "vs-083",
    number: "Stotra 83 (names 773–781)",
    section: "Stotra · The hard-won and the radiant",
    iast: "samāvarto nivṛttātmā durjayo duratikramaḥ । durlabho durgamo durgo durāvāso durārihā",
    conceptIds: ["vs-nama-773", "vs-nama-774", "vs-nama-775", "vs-nama-776", "vs-nama-777", "vs-nama-778", "vs-nama-779", "vs-nama-780", "vs-nama-781"],
    translation: "The revolver; withdrawn-souled; hard to conquer; hard to cross; hard to win; hard to approach; the fort; hard to dwell in; slayer of hard foes.",
    commentary: "Eight dur- names (hard...) confess the path's difficulty honestly — hard to win, approach, inhabit — then answer it: revolver (samāvarta, who turns all back to Himself) slaying hard foes (durārihā). Withdrawn-souled (nivṛttātmā) effortlessness operates hardness. Attempt one hard thing with His hardness.",
    keyPoints: ["Names 773–781: Samāvartaḥ — Durārihā.", "Eight hards confessed honestly.", "Samāvarta: all turns ending in Him."],
  },
  {
    id: "vs-084",
    number: "Stotra 84 (names 782–789)",
    section: "Stotra · The hard-won and the radiant",
    iast: "śubhāṅgo loka-sāraṅgaḥ sutantus tantu-vardhanaḥ । indra-karmā mahā-karmā kṛta-karmā kṛtāgamaḥ",
    conceptIds: ["vs-nama-782", "vs-nama-783", "vs-nama-784", "vs-nama-785", "vs-nama-786", "vs-nama-787", "vs-nama-788", "vs-nama-789"],
    translation: "Fair-limbed; world's essence-doe (beloved); fine-threaded; thread-increaser; Indra-acting; greatly acting; act-accomplishing; scripture-authoring.",
    commentary: "Fair limbs (śubhāṅga) weave fine threads (sutantu) that He then lengthens (tantuvardhana): beauty spinning continuity. World's beloved (lokasāraṅga) acts as Indra, greatly, accomplishedly — action triple-sealed — and authors scripture (kṛtāgama) so deeds become doctrine. Spin one fine thread of work today.",
    keyPoints: ["Names 782–789: Śubhāṅgaḥ — Kṛtāgamaḥ.", "Beauty spinning continuity.", "Deeds becoming doctrine."],
  },
  {
    id: "vs-085",
    number: "Stotra 85 (names 790–799)",
    section: "Stotra · The hard-won and the radiant",
    iast: "udbhavaḥ sundaraḥ sundo ratna-nābhaḥ sulocanaḥ । arko vājasanaḥ śṛṅgī jayantaḥ sarva-vij-jayī",
    conceptIds: ["vs-nama-790", "vs-nama-791", "vs-nama-792", "vs-nama-793", "vs-nama-794", "vs-nama-795", "vs-nama-796", "vs-nama-797", "vs-nama-798", "vs-nama-799"],
    translation: "The origin; the beautiful; the tender; jewel-navelled; fair-eyed; the sun; giver of vigour; the horned; the victorious; all-knowing conqueror.",
    commentary: "Origin (udbhava) flowers into beauty (sundara) and tenderness (sunda): source as loveliness, not machinery. Jewel-navel (ratnanābha) and fair eyes (sulocana) adorn; horned (śṛṅgī, Matsya's horn remembered) steers the flood-boat; all-knowing conquest (sarvavijjayī) wins by wisdom. Originate one beautiful thing.",
    keyPoints: ["Names 790–799: Udbhavaḥ — Sarvavijjayī.", "Source as loveliness, not machinery.", "Śṛṅgī: the horn that steered the flood."],
  },
  {
    id: "vs-086",
    number: "Stotra 86 (names 800–806)",
    section: "Stotra · The hard-won and the radiant",
    iast: "suvarṇa-bindur akṣobhyaḥ sarva-vāgīśvareśvaraḥ । mahā-hrado mahā-garto mahā-bhūto mahā-nidhiḥ",
    conceptIds: ["vs-nama-800", "vs-nama-801", "vs-nama-802", "vs-nama-803", "vs-nama-804", "vs-nama-805", "vs-nama-806"],
    translation: "Golden-dropped; unagitated; lord of lords of speech; the great lake; the great depth; the great being; the great treasure.",
    commentary: "Golden drop (suvarṇabindu) stills into unagitated (akṣobhya): a point of gold calming oceans. Lord of speech-lords (sarvavāgīśvareśvara) rules every tongue's master; lake, depth, being, treasure (mahāhrada/garta/bhūta/nidhi) deepen greatness downward. Settle one agitation into a golden point.",
    keyPoints: ["Names 800–806: Suvarṇabinduḥ — Mahānidhiḥ.", "Golden point calming oceans.", "Greatness deepening downward."],
  },
  {
    id: "vs-087",
    number: "Stotra 87 (names 807–816)",
    section: "Stotra · The hard-won and the radiant",
    iast: "kumudaḥ kundaraḥ kundaḥ parjanyaḥ pāvano 'nilaḥ । amṛtāṃśo 'mṛta-vapuḥ sarva-jñaḥ sarvato-mukhaḥ",
    conceptIds: ["vs-nama-807", "vs-nama-808", "vs-nama-809", "vs-nama-810", "vs-nama-811", "vs-nama-812", "vs-nama-813", "vs-nama-814", "vs-nama-815", "vs-nama-816"],
    translation: "Lotus-joy; earth-cleaver; jasmine-pure; rain-cloud; purifier; wind; nectar-rayed; nectar-bodied; all-knowing; all-faced.",
    commentary: "Earth (kundara, cleaving ground for the plough) softens into jasmine (kunda) and rain (parjanya): hardness flowering, then raining. Purifier-wind (pāvana/anila) moves cleansing; nectar-ray and nectar-body (amṛtāṃśa/amṛtavapu) make immortality both light and flesh. All-faced (sarvatomukha) ends surveillance as welcome. Face all sides with nectar today.",
    keyPoints: ["Names 807–816: Kumudaḥ — Sarvatomukhaḥ.", "Hardness flowering, then raining.", "Nectar as light and flesh."],
  },
  {
    id: "vs-088",
    number: "Stotra 88 (names 817–825)",
    section: "Stotra · The hard-won and the radiant",
    iast: "sulabhaḥ suvrataḥ siddhaḥ śatru-jic chatru-tāpanaḥ । nyagrodho 'dumbaro 'śvatthaś cāṇūrāndhra-niṣūdanaḥ",
    conceptIds: ["vs-nama-817", "vs-nama-818", "vs-nama-819", "vs-nama-820", "vs-nama-821", "vs-nama-822", "vs-nama-823", "vs-nama-824", "vs-nama-825"],
    translation: "Easily won; fair-vowed; perfect; foe-conquering; foe-scorching; banyan; fig; pipal; slayer of Cāṇūra.",
    commentary: "Easily won (sulabha) though foe-scorching (śatrutāpana): gentleness to friends, fire to foes — accessibility with an edge. Three trees (nyagrodha/udumbara/aśvattha) root Him in village shade and Gītā's cosmic tree; Cāṇūra's slaying (Kṛṣṇa's wrestling recalled) proves play can kill tyranny. Rest in His shade; wrestle one tyranny.",
    keyPoints: ["Names 817–825: Sulabhaḥ — Cāṇūrāndhraniṣūdanaḥ.", "Easily won, yet foe-scorching.", "Three trees: village shade, cosmic roots."],
  },
  {
    id: "vs-089",
    number: "Stotra 89 (names 826–834)",
    section: "Stotra · The hard-won and the radiant",
    iast: "sahasrārciḥ sapta-jihvaḥ saptaidhāḥ sapta-vāhanaḥ । amūrtir anagho 'cintyo bhaya-kṛd bhaya-nāśanaḥ",
    conceptIds: ["vs-nama-826", "vs-nama-827", "vs-nama-828", "vs-nama-829", "vs-nama-830", "vs-nama-831", "vs-nama-832", "vs-nama-833", "vs-nama-834"],
    translation: "Thousand-rayed; seven-tongued; seven-f flamed; seven-horsed; formless; sinless; inconceivable; fear-maker; fear-destroyer.",
    commentary: "Fire septuples — rays, tongues, flames, horses (Agni's equipage) — then form dissolves (amūrti) into inconceivable (acintya): ritual fire opening onto mystery. Fear made (bhayakṛt) for the wicked, destroyed (bhayanāśana) for devotees: one energy, two addresses. Offer one fear to be destroyed.",
    keyPoints: ["Names 826–834: Sahasrārciḥ — Bhayanāśanaḥ.", "Sevenfold fire opening onto formless.", "One energy, two addresses."],
  },
  {
    id: "vs-090",
    number: "Stotra 90 (names 835–846)",
    section: "Stotra · The hard-won and the radiant",
    iast: "aṇur bṛhat kṛśaḥ sthūlo guṇa-bhṛn nirguṇo mahān । adhṛtaḥ sva-dhṛtaḥ svāsyaḥ prāg-vaṃśo vaṃśa-vardhanaḥ",
    conceptIds: ["vs-nama-835", "vs-nama-836", "vs-nama-837", "vs-nama-838", "vs-nama-839", "vs-nama-840", "vs-nama-841", "vs-nama-842", "vs-nama-843", "vs-nama-844", "vs-nama-845", "vs-nama-846"],
    translation: "Atomic; vast; lean; gross; bearer of qualities; qualityless; the great; unsupported; self-supported; fair-faced; first of lineage; lineage-increaser.",
    commentary: "The famous dozen contraries — atomic yet vast, quality-bearing yet qualityless, unsupported yet self-supported — state non-duality as paradox, not proposition. Lean (kṛśa) and gross (sthūla) share one verse as one body; fair-faced (svāsya) keeps paradox beautiful. Lineage (vaṃśa) firsts and increases: tradition lives. Hold one paradox without solving it.",
    keyPoints: ["Names 835–846: Aṇuḥ — Vaṃśavardhanaḥ.", "Twelve contraries: non-duality as paradox.", "Unsupported yet self-supported."],
  },
  {
    id: "vs-091",
    number: "Stotra 91 (names 847–856)",
    section: "Stotra · Bow, sky and wonder",
    iast: "bhāra-bhṛt kathito yogī yogīśaḥ sarva-kāmadaḥ । āśramaḥ śramaṇaḥ kṣāmaḥ suparṇo vāyu-vāhanaḥ",
    conceptIds: ["vs-nama-847", "vs-nama-848", "vs-nama-849", "vs-nama-850", "vs-nama-851", "vs-nama-852", "vs-nama-853", "vs-nama-854", "vs-nama-855", "vs-nama-856"],
    translation: "Burden-bearer; the narrated; the yogī; lord of yogīs; granter of all wishes; the hermitage; the ascetic; the thin; fair-winged; wind-borne.",
    commentary: "Burden-bearing (bhārabhṛt) opens: He carries weight before granting wishes (sarvakāmada) — service before largesse. Narrated (kathita, scripture's subject) yet thin (kṣāma, worn by tapas): fame with fasting. Hermitage (āśrama) and ascetic (śramaṇa) root flight (suparṇa/vāyuvāhana) in stillness. Carry one burden; grant one wish.",
    keyPoints: ["Names 847–856: Bhārabhṛt — Vāyuvāhanaḥ.", "Service before largesse.", "Fame with fasting: narrated yet thin."],
  },
  {
    id: "vs-092",
    number: "Stotra 92 (names 857–866)",
    section: "Stotra · Bow, sky and wonder",
    iast: "dhanur-dharo dhanur-vedo daṇḍo damayitā damaḥ । aparājitaḥ sarva-saho niyantā 'niyamo 'yamaḥ",
    conceptIds: ["vs-nama-857", "vs-nama-858", "vs-nama-859", "vs-nama-860", "vs-nama-861", "vs-nama-862", "vs-nama-863", "vs-nama-864", "vs-nama-865", "vs-nama-866"],
    translation: "Bow-bearer; knower of archery; the rod; the subduer; self-mastery; undefeated; all-enduring; the ordainer; rule-free; death-free.",
    commentary: "Bow (dhanurdhara, Rāma) and rod (daṇḍa) frame subduing (damayitā) that ripens into self-mastery (damaḥ): force educated into restraint. All-enduring (sarvasaha) ordains (niyantā) while staying rule-free (aniyama) and death-free (ayama): law's source above law. (Some recensions read niyama/yamaḥ here.) Master one impulse; endure one blow.",
    keyPoints: ["Names 857–866: Dhanurdharaḥ — Ayamaḥ.", "Force educated into self-mastery.", "Law's source above law."],
  },
  {
    id: "vs-093",
    number: "Stotra 93 (names 867–875)",
    section: "Stotra · Bow, sky and wonder",
    iast: "sattva-vān sāttvikaḥ satyaḥ satya-dharma-parāyaṇaḥ । abhiprāyaḥ priyārho 'rhaḥ priya-kṛt prīti-vardhanaḥ",
    conceptIds: ["vs-nama-867", "vs-nama-868", "vs-nama-869", "vs-nama-870", "vs-nama-871", "vs-nama-872", "vs-nama-873", "vs-nama-874", "vs-nama-875"],
    translation: "Full of being; abiding in purity; truth; devoted to truth-dharma; intention; worthy of love; the worthy; doer of loving acts; increaser of joy.",
    commentary: "Being (sattvavān) settles into purity (sāttvika) into truth (satyaḥ): ontology, clarity, veracity ascending. Intention (abhiprāya) is claimed as His — even our purposes are His residence — and love quadruples to joy-increase (prītivardhana): affection's arithmetic. Intend one loving act; watch joy increase.",
    keyPoints: ["Names 867–875: Sattvavān — Prītivardhanaḥ.", "Being, clarity, veracity ascending.", "Intention claimed as His residence."],
  },
  {
    id: "vs-094",
    number: "Stotra 94 (names 876–885)",
    section: "Stotra · Bow, sky and wonder",
    iast: "vihāyasa-gatir jyotiḥ surucir hutabhug vibhuḥ । ravir virocanaḥ sūryaḥ savitā ravi-locanaḥ",
    conceptIds: ["vs-nama-876", "vs-nama-877", "vs-nama-878", "vs-nama-879", "vs-nama-880", "vs-nama-881", "vs-nama-882", "vs-nama-883", "vs-nama-884", "vs-nama-885"],
    translation: "Sky-goer; light; radiant; oblation-eater; the pervader; the sun; the shining; Sūrya; the impeller; sun-eyed.",
    commentary: "Sky-going (vihāyasagati) light (jyotiḥ) eats oblations (hutabhuk): heaven consuming earth's gifts. Six sun-names (ravi/virocana/sūrya/savitā/ravilocana...) blaze differently — drawer-up, shiner, impeller, eye — solar theology complete, closed by pervader (vibhu) lest light localize. Face the sun once as His eye.",
    keyPoints: ["Names 876–885: Vihāyasagatiḥ — Ravilocanaḥ.", "Six suns blazing differently.", "Heaven consuming earth's gifts."],
  },
  {
    id: "vs-095",
    number: "Stotra 95 (names 886–895)",
    section: "Stotra · Bow, sky and wonder",
    iast: "ananto hutabhug bhoktā sukhado naika-jo 'grajaḥ । anirviṇṇaḥ sadā-marṣī lokādhiṣṭhānam adbhutam",
    conceptIds: ["vs-nama-886", "vs-nama-887", "vs-nama-888", "vs-nama-889", "vs-nama-890", "vs-nama-891", "vs-nama-892", "vs-nama-893", "vs-nama-894", "vs-nama-895"],
    translation: "Endless; oblation-eater; enjoyer; joy-giver; repeatedly born; first-born; never dejected; ever-forbearing; world's foundation; the wonderful.",
    commentary: "Endless (ananta) is born again (naikaja) and first-born (agraja): eternity practising beginnings. Eating (hutabhuk/bhoktā) turns into joy-giving (sukhada): consumption transmuted to blessing. Never-dejected (anirviṇṇa) forbearance (sadāmarṣī) props the world (lokādhiṣṭhāna) — patience as cosmology — ending in wonder (adbhutam). Begin once more, unwearied.",
    keyPoints: ["Names 886–895: Anantaḥ — Adbhutam.", "Eternity practising beginnings.", "Patience as cosmology."],
  },
  {
    id: "vs-096",
    number: "Stotra 96 (names 896–905)",
    section: "Stotra · Bow, sky and wonder",
    iast: "sanāt sanātana-tamaḥ kapilaḥ kapir avyayaḥ । svastidaḥ svasti-kṛt svasti svasti-bhuk svasti-dakṣiṇaḥ",
    conceptIds: ["vs-nama-896", "vs-nama-897", "vs-nama-898", "vs-nama-899", "vs-nama-900", "vs-nama-901", "vs-nama-902", "vs-nama-903", "vs-nama-904", "vs-nama-905"],
    translation: "The ancient; most ancient; Kapila; Kapi (sun/monkey); undecaying; giver of blessing; maker of blessing; blessing; enjoyer of blessing; lavish in blessing.",
    commentary: "Ancient (sanāt) unto most-ancient (sanātanatama) — age superlatived — then Kapila the enumerator and Kapi the sun/monkey: wisdom and play in old age. Five svasti-names (blessing given, made, embodied, enjoyed, lavished) turn benediction into economy: welfare administered. Bless someone lavishly today.",
    keyPoints: ["Names 896–905: Sanāt — Svastidakṣiṇaḥ.", "Age superlatived, then playing.", "Blessing as administered economy."],
  },
  {
    id: "vs-097",
    number: "Stotra 97 (names 906–914)",
    section: "Stotra · Bow, sky and wonder",
    iast: "araudraḥ kuṇḍalī cakrī vikramyūrjita-śāsanaḥ । śabdātigaḥ śabda-sahaḥ śiśiraḥ śarvarī-karaḥ",
    conceptIds: ["vs-nama-906", "vs-nama-907", "vs-nama-908", "vs-nama-909", "vs-nama-910", "vs-nama-911", "vs-nama-912", "vs-nama-913", "vs-nama-914"],
    translation: "Never-cruel; earringed; discus-bearing; firm-striding, mighty-commanded; beyond word; word-enduring; the cool; night-maker.",
    commentary: "Never-cruel (araudra) wears earrings (kuṇḍalī) and discus (cakrī): gentleness armed. Stride firm (vikramī), command mighty (ūrjitaśāsana), yet beyond word (śabdātiga) while enduring words (śabdasaha) — transcendence that still listens. Cool (śiśira) night (śarvarīkara) rests what day commanded. Listen once past words.",
    keyPoints: ["Names 906–914: Araudraḥ — Śarvarīkaraḥ.", "Gentleness armed: earrings with discus.", "Beyond word, yet enduring words."],
  },
  {
    id: "vs-098",
    number: "Stotra 98 (names 915–922)",
    section: "Stotra · Crossing and ground",
    iast: "akrūraḥ peśalo dakṣo dakṣiṇaḥ kṣamiṇāṃ-varaḥ । vidvattamo vīta-bhayaḥ puṇya-śravaṇa-kīrtanaḥ",
    conceptIds: ["vs-nama-915", "vs-nama-916", "vs-nama-917", "vs-nama-918", "vs-nama-919", "vs-nama-920", "vs-nama-921", "vs-nama-922"],
    translation: "Never-cruel; gentle; deft; gracious; best of the patient; wisest of the wise; fear-free; whose hearing and praise purify.",
    commentary: "Araudra's gentleness continues as akrūra (Akrūra the devotee recalled): cruelty's absence becoming a person. Deft (dakṣa) and gracious (dakṣiṇa) pair skill with kindness; patience crowned (kṣamiṇāṃvara) flowers into fearlessness (vītabhaya). Hearing-and-praise purifying (puṇyaśravaṇakīrtana) makes this very recitation sacrament. Praise once to be purified.",
    keyPoints: ["Names 915–922: Akrūraḥ — Puṇyaśravaṇakīrtanaḥ.", "Skill paired with kindness.", "Recitation itself as sacrament."],
  },
  {
    id: "vs-099",
    number: "Stotra 99 (names 923–931)",
    section: "Stotra · Crossing and ground",
    iast: "uttāraṇo duṣkṛti-hā puṇyo duḥsvapna-nāśanaḥ । vīrahā rakṣaṇaḥ santo jīvanaḥ paryavasthitaḥ",
    conceptIds: ["vs-nama-923", "vs-nama-924", "vs-nama-925", "vs-nama-926", "vs-nama-927", "vs-nama-928", "vs-nama-929", "vs-nama-930", "vs-nama-931"],
    translation: "The ferryman; destroyer of evil deeds; the holy; destroyer of nightmares; slayer of heroes (of evil); protector; the good; life; the established-all-around.",
    commentary: "Ferrying (uttāraṇa) begins the final rescue-arc: evil deeds destroyed, nightmares (duḥsvapna) dissolved — even sleep protected — then protection (rakṣaṇa), goodness (santa), life (jīvana) and all-around establishment (paryavasthita). Slaying (vīrahā) serves ferrying: force clearing the channel. Name one nightmare to be dissolved.",
    keyPoints: ["Names 923–931: Uttāraṇaḥ — Paryavasthitaḥ.", "Ferrying with force clearing the channel.", "Even sleep protected."],
  },
  {
    id: "vs-100",
    number: "Stotra 100 (names 932–940)",
    section: "Stotra · Crossing and ground",
    iast: "ananta-rūpo 'nanta-śrīr jita-manyur bhayāpahaḥ । caturaśro gabhīrātmā vidiśo vyādiśo diśaḥ",
    conceptIds: ["vs-nama-932", "vs-nama-933", "vs-nama-934", "vs-nama-935", "vs-nama-936", "vs-nama-937", "vs-nama-938", "vs-nama-939", "vs-nama-940"],
    translation: "Endlessly formed; endlessly glorious; anger-conquered; fear-remover; four-square; deep-souled; ordainer of quarters; commander of directions; direction itself.",
    commentary: "Endlessness forms (anantarūpa) and glories (anantaśrī) without anger (jitamanyu): infinity with temper mastered. Four-square (caturaśra) steadiness deepens (gabhīrātmā), then quarters, commands and direction (vidiśa/vyādiśa/diśa) orient the lost: geometry of grace. Face your true direction once.",
    keyPoints: ["Names 932–940: Anantarūpaḥ — Diśaḥ.", "Infinity with temper mastered.", "Quarters ordained: geometry of grace."],
  },
  {
    id: "vs-101",
    number: "Stotra 101 (names 941–949)",
    section: "Stotra · Crossing and ground",
    iast: "anādir bhūr-bhuvo lakṣmīḥ suvīro rucira-aṅgadaḥ । janano jana-janmādir bhīmo bhīma-parākramaḥ",
    conceptIds: ["vs-nama-941", "vs-nama-942", "vs-nama-943", "vs-nama-944", "vs-nama-945", "vs-nama-946", "vs-nama-947", "vs-nama-948", "vs-nama-949"],
    translation: "Beginningless; ground of earth; Lakṣmī; greatly heroic; bright-braceleted; the begetter; birth's beginning; the terrible; terribly mighty.",
    commentary: "Beginningless (anādi) grounds (bhūrbhuva) and glories (lakṣmī): priority, support, splendour. Heroism (suvīra) wears bright bracelets (rucirāṅgada): terror adorned. Begetter (janana) and birth's beginning (janajanmādi) double the origin; terrible might (bhīmaparākrama) guards the nursery. Begin one begetting kindly.",
    keyPoints: ["Names 941–949: Anādiḥ — Bhīmaparākramaḥ.", "Priority, support, splendour.", "Terror adorned, guarding the nursery."],
  },
  {
    id: "vs-102",
    number: "Stotra 102 (names 950–958)",
    section: "Stotra · Crossing and ground",
    iast: "ādhāra-nilayo 'dhātā puṣpa-hāsaḥ prajāgaraḥ । ūrdhva-gaḥ sat-pathācāraḥ prāṇadaḥ praṇavaḥ paṇaḥ",
    conceptIds: ["vs-nama-950", "vs-nama-951", "vs-nama-952", "vs-nama-953", "vs-nama-954", "vs-nama-955", "vs-nama-956", "vs-nama-957", "vs-nama-958"],
    translation: "Abode of support; the sustainer; flower-smiling; ever-wakeful; upward-going; walker of true paths; breath-giver; Om; the trader.",
    commentary: "Support's abode (ādhāranilaya) smiles flowers (puṣpahāsa): gravity blooming. Ever-wakeful (prajāgara) upward-going (ūrdhvaga) true-path-walking (satpathācāra): vigilance, ascent, rectitude in stride. Breath given (prāṇada), Om sounded (praṇava), then trader (paṇa) startles — He bargains for souls, paying grace. Walk one true step upward.",
    keyPoints: ["Names 950–958: Ādhāranilayaḥ — Paṇaḥ.", "Gravity blooming: support smiling.", "Paṇa: He bargains for souls."],
  },
  {
    id: "vs-103",
    number: "Stotra 103 (names 959–966)",
    section: "Stotra · Crossing and ground",
    iast: "pramāṇaṃ prāṇa-nilayaḥ prāṇa-bhṛt prāṇa-jīvanaḥ । tattvaṃ tattva-vid ekātmā janma-mṛtyu-jarātigaḥ",
    conceptIds: ["vs-nama-959", "vs-nama-960", "vs-nama-961", "vs-nama-962", "vs-nama-963", "vs-nama-964", "vs-nama-965", "vs-nama-966"],
    translation: "The measure; home of breaths; bearer of breaths; liver by breath; reality; knower of reality; the one self; beyond birth, death and age.",
    commentary: "Measure (pramāṇa) means both proof and proportion: He is logic's warrant and life's scale. Three breath-names (nilaya/bhṛt/jīvana) — home, bearer, livelihood of breath — breathe into reality (tattva) known (tattvavit) as one self (ekātmā), closing beyond birth, death, age. The hymn's philosophy peaks here: epistemology, physiology, metaphysics, freedom. Breathe once as His livelihood.",
    keyPoints: ["Names 959–966: Pramāṇam — Janmamṛtyujarātigaḥ.", "Pramāṇa: proof and proportion.", "Philosophy's peak: proof, breath, Self, freedom."],
  },
  {
    id: "vs-104",
    number: "Stotra 104 (names 967–975)",
    section: "Stotra · Sacrifice, self-birth and weapons",
    iast: "bhūr-bhuvaḥ-svas-tarus tāraḥ savitā prapitāmahaḥ । yajño yajña-patir yajvā yajñāṅgo yajña-vāhanaḥ",
    conceptIds: ["vs-nama-967", "vs-nama-968", "vs-nama-969", "vs-nama-970", "vs-nama-971", "vs-nama-972", "vs-nama-973", "vs-nama-974", "vs-nama-975"],
    translation: "Tree over earth, sky and heaven; the deliverer; the impeller; great-grandsire; sacrifice; lord of sacrifice; sacrificer; limb of sacrifice; bearer of sacrifice.",
    commentary: "The cosmic tree (bhūrbhuvaḥsvastaru) spans three worlds as one trunk: cosmology as botany. Deliverer (tāra) and impeller (savitā) move what the tree shades; great-grandsire (prapitāmaha) fathers fathers. Sacrifice quintuples — act, lord, agent, limb, bearer — ritual entire under the tree. Shelter once under the spanning tree.",
    keyPoints: ["Names 967–975: Bhūrbhuvaḥsvastaruḥ — Yajñavāhanaḥ.", "Three worlds, one trunk.", "Sacrifice quintupled under the tree."],
  },
  {
    id: "vs-105",
    number: "Stotra 105 (names 976–984)",
    section: "Stotra · Sacrifice, self-birth and weapons",
    iast: "yajña-bhṛd yajña-kṛd yajñī yajña-bhug yajña-sādhanaḥ । yajñānta-kṛd yajña-guhyam annam annāda eva ca",
    conceptIds: ["vs-nama-976", "vs-nama-977", "vs-nama-978", "vs-nama-979", "vs-nama-980", "vs-nama-981", "vs-nama-982", "vs-nama-983", "vs-nama-984"],
    translation: "Upholder of sacrifice; maker of sacrifice; enjoined in sacrifice; enjoyer of sacrifice; perfecter of sacrifice; fruiter of sacrifice; sacrifice's secret; food; food-eater.",
    commentary: "Sacrifice's second nonuple — upholding, making, enjoying, perfecting, fruiting — ends its secret (yajñaguhya) in food (anna) and eater (annāda): ritual's mystery is dinner, the cosmos eating itself gratefully. Fruiter (yajñāntakṛt) guarantees no rite ends void. Eat one meal as sacrifice's secret.",
    keyPoints: ["Names 976–984: Yajñabhṛt — Annādaḥ.", "Ritual's mystery is dinner.", "No rite ends void: fruiter promised."],
  },
  {
    id: "vs-106",
    number: "Stotra 106 (names 985–992)",
    section: "Stotra · Sacrifice, self-birth and weapons",
    iast: "ātma-yoniḥ svayañ-jāto vaikhānaḥ sāma-gāyanaḥ । devakī-nandanaḥ sraṣṭā kṣitīśaḥ pāpa-nāśanaḥ",
    conceptIds: ["vs-nama-985", "vs-nama-986", "vs-nama-987", "vs-nama-988", "vs-nama-989", "vs-nama-990", "vs-nama-991", "vs-nama-992"],
    translation: "Self-wombed; self-born; the boar-digger; Sāman-singer; Devakī's joy; creator; earth-lord; sin-destroyer.",
    commentary: "Self-wombed (ātmayoni) and self-born (svayañjāta) — origin without other — digs as boar (vaikhāna) for drowned earth and sings Sāman (sāmagāyana) over the rescue: labour with music. Devakī's joy (devakīnandana) localizes the cosmic in a prison-cell birth; sin-destroying (pāpanāśana) is the lullaby's effect. Sing over one labour.",
    keyPoints: ["Names 985–992: Ātmayoniḥ — Pāpanāśanaḥ.", "Origin without other, labour with music.", "Cosmos in a prison-cell birth."],
  },
  {
    id: "vs-107",
    number: "Stotra 107 (names 993–1000)",
    section: "Stotra · Sacrifice, self-birth and weapons",
    iast: "śaṅkha-bhṛn nandakī cakrī śārṅga-dhanvā gadā-dharaḥ । rathāṅga-pāṇir akṣobhyaḥ sarva-praharaṇāyudhaḥ",
    conceptIds: ["vs-nama-993", "vs-nama-994", "vs-nama-995", "vs-nama-996", "vs-nama-997", "vs-nama-998", "vs-nama-999", "vs-nama-1000"],
    translation: "Conch-bearer; sword-bearer; discus-bearer; Śārṅga-bowed; mace-bearer; chariot-wheeled in hand; unagitated; weaponed with every weapon.",
    commentary: "The thousand names close as armoury: conch (proclamation), sword Nandaka (discrimination), discus (time), Śārṅga bow (resolve), mace (authority), chariot-wheel (Krṣṇa at Kurukṣetra, weaponless yet weaponed). Unagitated (akṣobhya) amid arms: perfect calm carrying perfect force — and every weapon (sarvapraharaṇāyudha) means no plight lacks its instrument. Take up one weapon calmly.",
    keyPoints: ["Names 993–1000: Śaṅkhabhṛt — Sarvapraharaṇāyudhaḥ.", "Armoury as finale: proclamation to wheel.", "Calm carrying force: akṣobhya amid arms."],
  },
]