export const lsConcepts801900: any[] = [
  {
    id: "ls-nama-801",
    title: "Puṣṭā",
    category: "Mūrta-saṃsāra",
    summary: "She who is always full of vigor, nourishment. The word puṣṭi means fullness, thriving strength and wholesome growth, so the name points to Her as the very principle of nurture. Doctrinally She needs nothing from outside, for Her body is formed of the thirty-six tattvas and what transcends them, and all sustenance in the cosmos flows outward from Her through those principles. The commentary also reads the relation in reverse, that devotee love itself nourishes Her, or that She is fed by the rasa of bliss. Contemplate Her as the quiet nourishment behind breath, food and attention, and offer every meal as return of Her own energy. Her fullness teaches that lack is never ultimate, for the thirty-six principles continually pour from Her into mind, breath and harvest alike.",
    relatedVerseIds: ["ls-152"],
  },
  {
    id: "ls-nama-802",
    title: "Purātanā",
    category: "Mūrta-saṃsāra",
    summary: "She who is ancient. Purātana means the oldest, prior to all that came later, so the name declares Her temporal primacy. Doctrinally She stands first within manifestation, brought forth by Śiva as the womb through whom the whole order of creation unfolds, hence older than gods, worlds and time-reckoning itself. This antiquity means She is not an event inside history but the ground that makes beginning possible. Contemplate Her as the ever-prior Presence that was already awake before your first memory, and let the sense of age settle the mind into trust rather than novelty-seeking. Her priority steadies ambition, reminding the seeker that every new project already rests within an older and kinder order.",
    relatedVerseIds: ["ls-152"],
  },
  {
    id: "ls-nama-803",
    title: "Pūjyā",
    category: "Mūrta-saṃsāra",
    summary: "She who is worthy of worship by all. Pūjyā means fit to be honored, and the fitness comes from completeness in form and quality. Doctrinally Her wholeness radiates as steady bright energy, the kind that gathers around clear thought, kind action and disciplined practice, and because She is universal energy itself that radiance naturally draws reverence. The passage links worshipfulness to the cultivation of wholesome inner states, even extending care to plants and small beings as training in reverence. Contemplate what in you is fragmentary and ask Her completeness to gather it, then practice one small act of kindness as worship. Such radiance grows through truthful speech, generous thought and steady meditation, which quietly magnetize trust and reverence in others.",
    relatedVerseIds: ["ls-152"],
  },
  {
    id: "ls-nama-804",
    title: "Puṣkarā",
    category: "Mūrta-saṃsāra",
    summary: "She who is complete; She who gives bourishment to all. Puṣkara here carries abundance, fullness and the power to feed, continuing the previous name as a pair in which She is both nourished and nourishing. Doctrinally She distributes the puṣṭi She embodies to devotees, and the commentary hears puṣkala behind puṣkara, meaning copious and whole, an epithet of Śiva, of Meru where She dwells, and of omnipresent fullness itself. Thus the name joins giver, gift and abode in one completeness. Contemplate lack as a narrow lens and then breathe as if fed from a larger fullness, dedicating the strength received to sustaining others. Meditating on Meru as Her seat helps the devotee feel completeness as place, a mountain-like stability that feeds rather than hoards.",
    relatedVerseIds: ["ls-152"],
  },
  {
    id: "ls-nama-805",
    title: "Puṣkarekṣaṇā",
    category: "Mūrta-saṃsāra",
    summary: "She who has eyes like lotus petals. Puṣkara can mean lotus, blue lotus, sky, waters of dissolution and many other things, while īkṣaṇa means gaze, so the name holds both beauty and cosmic watchfulness. Doctrinally the commentary weighs a simple reading of lovely lotus eyes alongside a deeper one in which, when flood-waters cover the earth at dissolution, Her maternal glance prepares renewal, guarding the seed of the next creation. The uncertainty of the Vāc Devīs wording itself becomes instruction that Her look is both tender and sovereign. Contemplate Her eyes resting on your most flooded inner place, and remain still until the waters seem purposeful. Her glance thus joins tenderness with cosmic responsibility, watching over dissolution itself so that ending always serves renewal.",
    relatedVerseIds: ["ls-152"],
  },
  {
    id: "ls-nama-806",
    title: "Parañjyotiḥ",
    category: "Mūrta-saṃsāra",
    summary: "She who is the supreme light. Para means highest and jyotis means light, so the name means the Light behind all lights. Doctrinally She is the self-shining awareness by which sun, moon, fire and intellect borrow their shining, praised in the Upaniṣads as the immortal radiance on which even gods meditate for life, and as the arrival where the person knows his true nature. Realization here flashes as inner illumination when thought grows utterly quiet. Contemplate the light by which you know light, turning attention from objects lit to the silent shining that never sets, and rest there briefly each morning. The old lamp-offering verse that sings how nothing shines apart from That becomes a practical pointer to seek the shining Self within.",
    relatedVerseIds: ["ls-153"],
  },
  {
    id: "ls-nama-807",
    title: "Parandhāma",
    category: "Mūrta-saṃsāra",
    summary: "She who is the supreme abode. Parama marks the highest excellence and dhāma means brilliance, dwelling and radiant home, the word Kṛṣṇa uses for His own supreme state that sun and moon cannot light. Doctrinally light and its effulgence belong together, so after approaching Her brilliance the seeker is bathed in bliss and then merges into the self-shining ground itself, the journey from constructed thought to paraṃdhāma to supreme light. The celebrated Viṣṇu phrase about the highest step belongs to this same ascent. Contemplate Her as both path and home, and when meditation brightens, do not grasp the glow but let it carry you further inward. Yogic ascent therefore moves from outer glow to inner brilliance to sheer luminosity, each stage ripening as bliss before final merging.",
    relatedVerseIds: ["ls-153"],
  },
  {
    id: "ls-nama-808",
    title: "Paramāṇuḥ",
    category: "Mūrta-saṃsāra",
    summary: "She who is the subtlest particle. Paramāṇu means smaller than the smallest, the ultimate grain of matter beneath atoms and subatomic parts. Doctrinally this images the Brahman as both infinitely vast and infinitely minute, subtler than mind can divide, remembered in the Upaniṣadic phrase smaller than the small and greater than the great. Her smallness is not insignificance but pervasiveness, present inside every division without being cut by it. Contemplate Her in a single point of breath or a grain of attention, narrowing focus until vastness opens inside minuteness, and let humility before the tiny dissolve pride in the large. Such minuteness assures the devotee that no corner of experience is too small or hidden for Her indwelling presence.",
    relatedVerseIds: ["ls-153"],
  },
  {
    id: "ls-nama-809",
    title: "Parātparā",
    category: "Mūrta-saṃsāra",
    summary: "She who is tshe most supreme of the supreme ones. Para already means supreme, so parātparā intensifies it to the supremacy beyond supremacy, with nothing higher. Doctrinally She stands beyond the three ritual stages of parā, aparā and parāparā honored with triple gesture in the ninth enclosure by initiates of ṣoḍaśī, subtler even than kuṇḍalinī, beyond comparison and beyond speech. Another reading places Her above the creator, preserver and dissolver themselves. Contemplate the mind reaching for a highest object and then releasing even that reaching, honoring Her as the silence that remains when ranking ends. Initiates honor this height with folded gesture and triple invocation, confessing that speech must fall silent before what exceeds comparison.",
    relatedVerseIds: ["ls-153"],
  },
  {
    id: "ls-nama-810",
    title: "Pāśahastā",
    category: "Mūrta-saṃsāra",
    summary: "She who holds a noose in Her hand. Pāśa means cord, snare and whatever binds the soul, especially pressured habit and ripening karma. Doctrinally the weapon already described among Her implements carries a double sense, She wields the binding power that holds worlds in order and She loosens that same cord for the ripened seeker so that realization becomes possible. Without release from karmic entanglement, clear knowing cannot stabilize. Contemplate the one loop that most often tightens around your choices, place it imaginatively in Her uplifted hand, and ask for skill rather than struggle in its untying. Holding the cord in Her hand shows mastery over binding itself, turning fate from prison into leash guided by compassionate intelligence.",
    relatedVerseIds: ["ls-153"],
  },
  {
    id: "ls-nama-811",
    title: "Pāśahantrī",
    category: "Mūrta-saṃsāra",
    summary: "She who destroys the bonds. Hantrī means the destroyer, and pāśa here means attachment, clinging and the inner fetters that block knowledge of Śiva. Doctrinally She actively cuts those ties for those made ready by discipline and grace, recalling Her role as giver of Śiva wisdom, for the same cord She holds as order becomes liberation when She wills it. Destruction here is rescue, not violence. Contemplate one attachment honestly by name, breathe out the story that feeds it, and inwardly ask Her to sever the knot at its root while you cooperate through restraint. Her cutting grace works together with discipline, for sincere restraint and prayer invite the sword that severs inner knots.",
    relatedVerseIds: ["ls-153"],
  },
  {
    id: "ls-nama-812",
    title: "Paramantravibhedinī",
    category: "Mūrta-saṃsāra",
    summary: "She who breaks the spell of the evil mantras of the enemies. Para means hostile or alien, mantra means charged utterance, and vibhedinī means She who splits apart, so the name means breaker of spiteful sorceries. Doctrinally such hostile formulas used in black rites cannot hold where She protects, for She disperses their force and shields devotees who take refuge in Her larger sound-order. Her own mantra-essence overrules borrowed malice. Contemplate any intrusive speech, curse or anxious suggestion as a thin spell, and answer it by steady remembrance of Her name until its charge thins and breaks. Devotees therefore need not fear whispered malice when established in Her sound, since greater harmony dissolves lesser discord.",
    relatedVerseIds: ["ls-153"],
  },
  {
    id: "ls-nama-813",
    title: "Mūrtā",
    category: "Mūrta-saṃsāra",
    summary: "She who has forms. Mūrta means embodied, with shape and outline, so the name affirms that the formless accepts form. Doctrinally the Upaniṣad speaks of Brahman as twofold, gross and subtle, and form appears through māyā so that the unlimited can be met, loved and worshipped. Far from denying transcendence, form becomes its doorway. Contemplate Her in one concrete image, flower, lamp-flame or temple figure, allowing the finite shape to steady the mind, then notice the awareness that beholds the image as already beyond it. This concession to form protects devotion from abstraction, giving love hands, eyes and feet through which to serve.",
    relatedVerseIds: ["ls-154"],
  },
  {
    id: "ls-nama-814",
    title: "Amūrtā",
    category: "Mūrta-saṃsāra",
    summary: "She who has no definite form. A-mūrta negates bounded shape, pointing beyond even the subtlest envisioned form of kuṇḍalinī energy. Doctrinally the same Upaniṣadic teaching that grants Brahman form also declares an immortal, unlimited and undefined aspect, immortal and without outline, so both affirmations stand together without contradiction. She is with form for worship and without form in essence. Contemplate by gently releasing every image after invoking it, resting in open spaceless presence, and let formlessness clarify rather than erase devotion. Holding both truths prevents idolatry and dry negation, letting worship flower while wisdom remembers the beyond-form ground. Let emptiness clarify love, so that mystery deepens worship instead of thinning it.",
    relatedVerseIds: ["ls-154"],
  },
  {
    id: "ls-nama-815",
    title: "Anityatṛptā",
    category: "Mūrta-saṃsāra",
    summary: "She who is satisfied even by our perishable offerings. Anitya means transient and tṛptā means contented, a deliberate counterpart to the name that calls Her ever-content with the imperishable. Doctrinally She needs neither perishable nor imperishable since all comes from Her, yet She accepts simple gifts when given with unstained devotion, as Kṛṣṇa accepts leaf, flower, fruit and water from a sincere heart. Sincerity outweighs substance. Contemplate what small perishable thing you can offer today, time, food, attention, and give it without display as if placing it directly in Her hands. Even leaf, flower, fruit and water suffice when devotion is undivided, proving that love consecrates littleness into abundance.",
    relatedVerseIds: ["ls-154"],
  },
  {
    id: "ls-nama-816",
    title: "Munimānasahaṃsikā",
    category: "Mūrta-saṃsāra",
    summary: "She who is the swan in the mānasa lake of the minds of sages. Muni means seer, mānasa means the inner lake of mind, and haṃsikā means swan, the bird famed for separating milk from water. Doctrinally She glides within clarified contemplation, echoing the kindred name that places Her as swan in devotees minds, with the stress here on disciplined sages whose discernment is mature. Where discrimination is pure, She is at home. Contemplate the mind as a still high lake at dawn, invite the white swan of discernment to move across it, and let one confused issue separate into clear and unclear. The swan image praises discrimination that separates milk-like truth from watery confusion within the quieted inner lake.",
    relatedVerseIds: ["ls-154"],
  },
  {
    id: "ls-nama-817",
    title: "Satyavratā",
    category: "Mūrta-saṃsāra",
    summary: "She who abides firmly in truth. Satya means what endures and vrata means vow, so the name means both that truth is Her vow and that She is reached through truthfulness. Doctrinally truth is Brahman itself, existent in past, present and future, and one terse Śaiva aphorism even calls abiding awake in the body the true vow, making ordinary embodied honesty a spiritual discipline. Falsehood scatters energy while truth gathers it. Contemplate one place where speech drifts from fact, quietly correct it inwardly, and take truthfulness as your daily vow for reaching Her. Steadiness in truth thus becomes liturgy, each honest word a vow-utterance that gradually tunes the whole life to Brahman.",
    relatedVerseIds: ["ls-154"],
  },
  {
    id: "ls-nama-818",
    title: "Satyarūpā",
    category: "Mūrta-saṃsāra",
    summary: "She who is truth itself. Rūpa means form, so the name says truth is not merely Her rule but Her body. Doctrinally the wise distinguish truth from untruth because the two lead opposite ways, one toward the divine order and one toward confusion, and the Vedic verse praises the discerning person who cherishes the true. To see Her is to stand in what does not pass. Contemplate by asking of any strong claim whether it holds across time or only flatters the moment, and lean your weight on what remains steady. Leaning on what endures across past, present and future frees the heart from fashion, rumor and flattering falsehood.",
    relatedVerseIds: ["ls-154"],
  },
  {
    id: "ls-nama-819",
    title: "Sarvāntaryāminī",
    category: "Mūrta-saṃsāra",
    summary: "She who dwells inside all. Antar means within and yāminī means the ruler or indweller, so the name means the inner controller present in every soul. Doctrinally She is found by inward search rather than distant pilgrimage, for ignorance drives the search outward while the Upaniṣads affirm the Self already seated within. Every elsewhere misses the actual residence. Contemplate by withdrawing attention from outer noise for a few breaths, feeling the quiet witness behind thinking, and address Her there rather than in an imagined far place. Searching within first saves years of wandering among outer shrines while overlooking the shrine of awareness itself.",
    relatedVerseIds: ["ls-154"],
  },
  {
    id: "ls-nama-820",
    title: "Satī",
    category: "Mūrta-saṃsāra",
    summary: "She who is reality, the eternal being. Satī joins the sense of true being with the storied daughter of Dakṣa, mind-born and wed to Śiva. Doctrinally the Purāṇic scene where She reproaches Her father for slighting Śiva and offers Herself in expiation shows loyalty to the absolute over pride of lineage, and Her later reappearances carry the same fidelity into new births. Being here means faithfulness to what is real. Contemplate where social approval tempts you to dishonor conscience, and choose quiet loyalty to the true even when it costs comfort. Her story warns against sacrificing conscience to family pride, showing that loyalty to the Real outranks social approval.",
    relatedVerseIds: ["ls-154"],
  },
  {
    id: "ls-nama-821",
    title: "Brahmāṇī",
    category: "Mūrta-saṃsāra",
    summary: "She who is the tail that is brahman; the support for all. Brahmāṇī means the energy of Brahman, and aṇī also means the linchpin of a cart axle without which movement fails. Doctrinally Śiva is luminosity and Śakti is its self-awareness, the one Reality and its universal process inseparable like fire and its power to burn. She is the small pin that keeps the great wheel of manifestation turning. Contemplate the humble supports that keep your life moving, breath, food, unnoticed help, and honor Her in them rather than only in grand experiences. Honoring small linchpins in daily life becomes worship of Her, for without humble supports the greatest chariots cannot move.",
    relatedVerseIds: ["ls-155"],
  },
  {
    id: "ls-nama-822",
    title: "Brahma",
    category: "Mūrta-saṃsāra",
    summary: "She who is brahman. The word points to the ultimate Reality itself, not a subordinate power, because Śiva and Śakti are not two. Doctrinally many names in this hymn converge on the same verdict, that She is the ground into which the liberated merge to be born no more, the teaching shared by Upaniṣads and aphorisms alike. To name Her Brahman is to refuse any lesser refuge. Contemplate by letting the phrase I am held by the Whole replace self-contraction for a minute, and notice how fear loosens when identity widens. Such identity dissolves spiritual shopping, gathering all longings into one sufficient and ever-present Whole.",
    relatedVerseIds: ["ls-155"],
  },
  {
    id: "ls-nama-823",
    title: "Jananī",
    category: "Mūrta-saṃsāra",
    summary: "She who is the mother. Jananī means birth-giver, echoing the opening name of the hymn as Mother and the names that call Her maker of the world. Doctrinally joined with the previous name it is recited as brahma-jananī, the Mother who is Brahman, holding both transcendence and tenderness without dividing them. Motherhood here is ontological care, not sentiment alone. Contemplate Her maternal regard behind both comfort and discipline in your life, and answer it with the trust a child places in a wise mother when the reason is not yet clear. Reciting Her as Brahman-Mother joins metaphysics with tenderness, so philosophy never hardens into cold abstraction.",
    relatedVerseIds: ["ls-155"],
  },
  {
    id: "ls-nama-824",
    title: "Bahurūpā",
    category: "Mūrta-saṃsāra",
    summary: "She who has a multitude of forms. Bahu means many and rūpa means shape, so the name celebrates inexhaustible manifestation. Doctrinally all that exists is Brahman, yet through māyā and sense-mediated thought the One is met as many, and when mental construction empties of clinging to multiplicity the many are recognized as Her play rather than rival realities. Variety veils and reveals at once. Contemplate a crowded scene or conflicting mood as shifting costumes of one awareness, and practice meeting difference without losing the sense of shared ground. Recognizing costumes without despising them lets the devotee enjoy diversity while resting in undivided awareness.",
    relatedVerseIds: ["ls-155"],
  },
  {
    id: "ls-nama-825",
    title: "Budhārcitā",
    category: "Mūrta-saṃsāra",
    summary: "She who is worshipped by the wise. Budha means awakened and discerning, arcitā means honored, so the name says even the Self-realized adore Her. Doctrinally the knowledgeable still act to wear out residual karma, and the four kinds of devotees include seekers of knowledge among those who turn to the Lord, showing that wisdom ripens into worship rather than outgrowing it. Knowing does not cancel kneeling. Contemplate one thing you understand well and deliberately offer it back in gratitude instead of using it for pride, letting knowledge become an offering. Offering understanding back in service completes knowledge, preventing learning from curdling into vanity or argument.",
    relatedVerseIds: ["ls-155"],
  },
  {
    id: "ls-nama-826",
    title: "Prasavitrī",
    category: "Mūrta-saṃsāra",
    summary: "She who is mother of the universe. Prasava means bringing forth, so the name speaks of actual delivery of the world. Doctrinally the cosmos is born from the conjugal bliss of Śiva and Śakti, and the name belongs especially to Her supreme goddess aspect in which delight itself becomes creative. Birth here is joy taking shape. Contemplate creativity in your own life as overflow rather than strain, and before beginning work recall delight as the true womb, asking Her to deliver through you what serves wholeness. Remembering delight as creative source heals strained effort, inviting work to be conceived in joy rather than anxiety.",
    relatedVerseIds: ["ls-155"],
  },
  {
    id: "ls-nama-827",
    title: "Pracaṇḍā",
    category: "Mūrta-saṃsāra",
    summary: "She who is full of awe-inspiring wrath. Pracaṇḍa means fierce and formidable, so the name honors holy severity. Doctrinally Brahman also enforces order through fear rightly understood, the image in which wind blows, sun shines and fire burns out of reverence for the supreme command, keeping each power within its task. Wrath here is discipline that protects the good. Contemplate where laxity harms you or others, and invoke Her firmness to set one clear boundary today, wielded without hatred but without apology. Holy severity thus guards the vulnerable, setting limits that compassion alone might hesitate to enforce. Such disciplined fierceness ultimately serves tenderness, clearing ground where kindness can safely grow.",
    relatedVerseIds: ["ls-155"],
  },
  {
    id: "ls-nama-828",
    title: "Ājñā",
    category: "Mūrta-saṃsāra",
    summary: "She who is divine commandment herself. Ājñā means order, and the name says She does not merely give orders but embodies governing word. Doctrinally Śiva declares Her as sacred text, memory, resolve, and the powers of knowing, acting and willing stabilized in Himself, so obedience to Her is alignment with reality rather than servility. Disregard invites the fierceness of the previous name. Contemplate scripture and conscience as Her voice addressing your present choice, and practice prompt obedience in one small duty you have been postponing. Prompt obedience in small duties trains the ear to hear subtler commands when greater discernment is required.",
    relatedVerseIds: ["ls-155"],
  },
  {
    id: "ls-nama-829",
    title: "Pratiṣṭhā",
    category: "Mūrta-saṃsāra",
    summary: "She who is the foundation. Pratiṣṭhā means base, support and established order, praised as the righteous ground that upholds the universe. Doctrinally the name also recalls a sixteen-syllable meter and a particular ordering of subtle energies in dissolution, showing that foundation is both ethical and sonic, conduct and rhythm holding together. To stand on Her is to stand firm. Contemplate what truly supports your life when excitement fades, and strengthen one foundational habit of conduct, rest or honesty as worship of Her stability. Both meter and morals reveal rhythm as support, teaching that steady cadence in conduct upholds communal life.",
    relatedVerseIds: ["ls-155"],
  },
  {
    id: "ls-nama-830",
    title: "Prakaṭākṛtiḥ",
    category: "Mūrta-saṃsāra",
    summary: "She who is manifested in the form of the universe. Prakaṭa means evident and ākṛti means shape, so the name says Her nature is openly displayed in all beings. Doctrinally Brahman dwells in every creature, yet through māyā a person mistakes himself for only the body and misses the pervading presence, needing instruction to recognize the evident. The world is revelation awaiting recognition. Contemplate by looking slowly at one ordinary thing until its mere existing feels startling, and greet it inwardly as Her made public. Training perception to greet the evident as sacred slowly thins the veil of habit that made the obvious invisible.",
    relatedVerseIds: ["ls-155"],
  },
  {
    id: "ls-nama-831",
    title: "Prāṇeśvarī",
    category: "Mūrta-saṃsāra",
    summary: "She who lords over the five prāṇas and the senses. Prāṇa means vital breath and īśvarī means sovereign, so the name enthrones Her over respiration and perception. Doctrinally the aphorism that Brahman is prāṇa because it is known through prāṇa joins breath with consciousness, the purest awareness being Brahman itself, while daily physiology confirms that senses and mind fail when breath withdraws. She rules the currents that rule us. Contemplate by lengthening the exhale and observing senses grow calmer, acknowledging Her sovereignty each time agitation yields to steady breathing. Observing breath calm the senses confirms Her rule experientially, turning physiology itself into testimony of spirit.",
    relatedVerseIds: ["ls-156"],
  },
  {
    id: "ls-nama-832",
    title: "Prāṇadātrī",
    category: "Mūrta-saṃsāra",
    summary: "She who is the giver of life. Dātrī means bestower, so after ruling breath She is praised as its source. Doctrinally prāṇa feeds sense and mind, and the teaching that vital energies originate from Brahman makes Her both embodiment and donor of aliveness, without whom instruments of knowing lie dormant. Every inhalation is largesse. Contemplate the next breath as received gift rather than seized possession, and use renewed energy for one life-giving word or act toward someone depleted. Receiving air as alms transforms breathing into thanksgiving, and thanksgiving naturally overflows into life-giving speech. Even a single conscious breath, received gratefully, can restore steadiness to mind and senses together.",
    relatedVerseIds: ["ls-156"],
  },
  {
    id: "ls-nama-833",
    title: "Pañcāśatpīṭharūpiṇī",
    category: "Mūrta-saṃsāra",
    summary: "She who has fifty centers of worship. Pañcāśat means fifty, pīṭha means seat, and rūpiṇī means embodied, pointing to the fifty letters and their shrines. Doctrinally the tantric opening that praises bliss embodied as word and meaning unfolded into fifty sounds makes language itself Her temple circuit, each phoneme a seat where mover and moved meet. To utter purely is to pilgrimage. Contemplate the alphabet as Her garland, recite a few seed sounds slowly feeling their places in the body, and let speech become conscious worship. Each letter then becomes pilgrimage, and careful pronunciation becomes circumambulation through temples of sound.",
    relatedVerseIds: ["ls-156"],
  },
  {
    id: "ls-nama-834",
    title: "Viśṛṅkhalā",
    category: "Mūrta-saṃsāra",
    summary: "She who is unfettered, free in every way. Vi means without and śṛṅkhalā means chain, so the name declares absolute unboundness. Doctrinally bondage belongs to the performer who acts with ego or neglects enjoined duty, while Brahman stands beyond both merit and fault that chain the doer. Her freedom is the promise of ours. Contemplate which self-imposed chain feels most real today, opinion, habit or resentment, and rehearse one moment of acting without consulting it, tasting Her unbound state. Tasting even brief unbound action encourages the soul that chains are habits, not essence, and habits can be unlearned. Each taste of inner freedom weakens old chains, proving that bondage was habit rather than nature.",
    relatedVerseIds: ["ls-156"],
  },
  {
    id: "ls-nama-835",
    title: "Viviktasthā",
    category: "Mūrta-saṃsāra",
    summary: "She who abides in secluded places. Vivikta means solitary and withdrawn, sthā means dwelling, so the name loves privacy. Doctrinally the true recluse places are the hearts of those who can separate Self from small self, and worship thrives away from crowds because mixed agitation disturbs subtle attunement, making inward retirement the proper temple. Solitude clarifies signal. Contemplate by creating a brief private interval daily, door closed and devices silent, and meet Her there before seeking Her in public praise. Brief daily retirement multiplies outer effectiveness, for the mind returning from stillness carries clearer purpose. In that hush She is most audible, guiding without noise toward what truly matters.",
    relatedVerseIds: ["ls-156"],
  },
  {
    id: "ls-nama-836",
    title: "Vīramātā",
    category: "Mūrta-saṃsāra",
    summary: "She who is the mother of the valiant. Vīra can mean the elephant-faced lord as well as warriors, so the name honors Her as mother of Ganesha and of all who fight evil. Doctrinally Her own warrior nature flows into Her children, and courage against inner and outer harm becomes a family trait shared with the company of heroes She loves. Valor is Her maternity. Contemplate one evil, however small, that needs resisting in your conduct, and ask the Mother of the brave to lend you steady nerve for that single battle. Courage inherited from Her turns householders into guardians, able to confront small evils without hatred or cowardice.",
    relatedVerseIds: ["ls-156"],
  },
  {
    id: "ls-nama-837",
    title: "Viyatprasūḥ",
    category: "Mūrta-saṃsāra",
    summary: "She who is the mother to the ether. Viyat means sky or ether and prasū means birth-giver, so the name makes space itself Her child. Doctrinally the Upaniṣad traces ether from the Self and then air, fire, water and earth in sequence, placing Her before the first element as source of room for all else. Without Her there is nowhere for worlds to happen. Contemplate open space between sounds, thoughts and buildings as Her maternal expanse, and let spacious pausing soften your sense of crowding. Spacious pausing between tasks honors Her motherhood of ether, giving events room to breathe and reveal meaning.",
    relatedVerseIds: ["ls-156"],
  },
  {
    id: "ls-nama-838",
    title: "Mukundā",
    category: "Mūrta-saṃsāra",
    summary: "She who gives salvation. Mukunda, a name of the great preserver, means giver of mukti, final release where the separate soul merges with Brahman and ceases to wander. Doctrinally She shares this liberating office, granting gradual or immediate freedom according to ripeness, the cessation that is not blankness but homecoming. Salvation is Her gift, not a wage. Contemplate liberation as release from compulsive becoming rather than escape from place, and ask what one clinging you are willing to have loosened now. Longing for release thus finds personal address, for liberation is granted by One who knows each soul by name.",
    relatedVerseIds: ["ls-157"],
  },
  {
    id: "ls-nama-839",
    title: "Muktinilayā",
    category: "Mūrta-saṃsāra",
    summary: "She who is the abode of salvation. Nilaya means dwelling, so She is both giver and home of freedom. Doctrinally what She possesses She shares, and mukti is portrayed as complete disconnection of the seer from entangling intellect and from prakṛti as seen-object, isolation that is really reintegration. To reach Her is already to arrive. Contemplate Her as the house you never left but forgot, and practice returning by releasing one object of anxious gripping during quiet sitting. Dwelling-language comforts the weary traveler, promising not merely ticket but home, hearth and final rest. To turn toward Her, even briefly, is already to step across the threshold of home.",
    relatedVerseIds: ["ls-157"],
  },
  {
    id: "ls-nama-840",
    title: "Mūlavigraharūpiṇī",
    category: "Mūrta-saṃsāra",
    summary: "She who is the root form of everything. Mūla means origin, vigraha means formed body, so the name means the original embodiment behind all śaktis. Doctrinally an old Upaniṣad recalls only Her present before any world, with all manifestation flowing forth afterward, making Her Mother-form the root image from which other divine figures branch. Return means tracing branches to root. Contemplate by tracing any blessing backward to its source until thought rests in sheer givenness, and bow to the Root that precedes every particular form. Tracing blessings backward becomes practical inquiry, each thank-you a step along the branch toward nourishing root.",
    relatedVerseIds: ["ls-157"],
  },
  {
    id: "ls-nama-841",
    title: "Bhāvajñā",
    category: "Mūrta-saṃsāra",
    summary: "She who is the knower of all thoughts and sentiments. Bhāva spans becoming, feeling, intention, resolve, meditation and even the worlds, while jñā means knowing, so the name knows every shade of inner life. Doctrinally differing schools apply the word differently, yet all agree She reads resolve, devotion and hidden motive without being told, making pretense before Her useless. To be known utterly is also to be held. Contemplate by silently placing an unedited feeling before Her regard without justification, and let being fully known become relief rather than shame. Such total knowing invites radical honesty in prayer, laying motives bare before the One who already sees.",
    relatedVerseIds: ["ls-157"],
  },
  {
    id: "ls-nama-842",
    title: "Bhavarogaghnī",
    category: "Mūrta-saṃsāra",
    summary: "She who eradicates the diseases of the cycle of birth and death. Bhava here means worldly transmigration, roga means sickness, and ghnī means destroyer, so rebirth itself is diagnosed as fever. Doctrinally both Śiva and Śakti relieve this ailment through knowledge, rites rightly done and grace that dries the thirst driving new births. Healing is liberation from compulsive return. Contemplate recurring suffering as symptom rather than identity, and ask the Physician of transmigration to show the one habit whose cure would cool the whole fever. Diagnosing rebirth as curable sickness replaces despair with treatment, prescribing knowledge, devotion and selfless conduct.",
    relatedVerseIds: ["ls-157"],
  },
  {
    id: "ls-nama-843",
    title: "Bhavacakrapravartinī",
    category: "Mūrta-saṃsāra",
    summary: "She who turns the wheel of the cycle of birth and death. Cakra means wheel and pravartinī means She who sets it rotating, so the same Mother who heals also turns the round of rising and falling lives. Doctrinally the image is of a point on a wheel lifted and lowered by rotation, picturing how indulgence in world process carries beings up and down until remedy is sought. Her turning is both justice and invitation. Contemplate where you are on the wheel right now, ascent, descent or pause, and ask for wisdom to step toward the still hub rather than another rim-ride. Seeing the wheel clearly motivates seeking the hub, where stillness holds though rims continue turning for a while.",
    relatedVerseIds: ["ls-157"],
  },
  {
    id: "ls-nama-844",
    title: "Chandaḥsārā",
    category: "Mūrta-saṃsāra",
    summary: "She who is the essence of all the vedas. Chandas means meter, the measured music of sacred verse counted as outer knowledge beside liberating insight, while sāra means heart or marrow. Doctrinally She is the substance that makes poetic measure carry more than sound, the rhythmic intelligence by which hymns hold memory, breath and meaning together. Meter becomes meditation when She is heard within it. Contemplate by reciting one verse slowly, feeling syllables as footsteps, and let regularity of sound gather scattered attention into Her essence. Attending to rhythm in recitation thus becomes medicine for scattered attention, gathering fragments into measured wholeness.",
    relatedVerseIds: ["ls-158"],
  },
  {
    id: "ls-nama-845",
    title: "Śāstrasārā",
    category: "Mūrta-saṃsāra",
    summary: "She who is the essence of all scriptures. Śāstra means authoritative teaching and sāra means core, so the name places Her as the heart of every true manual. Doctrinally the aphorism that Brahman is the source of scripture means the Vedas breathe from the highest goodness itself, impossible from any lesser spring, hence all sound guidance converges on Her. Texts differ in branch while sharing root. Contemplate study as meeting Her rather than collecting views, pausing after reading to ask what single practice the passage asks of you today. Approaching texts as Her heart-beat keeps scholarship devout, preventing commentary from replacing transformation.",
    relatedVerseIds: ["ls-158"],
  },
  {
    id: "ls-nama-846",
    title: "Mantrasārā",
    category: "Mūrta-saṃsāra",
    summary: "She who is the essence of all mantras. Mantra means a charged gathering of seed sounds, and as goddess of sacred sound and mother of letters She is the life inside every formula. Doctrinally this repeats and deepens the teaching that She embodies all mantra-forms, for syllables are Her limbs and their power is Her presence concentrated for the seeker. To sound truly is to touch Her. Contemplate one mantra as Her condensed body rather than a tool, sounding it gently with attention at the heart, and let repetition ripen into listening. Gentle sounding with breath awareness lets vibration massage the heart, dissolving armored tension around feeling.",
    relatedVerseIds: ["ls-158"],
  },
  {
    id: "ls-nama-847",
    title: "Talodarī",
    category: "Mūrta-saṃsāra",
    summary: "She who is slender-waisted. Tala can suggest slenderness and udara means belly, so the name praises exquisite proportion already sung in the early bodily vision. Doctrinally another hearing adds a-tala-udarī, making Her waist the lower cosmic region when She assumes the vast world-form, joining beauty with cosmology so that adornment maps the universe. The body becomes atlas. Contemplate Her proportion as balance itself, neither indulgent nor starved, and adjust one daily habit toward graceful measure as homage to Her waist. Balanced measure in food, rest and adornment mirrors Her waist, neither constricted nor sprawling but graceful. Such proportion outwardly expresses inward harmony, where appetite and restraint serve a common grace.",
    relatedVerseIds: ["ls-158"],
  },
  {
    id: "ls-nama-848",
    title: "Udārakīrtiḥ",
    category: "Mūrta-saṃsāra",
    summary: "She who possesses exalted fame. Udāra means noble and generous, kīrti means glory that spreads, so the name says Her renown is both lofty and vitalizing. Doctrinally She both owns such fame and bestows it, granting swift recognition to worship freed from ego, while the syllables themselves are read as superiority, pervasion, swiftness and shining report confirmed by Upaniṣadic praise of radiance. True fame enlightens rather than inflates. Contemplate doing one excellent act in secret for Her alone, letting Her kīrti replace hunger for your own. Secret excellence purifies ambition, allowing recognition to come as byproduct rather than pursued prize.",
    relatedVerseIds: ["ls-158"],
  },
  {
    id: "ls-nama-849",
    title: "Uddāmavaibhavā",
    category: "Mūrta-saṃsāra",
    summary: "She whose prowess is unlimited. Uddāma means unbound and vaibhava means glory and sovereign power, while dhāma as rope suggests no cord can tie Her greatness. Doctrinally limits belong to instruments, not to their source, so Her magnificence overflows every measure applied to it. Praise confesses its own failure and continues gladly. Contemplate by naming your largest category for Her and then deliberately setting it aside, resting in awed silence that honors unlimitedness better than adjectives. Silent awe before excess teaches humility to praise itself, keeping doxology honest about its limits. Words fail gladly here, and that glad failure itself becomes the truest praise.",
    relatedVerseIds: ["ls-158"],
  },
  {
    id: "ls-nama-850",
    title: "Varṇarūpiṇī",
    category: "Mūrta-saṃsāra",
    summary: "She who is in the form of the letters of the alphabets. Varṇa means phoneme and color, rūpiṇī means embodied, recalling the earlier mother-of-letters name. Doctrinally traditions counting sixty-four sounds with their marks make every articulation Her limb, so reading, speaking and hearing become encounters with Her body distributed in sound. Language is incarnation. Contemplate the letters of your own name as small shrines, sounding each with care, and resolve to let no harsh word deform Her alphabet in your mouth today. Guarding speech from harshness thus protects Her alphabet in oneself, making the mouth a clean temple of letters.",
    relatedVerseIds: ["ls-158"],
  },
  {
    id: "ls-nama-851",
    title: "Janmamṛtyujarātaptajanaviśrāntidāyinī",
    category: "Mūrta-saṃsāra",
    summary: "She who gives peace and repose to those who are afflicted by birth, death and decrepitude. Janma, mṛtyu and jarā name the three heats that scorch living beings, while viśrānti means rest and dāyinī means giver. Doctrinally the solace offered is not temporary heaven, which must be left for further birth, but liberating rest where the soul merges with Brahman and loses separate restlessness. Relief is reunion. Contemplate exhaustion or grief as heat asking for Her shade, and turn toward Her with the simple prayer to be gathered into rest that does not end. Such rest differs from sleep or heaven by ending compulsive return, offering repose that does not expire into new unrest.",
    relatedVerseIds: ["ls-159"],
  },
  {
    id: "ls-nama-852",
    title: "Sarvopaniṣadudghuṣṭā",
    category: "Mūrta-saṃsāra",
    summary: "She who is celebrated by all the upaniṣads. Sarva means all, Upaniṣad means the intimate teachings that impart liberating knowledge, and udghuṣṭā means loudly proclaimed with superiority. Doctrinally every Upaniṣad in its own idiom announces Her glory because all instruments of Self-knowledge point to the same ground, making Her the shared verdict beneath differing texts. To study them is to hear one chorus. Contemplate by reading a single Upaniṣadic sentence as Her praise, repeating it until explanation yields to recognition, and let learning become adoration. Hearing one chorus beneath many texts reconciles apparent contradictions, deepening respect for diverse teachers. Each Upaniṣad thus becomes a lamp, and together they light one shared path to Her door.",
    relatedVerseIds: ["ls-159"],
  },
  {
    id: "ls-nama-853",
    title: "Śāntyatītakalātmikā",
    category: "Mūrta-saṃsāra",
    summary: "She who transcends the state of peace. Śānti means peace, atīta means beyond, and kalā means phase or subtle power, naming a time-aspect past tranquility itself. Doctrinally this belongs to the ninth enclosure worship open to ṣoḍaśī initiates, the station of living liberation where even holy calm is surpassed for unconditioned freedom. Peace is a door, not the house. Contemplate by noticing attachment to pleasant stillness in meditation, gently releasing the demand to remain calm, and allow Her beyond-peace to hold both stillness and movement. Releasing even attachment to calm prepares the ground for freedom that embraces both silence and activity equally.",
    relatedVerseIds: ["ls-159"],
  },
  {
    id: "ls-nama-854",
    title: "Gambhīrā",
    category: "Mūrta-saṃsāra",
    summary: "She who is unfathomable. Gambhīrā means deep like an abyss and also a reservoir, depth that holds without showing bottom. Doctrinally a Śaiva aphorism promises that union with the infinite reservoir of pure consciousness awakens supreme I-awareness, while Her independent power merges back into Śiva like river into sea. Depth here is plenitude, not obscurity. Contemplate by sinking attention below surface agitation as into still water, trusting that beneath noise lies a reservoir already full, and draw one quiet decision from that depth. Drawing decisions from depth rather than surface agitation lends choices weight, patience and quiet authority. From that reservoir one quiet choice can carry more wisdom than many hurried counsels.",
    relatedVerseIds: ["ls-160"],
  },
  {
    id: "ls-nama-855",
    title: "Gaganāntasthā",
    category: "Mūrta-saṃsāra",
    summary: "She who resides in the ether, space. Gagana means sky and antasthā means dwelling within and beyond, so She both fills space and outlasts it. Doctrinally the Upaniṣad that says the same Self fills the universe also implies survival after even ether dissolves in great dissolution, of which She is witness, making space Her garment rather than Her limit. She remains when room itself is withdrawn. Contemplate vast sky or the pause between breaths as Her residence, and let claustrophobic worry expand into the space that already contains it. Expanding worry into sky-like awareness reveals problems as weather within vaster clear space, not as encompassing fate.",
    relatedVerseIds: ["ls-160"],
  },
  {
    id: "ls-nama-856",
    title: "Garvitā",
    category: "Mūrta-saṃsāra",
    summary: "She who is proud. Garva usually faults the ego, yet here it means majestic self-poise with ample cause. Doctrinally the pride is the great I-consciousness itself, I am That, the affirmation of identity with Brahman, and since She gives what She embodies, dignified self-recognition flows to devotees as healing of cringing littleness. Pride transfigured is grandeur. Contemplate the difference between grasping superiority and upright remembrance of divine kinship, and stand inwardly taller without pushing anyone smaller. Upright remembrance without contempt heals both inferiority and arrogance, establishing dignified kinship with all. Stand tall within, yet bow outwardly, letting grandeur express as gentle and respectful strength.",
    relatedVerseIds: ["ls-160"],
  },
  {
    id: "ls-nama-857",
    title: "Gānalolupā",
    category: "Mūrta-saṃsāra",
    summary: "She who delights in music. Gāna means song and lolupā means lovingly eager, so the name loves sacred sound. Doctrinally hymns of victory like the glorious battle narrative and sweet stringed accompaniment praised in the wave-of-beauty hymn show that melody carrying Her deeds pleases Her, voice itself becoming offering. Music remembers triumphs of grace. Contemplate by singing or listening to one devotional song with full attention today, letting tone carry meaning deeper than analysis, and dedicate the pleasure to Her. Tone carrying sacred story bypasses argument, softening hearts that prose alone could not persuade. Offered tone then returns multiplied, filling the singer with peace that outlasts the song.",
    relatedVerseIds: ["ls-160"],
  },
  {
    id: "ls-nama-858",
    title: "Kalpanārahitā",
    category: "Mūrta-saṃsāra",
    summary: "She who is free from imaginary attributes. Kalpanā means mental construction and rahitā means devoid, so She stands clear of superimposed ideas. Doctrinally when ultimate Reality is directly known, approximations fall away as unnecessary, while another hearing divides the word into delight in universal welfare, hinting that freedom from fantasy expresses as care for beings. Clarity serves compassion. Contemplate by noticing one story you habitually add to bare facts, gently setting the addition aside, and meet the situation as it is before Her unsparing light. Meeting facts without added fiction reduces suffering at its root, for much pain comes from embroidery rather than event.",
    relatedVerseIds: ["ls-160"],
  },
  {
    id: "ls-nama-859",
    title: "Kāṣṭhā",
    category: "Mūrta-saṃsāra",
    summary: "She who dwells in the highest state (beyond which there is nothing). Kāṣṭhā means limit, culmination and direction, the word used for the goal beyond which none higher remains. Doctrinally the Kaṭha verse that calls That the limit and supreme course urges movement from gross to subtle until growth ends in arrival, making Her both destination and perfection of direction. Aspiration finds its term. Contemplate your highest aim and ask whether it points beyond itself to Her, then orient one present effort explicitly toward that ultimate limit. Orienting effort toward the ultimate limit prevents talents from scattering among lesser goals that cannot satisfy.",
    relatedVerseIds: ["ls-160"],
  },
  {
    id: "ls-nama-860",
    title: "Akāntā",
    category: "Mūrta-saṃsāra",
    summary: "She who ends all sins and sorrows. A-kānta here is read as destroyer of stain, kin to names that burn sin like forest fire. Doctrinally faults are undone by turning toward good action and surrender, as the song of the Lord promises that entrusting all duties to Him releases the burden, making grace the true detergent of guilt. Ending is beginning. Contemplate one fault without evasion or self-hatred, resolve its concrete repair, and place the residue at Her feet asking to be freed for cleaner service. Concrete repair paired with surrender completes repentance, joining human responsibility with divine absolution. Freedom from stain opens lightness, allowing past faults to become teachers rather than chains.",
    relatedVerseIds: ["ls-160"],
  },
  {
    id: "ls-nama-861",
    title: "Kāntārdhavigrahā",
    category: "Mūrta-saṃsāra",
    summary: "She who is half the body of Her husband. Kānta means beloved lord, ardha means half, and vigraha means form, naming the half-male half-female lord beloved in old sculpture. Doctrinally male as spirit and female as nature unite in one body to show creation itself, neither principle complete without the other. Union is cosmology. Contemplate partnership within yourself of still awareness and active energy, honoring both, and in outer relations practice sharing space rather than occupying it alone. Sharing space rather than seizing it embodies half-and-half wisdom in marriage, friendship and inner balance. In that shared body, difference is not division but the very condition of creative wholeness.",
    relatedVerseIds: ["ls-160"],
  },
  {
    id: "ls-nama-862",
    title: "Kāryakāraṇanirmuktā",
    category: "Mūrta-saṃsāra",
    summary: "She who is free from the bond of cause and effect. Kārya means effect and kāraṇa means cause, nirmuktā means released, so the chain that governs things does not govern Her. Doctrinally only Brahman acts without need, as Kṛṣṇa says He has nothing to gain yet continues to work, while variant readings stress She neither makes nor is made in the worldly sense. Freedom grounds responsibility. Contemplate acting once today purely for rightness without calculating gain, tasting causeless action as a spark of Her freedom. Causeless service for rightness alone gives a foretaste of liberation while still living within cause and effect.",
    relatedVerseIds: ["ls-161"],
  },
  {
    id: "ls-nama-863",
    title: "Kāmakelitaraṅgitā",
    category: "Mūrta-saṃsāra",
    summary: "She who is overflowing with pleasure in the union with kāmeśvara. Kāma here names the lord of desire as Śiva, keli means loving play, and taraṅgitā means rippling over, so bliss crests like waves. Doctrinally this continues the teaching that She is full of the aesthetic savor of love, conjugal delight revealing that ultimate Reality is not dry unity but overflowing affection. Joy is theological. Contemplate sacred intimacy as mutual delight that respects and renews, and let gratitude for love received become worship of their union. Gratitude for love received sanctifies eros, lifting intimacy from consumption into mutual consecration. May such delight teach lovers reverence, turning closeness into mutual offering rather than use.",
    relatedVerseIds: ["ls-161"],
  },
  {
    id: "ls-nama-864",
    title: "Kanatkanakatāṭaṅkā",
    category: "Mūrta-saṃsāra",
    summary: "She who wears glittering gold ear ornaments. Kanat means gleaming, kanaka means gold, and tāṭaṅka means ear-disc, so the name admires radiant adornment. Doctrinally the wave-of-beauty hymn credits these ear-jewels with power that keeps even poison-drinking Śiva deathless, while other verses read sun and moon themselves as Her earrings, joining ornament to cosmic protection. Beauty guards being. Contemplate adornment as consecration rather than vanity, wearing one thing today with remembrance that brightness can serve blessing. Consecrated brightness then serves blessing, reminding wearers that beauty carries responsibility to uplift beholders. Remember that true ornament protects and blesses, carrying kindly power to all who behold it.",
    relatedVerseIds: ["ls-161"],
  },
  {
    id: "ls-nama-865",
    title: "Līlāvigrahadhāriṇī",
    category: "Mūrta-saṃsāra",
    summary: "She who assumes various glorious forms as a sport. Līlā means effortless play, vigraha means embodied form, so incarnations cost Her no labor. Doctrinally ease of assuming shapes, already touched in earlier many-formed names, is explained at length as the Lord taking birth while remaining birthless, moved by compassion and order rather than compulsion. Play is providence wearing lightness. Contemplate your own roles as temporary costumes assumed for service, and enter the next duty lightly as if joining Her game rather than dragging a burden. Lightness in duty redeems routine from drudgery, revealing each role as costume graciously assumed for others.",
    relatedVerseIds: ["ls-161"],
  },
  {
    id: "ls-nama-866",
    title: "Ajā",
    category: "Mūrta-saṃsāra",
    summary: "She who has no birth. A-jā negates birth, declaring beginninglessness. Doctrinally the white-horse Upaniṣad describes primal nature as unborn though ever changing in form, without start and without production, making Her eternity compatible with endless transformation. Change of dress is not birth of wearer. Contemplate whatever in you feels newly begun or anxiously ending, and rest attention on the awareness that witnesses both without itself beginning, greeting Her as the Unborn in you. Resting in the Unborn steadies grief over endings, for what witnesses birth and death never itself began. Greet Her as the ever-Unborn behind waking, dreaming and sleep, silently present through all change.",
    relatedVerseIds: ["ls-162"],
  },
  {
    id: "ls-nama-867",
    title: "Kṣayavinirmuktā",
    category: "Mūrta-saṃsāra",
    summary: "She who is free from decay. Kṣaya means wasting and vinirmuktā means wholly released, decay here standing for death itself. Doctrinally without birth there is no death, for all origination returns to its source, and the teaching that the born must die and the dead be reborn applies to products, not to their imperishable ground. Exemption is essence. Contemplate fear of decline in body or fortune as belonging to instruments, and anchor identity a little deeper in the undecaying witness that watches change. Anchoring identity deeper than instruments quiets panic about aging, loss and changing fortune. What is undecaying in you can then carry what decays with patience and compassionate care.",
    relatedVerseIds: ["ls-162"],
  },
  {
    id: "ls-nama-868",
    title: "Mugdhā",
    category: "Mūrta-saṃsāra",
    summary: "She who is captivating in Her beauty. Mugdhā means lovely and also innocent, charm without intent to harm. Doctrinally as Mother She cannot injure Her children, and Her beauty is traced to innocent self-power that delights without guile, making moral purity the secret of aesthetic spell. Innocence beautifies. Contemplate one interaction where cleverness tempts you toward harm, choose harmless clarity instead, and notice how such innocence quietly makes the face and voice more beautiful. Choosing harmless clarity over clever harm refines both character and countenance, making goodness visibly attractive. Harmless beauty disarms defensiveness in others, inviting trust where cleverness would provoke guardedness.",
    relatedVerseIds: ["ls-162"],
  },
  {
    id: "ls-nama-869",
    title: "Kṣipraprasādinī",
    category: "Mūrta-saṃsāra",
    summary: "She who is quickly pleased. Kṣipra means swift and prasādinī means gracious, so favor is near, not remote. Doctrinally while other approaches may ripen slowly, Her great fifteen and sixteen syllable disciplines are famed to grant liberating grace even in this very life when approached sincerely, showing that readiness meets immediacy in Her. Delay is in preparation, not in Her. Contemplate by shortening the gap between remembrance and turning, invoking Her at once when distracted, and trust swift grace while keeping practice steady. Immediate turning at the first distraction builds intimacy faster than occasional intense effort separated by neglect. Swift response builds living dialogue, turning practice from schedule into continuous companionship with Her.",
    relatedVerseIds: ["ls-162"],
  },
  {
    id: "ls-nama-870",
    title: "Antarmukhasamārādhyā",
    category: "Mūrta-saṃsāra",
    summary: "She who is to be worshipped internally (mentally). Antar-mukha means facing inward and samārādhyā means to be deeply honored, so worship turns within. Doctrinally the Self dwells inside and the long discourse on inward collectedness teaches withdrawal, steadiness and absorption as the true temple service, outer rites maturing only when mind turns homeward. Interiority is not rejection of form but its fulfillment. Contemplate by closing the eyes after outer prayer, gathering breath and thought at the heart, and offering silence itself as the subtlest flower. Offering silence as flower completes outer ritual, carrying fragrance inward where words cannot follow. Rest there a little longer each day, letting stillness itself complete what words began.",
    relatedVerseIds: ["ls-162"],
  },
  {
    id: "ls-nama-871",
    title: "Bahirmukhasudurlabhā",
    category: "Mūrta-saṃsāra",
    summary: "She who is difficult to attain by those whose attention is directed outwards. Bahir-mukha means outward-facing and sudurlabhā means very hard to win, completing the previous name as a pair. Doctrinally mind is the gate, and unless senses are restrained the mind cannot turn within, leaving Her unattainable not from harshness but from mismatched direction. The seeker looks everywhere except where She stands. Contemplate by noticing how often attention flees outward today, gently recalling it once each hour, and taste how nearness grows as wandering lessens. Hourly recall of attention gradually reverses lifelong outward habit, making nearness feel natural rather than forced.",
    relatedVerseIds: ["ls-162"],
  },
  {
    id: "ls-nama-872",
    title: "Trayī",
    category: "Mūrta-saṃsāra",
    summary: "She who is the three vedas. Trayī means the triple wisdom of Ṛg, Yajur and Sāma, so the name says She is scripture in triune voice. Doctrinally praised elsewhere as mother of the Vedas, She takes their shape as hymn, rite and chant, a point a Durvāsā hymn to Her greatness unfolds across successive verses. Three utterances, one Mother. Contemplate study, practice and song as three doors to the same room, giving each its turn today rather than favoring only the mental or only the musical. Giving hymn, rite and chant each their turn balances head, hands and heart in integrated worship.",
    relatedVerseIds: ["ls-163"],
  },
  {
    id: "ls-nama-873",
    title: "Trivarganilayā",
    category: "Mūrta-saṃsāra",
    summary: "She who is the abode of the threefold aims of human life. Trivarga can mean past, present and future or the three pursuits of righteousness, prosperity and pleasure, with liberation as the crowning fourth She Herself provides. Doctrinally She shelters legitimate worldly aims while opening beyond them, refusing both world-denial and world-indulgence. Dharma steadies, artha serves, kāma flowers under Her roof. Contemplate your duties, resources and desires as rooms in Her house, ordering each honestly so that none blocks the stairway to freedom. Ordering duties, resources and desires honestly builds a household where freedom can descend as welcome guest. A well-ordered household of aims thus becomes a temple where liberation gladly visits as guest.",
    relatedVerseIds: ["ls-163"],
  },
  {
    id: "ls-nama-874",
    title: "Tristhā",
    category: "Mūrta-saṃsāra",
    summary: "She who resides in the three worlds. Tri-sthā means standing in the triple, recapitulating the previous name across every triad. Doctrinally She pervades past-present-future, creator-preserver-dissolver, creation-sustenance-dissolution, the three syllables of the sacred monosyllable and the three kinds of karma, leaving no third outside Her standing. Enumeration becomes assurance of omnipresence. Contemplate by finding Her in beginning, middle and end of one task today, honoring Her at start with intention, at middle with attention, at end with gratitude. Honoring beginning, middle and end with awareness turns ordinary tasks into triple shrines of remembrance. Start, continue and finish with Her remembrance, and even routine labor will shine with purpose.",
    relatedVerseIds: ["ls-163"],
  },
  {
    id: "ls-nama-875",
    title: "Tripuramālinī",
    category: "Mūrta-saṃsāra",
    summary: "She who is the goddess of the antardaśāra chakra of the śrī chakra. Tripura-mālinī names the garlanded mistress of the inner ten-spoked enclosure of supreme protection, served by attendants not born of wombs and governing creative unfolding. Doctrinally Mālinī also means beloved of the lord of love, joining geometric power with bridal tenderness. Diagram and devotion coincide. Contemplate the sacred diagram as a palace with Herself at its guarded heart, circumambulating inwardly with breath as you move attention layer by layer toward Her. Layer-by-layer inward movement with breath makes geometry experiential, each enclosure a softening of ego boundary. Each softened boundary lets more light pass, until the diagram dissolves into living presence.",
    relatedVerseIds: ["ls-163"],
  },
  {
    id: "ls-nama-876",
    title: "Nirāmayā",
    category: "Mūrta-saṃsāra",
    summary: "She who is free from diseases of all kinds. Nir means without and āmayā suggests sickness needing remedy, covering ills of body and mind. Doctrinally beyond both frames, She is also the cure for all ailments praised in the name that pacifies every disease, wholeness itself acting as medicine. Health flows from contact with the whole. Contemplate illness or anxiety as partiality asking for reintegration, and pray for healing that restores participation in Her wholeness rather than merely removing pain. Praying for reintegration rather than mere pain-relief aligns healing with wholeness, serving long-term flourishing. Wholeness heals by reintegration, gathering scattered parts into healthy participation in Her life.",
    relatedVerseIds: ["ls-163"],
  },
  {
    id: "ls-nama-877",
    title: "Nirālambā",
    category: "Mūrta-saṃsāra",
    summary: "She who depends on none. Nir-ālambā means without prop, needing no support while supporting all acts of creating, preserving and dissolving. Doctrinally dependence would divide Her from Śiva or subordinate Her to another, yet no difference separates them, so self-subsistence is the truth of nonduality. To lean on Her is to lean on ground that leans on nothing. Contemplate one dependency that frightens you, and practice trusting Her unsupported support by taking the next right step without demanding a guarantee. Stepping forward without guaranteed outcome exercises trust in groundless ground, strengthening spiritual nerve. Trust Her unsupported support when guarantees fail, stepping forward in duty with quiet courage.",
    relatedVerseIds: ["ls-163"],
  },
  {
    id: "ls-nama-878",
    title: "Svātmārāmā",
    category: "Mūrta-saṃsāra",
    summary: "She who rejoices in Her own self. Sva-ātman means own Self and rāmā means delighting, so bliss needs no second. Doctrinally the great forest Upaniṣad pictures the solitary One unhappy alone desiring a counterpart, dividing as husband and wife to begin the world, yet Her delight remains self-grounded even within play of two. Solitude and union share one joy. Contemplate contentment that does not wait for company or praise, sitting quietly with your own being as sufficient, and let that fullness sweeten later companionship. Fullness within sweetens later company, for those needing nothing radiate quiet generosity to all around. Solitude then ripens into generosity, for fullness naturally seeks to share itself with others.",
    relatedVerseIds: ["ls-163"],
  },
  {
    id: "ls-nama-879",
    title: "Sudhāsrutiḥ",
    category: "Mūrta-saṃsāra",
    summary: "She who is the source of nectar. Sudhā means ambrosia and sruti means flow, naming the sweet stream tasted when kuṇḍalinī reaches the brow center and subtle energy gathers near the soft palate and throat. Doctrinally earlier names of nectar-rain and moon-circle describe the same physiology of bliss, where concentrated energy normally diffusing through head centers is gathered by practice into illumination felt as flowing sweetness. Since kuṇḍalinī is Her subtlest form, the flow is Hers. An alternative reading gives Sṛitiḥ. Contemplate with grounded guidance, relaxing the palate in quiet joy and receiving sweetness as grace rather than forcing ascent. Receiving sweetness as grace rather than achievement protects practitioners from forcing subtle physiology beyond readiness.",
    relatedVerseIds: ["ls-163"],
  },
  {
    id: "ls-nama-880",
    title: "Saṃsārapaṅkanirmagnasamuddharaṇapaṇḍitā",
    category: "Mūrta-saṃsāra",
    summary: "She who is skilled in raising those who are immersed in the mire of transmigratory life. Saṃsāra-paṅka means the mud of compulsive worldliness, nirmagna means sunk, and paṇḍitā means expert in rescue. Doctrinally those who constantly remember Her avoid sinking, for remembrance lifts conduct toward spirit while forgetfulness drags it back into clutching, the word for worldling itself confessing entanglement. Skill meets willingness. Contemplate one muddy habit that sucks you downward, cry inwardly for Her expert hand, and cooperate by taking the single firm step She shows first. Single firm cooperation with grace matters more than remorse alone, for rescue requires extended hand and answering grasp.",
    relatedVerseIds: ["ls-164"],
  },
  {
    id: "ls-nama-881",
    title: "Yajñapriyā",
    category: "Mūrta-saṃsāra",
    summary: "She who is fond all sacrifices and other rituals. Yajña means offering and priyā means loving, so sacred giving delights Her. Doctrinally the nine-enclosure worship itself is a sacrificial rite, while yajña as a name of the preserver hints that offering sustains the world-order She loves. Every true gift feeds dharma. Contemplate an act of your day as oblation rather than transaction, placing time, work or food into a larger fire with attention, and notice how affection for giving purifies the giver. Viewing work as oblation purifies motive, turning transaction into thanksgiving and labor into liturgy. A single gift given with love can outweigh lavish ritual performed without heartfelt attention.",
    relatedVerseIds: ["ls-164"],
  },
  {
    id: "ls-nama-882",
    title: "Yajñakartrī",
    category: "Mūrta-saṃsāra",
    summary: "She who is the doer of sacrificial rites. Kartrī means agent, so She not only loves sacrifice but performs and enables it. Doctrinally She takes the place of the sacrificer wife who holds an essential station beside the patron, tending the three household fires of discipline through which offerings ascend. Divine agency works through human hands. Contemplate your role in any shared work as priestly rather than merely functional, preparing place, materials and mind carefully so that the common offering succeeds. Careful preparation of place and mind honors shared sacrifice, recognizing that small fidelities uphold great rites. Small fidelities faithfully kept uphold the whole sacrifice, proving devotion lives in careful details.",
    relatedVerseIds: ["ls-164"],
  },
  {
    id: "ls-nama-883",
    title: "Yajamānasvarūpiṇī",
    category: "Mūrta-saṃsāra",
    summary: "She who is in the form of yajamāna, who directs sacrificial rites. Yajamāna means the patron who ordains and funds the rite, svarūpiṇī means embodied as, so She is the directing will of worship. Doctrinally among the eight forms of Śiva the Rudra-fire form carries offering, while the Lord declares Himself enjoyer and master of all sacrifices, making patron, fire and offering one economy of grace. Command and surrender meet. Contemplate taking conscious responsibility for one practice you sponsor with time and care, directing it firmly yet offering its fruits upward. Firm yet surrendered direction balances leadership with humility, wielding authority as stewardship rather than ownership.",
    relatedVerseIds: ["ls-164"],
  },
  {
    id: "ls-nama-884",
    title: "Dharmādhārā",
    category: "Mūrta-saṃsāra",
    summary: "She who is the support of the code for righteous living. Dharma means the way of life taught by seers, ādhārā means ground that bears it. Doctrinally dharma varies with place, heritage and condition yet remains the conduct of those free from grasping, showing righteousness as living responsiveness rather than rigid copy. She upholds that supple order. Contemplate one rule of good conduct suited to your setting, keeping it today not for praise but as maintenance of the shared ground on which all stand. Maintaining shared ground through daily righteousness quietly sustains worlds, unseen yet indispensable like foundation stones. Daily righteousness, quietly kept, holds the world together more surely than grand spectacular deeds.",
    relatedVerseIds: ["ls-165"],
  },
  {
    id: "ls-nama-885",
    title: "Dhanādhyakṣā",
    category: "Mūrta-saṃsāra",
    summary: "She who oversees wealth. Dhana means riches and adhyakṣā means presiding supervisor, a station mythically held by the lord of treasures counted among Her twelve great worshippers. Doctrinally worshipper and worshipped converge, so oversight of wealth belongs to Her, reminding seekers that prosperity needs guardianship by wisdom rather than anxious hoarding. Wealth is trust. Contemplate resources under your care as supervised by Her eyes, reviewing one holding honestly and directing a portion toward sustaining goodness. Directing portion of holdings toward goodness acknowledges supervision, transforming ownership into trusteeship. Held as trust, wealth loses its sting and becomes an instrument for sustaining dharma and relieving need.",
    relatedVerseIds: ["ls-165"],
  },
  {
    id: "ls-nama-886",
    title: "Dhanadhānyavivardhinī",
    category: "Mūrta-saṃsāra",
    summary: "She who increases wealth and harvests. Dhana means treasure, dhānya means grain, and vivardhinī means increaser, so plenty follows Her favor. Doctrinally such growth comes unasked to true devotees whose energies align with dharma, increase serving generosity rather than inflation of ego. Abundance is responsibility ripened. Contemplate gratitude for food and means as Her increase, eating one meal mindfully and setting aside a share for another being as acknowledgment of the Giver. Setting aside share for others seals abundance with righteousness, keeping increase circulating rather than stagnant. Circulation keeps abundance alive, preventing hoarded plenty from stagnating into burden or pride.",
    relatedVerseIds: ["ls-165"],
  },
  {
    id: "ls-nama-887",
    title: "Viprapriyā",
    category: "Mūrta-saṃsāra",
    summary: "She who is fond of the learned. Vipra means the inwardly illumined and priyā means dear, so wisdom attracts Her affection. Doctrinally knowledge alone opens Self-recognition, making love of the learned love of the lamp that reveals Her. Learning is beloved because it liberates. Contemplate love for study as devotion rather than pride, reading one difficult passage slowly today and letting its light soften conduct toward others. Slow reading as devotion lets difficult passages work inwardly, fermenting into conduct rather than mere opinion. Let study ripen into humility and service, so that learning becomes worship and reverent service rather than mere accumulation.",
    relatedVerseIds: ["ls-165"],
  },
  {
    id: "ls-nama-888",
    title: "Viprarūpā",
    category: "Mūrta-saṃsāra",
    summary: "She who is in the form of a knower of the self. Rūpā means embodied, so after loving the wise She is the wisdom they carry. Doctrinally what dwells in the Self is naturally cherished, and the purified knower of sacred word becomes a living shrine where restraint, clarity and compassion show Her shape. The knower reveals the Known. Contemplate the wisest person you have met as a window to Her, recalling one quality of theirs to embody today, and honor knowledge by becoming kinder. Becoming kinder through learning proves study authentic, for true knowledge invariably softens the knower. Softer eyes and kinder speech will then testify that understanding has truly entered the heart.",
    relatedVerseIds: ["ls-165"],
  },
  {
    id: "ls-nama-889",
    title: "Viśvabhramaṇakāriṇī",
    category: "Mūrta-saṃsāra",
    summary: "She who makes the universe go around through Her power of illusion. Viśva means the all, bhramaṇa means whirling, and kāriṇī means causer, naming Her as spinner of worlds. Doctrinally many world-systems lie beyond grasp, yet one Brahman moves them all, praised as ruler of countless cosmoses whose revolution is Her play of measure and wonder. Motion obeys Mother. Contemplate the turning year, breath and thought as Her rotation, and steady yourself at the witnessing center while phenomena whirl, refusing to mistake spinning for self. Resting at the witnessing center while phenomena whirl prevents dizziness of soul amid rapid change.",
    relatedVerseIds: ["ls-165"],
  },
  {
    id: "ls-nama-890",
    title: "Viśvagrāsā",
    category: "Dharma-tattva",
    summary: "She who devours the universe. Grāsā means mouthful or swallowing, naming dissolution as Her meal. Doctrinally this repeats the earlier great-devouring name, with the Upaniṣad picturing even death as condiment to the Self for whom the best among peoples are as food, showing withdrawal as assimilation rather than annihilation. Ending is ingathering. Contemplate impermanence without panic, releasing one finished thing fully today, and trust Her larger hunger that eats worlds to free their essence. Releasing finished things fully practices small dissolutions, rehearsing trust for the great ingathering at the end. Trust that larger appetite for wholeness, allowing endings to feed beginning in Her wise economy.",
    relatedVerseIds: ["ls-166"],
  },
  {
    id: "ls-nama-891",
    title: "Vidrumābhā",
    category: "Dharma-tattva",
    summary: "She who shines like coral (with Her red complexion). Vidruma means red coral and ābhā means radiance, so the name praises Her ruddy glow. Doctrinally coral color recalls compassion made visible, while vidruma as tree of knowledge images a single teacher branching into many disciples, joining beauty with transmission, a theme continued in names of the teacher. Redness teaches. Contemplate Her warm hue as love thinking, and let one stern judgment redden into kindness today as you picture Her coral light on the person involved. Picturing coral light on difficult persons melts stern judgment, allowing compassion to color perception. Let that warm hue tint speech and gaze, so that others feel seen through compassion rather than judgment.",
    relatedVerseIds: ["ls-166"],
  },
  {
    id: "ls-nama-892",
    title: "Vaiṣṇavī",
    category: "Dharma-tattva",
    summary: "She who is in the form of viṣṇu. Vaiṣṇavī means power of the all-pervader, and tradition calls them brother and sister, sharers of weapons and of demon-slaying care for the virtuous. Doctrinally similarity of office reveals unity of ground, preserving love wearing two faces for different needs. Kinship signals oneness. Contemplate devotion beyond sectarian edge, honoring the preserving tenderness in Her alongside fierce protection, and practice one act that preserves goodness rather than merely protesting evil. Preserving goodness through active care completes praise, for guardianship proves love stronger than complaint. Honor the preserving office in daily choices, protecting fragile goodness wherever it struggles to survive.",
    relatedVerseIds: ["ls-166"],
  },
  {
    id: "ls-nama-893",
    title: "Viṣṇurūpiṇī",
    category: "Dharma-tattva",
    summary: "She who is in a form that extends over the whole universe. Viṣṇu means the pervader, rūpiṇī means embodied, so She is pervasion personified. Doctrinally other names affirming the same identity show Her as divine potency called creative enchantment, the Lord declaring that though birthless He appears through His own power. Pervasion becomes person to meet persons. Contemplate space itself as Her extended body, feeling Her presence in far and near equally, and act as if every place were interior to Her. Acting as if every place were interior to Her sanctifies travel, labor and rest alike with pervasive reverence.",
    relatedVerseIds: ["ls-166"],
  },
  {
    id: "ls-nama-894",
    title: "Ayoniḥ",
    category: "Dharma-tattva",
    summary: "She who is without origin. Yoni means source, womb and abode, so a-yoni denies beginning and containment. Doctrinally without origin means without dependence, while without abode means omnipresent, needing no place because every place needs Her. Negation here magnifies. Contemplate any question that asks where God comes from, letting it dissolve into awareness of the Ever-Present that precedes whence, and rest in groundless ground with quiet confidence. Resting in groundless ground calms origin-anxiety, replacing explanatory demand with present assurance. What has no beginning can never be lost, so rest full confidence in Her unoriginated, unfailing and ever-abiding presence today and always.",
    relatedVerseIds: ["ls-166"],
  },
  {
    id: "ls-nama-895",
    title: "Yoninilayā",
    category: "Dharma-tattva",
    summary: "She who is the seat of all origins. Nilayā means dwelling, so after originlessness She is the home of all origination. Doctrinally the Upaniṣadic phrase naming Brahman as cause of the golden-womb creator identifies nature as the productive matrix when touched by spirit, making Her the lap where beginnings gestate. She is no-origin yet every-origin. Contemplate new beginnings in your life as resting in Her lap, tending one seed-project patiently without forcing birth, trusting Her timing for emergence. Patient tending without forcing birth respects gestation rhythms in projects, relationships and spiritual growth. Entrust each seed to Her timing, tending with care while releasing anxious demands for immediate fruit.",
    relatedVerseIds: ["ls-166"],
  },
  {
    id: "ls-nama-896",
    title: "Kūṭasthā",
    category: "Dharma-tattva",
    summary: "She who remains unchanged like the anvil. Kūṭa means riddle, heap, fraud and also the anvil that bears hammering without moving, sthā means abiding. Doctrinally ignorance from world-absorption seems to locate Her in confusion, yet She stays motionless like anvil amid blows, the changeless witness within change, later readings stressing steadfastness over entanglement. Stability redeems bewilderment. Contemplate remaining inwardly still while outer demands hammer, answering from the anvil-place rather than vibrating with each strike, and let one provocation pass without moving your center. Letting provocation pass without losing center demonstrates anvil-strength, answering firmness with calm rather than reaction. From that steady place choose response over reaction, letting calm strength guide word and deed.",
    relatedVerseIds: ["ls-166"],
  },
  {
    id: "ls-nama-897",
    title: "Kularūpiṇī",
    category: "Dharma-tattva",
    summary: "She who is the deity of the kaula path. Kula means family, noble lineage and the esoteric discipline of left-hand worship, while mūlādhāra is also called kula as base of ascent. Doctrinally many names unfold this mystery of embodied lineage where worship, body and community interpenetrate under Her presidency. Path and goal share one household. Contemplate your spiritual lineage, teachers, companions and bodily base, as Her family chamber, and purify one family habit of speech or diet as homage to the Kula Mother. Purifying speech and diet as family offering keeps lineage vital, transmitting blessing rather than confusion to successors.",
    relatedVerseIds: ["ls-166"],
  },
  {
    id: "ls-nama-898",
    title: "Vīragoṣṭhīpriyā",
    category: "Dharma-tattva",
    summary: "She who is fond of the assembly of warriors. Vīra means brave, goṣṭhī means gathering, and priyā means loving, so heroic company delights Her. Doctrinally as mother of heroes She favors those who have conquered senses, for mastery of impulse is true battle and its victors form the noble assembly. Warriorship is self-mastery celebrated together. Contemplate joining that assembly by winning one small sense-battle today, delaying a craving deliberately, and dedicate the victory quietly to Her assembly. Deliberate delay of craving builds quiet victory, each mastered impulse enrolling the seeker among true warriors. Each deliberate restraint quietly enrolls you among heroes whose battlefield is the craving mind.",
    relatedVerseIds: ["ls-167"],
  },
  {
    id: "ls-nama-899",
    title: "Vīrā",
    category: "Dharma-tattva",
    summary: "She who is heroic. Vīrā in feminine form means valorous herself, not only mother or lover of heroes. Doctrinally Her household overflows with warriors, spouse and sons famed for slaying obstructive demons, showing courage as family dharma against arrogance, hypocrisy and pride catalogued as demonic traits. Heroism protects tenderness. Contemplate where fear dresses as prudence and keeps you from right action, invoke Her valor, and take one brave step that defends goodness without cruelty. Defending goodness without cruelty distinguishes heroism from aggression, wielding strength as shelter rather than sword. True courage shelters the gentle, using power to uphold justice while refusing cruelty and revenge.",
    relatedVerseIds: ["ls-167"],
  },
  {
    id: "ls-nama-900",
    title: "Naiṣkarmyā",
    category: "Dharma-tattva",
    summary: "She who abstains from actions. Naiṣkarmya means beyond the binding force of deeds, actionlessness as freedom. Doctrinally law of karma grips the perishable doer, but She who ordained that law stands unbound by it, Brahman untouched by works even while sustaining their order. Transcendence authorizes justice. Contemplate acting without accumulating inner bondage by offering results upward, doing one duty carefully today while releasing claim to its fruit, and taste Her actionless peace inside activity. Releasing claim to fruits while working carefully lets peace coexist with responsibility, mirroring Her free ordering. In that release, work continues but binding ceases, and activity itself becomes a form of rest.",
    relatedVerseIds: ["ls-167"],
  },
];
