// Bhagavad Gītā with Sarvatobhadra (Rājānaka Rāmakantha, KSTS LXIV, 1943) — English.
// Devanagari follows the Rāmakantha recension (pāṭhāntara tables pp.421–430); translations/commentaries original to this project.
export const gitaEnPart5: any[] = [
  {
    "id": "13.1",
    "number": "13.1",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Vulgate opening question (Śaṅkara 13.1); not numbered among the 34 KSTS chapter-13 verses, which begin इदं शरीरं as 13.1. Canonical numbering follows vulgate here."}],
    "translation": "Arjuna asks to know prakriti, purusha, kshetra, kshetrajna, jnana and jneya.",
    "commentary": "This introductory question is Śaṅkara's 13.1; the KSTS edition numbers 34 verses beginning इदं शरीरं as its 13.1–13.34. In this project's reading it frames Ch.13 as jnana-karma-samuccaya bhumika.",
    "keyPoints": ["Kashmir extra prccha", "frames kshetra-vicara"]
  },
  {
    "id": "13.2",
    "number": "13.2",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.1 = vulgate 13.2."}],
    "translation": "This body is called kshetra, and one who knows it is called kshetrajna.",
    "commentary": "Kshetra is the objective field, kshetrajna the knower. Ramakantha stresses kshetrajna as Shiva-svarupa sakshin, not mere jiva.",
    "keyPoints": ["deha=kshetra", "jnata=kshetrajna"]
  },
  {
    "id": "13.3",
    "number": "13.3",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.2 = vulgate 13.3."}],
    "translation": "Know Me as kshetrajna in all kshetras; knowledge of both is true jnana.",
    "commentary": "Universalizes the knower as Ishvara. Ramakantha reads this as advaya Shaiva atman, witnessing all fields without division.",
    "keyPoints": ["sarva-kshetra eka jnata", "jnana-lakshana"]
  },
  {
    "id": "13.4",
    "number": "13.4",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.3 = vulgate 13.4."}],
    "translation": "Hear briefly what the field is, its nature, modifications, origin, and the knower's power.",
    "commentary": "Programmatic verse for six questions. Ramakantha divides exposition into kshetra-svarupa, vikara, and kshetrajna-mahima.",
    "keyPoints": ["shad-prashna", "samasena exposition"]
  },
  {
    "id": "13.5",
    "number": "13.5",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.4 = vulgate 13.5."}],
    "translation": "It has been sung by rishis in various hymns and settled Brahmasutra aphorisms.",
    "commentary": "Authority is shruti and yukti. Ramakantha cites Shaiva agamas alongside Vedanta-sutras as pramana.",
    "keyPoints": ["rishi-vacana", "hetumad Brahma-sutra"]
  },
  {
    "id": "13.6",
    "number": "13.6",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.5 = vulgate 13.6."}],
    "translation": "The field comprises great elements, ahankara, buddhi, avyakta, ten senses plus mind, and five sense-objects.",
    "commentary": "Samkhya 24-tattva enumeration adapted. Ramakantha maps avyakta to maya-shakti, not independent prakriti.",
    "keyPoints": ["24-tattva kshetra", "Samkhya frame"]
  },
  {
    "id": "13.7",
    "number": "13.7",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.6 = vulgate 13.7."}],
    "translation": "Desire, hatred, pleasure, pain, the aggregate, consciousness-signs, and resolve are modifications of the field.",
    "commentary": "Vikaras are dharmas of kshetra, not of atman. Ramakantha insists cetana here is anta-karana-vritti, not pure caitanya.",
    "keyPoints": ["vikara=kshetra-dharma", "cetana as vritti"]
  },
  {
    "id": "13.8",
    "number": "13.8",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.7 = vulgate 13.8."}],
    "translation": "Humility, pridelessness, nonviolence, patience, honesty, teacher-service, purity, steadfastness and self-control constitute jnana.",
    "commentary": "First of jnana-sadhana virtues. Ramakantha treats them as karma-shuddhi preparing samuccaya.",
    "keyPoints": ["amanitya etc.", "jnana-sadhana"]
  },
  {
    "id": "13.9",
    "number": "13.9",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.8 = vulgate 13.9."}],
    "translation": "Dispassion toward sense-objects, egolessness, and constant perception of suffering in birth, death, age and disease.",
    "commentary": "Vairagya and dosha-darshana detach from kshetra. Ramakantha pathantara links this discipline directly to kshetrajna-avabodha, hence  gloss.",
    "keyPoints": ["vairagya", "janma-duhkha-darshana"]
  },
  {
    "id": "13.10",
    "number": "13.10",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.9 = vulgate 13.10."}],
    "translation": "Non-attachment without clinging to son, wife and home, and constant equanimity in pleasant and unpleasant events.",
    "commentary": "Asakti is inner freedom while acting. Ramakantha allows grihastha-karma with samuccaya, not forced sannyasa.",
    "keyPoints": ["asakti", "sama-cittatva"]
  },
  {
    "id": "13.11",
    "number": "13.11",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.10 = vulgate 13.11."}],
    "translation": "Unswerving devotion to Me through exclusive yoga, resort to solitude, and distaste for crowds.",
    "commentary": "Bhakti stabilizes jnana. Ramakantha reads ananya-bhakti as Shivaika-bhakti, support for karma-jnana unity.",
    "keyPoints": ["ananya-bhakti", "vivikta-seva"]
  },
  {
    "id": "13.12",
    "number": "13.12",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.11 = vulgate 13.12."}],
    "translation": "Constancy in self-knowledge and insight into the goal of truth-knowledge is called jnana, all else is ajnana.",
    "commentary": "Closes the 20-fold jnana list. Ramakantha: these are means, not end; jneya follows.",
    "keyPoints": ["adhyatma-nityatva", "jnana/ajnana divide"]
  },
  {
    "id": "13.13",
    "number": "13.13",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Rāmakantha pāṭha: Rāmakantha: na sannāsat tad ucyate."}, {"note": "Concordance: KSTS 13.12 = vulgate 13.13."}],
    "translation": "I shall teach the knowable by which immortality is gained, beginningless supreme Brahman called neither being nor non-being.",
    "commentary": "Jneya transcends sat/asat categories. Ramakantha:   emphasizes anubhava-avyapadesya Shiva-tattva beyond affirmation-negation.",
    "keyPoints": ["anadi para Brahman", "na san-na-asat"]
  },
  {
    "id": "13.14",
    "number": "13.14",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.13 = vulgate 13.14."}],
    "translation": "Everywhere hands and feet, everywhere eyes, heads, mouths and ears, it abides enveloping all.",
    "commentary": "Omnipresence through borrowed organs. Ramakantha: Shakti-vyapti, not physical limbs.",
    "keyPoints": ["sarvatah-pani", "vyapti"]
  },
  {
    "id": "13.15",
    "number": "13.15",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.14 = vulgate 13.15."}],
    "translation": "Shining through all sense-qualities yet devoid of senses, detached yet sustaining all, attributeless yet experiencing gunas.",
    "commentary": "Paradox of nirguna-saguna. Ramakantha resolves via svatantrya: Shiva reveals through instruments without bondage.",
    "keyPoints": ["nirguna yet bhoktri", "svatantrya"]
  },
  {
    "id": "13.16",
    "number": "13.16",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.15 = vulgate 13.16."}],
    "translation": "Outside and inside beings, moving and unmoving, subtle hence unknowable, yet far and near.",
    "commentary": "Proximity is epistemic, not spatial. Ramakantha: subtlety requires diksha-shuddha buddhi.",
    "keyPoints": ["bahir-antah", "suksmatva"]
  },
  {
    "id": "13.17",
    "number": "13.17",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.16 = vulgate 13.17."}],
    "translation": "Undivided yet standing as if divided among beings, the knowable sustains, devours and creates beings.",
    "commentary": "One sustainer appearing manifold. Ramakantha: srishti-samhara as Shiva-kritya.",
    "keyPoints": ["avibhakta-vibhakta", "bharta-prabhavishnu"]
  },
  {
    "id": "13.18",
    "number": "13.18",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.17 = vulgate 13.18."}],
    "translation": "Light of lights beyond darkness, knowledge itself, the knowable and goal of knowledge, seated in every heart.",
    "commentary": "Hridaya-stha jyotis is directly realisable. Ramakantha: heart is samvit-pitha.",
    "keyPoints": ["jyotir-jyotis", "hridi-sthita"]
  },
  {
    "id": "13.19",
    "number": "13.19",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.18 = vulgate 13.19."}],
    "translation": "Thus field, knowledge and knowable are briefly told; knowing this My devotee attains My state.",
    "commentary": "Phala-shruti for jnana-prakarana. Ramakantha: mad-bhava is Shivatva-patti through samuccaya.",
    "keyPoints": ["samasa-upasamhara", "mad-bhava"]
  },
  {
    "id": "13.20",
    "number": "13.20",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.19 = vulgate 13.20."}],
    "translation": "Know prakriti and purusha both as beginningless; modifications and gunas arise from prakriti.",
    "commentary": "Dual beginningless principles for vyavahara. Ramakantha subordinates both to Parama-Shiva as prakasha-vimarsha.",
    "keyPoints": ["ubhau anadi", "vikara from prakriti"]
  },
  {
    "id": "13.21",
    "number": "13.21",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Rāmakantha pāṭha: Rāmakantha: kārya-kāraṇa (vs kārya-karaṇa)."}, {"note": "Concordance: KSTS 13.20 = vulgate 13.21."}],
    "translation": "Prakriti is declared the cause of effect-instrument-agency, purusha of experiencing pleasure and pain.",
    "commentary": "Division of kartrtva and bhoktrtva. Ramakantha patha  (karya-karana, effect-cause) stresses sharira-indriya as karya-karana, correcting .",
    "keyPoints": ["prakriti=kartrtva-hetu", "purusha=bhokta"]
  },
  {
    "id": "13.22",
    "number": "13.22",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.21 = vulgate 13.22."}],
    "translation": "Purusha seated in prakriti enjoys prakriti-born gunas; attachment to gunas causes good and evil births.",
    "commentary": "Bondage is sanga, not svarupa. Ramakantha: guna-sanga is mala, removable by jnana-karma-shuddhi.",
    "keyPoints": ["guna-sanga", "yoni-karana"]
  },
  {
    "id": "13.23",
    "number": "13.23",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.22 = vulgate 13.23."}],
    "translation": "In this body the supreme Purusha is witness, approver, supporter, enjoyer, great Lord and supreme Self.",
    "commentary": "Sixfold maheshvara-linga. Ramakantha highlights Maheshvara nama as Shaiva pratyabhijna.",
    "keyPoints": ["upadrashtri etc.", "Maheshvara"]
  },
  {
    "id": "13.24",
    "number": "13.24",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.23 = vulgate 13.24."}],
    "translation": "Who knows purusha and prakriti with gunas is not reborn however he lives.",
    "commentary": "Jivanmukti assurance. Ramakantha: sarvatha vartamano'pi = samuccaya-yukta grihastha also liberated.",
    "keyPoints": ["tattva-viveka", "apunarjanma"]
  },
  {
    "id": "13.25",
    "number": "13.25",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.24 = vulgate 13.25."}],
    "translation": "Some see the Self by meditation, others by Samkhya-yoga, others by karma-yoga.",
    "commentary": "Adhikari-bheda with same lakshya. Ramakantha harmonizes them as samuccaya stages, not exclusive alternatives.",
    "keyPoints": ["dhyana-samkhya-karma", "adhikari-bheda"]
  },
  {
    "id": "13.26",
    "number": "13.26",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.25 = vulgate 13.26."}],
    "translation": "Others unknowing worship after hearing from others; they too cross death through devotion to hearing.",
    "commentary": "Shruti-parayana as valid path for manda. Ramakantha validates agama-shravana for unlettered.",
    "keyPoints": ["shrutva-upasana", "manda-adhikara"]
  },
  {
    "id": "13.27",
    "number": "13.27",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.26 = vulgate 13.27."}],
    "translation": "Whatever existent, moving or unmoving, arises from union of kshetra and kshetrajna.",
    "commentary": "All srishti is samyoga. Ramakantha: samyoga is Shakti-sparsha, not real mixture.",
    "keyPoints": ["kshetra-kshetrajna-samyoga", "sarva-utpatti"]
  },
  {
    "id": "13.28",
    "number": "13.28",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.27 = vulgate 13.28."}],
    "translation": "Who sees the supreme Lord equally abiding in all beings, imperishable in the perishing, truly sees.",
    "commentary": "Sama-darshana is true vision. Ramakantha: Parameshvara-darshana dissolves bheda-buddhi.",
    "keyPoints": ["sama-darshana", "avinashyan"]
  },
  {
    "id": "13.29",
    "number": "13.29",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.28 = vulgate 13.29."}],
    "translation": "Seeing the Lord equally everywhere, one does not injure the self by the self and attains the supreme goal.",
    "commentary": "Non-himsa follows from equality. Ramakantha: atma-himsa is guna-sanga; avoidance is moksha-marga.",
    "keyPoints": ["a-himsa", "param gati"]
  },
  {
    "id": "13.30",
    "number": "13.30",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.29 = vulgate 13.30."}],
    "translation": "Who sees all actions done by prakriti alone and the Self as non-doer truly sees.",
    "commentary": "Akartrtva-darshana. Ramakantha: Shiva as akarta witnesses maya-karma; jnana-karma union preserves this.",
    "keyPoints": ["prakriti-kartrtva", "atma-akartrtva"]
  },
  {
    "id": "13.31",
    "number": "13.31",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.30 = vulgate 13.31."}],
    "translation": "When one sees manifold beings grounded in One and expanding from It, one attains Brahman.",
    "commentary": "Ekastha-darshana leads to Brahma-sampatti. Ramakantha: eka is samvit, vistara its sphuratta.",
    "keyPoints": ["eka-stha", "Brahma-sampatti"]
  },
  {
    "id": "13.32",
    "number": "13.32",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.31 = vulgate 13.32."}],
    "translation": "Beginningless and attributeless, this imperishable supreme Self though in body neither acts nor is tainted.",
    "commentary": "Asanga despite deha-sthiti. Ramakantha: nirgunatva does not deny svatantrya-shakti.",
    "keyPoints": ["anadi-nirguna", "a-lipyamana"]
  },
  {
    "id": "13.33",
    "number": "13.33",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.32 = vulgate 13.33."}],
    "translation": "As all-pervading ether is unstained by subtlety, so the Self everywhere in body is unstained.",
    "commentary": "Akasha-drishtanta for asanga. Ramakantha uses it to defend embodied liberation.",
    "keyPoints": ["akasha-drishtanta", "asanga"]
  },
  {
    "id": "13.34",
    "number": "13.34",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.33 = vulgate 13.34."}],
    "translation": "As one sun illumines this whole world, so the field-knower illumines the whole field.",
    "commentary": "Prakasha is bodha. Ramakantha: kshetri as prakasha, kshetra as prakashya-vimarsha.",
    "keyPoints": ["surya-drishtanta", "prakasha"]
  },
  {
    "id": "13.35",
    "number": "13.35",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: KSTS 13.34 = vulgate 13.35."}],
    "translation": "Those who know by wisdom-eye the distinction of field and knower and liberation from elemental prakriti reach the Supreme.",
    "commentary": "Phala: jnana-cakshu gives moksha. Ramakantha closes kshetra-adhyaya as samuccaya-purva.",
    "keyPoints": ["jnana-cakshu", "prakriti-moksha"]
  },
  {
    "id": "14.1",
    "number": "14.1",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I shall again teach the supreme knowledge among knowledges by which sages attained perfection.",
    "commentary": "Para-jnana is guna-viveka. Ramakantha: beyond kshetra-vicara, guna-knowledge enables samuccaya-siddhi.",
    "keyPoints": ["para-jnana", "siddhi-hetu"]
  },
  {
    "id": "14.2",
    "number": "14.2",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Resorting to this knowledge and attaining My likeness, they are not born at creation nor troubled at dissolution.",
    "commentary": "Sadharmya is similarity, not annihilation. Ramakantha: Shaiva samya, retaining svatantrya.",
    "keyPoints": ["sadharmya", "sarga-pralaya-mukta"]
  },
  {
    "id": "14.3",
    "number": "14.3",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "My womb is great Brahman; in it I place the seed, whence all beings arise.",
    "commentary": "Mahad-Brahma is maya-yoni. Ramakantha: garbhadhana is Shakti-sankalpa by Shiva.",
    "keyPoints": ["mahad-brahma yoni", "sarva-sambhava"]
  },
  {
    "id": "14.4",
    "number": "14.4",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "In all wombs whatever forms arise, great Brahman is womb and I the seed-giving father.",
    "commentary": "Dual parenthood of manifestation. Ramakantha: pitritva is prakasha, yonitva vimarsha.",
    "keyPoints": ["yoni-bija", "pita-putra nyaya"]
  },
  {
    "id": "14.5",
    "number": "14.5",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sattva, rajas, tamas born of prakriti bind the imperishable embodied self in body.",
    "commentary": "Bandha mechanism introduced. Ramakantha: gunas are pasha, body the bandha-sthana.",
    "keyPoints": ["tri-guna", "bandha-hetu"]
  },
  {
    "id": "14.6",
    "number": "14.6",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sattva being stainless, luminous and healthy binds by attachment to pleasure and knowledge.",
    "commentary": "Even sattva binds subtly. Ramakantha warns samuccaya must transcend jnana-abhimana.",
    "keyPoints": ["sattva-nirmala", "sukha-jnana-sanga"]
  },
  {
    "id": "14.7",
    "number": "14.7",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Know rajas as passion-born, springing from thirst and attachment; it binds by attachment to action.",
    "commentary": "Rajas drives pravritti. Ramakantha: karma-sanga must be purified into nishkama-karma.",
    "keyPoints": ["rago-rajah", "karma-sanga"]
  },
  {
    "id": "14.8",
    "number": "14.8",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Know tamas born of ignorance deluding all embodied beings, binding by negligence, sloth and sleep.",
    "commentary": "Tamas veils viveka. Ramakantha: pramada is Shaiva apratyavamarsha.",
    "keyPoints": ["ajnana-ja tamas", "pramada-bandha"]
  },
  {
    "id": "14.9",
    "number": "14.9",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sattva attaches to pleasure, rajas to action, tamas covering knowledge attaches to negligence.",
    "commentary": "Summary of guna-functions. Ramakantha uses it for daily self-pariksha.",
    "keyPoints": ["sukha-karma-pramada", "guna-karya"]
  },
  {
    "id": "14.10",
    "number": "14.10",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sattva prevails overpowering rajas and tamas, and each in turn overpowers the others.",
    "commentary": "Mutual struggle of gunas. Ramakantha: kshana-parinama requires constant sadhana vigilance.",
    "keyPoints": ["anyonya-abhibhava", "guna-parinama"]
  },
  {
    "id": "14.11",
    "number": "14.11",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "When light of knowledge arises in all gates of body, know sattva increased.",
    "commentary": "Linga of sattva-vriddhi. Ramakantha: dvAras are indriyas illumined by samvit.",
    "keyPoints": ["prakasha-linga", "sattva-vriddhi"]
  },
  {
    "id": "14.12",
    "number": "14.12",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Greed, activity, undertaking of works, restlessness and craving arise when rajas increases.",
    "commentary": "Rajas-lingas. Ramakantha: arambha without shastra is bandhaka.",
    "keyPoints": ["lobha-pravritti", "rajo-linga"]
  },
  {
    "id": "14.13",
    "number": "14.13",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Darkness, inactivity, negligence and delusion arise when tamas increases.",
    "commentary": "Tamas-lingas. Ramakantha prescribes karma-yoga and japa to pierce aprakasha.",
    "keyPoints": ["aprakasha-pramada", "tamo-linga"]
  },
  {
    "id": "14.14",
    "number": "14.14",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Dying in increased sattva, the embodied attains pure worlds of knowers.",
    "commentary": "Sattva-mrityu-phala. Ramakantha: loka is citta-bhumika, not mere svarga.",
    "keyPoints": ["sattva-pralaya", "amala-loka"]
  },
  {
    "id": "14.15",
    "number": "14.15",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Dying in rajas one is born among action-attached, dying in tamas among deluded wombs.",
    "commentary": "Gati according to guna. Ramakantha stresses anta-kala guna determines dehantara.",
    "keyPoints": ["rajas-karma-sangi", "tamas-mudha-yoni"]
  },
  {
    "id": "14.16",
    "number": "14.16",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Fruit of good action is sattvic and pure, of rajasic is suffering, of tamasic is ignorance.",
    "commentary": "Karma-phala triad. Ramakantha: sukrita is shastra-vihita nishkama karma.",
    "keyPoints": ["sukrita-phala", "guna-phala"]
  },
  {
    "id": "14.17",
    "number": "14.17",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "From sattva arises knowledge, from rajas greed, from tamas negligence, delusion and ignorance.",
    "commentary": "Epistemic effects. Ramakantha: jnana here is viveka, to be united with karma.",
    "keyPoints": ["jnana-lobha-moha", "guna-janya"]
  },
  {
    "id": "14.18",
    "number": "14.18",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sattva-dwellers go upward, rajasic stay in middle, tamasic sunk in lowest guna go down.",
    "commentary": "Tri-gati. Ramakantha maps urdhva to Shivatva-unmukha.",
    "keyPoints": ["urdhva-madhya-adho", "tri-gati"]
  },
  {
    "id": "14.19",
    "number": "14.19",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "When the seer sees no agent beyond gunas and knows what is beyond them, he attains My state.",
    "commentary": "Guna-kartrtva darshana and guna-para bodha. Ramakantha: para is fourth, turya Shiva.",
    "keyPoints": ["guna-kartrtva", "guna-para"]
  },
  {
    "id": "14.20",
    "number": "14.20",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Transcending these three gunas born of body, the embodied freed from birth-death-age-suffering enjoys immortality.",
    "commentary": "Gunatita is jivanmukta. Ramakantha: atityA is not rejection but samuccaya-adhiroha.",
    "keyPoints": ["gunatita", "amrita"]
  },
  {
    "id": "14.21",
    "number": "14.21",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Arjuna asks the marks, conduct, and means of one who transcends the three gunas.",
    "commentary": "Practical inquiry. Ramakantha frames answer as samuccaya-lakshana.",
    "keyPoints": ["gunatita-prashna", "linga-acara-upaya"]
  },
  {
    "id": "14.22",
    "number": "14.22",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "One who neither hates nor craves light, activity, or delusion when present or absent.",
    "commentary": "Sama-buddhi toward guna-vrittis. Ramakantha: advEsha is Shaiva upeksha.",
    "keyPoints": ["a-dvesha-a-kanksha", "sama"]
  },
  {
    "id": "14.23",
    "number": "14.23",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Seated as neutral, unmoved by gunas, knowing gunas operate, who stays firm and unshaken.",
    "commentary": "Udasina is sakshi-sthiti. Ramakantha: gunA vartante = maya-krida darshana.",
    "keyPoints": ["udasina", "a-vicalya"]
  },
  {
    "id": "14.24",
    "number": "14.24",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Equal in pain-pleasure, self-abiding, equal toward clod-stone-gold, equal toward dear-undesired, blame-praise, steady.",
    "commentary": "External samatva signs. Ramakantha: svastha = Shiva-svarupa-stha.",
    "keyPoints": ["sama-duhkha-sukha", "svastha"]
  },
  {
    "id": "14.25",
    "number": "14.25",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Equal in honour-dishonour, friend-foe, renouncing all undertakings, is called beyond gunas.",
    "commentary": "Sarvarambha-tyaga is phala-tyaga, not karma-tyaga. Ramakantha: crucial for samuccaya.",
    "keyPoints": ["mana-apamana-sama", "arambha-tyaga"]
  },
  {
    "id": "14.26",
    "number": "14.26",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who serves Me with unfailing devotion transcends gunas and becomes fit for Brahman-becoming.",
    "commentary": "Bhakti as gunatita-upaya. Ramakantha: avyabhicara-bhakti is means to Shivatva.",
    "keyPoints": ["avyabhicara-bhakti", "Brahma-bhuya"]
  },
  {
    "id": "14.27",
    "number": "14.27",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am the foundation of Brahman, of imperishable immortality, eternal dharma and absolute bliss.",
    "commentary": "Krishna as pratishtha of Brahman. Ramakantha: Para-Shiva as adhishthana of para-Brahman.",
    "keyPoints": ["Brahmano pratishtha", "ekantika-sukha"]
  },
  {
    "id": "15.1",
    "number": "15.1",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "They speak of imperishable ashvattha with roots above, branches below, Vedas as leaves; knower thereof knows Vedas.",
    "commentary": "Samsara-vriksha inverted. Ramakantha: urdhva-mula is Para-Shiva, shakhas tattva-prapanca.",
    "keyPoints": ["urdhva-mula ashvattha", "Veda-patra"]
  },
  {
    "id": "15.2",
    "number": "15.2",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Branches spread below and above, nourished by gunas with sense-object sprouts, and roots binding action in human world.",
    "commentary": "Guna-poshita vistara. Ramakantha: karma-anubandhi roots are vasana-jala.",
    "keyPoints": ["guna-pravriddha", "karma-anubandha"]
  },
  {
    "id": "15.3",
    "number": "15.3",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Its form, end, beginning or support is not perceived; cutting this deep-rooted tree with strong non-attachment sword.",
    "commentary": "Asanga-shastra is viveka-vairagya. Ramakantha:  asanga from samuccaya-abhyasa.",
    "keyPoints": ["a-rupa", "asanga-shastra"]
  },
  {
    "id": "15.4",
    "number": "15.4",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Then seek the state of no return, surrendering to the primal Purusha whence ancient activity issued.",
    "commentary": "Pada-marga and prapatti. Ramakantha: adya Purusha is Adi-Shiva, prapatti is samuccaya-nishtha.",
    "keyPoints": ["a-nivritti pada", "adya-prapatti"]
  },
  {
    "id": "15.5",
    "number": "15.5",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Free from pride-delusion, conquering attachment, ever in Self, desires ceased, freed from pleasure-pain dualities, the undeluded reach that imperishable state.",
    "commentary": "Qualifications for pada. Ramakantha: nirmana-moha is mala-kshaya.",
    "keyPoints": ["nirmana-moha", "avyaya-pada"]
  },
  {
    "id": "15.6",
    "number": "15.6",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Neither sun, moon nor fire illumines it; reaching it none return; that is My supreme abode.",
    "commentary": "Svayam-prakasha dhama. Ramakantha: parama dhama is Chid-vyoman, beyond jyotir-mandala.",
    "keyPoints": ["a-bhasya", "parama dhama"]
  },
  {
    "id": "15.7",
    "number": "15.7",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "My eternal portion becomes jiva in life-world, drawing the mind-sixth senses abiding in prakriti.",
    "commentary": "Jiva as amsha. Ramakantha: amsha is pratibimba, not khanda; non-dual Shaiva amsha-vada.",
    "keyPoints": ["mama-amsha", "mana-shashtha-karshana"]
  },
  {
    "id": "15.8",
    "number": "15.8",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "When the lord takes or leaves a body, he carries these senses as wind carries scents.",
    "commentary": "Dehantara-sankranti. Ramakantha: ishvara here is jiva-bhokta with anava-mala.",
    "keyPoints": ["dehantara", "vayu-gandha nyaya"]
  },
  {
    "id": "15.9",
    "number": "15.9",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Presiding over ear, eye, touch, taste, smell and mind, it enjoys sense-objects.",
    "commentary": "Bhoga through adhishthana. Ramakantha: manas-adhiṣṭhana shows bhoktrtva is aupadhika.",
    "keyPoints": ["shad-indriya-adhishthana", "vishaya-seva"]
  },
  {
    "id": "15.10",
    "number": "15.10",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The deluded do not see it departing, staying or enjoying with gunas; wisdom-eyed see.",
    "commentary": "Jnana-cakshu requirement. Ramakantha links to Ch.13 jnana-cakshu.",
    "keyPoints": ["vimudha-a-darshana", "jnana-cakshu"]
  },
  {
    "id": "15.11",
    "number": "15.11",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Striving yogis see it abiding in self; striving yet impure-souled senseless do not see.",
    "commentary": "Yatna plus atma-shuddhi. Ramakantha: akritatman = asamucita-karma-jnana.",
    "keyPoints": ["yatna-darshana", "akritatman"]
  },
  {
    "id": "15.12",
    "number": "15.12",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Know the radiance in sun illumining world, in moon and fire, as Mine.",
    "commentary": "Tejas as vibhuti. Ramakantha: sarva-tejas is Shiva-prakasha-amsha.",
    "keyPoints": ["aditya-tejas", "mat-tejas"]
  },
  {
    "id": "15.13",
    "number": "15.13",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Entering earth I support beings by power, and as sapful moon nourish all herbs.",
    "commentary": "Dharana-poshana kritya. Ramakantha: ojas is dharika-shakti.",
    "keyPoints": ["bhu-dharana", "soma-poshana"]
  },
  {
    "id": "15.14",
    "number": "15.14",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Becoming Vaishvanara fire in bodies, united with in-out breaths, I digest fourfold food.",
    "commentary": "Antaryami as pachaka. Ramakantha: vaishvanara is jathara-Shakti of Parameshvara.",
    "keyPoints": ["vaishvanara", "caturvidha-anna-paka"]
  },
  {
    "id": "15.15",
    "number": "15.15",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Seated in every heart, from Me come memory, knowledge and forgetting; by all Vedas I am knowable, author and knower of Vedanta.",
    "commentary": "Hridaya-antaryami and Veda-vedya. Ramakantha: smriti-jnana-apohana are vimarsha-shaktis; Vedanta-krit is Agama-praneta.",
    "keyPoints": ["hridi-sannivishta", "smriti-apohana"]
  },
  {
    "id": "15.16",
    "number": "15.16",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Two purushas in world, perishable and imperishable; perishable all beings, immutable the kutastha.",
    "commentary": "Kshara-akshara vibhaga. Ramakantha: kshara = maya-karya, akshara = maya-shuddha purusha.",
    "keyPoints": ["kshara-akshara", "kutastha"]
  },
  {
    "id": "15.17",
    "number": "15.17",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The supreme Purusha is other, called supreme Self, imperishable Lord pervading and sustaining three worlds.",
    "commentary": "Uttama beyond duality. Ramakantha: anya means vilakshana Para-Shiva, Purusottama.",
    "keyPoints": ["uttama-anya", "loka-bhartri"]
  },
  {
    "id": "15.18",
    "number": "15.18",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Since I transcend perishable and excel imperishable, I am famed as Purushottama in world and Veda.",
    "commentary": "Nirvacana of Purushottama. Ramakantha: atita-uttama shows samuccaya-phala is Purusottama-patti.",
    "keyPoints": ["ksharatita", "Purushottama-prathita"]
  },
  {
    "id": "15.19",
    "number": "15.19",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Undeluded knower of Me as Purushottama knows all and worships Me with whole being.",
    "commentary": "Sarvavit-phala of Purusottama-jnana. Ramakantha: sarva-bhava-bhajana is jnana-karma-aikya.",
    "keyPoints": ["asammudha", "sarvavit"]
  },
  {
    "id": "15.20",
    "number": "15.20",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Thus this most secret teaching is spoken; understanding it one becomes wise and fulfilled.",
    "commentary": "Shastra-upasamhara. Ramakantha: guhyatama because samuccaya-rahasya revealed.",
    "keyPoints": ["guhyatama-shastra", "kritakritya"]
  },
];