export const lsUttaraVersesEnB: any[] = [
  {
    id: "ls-uttara-43",
    number: "Uttara 43",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "taddṛṣṭigocarāssarve mucyante sarvakilbiṣaiḥ । yo vetti nāmasāhasraṁ tasmai deyaṁ dvijanmane",
    translation: "All who come within the seer's gaze are freed from every stain of sin. Gifts of support should therefore be offered to the twice-born who truly knows this thousand-name hymn.",
    commentary: "This verse extends the reciter's merit outward: even beholders share in the cleansing, a common phala idiom for collective purification. The practice enjoined is material support of a qualified knower rather than indiscriminate charity. Doctrinally this links vision with grace, where the sight of a steadfast devotee itself becomes a medium of the Goddess. The injunction guards the transmission by directing resources toward study and recitation instead of mere ritual display.",
    keyPoints: ["The reciter's gaze itself is said to cleanse onlookers of sin.", "Material support belongs to the qualified knower of the hymn.", "Merit here flows outward from practice to community."],
  },
  {
    id: "ls-uttara-44",
    number: "Uttara 44",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "annaṁ vastraṁ dhanaṁ dhānyaṁ nānyebhyastu kadācana । śrīmantrarājaṁ yo vetti śrīcakraṁ yaḥ samarcati",
    translation: "Food, clothing, wealth and grain should be given to such a knower, and never to the unworthy. This refers to one who knows the auspicious king of mantras and worships the sacred wheel.",
    commentary: "The verse regulates giving by pairing outer charity with inner qualification. The practice is discriminating generosity: sustenance goes to the practitioner grounded in mantra knowledge and regular worship of the sacred diagram. Doctrinally the mantra sovereign and the wheel are inseparable, sound and form of one Goddess. Restricting gifts protects both giver and teaching, since offerings made without discernment are said to yield no lasting spiritual result.",
    keyPoints: ["Food, clothing, wealth and grain are the listed gifts.", "The recipient knows the mantra sovereign and honors the wheel.", "Discernment in giving preserves the merit of charity."],
  },
  {
    id: "ls-uttara-45",
    number: "Uttara 45",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "yaḥ kīrtayati nāmāni taṁ satpātraṁ vidurbudhāḥ । tasmai deyaṁ prayatnena śrīdevīprītimicchatā",
    translation: "The wise regard one who chants these names as a truly worthy recipient. Whoever seeks the pleasure of the Goddess should make offerings to such a person with care.",
    commentary: "Recitation becomes the test of worthiness: steady chanting marks the fit vessel for gifts. The practice enjoined is deliberate honoring of the chanter as a way of pleasing the Goddess herself. Doctrinally this reflects the identity between devotee and deity, where service to the knower counts as service to Her. Effort and attentiveness matter more than the size of the gift, since intention carries the offering to its goal.",
    keyPoints: ["Steady chanting marks a person as a worthy recipient.", "Honoring the chanter is a way of pleasing the Goddess.", "Care and effort outweigh the mere value of the gift."],
  },
  {
    id: "ls-uttara-46",
    number: "Uttara 46",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "na kīrtayati nāmāni mantrarājaṁ na vetti yaḥ । paśutulyaḥ sa vijñeyastasmai dattaṁ nirarthakam",
    translation: "One who never chants the names and does not know the king of mantras should be understood as no better than a beast. Whatever is given to such a person brings no fruit.",
    commentary: "The harsh comparison is disciplinary rather than abusive: without remembrance and mantra knowledge, human discernment stays dormant. The practice warned against is wasteful giving to the indifferent, which earns no merit. Doctrinally the verse treats sacred sound as what awakens the human capacity for liberation. Its bluntness serves the larger economy of merit, steering support toward practitioners who will convert gifts into continued worship and study.",
    keyPoints: ["Neglect of chanting and mantra is likened to a dull beast-like state.", "Gifts to the indifferent are declared fruitless.", "The warning steers support toward sincere practitioners."],
  },
  {
    id: "ls-uttara-47",
    number: "Uttara 47",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "parīkṣya vidyāviduṣastebhyo dadyādvicakṣaṇaḥ । śrīmantrarājasadṛśo yathā mantro na vidyate",
    translation: "The discerning giver should first examine those learned in the sacred lore, and give to them. For there is no mantra equal to the auspicious king of mantras.",
    commentary: "Examination precedes generosity: lineage, conduct and learning must be weighed before transmission or gifts. The practice is careful testing of recipients rather than impulsive charity. Doctrinally the verse asserts the supremacy of the fifteen-syllabled mantra sovereign, grounding the whole hymn's authority in that sound-form. By yoking discernment to supremacy, it presents the teaching as both precious and protected, shared only where it will be upheld.",
    keyPoints: ["Recipients learned in the lore must be tested first.", "The mantra sovereign is declared without equal.", "Precious teaching requires guarded transmission."],
  },
  {
    id: "ls-uttara-48",
    number: "Uttara 48",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "devatā lalitātulyā yathā nāsti ghaṭodbhava । rahasyanāmasāhasratulyā nāsti tathā stutiḥ",
    translation: "O pot-born sage, as there is no deity equal to Lalita, so there is no hymn of praise equal to this secret thousand names.",
    commentary: "The verse crowns both Goddess and hymn with unsurpassed status. No practice beyond reverent recitation is enjoined here; the point is confidence in the text being received. Doctrinally the parallel is exact: supreme deity, supreme mantra, supreme praise form a single hierarchy. Addressing the sage by his birth-epithet recalls the intimate teacher-disciple setting. Such praise passages function to settle doubt and steady the hearer before the closing instructions on worship.",
    keyPoints: ["No deity equals Lalita; no hymn equals this thousand names.", "Supremacy language builds confidence in the teaching.", "Deity, mantra and praise form one ascending scale."],
  },
  {
    id: "ls-uttara-49",
    number: "Uttara 49",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "likhitvā pustake yastu nāmasāhasramuttamam । samarcayetsadā bhaktyā tasya tuṣyati sundarī",
    translation: "Whoever copies this excellent thousand names into a book and worships it continually with devotion wins the favor of the Beautiful One.",
    commentary: "Writing becomes worship: the hand-copied book is treated as an embodied presence to be honored with flowers and attention. The practice suits those unable to perform elaborate rites, offering a simple durable devotion. Doctrinally the book functions like an image or diagram, a locus where sound settles into visible form. The verse promises Her contentment rather than a specific boon, placing loving constancy above occasional grandeur in daily religious life.",
    keyPoints: ["Copying the hymn into a book is itself meritorious.", "Daily devout worship of the book pleases the Goddess.", "Simple constancy outweighs occasional grandeur."],
  },
  {
    id: "ls-uttara-50",
    number: "Uttara 50",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "bahunātra kimuktenā śṛṇu tvaṁ kumbhasambhava । nānena sadṛśaṁ stotraṁ sarvatantreṣu dṛśyate",
    translation: "Why say more on this point? Hear, O pot-born one: in all the sacred treatises no hymn is seen that equals this one.",
    commentary: "Brevity itself becomes emphasis: after catalogues of merit, the teacher cuts short further enumeration. The practice implied is listening with trust rather than demanding endless proof. Doctrinally the claim spans the whole tantric corpus, placing this hymn at its summit. Calling the sage by his epithet renews the personal charge. Such closing superlatives seal the preceding promises and prepare the hearer for concrete instructions on daily recitation and worship.",
    keyPoints: ["Further enumeration is cut short in favor of direct hearing.", "No hymn in all the treatises is said to equal this one.", "The claim seals prior promises and opens practical instruction."],
  },
  {
    id: "ls-uttara-51",
    number: "Uttara 51",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "tasmādupāsako nityaṁ kīrtayedidamādarāt । ebhirnāmasahasraistu śrīcakraṁ yo’rcayetsakṛt",
    translation: "Therefore the worshipper should chant this hymn daily with reverence. And whoever worships the sacred wheel even once with these thousand names gains great fruit.",
    commentary: "Daily chanting with respect is laid down as the standing rule, with wheel worship as its ritual crown. Even a single united performance of hymn and diagram is credited with full effect, encouraging beginners. Doctrinally word and diagram complete each other, praise giving voice to the geometry of the Goddess. The verse balances discipline with accessibility: lifelong repetition for the committed, yet one sincere combined worship suffices to plant enduring merit.",
    keyPoints: ["Daily reverent chanting is the standing rule.", "One worship of the wheel with the names bears great fruit.", "Word and diagram complete each other in practice."],
  },
  {
    id: "ls-uttara-52",
    number: "Uttara 52",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "padmairvā tulasīpuṣpaiḥ kalhārairvā kadambakaiḥ । campakairjātikusumaiḥ mallikākaravīrakaiḥ",
    translation: "Such worship may be done with lotuses, basil blossoms, white water-lilies, kadamba flowers, campaka and jasmine blooms, and mallika and red oleander.",
    commentary: "The verse opens a catalogue of suitable flowers, naming familiar fragrant kinds from pond and garden. The practice is floral offering with each name, adaptable to season and region. Doctrinally flowers stand for the heart's opening, each petal laid as a unit of attention. Listing many species shows that devotion is not confined to one rare bloom. The catalogue continues into the next verse, forming a single garland of permitted substances for the rite.",
    keyPoints: ["Lotus, basil, lilies, kadamba and jasmine head the list.", "Many species show devotion is not bound to one bloom.", "Flowers stand for attention offered petal by petal."],
  },
  {
    id: "ls-uttara-53",
    number: "Uttara 53",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "utpalairbilvapatrairvā kundakesarapāṭalaiḥ । anyaiḥ sugandhikusumaiḥ ketakīmādhavīmukhaiḥ",
    translation: "Or with blue lotuses and wood-apple leaves, with kunda, saffron-bud and trumpet flowers, and with other sweet-scented blooms such as screwpine and spring creeper.",
    commentary: "The flower list concludes with more fragrant options, including leaves acceptable for the rite. The practice remains flexible: whatever sweet-scented blossoms are at hand may serve. Doctrinally fragrance suggests the subtle pervasion of awareness, spreading without being seen. By closing with an open class of other blooms, the text prevents scrupulosity. Sincerity of offering outweighs botanical exactness, while the traditional favorites retain pride of place in the worship.",
    keyPoints: ["Blue lotus, wood-apple leaf and fragrant blooms continue the list.", "Any sweet-scented flower may serve as needed.", "Fragrance suggests awareness pervading unseen."],
  },
  {
    id: "ls-uttara-54",
    number: "Uttara 54",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "tasya puṇyaphalaṁ vakttuṁ na śaknoti maheśvaraḥ । sā vetti lalitādevī svacakrārcanajaṁ phalam",
    translation: "Not even the Great Lord can fully state the holy fruit of such worship. Only the Goddess Lalita herself knows the fruit born of worshipping her own wheel.",
    commentary: "Inexpressibility becomes the highest praise: the merit exceeds even the great God's speech. The practice needs no further motive once its fruit is declared immeasurable. Doctrinally only the Goddess as both object and witness of her own worship can comprehend its yield. This reserves ultimate knowledge to Her while freeing devotees from anxious calculation. The verse thus turns limitation of speech into assurance of boundless return for sincere floral worship.",
    keyPoints: ["Even the Great Lord cannot fully state the merit.", "Only the Goddess herself knows its full fruit.", "Immeasurability assures boundless return for sincerity."],
  },
  {
    id: "ls-uttara-55",
    number: "Uttara 55",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "anye kathaṁ vijānīyurbrahmādyāḥ svalpamedhasaḥ । pratimāsaṁ paurṇamāsyāmebhirnāmasahasrakaiḥ",
    translation: "How then could others, beginning with Brahma, of lesser understanding, ever know it? Each month, on the full-moon day, one should worship with these thousand names.",
    commentary: "If the highest gods cannot measure the fruit, lesser intellects certainly cannot. The practice fixed here is monthly full-moon worship with the hymn, aligning devotion with lunar fullness. Doctrinally the full moon signifies the mind filled with light, a fit time for honoring the Goddess of radiance. The verse moves from theology of immeasurable merit to calendar discipline, giving ordinary practitioners a clear recurring observance through the year.",
    keyPoints: ["Lesser intellects cannot measure what the great gods cannot.", "Monthly full-moon worship with the names is enjoined.", "Lunar fullness images the mind filled with light."],
  },
  {
    id: "ls-uttara-56",
    number: "Uttara 56",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "rātrau yaścakrarājasthāmarcayetparadevatām । sa eva lalitārūpastadrūpā lalitā svayam",
    translation: "Whoever worships at night the Supreme Goddess abiding in the king of wheels becomes himself of Lalita's nature, and Lalita herself takes on his nature.",
    commentary: "Night worship in the diagram's center is said to mature into mutual indwelling. The practice is quiet nocturnal adoration, when distraction subsides and attention gathers. Doctrinally the verse teaches identity rather than mere favor: worshiper and Goddess mirror each other. This non-dual note is the summit of the whole benefit section. Full-moon nights intensify the symbolism, outer light supporting inner recognition of shared luminous nature.",
    keyPoints: ["Night worship in the king of wheels is specially praised.", "Worshiper and Goddess are said to share one nature.", "Quiet hours support recognition of luminous identity."],
  },
  {
    id: "ls-uttara-57",
    number: "Uttara 57",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "na tayorvidyate bhedo bhedakṛtpāpakṛdbhavet । mahānavamyāṁ yo bhaktaḥ śrīdevīṁ cakramadhyagām",
    translation: "There is no difference between those two, and one who imagines difference commits wrong. The devotee who on the great ninth day worships the Goddess abiding in the middle of the wheel gains liberation.",
    commentary: "Difference-making is censured as a fault against realized unity. The practice added is worship on the great ninth lunar day, a festival peak of the autumn rites. Doctrinally non-difference is an ethical claim too: to divide devotee from Goddess is to deny grace already given. The verse thus pairs a metaphysical statement with a calendar observance, joining insight and festival. The promised fruit turns from identity language to liberation held close at hand.",
    keyPoints: ["No difference remains between Goddess and true worshiper.", "Imagining division is declared a fault.", "Worship on the great ninth day brings liberation near."],
  },
  {
    id: "ls-uttara-58",
    number: "Uttara 58",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "arcayennāmasāhasraistasya muktiḥ kare sthitā । yastu nāmasahasreṇa śukravāre samarcayet",
    translation: "Whoever worships Her with the thousand names gains liberation held in hand. And whoever worships with the thousand names on Friday should hear his reward.",
    commentary: "Liberation is pictured as grasped, not distant, through worship with the hymn. The practice of Friday worship is then singled out for special praise. Doctrinally Friday's association with the Goddess makes weekly rhythm carry cosmic meaning. The verse works as a hinge: it closes the festival promise and opens a longer description of Friday merit. Hearing itself becomes part of the rite, attention preparing the ground for the stated blessings.",
    keyPoints: ["Worship with the names places liberation in hand.", "Friday worship receives special praise.", "Listening attentively prepares the promised blessings."],
  },
  {
    id: "ls-uttara-59",
    number: "Uttara 59",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "cakrarāje mahādevīṁ tasya puṇyaphalaṁ śṛṇu । sarvānkāmānavāpyeha sarvasaubhāgyasaṁyutaḥ",
    translation: "Hear the holy fruit of one who worships the Great Goddess in the king of wheels on that day: here on earth he wins all his wishes and is endowed with every good fortune.",
    commentary: "The Friday promise begins with fulfillment in this life rather than only after death. The practice is weekly worship of the Great Goddess enthroned in the diagram. Doctrinally auspiciousness is Her own nature shared with devotees, not an external prize. All desires here means legitimate aims ordered toward a flourishing household life. The verse grounds transcendence in present wellbeing, showing enjoyment and sanctity advancing together rather than opposed.",
    keyPoints: ["Friday worship in the wheel fulfills desires in this life.", "Every good fortune attends such a devotee.", "Enjoyment and sanctity advance together."],
  },
  {
    id: "ls-uttara-60",
    number: "Uttara 60",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "putrapautrādisaṁyukto bhuktvā bhogānyathepsitān । ante śrīlalitādevyāḥ sāyujyamatidurlabham",
    translation: "Joined with sons, grandsons and family, he enjoys desired pleasures as he wishes. In the end he attains identity with the Goddess Lalita, so difficult to win.",
    commentary: "Household continuity and lawful enjoyment precede final release in this sequence. The practice implied remains steady Friday worship across a lifetime. Doctrinally identity with the Goddess is the rarest attainment, set beyond even heavenly rewards. Sons and grandsons signify lineage blessing, not mere numbers. By placing final union after enjoyed pleasures, the verse affirms a path that ripens desires rather than merely suppressing them.",
    keyPoints: ["Family continuity and enjoyed pleasures come first.", "Final identity with the Goddess crowns a lifetime.", "Desires ripen rather than being merely suppressed."],
  },
  {
    id: "ls-uttara-61",
    number: "Uttara 61",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "prārthanīyaṁ śivādyaiśca prāpnotyeva na saṁśayaḥ । yaḥ sahasraṁ brāhmaṇānāmebhirnāmasahasrakaiḥ",
    translation: "That supreme identity, prayed for even by Shiva and the gods, he indeed attains — of this there is no doubt. Whoever honors a thousand learned priests with these thousand names wins grace.",
    commentary: "The goal is heightened by noting that even great gods aspire to it. The practice introduced is large-scale honoring of a thousand priests with recitation of the hymn. Doctrinally the verse removes hesitation with a firm assurance of result. Vedic and tantric streams meet here, priestly hospitality carrying hymn recitation. Scale expresses gratitude rather than extravagance, turning private devotion into communal nourishment and shared blessing.",
    keyPoints: ["Even Shiva and the gods aspire to this final identity.", "Honoring a thousand priests with the hymn is enjoined.", "Assurance removes doubt about the promised result."],
  },
  {
    id: "ls-uttara-62",
    number: "Uttara 62",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "samarcya bhojayedbhaktyā pāyasāpūpaṣaḍrasaiḥ । tasmai prīṇāti lalitā svasāmrājyaṁ prayacchati",
    translation: "Having honored them and fed them lovingly with milk-rice, cakes and savory dishes, Lalita is pleased with him and bestows her own sovereign domain.",
    commentary: "Feeding completes honoring: sweet and savory foods are served with devotion after worship. The practice joins recitation, hospitality and shared meals into one rite. Doctrinally the Goddess repays hospitality with a share in her own sovereignty, dominion over desire itself. Pleasure here means gracious favor, not indulgence. The verse shows merit moving through concrete generosity, where feeding the learned becomes feeding the Goddess who dwells in them.",
    keyPoints: ["Honored guests are fed with milk-rice, cakes and savories.", "The Goddess responds with her own sovereign domain.", "Feeding the learned counts as honoring Her."],
  },
  {
    id: "ls-uttara-63",
    number: "Uttara 63",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "na tasya durlabhaṁ vastu triṣu lokeṣu vidyate । niṣkāmaḥ kīrtayedyastu nāmasāhasramuttamam",
    translation: "Then nothing remains hard to obtain for him in the three worlds. And whoever chants this excellent thousand names without selfish motive gains the highest knowledge.",
    commentary: "Universal attainability prepares the turn to desireless recitation. The practice praised is chanting free from bargaining, seeking truth rather than prizes. Doctrinally the three worlds cover all possible fields of lack, so nothing remains outside grace. Desirelessness does not mean blankness but ripeness of motive. The verse divides outer abundance from inner freedom, giving the greater portion to the seeker who asks for nothing but understanding.",
    keyPoints: ["Nothing in the three worlds stays unattainable.", "Desireless chanting is set above bargaining prayer.", "Freedom of understanding crowns outer abundance."],
  },
  {
    id: "ls-uttara-64",
    number: "Uttara 64",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "brahmajñānamavāpnoti yena mucyeta bandhanāt । dhanārthī dhanamāpnoti yaśo’rthī cāpnuyādyaśaḥ",
    translation: "Such a one attains knowledge of the Absolute, by which he is freed from bondage. The seeker of wealth gains wealth, and the seeker of fame gains fame, through this chant.",
    commentary: "One hymn serves both liberation and legitimate aims according to motive. The practice accommodates beginners who pray for wealth or honor alongside seekers of freedom. Doctrinally knowledge of the Absolute alone severs the bonds of misidentification. Wealth and fame are not condemned but assigned their proper level. The verse thus keeps a single discipline open to many temperaments while clearly marking liberating knowledge as the supreme fruit.",
    keyPoints: ["Desireless chant yields knowledge that frees from bondage.", "Wealth and fame come to those who rightly seek them.", "One discipline serves many temperaments and aims."],
  },
  {
    id: "ls-uttara-65",
    number: "Uttara 65",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "vidyārthī cāpnuyādvidyāṁ nāmasāhasrakīrtanāt । nānena sadṛśaṁ stotraṁ bhogamokṣapradaṁ mune",
    translation: "The seeker of learning gains learning through chanting the thousand names. O sage, there is no hymn like this one for granting both enjoyment and release.",
    commentary: "Learning completes the triad of common petitions with wealth and fame. The practice stays the same, chanting with steady intention. Doctrinally enjoyment and release are twin gifts of the Goddess, worldly flourishing and final freedom held together. Addressing the sage renews the teaching frame. The verse presents completeness as this hymn's distinction: it does not force a choice between household life and liberation but nourishes both in order.",
    keyPoints: ["Seekers of learning gain learning through chanting.", "The hymn grants both enjoyment and release.", "Household life and liberation are nourished together."],
  },
  {
    id: "ls-uttara-66",
    number: "Uttara 66",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "kīrtanīyamidaṁ tasmādbhogamokṣārthibhirnaraiḥ । caturāśramaniṣṭhaiśca kīrtanīyamidaṁ sadā",
    translation: "Therefore men seeking either enjoyment or liberation should chant this hymn. And those established in all four stages of life should chant it always.",
    commentary: "The injunction widens to every aim and every stage, student through renunciant. The practice is constant recitation fitted to each station's duties. Doctrinally the four orders of life all find their completion in remembrance of the Goddess. No one is excluded by age or vocation. The verse functions as a universal recommendation, gathering householders and ascetics alike under one accessible discipline of sacred sound.",
    keyPoints: ["Seekers of enjoyment and liberation alike should chant.", "All four stages of life are included in the call.", "One discipline gathers every vocation together."],
  },
  {
    id: "ls-uttara-67",
    number: "Uttara 67",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "svadharmasamanuṣṭhānavaikalyaparipūrtaye । kalau pāpaikabahule dharmānuṣṭhānavarjite",
    translation: "Its chanting completes whatever remains defective in the performance of one's own duty. In the Kali age, crowded with strife, where righteous observance is neglected, this completion is precious.",
    commentary: "Chanting is offered as補 supplement for inevitable lapses in prescribed duty. The practice suits an age when full ritual performance often falters. Doctrinally grace completes effort rather than replacing duty outright. Naming the Kali age acknowledges diminished capacity without despair. The verse thus gives conscientious practitioners assurance: defects in outer observance can be mended through faithful remembrance of the Goddess.",
    keyPoints: ["Chanting mends defects in one's own duty.", "The Kali age makes such completion especially precious.", "Grace completes effort rather than replacing duty."],
  },
  {
    id: "ls-uttara-68",
    number: "Uttara 68",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "nāmasaṅkīrtanaṁ muktvā nṛṇāṁ nānyatparāyaṇam । laukikādvacanānmukhyaṁ viṣṇunāmānukīrtanam",
    translation: "Apart from chanting the divine Name, people in this age have no other refuge. And among chants, the repetition of Vishnu's names, rising above common speech, is foremost.",
    commentary: "The Name is presented as the accessible refuge when elaborate rites decline. The practice begins with Vishnu's names as the chief ascent from ordinary talk. Doctrinally sound carries grace directly, requiring neither wealth nor learning. The verse builds a ladder of praise that will rise through Shiva to the Goddess. Its sober view of the age is pastoral: it meets diminished strength with a discipline everyone can sustain.",
    keyPoints: ["The divine Name is the refuge of a ritual-poor age.", "Vishnu's names rise foremost above common speech.", "A ladder of praise begins its ascent here."],
  },
  {
    id: "ls-uttara-69",
    number: "Uttara 69",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "viṣṇunāmasahasrācca śivanāmaikamuttamam । śivanāmasahasrācca devyā nāmaikamuttamam",
    translation: "Yet above a thousand Vishnu names stands a single name of Shiva as higher, and above a thousand Shiva names stands a single name of the Goddess as higher still.",
    commentary: "A graded scale of efficacy leads the hearer upward from Vishnu to Shiva to the Goddess. The practice implied is steady ascent in devotion rather than sectarian rivalry. Doctrinally the Goddess as supreme power crowns the hierarchy of sacred sound. Numbers express intensity of grace, not contempt for lower rungs. The verse thus honors each level while directing final allegiance to the Divine Mother's names as most direct.",
    keyPoints: ["One Shiva name outweighs a thousand Vishnu names.", "One Goddess name outweighs a thousand Shiva names.", "The scale honors each rung while crowning the Mother."],
  },
  {
    id: "ls-uttara-70",
    number: "Uttara 70",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "devīnāmasahasrāṇi koṭiśaḥ santi kumbhaja । teṣu mukhyaṁ daśavidhaṁ nāmasāhasramucyate",
    translation: "O pot-born sage, thousands of Goddess hymns exist by the crore. Among them, ten thousand-name hymns are declared the foremost.",
    commentary: "Abundance of Goddess hymns frames the need for selection. The practice is guided toward ten principal thousand-name hymns rather than random wandering. Doctrinally vastness of revelation requires trusted ranking by the teacher. Addressing the sage personalizes the guidance. The verse prepares the catalogue that follows, assuring the hearer that devotion to the Goddess has many doors, with ten chief portals clearly marked.",
    keyPoints: ["Countless Goddess hymns exist in tradition.", "Ten thousand-name hymns are declared foremost.", "Ranking guides devotion amid abundance."],
  },
  {
    id: "ls-uttara-71",
    number: "Uttara 71",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "gaṅgā bhavānī gāyatrī kālī lakṣmīḥ sarasvatī । rājarājeśvarī bālā śyāmalā lalitā daśa",
    translation: "They are those of Ganga, Bhavani, Gayatri, Kali, Lakshmi, Sarasvati, Rajarajeshvari, Bala, Shyamala and Lalita — these ten.",
    commentary: "The ten foremost hymns are named through their presiding forms, from river goddess to supreme Lalita. No new practice is added; the list itself orients choice. Doctrinally diverse aspects gather into one Mother, each hymn a facet of her fullness. Placing Lalita last marks her as summit. The verse serves as a map, letting practitioners honor affinity while recognizing the crowning place of the present hymn.",
    keyPoints: ["Ten presiding forms from Ganga to Lalita are listed.", "Many facets gather into one Mother.", "Lalita stands last as the summit."],
  },
  {
    id: "ls-uttara-72",
    number: "Uttara 72",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "rahasyanāmasāhasramidaṁ śastaṁ daśasvapi । tasmātsaṅkīrtayennityaṁ kalidoṣanivṛttaye",
    translation: "Among even those ten, this secret thousand names is praised as excellent. Therefore one should chant it daily to wash away the taints of the Kali age.",
    commentary: "The present hymn is singled out as best among the best. The practice is daily chanting aimed at cleansing the specific faults of the present age. Doctrinally secrecy here means intimacy and protection, not concealment from the sincere. Daily repetition acts as steady antidote to distraction and strife. The verse gives Kali-age practitioners a clear anchor: one hymn, recited each day, sufficient for purification.",
    keyPoints: ["This secret hymn is praised above the ten.", "Daily chanting washes the taints of Kali.", "One anchor suffices for a distracted age."],
  },
  {
    id: "ls-uttara-73",
    number: "Uttara 73",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "mukhyaṁ śrīmātṛnāmeti na jānanti vimohitāḥ । viṣṇunāmaparāḥ kecicchivanāmaparāḥ pare",
    translation: "The deluded do not know that the Mother's names are supreme. Some cling only to Vishnu's names, and others only to Shiva's names.",
    commentary: "One-sided allegiance is gently called delusion, not devotion's strength. The practice corrected is exclusive clinging that refuses the Mother's primacy. Doctrinally the verse asserts Shakta supremacy without abusing other deities. Vishnu and Shiva remain revered; the error lies in stopping short. The observation is pastoral, urging completeness of vision where fixed habit or narrow partisanship has narrowed the sincere heart's worship.",
    keyPoints: ["Exclusive clinging is called delusion.", "Vishnu and Shiva remain revered, not rejected.", "The Mother's primacy completes narrower devotion."],
  },
  {
    id: "ls-uttara-74",
    number: "Uttara 74",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "na kaścidapi lokeṣu lalitānāmatatparaḥ । yenānya devatānāma kīrtitaṁ janmakoṭiṣu",
    translation: "Scarcely anyone in the worlds is devoted to Lalita's names. Such devotion comes only to one who has chanted the names of other deities through crores of births.",
    commentary: "Rarity marks the culmination: devotion to Lalita crowns long pilgrimage through other worships. The practice honored is patient ripening across lifetimes, not sudden claim. Doctrinally earlier devotions are stepping stones, each purifying the heart for the Mother. The verse consoles slow seekers and checks pride in quick attainment. It presents supreme devotion as earned maturity, the fruit of vast prior chanting coming to fullness at last.",
    keyPoints: ["Devotion to Lalita is rare in the worlds.", "It crowns crores of births of other worship.", "Earlier devotions ripen into this maturity."],
  },
  {
    id: "ls-uttara-75",
    number: "Uttara 75",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "tasyaiva bhavati śraddhā śrīdevīnāmakīrtane । carame janmani yathā śrīvidyopāsako bhavet",
    translation: "Only such a one gains deep faith in chanting the Goddess's names. And just so, one becomes a worshiper of the sacred lore only in the final birth.",
    commentary: "Faith itself is shown as ripened fruit rather than initial effort. The practice of sacred-lore worship belongs to the mature final birth. Doctrinally the closing births gather all prior merit into direct worship of the Mother. The verse links faith, chanting and initiation into one arc. It reassures practitioners that present attraction to the Goddess signals long preparation finally bearing visible flower and steady confidence.",
    keyPoints: ["Deep faith in Her names is ripened fruit.", "Sacred-lore worship belongs to the final birth.", "Present attraction signals long preparation."],
  },
  {
    id: "ls-uttara-76",
    number: "Uttara 76",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "nāmasāhasrapāṭhaśca tathā caramajanmani । yathaiva viralā loke śrīvidyārājavedinaḥ",
    translation: "So too the reading of this thousand names comes in that final birth. For as knowers of the royal sacred lore are rare in the world, the same rarity holds here.",
    commentary: "Access to the hymn is set alongside initiation into the royal lore, both rare culminations. The practice is treasured reading, not casual perusal. Doctrinally rarity protects value: what comes rarely is guarded dearly. The comparison dignifies the chanter without breeding exclusivism. It tells the hearer that present opportunity is precious precisely because countless seekers pass it by, urging grateful and steady use.",
    keyPoints: ["Reading the hymn belongs to the final birth.", "Knowers of the royal lore are rare in the world.", "Rarity calls for grateful and steady use."],
  },
  {
    id: "ls-uttara-77",
    number: "Uttara 77",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "tathaiva viralo guhyanāmasāhasrapāṭhakaḥ । mantrarājajapaścaiva cakrarājārcanaṁ tathā",
    translation: "Equally rare is the reader of this secret thousand names. So too are the repeater of the king of mantras and the worshiper of the king of wheels.",
    commentary: "Three disciplines share one rarity: hymn reading, mantra repetition and diagram worship. The practice holds them as a united triad rather than rivals. Doctrinally sound, praise and form complete a single worship of the Goddess. Each supports the others, recitation steadying repetition and worship grounding both. The verse honors the full practitioner who carries all three, marking such completeness as uncommon grace rather than common routine.",
    keyPoints: ["Hymn, mantra and wheel form one rare triad.", "Each discipline supports the other two.", "Completeness in all three is uncommon grace."],
  },
  {
    id: "ls-uttara-78",
    number: "Uttara 78",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "rahasyanāmapāṭhaśca nālpasya tapasaḥ phalam । apaṭhannāmasāhasraṁ prīṇayedyo maheśvarīm",
    translation: "The reading of the secret names is no fruit of slight austerity. Whoever would please the Great Goddess without reading the thousand names attempts the impossible.",
    commentary: "Great prior discipline is declared the root of present access. The practice required is the thousand-name reading itself, not bypassed by other offerings. Doctrinally pleasing the Goddess means meeting Her in the form She has most favored. The verse uses deliberate impossibility images to settle priority. It warns against seeking shortcuts around the hymn while affirming that sustained austerity naturally flowers into its devoted recitation.",
    keyPoints: ["Access to the hymn ripens from great austerity.", "No pleasing of the Goddess bypasses these names.", "Shortcuts around the hymn are set aside."],
  },
  {
    id: "ls-uttara-79",
    number: "Uttara 79",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "sa cakṣuṣā vinā rūpaṁ paśyedeva vimūḍhadhīḥ । rahasyanāmasāhasraṁ tyaktvā yaḥ siddhikāmukaḥ",
    translation: "Such a one, deluded in mind, would see form without eyes. Whoever longs for accomplishment yet abandons the secret thousand names labors in vain.",
    commentary: "Blind seeing pictures the futility of seeking favor while spurning the favored hymn. The practice corrected is chasing powers apart from foundational praise. Doctrinally accomplishments follow grace rather than compelling it. Calling the attempt deluded is medicinal bluntness, meant to redirect energy. The verse places the secret names at the center of effective worship, with all other aims arranged around steady devotion to them.",
    keyPoints: ["Seeking favor without the hymn is like seeing without eyes.", "Powers pursued apart from praise prove vain.", "The secret names stand at worship's center."],
  },
  {
    id: "ls-uttara-80",
    number: "Uttara 80",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "sa bhojanaṁ vinā nūnaṁ kṣunnivṛttimabhīpsati । yo bhakto lalitādevyāḥ sa nityaṁ kīrtayedidam",
    translation: "He surely hopes to end hunger without food. The devotee of Lalita should therefore chant this hymn daily without fail.",
    commentary: "Hunger without eating completes the images of futility. The positive practice follows at once: daily chanting by one who claims Her devotion. Doctrinally regularity is the proof of love, not occasional intensity. The verse turns from warning to rule, giving a plain daily standard. Its homely food image keeps the teaching grounded: as the body needs meals, so devotion needs its daily portion of sacred names.",
    keyPoints: ["Neglecting the hymn is like ending hunger without food.", "Daily chanting is the devotee's plain standard.", "Regularity proves love more than intensity."],
  },
  {
    id: "ls-uttara-81",
    number: "Uttara 81",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "nānyathā prīyate devī kalpakoṭiśatairapi । tasmādrahasyanāmāni śrīmātuḥ prayataḥ paṭhet",
    translation: "By no other means is the Goddess pleased, even in hundreds of crores of ages. Therefore one should recite the Mother's secret names with discipline and care.",
    commentary: "Exclusivity language seals the exhortation: without these names, vast time alone does not win favor. The practice is disciplined, careful recitation as the sufficient means. Doctrinally the Mother's pleasure rests in being known through Her own thousandfold self-disclosure. The immense time span stresses that delay has no substitute for turning to the hymn. The verse closes encouragement with urgency, calling the hearer to begin steady practice now.",
    keyPoints: ["Vast time without the names does not win favor.", "Disciplined recitation is the sufficient means.", "Urgency joins encouragement to begin now."],
  },
  {
    id: "ls-uttara-82",
    number: "Uttara 82",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "iti te kathitaṁ stotraṁ rahasyaṁ kumbhasambhava । nāvidyāvedine brūyānnābhaktāya kadācana",
    translation: "Thus I have told you this secret hymn, O pot-born sage. Never speak it to one ignorant of the sacred lore, nor ever to the faithless.",
    commentary: "The closing seal restricts transmission to the prepared and the reverent. The practice is quiet guardianship: withhold the text where it would be scorned or misused. Doctrinally secrecy preserves potency, keeping intimate praise from casual handling. Addressing the sage marks personal entrustment, not public broadcast. The restraint is protective rather than harsh, shielding both teaching and unready hearer from mutual harm through premature disclosure.",
    keyPoints: ["The secret hymn is entrusted, not broadcast.", "Withhold it from the ignorant and the faithless.", "Restraint protects both teaching and hearer."],
  },
  {
    id: "ls-uttara-83",
    number: "Uttara 83",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "yathaiva gopyā śrīvidyā tathā gopyamidaṁ mune । paśutulyeṣu na brūyājjaneṣu stotramuttamam",
    translation: "O sage, as the sacred lore itself must be guarded, so this hymn must be guarded. This excellent hymn should not be spoken among beast-like people.",
    commentary: "Guarding the hymn is likened to guarding the sacred lore itself, equal in strictness. The practice is discernment in company, refraining where mockery or dullness prevails. Doctrinally the coarse term denotes unawakened conduct, not birth or status. The verse extends the prior seal with a general rule for assemblies. Its plain tone avoids sensational threat, presenting restraint as ordinary reverence for what is holy and easily profaned by scorn.",
    keyPoints: ["Guard the hymn as the sacred lore is guarded.", "Refrain where scorn or dullness prevails.", "Restraint is ordinary reverence, not harshness."],
  },
  {
    id: "ls-uttara-84",
    number: "Uttara 84",
    section: "Uttara-pīṭhikā · Phalaśruti",
    iast: "yo dadāti vimūḍhātmā śrīvidyārahitāya ca । tasmai kupyanti yoginyaḥ so’narthaḥ sumahānsmṛtaḥ",
    translation: "The deluded person who gives it to one void of the sacred lore offends the circle of Yoginis. That is remembered as a very great fault.",
    commentary: "Unfit transmission is said to disturb the guardian powers attending the Goddess. The practice required is continued discernment in sharing the text and its initiation. Doctrinally the Yoginis embody the protective order around sacred sound, turning misuse back upon the giver. The verse states consequence soberly, without lurid detail. Its function is to close the whole benefit section with responsibility: grace received must be passed on only where it will be honored and upheld.",
    keyPoints: ["Unfit transmission offends the guardian Yoginis.", "Sharing requires continued discernment.", "Grace received carries responsibility in giving."],
  },
];
