// Śiva-sūtra indexes: original finding aids for this app, standing in for the
// function of Singh's back-matter indexes (subject, Sanskrit-word and
// alphabetical-sūtra indexes, pp. 265–278). All entries point at our own verse
// IDs; the alphabetical list quotes only the sūtra incipits themselves (the
// ancient revealed text, public domain), sorted diacritic-blind. No wording is
// taken from Singh's translation, notes or expositions.
export interface SutraIndexEntry {
  id: string;
  iast: string;
  section: string;
}

export interface TermIndexEntry {
  term: string;
  iast: string;
  verseIds: string[];
}

/** All 77 sūtras alphabetically by transliteration (cf. Singh pp. 276–278). */
export const shivaSutrasAlphabeticalIndexEn: SutraIndexEntry[] = [
  { id: "SS-3.40", iast: "abhilāṣādbahirgatiḥ saṃvāhyasya", section: "Āṇavopāya — Section III" },
  { id: "SS-1.10", iast: "aviveko māyāsauṣuptam", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.36", iast: "bhedatiraskāre sargāntarakarmatvam", section: "Āṇavopāya — Section III" },
  { id: "SS-3.42", iast: "bhūtakañcukī tadā vimukto bhūyaḥ patisamaḥ paraḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-1.20", iast: "bhūtasandhānabhūtapṛthaktvaviśvasaṅghaṭṭāḥ", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.45", iast: "bhūyaḥ syātpratimīlanam", section: "Āṇavopāya — Section III" },
  { id: "SS-3.15", iast: "bījāvadhānam", section: "Āṇavopāya — Section III" },
  { id: "SS-1.1", iast: "caitanyam ātmā", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.39", iast: "cittasthitivaccharīrakaraṇabāhyeṣu", section: "Āṇavopāya — Section III" },
  { id: "SS-2.1", iast: "cittaṃ mantraḥ", section: "Śāktopāya — Section II" },
  { id: "SS-3.12", iast: "dhīvaśātsattvasiddhiḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-3.28", iast: "dānamātmajñānam", section: "Āṇavopāya — Section III" },
  { id: "SS-1.14", iast: "dṛśyaṃ śarīram", section: "Śāmbhavopāya — Section I" },
  { id: "SS-2.4", iast: "garbhe cittavikāso'viśiṣṭavidyāsvapnaḥ", section: "Śāktopāya — Section II" },
  { id: "SS-2.6", iast: "gururupāyaḥ", section: "Śāktopāya — Section II" },
  { id: "SS-1.15", iast: "hṛdaye cittasaṅghaṭṭād dṛśyasvāpadarśanam", section: "Śāmbhavopāya — Section I" },
  { id: "SS-1.13", iast: "icchāśaktir umā kumārī", section: "Śāmbhavopāya — Section I" },
  { id: "SS-2.9", iast: "jñānamannam", section: "Śāktopāya — Section II" },
  { id: "SS-1.2", iast: "jñānaṃ bandhaḥ", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.2", iast: "jñānaṃ bandhaḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-1.8", iast: "jñānaṃ jāgrat", section: "Śāmbhavopāya — Section I" },
  { id: "SS-1.4", iast: "jñānādhiṣṭhānaṃ mātṛkā", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.8", iast: "jāgraddvitīyakaraḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-1.7", iast: "jāgratsvapnasuṣuptabhede turyābhogasambhavaḥ", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.3", iast: "kalādīnāṃ tattvānāmaviveko māyā", section: "Āṇavopāya — Section III" },
  { id: "SS-3.37", iast: "karaṇaśaktiḥ svato'nubhavāt", section: "Āṇavopāya — Section III" },
  { id: "SS-3.27", iast: "kathā japaḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-3.19", iast: "kavargādiṣu māheśvaryādyāḥ paśumātaraḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-1.18", iast: "lokānandaḥ samādhisukham", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.23", iast: "madhye'varaprasavaḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-3.21", iast: "magnaḥ svacittena praviśet", section: "Āṇavopāya — Section III" },
  { id: "SS-1.22", iast: "mahāhradānusandhānānmantravīryānubhavaḥ", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.7", iast: "mohajayādanantābhogātsahajavidyājayaḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-3.35", iast: "mohapratisaṃhatastu karmātmā", section: "Āṇavopāya — Section III" },
  { id: "SS-3.6", iast: "mohāvaraṇātsiddhiḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-3.24", iast: "mātrāsvapratyayasaṃdhāne naṣṭasya punarutthānam", section: "Āṇavopāya — Section III" },
  { id: "SS-2.7", iast: "mātṛkācakrasambodhaḥ", section: "Śāktopāya — Section II" },
  { id: "SS-3.43", iast: "naisargikaḥ prāṇasaṃbandhaḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-3.9", iast: "nartaka ātmā", section: "Āṇavopāya — Section III" },
  { id: "SS-3.44", iast: "nāsikāntarmadhyasaṃyamāt kimatra savyāpasavyasauṣumneṣu", section: "Āṇavopāya — Section III" },
  { id: "SS-3.5", iast: "nāḍīsaṃhārabhūtajayabhūtakaivalyabhūtapṛthaktvāni", section: "Āṇavopāya — Section III" },
  { id: "SS-2.2", iast: "prayatnaḥ sādhakaḥ", section: "Śāktopāya — Section II" },
  { id: "SS-3.11", iast: "prekṣakāṇīndriyāṇi", section: "Āṇavopāya — Section III" },
  { id: "SS-3.22", iast: "prāṇasamācāre samadarśanam", section: "Āṇavopāya — Section III" },
  { id: "SS-3.10", iast: "raṅgo'ntarātmā", section: "Āṇavopāya — Section III" },
  { id: "SS-3.13", iast: "siddhaḥ svatantrabhāvaḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-3.31", iast: "sthitilayau", section: "Āṇavopāya — Section III" },
  { id: "SS-3.33", iast: "sukhaduḥkhayorbahirmananam", section: "Āṇavopāya — Section III" },
  { id: "SS-3.17", iast: "svamātrānirmāṇamāpādayati", section: "Āṇavopāya — Section III" },
  { id: "SS-1.9", iast: "svapno vikalpāḥ", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.30", iast: "svaśaktipracayo'sya viśvam", section: "Āṇavopāya — Section III" },
  { id: "SS-3.34", iast: "tadvimuktastu kevalī", section: "Āṇavopāya — Section III" },
  { id: "SS-3.41", iast: "tadārūḍhapramitestatkṣayājjīvasaṅkṣayaḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-3.32", iast: "tatpravṛttāvapyanirāsaḥ saṃvettṛbhāvāt", section: "Āṇavopāya — Section III" },
  { id: "SS-3.38", iast: "tripadādyanuprāṇanam", section: "Āṇavopāya — Section III" },
  { id: "SS-1.11", iast: "tritayabhoktā vīreśaḥ", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.20", iast: "triṣu caturthaṃ tailavadāsecyam", section: "Āṇavopāya — Section III" },
  { id: "SS-1.5", iast: "udyamo bhairavaḥ", section: "Śāmbhavopāya — Section I" },
  { id: "SS-2.5", iast: "vidyāsamutthāne svābhāvike khecarī śivāvasthā", section: "Śāktopāya — Section II" },
  { id: "SS-2.10", iast: "vidyāsaṃhāre tadutthasvapnadarśanam", section: "Śāktopāya — Section II" },
  { id: "SS-3.18", iast: "vidyāvināśe janmavināśaḥ", section: "Āṇavopāya — Section III" },
  { id: "SS-2.3", iast: "vidyāśarīrasattā mantrarahasyam", section: "Śāktopāya — Section II" },
  { id: "SS-1.12", iast: "vismayo yogabhūmikāḥ", section: "Śāmbhavopāya — Section I" },
  { id: "SS-1.17", iast: "vitarka ātmajñānam", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.14", iast: "yathā tatra tathānyatra", section: "Āṇavopāya — Section III" },
  { id: "SS-3.29", iast: "yo'vipastho jñāhetuśca", section: "Āṇavopāya — Section III" },
  { id: "SS-1.3", iast: "yonivargaḥ kalāśarīram", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.16", iast: "āsanasthaḥ sukhaṃ hrade nimajjati", section: "Āṇavopāya — Section III" },
  { id: "SS-3.1", iast: "ātmā cittam", section: "Āṇavopāya — Section III" },
  { id: "SS-1.6", iast: "śakticakrasaṃdhāne viśvasaṃhāraḥ", section: "Śāmbhavopāya — Section I" },
  { id: "SS-1.19", iast: "śaktisaṃdhāne śarīrotpattiḥ", section: "Śāmbhavopāya — Section I" },
  { id: "SS-3.26", iast: "śarīravṛttirvratam", section: "Āṇavopāya — Section III" },
  { id: "SS-2.8", iast: "śarīraṃ haviḥ", section: "Śāktopāya — Section II" },
  { id: "SS-3.4", iast: "śarīre saṃhāraḥ kalānām", section: "Āṇavopāya — Section III" },
  { id: "SS-3.25", iast: "śivatulyo jāyate", section: "Āṇavopāya — Section III" },
  { id: "SS-1.16", iast: "śuddhatattvasaṃdhānād vāpaśuśaktiḥ", section: "Śāmbhavopāya — Section I" },
  { id: "SS-1.21", iast: "śuddhavidyodayāccakreśatvasiddhiḥ", section: "Śāmbhavopāya — Section I" }
];

/** Key Sanskrit terms → sūtras using them (cf. Singh pp. 267–275; refs are our own). */
export const shivaSutrasWordIndexEn: TermIndexEntry[] = [
  { term: "Abhilāṣa", iast: "abhilāṣā", verseIds: ["SS-3.40", "SS-3.41"] },
  { term: "Ābhoga", iast: "ābhoga", verseIds: ["SS-1.7", "SS-3.7"] },
  { term: "Ātmā", iast: "ātmā", verseIds: ["SS-1.1", "SS-3.1", "SS-3.9"] },
  { term: "Aviveka", iast: "aviveka", verseIds: ["SS-1.10", "SS-3.3"] },
  { term: "Bandha", iast: "bandha", verseIds: ["SS-1.2", "SS-3.2"] },
  { term: "Bhairava", iast: "bhairava", verseIds: ["SS-1.5"] },
  { term: "Bhūta", iast: "bhūta", verseIds: ["SS-1.20", "SS-3.5", "SS-3.42"] },
  { term: "Bīja", iast: "bīja", verseIds: ["SS-3.15"] },
  { term: "Caitanya", iast: "caitanya", verseIds: ["SS-1.1"] },
  { term: "Cakra", iast: "cakra", verseIds: ["SS-1.6", "SS-1.21", "SS-2.7"] },
  { term: "Citta", iast: "citta", verseIds: ["SS-1.15", "SS-2.1", "SS-2.4", "SS-3.1", "SS-3.21", "SS-3.39"] },
  { term: "Dṛśya", iast: "dṛśya", verseIds: ["SS-1.14", "SS-1.15"] },
  { term: "Garbha", iast: "garbha", verseIds: ["SS-2.4"] },
  { term: "Guru", iast: "guru", verseIds: ["SS-2.6", "SS-2.7"] },
  { term: "Hrada", iast: "hrada", verseIds: ["SS-1.22", "SS-3.16"] },
  { term: "Hṛdaya", iast: "hṛdaya", verseIds: ["SS-1.15"] },
  { term: "Icchā-śakti", iast: "icchāśakti", verseIds: ["SS-1.13", "SS-1.19"] },
  { term: "Japa", iast: "japa", verseIds: ["SS-3.27"] },
  { term: "Jāgrat", iast: "jāgrat", verseIds: ["SS-1.7", "SS-1.8", "SS-3.8"] },
  { term: "Jīva", iast: "jīva", verseIds: ["SS-3.41"] },
  { term: "Jñāna", iast: "jñāna", verseIds: ["SS-1.2", "SS-1.8", "SS-2.9", "SS-3.2"] },
  { term: "Kalā", iast: "kalā", verseIds: ["SS-1.3", "SS-3.3", "SS-3.4"] },
  { term: "Karaṇa", iast: "karaṇa", verseIds: ["SS-3.37", "SS-3.39"] },
  { term: "Karma-ātmā", iast: "karmātmā", verseIds: ["SS-3.35"] },
  { term: "Kathā", iast: "kathā", verseIds: ["SS-3.27"] },
  { term: "Kevalī", iast: "kevalī", verseIds: ["SS-3.34"] },
  { term: "Khecarī", iast: "khecarī", verseIds: ["SS-2.5"] },
  { term: "Madhya", iast: "madhya", verseIds: ["SS-3.23", "SS-3.44"] },
  { term: "Mantra", iast: "mantra", verseIds: ["SS-1.22", "SS-2.1", "SS-2.3"] },
  { term: "Mātṛkā", iast: "mātṛkā", verseIds: ["SS-1.4", "SS-2.7", "SS-3.19"] },
  { term: "Māyā", iast: "māyā", verseIds: ["SS-1.10", "SS-3.3"] },
  { term: "Moha", iast: "moha", verseIds: ["SS-3.6", "SS-3.7", "SS-3.35"] },
  { term: "Nartaka", iast: "nartaka", verseIds: ["SS-3.9"] },
  { term: "Niyati (implied in kalādi)", iast: "kalādi", verseIds: ["SS-3.3"] },
  { term: "Pramiti / Pramātā", iast: "pramiti", verseIds: ["SS-3.41"] },
  { term: "Prāṇa", iast: "prāṇa", verseIds: ["SS-3.5", "SS-3.22", "SS-3.43"] },
  { term: "Raṅga", iast: "raṅga", verseIds: ["SS-3.10"] },
  { term: "Sahaja-vidyā", iast: "sahajavidyā", verseIds: ["SS-3.7"] },
  { term: "Sama-darśana", iast: "samadarśana", verseIds: ["SS-3.22"] },
  { term: "Saṃhāra", iast: "saṃhāra", verseIds: ["SS-1.6", "SS-2.10", "SS-3.4", "SS-3.5"] },
  { term: "Saṃvettṛ", iast: "saṃvettṛ", verseIds: ["SS-3.32"] },
  { term: "Siddha / Siddhi", iast: "siddha, siddhi", verseIds: ["SS-1.21", "SS-3.6", "SS-3.12", "SS-3.13"] },
  { term: "Sthiti / Laya", iast: "sthiti, laya", verseIds: ["SS-3.31"] },
  { term: "Svapna", iast: "svapna", verseIds: ["SS-1.7", "SS-1.9", "SS-2.4", "SS-2.10"] },
  { term: "Svātantrya (bhāva)", iast: "svatantrabhāva", verseIds: ["SS-3.13"] },
  { term: "Turya", iast: "turya", verseIds: ["SS-1.7", "SS-1.11", "SS-3.38"] },
  { term: "Udyama", iast: "udyama", verseIds: ["SS-1.5"] },
  { term: "Vidyā", iast: "vidyā", verseIds: ["SS-1.21", "SS-2.3", "SS-2.4", "SS-2.5", "SS-2.10", "SS-3.18"] },
  { term: "Vikalpa", iast: "vikalpa", verseIds: ["SS-1.9", "SS-1.17"] },
  { term: "Vīra / Vīreśa", iast: "vīra, vīreśa", verseIds: ["SS-1.11", "SS-1.22"] },
  { term: "Vismaya", iast: "vismaya", verseIds: ["SS-1.12"] },
  { term: "Vitarka", iast: "vitarka", verseIds: ["SS-1.17"] },
  { term: "Vrata", iast: "vrata", verseIds: ["SS-3.26"] },
  { term: "Yoni / Varga", iast: "yoni, varga", verseIds: ["SS-1.3"] }
];

/** Subjects → sūtras (cf. Singh pp. 265–266; mapping is our own). */
export const shivaSutrasSubjectIndexEn: TermIndexEntry[] = [
  { term: "Absolute (Self as consciousness)", iast: "caitanya-ātmā", verseIds: ["SS-1.1", "SS-3.9", "SS-3.25", "SS-3.42"] },
  { term: "Bondage (limited knowing, malas)", iast: "bandha, mala", verseIds: ["SS-1.2", "SS-1.3", "SS-1.4", "SS-1.10", "SS-3.1", "SS-3.2", "SS-3.3", "SS-3.18", "SS-3.35", "SS-3.40"] },
  { term: "Liberation — Śāmbhavopāya", iast: "śāmbhavopāya", verseIds: ["SS-1.5", "SS-1.6", "SS-1.12", "SS-1.13", "SS-1.15", "SS-1.16"] },
  { term: "Liberation — Śāktopāya", iast: "śāktopāya", verseIds: ["SS-1.17", "SS-2.1", "SS-2.2", "SS-2.3", "SS-2.4", "SS-2.5"] },
  { term: "Liberation — Āṇavopāya", iast: "āṇavopāya", verseIds: ["SS-3.1", "SS-3.4", "SS-3.5", "SS-3.12", "SS-3.15", "SS-3.16", "SS-3.43", "SS-3.44"] },
  { term: "Guru and grace", iast: "guru, śaktipāta", verseIds: ["SS-2.6", "SS-2.7", "SS-3.28", "SS-3.29"] },
  { term: "Mantra and Mātṛkā", iast: "mantra, mātṛkā", verseIds: ["SS-1.4", "SS-1.22", "SS-2.1", "SS-2.3", "SS-2.7", "SS-2.8", "SS-2.9", "SS-3.15", "SS-3.19", "SS-3.27"] },
  { term: "Three states and the Fourth", iast: "avasthā, turya", verseIds: ["SS-1.7", "SS-1.8", "SS-1.9", "SS-1.10", "SS-1.11", "SS-3.8", "SS-3.20", "SS-3.21", "SS-3.22", "SS-3.38", "SS-3.39", "SS-3.45"] },
  { term: "Powers: warning and mastery", iast: "siddhi, moha", verseIds: ["SS-1.19", "SS-1.20", "SS-1.21", "SS-2.4", "SS-3.6", "SS-3.7", "SS-3.17", "SS-3.36", "SS-3.37"] },
  { term: "Freedom and world-authorship", iast: "svātantrya", verseIds: ["SS-1.13", "SS-3.9", "SS-3.10", "SS-3.11", "SS-3.13", "SS-3.14", "SS-3.30", "SS-3.31", "SS-3.32"] },
  { term: "Recognition-conduct (jīvanmukti)", iast: "pratyabhijñā", verseIds: ["SS-1.14", "SS-1.18", "SS-3.25", "SS-3.26", "SS-3.27", "SS-3.28", "SS-3.32", "SS-3.33", "SS-3.34", "SS-3.42"] },
  { term: "Craving, relapse and recovery", iast: "abhilāṣa, pramāda", verseIds: ["SS-2.10", "SS-3.23", "SS-3.24", "SS-3.40", "SS-3.41"] },
  { term: "Body, breath and senses", iast: "śarīra, prāṇa, indriya", verseIds: ["SS-1.6", "SS-2.8", "SS-3.5", "SS-3.11", "SS-3.12", "SS-3.22", "SS-3.37", "SS-3.39", "SS-3.43", "SS-3.44"] },
  { term: "Bliss and wonder", iast: "ānanda, vismaya", verseIds: ["SS-1.11", "SS-1.12", "SS-1.18"] }
];
