import { parseGitaVerseRef } from './gitaDocument';

/**
 * Rāmakaṇṭha commentary passages (Phase 6 pilot: eleven bounded excerpts;
 * Phase 7 Chapter-13 edition: eleven further bounded excerpts).
 *
 * Transcription policy (see docs/scholarly/bhagavad-gita-ramakantha-source-text.md
 * and docs/scholarly/bhagavad-gita-chapter-13-rama-kantha-edition.md):
 * - Source: the inspected file's text layer (`Gitasarvatobhadrarajanka.pdf`,
 *   Drive ID 10InuCi5WpCHkDWzT3_iZcybksGDs4_so), human-reviewed token by
 *   token against extraction in this session. NOT collated against page
 *   images — recorded as a limitation, not hidden.
 * - Verification levels: Phase-6 records use `verified-source` (which means
 *   text-layer-reviewed, never page-image-collated); Phase-7 Chapter-13
 *   records use the explicit `text-layer-reviewed` status. No record claims
 *   `page-image-collated` or `partially-collated`: page images were
 *   unavailable, so collation remains future work.
 * - Joined only unambiguous end-of-line hyphens (print layout, not
 *   content); stripped zero-width format chars (U+200C/200D/FEFF).
 * - Retained verbatim: spaces, variant spellings (गुणमय, सेवे-class),
 *   punctuation, quote glyphs, dandas. Footnotes and running heads
 *   excluded (apparatus lives elsewhere).
 * - Mūla verses excluded even inside gloss flow (root-text import is a
 *   separate future phase).
 * - `[?]` marks unresolvable readings inline, each documented in `note`.
 *   `लक्ष[ण]` brackets supply a single dropped akṣara where grammar
 *   admits exactly one reading (standard diplomatic supply).
 * - No field for normalized text exists by design: diplomatic text is
 *   never overwritten, and normalization was not justified.
 */

export type PassageStatus =
  | 'verified-source'
  | 'text-layer-reviewed'
  | 'page-image-collated'
  | 'partially-collated'
  | 'extraction-unreviewed'
  | 'partially-verified';

export interface GitaCommentaryText {
  id: string;
  /** Passage span, when the evidence sits in a demarcated region. */
  spanId?: string;
  /** Canonical units the passage belongs to. */
  unitIds: string[];
  /** KSTS refs, fully qualified. */
  ksts: string[];
  pdf: number;
  folio: number;
  sourceId: string;
  /** Diplomatic transcription (Devanagari only — enforced). */
  text: string;
  status: PassageStatus;
  /** Boundaries, anomalies, [?] keys — required wherever [?] appears. */
  note?: string;
}

export const KSTS_SOURCE_ID = 'bhagavad-gita-source-ksts-64';

export const GITA_COMMENTARY_TEXTS: GitaCommentaryText[] = [
  {
    id: 'gita-tx-13.1-glosa',
    spanId: 'gita-seg-13.1-glosa',
    unitIds: ['13.2'],
    ksts: ['13.1'],
    pdf: 287,
    folio: 277,
    sourceId: KSTS_SOURCE_ID,
    status: 'verified-source',
    text: '‘इदं’ सर्वप्रमातृप्रसिद्धतया व्यवस्थितं ‘शरीर’ देहः क्षेत्रसाधर्म्यात् ‘क्षेत्रमिति’ उच्यते क्षेत्रसंज्ञया कथ्यते । यथा कुसूलादिगतानां धान्यादिबीजानां मूलस्तम्बशाखाशिलादिविशेषप्रसवाभिव्यक्त्यधिकरणः पृथिव्युद्देशः क्षेत्रमित्युच्यते, तथा कर्माशयसंभूतानां कर्मणां जात्यायुर्भोगलक्षणविपाकविशेषाभिव्यक्त्यधिकरणभूतं शरीरमपि इदं क्षेत्रमिति उच्यते । तेन तत्कर्मविपाकास्पदत्वेन यदनुभूयते, तत् शरीरमिति वेदितव्यम् ।',
    note: 'Bounded: gloss opening through the śarīra conclusion (excludes following etat-gloss). Hyphens joined: क्षेत्रसा-धर्म्यात्, कुसूला-दिगतानां, प्रसवा-भिव्यक्ति, कर्मा-शय, विपाका-स्पदत्वेन.',
  },
  {
    id: 'gita-tx-13.2-nanu',
    spanId: 'gita-ps-13.2-nanu',
    unitIds: ['13.2', '13.3'],
    ksts: ['13.1', '13.2'],
    pdf: 287,
    folio: 277,
    sourceId: KSTS_SOURCE_ID,
    status: 'verified-source',
    text: 'ननु परमार्थत एक एव प्रमाता प्रतिपादितः । प्रतिक्षेत्रं च पृथक्पृथक् वेदकप्रतीतिरबाधिता व्यवस्थिता, इति स्वसिद्धान्तविरोधभ्रान्तिं परिहर्तुमाह -',
    note: 'Bounded: objection through the introducing parihartum (verse excluded: mūla import is separate). Hyphen joined: स्वसिद्धान्त-विरोध.',
  },
  {
    id: 'gita-tx-13.2-resolution',
    spanId: 'gita-seg-13.2-resolution',
    unitIds: ['13.3'],
    ksts: ['13.2'],
    pdf: 288,
    folio: 278,
    sourceId: KSTS_SOURCE_ID,
    status: 'verified-source',
    text: 'इह वेदकत्वमात्रमेकमव्यभिचारि असाधारणमात्मनो लक्षणमुक्तम् । अतः परस्परभिन्नानां क्षणिकनानावस्थाजुषां वेद्यानां शरीराणामेव भिन्नरूपत्वं व्यवस्थितम् । न तु वेदकत्वमात्रतयैव तदधिष्ठायकत्वेन व्यवस्थितस्य पारमार्थिकस्य एकस्य वेदकस्य आत्मनो नानात्वमस्ति सर्वदेहगतत्वेऽपि वेदकैकलक्षणाव्यभिचारात् । या तु प्रतिशरीरं जात्यवच्छेदेन पृथक् प्रतिपत्तिः, तदचिन्त्येश्वरमायाशक्तिविलसितमेव । अतस्तयुदासार्थमेव[?] च अयमुपदेशः प्रबुद्धान्प्रति अर्जुनमुखेन उच्यते ।',
    note: 'Bounded: resolution gloss through the address close. ZWNJ stripped (तदधिष्ठायकत्वेन); hyphen joined (वेदकैकलक्षणाव्यभिचा-रात्, अचिन्त्येश्व-रमायाशक्ति). [?]: अतस्तयुदासार्थमेव retained verbatim (print possibly तदुदासार्थम्); लक्ष[ण] supplies one dropped akṣara (लक्षणमुक्तम् admits no other reading).',
  },
  {
    id: 'gita-tx-2.39-tail',
    spanId: 'gita-seg-2.39-tail',
    unitIds: ['2.38'],
    ksts: ['2.39'],
    pdf: 48,
    folio: 38,
    sourceId: KSTS_SOURCE_ID,
    status: 'verified-source',
    text: 'एवं ज्ञानक्रियासमुच्चयमेव उपदेश्यतया विनिश्चित्य, ज्ञानविषयां मतिमुक्तकल्पां[?] मत्वा, तां क्रियाविषयां वक्तमुपक्रममाणस्त एव ज्ञानकर्मणी सांख्ययोगशब्दाभ्यां व्यवहरन्नाह',
    note: 'Bounded: closing sentence before KSTS 2.40 verse (mūla excluded). Hyphen joined (उपक्रममा-णस्त). [?]: मतिमुक्तकल्पां retained verbatim (spacing uncertain).',
  },
  {
    id: 'gita-tx-3-avat',
    spanId: 'gita-ps-3-avat',
    unitIds: ['3.1'],
    ksts: [],
    pdf: 71,
    folio: 61,
    sourceId: KSTS_SOURCE_ID,
    status: 'verified-source',
    text: 'अथ तृतीयोऽध्यायः । अथ ज्ञानस्य कर्मणश्च भगवद्भाषितानि पृथक् प्रशंसावचनानि अनुविमृशन् सम्यक् समुच्चयार्थमनवधार्य किमेतयोरुपादेयतरं स्यादिति संशयानो भगवन्तमर्जुन उवाच',
    note: 'Bounded: chapter opening through the speaker label (verses excluded). Hyphen joined (प्रशंसावच-नानि).',
  },
  {
    id: 'gita-tx-4-avat',
    spanId: 'gita-ps-4-avat',
    unitIds: ['4.1'],
    ksts: [],
    pdf: 102,
    folio: 92,
    sourceId: KSTS_SOURCE_ID,
    status: 'verified-source',
    text: 'अथ चतुर्थोऽध्यायः । एवमस्य समस्ताध्यात्मशास्त्रसर्वस्वभूतार्थगर्भस्य प्रकरणस्य ज्ञानकर्मसमुच्चयलक्षणमभिधेयं परमात्मसमापत्तिलक्षणं च प्रयोजनं प्रतिपाद्य इदानीं सम्बन्धविषययोः प्रतिपादनद्वारेण अर्जुनस्य आत्मनि पुरुषत्वमात्रप्रतिपत्तिव्यामोहनिवृत्तये परमकारणतामाविष्कुर्वन् भगवानुवाच',
    note: 'Bounded: chapter opening through the speaker label (verses excluded). Hyphen joined (प्रयो-जनं, अर्जु-नस्य).',
  },
  {
    id: 'gita-tx-5.3-sent',
    unitIds: ['5.3'],
    ksts: ['5.3'],
    pdf: 127,
    folio: 117,
    sourceId: KSTS_SOURCE_ID,
    status: 'verified-source',
    text: 'समुच्चयानुष्ठाता कुर्वन्नपि कर्माणि नित्यं संन्यासी सदात्यक्तकर्मा बोद्धव्यः ।',
    note: 'Bounded: single sentence in the 5.3 gloss (no print-demarcated sub-span; unit-level evidence). Hyphen joined (सदात्यक्त-कर्मा).',
  },
  {
    id: 'gita-tx-7.14-def',
    unitIds: ['7.14'],
    ksts: ['7.14'],
    pdf: 175,
    folio: 165,
    sourceId: KSTS_SOURCE_ID,
    status: 'verified-source',
    text: '‘एषा हि गुणमय देवी साया[?]’ इत्थं देवनात् क्रीडनात् देवस्य सतो मम संबन्धिनी असती अपि सत्यवदाभासयन्ती मदीया शक्तिः ।',
    note: 'Bounded: definition core (excludes following parā-śakti elaboration). [?]: साया retained verbatim (print likely माया); गुणमय retained verbatim (gloss spelling against verse गुणमयी).',
  },
  {
    id: 'gita-tx-7.14-q2',
    spanId: 'gita-seg-7.14-q2',
    unitIds: ['7.14'],
    ksts: ['7.14'],
    pdf: 176,
    folio: 166,
    sourceId: KSTS_SOURCE_ID,
    status: 'verified-source',
    text: 'ननु यथेवेमेषा न केनचिदन्यथाकर्तुं पार्यते, तत् सर्वथा संसारविभ्रमानुपरमे प्रसक्ते निरर्थक एव अयमपवर्गमार्गाप्युपायोपदेश इति ।',
    note: 'Bounded: objection through its close (response excluded). Hyphen joined (संसार-विभ्रम).',
  },
  {
    id: 'gita-tx-7.14-resp',
    spanId: 'gita-seg-7.14-response',
    unitIds: ['7.14'],
    ksts: ['7.14'],
    pdf: 176,
    folio: 166,
    sourceId: KSTS_SOURCE_ID,
    status: 'verified-source',
    text: 'अत्र आह ‘मामेव’ एकं यथोक्तस्वरूपं परमेश्वरं परमात्मानं मदनुप्रद्देच्छाबोधिताः[?] सन्तो ‘ये प्रपद्यन्ते’ मदभेदपर्यवसायिना यथोक्तेन ज्ञानेन समाश्रयन्ते, ‘ते’ एनां ‘अतितरन्ति’ अतिक्रामन्ति ।',
    note: 'Bounded: response through the crossing close (prabhākara simile excluded). [?]: मदनुप्रद्दे retained verbatim (possibly मदनुग्रहेच्छा). Spaces retained (padaccheda may be print’s own).',
  },
  {
    id: 'gita-tx-18.61-maya',
    spanId: 'gita-ps-18.61-maya',
    unitIds: ['18.61'],
    ksts: ['18.61'],
    pdf: 406,
    folio: 396,
    sourceId: KSTS_SOURCE_ID,
    status: 'verified-source',
    text: '‘एष’ प्रबन्धतः पुनः पुनः प्रतिपादित ‘ईश्वरः’ परमात्मा सर्वभूतानां समस्तप्राणिनां ‘हृदि’ हृदये सर्वसंविद्धिकरणभूते देशे ‘वसति’ नित्यं प्रतिष्ठति । किं कुर्वन् । यत् किञ्चिदेषां सर्वभूतानां ज्ञानात्मकं क्रियात्मकं वा परिस्पन्दितं, तत् सर्व स एव एकः परमार्थतः कुर्वन्नपि मायाशक्त्यवभासित परस्पर विभिन्ननानारूपाणि तानि ‘सर्वभूतानि’ प्रत्येकमहंकरोमीति सिध्याभिमाननिवेशनेन ‘भ्रामयन्’ व्यामोहयन् ।',
    note: 'Bounded: gloss core through the bhrāmayan close (कथमिव-question excluded). Hyphens joined (प्रत्येकम-हंकरोमीति, सिध्या-भिमान); quote-glyph mix ("सर्वभूतानां’) retained as extraction noise class; spaces retained.',
  },
  {
    id: 'gita-tx-13-avat',
    spanId: 'gita-ps-13-avat',
    unitIds: ['13.2'],
    ksts: [],
    pdf: 286,
    folio: 276,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'इदानीं शरीरशरीरिभावेन व्यवस्थितायास्तस्या उद्वेष्टनोपायभूतत्वेन ज्ञानस्य निर्णयार्थ समनन्तरमध्यायमारभते ।',
    note: 'Bounded: chapter-gateway purpose sentence (excludes following tayoh exposition). No hyphens; no [?]. Mūla excluded by policy.',
  },
  {
    id: 'gita-tx-13.3-gloss',
    spanId: 'gita-seg-13.3-gloss',
    unitIds: ['13.4'],
    ksts: ['13.3'],
    pdf: 289,
    folio: 279,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तस्मिश्च क्षेत्रे ‘यत्’ वस्तु ‘विकारि’ विशिष्टकार्यकारणत्वात् विकारवत् विकारसंयुक्तं, तदपि ‘शृणु’ ।',
    note: 'Bounded: vikāri gloss sentence (excludes preceding tat-definition and following yataśca exposition). No hyphens; no [?].',
  },
  {
    id: 'gita-tx-13.5-gloss',
    spanId: 'gita-seg-13.5-gloss',
    unitIds: ['13.6'],
    ksts: ['13.5'],
    pdf: 290,
    folio: 280,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: '‘एतत्’ महाभूतादिवस्तुसमुदायात्मकं ‘क्षेत्र’ विकारसंयुक्तं विकारग्रहणात् प्रकृतिभूतसंयुक्तमपि संक्षेपेण कथितम् ।',
    note: 'Bounded: kṣetra-saṅgraha sentence (excludes preceding mahābhūta analysis and following ṣoḍaśaka exposition). No hyphens; no [?].',
  },
  {
    id: 'gita-tx-13.6-iccha',
    spanId: 'gita-seg-13.6-iccha',
    unitIds: ['13.7'],
    ksts: ['13.6'],
    pdf: 291,
    folio: 281,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'कैश्चिदिच्छाद्वेषसुखदुःखादय आत्मधर्मत्वेन अभ्युपगतास्ते वेद्यत्वात्क्षेत्रमेव । तथा शरीरिन्द्रियादिसमुदायः ‘संघातः’ । ‘चेतना’ चेत्यतेऽनयेति कृत्वा ज्ञानं बुद्धिवृत्तिः । ‘धृतिः’ प्राणादिधारणानिबन्धनमहंप्रत्ययः ।',
    note: 'Bounded: icchā-ādi definitions through the dhṛti close (excludes following pramātṛ puzzle). Hyphens joined (सुखदुःखा-दय, शरीरे-न्द्रियादि). No [?].',
  },
  {
    id: 'gita-tx-13.11-ajnana',
    spanId: 'gita-seg-13.11-ajnana',
    unitIds: ['13.12'],
    ksts: ['13.11'],
    pdf: 296,
    folio: 286,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'अत उक्तात् गुणसमूहात् ‘अन्यथा’ अन्येन विपरीतेन प्रकारेण मानित्वदम्भित्वादिना यत्स्थितं, तत्सर्व ‘अज्ञानं’ ज्ञानविपरीतं वेदितव्यम् ।',
    note: 'Bounded: ajñāna close (excludes preceding jñānam-iti-proktam sentence and following devāsura promise). No hyphens; no [?].',
  },
  {
    id: 'gita-tx-13.12-jneya-resp',
    spanId: 'gita-seg-13.12-jneya-resp',
    unitIds: ['13.13'],
    ksts: ['13.12'],
    pdf: 297,
    folio: 287,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'सत्यं, न तस्य वस्तुनः परमार्थतो ज्ञेयता संभवति । किन्तु आरुरुक्षावस्थायां ज्ञातृज्ञानज्ञेय विभागात्मकत्वादुपचारेण ज्ञेयशब्दस्तत्र प्रवर्तते, नतु वास्तवेन रूपेण तस्य ज्ञेयता विवक्षिता ।',
    note: 'Bounded: satyam response (excludes preceding nanu question on ananya-saṃvedya and following tadviśeṣaṇa introduction). Hyphen joined (आरुरुक्षा-वस्थायां). Spaces retained as extracted (ज्ञातृज्ञानज्ञेय विभागात्मकत्वात्, नतु). No [?].',
  },
  {
    id: 'gita-tx-13.12-anadi',
    spanId: 'gita-seg-13.12-anadi',
    unitIds: ['13.13'],
    ksts: ['13.12'],
    pdf: 298,
    folio: 288,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तद्विपरीतं तु कारणान्तरनिरपेक्षसद्भावं ‘अनादिमत् परं ब्रह्म’ इत्युक्तम् ।',
    note: 'Bounded: anādimat sentence (excludes preceding ādimat analysis and following na-sat exposition). Hyphen joined (‘अनादि-मत्). No [?].',
  },
  {
    id: 'gita-tx-13.19-prakrti',
    spanId: 'gita-seg-13.19-prakrti',
    unitIds: ['13.20'],
    ksts: ['13.19'],
    pdf: 301,
    folio: 291,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'यैषा ‘प्रकृतिः’ सप्तमेऽध्याये विषयभावेन, संप्रति शरीरभावेन विभज्य प्रतिपादितस्वरूपा, तथैव यः ‘पुरुषः’ विषयित्वेन शरीरित्वेन प्रतिपादितः, एतावेव अन्योन्यसंबद्धत्वेन ‘अनादी विद्धि’ जानीहि ।',
    note: 'Bounded: prakṛti-puruṣa recall sentence (excludes preceding saṅgraha introduction and following anāditva-tātparya). Hyphen joined (शरीरभा-वेन). ‘अनादी विद्धि’ retained verbatim. No [?].',
  },
  {
    id: 'gita-tx-13.20-karya',
    spanId: 'gita-seg-13.20-karya',
    unitIds: ['13.21'],
    ksts: ['13.20'],
    pdf: 301,
    folio: 291,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'कार्य महाभूताद्यात्मकं, कारणानि बाह्याभ्यन्तराणि इन्द्रियाणि, इति शरीराद्यात्मकः समूहः कार्यकारणशब्देन उच्यते ।',
    note: 'Bounded: kārya-kāraṇa definition sentence (excludes following kartṛtve-hetu exposition). Hyphen joined (इन्द्रि-याणि). No [?].',
  },
  {
    id: 'gita-tx-13.22-mahesvara',
    spanId: 'gita-seg-13.22-mahesvara',
    unitIds: ['13.23'],
    ksts: ['13.22'],
    pdf: 303,
    folio: 293,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: '‘महेश्वरः’ सर्वपुरुषैश्वर्यापेक्षया महानत्युत्कृष्ट ईश्वरः प्रभुः परब्रह्मशब्दापरपर्यायः स्वमायोद्भावितपुरुषव्यपेक्षया देहेऽस्मिन्नुपद्रष्टा भर्ता अनुमन्ता भोक्ता च’ इति व्यवस्थितः ।',
    note: 'Bounded: maheśvara sentence through the vyavasthitaḥ close (excludes following upadraṣṭā analysis). Hyphen joined (देहेऽस्मि-नुपद्रष्टा). No [?].',
  },
  {
    id: 'gita-tx-13.34-synthesis',
    spanId: 'gita-seg-13.34-synthesis',
    unitIds: ['13.35'],
    ksts: ['13.34'],
    pdf: 311,
    folio: 301,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: '‘ये’ योगिनः ‘एवं’ उक्तेन प्रकारेण क्षेत्रस्य शरीरभावेन परिणताया अपरायाः प्रकृतेः, तथा क्षेत्रज्ञस्य नानाक्षेत्राहकारावष्टम्भेन अवस्थिताया जीवरूपायाः परायाः प्रकृतेः ‘अन्तरं विशेषं परस्पर विविक्तं स्वरूपं ‘विदुः’ जानते ।',
    note: 'Bounded: antara gloss sentence (excludes following kena/jñāna-cakṣuṣā exposition and bhūtaprakṛtimokṣa close). Hyphen joined (नानाक्षेत्राहका-रावष्टम्भेन). अहकार for expected अहङ्कार retained verbatim (ṅ may be extraction loss; uncollated against page images). Spaces retained (परस्पर विविक्तं). No [?].',
  },
  // Phase-8 Chapter-13 corpus completion passages (62 bounded excerpts,
  // all `text-layer-reviewed`: page images genuinely unavailable, so no
  // record claims collation). Mūla verses, verse-number markers, running
  // heads, folio fragments and footnotes excluded throughout (apparatus
  // lives in the inventory); print locators inside commentary retained
  // except the single (७।१८) whose extraction renders the danda as `/`
  // (locator preserved instead in gita-xref-055).
  {
    id: 'gita-tx-13.1-etat',
    spanId: 'gita-seg-13.1-etat',
    unitIds: ['13.2'],
    ksts: ['13.1'],
    pdf: 287,
    folio: 277,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: '‘एतत्’ च एवंविधं क्षेत्रं ‘यो वेद’ जानाति, ‘तं तद्विदः’ क्षेत्रज्ञस्वरूपज्ञाः ‘क्षेत्रज्ञ मिति’ विदुर्जानते । किमनेन उक्तं भवति । अस्मिन् शरीरे द्विप्रकारा प्रतिपत्तिरेव स्थिता सर्वदेहिना महन्तया इदन्तया च । तथाच - ‘अहं ब्राह्मणो यज्ञदत्तः’ इत्यादिना देहमहन्तया व्यवस्यन्ति, कदाचित् ‘ममेदं शरीर’ इतीदन्तया व्यवस्यन्ति, अतो व्यवसायिता प्रमाता तावत् कश्चिदा विद्यत एव । यश्च अंशः प्रमातृतया प्रतीयते, स क्षेत्रज्ञो जीवश्वेतनः इति प्रतिपत्तव्यः । एवमस्मिन् शरीरे यद्यत् वेद्यतया वेदकसंबन्धमात्रात् प्रतीयते, तत् क्षेत्रांशतया वेदितव्यम् । योऽसौ वेदकतया प्रतीयते, स क्षेत्रज्ञ आत्मा इति वेदितव्यः ।',
    note: 'Bounded: etat pratīka through the vedaka exhibit close (excludes the śarīra gloss before and the nityāvahitatva turn after). Hyphen joined (व्यव-स्यन्ति). कश्चिदा, जीवश्वेतनः and यश्च अंशः retained verbatim as extracted; uncollated against page images. No [?].',
  },
  {
    id: 'gita-tx-13.1-tatparya',
    spanId: 'gita-seg-13.1-tatparya',
    unitIds: ['13.2'],
    ksts: ['13.1'],
    pdf: 287,
    folio: 277,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'एतावत्येव नित्यावहितत्वं शरीरशरीरिणोर्विवेकज्ञानकारणम् । तच्च वेद्यवेदकसंबन्धमात्रनिबन्धनसकलपरापरव्यवहाराणामपि सर्वदेहिनां मायानिमीलिततत्त्वदृशां स्वप्नेऽपि न उन्मिषति, यावदीश्वरानुग्रहशत्यैव सा तत्त्वदृक् तेषां न उन्मीलिता । तेन अनुगृहीत एव विषयोऽस्य ज्ञानस्य, इति तात्पर्यम् । यत उक्तम् तद्विदः केचनैव योगिनस्तं विदुरिति ।',
    note: 'Bounded: nityāvahitatva turn through the verse close (verse-number marker excluded). Hyphens joined (शरीरशरी-रिणो, निबन्धनस-कल, विदु-रिति). Runs to printed p.278; cross-page sentence joined with a space. अनुग्रहशत्यैव retained verbatim (extraction for शक्त्यैव uncertain); uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.2-sarvaksetra',
    spanId: 'gita-seg-13.2-sarvaksetra',
    unitIds: ['13.3'],
    ksts: ['13.2'],
    pdf: 288,
    folio: 278,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: '‘सर्वक्षेत्रेषु’ चतुर्दशविधभूतसर्गभेदेन अवस्थितेषु अपरिसंख्येयेषु शरीरेषु एकमेव ‘मां क्षेत्रज्ञ परमात्मानं ‘विद्धि’ जानीहि । यथा एकक्षेत्रगतनानावयववेदकत्वेनैव क्षेत्रज्ञप्रतीतिर्मायादशायामवस्थिता, तथा समस्तशरीरवेदकत्वेन एकः पारमार्थिकोऽहमेव क्षेत्रज्ञः । ततश्च एवंविधयोः ‘क्षेत्रक्षेत्रज्ञयोर्यज्ज्ञानं’ सम्यप्रतिपत्तिस्तदेव ‘मम मतं ज्ञानत्वेन अभिप्रेतम् । नतु सांख्यादिप्रतिपादितयोः शरीरशरीरिणोर्विवेकज्ञानमात्रं तात्त्विकं ज्ञानमिति तात्पर्यम् ।',
    note: 'Bounded: sarvakṣetreṣu pratīka through the verse close (verse-number marker excluded). Hyphens joined (भूत-सर्ग, वेदक-त्वेन, वेद-कत्वेन, क्षेत्र-क्षेत्रज्ञ, विवेक-ज्ञान). Unclosed ‘मां क्षेत्रज्ञ, विद्धि for विद्धि and सम्यप्रतिपत्ति retained verbatim; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.3-intro',
    spanId: 'gita-seg-13.3-intro',
    unitIds: ['13.4'],
    ksts: ['13.3'],
    pdf: 288,
    folio: 278,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'इदानीं नानादर्शन भेदेन व्यवस्थापितनाना रूपस्य अपि क्षेत्रस्य वेद्यत्वमात्रसामान्यलक्षणाभेदात् कांचिदेव दर्शन प्रक्रियामाश्रित्य तत्स्वरूपे प्रतिपादयितव्ये वेदाद्यागमप्रसिद्धसांख्यप्रक्रियासमायणेन प्रतिपादयिष्यमाणक्षेत्रस्य स्वरूप पक्षेप्तमाह -',
    note: 'Bounded: idānīṃ turn through the verse-introducing dash (mūla verses excluded). Hyphen joined (समा-यणेन). Runs to printed p.279. Spaces (नानादर्शन भेदेन, दर्शन प्रक्रिया) and पक्षेप्तमाह retained verbatim; uncollated. Trailing dash introduces the excluded mūla. No [?].',
  },
  {
    id: 'gita-tx-13.3-tat',
    spanId: 'gita-seg-13.3-tat',
    unitIds: ['13.4'],
    ksts: ['13.3'],
    pdf: 289,
    folio: 279,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: '‘तत्’ क्षेत्रज्ञज्ञेयतया उपक्रान्तं ‘क्षेत्रं यत्’ यभिधानमित्यर्थः, तथा ‘यादृक’ यादृशेन प्रकार भेदेन स्थितं ‘तत्’ संक्षेपेण अवधारय । तस्मिश्च क्षेत्रे ‘यत्’ वस्तु ‘विकारि’ विशिष्टकार्यकारणत्वात् विकारवत् विकारसंयुक्तं, तदपि ‘शृणु’ । तथा ‘यतश्च’ विकारिणो ‘यत्’ विकारभूतं वस्तु उपपद्यते, तदपि शृणु । तथा ‘स च’ क्षेत्रज्ञ एवमेव ‘यो’ यत्पर्यायो ‘यत्स्वभावः’ यादृशश्च, तत्सवै संग्रहेण उच्यमानमवधारय ।',
    note: 'Bounded: tat pratīka through the saṅgraha turn (excludes the ṛṣibhiḥ gloss after). Hyphen joined (अवधा-रय). यभिधानमित्यर्थः, प्रकार भेदेन and तत्सवै retained verbatim; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.4-rsibhi',
    spanId: 'gita-seg-13.4-rsibhi',
    unitIds: ['13.5'],
    ksts: ['13.4'],
    pdf: 289,
    folio: 279,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'अस्य वस्तुनः स्मृतिश्रुतिप्रसिद्धत्वप्रतिपादनार्थमाह ‘ऋषिभिः’ स्मृतिकर्तृभिः ‘बहुधा’ बहुप्रकारं तत्र तत्र स्मृतिशास्त्रेषु ‘गीतम्’ । तथा ‘छन्दोभिर्विविधैः वेदशाखाभेदेन नानारूपैरत एव ‘पृथक् पृथक् प्रकरणभेदेन गीतम् । ‘ब्रह्मसूत्रपदैः’ ब्रह्मसूत्रशब्देन रहस्यभागो वेदस्य वेदान्तसंज्ञ उच्यते, तस्य यानि पदानि अवान्तरवाक्यानि तैः ‘हेतुमद्भिः’ उपपत्तिसंयुक्तः ‘विनिश्चितं’ विशेषेण कृतनिश्चयमिति ।',
    note: 'Bounded: prasiddhatva turn through the joint-verse close (verse-number marker excluded). Hyphens joined (प्रसिद्ध-त्व, वेदशा-खा). Unclosed ‘छन्दोभिर्विविधैः and उपपत्तिसंयुक्तः retained verbatim; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.4-upasamhara',
    spanId: 'gita-seg-13.4-upasamhara',
    unitIds: ['13.5', '13.6'],
    ksts: ['13.4', '13.5'],
    pdf: 289,
    folio: 279,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'एवं वेदवेदान्तस्मृतिप्रसिद्धत्वमनेन वक्ष्यमाणस्य क्षेत्रादित्रतिपादकस्य अर्थस्य प्रोक्तम् । तत्र यत् क्षेत्रं यश्च क्षेत्रज्ञ इति यदुक्तं, तत्र क्षेत्रं शरीरं; यश्च तद्वेदकः, स क्षेत्रज्ञ इति प्रागेव उक्तस्वरूपमनयोर्मन्यमानो यादृगित्यादिना शिष्टं वक्तुमाह -',
    note: 'Bounded: evaṃ bridge through the verse-introducing dash (mūla excluded; spans the KSTS 13.4 close into the 13.5 exposition, hence two units). Hyphens joined (क्षेत्रादित्र-तिपादकस्य, उक्त-स्वरूप). क्षेत्रादित्रतिपादकस्य retained verbatim as joined; uncollated. Trailing dash introduces the excluded mūla. No [?].',
  },
  {
    id: 'gita-tx-13.5-tattva',
    spanId: 'gita-seg-13.5-tattva',
    unitIds: ['13.6'],
    ksts: ['13.5'],
    pdf: 290,
    folio: 280,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तत्र महाभूतशब्देन व्यापकत्वादिमहत्त्वे सति तन्मात्राण्येव उक्तानि वेदितव्यानि । यतः श्लोकार्धेन कारणभूतं पदार्थचतुष्टयं सङ्गहीतम् । तत्र ‘अहङ्कारः’ अस्मीतिप्रत्ययोऽस्मिताशब्देन कचिदुक्तः । ‘बुद्धिः’ निश्चयात्मकं ज्ञानं महत्तत्त्वमिति प्रसिद्धम् । तथा ‘अव्यक्त’ गुणत्रयात्मिका प्रकृतिः । एतानि चत्वारि कारणभूतानि स्थूलादिक्रमेण निर्दिष्टानि ।',
    note: 'Bounded: tatra definitions through the etāni summary (excludes the ahaṅkāra causal analysis after). Hyphens joined (सङ्ग-हीतम्, कचि-दुक्तः, कारण-भूतानि). No [?].',
  },
  {
    id: 'gita-tx-13.5-karana',
    spanId: 'gita-seg-13.5-karana',
    unitIds: ['13.6'],
    ksts: ['13.5'],
    pdf: 290,
    folio: 280,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तानि च पृथिव्यादीनां भूतानां तन्मात्राणि कारणम् । अहङ्कारस्तैजसवैकारिक भूतादिभेदेन त्रिविधः । तत्र तेजसत्वेन मनसः कारणम्, वैकारिकत्वेन इन्द्रियाणाम्, भूतात्मत्वेन तन्मात्राणाम्, इति अहङ्कारस्य त्रिविधगुणात्मकस्य कारणत्वम् । केचित्तु अहङ्कारतन्मात्रलक्षणस्य षट्टस्य महत्तत्वं कारणमाहुः, केचिदहकारस्यैवेति बुद्धेः कारणत्वम् । बुद्धेश्च गुणत्रयरूपा प्रकृतिरव्यक्तशब्देन उक्ता कारणमिति कारणभूतवस्तु चतुष्ट्रय प्रतिपादनेन ‘यद्विकारि’ इति प्रकान्तोऽर्थो निर्णीतः ।',
    note: 'Bounded: tāni-ca analysis through the nirṇītaḥ close (excludes the kārya-varga after). Hyphens joined (भे-देन, त्रिवि-ध, कार-णत्वम्). षट्टस्य, केचिदहकारस्यैवेति (अहकार without ṅ, as before), चतुष्ट्रय and प्रकान्तोऽर्थो retained verbatim; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.5-karya',
    spanId: 'gita-seg-13.5-karya',
    unitIds: ['13.6'],
    ksts: ['13.5'],
    pdf: 290,
    folio: 280,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'अथ कार्यवर्ग प्रतिपाद यितुमाह - ‘इन्द्रियाणि’ पञ्च बुद्धीन्द्रियाणि श्रोत्रादीनि प्रसिद्धानि, पञ्च वागादीनि कर्मेन्द्रियाण्यपि तत्त्वम्, मनश्च एकादर्श संकल्पविकल्पात्मकम् । ‘पञ्च इन्द्रियगोचराः’ इति इन्द्रियगोचरशब्देन यद्यपि शब्दादयो भूतगुणा उच्यन्ते, तथापि महाभूतानां स्वगुणोपलब्धिद्वारेण स्वरूपोपलब्धेरिन्द्रियगोचर शब्देन स्थूलान्येव भूतानि उक्तानि यतः षोडशकोऽसौ विकारवर्गः, एष च कार्य एव, न कारणमिति । एवं सांख्यदर्शनप्रसिद्धा तत्त्व चतुर्विंशतिरेषा शरीरभावेन व्यवस्थिता क्षेत्रज्ञज्ञेयत्वात् क्षेत्रमिति उक्ता ।',
    note: 'Bounded: atha turn through the kṣetram-iti-uktā close (excludes the darśanāntara transition after). Hyphens joined (इन्द्रि-याणि, शब्दा-दयो, उपलब्ब्धि-द्वारेण, शरीर-भावेन). Runs to printed p.281. प्रतिपाद यितुमाह, एकादर्श, तत्त्वम्, तत्त्व चतुर्विंशतिरेषा and इन्द्रियगोचर शब्देन retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.6-darsanantara',
    spanId: 'gita-seg-13.6-darsanantara',
    unitIds: ['13.7'],
    ksts: ['13.6'],
    pdf: 291,
    folio: 281,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'इदानीं तु दर्शनान्तरेषु तत्तत्प्रक्रिया विशेषसमाश्रयणेन यो यः पदार्थसंग्रहः कृतो भवति, तस्य सर्वस्य प्रमेयत्वानतिक्रमादस्मत्पक्षे क्षेत्रत्वमेवेति प्रतिपादयितुमाह इच्छेत्यादि ।',
    note: 'Bounded: idānīṃ-tu transition through icchetyādi (introduces the transcribed icchā-ādi gloss). Hyphen joined (क्षेत्रत्व-मेवेति). प्रक्रिया विशेष retained with space as extracted. No [?].',
  },
  {
    id: 'gita-tx-13.6-upasamhara',
    spanId: 'gita-seg-13.6-upasamhara',
    unitIds: ['13.7'],
    ksts: ['13.6'],
    pdf: 291,
    folio: 281,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'एतत्सर्व वेद्यत्वानतिक्रमात् क्षेत्रमेवेत्यस्य लोकार्थस्य तात्पर्यम् । अत्र तु प्रमात्रेकस्वभावस्य आत्मनः कथं प्रमेयत्वं, कथंषा सर्वव्यवहारानुपपत्तिसिद्धानुसंधातृलक्षणस्वरूपस्य तस्य असम्भवः, कथंवा देशकालाद्यनवच्छिन्नमहिनो यावजीवभावित्वं, इत्यादिनानाप्रवाद प्रतिक्षेपाय बहवो विपश्चितः कृतपरिश्रमाः ।',
    note: 'Bounded: etatsarvam tātparya with the pramātṛ puzzle (excludes the siddhānta-kathā after). Hyphens joined (सर्व-व्यवहार, इत्या-दिनानाप्रवाद). लोकार्थस्य, कथंषा, महिनो and नानाप्रवाद प्रतिक्षेपाय retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.6-siddhanta',
    spanId: 'gita-seg-13.6-siddhanta',
    unitIds: ['13.7'],
    ksts: ['13.6'],
    pdf: 291,
    folio: 281,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'सा च तत्त्वस्य साध्यमानावस्था सन्दिग्धबुद्धित्वदशानुत्तीर्णपुरुषविपयतया । अस्यां सिद्धान्तकथायामीश्वरानुग्रहाविर्भूतविशुद्धश्रद्धादिगुणापिशु नितसंशयादिदोषाभावनिर्मलप्रज्ञोपदेश्यपुरुष विशेषविषयायामुपन्यस्तायां मतिकालुष्यादृते न किञ्चित् प्रयोजनम् । नहि सुसिद्धं सुरसमाहार विशेषमास्वादयन्तं पुरुषं प्रति तत्साधनावस्थाप्रतिपादनेन प्रस्तुताहार वैरस्यजननमात्रातिरिक्तः कश्चिदुपकारः संभवतीति अकाण्डपाण्डित्यप्रकटन ताण्डवाडम्बरविडम्बितात्मनां मार्गो न मन्तव्यः । तदेवं यथोपक्रान्तं क्षेत्रलक्षणं तावत् निर्णीतम् ।',
    note: 'Bounded: sā-ca turn through the joint-verse close (verse-number marker and the ३६ भग० folio fragment excluded). Hyphens joined (पुरुषवि-पयतया, श्रद्धा-दिगुण, विशेष-विषयायां, तत्सा -धना, कश्चि-दुपकार, विड-म्वित); the last joins across printed pp.281–282. नितसंशय, पुरुष विशेष, सुरसमाहार विशेष, प्रस्तुताहार वैरस्य and अकाण्डपाण्डित्यप्रकटन ताण्डव retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.7-intro',
    spanId: 'gita-seg-13.7-intro',
    unitIds: ['13.7', '13.8'],
    ksts: ['13.6', '13.7'],
    pdf: 292,
    folio: 282,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'इदानी ‘स च यो यत्वभावश्च’ इति उपक्रान्तक्षेत्रज्ञलक्षणं निर्णेतव्यतया अवशिष्यते । स च ‘क्षेत्रज्ञ चापि मां विद्धि ।’ (१३।२) इति मुख्य एव एकः क्षेत्रज्ञो विवक्षितः, तस्य ‘ज्ञेयं यत्तत्प्रवक्ष्यामि ।’ (१३।१२) इत्यादिना वितत्य लक्षणं वक्ष्यति । संप्रति तु तादृशस्य क्षेत्रज्ञस्य उक्तस्य च क्षेत्रस्य यत् ज्ञानं सम्यक्संवेदनं मुख्यज्ञानतया प्राक् प्रतिपादितं यादृगुणद्वारेण अभिव्यज्यते, सोऽभिव्यक्तिहेतुगुणगण एव ज्ञानमिति प्रतिपादयितुमाह -',
    note: 'Bounded: idānīṃ bridge through the verse-introducing dash (mūla verses excluded; spans the KSTS 13.6 close into the 13.7 exposition, hence two units). Hyphen joined (हेतु-गुणगण). The (१३।२) quotation is already edged as gita-xref-038; the (१३।१२) quotation is newly edged as gita-xref-058. Trailing dash introduces the excluded mūla. No [?].',
  },
  {
    id: 'gita-tx-13.7-mana',
    spanId: 'gita-seg-13.7-mana',
    unitIds: ['13.8'],
    ksts: ['13.7'],
    pdf: 292,
    folio: 282,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'संघर्षा दिदोषप्रसक्तस्य प्रसिद्धपुरुषान्तरानुष्ठीयमानसदाचारानुकरणे संकल्पो मान इति उच्यते । स च अनुष्ठितस्य अपि सदाचारमात्रस्य संसारश्व पातफलतामावहन्नासुरसर्गभाग्जनविषयो महान् दोषः । तथाच उक्त ‘मानाग्निहोत्रमुत मानमौनं मानेनाधीतमुत मानयज्ञः । चत्वार्यतान्यभयङ्कराणि भयं प्रयच्छन्त्ययथाकृतानि ।’ (महाभा०) इति । चत्वारि अग्निहोत्रादीनि वस्तूनि आश्रमधर्मरूपाणि शास्त्रचोदितत्वादनुष्ट्रीयमानानि अभयं तावत् कुर्वन्ति, मानादिदोषदूषित चित्तत्वेन कृतानि प्रत्युत महद्भयमनुष्ठातुः फलन्तीत्यपि हि अस्य लोकस्य अर्थः । एवंविधो मानो विद्यते यस्य, स मानी; तस्य भावो मानित्वं, तदभावः ‘अमानित्वं’ शुद्धसंकल्पत्वं नाम गुणो ज्ञानाभिव्यक्तिहेतुत्वात् ज्ञानमित्युक्तम् ।',
    note: 'Bounded: saṅgharṣa definition through the jñānam-ityuktam close (excludes the adambhitva gloss after). Hyphens joined (सदाचा-रानुकरणे across a bare hyphen line, भाग्जन-विषयो, शास्त्र-चोदितत्वात्, दो-षदूषित). Runs to printed p.283. संघर्षा दिदोष, संसारश्व, फलन्तीत्यपि and दोषदूषित चित्तत्वेन retained verbatim with spaces as extracted; uncollated. The Mahābhārata quotation carries (महाभा०) without verse locator: retained as unresolved source evidence, no edge. No [?].',
  },
  {
    id: 'gita-tx-13.7-adambha',
    spanId: 'gita-seg-13.7-adambha',
    unitIds: ['13.8'],
    ksts: ['13.7'],
    pdf: 293,
    folio: 283,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'एवमेव ‘अदम्भित्वम् । दम्भो हि मानादिदोषदूषितसंकल्पत्वे सति दृष्टमात्रफलतया सदाचारानुष्ठानं, व्याजेन धर्माचरणमित्यर्थः । स विद्यते यस्य असा दम्भी मिथ्याचारः, तस्य भावो दम्भित्वं; तदभावः ‘अदम्भित्वं’ सम्यक्रियानुष्ठानमित्यर्थः, तदपि पूर्ववत् ज्ञानमेव । तथा ‘अहिंसा’। हिंसा नाम शास्त्रीयनियमनैरपेक्ष्येण द्वेषलौल्यादिप्रसक्तस्य प्राणिनां जिघांसा, तदभावोऽहिंसा निसर्गतः सर्वभूतेषु करुणाद्रेचित्तत्वादन भिद्रोहः, तदपि ज्ञानम् । तथा ‘क्षान्तिः’ परैरभिद्रुह्यमाणस्य सत्यपि प्रतीकारसाम स्वभावतः प्रशान्तचित्तत्वात् वाड्यानः कर्मभिरविकारित्वं, सापि हि ज्ञानम् । ननु अहिंसाक्षान्त्योर्यदि ज्ञानत्वं, तत् कथं तत्त्वज्ञानोपदेशविषयत्वेन परिगृहीतस्य अर्जुनस्य यज्ञसंग्रामादिक्रियानुष्ठाने नियुज्यमानस्य तद्गता हिंसा अक्षान्तिश्च अनुष्ठेयत्वेन उपदिष्टा । उच्यते -',
    note: 'Bounded: evameva gloss through the ucyate response dash (excludes the resolution after). Hyphens joined (अदम्भि-त्वम्, फल-तया, ज्ञान-मेव, द्वेष-लौल्य, विषय-त्वेन, नियुज्यमा-नस्य). असा दम्भी, करुणाद्रेचित्तत्वादन भिद्रोहः, प्रतीकारसाम and वाड्यानः retained verbatim with spaces as extracted; uncollated. Contains the print objection (ननु) and response (उच्यते). No [?].',
  },
  {
    id: 'gita-tx-13.7-arjava',
    spanId: 'gita-seg-13.7-arjava',
    unitIds: ['13.8'],
    ksts: ['13.7'],
    pdf: 294,
    folio: 284,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'यथोक्तज्ञाननिष्ठस्य अवश्यानुष्ठेयस्वकर्मभावेन अवस्थिता हिंसा अक्षान्तिश्च हिंसेव न भवति, नच अक्षान्तिरित्युक्तमेव प्राक् । ‘आर्जवम्’ ऋजुत्वं यथाहृदयं वाङ्मनः प्रवृत्तिहेतुरकुटिलता । यदेवं प्रशंसन्ति- ‘सर्व जि मृत्युपदमार्जवं ब्रह्मणः पद्म् ।’ इति । तदपि ज्ञानम् । एवं पञ्चैते धर्माः परमेश्वरानुमहसूचकदैवसर्गभाजो, न अन्यस्य प्रक्षीयमाणसदसत्कर्मसन्तानस्य संसारस्वरूपप्रत्यवेक्षायोग्यप्रज्ञस्य सहसैव जायन्ते । ते च तद्धयकृतप्रतिष्ठस्य ज्ञानतरोर्मूलसन्ततिस्थानीयाः । तयुक्तस्य पुरुषस्य अनुग्रहशत्या कल्याण मित्रसंस्तवादिना प्रेर्यमाणस्य ‘आचार्योपासनं’ सर्वाराधनं नाम धर्मो य उत्पद्यते, स ज्ञानम् ।',
    note: 'Bounded: yathokta resolution through the ācāryopāsana pratīka (excludes the skandha elaboration after). Hyphens joined (तद-पि, अनुमहसू-चक, तद्ध-य, आचार्योपा-सनं). यथाहृदयं, सर्व जि मृत्युपदमार्जवं, अनुमहसूचक, तद्धयकृत, अनुग्रहशत्या and कल्याण मित्र retained verbatim with spaces as extracted; uncollated. The mṛtyupada quotation has no work or locator: retained as unresolved source evidence, no edge. No [?].',
  },
  {
    id: 'gita-tx-13.7-acarya',
    spanId: 'gita-seg-13.7-acarya',
    unitIds: ['13.8'],
    ksts: ['13.7'],
    pdf: 294,
    folio: 284,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'ज्ञानतरोः किल असौ स्कन्धस्थानीयो धर्मः, षडान्तरीयकाः शाखाप्रतानकल्पा अमी धर्माः प्रादुर्भवन्ति । तद्यथा शास्त्राधिगमपुरस्सरः संस्कारविशेषः, तथा हेयोपादेयवस्तुविषयो विवेकः, विज्ञाततत्स्वरूपस्य हेयापवर्जन पूर्वमुपादेयानुष्ठानोन्मुख्यम् । अचार्योपासनादेवंविधधर्मोदये सति पल्लवपुष्पस्थानीयाः शौचादयो जन्मादिदोषदर्शन पर्यन्ता धर्मविशेषाः समुन्मिन्ति । तत्र विशिष्टक्रियानुष्ठाने प्राप्ताधिकारस्य कल्याणहेतुषु तासु तासु क्रियासु आसक्तचित्तस्य तद्गुणैः सम्बध्यमानस्य प्रथमः शौचो नाम गुणः सर्वक्रियाणां तत्पूर्वकत्वात् । तच्च द्विप्रकारं बाह्यमाभ्यन्तरं च । तत्र बाह्यम् अधिकारिदेशकालाद्यवस्थापेक्षया नियतेतिकर्तव्यतया मृज्जलादिना दुष्टद्रव्यगन्धलेपाद्यपासनपर्यन्ता मृजा । आभ्यन्तरं बाह्यनिवृत्तौ सत्यां शुद्धोऽस्मीति निर्विप्लवा प्रतिपत्तिः, यां भावशुद्धिसित्याहुः । एतश्च शौचं कायवाड्यानोनिर्वनां तपःस्वाध्यायध्यानादीनां गुणान्तराणामुपलक्षणं वेदितव्यम् ।',
    note: 'Bounded: jñānataroḥ skandha through the śauca upalakṣaṇa close (excludes the sthairya gloss after). Hyphens joined (शाखाप्रता-नकल्पा, विज्ञातत-त्स्वरूपस्य, अचार्यो-पासनात्, विशि-ष्ट, कर्तव्य-तया, आभ्य-न्तरं, तपः-स्वाध्याय); the last joins across printed pp.284–285. अचार्यो, हेयापवर्जन पूर्वमुपादेयानुष्ठानोन्मुख्यम्, जन्मादिदोषदर्शन पर्यन्ता, भावशुद्धिसित्याहुः and कायवाड्यानोनिर्वनां retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.8-sthairya',
    spanId: 'gita-seg-13.8-sthairya',
    unitIds: ['13.8', '13.9'],
    ksts: ['13.7', '13.8'],
    pdf: 295,
    folio: 285,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'अथ ‘स्थैर्य’ संशयादिदोषनिवृत्त्या अनुष्ठेयेषु अर्थेषु अचचलता । तस्मिश्च सति ‘आत्मविनिग्रहः’ अत्मनोऽन्तःकरणस्य निषिद्धात् विषयात् विनिग्रहो नियमनम्। ततश्च ‘इन्द्रियार्थेषु’ विषयेषु दृष्टानुश्रविकेषु क्षयातिशयादिदोषदर्शनात् ‘वैराग्यं’ रागद्वेषर हितत्वं, तत् प्रकर्षमासादयत् सत्त्वान्तरेषु गुणेष्वपि पर्यवस्यति । तस्मिश्च तादृशे गुणे सति ‘अनहङ्कारः’ ईदृशोऽस्मीतिदुर भिमानाभावः, यदिवा शरीरादा वहस्मीतिप्रत्ययनिवृत्तिः । ततश्च जन्मादिदोषप्रभवस्य दुःखस्यैव महादोषस्य अनुदर्शनं पृष्ठतो निरूपणम् । तद्यथा गर्भवासादिनिरतिशयक्तेशानुभवादिकं जन्मनो दुःखं, प्राप्तशरीरग्रहस्य अवश्यंभावि मरणदुःखम् । तथा सति शरीरे वार्धक्यरोगादिदुःखमिति शरीरित्वं नाम आदिमध्यान्तावस्थासु दुःखमयमेव - इति विवेकहधिरूढः स्वपरविषयत्वेन विवेक्तं क्षमः । यथोक्तं ‘प्रज्ञाप्रासादमारुह्य अशोच्यः शोचतो जनान् । भूमिष्ठानिव शैलस्थः सर्वान प्राज्ञोऽनुपश्यति ॥ इति ।',
    note: 'Bounded: atha turn through the iti close (spans the KSTS 13.7–13.8 gloss, hence two units; excludes the asakti gloss after). Hyphens joined (दृष्टा-नुश्रविकेषु, दोष-प्रभवस्य). अचचलता, अत्मनोऽन्तःकरणस्य, रागद्वेषर हितत्वं, दुर भिमानाभावः, शरीरादा वहस्मीतिप्रत्ययनिवृत्तिः, क्तेशानुभवादिकं, सर्वान प्राज्ञो and विवेकहधिरूढः retained verbatim with spaces as extracted; uncollated. The prajñāprāsāda quotation (यथोक्तं) has no locator: retained as unresolved source evidence, no edge. The quotation close ॥ is print punctuation, retained. No [?].',
  },
  {
    id: 'gita-tx-13.9-asakti',
    spanId: 'gita-seg-13.9-asakti',
    unitIds: ['13.10', '13.11'],
    ksts: ['13.9', '13.10'],
    pdf: 295,
    folio: 285,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तथाविधस्य च स्वर्गादिफलेषु क्रियाविशेषेषु ‘असक्ति’ असङ्ग औदासीन्यम् । तथा दृष्टसुखहेतुषु सुतकलत्रभवनादिषु ‘अनभिवंङ्गः’ सर्वस्वग्रहपरित्यागः । एतां च दशां प्राप्तस्य ‘इष्टानिष्टोपपत्तिषु’ प्रियाप्रियपदार्थप्राप्तिषु सतीषु ‘समचित्तत्वं’ हर्षशोका दिविकाररहितान्तः करणत्वम् । एवमेव तस्यां ज्ञानतरो-नौनाविधपल्लवपुष्पस्थानीयायां गुणसामग्रयां निर्वृत्तायां फलस्थानीया ‘मयि भक्तिः’ उपासा । कीदृशी । ‘अव्यभिचारिणी’ निरपाया । केन हेतुना। ‘अनन्ययोगेन’ अन्येन यथाप्रतिपादितमत्स्वरूपव्यतिरिक्तेन वस्तुना योगः संबन्धोऽन्ययोगः, तदभावोऽनन्ययोगस्तेन । किमुक्तं भवति । सर्वभावानां मत्स्वरूपाव्यतिरिक्तत्वदर्शनं ज्ञानतरोः फलभूता मुख्या मद्भक्तिः । सा हि चतुर्थी ज्ञानित्वरूपा भक्त्यवस्था । यथोक्त प्राक् ज्ञानी त्वात्मैव मे मतः ।’ इति ।',
    note: 'Bounded: tathāvidhasya turn through the iti close (spans the KSTS 13.9–13.10 gloss, hence two units; excludes the vivikta gloss after). Hyphens joined (फलस्था-नीया, यथाप्रतिपादित-मत्स्वरूप, तदभावो-ऽनन्ययोगस्तेन, अव्यति-रिक्तत्व); the ज्ञानतरो-नौनाविध hyphen is ambiguous in extraction (visarga or space lost) and is retained unjoined. Runs to printed p.286. अनभिवंङ्गः, हर्षशोका दिविकार and रिक्तत्वदर्शनं retained verbatim with spaces as extracted; uncollated. The printed (७।१८) locator is excluded from transcription (extraction renders its danda as `/`, which the source-text invariant forbids); the locator and quotation are preserved instead in gita-xref-055. No [?].',
  },
  {
    id: 'gita-tx-13.10-vivikta',
    spanId: 'gita-seg-13.10-vivikta',
    unitIds: ['13.11', '13.12'],
    ksts: ['13.10', '13.11'],
    pdf: 296,
    folio: 286,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तस्यां च सत्यां ‘विविक्तदेश सेवित्वं’ विविक्तदेशस्य तादृशनिरुत्तर भक्तिरसामृतास्वाद विघ्नकारिचेतनाचेतन वस्तुरहितस्य गिरिगुहा पुण्य सरित्पुलिनगुप्तगृहदेशस्य सेवित्वं भजनशीलता । तद्विपरीतायां ‘जनसंसदि’ चित्तव्युत्थान हेतु लोकसभायां ‘अरतिः’ उद्वेगस्तत्परिहरण मित्यर्थः । तथा ‘अध्यात्मज्ञाननित्यत्वम् अध्यात्ममात्मनि यत् ज्ञानं परमात्मस्वभावसंवेदनं, तत् नित्यमव्यभिचारि यस्य, स तथा, तस्य भावस्तत्त्वम् । तस्मिश्च सति ‘तत्त्वज्ञानार्थदर्शनं’ तत्त्वस्य परमात्मस्वरूपलक्षणस्य परस्य भावस्य ज्ञानं बोधः स्वसंवेदनानुभवः । पूर्वेण पदेन ज्ञानस्य सिद्धिं कल्पयता उत्तरेण सिद्धत्वमेव प्रतिपादितं, स एव अर्थः प्रयोजर्न फलं यस्येति तस्य दर्शनं साक्षात्कारो निरुत्तरा सिद्धिरित्यर्थः । एते विविक्त देश से वित्वादयस्तत्त्वज्ञानार्थदर्शनान्ता धर्माः फलभूताया भक्ते रसस्थानीयाः, इत्येतावती गुणसामग्री ‘ज्ञानमिति प्रोक्त स्पष्टोऽर्थः । अत उक्तात् गुणसमूहात् ‘अन्यथा’ अन्येन विपरीतेन प्रकारेण मानित्वदम्भित्वादिना यत्स्थितं, तत्सर्व ‘अज्ञानं’ ज्ञानविपरीतं वेदितव्यम् । एतच्च पुरस्तात् देवासुरसर्गकथनप्रसङ्गेन पुनरपि ज्ञानाज्ञानलक्षणं वक्ष्यति ।',
    note: 'Bounded: tasyāṃ-ca turn through the vakṣyati close (joint-verse marker excluded; spans the KSTS 13.10–13.11 gloss, hence two units; excludes the jñeya verse after). Hyphens joined (वस्तुरहित-स्य, भजनशी-लता, नित्य-मव्यभिचारि, भा-वस्य, सिद्धिरि-त्यर्थः, ज्ञान-मिति, देवासुरस-र्ग); प्रयो-जर्न joins to प्रयोजर्न, retained verbatim. All print spaces (विविक्तदेश सेवित्वं, तादृशनिरुत्तर भक्तिरसामृतास्वाद, चित्तव्युत्थान हेतु, तत्परिहरण, स एव अर्थः, भक्ते रसस्थानीयाः) retained as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.12-pratijna',
    spanId: 'gita-seg-13.12-pratijna',
    unitIds: ['13.13'],
    ksts: ['13.12'],
    pdf: 296,
    folio: 286,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'एवंविधेन च ज्ञानेन- ‘ज्ञेयं’ ज्ञातव्यं ‘यत्’ यथोक्तेन ज्ञानेन फलतया अवस्थितं परमात्मलक्षणं वस्तु ‘तत्’ इदानीं ‘प्रवक्ष्यामि’ तत्स्वरूपं प्रकर्षण कथयिष्यामि । ‘यज्ञात्वा’ यदुच्चा ‘अमृतम्’ अविनाशिस्वरूपं ‘अनुते’ व्याप्नोति । ननु अनन्यसंवेद्यस्य सर्वसंवेदकस्वभावस्य कथ मि दन्ताक्सेयवस्त्वन्तरवत् ज्ञेयत्वेन व्यपदेशः कृतः ।',
    note: 'Bounded: evaṃvidhena turn through the nanu close (mūla verse line excluded; the transcribed satyam response follows in the next passage). Runs to printed p.287. Trailing dash after ज्ञानेन introduces the excluded mūla. यदुच्चा, अनुते (against mūla अमृतमश्नुते) and the garbled कथ मि दन्ताक्सेयवस्त्वन्तरवत् retained verbatim: the full nanu wording is extraction-noisy and stays an unresolved argument (gita-arg-13.13-jneya-obj), never reconstructed. No [?].',
  },
  {
    id: 'gita-tx-13.12-pratyavamarsa',
    spanId: 'gita-seg-13.12-pratyavamarsa',
    unitIds: ['13.13'],
    ksts: ['13.12'],
    pdf: 297,
    folio: 287,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'यतः सोऽयमहमिति स्वात्मत्वेन प्रत्यवमर्श एव तस्य ज्ञानं, तद्वदहमिदं वेद्मि इति, व्यतिरेकेण तस्य एकस्य अनुभवितृत्वमात्रलक्षणस्य तत्त्वस्य अवगमः संभवति ॥',
    note: 'Bounded: yataḥ elaboration through the avagamaḥ close (excludes the tadviśeṣaṇa introduction after). Spaces (तद्वदहमिदं वेद्मि इति, तस्य एकस्य) retained as extracted. The closing ॥ is print punctuation, retained. No [?].',
  },
  {
    id: 'gita-tx-13.12-samjna',
    spanId: 'gita-seg-13.12-samjna',
    unitIds: ['13.13'],
    ksts: ['13.12'],
    pdf: 297,
    folio: 287,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'किं तज्ज्ञेयमिति ससंज्ञ निर्दिशति परं ब्रह्मेति । परमार्थतः सर्वस्य वस्तुनो ब्रह्मरूपत्वे स्थिते यत् ज्ञेयतया संप्रति आभासते, तपः यत्तुं ज्ञातृमात्रस्वरूपं ‘तत्परं ब्रह्म’ इत्युक्तम् । कीदृशं तत् । ‘अनादिमत् । इदं वेद्यं वस्तु सर्वक्षेत्रज्ञसाधारणं पृथिव्यादिरूप विषयतया व्यवस्थितं, तथा प्रतिक्षेत्रज्ञ शरीरतया व्यवस्थितम्, उभयरूपतया प्राप्रतिपादितं, कारणापेक्षतया सर्वमादिम त् आगमापायधर्मकत्वादादिकोट्यवच्छिन्नं, ततैश्च अन्तकोट्यवच्छिन्नमपि ।',
    note: 'Bounded: kiṃ-tajjñeyam turn through the antakoṭi close (excludes the na-sat exposition after). Runs to printed p.288. ससंज्ञ निर्दिशति, पृथिव्यादिरूप विषयतया, प्रतिक्षेत्रज्ञ शरीरतया, सर्वमादिम त्, तपः यत्तुं and ततैश्च retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.12-nasat',
    spanId: 'gita-seg-13.12-nasat',
    unitIds: ['13.13', '13.14'],
    ksts: ['13.12', '13.13'],
    pdf: 298,
    folio: 288,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'अन्यञ्च कीदृशम् । ‘न सत् । इह हि यदिन्द्रियैर्वाह्याभ्यन्तरैरिदमिति गृह्यते, तत् मायीयैः प्रमातृभिः सदिति प्रतिपद्यते । ब्रह्म तु प्रमात्रेकस्वभावत्वात् सर्वेन्द्रियगोचरभूतं तथा सत् न भवति । नच एवम् ‘असत् तदुच्यते’ । यत एवमपि सत्त्वेन प्रतिपन्नस्य सर्वस्य वस्तुभस्तथावभासकत्वात् तदेव सद्भावकारणं कथमसदिति वक्तुं शक्यम् । अत एव तस्य परमार्थसदेकप्रमातृरूपस्य विश्वरूपत्वं प्रतिपादयितुमाह - ‘सर्वतः पाणिपादं तत्’ - इत्यादिना । सर्वेषां क्षेत्रज्ञानां यानि पादादीनि कर्मेन्द्रियाणि, यानि च चक्षुः श्रोत्रादीनि बुद्धीन्द्रियाणि तत्तत्क्रियाज्ञानसाधनत्वेन व्यवस्थितानि; तानि असाधारण कर्तृज्ञातृशक्तेरेकस्यैव तस्यै विश्वात्मनः शक्तिभेद इति तात्पर्यम् । यत आह ‘सर्वमावृत्य तिष्ठति’ इति । एकमेव तत्त्वं सर्वमिदं जगत् कर्तृतया ज्ञातृतया च व्याप्य वर्तत इति ।',
    note: 'Bounded: anyacca turn through the vyāpya-vartata close (spans the KSTS 13.12–13.13 gloss, hence two units; excludes the sarvendriya gloss after). Hyphens joined (तत्तत्क्रि-याज्ञान, कर्तृज्ञातृश-क्तेरेकस्यैव). वस्तुभस्तथावभासकत्वात्, असाधारण कर्तृज्ञातृ and तस्यै विश्वात्मनः retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.13-sarvendriya',
    spanId: 'gita-seg-13.13-sarvendriya',
    unitIds: ['13.14'],
    ksts: ['13.13'],
    pdf: 298,
    folio: 288,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'अत एव आह ‘सर्वेन्द्रियगुणाभास’ इति । यानि नानाक्षेत्रज्ञसंबद्धत्वेन अवभासमानानि सर्वाणि बाह्याभ्यन्तराणि इन्द्रियाणि तेषां शब्दादिविषयावभासकत्वादयो ये गुणा धर्माः, तानवभासयति प्रकाशयति यत्; तत् तथोक्तम्, स्वयं तु ‘सर्वेन्द्रियविवर्जितम्’ नहि तस्य मायावभासितावच्छिन्नस्वरूपक्षेत्रज्ञवत् नियतेन्द्रियाधीनं ज्ञानमित्यर्थः ।',
    note: 'Bounded: ata-eva turn through the jñānam-ityarthaḥ close (excludes the asakta gloss after). Hyphens joined (अव-भासमानानि, प्रकाश-यति); the last joins across printed pp.288–289. No [?].',
  },
  {
    id: 'gita-tx-13.14-asakta',
    spanId: 'gita-seg-13.14-asakta',
    unitIds: ['13.15'],
    ksts: ['13.14'],
    pdf: 299,
    folio: 289,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तथा ‘असक्त’ विशुद्धचिन्मात्रैकस्वभावव्यवस्थितत्वात वैद्यरूपेण प्राकृतेन प्रपञ्चेन अमिश्रीभूतम् । अथच ‘सर्वभृत् सर्व बिभर्ति धारयति यत् । तत्र हि तत्त्वे वेद्यव्यतिरिक्तस्वभावेऽपि सर्वमिदमवस्थितं तद्विना कस्यचिदपि स्वरूपलाभाभावात् । अत एव ‘निर्गुणं’ गुणेभ्यः सत्त्वादिभ्यः प्रकाशप्रवृत्तिनियमात्मकेभ्यः सुखदुःखमोहवृत्तिभ्यो निष्क्रान्तं तेभ्योऽत्यन्तव्यतिरिक्तस्वरूपम् । नहि ब्रह्म अनित्यसुखाद्यात्मकं भवति, केवलमाकाशमिव सूर्यातपरजस्तिमिरादिभिस्तैस्तै गुणैरत्यन्तासंस्पृष्टस्वरूपमपि तत्त्वविचारशून्यैः प्रमातृभिस्तद्वत्तया गृह्यते । वस्तुतस्तु गुणभोक्तृत्वात् गुणाननुभवितृतया भुते, नतु तैस्तत्स्वरूपमात्रियते ।',
    note: 'Bounded: tathā turn through the mātriyate close (excludes the bahir-antaḥ gloss after). Hyphens joined (सूर्या-तपरजस्ति, तत्त्ववि-चारशून्यैः). विशुद्धचिन्मात्रैकस्वभावव्यवस्थितत्वात वैद्यरूपेण, सर्व बिभर्ति, तैस्तै गुणैः and भुते retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.15-bahiranta',
    spanId: 'gita-seg-13.15-bahiranta',
    unitIds: ['13.15', '13.16'],
    ksts: ['13.14', '13.15'],
    pdf: 299,
    folio: 289,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'अत एव अनवच्छिन्ननिजमा हात्म्यविश्वरूपत्वादाकाशमिव घटादीनां सर्वभूतानां चराचराणां ‘बहिः’ ज्ञेयभावेन ‘अन्तः ज्ञातृभावेन च अवभासमानमपि परमार्थतः सामान्य संवित्स्वभावमेवैकं तत्तत्त्वं व्यवस्थितं, देहादिप्रत्ययव्यवधानमात्रकृतो बाह्याभ्यन्तरव्यपदेशः । अत एव आह नित्यनिश्चलखभावमात्रप्रतिष्ठितत्वात् ‘अचरं’ गतिधर्मविवर्जितं सर्ववस्तुवेदकतया नित्यप्रसृतशक्तित्वात् ‘चरं’ गमनशीलमिव । तथा इदन्तावसेयसर्ववस्तुविलक्षणस्वरूपत्वात् परमसूक्ष्मं ‘तत्’ तस्माञ्च सौक्ष्म्यात् कारणात् ‘अविज्ञेयम् इदमित्यनवधार्यस्वरूपम् ।',
    note: 'Bounded: ata-eva turn through the anavadhārya close (spans the KSTS 13.14–13.15 gloss, hence two units; excludes the dūra/antika turn after). Hyphens joined (व्य-वस्थितं, गम-नशीलमिव, पर-मसूक्ष्मं, इदमित्य-नवधार्य). निजमा हात्म्य, ‘अन्तः ज्ञातृभावेन, सामान्य संवित् and नित्यनिश्चलखभाव retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.15-avibhakta',
    spanId: 'gita-seg-13.15-avibhakta',
    unitIds: ['13.16', '13.17'],
    ksts: ['13.15', '13.16'],
    pdf: 299,
    folio: 289,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'अत एव सर्वप्रमातृणां ज्ञेयत्वाभावात् ‘दूरस्थम् अतिविप्रकृष्टम् । अथच तद्विना कस्यचिदपि ज्ञानस्य कर्मणो वा अपि अनुपपत्तेः सर्वेषां ‘अन्तिके’ अभ्याशे स्थितम् । तथा ‘विभक्तेषु’ देव मनुष्यतिर्यगादित्वात् परस्परभिन्नेषु वस्तुषु सामान्य संविदात्मकत्वेन ‘अविभक्तम्’ अभिन्नैकस्वरूपम् । अथच ‘विभक्तवञ्च संस्थितम्’ भेदेन अवभासमानत्वात् ।',
    note: 'Bounded: ata-eva turn through the avabhāsamānatvāt close (spans the KSTS 13.15–13.16 gloss, hence two units; excludes the bhūtabhartṛ gloss after). Hyphens joined (विभ-क्तेषु); संवि-दात्मकत्वेन joins across a bare line break. Runs to printed p.290. ‘दूरस्थम् अतिविप्रकृष्टम्, देव मनुष्यतिर्यगादित्वात्, सामान्य संविदात्मकत्वेन and ‘विभक्तवञ्च संस्थितम्’ (split across the page break, space-joined) retained verbatim as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.16-bhutabhartr',
    spanId: 'gita-seg-13.16-bhutabhartr',
    unitIds: ['13.17'],
    ksts: ['13.16'],
    pdf: 300,
    folio: 290,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तथा ‘तत्’ तत्त्वं ‘भूतभ ’ सर्वभूतानां तस्य तस्य रूपस्य अवस्थित्येक हेतुत्वात् धारकम् । तथा प्रसिष्णु’ संहारशक्तियुक्तत्वात् प्रसनशीलम् । तथा ‘प्रभविष्णु उत्पादन हेतुत्वात् स्थितिप्रलयस कारणमित्यर्थः । तथा ‘ज्योतिषां सूर्यादीनां प्रकाशकानां प्रकाशहेतुत्वात् ‘ज्योतिः’ प्रकाशकम् । तानि, हि जगद्भावप्रकाशकान्यपि संवित्प्रकाशप्रकाश्यानि । अत एव ‘तमसः परमुच्यते । यद्यत् परप्रकाश्यं, तत्तत् स्वयमप्रकाशात्मकत्वात् तमोरूपम् । तस्मात् तत् तत्त्वं परं सर्वप्रकाशकरूपत्वात् प्रकृष्टं व्यतिरिक्त वा ।',
    note: 'Bounded: tathā turn through the vyatirikta-vā close (excludes the jñāna-jñeya turn after). ‘भूतभ ’ (truncated pratīka with space), अवस्थित्येक हेतुत्वात्, प्रसिष्णु’ (unopened quote), ‘प्रभविष्णु (unclosed quote), उत्पादन हेतुत्वात्, स्थितिप्रलयस and तानि, हि retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.17-jnanagamya',
    spanId: 'gita-seg-13.17-jnanagamya',
    unitIds: ['13.18'],
    ksts: ['13.17'],
    pdf: 300,
    folio: 290,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तथा ‘ज्ञानज्ञेय’ ज्ञानेन यथाप्रतिपादितस्खरूपेण उपायेन ज्ञेयमात्मतया प्रत्यभिज्ञेयमित्यर्थः । यतो ‘ज्ञानगम्यं’ ज्ञानं विना तथा विषयीकर्तुमशक्यम् । परमार्थतस्तु ‘सर्वस्य’ कस्यचित् प्रमातुः ‘हृदि’ हृदये संवेत्तृतया विशेषेण स्थितं सिद्ध्यवस्थायां तथा स्वसंवेदनसंवेद्यत्वात् ।',
    note: 'Bounded: tathā turn through the joint-verse close (verse-number marker excluded; excludes the kṣetra upasaṃhāra after). Hyphens joined (यथाप्रतिपादितस्ख-रूपेण, ज्ञान-गम्यं). यथाप्रतिपादितस्खरूपेण and ‘सर्वस्य’ कस्यचित् retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.18-upasamhara',
    spanId: 'gita-seg-13.18-upasamhara',
    unitIds: ['13.19'],
    ksts: ['13.18'],
    pdf: 300,
    folio: 290,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: '‘इति’ एतावता अन्थेन ‘क्षेत्र’ ‘महाभूतानि इत्यादिना प्राकृतभावमयं शरीरं, ‘तथा’ अमानित्वादितत्वज्ञानार्थदर्शनान्तधर्मरूपं ‘ज्ञानं’ तथा ‘क्षेत्रज्ञ चापि मां विद्धि सर्वक्षेत्रेषु .....’ (१३।५) इत्यादिना मुख्यक्षेत्रज्ञरूपं ‘ज्ञेय’ तत्तत्वमिति प्रधानं पदार्थत्रयमेतदुक्तम् । यतो ‘मद्भक्तो’ मदनुमहादेव मत्सपर्यापरः ‘एतत् त्रितर्य ज्ञात्वा ‘मद्भावाय’ मत्स्वरूपसमापत्तये ‘उपपद्यते’ उपपन्नः समर्थो भवति ।',
    note: 'Bounded: iti turn through the verse close (verse-number marker excluded). Hyphen joined (अमानित्वादितत्व-ज्ञान). Runs to printed p.291. A corrupt non-Devanagari extraction fragment after ‘महाभूतानि is excluded as apparatus noise (unresolvable, never reconstructed); the pratīka itself is retained. अन्थेन, तत्तत्वमिति, मदनुमहादेव, मत्सपर्यापरः, त्रितर्य and ..... retained verbatim as extracted; uncollated. The printed (१३।५) disagrees with its quotation (KSTS 13.2, not 13.5): retained unresolved, no edge. No [?].',
  },
  {
    id: 'gita-tx-13.19-anaditva',
    spanId: 'gita-seg-13.19-anaditva',
    unitIds: ['13.20'],
    ksts: ['13.19'],
    pdf: 301,
    folio: 291,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'नहि एतयोरेकतासंबन्धस्य पूर्व कोटि रुपलभ्यते, ज्ञानातु यथोक्तस्वरूपादन्तकोटिरस्त्येव, अनयोरेवमनादित्वं संबन्धस्य, इति अत्र तात्पर्यं; नतु समशीर्षिकया नित्यत्वप्रतिपादनम् । यतः प्रकृतेर्वेद्यत्वादुदयव्ययधर्मयोगित्वे सति प्रवाहनित्यत्वं, पुरुषस्य तु परमार्थतः संविद्रूपत्वात् कूटस्थनित्यत्वम् । अत एव आह ‘विकारान्’ महदादीन् ‘गुणांश्च’ सत्त्वादीन वेधैकस्वभावान् ‘प्रकृतिसंभवान्’ प्रधानकारणान् जानीहि ।',
    note: 'Bounded: nahi turn through the jānīhi close (excludes the sāmānya transition after; follows the transcribed prakṛti-puruṣa recall). Hyphens joined (कोटि रुपल-भ्यते, नित्यत्वप्र-तिपादनम्, वेधैक-स्वभावान्). पूर्व कोटि रुपलभ्यते, सत्त्वादीन वेधैकस्वभावान् retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.19-samanya',
    spanId: 'gita-seg-13.19-samanya',
    unitIds: ['13.21'],
    ksts: ['13.20'],
    pdf: 301,
    folio: 291,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'एवं सामान्येन प्रकृतिपुरुषयोः स्वरूपं प्रतिपाद्य, इदानीं यथा प्रकृतिः प्रतिपुरुषं नानाशरीरभावेन संबद्धा, पुरुषश्च प्रतिशरीरं नानाक्षेत्रज्ञभावेन यथा संबद्धस्तथा प्रतिपादयितुमाह -',
    note: 'Bounded: evaṃ transition through the verse-introducing dash (mūla excluded; bridges the KSTS 13.19 close into the 13.20 exposition). No hyphens; no [?].',
  },
  {
    id: 'gita-tx-13.20-prakrtihetu',
    spanId: 'gita-seg-13.20-prakrtihetu',
    unitIds: ['13.21'],
    ksts: ['13.20'],
    pdf: 301,
    folio: 291,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तस्य कर्तृत्वे तावन्मात्रनिविष्टाहंप्रत्ययरूपे ‘प्रकृतिः’ अव्यक्त ‘हेतुः’ कारणम् । सा हि शरीरात्मना व्यवस्थिता सती तन्निविष्टाहंप्रत्ययनिमित्तम् । तथा सुखादीनां वेद्यत्वात् भोग्यानामात्मनो यो भोक्तृत्वाभिमानः, तत्र वेदकस्वभावत्वात् पुरुष एव कारणम् । सति पुरुषप्रत्यये सुखदुःखात्मनो भोग्यस्य विषयत्वं, पुरुषस्य च विषयित्वव्यपदेशः ।',
    note: 'Bounded: tasya turn through the verse close (verse-number marker excluded; follows the transcribed kārya-kāraṇa definition). The तन्निविष्टा-हंप्रत्ययनिमित्तम् hyphen joins across printed pp.291–292. भोग्यानामात्मनो retained with space as extracted. No [?].',
  },
  {
    id: 'gita-tx-13.21-gunasanga-a',
    spanId: 'gita-seg-13.21-gunasanga-a',
    unitIds: ['13.22'],
    ksts: ['13.21'],
    pdf: 302,
    folio: 292,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'यस्मात् प्रकृतौ नानाकार्यकारणात्मकशरीरभावेन परिणते प्रधाने स्थितो मायावशात् तावन्मात्राहकारावष्टम्भेन वर्तमानः ‘पुरुषः प्रकृतिजान्’ प्रकृतेः समुद्भूतान् ‘गुणान्’ सत्त्वादीन् सुखाद्यात्मना परिणतान् ‘भुङ्गे’ वेदकत्वेन विषयीकरोति । यतो महाभूतगुणाः शब्दादयः सुखाद्यात्मना वैद्यत्वमापन्नाः पुरुषस्य विषयित्वव्यपदेशहेतवः ।',
    note: 'Bounded: yasmāt turn through the vyapadeśahetavaḥ close (excludes the avivekaja turn after). Hyphen joined (विषयविषय-भावेन). तावन्मात्राहकारावष्टम्भेन (अहकार without ṅ, as before), ‘भुङ्गे’ and वैद्यत्वमापन्नाः retained verbatim; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.21-gunasanga-b',
    spanId: 'gita-seg-13.21-gunasanga-b',
    unitIds: ['13.22'],
    ksts: ['13.21'],
    pdf: 302,
    folio: 292,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'एवं शरीरशरीरिभावेन विषयविषयभावेन च प्रकृतिपुरुषयोरविवेकजः संबन्धः । ततश्च ‘अस्य’ पुरुषस्य गुणेषु शरीरात्मना विषयात्मना च सङ्गोऽहङ्कारसमकारात्मको दृढः संबन्धः, तत् सतीषु सत्त्वगुणप्रधानासु, असतीषु च रजस्तमः प्रधानासु योनिषु उत्पत्तिकारणमूर्तिषु यानि जन्मानि पुरुषादिरूपतया संभवाः, तेषु ‘गुणसङ्गः’ एव ‘कारणं’ हेतुः प्रकृतिपुरुषविवेकाभावमात्रनिमित्ता संसारिता पुरुषस्येत्यर्थः ।',
    note: 'Bounded: evaṃ turn through the verse close (verse-number marker excluded). Hyphens joined (सङ्गोऽहङ्कार -समकारात्मको across a spaced hyphen, पुरुष-स्येत्यर्थः). तत् सतीषु and रजस्तमः प्रधानासु retained with spaces as extracted. No [?].',
  },
  {
    id: 'gita-tx-13.22-dvividha',
    spanId: 'gita-seg-13.22-dvividha',
    unitIds: ['13.23'],
    ksts: ['13.22'],
    pdf: 302,
    folio: 292,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'यतः परस्य तत्त्वस्य देहेऽस्मिन् नानापुरुषसंबन्धिनि द्विधा स्थितिरित्याह -',
    note: 'Bounded: yataḥ transition through the verse-introducing dash (mūla excluded; bridges the KSTS 13.21 close into the 13.22 exposition). No hyphens; no [?].',
  },
  {
    id: 'gita-tx-13.22-upadrastra',
    spanId: 'gita-seg-13.22-upadrastra',
    unitIds: ['13.23'],
    ksts: ['13.22'],
    pdf: 303,
    folio: 293,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'यतः प्रकत्यादिमहदहङ्कारात्मना दृश्यत्वेन उपस्थापितमर्थ पुरुषः पश्यति, इत्यसौ ‘उपद्रष्टा’ इत्युच्यते । तथा दृश्यमेव शरीरादि अहन्तया परामृशन् ‘भता’ कार्यकारणस्य अहन्तया धारकः स एव व्यपदिश्यते । तथा प्रकृत्या मतं ज्ञातं वेद्यत्वेन प्रतिपन्न सुखादिविषयभूतं वस्तु पृष्ठतः पुरुषो मन्यत इति ‘अनुमन्ता’ स उच्यते ।',
    note: 'Bounded: yataḥ analysis through the anumantā close (follows the transcribed maheśvara sentence; excludes the bhoktṛ-vyapadeśa after). Hyphens joined (देहेऽस्मि-नुपद्रष्टा across a bare break, प्रक-त्यादि, व्यपदि-श्यते, सुखादिविषय-भूतं). प्रकत्यादि, ‘भता’ (for भर्ता) and प्रतिपन्न सुखादि retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.22-viveka',
    spanId: 'gita-seg-13.22-viveka',
    unitIds: ['13.23'],
    ksts: ['13.22'],
    pdf: 303,
    folio: 293,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'ततश्च तस्यैव भोक्तृत्वव्यपदेशः । इत्थं सांख्यप्रक्रियया पुरुषस्य शरीरित्व विषयित्वारोपो य उच्यते, तत्र विवेकाभावः कारणं; स च मायानिबन्धनः । यदा तु विद्योदयात् विवेकजज्ञानाविर्भावः, तदा असावेव पुरुषः ‘परमात्मा’ इत्यभिधीयते प्रबन्धतो यथाप्रतिपादिताद्वयचि कस्वभावब्रह्मस्वरूपतया उच्यते ।',
    note: 'Bounded: tataśca turn through the verse close (verse-number marker excluded). Hyphen joined (यथा-प्रतिपादिताद्वयचि). यथाप्रतिपादिताद्वयचि कस्वभावब्रह्मस्वरूपतया (space as extracted, for अद्वयचित्) and शरीरित्व विषयित्वारोपो retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.23-phala-intro',
    spanId: 'gita-seg-13.23-phala-intro',
    unitIds: ['13.24'],
    ksts: ['13.23'],
    pdf: 303,
    folio: 293,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'एवं प्रकृतिपुरुषेश्वरविवेकलक्षणस्य ज्ञानस्य फलमाह -',
    note: 'Bounded: evaṃ phala turn through the verse-introducing dash (mūla excluded; bridges the KSTS 13.22 close into the 13.23 exposition). No hyphens; no [?].',
  },
  {
    id: 'gita-tx-13.23-yogi',
    spanId: 'gita-seg-13.23-yogi',
    unitIds: ['13.24'],
    ksts: ['13.23'],
    pdf: 303,
    folio: 293,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: '‘यो’ योगी ‘एवं’ उक्तेन प्रकारेण ‘पुरुषं’ नानाक्षेत्रज्ञरूपतया अवस्थितं ‘गुणैः’ सुखाद्यात्मकविषयभावेन अवस्थितैः ‘सह वेत्ति’, ‘स’ तत्त्वत्रयपरमार्थ वेदित्वात् ‘सर्वथा’ सर्वेणापि प्रकारेण तत्तद्वर्णधर्मात्मकेन तत्तदाश्रमधर्मात्मकेन चं ‘वर्तमानः ’ तदनुष्ठावृतया तिष्ठन्नपि ‘भूयः’ पुनः ‘न अभिजायते’ न संसारी भवति यथोक्तेन ज्ञानानिना संसारप्रसवहेतूनां बीजस्थानीयानां कर्मणां दाहादिति । यथोक्त ‘बीजान्यम्युपदग्धानि न रोहन्ति यथा पुनः ज्ञानदग्धैस्तथा केशनत्मा संपद्यते पुनः ॥’ इति । स्पष्टोऽर्थः ।',
    note: 'Bounded: yo pratīka through the spaṣṭa close (verse-number marker excluded). Hyphens joined (प्रका-रेण). Runs to printed p.294. तत्त्वत्रयपरमार्थ वेदित्वात्, चं ‘वर्तमानः ’, तदनुष्ठावृतया, ज्ञानानिना, बीजान्यम्युपदग्धानि and केशनत्मा retained verbatim with spaces as extracted; uncollated. The jñāna-dagdha quotation (यथोक्त) has no locator: retained as unresolved source evidence, no edge. The quotation close ॥ is print punctuation, retained. No [?].',
  },
  {
    id: 'gita-tx-13.24-dhyana',
    spanId: 'gita-seg-13.24-dhyana',
    unitIds: ['13.25'],
    ksts: ['13.24'],
    pdf: 304,
    folio: 294,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'केचित् सहजसिद्धतत्त्वज्ञाना निरुत्तरपरमेश्वरानुग्रह भाजो "ध्यानेन आत्मानं पश्यन्ति’ यथोक्तब्रह्मस्वरूपतानुस्मरणेन साक्षाकुर्वन्ति । अत एव केन क पश्यन्तीत्यभेदप्रतिपादनार्थमाह आत्मनात्मानमात्मनि पश्यन्ति’ इति । किमुक्तं भवति । यन्त्र अधिकरणे हृदयादौ ध्यानं कुर्वन्ति, येन च अन्तः करणेन कुर्वन्ति, यञ्च तेन ध्यानेन उपलभन्ते, तत् सर्व परब्रह्मरूपतयैव प्रत्यवमृशन्तीति तात्पर्यम् । तथाच परा काष्ठा आत्मज्ञानस्य ।',
    note: 'Bounded: ke-cit gloss through the parā-kāṣṭhā close (excludes the sāṅkhya turn after). Hyphen joined (साक्षा-कुर्वन्ति). साक्षाकुर्वन्ति retained verbatim (त् possibly extraction loss, as with अहकार; uncollated, never corrected). Opening " (extraction renders the opening quote glyph as ASCII) retained as an extraction-noise class, as elsewhere. सहजसिद्धतत्त्वज्ञाना निरुत्तरपरमेश्वरानुग्रह भाजो, केन क, यन्त्र अधिकरणे, येन च अन्तः करणेन, यञ्च and तत् सर्व परब्रह्मरूपतयैव retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.24-sankhya',
    spanId: 'gita-seg-13.24-sankhya',
    unitIds: ['13.25'],
    ksts: ['13.24'],
    pdf: 304,
    folio: 294,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'संप्रत्येतावती योग्यतामप्राप्ताः ‘अन्ये सांख्येन’ प्रकृतिपुरुषविवेकरूपेण ज्ञानेन आत्मानं पश्यन्ति । अन्ये ‘योगेन’ पातञ्जलादिप्रणीतविधिना समाधिना, अन्ये तु ‘कर्मयोगेन’ यथोक्तज्ञाननिष्ठतया स्वकर्मानुष्ठानरूपेण समाधिना आत्मानं पश्यन्ति, इति आत्मज्ञानस्य परापर भेदेन प्रकारद्वयमुपन्यस्तम् । तत्र ध्यानेनेत्यादिना शुद्धज्ञानमात्रस्वरूपतया य उक्तः, सा च कर्मयोगिनामारूढावस्था । यथोक्त ‘योगारूढस्य तस्यैव शमः कारणमुच्यते । (६।३)',
    note: 'Bounded: samprati turn through the printed (६।३) close (excludes the joint-verse marker and the KSTS 13.25 gloss after). Hyphens joined (ध्यानेने-त्यादिना, कर्मयोगिना-मारूढावस्था). आत्मज्ञानस्य परापर भेदेन and पातञ्जलादिप्रणीतविधिना retained verbatim with spaces as extracted; uncollated. The (६।३) quotation is already edged as gita-xref-056. No [?].',
  },
  {
    id: 'gita-tx-13.25-samuccaya',
    spanId: 'gita-seg-13.25-samuccaya',
    unitIds: ['13.26'],
    ksts: ['13.25'],
    pdf: 305,
    folio: 295,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'कर्मयोगेनेति समुच्चयात्मकत्वेऽपि कर्मप्रधाना कर्मयोगिनामारुरुक्ष्यवस्था ‘आरुरुक्षोर्मुनेर्योग इत्यादिना प्राप्रतिपादिता, इति द्विप्रकारः पर उपायः, सांख्येन योगेन च, इति अपरः स्थूलभेदप्रतिपत्तेरनुमानात् ।',
    note: 'Bounded: karmayogeneti turn through the anumānāt close (excludes the śruta-upāsaka turn after). Hyphen joined (कर्मयोगिना-मारुरुक्ष्य). समुच्चयात्मकत्व now stands as source-text evidence (the Phase-7 locator-only gap is closed). The partial आरुरुक्षो quotation has no printed locator: retained as unresolved source evidence, no edge. प्राप्रतिपादिता retained verbatim; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.25-sruta',
    spanId: 'gita-seg-13.25-sruta',
    unitIds: ['13.26'],
    ksts: ['13.25'],
    pdf: 305,
    folio: 295,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: '‘अन्ये पुनर्विप्रकारेऽपि उपाये संप्रति योग्यताभावात् ‘एवं यथोक्तेन प्रकारेण आत्मानम् ‘अजानन्तः’ तावन्मात्रशुद्धादिगुणयोगात् ‘अन्येभ्यो’ दृष्टानुमितं तत आप्तेभ्यः ‘श्रुत्वा’ अवधार्य आगममात्रशरणास्तम् ‘उपासते’ भजन्ते । ‘तेऽपि’ तथाविधाः श्रद्धालक्षणस्य सिद्धिबीजस्य क्षेत्रीभूताः सन्तो ‘मृत्युमतितरन्त्येव’ अविनाशिनमात्मानं क्रमेण प्रतिपद्यन्ते सत्यार्थाभिनिवेशित्वात् । यतः सत्यमसत्यं च द्वयमपि संभवति । विद्यानुगृहीताः सत्यमभिनिविशन्ते, मायामोहितास्तु असत्यं; ते च तादृशमेव फलं प्राप्नुवन्ति । तथाच उक्तम् ‘अमृतं चैव मृत्युश्च द्वयं देहे प्रतिष्ठितम् मृत्युमापद्यते मोहात् सत्यत्वेऽमृतमाहितम् ॥ इति ।',
    note: 'Bounded: anye-punar turn through the joint-verse close (verse-number marker excluded). Hyphens joined (आग-ममात्र, श्रद्धा-लक्षणस्य); सत्य-मभिनिविशन्ते joins across a bare break. ‘अन्ये पुनर्विप्रकारेऽपि उपाये retained with space as extracted. The amṛta quotation (तथाचोक्तम्) has no locator: retained as unresolved source evidence, no edge. The quotation close ॥ is print punctuation, retained. No [?].',
  },
  {
    id: 'gita-tx-13.26-samyoga',
    spanId: 'gita-seg-13.26-samyoga',
    unitIds: ['13.27'],
    ksts: ['13.26'],
    pdf: 305,
    folio: 295,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'उक्तमेव अर्थ स्फुटतरं प्रतिपादयितुमा अध्यायपरिसमाप्तेराह- ‘यावत्’ यत्परिमाणमपरिसंख्येयं ‘किञ्चित् सत्त्वं’ केनचिद्भेदेन युक्तं प्राणिजातं ‘संभवति’ विद्यते, ‘तत्’ सर्व क्षेत्रस्य शरीरभावेन परिणतायाः प्रकृतेस्तथा क्षेत्रज्ञस्य नानाशरीरित्वाभिमानेन व्यवस्थितस्य आत्मनः संयोगादनादिप्रबन्धप्रवृत्तादन्योन्यसंबन्धात् हेतोः ‘विद्धि’ विजानीहि । किमुक्तं भवति । अस्य अपर्यवसानस्य नानाचराचरभावरूपस्य प्रपञ्चस्य अविवेचितस्वरूपतया प्रकृतिपुरुषयोः शरीरशरीरिभावेन एकतया संबन्धो निमित्तम् । अतः शरीरशरीरिणोर्विवेक आद्यः प्रकारो यथाप्रतिपादितस्य ज्ञानस्य तेन शरीरभावपरिणत प्रकृतिविविक्तस्वरूपे सुविज्ञाते आत्मनि वेदकत्वमात्रैकलक्षणाव्यभिचारात् सर्वक्षेत्रज्ञप्रतिपत्ति भ्रमनिवृत्तेरिति ।',
    note: 'Bounded: uktameva turn through the verse close (mūla excluded; verse-number marker excluded). Hyphens joined (केनचि-द्भेदेन, शरी-रभावेन, नानाशरीरित्वा-भिमानेन, प्रवृ-त्तादन्योन्य, अविवेचि-तस्वरूपतया, यथा-प्रतिपादितस्य, सर्वक्षेत्रज्ञ-प्रतिपत्ति); the last two join across printed pp.295–296. उक्तमेव अर्थ, प्रतिपादयितुमा, तत् सर्व क्षेत्रस्य, शरीरभावपरिणत प्रकृतिविविक्तस्वरूपे and प्रतिपत्ति भ्रमनिवृत्तेरिति retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.27-sama',
    spanId: 'gita-seg-13.27-sama',
    unitIds: ['13.28'],
    ksts: ['13.27'],
    pdf: 306,
    folio: 296,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'योगी परमात्मनः स्वाभाविकैक्यदर्शनात् सम्यग्दर्शी भवतीत्याह । ‘सर्वेषु’ जङ्गमेषु स्थावरेषु च द्विप्रकारेषु अपि अवान्तर भेदादनन्तविशेषेषु अपि ‘भूतेषु सम’ जन्मादिविकाररहितत्वात् निर्विशेषं ‘तिष्ठन्त’ परमार्थनित्यत्वात् सदा वर्तमानं ‘परमेश्वरं’ स्वतन्त्रं परमात्मानं यो योगी ‘पश्यति’ आत्मत्वेन प्रत्यवमर्शात् साक्षात्कुरुते, ‘स पश्यति’ तस्य एव सत्यार्थदर्शित्वात् पारमार्थिकं द्रष्टृत्वं तव्यतिरिक्तात्मनानात्वदर्शिनः सर्वे मिथ्यार्थदर्शिन इत्यर्थः ।',
    note: 'Bounded: yogī turn through the sākṣātkurute close (the local mūla verse KSTS 13.27 between the turn and the sarveṣu gloss is excluded by policy, hence the boundary mark after भवतीत्याह). Hyphens joined (भेदा-दनन्त, निर्वि-शेषं). त्याह is extracted on its own line before योगी and भवती- at the line end before the verse: joined as भवतीत्याह (extraction line-misorder around the verse; uncollated against page images). अवान्तर भेदा, तव्यतिरिक्तात्मनानात्वदर्शिनः retained verbatim with spaces as extracted. No [?].',
  },
  {
    id: 'gita-tx-13.27-samapasya',
    spanId: 'gita-seg-13.27-samapasya',
    unitIds: ['13.28'],
    ksts: ['13.27'],
    pdf: 306,
    folio: 296,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'कीदृशेषु भूतेषु कीदृशं पश्यति । ‘विनश्यत्सु’ विनाशान्तजन्मादिविकारभागिषु ‘अविनश्यन्तं’ वेदकत्वमात्रादेकस्मात् स्वभावादप्रच्यवमानम् । स हि तथाविधो योगी समुन्मिषितेन यथोपवर्णितेन ज्ञानमयेन चक्षुषा प्रादुर्भावतिरोभावधर्मकसकलवेद्यांश विविक्तस्वरूपं वेदकैकलक्षणं परमात्मानं सर्वावस्थासु एकतत्त्वमात्मत्वेन साक्षात्कुर्वन् सम्यग्दर्शन उच्यते, अन्ये तु विपरीतदर्शना इत्यर्थः । स एवच आत्मवानिति ।',
    note: 'Bounded: kīdṛśeṣu turn through the verse close (verse-number marker excluded). Hyphens joined (स्वभा-वादप्रच्यवमानम्, यथो-पवर्णितेन, सकलवे-द्यांश, एकत-त्त्वमात्मत्वेन, विप-रीतदर्शना). सकलवेद्यांश विविक्तस्वरूपं, स एवच and यथोपवर्णितेन retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.28-atmahimsa',
    spanId: 'gita-seg-13.28-atmahimsa',
    unitIds: ['13.29'],
    ksts: ['13.28'],
    pdf: 306,
    folio: 296,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'यस्मात् यथोक्तेन प्रकारेण ‘सर्वत्र’ प्राकृतभावमयवेद्यवर्गे ‘समं’ सामान्यसंविद्रूपतया तुल्यं कृत्वा ‘समवस्थितं स्वभावतएव सम्यक्तप्रतिष्ठम् ‘ईश्वरं प्रभु परमात्मानं ‘पश्यन् प्रत्यभिजानन् कश्चिदेव ‘आत्मना’ स्वयमेव ‘आत्मानं’ सत्यस्वभावं ‘न हिनस्ति’ अप्रत्यभिज्ञानेन सन्तमेव अभावं न प्रापयति । किमुक्तं भवति । य एवंप्रतिपादितेन ज्ञानचचुषा क्षेत्रक्षेत्रज्ञविविक्तं परमात्मानं न पश्यति, स आत्मघातयुक्तो मुख्यया वृत्त्या । यथोक्त ‘योऽन्यथा सन्तमात्मानमन्यथा प्रतिपद्यते । किं तेन न कृतं पापं चौरेणात्मापहारिणा ॥ इति ।',
    note: 'Bounded: yasmāt turn through the iti close (verse-number marker excluded). Hyphens joined across the bare break (स्वभावत-एव); प्रत्य-भिजानन्. Runs to printed p.297. ‘ईश्वरं प्रभु परमात्मानं, सन्तमेव अभावं and ज्ञानचचुषा retained verbatim with spaces as extracted; uncollated. The anyathā quotation (यथोक्त) has no locator: retained as unresolved source evidence, no edge. The quotation close ॥ is print punctuation, retained. No [?].',
  },
  {
    id: 'gita-tx-13.29-prakrtya',
    spanId: 'gita-seg-13.29-prakrtya',
    unitIds: ['13.30'],
    ksts: ['13.29'],
    pdf: 307,
    folio: 297,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'प्रकृतिश्चेतनाचेतन विभागेन परापररूपा प्राप्रतिपादितद्विप्रकारा परमेश्वरेच्छावशोदेव क्षेत्रक्षेत्रज्ञ भावेन अनादिना संबन्धेन संबद्धा सती सर्वमिदं जगचित्रं विरचयति । तथाच सप्तमेऽध्याये द्विप्रकारायाः प्रकृतेः स्वरूपं प्रतिपाद्य उक्तम् ‘एतद्योनीनि भूतानि सर्वाणीत्युपधारय’ । (७।६) इति । अस्मिन्नपि अध्याये ‘यावत् संभवति किञ्चित्।’ (१३।२६) इत्यादिना श्लोकेन एष एव अर्थोऽभिहितः ।',
    note: 'Bounded: prakṛtiśca turn through the abhihitaḥ close (excludes the tadevarūpayā turn after). Hyphen joined across the bare break (प्राप्रतिपादि-तद्विप्रकारा). क्षेत्रक्षेत्रज्ञ भावेन, परमेश्वरेच्छावशोदेव and एष एव अर्थोऽभिहितः retained verbatim with spaces as extracted; uncollated. The (७।६) quotation is already edged as gita-xref-057 and the (१३।२६) quotation as gita-xref-039. No [?].',
  },
  {
    id: 'gita-tx-13.29-akartra',
    spanId: 'gita-seg-13.29-akartra',
    unitIds: ['13.30'],
    ksts: ['13.29'],
    pdf: 307,
    folio: 297,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तदेवरूपया ‘प्रकृत्यैव केवलया ‘क्रियमाणानि’ निर्व मानानि नानाशरीरसंबद्धत्वेन अवभासमानानि कुत्नानि ‘कर्माणि’ विविधाः क्रियाः ‘यः’ आत्मतत्त्वदर्शी ‘पश्यति’ सम्यक् निरूपयति, स तादृशो योगी ‘तथा’ तेन प्रकारेण ‘आत्मानं’ ब्रह्मस्वरूपं सत्यस्वभाव सर्वदा विशुद्धचिन्मात्रस्वरूपे स्वात्मनि एव सुप्रतिष्ठित सन्तं ‘अकर्तार’ परमार्थतः सर्वक्रियासु अव्या तत्वात् स्वरूपव्यतिरिक्तकार्यनिर्वृत्ति प्रयत्न रहितं ‘पश्यति’ । किमुक्तं भवति । यथा क्षेत्रज्ञस्य प्रकृत्यभेदाभिमानेन कर्तृत्वं, न तथा परमात्मनः । तस्य हि स्वरूपप्रत्यवमर्शमात्रे मुख्या कर्तृता, क्षेत्रज्ञस्य कर्तृतोद्भावनेन गौणी, इति योऽयं कर्तृकार्यव्यपदेशः, स सर्वो भेदनिबन्धनः, भेदश्च मायामात्रविलसितो न वस्तुसत्तामवलम्बते । तत एकस्य तत्वस्य व्यतिरिक्तकार्यनिबन्धनं कर्तृत्वं न वास्तवमिति तात्पर्यम् ।',
    note: 'Bounded: tadevarūpayā turn through the verse close (verse-number marker excluded). Hyphen joined (स्वरूप-व्यतिरिक्त); वस्तुसत्तामव -लम्बते joins across a spaced hyphen. Runs to printed p.298. ‘प्रकृत्यैव केवलया and सत्यस्वभाव सर्वदा join bare line breaks with a space (print word-break, not content). निर्व मानानि, कुत्नानि, ‘यः’ आत्मतत्त्वदर्शी, सुप्रतिष्ठित सन्तं, अव्या तत्वात्, स्वरूपव्यतिरिक्तकार्यनिर्वृत्ति प्रयत्न रहितं and तत एकस्य तत्वस्य retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.30-ekatva',
    spanId: 'gita-seg-13.30-ekatva',
    unitIds: ['13.31'],
    ksts: ['13.30'],
    pdf: 308,
    folio: 298,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'इत्थंच स्थिते प्रकृतिपुरुषविवेकज्ञानादनन्तरं वास्तवज्रह्मलक्षणैकतत्त्वविषये परं ज्ञानमाविर्भवतीति प्रतिपादयितुमाह - ‘तदा’ तस्मिन् काले योगी ‘ब्रह्म संपद्यते’ यथोक्तपरमात्मनि परमार्थसत्ये एकस्मिस्तत्त्वे समापत्तिमाप्नोति । कदा । ‘यदा’ यस्मिन् काले विवेकज्ञाननैर्मल्यात् सम्यक्प्रकाशमानसर्वगतैकक्षेत्रज्ञस्वरूपो योगी ‘भूतपृथग्भाव’ भूतानां चराचराणामनन्तभेदानां पृथग्भावमन्योन्यव्यतिरिक्तत्वम् ‘एकस्थमनुपश्यति’ एकस्मिन् परमात्मनि अभिन्न संवित्प्रकाशमात्रे स्थितं तदात्मकत्वेन एव वर्तमानं साक्षात्करोति । किमनेन उक्तं भवति । प्रकाशपदवीजुषां सर्वभावानां प्रकाशमानतामात्राधीनात्मलाभानां वास्तवीं परप्रकाशैकरूपतां यदा अनुभवति योगी, यथाच सर्वमेकथं पश्यति,',
    note: 'Bounded: itthañca turn through the eka-dhā close (excludes the tata-eva turn after; the sentence continues in the next passage). Hyphens joined (सम्यक्प्रकाशमानसर्वगतैक-क्षेत्रज्ञ, अनन्त-भेदानां, एक-स्मिन्, परप्र-काशैकरूपतां). अभिन्न संवित्प्रकाशमात्रे, तदात्मकत्वेन एव वर्तमानं (bare break space-joined), वास्तवीं and सर्वमेकथं retained verbatim with spaces as extracted; uncollated. वास्तवज्रह्म retained verbatim. No [?].',
  },
  {
    id: 'gita-tx-13.30-vistara',
    spanId: 'gita-seg-13.30-vistara',
    unitIds: ['13.31'],
    ksts: ['13.30'],
    pdf: 308,
    folio: 298,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तथैव यदा ‘तत एव’ एकस्मात् तत्त्वात् ‘विस्तार’ नानाभावमयं विभूतिवैतत्यं पश्यति, तदा ब्रह्म संपद्यते । अनेन अपि किमुक्त भवति । विवेकजज्ञाननिष्णातनिर्मलमतिर्योगी यथा एकस्मिस्तत्त्वे लीनं सर्व भेदजातं तदभिन्नं पश्यति, तथैव तदेव एकं तत्त्वं विश्वभावभेदात्मना प्रसृतं तस्य सर्वात्मना भावनानात्वप्रतिपत्तिभ्रमो विगलतीत्यर्थः । तथाच अयमेव अर्थः केनापि विपश्चिता अनूदितः ‘यद्यत् पृथक्त्वसंदिग्धं तत्पृथक्त्वान्न भिद्यते ।’ इति ।',
    note: 'Bounded: tathaiva turn through the joint-verse close (verse-number marker excluded; continues the ekatva sentence). Runs to printed p.299. नानाभावमयं विभूतिवैतत्यं joins a bare break with a space. अनेन अपि किमुक्त, सर्व भेदजातं, तदेव एकं तत्त्वं and अयमेव अर्थः retained verbatim with spaces as extracted; uncollated. The vipascit quotation (केनापि विपश्चिता) has no locator: retained as unresolved source evidence, no edge. No [?].',
  },
  {
    id: 'gita-tx-13.31-avyaya-a',
    spanId: 'gita-seg-13.31-avyaya-a',
    unitIds: ['13.32'],
    ksts: ['13.31'],
    pdf: 309,
    folio: 299,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'तदेवंविधस्य परमात्मनो बहुशोऽपि उक्तं लक्षणं प्रसङ्गात् पुनराह- ‘अयं’ भगवान् ‘परमात्मा’ परं तत्त्वं स्वभावत एव सर्वत्र सर्वदा च अव्याहतसद्भावः, ततश्च सर्वस्मिन् शरीरे स्थितिरबाधिता एव । तथापिच तत्रस्थोऽपि प्रतिपादितैकस्वरूपमात्रे सुस्थितत्वात् ‘न करोति’ न भिन्नकार्यनिबन्धनं कर्तृत्वमनुभवति, ततश्च का कथा कर्मफलानुभवस्थेति ‘न लिप्यते’ ।',
    note: 'Bounded: tadevaṃvidhasya turn through the na-lipyate close (excludes the anāditvāt turn after). Hyphens joined (अबाधि-ता, सुस्थित-त्वात्). बहुशोऽपि उक्तं retained with space as extracted. No [?].',
  },
  {
    id: 'gita-tx-13.31-avyaya-b',
    spanId: 'gita-seg-13.31-avyaya-b',
    unitIds: ['13.32'],
    ksts: ['13.31'],
    pdf: 309,
    folio: 299,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'यस्मात् ‘अनादित्वात्’ सर्वकारणत्वात्, अत एव ‘निर्गुणत्वात्’ गुणेभ्य उदयव्ययधर्मकेभ्यो निष्कान्तत्वात् तद्विविक्तस्वभावत्वात् ‘अव्ययः’ गुणवत् व्ययेन विनाशेन रहितः । यद्यपि अनादित्वमव्ययत्वं च क्षेत्रज्ञस्य अपि उक्तं, तथापि तस्य गुणमय्या प्रकृत्या संबद्धस्य तत्स्वरूपानुविधायित्वात् तत्तदुदयव्ययधर्मकत्वमुपचर्यते आ विद्योदयात् । परमात्मनस्तु उपचारोऽपि नास्ति । अतः क्षेत्रज्ञवत् न तस्य कर्तृत्वं, न कर्मफलसंयोग इति ।',
    note: 'Bounded: yasmāt turn through the verse close (verse-number marker excluded). Hyphens joined (‘अनादि-त्वात्’, गुणवत् across गुण-वत्, तत्स्वरू-पानुविधायित्वात्, विद्यो-दयात्). क्षेत्रज्ञस्य अपि उक्तं and आ विद्योदयात् retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.32-akasa',
    spanId: 'gita-seg-13.32-akasa',
    unitIds: ['13.33'],
    ksts: ['13.32'],
    pdf: 310,
    folio: 300,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'यथाच एतस्य सर्वशरीरस्थत्वेऽपि कर्म फलसंयोगलक्षणकलङ्क संपर्काभावस्तथा उपमानेन दर्शयितुमाह - ‘यथा सौक्ष्म्यात्’ अणीयस्त्वात् ‘सर्वगतं’ समस्तवस्तुव्यापर्क देशकालायनवच्छिन्नमाहात्म्यम् ‘आकाशम्’ अवच्छिन्नैप्यैर्भावैः ‘न उपलिप्यते’ स्वधर्मेण न संयोज्यते, ‘तथा’ एव ‘सर्वत्र’ सर्वस्मिन् सुरनरतिर्यगाद्यनन्तभेदेऽपि ‘देहे’ शरीरे व्यापकतया ‘अवस्थितः’ नित्यसंनिहितोऽपि अयं परमात्मा तद्धर्मैः सुखदुःखादिभिरुत्पाद विनाशादिभिर्वा कर्मफलसंबन्धित्वाभिमानजन्मभिः ‘नोपलिप्यते’ न संस्पृश्यते । तथाच उक्तं ब्रह्मविदा केनचित् ‘यथैकस्मिन्घटाकाशे रजोधूमादिभिवृते । संयुज्यन्ते न सर्वाणि तथा जीवाः सुखादिभिः ॥’ इति ।',
    note: 'Bounded: yathāca turn through the verse close (verse-number marker excluded). Hyphens joined (अवच्छिन्नै प्यैर्भा-वैः, सुखदुः-खादिभिरुत्पाद, अभिमानज-न्मभिः). कर्म फलसंयोगलक्षणकलङ्क, समस्तवस्तुव्यापर्क देशकालायनवच्छिन्नमाहात्म्यम्, सुखदुःखादिभिरुत्पाद विनाशादिभिर्वा retained verbatim with spaces as extracted; uncollated. The ghaṭākāśa quotation (ब्रह्मविदा केनचित्) has no locator: retained as unresolved source evidence, no edge. The quotation close ॥ is print punctuation, retained. No [?].',
  },
  {
    id: 'gita-tx-13.33-ravi',
    spanId: 'gita-seg-13.33-ravi',
    unitIds: ['13.34'],
    ksts: ['13.33'],
    pdf: 310,
    folio: 300,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'एवं सर्वात्मना कर्मफलसंपर्काभावेऽपि अनन्यसाधारणप्रकाशकत्वधर्मयोगात् स एव एकः क्षेत्रक्षेत्रज्ञव्यवहार प्रकाशक इत्युपमानान्तरेण दर्शयितुमाह - ‘यथा’ येन प्रकारेण अर्थ सकललोकप्रत्यक्षपरिदृश्यस्वभावो भगवान् भास्करः ‘कृत्नम्’ अखिलं ‘लोक’ नानाभावमयं विश्वम् ‘एक एव’ असहायः ‘प्रकाशयति’ स्वस्वरूपं लम्भयति, तेन एव प्रकारेण अयं ‘क्षेत्री’ सर्वक्षेत्रज्ञव्यापक ‘एक’ परमात्मा ‘क्षेत्रं प्रकाशयति’ इति ।',
    note: 'Bounded: evaṃ turn through the prakāśayati close (excludes the kimuktaṃ turn after). Hyphen joined across the page break (पर-मात्मा). Runs to printed p.301. क्षेत्रक्षेत्रज्ञव्यवहार प्रकाशक, अर्थ सकललोकप्रत्यक्षपरिदृश्यस्वभावो, तेन एव प्रकारेण and सर्वक्षेत्रज्ञव्यापक ‘एक’ retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.33-janaka',
    spanId: 'gita-seg-13.33-janaka',
    unitIds: ['13.34'],
    ksts: ['13.33'],
    pdf: 311,
    folio: 301,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'किमुक्त भवति । प्रकाश्यवस्तुनानात्वात् प्रकाशस्य परमात्मधर्मस्य यदि परं नानात्वोपचारः परमार्थतस्तु एक एव सकलप्रकाश्यवस्तुप्रकाशकः । प्रकाशकत्वमात्रे च उपमानोपमेयभावो रविक्षेत्रिणोः । यथा हि रविर्भावानां प्रकाशको, न तथा च क्षेत्री । तथाहि कुतश्चित् कारणात् लब्धात्मनां घटगवादीनामर्थानामभिव्यञ्जकत्वमात्रेण रविः प्रकाशको न जनकत्वेन, क्षेत्री तु प्रकाश्यत्वापादनेन एव तान् जनयति, अतो जनकत्वं तस्य, इति प्राक् प्रतिपादित्तमेव ।',
    note: 'Bounded: kimuktaṃ turn through the pratipāditam close (excludes the adhyāya-upasaṃhāra after). Hyphens joined across bare breaks (प्रकाश्यवस्तुना-नात्वात्, पर-मार्थतस्तु, लब्धा-त्मनां). किमुक्त भवति, कुतश्चित् कारणात्, प्रकाश्यत्वापादनेन एव and प्राक् प्रतिपादित्तमेव retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.34-moksa',
    spanId: 'gita-seg-13.34-moksa',
    unitIds: ['13.35'],
    ksts: ['13.34'],
    pdf: 311,
    folio: 301,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'न केवलं तयोरन्तरं जानते, यावत् ‘भूतप्रकृतिमोक्षं च ये जानते । भूतात्मिकाया इयं प्रकृतिः स्थूला निर्दिष्टा, ततो मोक्षं पुनस्तत्र प्रवेशाभावादात्यन्तिकं बन्धत्यागं ये विदन्ति । किमुक्तं भवति । क्षेत्रक्षेत्रज्ञयोः परस्पर विविक्तस्वरूपावगममात्रमागमोपपत्तिपरिशीलनद्वारेण कदाचित् संभवति, नतु तावता प्रकृतेर्मोक्षः प्रभवति, स हि तद्विविक्तात्मस्वरूप नित्यावहितत्वेन एव भवति । ततः पृथगुक्तं ‘भूतप्रकृतिमोक्ष’ च इति ।',
    note: 'Bounded: na-kevalaṃ turn through the iti close (follows the transcribed antara sentence; excludes the te-para turn after). Hyphen joined (प्रवेशा-भावादात्यन्तिकं, परिशीलन-शीलनद्वारेण is परि-शीलनद्वारेण). भूतात्मिकाया इयं joins a bare break without hyphen; प्रकृतेर्मोक्षः प्रभवति joins a bare break with a space. भूतप्रकृतिमोक्ष now stands as source-text evidence (the Phase-7 locator-only gap is closed). परस्पर विविक्तस्वरूपावगममात्रमागमोपपत्तिपरिशीलनद्वारेण, तद्विविक्तात्मस्वरूप नित्यावहितत्वेन एव and ये विदन्ति retained verbatim with spaces as extracted; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.34-para',
    spanId: 'gita-seg-13.34-para',
    unitIds: ['13.35'],
    ksts: ['13.34'],
    pdf: 311,
    folio: 301,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: '‘ते’ एवंविधाः ‘परं निरुत्तरं तत्त्वं सप्तमे परतरप्रकृतित्वेन प्रतिपादितं परमात्मानं ‘यान्ति’ प्रतिपद्यन्ते तदभेदलक्षणां परां सिद्धिमधिगच्छन्ति, - इत्योम् ।',
    note: 'Bounded: te turn through the iti-om close (verse-number marker excluded; excludes the praśasti after). Runs to printed p.302. ‘परं निरुत्तरं joins a bare page break without hyphen. - इत्योम् (इति + ओम्) retained verbatim; uncollated. No [?].',
  },
  {
    id: 'gita-tx-13.34-prasasti',
    spanId: 'gita-seg-13.34-prasasti',
    unitIds: ['13.35'],
    ksts: ['13.34'],
    pdf: 312,
    folio: 302,
    sourceId: KSTS_SOURCE_ID,
    status: 'text-layer-reviewed',
    text: 'भविभिरखि र्नित्यं तापत्रयीपरिशोषितात् परमविरसात् क्षेत्राद्धोगो यतः किल भुज्यते । चिदमृतघनात् तद्वोऽध्यायात् प्रयोदशतः सुतेवैचनपृषतैः सिक्तं सूतां विमुक्तिफलश्रियम् ॥ इति श्रीमद्राजानकरामकण्ठविरचिते वाक्यार्थान्वयमात्रे सर्वतोभद्रनानि भगवद्गीताविवरणे त्रयोदशोऽध्यायः ॥ १३ ॥',
    note: 'Bounded: authorial praśasti verse with the fixed colophon (a distinct span from the locator-only closing-apparatus record gita-seg-13.34-closing, which is untouched). Hyphen joined across the bare break (सर्वतो-भद्रनानि, सुते-वैचन). भविभिरखि र्नित्यं, क्षेत्राद्धोगो, तद्वोऽध्यायात्, प्रयोदशतः (extraction for त्रयोदशतः uncertain), सुतेवैचनपृषतैः and सूतां विमुक्तिफलश्रियम् retained verbatim with spaces as extracted; uncollated against page images, never corrected. The colophon ॥ १३ ॥ marks the adhyāya, not a verse, and is retained as apparatus. No [?].',
  },
];

/** Devanagari source text plus print punctuation, digits, brackets and whitespace. */
const SOURCE_SCRIPT = /^[\u0900-\u097F\s\d।॥‘’'"()\[\]?.,;:\-–—]+$/;

/** True when a string is plausible diplomatic transcription (never prose). */
export function isSourceTranscription(value: unknown): boolean {
  return (
    typeof value === 'string' &&
    value.trim().length > 0 &&
    /[\u0900-\u097F]/.test(value) &&
    SOURCE_SCRIPT.test(value) &&
    !/[a-zA-Z]/.test(value)
  );
}

/** Structured validation for passage records (tests + future build gate). */
export function validatePassages(records: GitaCommentaryText[]): string[] {
  const errors: string[] = [];
  const seen = new Set<string>();
  for (const record of records) {
    if (!record.id || !record.id.trim()) {
      errors.push('passage without id');
      continue;
    }
    if (seen.has(record.id)) errors.push(`duplicate passage id ${record.id}`);
    seen.add(record.id);
    if (!['verified-source', 'text-layer-reviewed', 'page-image-collated', 'partially-collated', 'extraction-unreviewed', 'partially-verified'].includes(record.status)) {
      errors.push(`${record.id}: unknown status ${String(record.status)}`);
    }
    if (!record.sourceId || !record.sourceId.trim()) {
      errors.push(`${record.id}: missing source record`);
    }
    if (!Number.isInteger(record.pdf) || !Number.isInteger(record.folio)) {
      errors.push(`${record.id}: missing integer pdf/folio`);
    }
    if (!record.text || !isSourceTranscription(record.text)) {
      errors.push(`${record.id}: text absent or not Devanagari source transcription`);
    }
    if (record.text.includes('[?]') && !(record.note || '').trim()) {
      errors.push(`${record.id}: uncertainty markers without documenting note`);
    }
    if (!record.unitIds || record.unitIds.length === 0) {
      errors.push(`${record.id}: no canonical units`);
    }
    for (const ref of record.ksts || []) {
      if (!parseGitaVerseRef(ref)) errors.push(`${record.id}: invalid KSTS ref ${ref}`);
    }
  }
  return errors;
}

export function passageById(id: string): GitaCommentaryText | undefined {
  return GITA_COMMENTARY_TEXTS.find((p) => p.id === id);
}

/** Passages evidencing one span (a span may carry several excerpts). */
export function passagesForSpan(spanId: string): GitaCommentaryText[] {
  return GITA_COMMENTARY_TEXTS.filter((p) => p.spanId === spanId);
}
