import type { GitaReference } from './gitaDocument';

/**
 * Verified commentary quotation edges (Phase 2).
 *
 * Each edge pairs a quoted Gītā pāda with its printed locator and the
 * KSTS target verse identified from the quotation itself (never from
 * the digits alone — separators drop in extraction and a few printed
 * refs disagree with their quotes; disagreements were excluded, see the
 * architecture document). Hosts are the nearest preceding KSTS verse
 * marker; introductory/avataraṇikā matter has no host verse (null with
 * a note). Targets without a canonical unit (KSTS extras) keep null
 * toUnitId; the (2,50) quotation additionally resolves to adhika.8,
 * the unit carrying that content.
 */

export const GITA_QUOTATION_EDGES: GitaReference[] = [
  { id: 'gita-xref-001', fromKsts: null, fromUnitId: null, toKsts: { chapter: 10, verse: 39 }, toUnitId: '10.39', quotedText: 'न तदस्ति विना यत्स्यान्मया भूतं चराचरम् ।', locator: '(१००३९)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-002', fromKsts: null, fromUnitId: null, toKsts: { chapter: 11, verse: 47 }, toUnitId: null, quotedText: 'नान्योऽस्ति कर्ता जगतस्त्वमेको धाता विधाता च विभुभवश्च ।', locator: '(११।४७)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-003', fromKsts: null, fromUnitId: null, toKsts: { chapter: 15, verse: 15 }, toUnitId: '15.15', quotedText: 'सर्वस्य चाहं हृदि संनिविष्टो मत्तः स्मृतिर्ज्ञानमपोहनं च ।', locator: '(१५/१५)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-004', fromKsts: null, fromUnitId: null, toKsts: { chapter: 9, verse: 4 }, toUnitId: '9.4', quotedText: 'मत्स्थानि सर्वभूतानि"........', locator: '(९॥४)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter); quote follows the vulgate reading (सर्वं) against KSTS mūla (सेवे)' },
  { id: 'gita-xref-005', fromKsts: null, fromUnitId: null, toKsts: { chapter: 9, verse: 4 }, toUnitId: '9.4', quotedText: 'मया ततमिदं सर्वं जगदव्यक्तमूर्तिना ।', locator: '(९१४)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter); quote follows the vulgate reading (सर्वं) against KSTS mūla (सेवे)' },
  { id: 'gita-xref-006', fromKsts: null, fromUnitId: null, toKsts: { chapter: 11, verse: 48 }, toUnitId: null, quotedText: 'कर्तासि सर्वस्य यतः स्वयं वै विभो ततः सर्वमिदं त्वमेव ।', locator: '(११।४८)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-007', fromKsts: null, fromUnitId: null, toKsts: { chapter: 2, verse: 26 }, toUnitId: '2.25', quotedText: 'अव्यक्तोऽयमचिन्त्योऽयमविकार्योऽयमुच्यते  ।', locator: '(२।२६)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-008', fromKsts: null, fromUnitId: null, toKsts: { chapter: 7, verse: 10 }, toUnitId: '7.10', quotedText: 'बीजं मां सर्वभूतानां विद्धि पार्थ सनातनम् ।', locator: '(७।१०)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-009', fromKsts: null, fromUnitId: null, toKsts: { chapter: 13, verse: 31 }, toUnitId: '13.32', quotedText: 'यदा भूतपृथग्भावमेकस्थमनुपश्यति । तत एवच विस्तारं ब्रह्म संपद्यते तदा ।', locator: '(१३।३१)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-010', fromKsts: null, fromUnitId: null, toKsts: { chapter: 16, verse: 6 }, toUnitId: '16.6', quotedText: 'हौ भूतसग लोकेऽस्मिन्दैव आसुर प्रवच ।', locator: '(१६।६)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-011', fromKsts: null, fromUnitId: null, toKsts: { chapter: 9, verse: 11 }, toUnitId: '9.10', quotedText: 'मयाध्यक्षेण प्रकृतिः सूयते सचराचरम् ।', locator: '(९।११)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-012', fromKsts: null, fromUnitId: null, toKsts: { chapter: 16, verse: 18 }, toUnitId: '16.18', quotedText: '(१६१८) इत्यादि प्रद्विषन्तोऽभ्यसूयकाः ।', locator: '(१६।१८)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-013', fromKsts: null, fromUnitId: null, toKsts: { chapter: 18, verse: 55 }, toUnitId: '18.55', quotedText: 'समः सर्वेषु भूतेषु मद्भक्ति लभते पराम् । * भक्तया मामभिजानाति सोऽहं यश्चास्मि तत्त्वतः ॥', locator: '(१८५५)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-014', fromKsts: null, fromUnitId: null, toKsts: { chapter: 4, verse: 1 }, toUnitId: '4.1', quotedText: 'एवं विवखते योगं प्रोक्तवानहमव्ययम् ।', locator: '(४।१)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-015', fromKsts: null, fromUnitId: null, toKsts: { chapter: 4, verse: 3 }, toUnitId: '4.3', quotedText: 'स एवायं मया तेऽद्य योगः प्रोक्तः पुरातनः । भक्तोऽसि मे सखा चेति रहस्यं चैतदुत्तमम् ॥', locator: '(४।३)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-016', fromKsts: { chapter: 1, verse: 7 }, fromUnitId: '1.7', toKsts: { chapter: 3, verse: 31 }, toUnitId: '3.31', quotedText: 'श्रद्धावन्तोऽनसूयन्तो मुच्यन्ते सर्वकिल्विषैः ।', locator: '(३।३१)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-017', fromKsts: { chapter: 2, verse: 56 }, fromUnitId: '2.54', toKsts: { chapter: 2, verse: 50 }, toUnitId: 'adhika.8', quotedText: 'यस्य सर्वे समारम्भाः', locator: '(५०)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-018', fromKsts: { chapter: 3, verse: 9 }, fromUnitId: '3.9', toKsts: { chapter: 18, verse: 46 }, toUnitId: '18.46', quotedText: 'यतः प्रवृत्तिर्भूतानां येन सर्वमिदं ततम् । स्वकर्मणा तमेवार्थ्य सिद्धिं विन्दति मानवः ॥', locator: '(१८४६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-019', fromKsts: { chapter: 3, verse: 23 }, fromUnitId: '3.23', toKsts: { chapter: 3, verse: 17 }, toUnitId: '3.17', quotedText: 'यस्त्वात्मरतिरेव स्यात्.... ............ तस्य कार्य न विद्यते ।', locator: '(३।१७)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-020', fromKsts: { chapter: 3, verse: 22 }, fromUnitId: '3.22', toKsts: { chapter: 3, verse: 19 }, toUnitId: '3.19', quotedText: 'तस्मादसक्तः सततं कार्य कर्म समाचर ।', locator: '(३।१९)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-021', fromKsts: { chapter: 3, verse: 28 }, fromUnitId: '3.28', toKsts: { chapter: 18, verse: 14 }, toUnitId: '18.14', quotedText: 'अधिष्ठानं तथा कर्ता ।', locator: '(१८१४)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-022', fromKsts: { chapter: 4, verse: 22 }, fromUnitId: '4.22', toKsts: { chapter: 3, verse: 9 }, toUnitId: '3.9', quotedText: 'यज्ञार्थात्कर्मणोऽन्यत्र लोकोऽयं कर्मबन्धनः ।', locator: '(३।९)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-023', fromKsts: { chapter: 5, verse: 2 }, fromUnitId: '5.2', toKsts: { chapter: 3, verse: 1 }, toUnitId: '3.1', quotedText: 'ज्यायसी चैत्कर्मणस्ते मता बुद्धिर्जनार्दन', locator: '(३।१)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-024', fromKsts: { chapter: 8, verse: 5 }, fromUnitId: '8.5', toKsts: { chapter: 9, verse: 25 }, toUnitId: '9.24', quotedText: 'अहं हि सर्वयज्ञानां भोक्ता च प्रभुरेवच ।', locator: '(९।२५)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-025', fromKsts: { chapter: 8, verse: 6 }, fromUnitId: '8.6', toKsts: { chapter: 7, verse: 29 }, toUnitId: '7.29', quotedText: 'ते ब्रह्म तद्विदुः कृत्नम् इत्यादिना तत्त्वत्रयमेतदुक्त्वा ।', locator: '(७२९)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-026', fromKsts: { chapter: 8, verse: 5 }, fromUnitId: '8.5', toKsts: { chapter: 7, verse: 30 }, toUnitId: '7.30', quotedText: 'साधिभूताधिदेवं मां साधियज्ञ च ते विदुः ।', locator: '(७३०)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-027', fromKsts: { chapter: 8, verse: 14 }, fromUnitId: '8.14', toKsts: { chapter: 8, verse: 6 }, toUnitId: '8.6', quotedText: 'यं यं भावं स्मरन्वापि ...', locator: '(८६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-028', fromKsts: { chapter: 8, verse: 17 }, fromUnitId: '8.17', toKsts: { chapter: 8, verse: 16 }, toUnitId: '8.16', quotedText: 'आ ब्रह्मभुवनालोकाः पुनरावर्तिनः', locator: '(८।१६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-029', fromKsts: { chapter: 8, verse: 25 }, fromUnitId: '8.25', toKsts: { chapter: 8, verse: 27 }, toUnitId: '8.27', quotedText: 'नैते सृती पार्थ जानन् योगी मुह्यति कश्चन ।', locator: '(८।२७)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-030', fromKsts: { chapter: 9, verse: 10 }, fromUnitId: '9.9', toKsts: { chapter: 4, verse: 13 }, toUnitId: '4.13', quotedText: 'तस्य कर्तारमपि मां विद्धयकर्तारमव्ययम् ।', locator: '(४।१३)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-031', fromKsts: { chapter: 9, verse: 10 }, fromUnitId: '9.9', toKsts: { chapter: 4, verse: 14 }, toUnitId: '4.14', quotedText: 'न मां कर्माणि लिम्पन्ति न मे कामः फलेष्वपि ।', locator: '(४।१४)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-032', fromKsts: { chapter: 9, verse: 13 }, fromUnitId: '9.12', toKsts: { chapter: 18, verse: 28 }, toUnitId: '18.28', quotedText: 'अयुक्तः प्राकृतः स्तब्धः शठो नैकृतिकोऽलसः विषादी दीर्घसूत्रश्च कर्ता तामस उच्यते ॥', locator: '(१८/२८)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-033', fromKsts: { chapter: 9, verse: 13 }, fromUnitId: '9.12', toKsts: { chapter: 18, verse: 22 }, toUnitId: '18.22', quotedText: 'यत्त्वक विदेकस्मिन् कार्ये सक्तमतुकम् । अतत्त्वार्थवदल्पं च तत्तामसमुदाहृतम् ।', locator: '(१८।२२)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-034', fromKsts: { chapter: 9, verse: 13 }, fromUnitId: '9.12', toKsts: { chapter: 18, verse: 27 }, toUnitId: '18.27', quotedText: 'रागी कर्मफलप्रेप्सुर्लुब्धो हिंसात्मकोऽशुचिः I हर्षशोकान्वितः कर्ता राजसः परिकी ते ।', locator: '(१८।२७)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-035', fromKsts: { chapter: 10, verse: 5 }, fromUnitId: '10.5', toKsts: { chapter: 6, verse: 9 }, toUnitId: '6.9', quotedText: 'सुहृन्मित्रा दासीन', locator: '(६।९)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-036', fromKsts: { chapter: 11, verse: 19 }, fromUnitId: '11.19', toKsts: { chapter: 17, verse: 23 }, toUnitId: '17.23', quotedText: 'सावतधर्मगोप्ता त्वम् । सदिति ब्रह्मनाम यद्वक्ष्यति तत्स दिति निर्देशो ब्रह्मणस्त्रिविधः स्मृतः ।', locator: '(१७२३)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-037', fromKsts: { chapter: 13, verse: 11 }, fromUnitId: '13.12', toKsts: { chapter: 13, verse: 12 }, toUnitId: '13.13', quotedText: 'ज्ञेयं यत्तत्प्रवक्ष्यामि ।', locator: '(१३।१२)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-038', fromKsts: { chapter: 13, verse: 6 }, fromUnitId: '13.7', toKsts: { chapter: 13, verse: 2 }, toUnitId: '13.3', quotedText: 'क्षेत्रज्ञ चापि मां विद्धि ।', locator: '(१३।२)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-039', fromKsts: { chapter: 13, verse: 29 }, fromUnitId: '13.30', toKsts: { chapter: 13, verse: 26 }, toUnitId: '13.27', quotedText: 'यावत् संभवति किञ्चित्।', locator: '(१३।२६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-040', fromKsts: null, fromUnitId: null, toKsts: { chapter: 13, verse: 12 }, toUnitId: '13.13', quotedText: 'अनादिमत्परं ब्रह्म......... ।', locator: '(१३।१२)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-041', fromKsts: null, fromUnitId: null, toKsts: { chapter: 13, verse: 34 }, toUnitId: '13.35', quotedText: 'भूतप्रकृतिमोक्षं च ये विदुः .. ।', locator: '(१३।३४)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-042', fromKsts: null, fromUnitId: null, toKsts: { chapter: 13, verse: 31 }, toUnitId: '13.32', quotedText: 'अनादित्वान्निर्गुणत्वात्परमात्मायमव्ययः । शरीरस्थोऽपि कौन्तेय न करोति न लिप्यते ॥', locator: '(१३३१)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-043', fromKsts: { chapter: 14, verse: 2 }, fromUnitId: '14.2', toKsts: { chapter: 3, verse: 25 }, toUnitId: '3.25', quotedText: 'सक्ताः कर्मण्यविद्वांसो यथा कुर्वन्ति भारत । कुर्याद्विद्वांस्तथासक्तश्चिकीर्षुर्लोकसंग्रहम् ॥', locator: '(३।२५)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-044', fromKsts: { chapter: 15, verse: 1 }, fromUnitId: '15.1', toKsts: { chapter: 8, verse: 16 }, toUnitId: '8.16', quotedText: 'आ ब्रह्म भुवनाल्लोकाः पुनरावर्तिनोऽर्जुन ।', locator: '(८।१६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-045', fromKsts: { chapter: 18, verse: 2 }, fromUnitId: '18.2', toKsts: { chapter: 2, verse: 50 }, toUnitId: 'adhika.8', quotedText: 'यस्य सर्वे समारम्भाः"', locator: '(२५०)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-046', fromKsts: { chapter: 18, verse: 6 }, fromUnitId: '18.6', toKsts: { chapter: 3, verse: 16 }, toUnitId: '3.16', quotedText: 'अघायुरिन्द्रियारामो  मोघं पार्थ स जीवति ।', locator: '(३।१६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-047', fromKsts: { chapter: 18, verse: 7 }, fromUnitId: '18.7', toKsts: { chapter: 14, verse: 17 }, toUnitId: '14.17', quotedText: 'प्रमादमोहो जायेते तमसोऽज्ञानमेवच ।', locator: '(१४।१७)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-048', fromKsts: { chapter: 18, verse: 7 }, fromUnitId: '18.7', toKsts: { chapter: 18, verse: 11 }, toUnitId: '18.11', quotedText: 'नहि देह ता शक्यं व्यक्तुं कर्माण्यशेषतः ।', locator: '(१८।११)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-049', fromKsts: { chapter: 18, verse: 7 }, fromUnitId: '18.7', toKsts: { chapter: 3, verse: 5 }, toUnitId: '3.5', quotedText: 'नहि कश्चित्क्षणमपि जातु तिष्ठत्यकर्मकृत् ।', locator: '(३५)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-050', fromKsts: { chapter: 18, verse: 30 }, fromUnitId: '18.30', toKsts: { chapter: 18, verse: 20 }, toUnitId: '18.20', quotedText: 'सर्वभूतेषु येनैकम्', locator: '(१८२०)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-051', fromKsts: { chapter: 18, verse: 41 }, fromUnitId: '18.41', toKsts: { chapter: 4, verse: 13 }, toUnitId: '4.13', quotedText: 'चातुर्वर्ण्य मया सृष्टं गुणकर्मविभागशः । तस्य कतीरमपि मां विद्ध्यकर्तारमव्ययम् ॥', locator: '(४।१३)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-052', fromKsts: { chapter: 18, verse: 47 }, fromUnitId: '18.47', toKsts: { chapter: 16, verse: 1 }, toUnitId: '16.1', quotedText: 'अभयं सत्त्वसंशुद्धि नियोगव्यवस्थितिः ।', locator: '(१६।१)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-053', fromKsts: { chapter: 18, verse: 67 }, fromUnitId: '18.67', toKsts: { chapter: 18, verse: 46 }, toUnitId: '18.46', quotedText: 'यतः प्रवृत्तिर्भूतानाम् ।', locator: '(१८४६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-054', fromKsts: null, fromUnitId: null, toKsts: { chapter: 7, verse: 6 }, toUnitId: '7.6', quotedText: 'अहं कृत्नस्य जगतः प्रभवः प्रलयस्तथा ।', locator: '(७।६)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (chapter-13 avatāraṇikā, printed p.276)' },
  { id: 'gita-xref-055', fromKsts: { chapter: 13, verse: 11 }, fromUnitId: '13.12', toKsts: { chapter: 7, verse: 18 }, toUnitId: '7.18', quotedText: 'ज्ञानी त्वात्मैव मे मतः ।', locator: '(७।१८)', kind: 'commentary-quotes-unit', note: 'host KSTS 13.11 (jñāna-taru-phala bhakti; printed p.286)' },
  { id: 'gita-xref-056', fromKsts: { chapter: 13, verse: 24 }, fromUnitId: '13.25', toKsts: { chapter: 6, verse: 3 }, toUnitId: '6.3', quotedText: 'योगारूढस्य तस्यैव शमः कारणमुच्यते ।', locator: '(६।३)', kind: 'commentary-quotes-unit', note: 'host KSTS 13.24 (dhyāna vs karma-yoga stages; printed p.294)' },
  { id: 'gita-xref-057', fromKsts: { chapter: 13, verse: 29 }, fromUnitId: '13.30', toKsts: { chapter: 7, verse: 6 }, toUnitId: '7.6', quotedText: 'एतद्योनीनि भूतानि सर्वाणीत्युपधारय ।', locator: '(७।६)', kind: 'commentary-quotes-unit', note: 'host KSTS 13.29 (prakṛti as sarva-jagat-citra cause; printed p.297)' },
  { id: 'gita-xref-058', fromKsts: { chapter: 13, verse: 6 }, fromUnitId: '13.7', toKsts: { chapter: 13, verse: 12 }, toUnitId: '13.13', quotedText: 'ज्ञेयं यत्तत्प्रवक्ष्यामि ।', locator: '(१३।१२)', kind: 'commentary-quotes-unit', note: 'host KSTS 13.6 close (virtue-section bridge; printed p.282; distinct print event from gita-xref-037)' },
];

/** Edges quoting one KSTS verse, keyed by target. */
export function quotationEdgesForTarget(chapter: number, verse: number): GitaReference[] {
  return GITA_QUOTATION_EDGES.filter((e) => e.toKsts.chapter === chapter && e.toKsts.verse === verse);
}
