import type { GitaReference } from './gitaDocument';

/**
 * Verified commentary quotation edges (Phase 2).
 *
 * Each edge pairs a quoted Gītā pāda with its printed locator and the
 * KSTS target verse identified from the quotation itself (never from
 * the digits alone — separators drop in extraction and a few printed
 * refs disagree with their quotes; disagreements were excluded, see the
 * architecture document). Hosts are the nearest preceding KSTS verse
 * marker; introductory/avataraṇikā matter has no host verse (null with
 * a note). Targets without a canonical unit (KSTS extras) keep null
 * toUnitId; the (2,50) quotation additionally resolves to adhika.8,
 * the unit carrying that content.
 */

export const GITA_QUOTATION_EDGES: GitaReference[] = [
  { id: 'gita-xref-001', fromKsts: null, fromUnitId: null, toKsts: { chapter: 10, verse: 39 }, toUnitId: '10.39', quotedText: 'न तदस्ति विना यत्स्यान्मया भूतं चराचरम् ।', locator: '(१००३९)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-002', fromKsts: null, fromUnitId: null, toKsts: { chapter: 11, verse: 47 }, toUnitId: null, quotedText: 'नान्योऽस्ति कर्ता जगतस्त्वमेको धाता विधाता च विभुभवश्च ।', locator: '(११।४७)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-003', fromKsts: null, fromUnitId: null, toKsts: { chapter: 15, verse: 15 }, toUnitId: '15.15', quotedText: 'सर्वस्य चाहं हृदि संनिविष्टो मत्तः स्मृतिर्ज्ञानमपोहनं च ।', locator: '(१५/१५)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-004', fromKsts: null, fromUnitId: null, toKsts: { chapter: 9, verse: 4 }, toUnitId: '9.4', quotedText: 'मत्स्थानि सर्वभूतानि"........', locator: '(९॥४)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter); quote follows the vulgate reading (सर्वं) against KSTS mūla (सेवे)' },
  { id: 'gita-xref-005', fromKsts: null, fromUnitId: null, toKsts: { chapter: 9, verse: 4 }, toUnitId: '9.4', quotedText: 'मया ततमिदं सर्वं जगदव्यक्तमूर्तिना ।', locator: '(९१४)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter); quote follows the vulgate reading (सर्वं) against KSTS mūla (सेवे)' },
  { id: 'gita-xref-006', fromKsts: null, fromUnitId: null, toKsts: { chapter: 11, verse: 48 }, toUnitId: null, quotedText: 'कर्तासि सर्वस्य यतः स्वयं वै विभो ततः सर्वमिदं त्वमेव ।', locator: '(११।४८)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-007', fromKsts: null, fromUnitId: null, toKsts: { chapter: 2, verse: 26 }, toUnitId: '2.25', quotedText: 'अव्यक्तोऽयमचिन्त्योऽयमविकार्योऽयमुच्यते  ।', locator: '(२।२६)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-008', fromKsts: null, fromUnitId: null, toKsts: { chapter: 7, verse: 10 }, toUnitId: '7.10', quotedText: 'बीजं मां सर्वभूतानां विद्धि पार्थ सनातनम् ।', locator: '(७।१०)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-009', fromKsts: null, fromUnitId: null, toKsts: { chapter: 13, verse: 31 }, toUnitId: '13.32', quotedText: 'यदा भूतपृथग्भावमेकस्थमनुपश्यति । तत एवच विस्तारं ब्रह्म संपद्यते तदा ।', locator: '(१३।३१)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-010', fromKsts: null, fromUnitId: null, toKsts: { chapter: 16, verse: 6 }, toUnitId: '16.6', quotedText: 'हौ भूतसग लोकेऽस्मिन्दैव आसुर प्रवच ।', locator: '(१६।६)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-011', fromKsts: null, fromUnitId: null, toKsts: { chapter: 9, verse: 11 }, toUnitId: '9.10', quotedText: 'मयाध्यक्षेण प्रकृतिः सूयते सचराचरम् ।', locator: '(९।११)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-012', fromKsts: null, fromUnitId: null, toKsts: { chapter: 16, verse: 18 }, toUnitId: '16.18', quotedText: '(१६१८) इत्यादि प्रद्विषन्तोऽभ्यसूयकाः ।', locator: '(१६।१८)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-013', fromKsts: null, fromUnitId: null, toKsts: { chapter: 18, verse: 55 }, toUnitId: '18.55', quotedText: 'समः सर्वेषु भूतेषु मद्भक्ति लभते पराम् । * भक्तया मामभिजानाति सोऽहं यश्चास्मि तत्त्वतः ॥', locator: '(१८५५)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-014', fromKsts: null, fromUnitId: null, toKsts: { chapter: 4, verse: 1 }, toUnitId: '4.1', quotedText: 'एवं विवखते योगं प्रोक्तवानहमव्ययम् ।', locator: '(४।१)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-015', fromKsts: null, fromUnitId: null, toKsts: { chapter: 4, verse: 3 }, toUnitId: '4.3', quotedText: 'स एवायं मया तेऽद्य योगः प्रोक्तः पुरातनः । भक्तोऽसि मे सखा चेति रहस्यं चैतदुत्तमम् ॥', locator: '(४।३)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-016', fromKsts: { chapter: 1, verse: 7 }, fromUnitId: '1.7', toKsts: { chapter: 3, verse: 31 }, toUnitId: '3.31', quotedText: 'श्रद्धावन्तोऽनसूयन्तो मुच्यन्ते सर्वकिल्विषैः ।', locator: '(३।३१)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-017', fromKsts: { chapter: 2, verse: 56 }, fromUnitId: '2.54', toKsts: { chapter: 2, verse: 50 }, toUnitId: 'adhika.8', quotedText: 'यस्य सर्वे समारम्भाः', locator: '(५०)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-018', fromKsts: { chapter: 3, verse: 9 }, fromUnitId: '3.9', toKsts: { chapter: 18, verse: 46 }, toUnitId: '18.46', quotedText: 'यतः प्रवृत्तिर्भूतानां येन सर्वमिदं ततम् । स्वकर्मणा तमेवार्थ्य सिद्धिं विन्दति मानवः ॥', locator: '(१८४६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-019', fromKsts: { chapter: 3, verse: 22 }, fromUnitId: '3.22', toKsts: { chapter: 3, verse: 17 }, toUnitId: '3.17', quotedText: 'यस्त्वात्मरतिरेव स्यात्.... ............ तस्य कार्य न विद्यते ।', locator: '(३।१७)', kind: 'commentary-quotes-unit', note: 'host KSTS 3.22 (upakramya recall with the 3.19 companion; printed p.75; Phase-12 correction: the quotation sits in the 3.22 gloss, not 3.23)' },
  { id: 'gita-xref-020', fromKsts: { chapter: 3, verse: 22 }, fromUnitId: '3.22', toKsts: { chapter: 3, verse: 19 }, toUnitId: '3.19', quotedText: 'तस्मादसक्तः सततं कार्य कर्म समाचर ।', locator: '(३।१९)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-021', fromKsts: { chapter: 3, verse: 28 }, fromUnitId: '3.28', toKsts: { chapter: 18, verse: 14 }, toUnitId: '18.14', quotedText: 'अधिष्ठानं तथा कर्ता ।', locator: '(१८१४)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-022', fromKsts: { chapter: 4, verse: 22 }, fromUnitId: '4.22', toKsts: { chapter: 3, verse: 9 }, toUnitId: '3.9', quotedText: 'यज्ञार्थात्कर्मणोऽन्यत्र लोकोऽयं कर्मबन्धनः ।', locator: '(३।९)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-023', fromKsts: { chapter: 5, verse: 2 }, fromUnitId: '5.2', toKsts: { chapter: 3, verse: 1 }, toUnitId: '3.1', quotedText: 'ज्यायसी चैत्कर्मणस्ते मता बुद्धिर्जनार्दन', locator: '(३।१)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-024', fromKsts: { chapter: 8, verse: 5 }, fromUnitId: '8.5', toKsts: { chapter: 9, verse: 25 }, toUnitId: '9.24', quotedText: 'अहं हि सर्वयज्ञानां भोक्ता च प्रभुरेवच ।', locator: '(९।२५)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-025', fromKsts: { chapter: 8, verse: 6 }, fromUnitId: '8.6', toKsts: { chapter: 7, verse: 29 }, toUnitId: '7.29', quotedText: 'ते ब्रह्म तद्विदुः कृत्नम् इत्यादिना तत्त्वत्रयमेतदुक्त्वा ।', locator: '(७२९)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-026', fromKsts: { chapter: 8, verse: 5 }, fromUnitId: '8.5', toKsts: { chapter: 7, verse: 30 }, toUnitId: '7.30', quotedText: 'साधिभूताधिदेवं मां साधियज्ञ च ते विदुः ।', locator: '(७३०)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-027', fromKsts: { chapter: 8, verse: 14 }, fromUnitId: '8.14', toKsts: { chapter: 8, verse: 6 }, toUnitId: '8.6', quotedText: 'यं यं भावं स्मरन्वापि ...', locator: '(८६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-028', fromKsts: { chapter: 8, verse: 17 }, fromUnitId: '8.17', toKsts: { chapter: 8, verse: 16 }, toUnitId: '8.16', quotedText: 'आ ब्रह्मभुवनालोकाः पुनरावर्तिनः', locator: '(८।१६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-029', fromKsts: { chapter: 8, verse: 25 }, fromUnitId: '8.25', toKsts: { chapter: 8, verse: 27 }, toUnitId: '8.27', quotedText: 'नैते सृती पार्थ जानन् योगी मुह्यति कश्चन ।', locator: '(८।२७)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-030', fromKsts: { chapter: 9, verse: 10 }, fromUnitId: '9.9', toKsts: { chapter: 4, verse: 13 }, toUnitId: '4.13', quotedText: 'तस्य कर्तारमपि मां विद्धयकर्तारमव्ययम् ।', locator: '(४।१३)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-031', fromKsts: { chapter: 9, verse: 10 }, fromUnitId: '9.9', toKsts: { chapter: 4, verse: 14 }, toUnitId: '4.14', quotedText: 'न मां कर्माणि लिम्पन्ति न मे कामः फलेष्वपि ।', locator: '(४।१४)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-032', fromKsts: { chapter: 9, verse: 13 }, fromUnitId: '9.12', toKsts: { chapter: 18, verse: 28 }, toUnitId: '18.28', quotedText: 'अयुक्तः प्राकृतः स्तब्धः शठो नैकृतिकोऽलसः विषादी दीर्घसूत्रश्च कर्ता तामस उच्यते ॥', locator: '(१८/२८)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-033', fromKsts: { chapter: 9, verse: 13 }, fromUnitId: '9.12', toKsts: { chapter: 18, verse: 22 }, toUnitId: '18.22', quotedText: 'यत्त्वक विदेकस्मिन् कार्ये सक्तमतुकम् । अतत्त्वार्थवदल्पं च तत्तामसमुदाहृतम् ।', locator: '(१८।२२)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-034', fromKsts: { chapter: 9, verse: 13 }, fromUnitId: '9.12', toKsts: { chapter: 18, verse: 27 }, toUnitId: '18.27', quotedText: 'रागी कर्मफलप्रेप्सुर्लुब्धो हिंसात्मकोऽशुचिः I हर्षशोकान्वितः कर्ता राजसः परिकी ते ।', locator: '(१८।२७)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-035', fromKsts: { chapter: 10, verse: 5 }, fromUnitId: '10.5', toKsts: { chapter: 6, verse: 9 }, toUnitId: '6.9', quotedText: 'सुहृन्मित्रा दासीन', locator: '(६।९)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-036', fromKsts: { chapter: 11, verse: 19 }, fromUnitId: '11.19', toKsts: { chapter: 17, verse: 23 }, toUnitId: '17.23', quotedText: 'सावतधर्मगोप्ता त्वम् । सदिति ब्रह्मनाम यद्वक्ष्यति तत्स दिति निर्देशो ब्रह्मणस्त्रिविधः स्मृतः ।', locator: '(१७२३)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-037', fromKsts: { chapter: 13, verse: 11 }, fromUnitId: '13.12', toKsts: { chapter: 13, verse: 12 }, toUnitId: '13.13', quotedText: 'ज्ञेयं यत्तत्प्रवक्ष्यामि ।', locator: '(१३।१२)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-038', fromKsts: { chapter: 13, verse: 6 }, fromUnitId: '13.7', toKsts: { chapter: 13, verse: 2 }, toUnitId: '13.3', quotedText: 'क्षेत्रज्ञ चापि मां विद्धि ।', locator: '(१३।२)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-039', fromKsts: { chapter: 13, verse: 29 }, fromUnitId: '13.30', toKsts: { chapter: 13, verse: 26 }, toUnitId: '13.27', quotedText: 'यावत् संभवति किञ्चित्।', locator: '(१३।२६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-040', fromKsts: null, fromUnitId: null, toKsts: { chapter: 13, verse: 12 }, toUnitId: '13.13', quotedText: 'अनादिमत्परं ब्रह्म......... ।', locator: '(१३।१२)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-041', fromKsts: null, fromUnitId: null, toKsts: { chapter: 13, verse: 34 }, toUnitId: '13.35', quotedText: 'भूतप्रकृतिमोक्षं च ये विदुः .. ।', locator: '(१३।३४)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-042', fromKsts: null, fromUnitId: null, toKsts: { chapter: 13, verse: 31 }, toUnitId: '13.32', quotedText: 'अनादित्वान्निर्गुणत्वात्परमात्मायमव्ययः । शरीरस्थोऽपि कौन्तेय न करोति न लिप्यते ॥', locator: '(१३३१)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (introductory or boundary matter)' },
  { id: 'gita-xref-043', fromKsts: { chapter: 14, verse: 2 }, fromUnitId: '14.2', toKsts: { chapter: 3, verse: 25 }, toUnitId: '3.25', quotedText: 'सक्ताः कर्मण्यविद्वांसो यथा कुर्वन्ति भारत । कुर्याद्विद्वांस्तथासक्तश्चिकीर्षुर्लोकसंग्रहम् ॥', locator: '(३।२५)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-044', fromKsts: { chapter: 15, verse: 1 }, fromUnitId: '15.1', toKsts: { chapter: 8, verse: 16 }, toUnitId: '8.16', quotedText: 'आ ब्रह्म भुवनाल्लोकाः पुनरावर्तिनोऽर्जुन ।', locator: '(८।१६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-045', fromKsts: { chapter: 18, verse: 2 }, fromUnitId: '18.2', toKsts: { chapter: 2, verse: 50 }, toUnitId: 'adhika.8', quotedText: 'यस्य सर्वे समारम्भाः"', locator: '(२५०)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-046', fromKsts: { chapter: 18, verse: 6 }, fromUnitId: '18.6', toKsts: { chapter: 3, verse: 16 }, toUnitId: '3.16', quotedText: 'अघायुरिन्द्रियारामो  मोघं पार्थ स जीवति ।', locator: '(३।१६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-047', fromKsts: { chapter: 18, verse: 7 }, fromUnitId: '18.7', toKsts: { chapter: 14, verse: 17 }, toUnitId: '14.17', quotedText: 'प्रमादमोहो जायेते तमसोऽज्ञानमेवच ।', locator: '(१४।१७)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-048', fromKsts: { chapter: 18, verse: 7 }, fromUnitId: '18.7', toKsts: { chapter: 18, verse: 11 }, toUnitId: '18.11', quotedText: 'नहि देह ता शक्यं व्यक्तुं कर्माण्यशेषतः ।', locator: '(१८।११)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-049', fromKsts: { chapter: 18, verse: 7 }, fromUnitId: '18.7', toKsts: { chapter: 3, verse: 5 }, toUnitId: '3.5', quotedText: 'नहि कश्चित्क्षणमपि जातु तिष्ठत्यकर्मकृत् ।', locator: '(३५)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-050', fromKsts: { chapter: 18, verse: 30 }, fromUnitId: '18.30', toKsts: { chapter: 18, verse: 20 }, toUnitId: '18.20', quotedText: 'सर्वभूतेषु येनैकम्', locator: '(१८२०)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-051', fromKsts: { chapter: 18, verse: 41 }, fromUnitId: '18.41', toKsts: { chapter: 4, verse: 13 }, toUnitId: '4.13', quotedText: 'चातुर्वर्ण्य मया सृष्टं गुणकर्मविभागशः । तस्य कतीरमपि मां विद्ध्यकर्तारमव्ययम् ॥', locator: '(४।१३)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-052', fromKsts: { chapter: 18, verse: 47 }, fromUnitId: '18.47', toKsts: { chapter: 16, verse: 1 }, toUnitId: '16.1', quotedText: 'अभयं सत्त्वसंशुद्धि नियोगव्यवस्थितिः ।', locator: '(१६।१)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-053', fromKsts: { chapter: 18, verse: 67 }, fromUnitId: '18.67', toKsts: { chapter: 18, verse: 46 }, toUnitId: '18.46', quotedText: 'यतः प्रवृत्तिर्भूतानाम् ।', locator: '(१८४६)', kind: 'commentary-quotes-unit' },
  { id: 'gita-xref-054', fromKsts: null, fromUnitId: null, toKsts: { chapter: 7, verse: 6 }, toUnitId: '7.6', quotedText: 'अहं कृत्नस्य जगतः प्रभवः प्रलयस्तथा ।', locator: '(७।६)', kind: 'commentary-quotes-unit', note: 'host verse indeterminate from print order (chapter-13 avatāraṇikā, printed p.276)' },
  { id: 'gita-xref-055', fromKsts: { chapter: 13, verse: 11 }, fromUnitId: '13.12', toKsts: { chapter: 7, verse: 18 }, toUnitId: '7.18', quotedText: 'ज्ञानी त्वात्मैव मे मतः ।', locator: '(७।१८)', kind: 'commentary-quotes-unit', note: 'host KSTS 13.11 (jñāna-taru-phala bhakti; printed p.286)' },
  { id: 'gita-xref-056', fromKsts: { chapter: 13, verse: 24 }, fromUnitId: '13.25', toKsts: { chapter: 6, verse: 3 }, toUnitId: '6.3', quotedText: 'योगारूढस्य तस्यैव शमः कारणमुच्यते ।', locator: '(६।३)', kind: 'commentary-quotes-unit', note: 'host KSTS 13.24 (dhyāna vs karma-yoga stages; printed p.294)' },
  { id: 'gita-xref-057', fromKsts: { chapter: 13, verse: 29 }, fromUnitId: '13.30', toKsts: { chapter: 7, verse: 6 }, toUnitId: '7.6', quotedText: 'एतद्योनीनि भूतानि सर्वाणीत्युपधारय ।', locator: '(७।६)', kind: 'commentary-quotes-unit', note: 'host KSTS 13.29 (prakṛti as sarva-jagat-citra cause; printed p.297)' },
  { id: 'gita-xref-058', fromKsts: { chapter: 13, verse: 6 }, fromUnitId: '13.7', toKsts: { chapter: 13, verse: 12 }, toUnitId: '13.13', quotedText: 'ज्ञेयं यत्तत्प्रवक्ष्यामि ।', locator: '(१३।१२)', kind: 'commentary-quotes-unit', note: 'host KSTS 13.6 close (virtue-section bridge; printed p.282; distinct print event from gita-xref-037)' },
  // Chapter-1 upodghāta quotation edges (Phase 10). The grantha-mukha
  // (printed pp.2–11) quotes Gītā verses with explicit print locators;
  // each edge pairs the verbatim quoted text with its locator and the
  // KSTS target identified from the quotation itself. Hosts stay null:
  // upodghāta matter precedes every verse marker. Disagreeing and
  // ambiguous locators ((३।२१) for 3.22 text, (९।२२) for 9.20–21 text,
  // (१३।२०) for 12.20 text, (२१४५), (१६।३) for a three-verse quote)
  // are excluded by policy and inventoried as unresolved instead.
  { id: 'gita-xref-059', fromKsts: null, fromUnitId: null, toKsts: { chapter: 6, verse: 31 }, toUnitId: '6.31', quotedText: 'यो मां पश्यति सर्वत्र सर्वं च मयि पश्यति । तस्याहं न प्रणश्यामि स च मे न प्रणश्यति ॥', locator: '(६।३१)', kind: 'commentary-quotes-unit', note: 'Chapter-1 upodghāta (sarvātman gloss; printed p.3)' },
  { id: 'gita-xref-060', fromKsts: null, fromUnitId: null, toKsts: { chapter: 6, verse: 30 }, toUnitId: '6.30', quotedText: 'सर्वभूतस्थमात्मानं सर्वभूतानि चात्मनि । ईक्षते योगयुक्तात्मा सर्वत्र समदर्शनः ॥', locator: '(६।३०)', kind: 'commentary-quotes-unit', note: 'Chapter-1 upodghāta (sarvātman gloss; printed p.3)' },
  { id: 'gita-xref-061', fromKsts: null, fromUnitId: null, toKsts: { chapter: 4, verse: 14 }, toUnitId: '4.14', quotedText: 'न मां कर्माणि लिम्पन्ति न मे कामः फलेष्वपि । इति मां योऽभिजानाति कर्मभिर्न स बध्यते ॥', locator: '(४।१४)', kind: 'commentary-quotes-unit', note: 'Chapter-1 upodghāta (prayojana-vicāra close; printed p.6; distinct print event from gita-xref-031)' },
  { id: 'gita-xref-062', fromKsts: null, fromUnitId: null, toKsts: { chapter: 7, verse: 6 }, toUnitId: '7.6', quotedText: 'अहं कृत्स्नस्य जगतः प्रभवः प्रलयस्तथा ।', locator: '(७१६)', kind: 'commentary-quotes-unit', note: 'Chapter-1 upodghāta (jagat-prakriyā; printed p.7; separator dropped in extraction; distinct print event from gita-xref-054)' },
  { id: 'gita-xref-063', fromKsts: null, fromUnitId: null, toKsts: { chapter: 14, verse: 4 }, toUnitId: '14.4', quotedText: 'अहं बीजप्रदः पिता ।', locator: '(१४१४)', kind: 'commentary-quotes-unit', note: 'Chapter-1 upodghāta (single pāda quotation; printed p.7; separator dropped in extraction)' },
  { id: 'gita-xref-064', fromKsts: null, fromUnitId: null, toKsts: { chapter: 7, verse: 16 }, toUnitId: '7.16', quotedText: 'चतुर्विधा भजन्ते मां जनाः सुकृतिनः सदा ।', locator: '(७११६)', kind: 'commentary-quotes-unit', note: 'Chapter-1 upodghāta (upadeśya-parigraha; printed p.10; separator dropped in extraction)' },
  { id: 'gita-xref-065', fromKsts: null, fromUnitId: null, toKsts: { chapter: 18, verse: 50 }, toUnitId: '18.50', quotedText: 'सिद्धि प्राप्तो यदा ब्रह्म समासेन निबोध मे । समासेन तु कौन्तेय निष्ठा ज्ञानस्य या परा ॥', locator: '(१८१५०)', kind: 'commentary-quotes-unit', note: 'Chapter-1 upodghāta (prakaraṇa-parisamāpti; printed p.10; separator dropped in extraction; retained verbatim with extraction noise: यदा, समासेन निबोध)' },
  { id: 'gita-xref-066', fromKsts: null, fromUnitId: null, toKsts: { chapter: 4, verse: 39 }, toUnitId: '4.39', quotedText: 'श्रद्धावाल्लभते ज्ञानं संयतस्तत्परेन्द्रियः । ज्ञानं लब्ध्वा परां शान्तिमचिरेणाधिगच्छति ॥', locator: '(४।३९)', kind: 'commentary-quotes-unit', note: 'Chapter-1 upodghāta tail (śraddhā-viṣaya; printed p.11; retained verbatim: श्रद्धावाल्लभते, संयतस्तत्परेन्द्रियः; running-head fragment ११ between the halves excluded)' },
  { id: 'gita-xref-067', fromKsts: null, fromUnitId: null, toKsts: { chapter: 16, verse: 20 }, toUnitId: '16.20', quotedText: 'आसुरी योनिमापन्ना मूढा जन्मनि जन्मनि । मामप्राप्यैव कौन्तेय ततो यान्त्यधमां गतिम् ॥', locator: '(१६।२०)', kind: 'commentary-quotes-unit', note: 'Chapter-1 upodghāta (āsura-sarga; printed p.8; retained verbatim: आसुरी योनिम् for आसुरीं योनिम्)' },
  // Chapter-2 quotation edges (Phase 11). Each edge pairs the verbatim
  // quoted text with its print locator and the KSTS target identified
  // from the quotation itself. Hosts are the KSTS gloss regions carrying
  // the quotation; KSTS-extra targets (2.11) keep null toUnitId.
  { id: 'gita-xref-068', fromKsts: { chapter: 2, verse: 27 }, fromUnitId: '2.26', toKsts: { chapter: 2, verse: 11 }, toUnitId: null, quotedText: 'त्वं मानुष्येण', locator: '(२।११)', kind: 'commentary-quotes-unit', note: 'host KSTS 2.27 (sūtra-recall bridge; printed p.32); target is the KSTS extra verse' },
  { id: 'gita-xref-069', fromKsts: { chapter: 2, verse: 41 }, fromUnitId: '2.40', toKsts: { chapter: 2, verse: 74 }, toUnitId: '2.72', quotedText: 'स्थित्वास्यामन्तकालेऽपि ब्रह्म निर्वाणमृच्छति ।', locator: '(२०७४)', kind: 'commentary-quotes-unit', note: 'host KSTS 2.41 (jñāna-phala close; printed p.39; separator dropped in extraction)' },
  { id: 'gita-xref-070', fromKsts: { chapter: 2, verse: 57 }, fromUnitId: '2.55', toKsts: { chapter: 7, verse: 3 }, toUnitId: '7.3', quotedText: 'मनुष्याणां सहस्रेषु कश्चिद्यतति सिद्धये । यततामपि सिद्धानां कश्चिन्मां वेत्ति तत्त्वतः ॥', locator: '(७१३)', kind: 'commentary-quotes-unit', note: 'host KSTS 2.57 (adhikāra exposition; printed p.51; 7.3ab quoted with इति, तथा before the locatored 7.3cd; separator dropped in extraction)' },
  { id: 'gita-xref-071', fromKsts: { chapter: 2, verse: 57 }, fromUnitId: '2.55', toKsts: { chapter: 7, verse: 19 }, toUnitId: '7.19', quotedText: 'बहूनां जन्मनामन्ते ज्ञानवान्मां प्रपद्यते ।', locator: '(७।१९)', kind: 'commentary-quotes-unit', note: 'host KSTS 2.57 (adhikāra exposition; printed p.51; single half-verse quotation)' },
  // Chapter-3 quotation edges (Phase 12). Hosts are the KSTS gloss
  // regions carrying the quotation (joint regions host on the first
  // unit); targets identified from the quotation itself, never from
  // digits alone.
  { id: 'gita-xref-072', fromKsts: { chapter: 3, verse: 1 }, fromUnitId: '3.1', toKsts: { chapter: 2, verse: 51 }, toUnitId: '2.49', quotedText: 'दूरेण ह्यवरं कर्म बुद्धियोगात् .....', locator: '(२५१)', kind: 'commentary-quotes-unit', note: 'host KSTS 3.1–2 joint dilemma gloss (printed p.61; ellipsis and fused locator retained verbatim)' },
  { id: 'gita-xref-073', fromKsts: { chapter: 3, verse: 1 }, fromUnitId: '3.1', toKsts: { chapter: 2, verse: 48 }, toUnitId: '2.47', quotedText: 'कर्मण्यस्त्वधिकारस्ते', locator: '(२।४८)', kind: 'commentary-quotes-unit', note: 'host KSTS 3.1–2 joint dilemma gloss (printed p.61; partial pāda; trailing extraction space dropped, recorded here)' },
  { id: 'gita-xref-074', fromKsts: { chapter: 3, verse: 3 }, fromUnitId: '3.3', toKsts: { chapter: 2, verse: 51 }, toUnitId: '2.49', quotedText: 'दूरेण ह्यावरं कर्म', locator: '(२०५१)', kind: 'commentary-quotes-unit', note: 'host KSTS 3.3 samuccaya-nirvacana (printed p.63; ह्यावरं retained; trailing extraction space dropped, recorded here; distinct print event from gita-xref-072)' },
  { id: 'gita-xref-075', fromKsts: { chapter: 3, verse: 3 }, fromUnitId: '3.3', toKsts: { chapter: 2, verse: 66 }, toUnitId: '2.64', quotedText: 'रागद्वेषविमुक्तस्तु विषयानिन्द्रियैश्चरन् । आत्मवश्यैर्विधेयात्मा प्रसादमधिगच्छति ॥', locator: '(२।६६)', kind: 'commentary-quotes-unit', note: 'host KSTS 3.3 samuccaya-nirvacana (printed p.63)' },
  { id: 'gita-xref-076', fromKsts: { chapter: 3, verse: 7 }, fromUnitId: '3.7', toKsts: { chapter: 2, verse: 66 }, toUnitId: '2.64', quotedText: 'रागद्वेषविमुक्तस्तु विषयानिन्द्रियैश्चरन् ।', locator: '(२।६६)', kind: 'commentary-quotes-unit', note: 'host KSTS 3.7 viśeṣa bridge (printed p.66; distinct print event from gita-xref-075)' },
  { id: 'gita-xref-077', fromKsts: { chapter: 3, verse: 9 }, fromUnitId: '3.9', toKsts: { chapter: 18, verse: 46 }, toUnitId: '18.46', quotedText: 'यतः प्रवृत्तिर्भूतानां येन सर्वमिदं ततम् । स्वकर्मणा तमेवार्थ्य सिद्धिं विन्दति मानवः ॥', locator: '(१८४६)', kind: 'commentary-quotes-unit', note: 'host KSTS 3.9 yajña gloss (tathā-ca-vakṣyati; printed p.68; fused locator retained; distinct print event from gita-xref-053)' },
  // Chapter-4 quotation edges (Phase 13). Hosts are the KSTS gloss
  // regions carrying the quotation; targets identified from the
  // quotation itself, never from digits alone.
  { id: 'gita-xref-078', fromKsts: { chapter: 4, verse: 24 }, fromUnitId: '4.24', toKsts: { chapter: 4, verse: 23 }, toUnitId: '4.23', quotedText: 'गतसंगस्य मुक्तस्य ज्ञानावस्थितचेतसः । यज्ञायारभतः कर्म समग्रं प्रविलीयते ॥', locator: '(४।२३)', kind: 'commentary-quotes-unit', note: 'host KSTS 4.24 brahmārpaṇa close (self-recall; printed p.104)' },
  { id: 'gita-xref-079', fromKsts: { chapter: 4, verse: 24 }, fromUnitId: '4.24', toKsts: { chapter: 5, verse: 8 }, toUnitId: '5.8', quotedText: 'पश्य शृण्वन्स्पृशञ्जिघन्।', locator: '(५।८)', kind: 'commentary-quotes-unit', note: 'host KSTS 4.24 brahmārpaṇa close (printed p.104; partial pāda; स्पृशञ्जिघन् for स्पृशञ्जिघ्रन् retained)' },
  { id: 'gita-xref-080', fromKsts: { chapter: 4, verse: 28 }, fromUnitId: '4.28', toKsts: { chapter: 9, verse: 33 }, toUnitId: '9.32', quotedText: 'मां हि पार्थ व्यपाश्रित्य येऽपि स्युः पापयोनयः । स्त्रियो वैश्यास्तथा शूद्रास्तेऽपि यांति परां गतिम् ॥', locator: '(९३३)', kind: 'commentary-quotes-unit', note: 'host KSTS 4.28–30 exposition (jñāna-yajña adhikāra; printed p.108; KSTS-numbered locator for the repo-9.32 verse; यांति retained)' },
];

/** Edges quoting one KSTS verse, keyed by target. */
export function quotationEdgesForTarget(chapter: number, verse: number): GitaReference[] {
  return GITA_QUOTATION_EDGES.filter((e) => e.toKsts.chapter === chapter && e.toKsts.verse === verse);
}
