/**
 * Bhagavad Gītā joint commentary spans (Phase 2).
 *
 * The edition sometimes expounds several verses under one commentary
 * span instead of glossing each separately. These spans keep every
 * canonical verse individually addressable while recording the shared
 * exposition. Only spans stated in print (`निगद`-style markers
 * such as `निगदव्याख्यातौ श्लोकौ`, or an explicit joint gloss) are
 * listed; suspected spans stay out until verified.
 */

export interface GitaCommentarySpan {
  id: string;
  /** Canonical units covered, in order. */
  unitIds: string[];
  /** How the span is evidenced in print. */
  basis: string;
}

export const GITA_COMMENTARY_SPANS: GitaCommentarySpan[] = [
  {
    id: 'gita-span-18.74-75',
    unitIds: ['18.74', '18.75'],
    basis: 'KSTS 18.74–75 glossed jointly (लोकः स्पष्टार्थः on the pair; printed p.403)',
  },
  {
    id: 'gita-span-18.76-77',
    unitIds: ['18.76', '18.77'],
    basis: 'निगदव्याख्यातौ श्लोकौ on KSTS 18.76–77 (printed p.404)',
  },
];

/** Span covering a unit, when the unit shares its exposition. */
export function commentarySpanForUnit(unitId: string): GitaCommentarySpan | undefined {
  return GITA_COMMENTARY_SPANS.find((s) => s.unitIds.includes(unitId));
}

/**
 * Sub-unit passage spans (Phase 4). Where print gives an explicit
 * boundary — a `nanu` between verse markers, an avataraṇikā before the
 * first verse, a gloss on an unnumbered half — the region is named so
 * thread steps and concept occurrences can cite exact passages without
 * inventing sentence boundaries. No span is drawn inside undifferentiated
 * commentary prose.
 */
export const PASSAGE_SPAN_ROLES = [
  'gloss',
  'objection',
  'response',
  'question',
  'quotation',
  'cross-reference',
  'inference',
  'conclusion',
] as const;

export type PassageSpanRole = (typeof PASSAGE_SPAN_ROLES)[number];

export type PassageSpanAnchor = 'avataraṇikā' | 'commentary-tail' | 'commentary' | 'closing';

export interface GitaPassageSpan {
  id: string;
  /** Canonical units the passage belongs to (often one). */
  unitIds: string[];
  /** KSTS refs, fully qualified; empty for unnumbered opening matter. */
  ksts: string[];
  pdf?: number;
  folio?: number;
  anchor: PassageSpanAnchor;
  role?: PassageSpanRole;
  /**
   * Source vs editorial accounting. `source` = print-demarcated region
   * (nanu, avataraṇikā, verse-adjacent gloss bounded by markers);
   * `editorial` = Darśana grouping, explicitly marked; `unresolved` =
   * insufficient evidence for a stronger claim. Required on every span.
   */
  status: 'source' | 'editorial' | 'unresolved';
  /**
   * Reserved for future verified transcription. ABSENT throughout Phase
   * 5 by design: no Sanskrit has been imported, and tests enforce the
   * absence so commentary text can never be fabricated here.
   */
  transcription?: string;
  note?: string;
}

export const GITA_PASSAGE_SPANS: GitaPassageSpan[] = [
  {
    id: 'gita-ps-13-avat',
    unitIds: ['13.2'],
    ksts: [],
    pdf: 286,
    folio: 276,
    anchor: 'avataraṇikā',
    status: 'source',
    note: 'Chapter-13 gateway: jñāna-nirṇaya purpose for the śarīra-śarīri exposition (printed p.276).',
  },
  {
    id: 'gita-ps-13.2-nanu',
    unitIds: ['13.2', '13.3'],
    ksts: ['13.1', '13.2'],
    pdf: 287,
    folio: 277,
    anchor: 'commentary-tail',
    role: 'objection',
    status: 'source',
    note: 'ननु passage between KSTS 13.1 close and 13.2: one pramātṛ vs many knowers (printed pp.287–288).',
  },
  {
    id: 'gita-ps-3-avat',
    unitIds: ['3.1'],
    ksts: [],
    pdf: 71,
    folio: 61,
    anchor: 'avataraṇikā',
    status: 'source',
    note: 'Chapter-3 gateway: Arjuna asks from non-ascertainment of the samuccaya object.',
  },
  {
    id: 'gita-ps-4-avat',
    unitIds: ['4.1'],
    ksts: [],
    pdf: 102,
    folio: 92,
    anchor: 'avataraṇikā',
    status: 'source',
    note: 'Chapter-4 gateway: samuccaya as abhidheya, paramātma-samāpatti as prayojana.',
  },
  {
    id: 'gita-ps-7-avat',
    unitIds: ['7.1'],
    ksts: [],
    pdf: 168,
    folio: 158,
    anchor: 'avataraṇikā',
    status: 'source',
    note: 'Chapter-7 gateway: the unsurpassed yoga of samuccaya form.',
  },
  {
    id: 'gita-ps-18.61-maya',
    unitIds: ['18.61'],
    ksts: ['18.61'],
    pdf: 406,
    folio: 396,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Gloss on the unnumbered भ्रामयन् half: all stirrings done through māyā-śakti-avabhāsa.',
  },
  {
    id: 'gita-seg-13.1-glosa',
    unitIds: ['13.2'],
    ksts: ['13.1'],
    pdf: 287,
    folio: 277,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Śarīra pratīka gloss region of KSTS 13.1 (bounded by the verse marker and the nanu).',
  },
  {
    id: 'gita-seg-13.2-verse',
    unitIds: ['13.3'],
    ksts: ['13.2'],
    pdf: 288,
    folio: 278,
    anchor: 'commentary',
    status: 'source',
    note: 'Verse introduction (parihartum + āha) with KSTS 13.2 itself.',
  },
  {
    id: 'gita-seg-13.2-resolution',
    unitIds: ['13.3'],
    ksts: ['13.2'],
    pdf: 288,
    folio: 278,
    anchor: 'commentary',
    status: 'source',
    note: 'Vedakaika distinction and māyāśakti ground (shared by distinction and conclusion claims; retained whole — no inner boundary in print).',
  },
  {
    id: 'gita-seg-2.39-tail',
    unitIds: ['2.38'],
    ksts: ['2.39'],
    pdf: 48,
    folio: 38,
    anchor: 'commentary-tail',
    status: 'source',
    note: 'Closing sentence ascertaining jñāna-kriyā-samuccaya as the teachable.',
  },
  {
    id: 'gita-seg-7.14-q2',
    unitIds: ['7.14'],
    ksts: ['7.14'],
    pdf: 176,
    folio: 166,
    anchor: 'commentary',
    role: 'objection',
    status: 'source',
    note: 'Second nanu (vain-teaching objection) within the 7.14 gloss.',
  },
  {
    id: 'gita-seg-7.14-response',
    unitIds: ['7.14'],
    ksts: ['7.14'],
    pdf: 176,
    folio: 166,
    anchor: 'commentary',
    role: 'response',
    status: 'source',
    note: 'atrāha prapatti resolution following the second nanu.',
  },
  {
    id: 'gita-seg-13.3-gloss',
    unitIds: ['13.4'],
    ksts: ['13.3'],
    pdf: 289,
    folio: 279,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Vikāri gloss region of KSTS 13.3 (bounded by the verse markers; vikāra/vikāri distinction).',
  },
  {
    id: 'gita-seg-13.5-gloss',
    unitIds: ['13.6'],
    ksts: ['13.5'],
    pdf: 290,
    folio: 280,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Kṣetra-saṅgraha gloss of KSTS 13.5 (mahābhūtādi-samudaya as savikāra kṣetra; bounded by verse markers).',
  },
  {
    id: 'gita-seg-13.6-iccha',
    unitIds: ['13.7'],
    ksts: ['13.6'],
    pdf: 291,
    folio: 281,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Icchā-ādi gloss tail of KSTS 13.6 (icchā-dveṣa as vedyatvāt kṣetra; saṅghāta/cetanā/dhṛti definitions; runs to printed p.281).',
  },
  {
    id: 'gita-seg-13.11-ajnana',
    unitIds: ['13.12'],
    ksts: ['13.11'],
    pdf: 296,
    folio: 286,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Ajñāna close of the jñāna-virtue exposition (anyathā/mānitva as jñāna-viparīta; KSTS 13.11 tail on printed p.286).',
  },
  {
    id: 'gita-seg-13.12-jneya-resp',
    unitIds: ['13.13'],
    ksts: ['13.12'],
    pdf: 297,
    folio: 287,
    anchor: 'commentary',
    role: 'response',
    status: 'source',
    note: 'Satyam response on jneya-upacāra (ārurukṣā stage division; vastava jneya denied; bounded by the nanu and the anādi verse).',
  },
  {
    id: 'gita-seg-13.12-anadi',
    unitIds: ['13.13'],
    ksts: ['13.12'],
    pdf: 298,
    folio: 288,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Anādimat gloss of KSTS 13.12 (kāraṇāntara-nirapekṣa being vs ādimat vedya; bounded by verse markers).',
  },
  {
    id: 'gita-seg-13.19-prakrti',
    unitIds: ['13.20'],
    ksts: ['13.19'],
    pdf: 301,
    folio: 291,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Prakṛti-puruṣa anāditva gloss of KSTS 13.19 (saptama vs śarīra-bhāva exposition recalled; bounded by verse markers).',
  },
  {
    id: 'gita-seg-13.20-karya',
    unitIds: ['13.21'],
    ksts: ['13.20'],
    pdf: 301,
    folio: 291,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Kārya-kāraṇa gloss of KSTS 13.20 (mahābhūtādi + bāhyābhyantara indriyas as śarīrādi-samūha; bounded by verse markers).',
  },
  {
    id: 'gita-seg-13.22-mahesvara',
    unitIds: ['13.23'],
    ksts: ['13.22'],
    pdf: 303,
    folio: 293,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Maheśvara gloss of KSTS 13.22 (upadraṣṭā/bhartā/anumantā/bhoktā as svamāyodbhāvita vyapadeśa; tail on printed p.293).',
  },
  {
    id: 'gita-seg-13.34-synthesis',
    unitIds: ['13.35'],
    ksts: ['13.34'],
    pdf: 311,
    folio: 301,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Kṣetra-kṣetrajña antara gloss of KSTS 13.34 (aparā/parā prakṛti distinction as viduḥ object; bounded by the closing verse).',
  },
  {
    id: 'gita-seg-13.34-closing',
    unitIds: ['13.35'],
    ksts: ['13.34'],
    pdf: 312,
    folio: 302,
    anchor: 'closing',
    status: 'source',
    note: 'Chapter-13 closing apparatus: authorial praśasti verse + fixed colophon (printed p.302; transcription deferred — locator-only).',
  },
  // Phase-8 Chapter-13 corpus completion spans (61 bounded regions in
  // sequential source order). Every boundary follows print markers
  // (pratīka openings, nanu/atrāha/ucyate/satyam shifts, verse markers,
  // tātparya/nirṇīta closes, chapter transitions); unmarked prose stays
  // unmarked (no role). All status `source`; transcription lives only in
  // gitaCommentaryText.ts passages.
  {
    id: 'gita-seg-13.1-etat',
    unitIds: ['13.2'],
    ksts: ['13.1'],
    pdf: 287,
    folio: 277,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Etat-gloss region of KSTS 13.1 (bounded by the etat pratīka and the etāv exhibit close; excludes the śarīra gloss before and the nityāvahitatva turn after).',
  },
  {
    id: 'gita-seg-13.1-tatparya',
    unitIds: ['13.2'],
    ksts: ['13.1'],
    pdf: 287,
    folio: 277,
    anchor: 'commentary-tail',
    status: 'source',
    note: 'Nityāvahitatva turn through the tātparya close of KSTS 13.1 (bounded by etāv exhibit and iti tātparyam; runs to printed p.278).',
  },
  {
    id: 'gita-seg-13.2-sarvaksetra',
    unitIds: ['13.3'],
    ksts: ['13.2'],
    pdf: 288,
    folio: 278,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Sarvakṣetra gloss of KSTS 13.2 (bounded by the sarvakṣetreṣu pratīka and the verse close; follows the vedaka resolution without an inner print boundary).',
  },
  {
    id: 'gita-seg-13.3-intro',
    unitIds: ['13.4'],
    ksts: ['13.3'],
    pdf: 288,
    folio: 278,
    anchor: 'commentary',
    status: 'source',
    note: 'Sāṅkhya-prakriyā introduction to KSTS 13.3–13.4 (bounded by idānīṃ and the verse marker; runs to printed p.279; mūla excluded).',
  },
  {
    id: 'gita-seg-13.3-tat',
    unitIds: ['13.4'],
    ksts: ['13.3'],
    pdf: 289,
    folio: 279,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Tat/yādṛk/yataśca/sa-ca exposition of KSTS 13.3 (bounded by the tat pratīka and the saṅgraha turn; excludes the ṛṣibhiḥ verse gloss after).',
  },
  {
    id: 'gita-seg-13.4-rsibhi',
    unitIds: ['13.5'],
    ksts: ['13.4'],
    pdf: 289,
    folio: 279,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Smṛti-śruti-prasiddhatva gloss of KSTS 13.4 (bounded by the asya-vastunaḥ turn and the joint-verse close; ṛṣibhiḥ/chandobhiḥ/brahmasūtra pratīkas).',
  },
  {
    id: 'gita-seg-13.4-upasamhara',
    unitIds: ['13.5', '13.6'],
    ksts: ['13.4', '13.5'],
    pdf: 289,
    folio: 279,
    anchor: 'commentary',
    status: 'source',
    note: 'Prasiddhatva bridge from KSTS 13.4 close to the KSTS 13.5 exposition (bounded by evaṃ and the verse marker; cites the kṣetra/kṣetrajña recall).',
  },
  {
    id: 'gita-seg-13.5-tattva',
    unitIds: ['13.6'],
    ksts: ['13.5'],
    pdf: 290,
    folio: 280,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Tattva-catuṣṭaya definitions of KSTS 13.5 (bounded by tatra and the etāni summary; mahābhūta/ahaṅkāra/buddhi/avyakta).',
  },
  {
    id: 'gita-seg-13.5-karana',
    unitIds: ['13.6'],
    ksts: ['13.5'],
    pdf: 290,
    folio: 280,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Kāraṇa analysis of KSTS 13.5 (bounded by tāni-ca and the nirṇītaḥ close; ahaṅkāra trividha and the ke-cit positions).',
  },
  {
    id: 'gita-seg-13.5-karya',
    unitIds: ['13.6'],
    ksts: ['13.5'],
    pdf: 290,
    folio: 280,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Kārya-varga and sāṅkhya-saṅgraha close of KSTS 13.5 (bounded by atha and the kṣetram-iti-uktā close; runs to printed p.281; ṣoḍaśaka kārya, not kāraṇa).',
  },
  {
    id: 'gita-seg-13.6-darsanantara',
    unitIds: ['13.7'],
    ksts: ['13.6'],
    pdf: 291,
    folio: 281,
    anchor: 'commentary',
    status: 'source',
    note: 'Darśanāntara-saṅgraha transition to the KSTS 13.6 tail (bounded by idānīṃ-tu and icchetyādi; prameyatva as the kṣetratva ground).',
  },
  {
    id: 'gita-seg-13.6-upasamhara',
    unitIds: ['13.7'],
    ksts: ['13.6'],
    pdf: 291,
    folio: 281,
    anchor: 'commentary',
    status: 'source',
    note: 'Kṣetra-tātparya with the pramātṛ puzzle of KSTS 13.6 (bounded by etatsarvam and the kṛtaparishramāḥ close; lists the unanswered how-questions).',
  },
  {
    id: 'gita-seg-13.6-siddhanta',
    unitIds: ['13.7'],
    ksts: ['13.6'],
    pdf: 291,
    folio: 281,
    anchor: 'commentary-tail',
    status: 'source',
    note: 'Siddhānta-kathā adhikāra and kṣetra-nirṇīta close of KSTS 13.6 (bounded by sā-ca and the nirṇītam close; runs to printed p.282; folio fragment excluded).',
  },
  {
    id: 'gita-seg-13.7-intro',
    unitIds: ['13.7', '13.8'],
    ksts: ['13.6', '13.7'],
    pdf: 292,
    folio: 282,
    anchor: 'commentary',
    status: 'source',
    note: 'Virtue-section introduction bridging the KSTS 13.6 close to KSTS 13.7 (bounded by idānīṃ and the verse marker; carries the printed (१३।२) and (१३।१२) quotations).',
  },
  {
    id: 'gita-seg-13.7-mana',
    unitIds: ['13.8'],
    ksts: ['13.7'],
    pdf: 292,
    folio: 282,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Māna definition with the Mahābhārata quotation of KSTS 13.7 (bounded by saṅgharṣa and the jñānam-ityuktam close; runs to printed p.283).',
  },
  {
    id: 'gita-seg-13.7-adambha',
    unitIds: ['13.8'],
    ksts: ['13.7'],
    pdf: 293,
    folio: 283,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Adambhitva/ahiṃsā/kṣānti gloss of KSTS 13.7 with the hiṃsā nanu and ucyate response (bounded by evameva and the response dash).',
  },
  {
    id: 'gita-seg-13.7-arjava',
    unitIds: ['13.8'],
    ksts: ['13.7'],
    pdf: 294,
    folio: 284,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Hiṃsā resolution with ārjava and the jñāna-taru-mūla turn of KSTS 13.7 (bounded by yathokta and the ācāryopāsana pratīka; carries the mṛtyupada quotation).',
  },
  {
    id: 'gita-seg-13.7-acarya',
    unitIds: ['13.8'],
    ksts: ['13.7'],
    pdf: 294,
    folio: 284,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Ācāryopāsana skandha with śākhā-pratāna and śauca of KSTS 13.7 (bounded by jñānataroḥ and the tapaḥ turn; runs to printed p.285).',
  },
  {
    id: 'gita-seg-13.8-sthairya',
    unitIds: ['13.8', '13.9'],
    ksts: ['13.7', '13.8'],
    pdf: 295,
    folio: 285,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Sthairya through janma-doṣa-darśana gloss of KSTS 13.7–13.8 (bounded by atha and the iti close; carries the prajñāprāsāda quotation).',
  },
  {
    id: 'gita-seg-13.9-asakti',
    unitIds: ['13.10', '13.11'],
    ksts: ['13.9', '13.10'],
    pdf: 295,
    folio: 285,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Asakti through bhakti-phala gloss of KSTS 13.9–13.10 (bounded by tathāvidhasya and the iti close; runs to printed p.286; carries the printed (७।१८) already edged).',
  },
  {
    id: 'gita-seg-13.10-vivikta',
    unitIds: ['13.11', '13.12'],
    ksts: ['13.10', '13.11'],
    pdf: 296,
    folio: 286,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Vivikta through tattvajñānārtha gloss of KSTS 13.10–13.11 (bounded by tasyāṃ-ca and the vakṣyati close; excludes the joint-verse marker and the jñeya verse after).',
  },
  {
    id: 'gita-seg-13.12-pratijna',
    unitIds: ['13.13'],
    ksts: ['13.12'],
    pdf: 296,
    folio: 286,
    anchor: 'commentary',
    status: 'source',
    note: 'Jñeya-pratijñā with the ananya-saṃvedya nanu of KSTS 13.12 (bounded by evaṃvidhena and the nanu close; runs to printed p.287; mūla excluded; nanu wording extraction-noisy, retained verbatim).',
  },
  {
    id: 'gita-seg-13.12-pratyavamarsa',
    unitIds: ['13.13'],
    ksts: ['13.12'],
    pdf: 297,
    folio: 287,
    anchor: 'commentary',
    status: 'source',
    note: 'Pratyavamarśa elaboration after the satyam response of KSTS 13.12 (bounded by yataḥ and the avagamaḥ close; self-recognition as the jñāna).',
  },
  {
    id: 'gita-seg-13.12-samjna',
    unitIds: ['13.13'],
    ksts: ['13.12'],
    pdf: 297,
    folio: 287,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Saṃjñā-nirdeśa with the ādimat analysis of KSTS 13.12 (bounded by kiṃ-tajjñeyam and the antakoṭi close; runs to printed p.288).',
  },
  {
    id: 'gita-seg-13.12-nasat',
    unitIds: ['13.13', '13.14'],
    ksts: ['13.12', '13.13'],
    pdf: 298,
    folio: 288,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Na-sat exposition with the sarvataḥ-pāṇipāda turn of KSTS 13.12–13.13 (bounded by anyacca and the vyāpya-vartata close).',
  },
  {
    id: 'gita-seg-13.13-sarvendriya',
    unitIds: ['13.14'],
    ksts: ['13.13'],
    pdf: 298,
    folio: 288,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Sarvendriya gloss of KSTS 13.13 (bounded by ata-eva and the jñānam-ityarthaḥ close; runs to printed p.289).',
  },
  {
    id: 'gita-seg-13.14-asakta',
    unitIds: ['13.15'],
    ksts: ['13.14'],
    pdf: 299,
    folio: 289,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Asakta through guṇabhoktṛ gloss of KSTS 13.14 (bounded by tathā and the bhujyate close; nirguṇa/guṇabhoktṛ distinction).',
  },
  {
    id: 'gita-seg-13.15-bahiranta',
    unitIds: ['13.15', '13.16'],
    ksts: ['13.14', '13.15'],
    pdf: 299,
    folio: 289,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Bahir-antaḥ with acara-cara and sūkṣma of KSTS 13.14–13.15 (bounded by ata-eva and the saukṣmyāt close).',
  },
  {
    id: 'gita-seg-13.15-avibhakta',
    unitIds: ['13.16', '13.17'],
    ksts: ['13.15', '13.16'],
    pdf: 299,
    folio: 289,
    anchor: 'commentary-tail',
    role: 'gloss',
    status: 'source',
    note: 'Dūra/antika with avibhakta/vibhakta gloss of KSTS 13.15–13.16 (bounded by ata-eva and the avabhāsamānatvāt close; runs to printed p.290).',
  },
  {
    id: 'gita-seg-13.16-bhutabhartr',
    unitIds: ['13.17'],
    ksts: ['13.16'],
    pdf: 300,
    folio: 290,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Bhūtabhartṛ triad with jyotiṣ/tamas gloss of KSTS 13.16 (bounded by tathā and the vyatirikta-vā close).',
  },
  {
    id: 'gita-seg-13.17-jnanagamya',
    unitIds: ['13.18'],
    ksts: ['13.17'],
    pdf: 300,
    folio: 290,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Jñāna-jñeya with jñāna-gamya and hṛdi close of KSTS 13.17 (bounded by tathā and the siddhyavasthāyāṃ close).',
  },
  {
    id: 'gita-seg-13.18-upasamhara',
    unitIds: ['13.19'],
    ksts: ['13.18'],
    pdf: 300,
    folio: 290,
    anchor: 'commentary',
    status: 'source',
    note: 'Kṣetra-jñāna-jñeya upasaṃhāra with madbhakta of KSTS 13.18 (bounded by iti and the upapannaḥ close; runs to printed p.291; corrupt non-Devanagari fragment after mahābhūtāni excluded; disagreeing (१३।५) retained unresolved).',
  },
  {
    id: 'gita-seg-13.19-anaditva',
    unitIds: ['13.20'],
    ksts: ['13.19'],
    pdf: 301,
    folio: 291,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Anāditva-tātparya with vikārān/guṇān of KSTS 13.19 (bounded by nahi and the jānīhi close; pravāha-nityatva vs kūṭastha-nityatva).',
  },
  {
    id: 'gita-seg-13.19-samanya',
    unitIds: ['13.21'],
    ksts: ['13.20'],
    pdf: 301,
    folio: 291,
    anchor: 'commentary',
    status: 'source',
    note: 'Sāmānya to prati-puruṣa transition introducing KSTS 13.20 (bounded by evaṃ and the verse marker; bridges the 13.19 close; mūla excluded).',
  },
  {
    id: 'gita-seg-13.20-prakrtihetu',
    unitIds: ['13.21'],
    ksts: ['13.20'],
    pdf: 301,
    folio: 291,
    anchor: 'commentary-tail',
    role: 'gloss',
    status: 'source',
    note: 'Prakṛti-hetu with puruṣa-bhoktṛ gloss of KSTS 13.20 (bounded by tasya and the vyapadeśaḥ close; runs to printed p.292).',
  },
  {
    id: 'gita-seg-13.21-gunasanga-a',
    unitIds: ['13.22'],
    ksts: ['13.21'],
    pdf: 302,
    folio: 292,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Prakṛti-stha with bhuṅkte gloss of KSTS 13.21 (bounded by yasmāt and the vyapadeśahetavaḥ close; māyāvaśāt reference).',
  },
  {
    id: 'gita-seg-13.21-gunasanga-b',
    unitIds: ['13.22'],
    ksts: ['13.21'],
    pdf: 302,
    folio: 292,
    anchor: 'commentary',
    status: 'source',
    note: 'Avivekaja sambandha with guṇasaṅga and sadasad-yoni of KSTS 13.21 (bounded by evaṃ and the saṃsāritā close; ahaṅkāra-mamakāra dṛḍha sambandha).',
  },
  {
    id: 'gita-seg-13.22-dvividha',
    unitIds: ['13.23'],
    ksts: ['13.22'],
    pdf: 302,
    folio: 292,
    anchor: 'commentary',
    status: 'source',
    note: 'Dvividhā-sthiti transition introducing KSTS 13.22 (bounded by yataḥ and the verse marker; mūla excluded).',
  },
  {
    id: 'gita-seg-13.22-upadrastra',
    unitIds: ['13.23'],
    ksts: ['13.22'],
    pdf: 303,
    folio: 293,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Upadraṣṭṛ triad (upadraṣṭā/bhartā/anumantā) of KSTS 13.22 (bounded by yataḥ and the vastvuttaram close; dṛśya-parāmarśa analysis).',
  },
  {
    id: 'gita-seg-13.22-viveka',
    unitIds: ['13.23'],
    ksts: ['13.22'],
    pdf: 303,
    folio: 293,
    anchor: 'commentary',
    status: 'source',
    note: 'Bhoktṛ-vyapadeśa with viveka and paramātman close of KSTS 13.22 (bounded by tataśca and the ucyate close; māyā-nibandhana vivekābhāva).',
  },
  {
    id: 'gita-seg-13.23-phala-intro',
    unitIds: ['13.24'],
    ksts: ['13.23'],
    pdf: 303,
    folio: 293,
    anchor: 'commentary',
    status: 'source',
    note: 'Phala introduction to KSTS 13.23 (bounded by evaṃ and the verse marker; prakṛti-puruṣeśvara-viveka as the jñāna; mūla excluded).',
  },
  {
    id: 'gita-seg-13.23-yogi',
    unitIds: ['13.24'],
    ksts: ['13.23'],
    pdf: 303,
    folio: 293,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Yaḥ-yogī gloss with the jñāna-dagdha quotation of KSTS 13.23 (bounded by yo and the spaṣṭo close; runs to printed p.294; quotation without locator, unresolved).',
  },
  {
    id: 'gita-seg-13.24-dhyana',
    unitIds: ['13.25'],
    ksts: ['13.24'],
    pdf: 304,
    folio: 294,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Sahaja-dhyāna parā-kāṣṭhā gloss of KSTS 13.24 (bounded by ke-cit and the tātparyam close; abheda-pratipādana of ātmanā/ātmani).',
  },
  {
    id: 'gita-seg-13.24-sankhya',
    unitIds: ['13.25'],
    ksts: ['13.24'],
    pdf: 304,
    folio: 294,
    anchor: 'commentary',
    status: 'source',
    note: 'Sāṅkhya/yoga/karma-yoga dvi-prakāra with the (६।३) quotation of KSTS 13.24 (bounded by samprati and the upanyastam close; ārūḍha vs ārurukṣu stages).',
  },
  {
    id: 'gita-seg-13.25-samuccaya',
    unitIds: ['13.26'],
    ksts: ['13.25'],
    pdf: 305,
    folio: 295,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Samuccayātmakatva with the ārurukṣu turn of KSTS 13.25 (bounded by karmayogeneti and the anumānāt close; partial ārurukṣor quotation without locator, unresolved).',
  },
  {
    id: 'gita-seg-13.25-sruta',
    unitIds: ['13.26'],
    ksts: ['13.25'],
    pdf: 305,
    folio: 295,
    anchor: 'commentary',
    status: 'source',
    note: 'Śruta-upāsaka with satya/asatya and the amṛta quotation of KSTS 13.25 (bounded by anye-punar and the iti close; āgamamātra-śaraṇa crossing).',
  },
  {
    id: 'gita-seg-13.26-samyoga',
    unitIds: ['13.27'],
    ksts: ['13.26'],
    pdf: 305,
    folio: 295,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Kṣetra-saṃyoga gloss of KSTS 13.26 with the parisamāpti turn (bounded by uktameva and the nivṛtteḥ close; runs to printed p.296; anādi-prabandha hetu).',
  },
  {
    id: 'gita-seg-13.27-sama',
    unitIds: ['13.28'],
    ksts: ['13.27'],
    pdf: 306,
    folio: 296,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Sarveṣu-sama introduction of KSTS 13.27 (bounded by the yogī turn and the sākṣātkurute close; nirviśeṣa sthiti).',
  },
  {
    id: 'gita-seg-13.27-samapasya',
    unitIds: ['13.28'],
    ksts: ['13.27'],
    pdf: 306,
    folio: 296,
    anchor: 'commentary',
    status: 'source',
    note: 'Vinaśyatsu with the jñāna-cakṣuṣ close of KSTS 13.27 (bounded by kīdṛśeṣu and the ātmavān close; vedakaika-lakṣaṇa sākṣātkāra).',
  },
  {
    id: 'gita-seg-13.28-atmahimsa',
    unitIds: ['13.29'],
    ksts: ['13.28'],
    pdf: 306,
    folio: 296,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Ātma-ahiṃsā gloss with the anyathā quotation of KSTS 13.28 (bounded by yasmāt and the iti close; runs to printed p.297; quotation without locator, unresolved).',
  },
  {
    id: 'gita-seg-13.29-prakrtya',
    unitIds: ['13.30'],
    ksts: ['13.29'],
    pdf: 307,
    folio: 297,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Prakṛti-dviprakārā with the (७।६) and (१३।२६) quotations of KSTS 13.29 (bounded by prakṛtiśca and the abhihitaḥ close; jagac-citra cause).',
  },
  {
    id: 'gita-seg-13.29-akartra',
    unitIds: ['13.30'],
    ksts: ['13.29'],
    pdf: 307,
    folio: 297,
    anchor: 'commentary',
    status: 'source',
    note: 'Prakṛtyaiva with akartṛ and the māyā-mātra close of KSTS 13.29 (bounded by tadevarūpayā and the tātparyam close; runs to printed p.298).',
  },
  {
    id: 'gita-seg-13.30-ekatva',
    unitIds: ['13.31'],
    ksts: ['13.30'],
    pdf: 308,
    folio: 298,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Tadā/yadā with bhūta-ekastha gloss of KSTS 13.30 (bounded by itthañca and the sākṣātkaroti close; vivekajñāna-nairmalya condition).',
  },
  {
    id: 'gita-seg-13.30-vistara',
    unitIds: ['13.31'],
    ksts: ['13.30'],
    pdf: 308,
    folio: 298,
    anchor: 'commentary',
    status: 'source',
    note: 'Ekatva-anubhava with tata-eva-vistāra and the vipascit quotation of KSTS 13.30 (bounded by kimanena and the iti close; runs to printed p.299; quotation without locator, unresolved).',
  },
  {
    id: 'gita-seg-13.31-avyaya-a',
    unitIds: ['13.32'],
    ksts: ['13.31'],
    pdf: 309,
    folio: 299,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Ayaṃ-paramātmā with na-karoti gloss of KSTS 13.31 (bounded by tadevaṃvidhasya and the anubhavastha close; avyāhata-sadbhāva).',
  },
  {
    id: 'gita-seg-13.31-avyaya-b',
    unitIds: ['13.32'],
    ksts: ['13.31'],
    pdf: 309,
    folio: 299,
    anchor: 'commentary',
    status: 'source',
    note: 'Anāditva/nirguṇatva with the kṣetrajña contrast of KSTS 13.31 (bounded by yasmāt and the saṃyoga close; upacāra denied even to paramātman).',
  },
  {
    id: 'gita-seg-13.32-akasa',
    unitIds: ['13.33'],
    ksts: ['13.32'],
    pdf: 310,
    folio: 300,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Ākāśa-dṛṣṭānta with the ghaṭākāśa quotation of KSTS 13.32 (bounded by yathāca and the iti close; quotation without locator, unresolved).',
  },
  {
    id: 'gita-seg-13.33-ravi',
    unitIds: ['13.34'],
    ksts: ['13.33'],
    pdf: 310,
    folio: 300,
    anchor: 'commentary',
    role: 'gloss',
    status: 'source',
    note: 'Ravi-dṛṣṭānta with kṛtsna-prakāśa gloss of KSTS 13.33 (bounded by evaṃ and the prakāśayati close; runs to printed p.301).',
  },
  {
    id: 'gita-seg-13.33-janaka',
    unitIds: ['13.34'],
    ksts: ['13.33'],
    pdf: 311,
    folio: 301,
    anchor: 'commentary',
    status: 'source',
    note: 'Prakāśya-nānātva with kṣetrī-janakatva close of KSTS 13.33 (bounded by kimuktaṃ and the pratipāditameva close; upamāna-upameya limited to prakāśakatva).',
  },
  {
    id: 'gita-seg-13.34-moksa',
    unitIds: ['13.35'],
    ksts: ['13.34'],
    pdf: 311,
    folio: 301,
    anchor: 'commentary',
    status: 'source',
    note: 'Bhūtaprakṛtimokṣa exposition of KSTS 13.34 (bounded by na-kevalaṃ and the bhavati close; nityāvahitatva as the mokṣa ground beyond mere viveka).',
  },
  {
    id: 'gita-seg-13.34-para',
    unitIds: ['13.35'],
    ksts: ['13.34'],
    pdf: 311,
    folio: 301,
    anchor: 'commentary-tail',
    status: 'source',
    note: 'Para-gati close of KSTS 13.34 (bounded by te and the iti-om close; runs to printed p.302; saptama paratarā-prakṛti recall).',
  },
  {
    id: 'gita-seg-13.34-prasasti',
    unitIds: ['13.35'],
    ksts: ['13.34'],
    pdf: 312,
    folio: 302,
    anchor: 'closing',
    status: 'source',
    note: 'Authorial praśasti verse with the fixed colophon (bounded by the verse opening and the adhyāya number; distinct from the locator-only closing-apparatus record).',
  },
];

export function passageSpanById(id: string): GitaPassageSpan | undefined {
  return GITA_PASSAGE_SPANS.find((s) => s.id === id);
}
