/**
 * Sāṅkhya-Pravacana-Sūtra, Adhyāya II · Pradhāna-kārya (2.1–2.46) — English.
 * Topics: purpose of creation (1–9) · tattva-krama, mahat/ahaṅkāra/indriyas
 * (10–29) · antaḥkaraṇa, prāṇa, vṛttis (30–35) · instruments serve puruṣa,
 * thirteen karaṇas, buddhi-prādhānya (36–46).
 */
export const samkhyaSutraEn2: any[] = [
  {
    "id": "2.1",
    "number": "2.1",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "vimuktamokṣārthaṃ svārthaṃ vā pradhānasya",
    "devanagari": "विमुक्तमोक्षार्थं स्वार्थं वा प्रधानस्य",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Pradhāna's creativity is for the released one's release — or for her own sake.",
    "commentary": "Two readings: Aniruddha — vimukta-mokṣa (release even of the already-released, i.e., jīvanmukta's videha-sequel); Vijñāna — sva-artha (her own urge, spontaneity). Either way creation is purposive (prayojanavatī), never mechanical accident.",
    "keyPoints": ["Creation is purposive: release or urge.", "Prayojana, not chance, starts sarga."]
  },
  {
    "id": "2.2",
    "number": "2.2",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "vairāgyārthaṃ tatsiddheḥ",
    "devanagari": "वैराग्यार्थं तत्सिद्धेः",
    "conceptIds": ["vairagya-sutra"],
    "translation": "Successive creation is needed — for release matures only in the dispassioned.",
    "commentary": "Why sarga-paramparā at all? Vairāgya (indifference through seeing duḥkha in all bhoga) ripens across births. Creation's succession is the school where dispassion graduates — sarga serves vairāgya, vairāgya serves mokṣa.",
    "keyPoints": ["Sarga is dispassion's school.", "Release ripens only in the vairāgin."]
  },
  {
    "id": "2.3",
    "number": "2.3",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "na śravaṇamātrāt tad anādivāsanāyāḥ",
    "devanagari": "न श्रवणमात्रात् तद् अनादिवासनायाः",
    "conceptIds": ["vairagya-sutra"],
    "translation": "Not from mere hearing — for beginningless impressions block it.",
    "commentary": "Śravaṇa (learning) alone cannot birth vairāgya: anādi-vāsanā (beginningless habit-currents toward bhoga) resists. Manana-abhyāsa-vairāgya in succession wear vāsanā down — hence successive creation (II.2) is necessary.",
    "keyPoints": ["Hearing alone cannot uproot beginningless habit.", "Practice across births wears vāsanā down."]
  },
  {
    "id": "2.4",
    "number": "2.4",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "bahubhṛtyavat pratyekaṃ",
    "devanagari": "बहुभृत्यवत् प्रत्येकं",
    "conceptIds": ["purusha-sutra"],
    "translation": "As one householder's many dependants each have their lot — so each puruṣa; hence creation's stream flows eternal.",
    "commentary": "Aniruddha: many puruṣas, many lots — sarga never globally ends (cf. I.159). Vijñāna: one householder (prakṛti) serves many (puruṣas) distinctly. Pravāha-nityatva with individual lots — plurality restated cosmologically.",
    "keyPoints": ["Many lots, one household.", "Creation's stream is beginningless."]
  },
  {
    "id": "2.5",
    "number": "2.5",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "prakṛtivāstave puruṣasyādhyāropitasiddhiḥ",
    "devanagari": "प्रकृतिवास्तवे पुरुषस्याध्यारोपितसिद्धिः",
    "conceptIds": ["abhasa-sutra"],
    "translation": "Bondage, creativity and the like truly belonging to prakṛti proves their attribution to puruṣa fictitious.",
    "commentary": "Vāstava (real seat) vs āropita (attributed): once prakṛti's kartṛtva is proved real, puruṣa's kartṛtva stands exposed as adhyāsa. The argument's hinge — establishing prakṛti's reality (II.6) topples puruṣa's apparent agency.",
    "keyPoints": ["Real seat vs attributed seat.", "Proving prakṛti's agency disproves puruṣa's."]
  },
  {
    "id": "2.6",
    "number": "2.6",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "kāryataḥ tatsiddheḥ",
    "devanagari": "कार्यतः तत्सिद्धेः",
    "conceptIds": ["tattva-sutra"],
    "translation": "For her reality is proved from products.",
    "commentary": "Kāryataḥ-siddhi (cf. I.110, I.136): mahat-ādi stand before us; uncaused-yet-productive ground follows. Short seal: prakṛti is no hypothesis — she is effects' necessary presupposition.",
    "keyPoints": ["Products presuppose producer.", "Prakṛti is inference's conclusion, not assumption."]
  },
  {
    "id": "2.7",
    "number": "2.7",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "jñānaviṣaye niyamaḥ kaṇṭakoddhāravat",
    "devanagari": "ज्ञानविषये नियमः कण्टकोद्धारवत्",
    "conceptIds": ["viveka-sutra"],
    "translation": "The rule concerns the knower — as with thorn-removal.",
    "commentary": "Whose release? The jñānin's — as the surgeon removes the thorn for the patient who knows his pain. Jñāna-niyama: viveka binds its fruit to its knower; others' knowledge doesn't free me (cf. I.155).",
    "keyPoints": ["Knowledge frees its knower.", "Thorn removed for the one who feels it."]
  },
  {
    "id": "2.8",
    "number": "2.8",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "sahabhāve 'py anyasaṃyogāt tadabhāvaḥ dāhavat",
    "devanagari": "सहभावे ऽप्य् अन्यसंयोगात् तदभावः दाहवत्",
    "conceptIds": ["abhasa-sutra", "mukti-sutra"],
    "translation": "Though conjoined with the other, this (bondage) is not immediate in puruṣa — as burning belongs to fuel, not fire-seer.",
    "commentary": "Saṃyoga (I.19) doesn't instantly bind: fire contacts fuel yet 'burning' is fuel's; puruṣa contacts buddhi yet bandha is buddhi's. Temporal lag and locus-difference — conjunction occasions, aviveka constitutes (cf. I.57).",
    "keyPoints": ["Conjunction occasions; aviveka constitutes.", "Fire sees burning without burning."]
  },
  {
    "id": "2.9",
    "number": "2.9",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "rāgāt sṛṣṭiḥ vairāgyān mokṣaḥ",
    "devanagari": "रागात् सृष्टिः वैराग्यान् मोक्षः",
    "conceptIds": ["vairagya-sutra"],
    "translation": "From passion, creation; from dispassion, release.",
    "commentary": "Rāga (thirst for bhoga) draws prakṛti's display; vairāgya (seeing duḥkha in bhoga) withdraws it. One mechanism, two directions — sarga and apavarga are rāga/vairāgya's faces. The book's moral engine in one line.",
    "keyPoints": ["Passion projects; dispassion retracts.", "Sarga and mokṣa share one switch."]
  },
  {
    "id": "2.10",
    "number": "2.10",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "mahadādiṣu bhūtānāṃ pañcānāṃ kramaḥ",
    "devanagari": "महदादिषु भूतानां पञ्चानां क्रमः",
    "conceptIds": ["tattva-sutra"],
    "translation": "The five bhūtas arise in mahat's order.",
    "commentary": "'Sattva-rajas-tamas' aphorism's sequence governs: śabda→ākāśa, sparśa→vāyu, rūpa→tejas, rasa→ap, gandha→pṛthivī — each adding a quality (śabdādiguṇottaratā). Krama is guṇa-logic, not temporal accident.",
    "keyPoints": ["Elements condense in guṇa-order.", "Each adds one quality to the last."]
  },
  {
    "id": "2.11",
    "number": "2.11",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "ātmārthatvāt tadutpattiḥ na svārthā",
    "devanagari": "आत्मार्थत्वात् तदुत्पत्तिः न स्वार्था",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Since creation serves the Self, mahat and the rest arise not for themselves.",
    "commentary": "Parārtha-utpatti: evolutes never self-serving — buddhi doesn't enjoy its own determinations. Everything downstream serves puruṣa's bhoga/apavarga (cf. I.140 saṃghāta-parārthatva at cosmic scale).",
    "keyPoints": ["No evolute serves itself.", "All tattvas are puruṣa's instruments."]
  },
  {
    "id": "2.12",
    "number": "2.12",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "ākāśādibhyo deśakālau upādhibhyām",
    "devanagari": "आकाशादिभ्यो देशकालौ उपाधिभ्याम्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Space and time come from ākāśa and limiting adjuncts.",
    "commentary": "Deśa-kāla are not tattvas but upādhi-products: ākāśa (all-containing) + avaccheda (limitation) yield 'here/now.' Time = pariṇāma-krama cognized; space = ākāśa delimited. Constructions, not substances (cf. old karma/14 kāla note).",
    "keyPoints": ["Space-time are adjunct-products, not tattvas.", "Limitation of the unlimited yields here-now."]
  },
  {
    "id": "2.13",
    "number": "2.13",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "adhyavasāyo buddhiḥ",
    "devanagari": "अध्यवसायो बुद्धिः",
    "conceptIds": ["buddhi-sutra"],
    "translation": "Buddhi is ascertainment.",
    "commentary": "Buddhi-lakṣaṇa (cf. Kārikā 23): adhyavasāya — 'this is so' determination. All saṃśaya ends here; buddhi is the court of last appeal before puruṣa. Its eight bhāvas (I.43ff-old) color every verdict.",
    "keyPoints": ["Determination defines intellect.", "Doubt ends at buddhi."]
  },
  {
    "id": "2.14",
    "number": "2.14",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "dharmādayas tatprakṛtayaḥ",
    "devanagari": "धर्मादयस् तत्प्रकृतयः",
    "conceptIds": ["buddhi-sutra"],
    "translation": "Virtue and the rest are its modes.",
    "commentary": "Aṣṭa-bhāvas (dharma-jñāna-vairāgya-aiśvarya + reverses) are buddhi-prakṛti — her standing moods, not visitors. Destiny is buddhi-chemistry: dharma lifts, jñāna frees, vairāgya merges, aiśvarya unblocks (old 3.2).",
    "keyPoints": ["Eight moods are buddhi's nature.", "Mood-chemistry decides destiny."]
  },
  {
    "id": "2.15",
    "number": "2.15",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "uparāgāt tadviparītam",
    "devanagari": "उपरागात् तद्विपरीतम्",
    "conceptIds": ["buddhi-sutra"],
    "translation": "The same mahat yields opposites through adjacent tinting (of rajas-tamas).",
    "commentary": "One mahat, two faces: sattva-uparāga → dharma-jñāna; rajas/tamas-uparāga → adharma-ajñāna. Adjacency (saṃnidhi) tints — crystal-flower logic within buddhi herself. Guṇa-proportion explains moral diversity.",
    "keyPoints": ["One buddhi, two faces by tinting.", "Moral diversity is guṇa-proportion."]
  },
  {
    "id": "2.16",
    "number": "2.16",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "abhimāno 'haṅkāraḥ",
    "devanagari": "अभिमानो ऽहङ्कारः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Self-conceit is ahaṅkāra.",
    "commentary": "Ahaṅkāra-lakṣaṇa (cf. Kārikā 24): abhimāna — 'I-mine' appropriation. Buddhi determines; ahaṅkāra claims. All mamakāra passes through this second knot.",
    "keyPoints": ["Appropriation defines ego.", "Determination claimed as 'mine.'"]
  },
  {
    "id": "2.17",
    "number": "2.17",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "ekādaśapañcakau tatkāryam",
    "devanagari": "एकादशपञ्चकौ तत्कार्यम्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Eleven and five are its products.",
    "commentary": "Sixteen from one (cf. I.73): ekādaśa indriyas + pañca tanmātras. Count sealed: 11 + 5 = 16 vikāras (cf. old 2.2 census). Ahaṅkāra is the great divider into instruments and subtles.",
    "keyPoints": ["16 products: 11 organs + 5 subtles.", "Ego divides into seizing and subtle."]
  },
  {
    "id": "2.18",
    "number": "2.18",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "sāttvika ekādaśako vaikṛtāt",
    "devanagari": "सात्त्विक एकादशको वैकृतात्",
    "conceptIds": ["tattva-sutra"],
    "translation": "The sāttvika eleven come from vaikṛta (ahaṅkāra).",
    "commentary": "Vaikṛta (sāttvika-ahaṅkāra) → indriyas: instruments of प्रकाश (illumination) are sattva-born. Functional fit: seizing/holding/illumining need laghu-prakāśa stuff (cf. Kārikā 25).",
    "keyPoints": ["Sattva-ego births organs.", "Instruments are illumination-stuff."]
  },
  {
    "id": "2.19",
    "number": "2.19",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "karmabuddhīndriyaiḥ sahitaṃ ekādaśakam antaḥ",
    "devanagari": "कर्मबुद्धीन्द्रियैः सहितं एकादशकम् अन्तः",
    "conceptIds": ["tattva-sutra"],
    "translation": "With action- and cognition-organs, the inner (manas) is eleventh.",
    "commentary": "Census: 5 karmendriyas + 5 buddhīndriyas + manas (inner, ubhayātmaka) = 11. Manas counted among indriyas by function-sharing (sādharmya, cf. Kārikā 27) — director of both sets.",
    "keyPoints": ["5 + 5 + 1 = 11.", "Manas: inner eleventh, dual-natured."]
  },
  {
    "id": "2.20",
    "number": "2.20",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "na bhautikāḥ ahaṅkārikatvaśruteḥ",
    "devanagari": "न भौतिकाः अहङ्कारिकत्वश्रुतेः",
    "conceptIds": ["tattva-sutra", "sruti-sutra"],
    "translation": "Organs are not elemental — śruti declares them ego-born.",
    "commentary": "Against bhautika-indriya (organs = bhūta-composites): 'ahaṅkārāt' śruti + laya-evidence (senses withdraw into mind, not earth, at sleep/death). Organs are taijasa-vaikṛta, subtler than bhūtas.",
    "keyPoints": ["Organs withdraw into mind, not clay.", "Śruti: ego-born, not element-born."]
  },
  {
    "id": "2.21",
    "number": "2.21",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "devatālayśruteḥ na tatkāraṇatvam",
    "devanagari": "देवतालय्श्रुतेः न तत्कारणत्वम्",
    "conceptIds": ["tattva-sutra", "sruti-sutra"],
    "translation": "Śruti of merging into devatās denies bhūta-causality.",
    "commentary": "Aniruddha: 'vāg agnau' — speech merges into Agni-devatā at death, not into earth; originator (bhūtas) disproved. Vijñāna: devatā-laya confirms adhidaiva-level (ahaṅkārika) source. Dissolution reveals origin.",
    "keyPoints": ["Death-dissolution reveals birth-source.", "Senses merge Godward, not earthward."]
  },
  {
    "id": "2.22",
    "number": "2.22",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "utpattyādivināśadarśanād anityāḥ",
    "devanagari": "उत्पत्त्यादिविनाशदर्शनाद् अनित्याः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Organs are non-eternal — production heard, destruction seen.",
    "commentary": "Śruti declares their birth ('prāṇāḥ prajāyante'); pratyakṣa sees decay (blindness, death). Ubhaya-pramāṇa: āgama + dṛṣṭa agree — organs are vikāra (cf. I.124 anitya).",
    "keyPoints": ["Birth heard, decay seen.", "Two proofs of non-eternity."]
  },
  {
    "id": "2.23",
    "number": "2.23",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "atīndriyam indriyaṃ mūḍhānāṃ sthāne buddhiḥ",
    "devanagari": "अतीन्द्रियम् इन्द्रियं मूढानां स्थाने बुद्धिः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Organs are supersensible; fools mistake their seats for them.",
    "commentary": "Indriya ≠ golaka (eyeball): the power is atīndriya (ahaṅkārika); the locus visible. Mūḍhas identify instrument with socket — like mistaking socket for electricity. Subtlety explains invisibility (cf. I.109).",
    "keyPoints": ["Power, not socket, is the organ.", "Eyeball is seat, not seer."]
  },
  {
    "id": "2.24",
    "number": "2.24",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "śaktibhede 'pi naikatvaṃ bhedasiddheḥ",
    "devanagari": "शक्तिभेदे ऽपि नैकत्वं भेदसिद्धेः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Despite power-differences, no unity — difference is established.",
    "commentary": "One śakti manifesting as many functions doesn't merge organs: vṛtti-bheda + āśraya-bheda + viṣaya-bheda (different acts, seats, objects) prove bheda. Economy (lāghava) can't override observed plurality.",
    "keyPoints": ["Act, seat, object differ per organ.", "Observed difference beats assumed unity."]
  },
  {
    "id": "2.25",
    "number": "2.25",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "pramāṇasiddhasya na cittavirodhaḥ",
    "devanagari": "प्रमाणसिद्धस्य न चित्तविरोधः",
    "conceptIds": ["pramana-sutra"],
    "translation": "What proof establishes, thought cannot contradict.",
    "commentary": "Pramāṇa beats citta (fancy): established organ-plurality stands against monistic 'feelings.' Method-seal: yukti serves pramāṇa; private intuition never overrides. (Guards II.24's conclusion.)",
    "keyPoints": ["Proof outranks fancy.", "Reason serves evidence, not mood."]
  },
  {
    "id": "2.26",
    "number": "2.26",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "ubhayātmakaṃ manaḥ",
    "devanagari": "उभयात्मकं मनः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Manas is dual-natured.",
    "commentary": "Ubhayātmaka (cf. Kārikā 27): saṅkalpa serves jñāna (presenting to buddhi) and karma (directing organs). Bridge-organ: outer data → inner decision passes through manas both ways.",
    "keyPoints": ["Knows and acts — both.", "Bridge between outer and inner."]
  },
  {
    "id": "2.27",
    "number": "2.27",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "guṇapariṇāmabhedān manasāṃ nānātvam ekaikasya iva",
    "devanagari": "गुणपरिणामभेदान् मनसां नानात्वम् एकैकस्य इव",
    "conceptIds": ["tattva-sutra", "guna-sutra"],
    "translation": "Minds differ by guṇa-transformation differences — as one man's states differ.",
    "commentary": "One manas-stuff, many mind-states: sattva-dawn clarity, rajas-noon restlessness, tamas-night dullness in one person daily. Guṇa-pariṇāma explains intra- and inter-personal mental diversity without many manas-substances.",
    "keyPoints": ["One stuff, many states.", "Daily mood-cycle proves guṇa-shifts."]
  },
  {
    "id": "2.28",
    "number": "2.28",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "ālocanamātram indriyāṇāṃ vacanādayas tu karmendriyāṇām",
    "devanagari": "आलोचनमात्रम् इन्द्रियाणां वचनादयस् तु कर्मेन्द्रियाणाम्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Bare awareness is the sense-organs' lot; speech and the rest, the action-organs'.",
    "commentary": "Ālocana-mātra (cf. Kārikā 28): jñānendriyas register indeterminate vibration; determination belongs to antaḥkaraṇa. Karmendriyas: vacana-ādāna-viharaṇa-utsarga-ānanda. Division: sensing vs doing.",
    "keyPoints": ["Senses register; inner organ determines.", "Five actions: speech, grasp, movement, excretion, delight."]
  },
  {
    "id": "2.29",
    "number": "2.29",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "draṣṭṛtvam ātmanaḥ karaṇatvam indriyāṇām",
    "devanagari": "द्रष्टृत्वम् आत्मनः करणत्वम् इन्द्रियाणाम्",
    "conceptIds": ["purusha-sutra", "tattva-sutra"],
    "translation": "Seership belongs to the Self; instrumentality to the organs.",
    "commentary": "Draṣṭṛ–karaṇa vibhāga: puruṣa never instrument, organs never seer. Category-seal preventing the two fundamental confusions (puruṣa-as-doer, buddhi-as-knower) — cf. I.96–99, old 3.5.",
    "keyPoints": ["Seer never instrument.", "Instrument never seer."]
  },
  {
    "id": "2.30",
    "number": "2.30",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "trayasya svalakṣaṇaṃ vṛttiḥ",
    "devanagari": "त्रयस्य स्वलक्षणं वृत्तिः",
    "conceptIds": ["tattva-sutra"],
    "translation": "The three (inner) have own-marks as functions.",
    "commentary": "Sva-lakṣaṇa (cf. Kārikā 29): buddhi-adhyavasāya, ahaṅkāra-abhimāna, manas-saṅkalpa — unshared acts. Asāmānya (distinctive) functions individuate the antaḥkaraṇa members; prāṇa is sāmānya (II.31).",
    "keyPoints": ["Determine, appropriate, deliberate — three distinct acts.", "Distinctive vs common functions divided."]
  },
  {
    "id": "2.31",
    "number": "2.31",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "sāmānyakaraṇavṛttiḥ prāṇādyāḥ",
    "devanagari": "सामान्यकरणवृत्तिः प्राणाद्याः",
    "conceptIds": ["tattva-sutra"],
    "translation": "The common instrument-function is the five airs beginning with prāṇa.",
    "commentary": "Pañca-vāyu (prāṇa-apāna-udāna-vyāna-samāna) run beneath all organs as sāmānya-vṛtti — no organ acts unfueled. Common (shared) vs own (distinctive): the two-tier function economy (cf. Kārikā 29).",
    "keyPoints": ["Five airs fuel every organ.", "No function without vital current."]
  },
  {
    "id": "2.32",
    "number": "2.32",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "yugapatkramaśaś ca vṛttiḥ catuṣṭayasya",
    "devanagari": "युगपत्क्रमशश् च वृत्तिः चतुष्टयस्य",
    "conceptIds": ["tattva-sutra"],
    "translation": "The four function now together, now in sequence.",
    "commentary": "Catuṣṭaya (three inner + one outer) work yugapat (snake-seen-fled in a flash) or kramaśas (dark-sound → shape → weapon → danger → flight). Speed compresses sequence into seeming simultaneity (cf. Kārikā 30).",
    "keyPoints": ["Flash or sequence — same organs.", "Simultaneity is compressed succession."]
  },
  {
    "id": "2.33",
    "number": "2.33",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "pañcadhā vṛttayaḥ kliṣṭākliṣṭāḥ",
    "devanagari": "पञ्चधा वृत्तयः क्लिष्टाक्लिष्टाः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Modifications are fivefold — afflicted and unafflicted (cf. Yoga I.5).",
    "commentary": "Pañca-vṛtti (pramāṇa-viparyaya-vikalpa-nidrā-smṛti) imported from Yoga: kliṣṭa (rati-dveṣa-feeding) vs akliṣṭa (viveka-serving). Citta-bhūmi shared with Yoga — Sāṅkhya-Yoga psychology one (cf. old 3.1 buddhi-forms).",
    "keyPoints": ["Five modifications, two moral signs.", "Yoga psychology adopted wholesale."]
  },
  {
    "id": "2.34",
    "number": "2.34",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "tannivṛttau pratibimbābhāvāt svarūpasthitiḥ",
    "devanagari": "तन्निवृत्तौ प्रतिबिम्बाभावात् स्वरूपस्थितिः",
    "conceptIds": ["mukti-sutra"],
    "translation": "On their cessation, reflection gone, He rests in own-form.",
    "commentary": "Vṛtti-nirodha → pratibimba-nivṛtti → svarūpa-sthiti (cf. Yoga I.2–3, old 4.x). Cessation of coloring ends apparent agency/suffering; puruṣa 'remains' — ever remained — Self-seated. Book II's mokṣa-glimpse mid-psychology.",
    "keyPoints": ["Coloring ceases; crystal stands clear.", "Rest is revelation of the ever-rested."]
  },
  {
    "id": "2.35",
    "number": "2.35",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "maṇivat kusumādinā",
    "devanagari": "मणिवत् कुसुमादिना",
    "conceptIds": ["abhasa-sutra"],
    "translation": "As jewel with flower and the like.",
    "commentary": "Sphaṭika-japākusuma-dṛṣṭānta (cf. I.58): clear jewel glows red beside hibiscus, clear alone. Buddhi-vṛttis are the flowers; puruṣa the jewel. Upādhi-proximity, never essence-mixture.",
    "keyPoints": ["Jewel reddens beside red flower.", "Proximity colors; essence untouched."]
  },
  {
    "id": "2.36",
    "number": "2.36",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "adṛṣṭavikāsāt karaṇānāṃ puruṣārthatvaṃ",
    "devanagari": "अदृष्टविकासात् करणानां पुरुषार्थत्वं",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Instruments stir toward puruṣa's ends by adṛṣṭa-unfolding.",
    "commentary": "Adṛṣṭa-vikāsa (merit's unfolding) occasions organ-activity toward bhoga/apavarga — occasions, not coerces (cf. I.30–31 adṛṣṭa-limits). Karaṇas are puruṣārtha-yantras; adṛṣṭa is the occasion-wheel.",
    "keyPoints": ["Merit occasions; purpose directs.", "Organs are puruṣa-end machines."]
  },
  {
    "id": "2.37",
    "number": "2.37",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "vatsāya dhenuvat",
    "devanagari": "वत्साय धेनुवत्",
    "conceptIds": ["prayojana-sutra"],
    "translation": "As the cow for the calf.",
    "commentary": "Kṣīra-dṛṣṭānta restated (cf. old 4.1, Kārikā 57): unconscious, spontaneous, need-fitted flow. Cow doesn't deliberate calf-nutrition; prakṛti doesn't deliberate puruṣa-release — yet both serve perfectly.",
    "keyPoints": ["Unconscious service, perfect fit.", "Need draws supply without deliberation."]
  },
  {
    "id": "2.38",
    "number": "2.38",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "trayodaśavidhaṃ karaṇam avāntarabhedāt",
    "devanagari": "त्रयोदशविधं करणम् अवान्तरभेदात्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Instruments are thirteen by sub-division.",
    "commentary": "Trayodaśa-karaṇa census (cf. Kārikā 32): 10 outer + 3 inner. Avāntara-bheda (sub-division) fixes the count against regroupers — thirteen distinct vṛtti-seats, no more, no fewer.",
    "keyPoints": ["10 + 3 = 13 instruments.", "Count fixed by function-seats."]
  },
  {
    "id": "2.39",
    "number": "2.39",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "tadāharaṇadhāraṇaprakāśakaram",
    "devanagari": "तदाहरणधारणप्रकाशकरम्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Their work: seizing, holding, illumining.",
    "commentary": "Tri-kārya (cf. Kārikā 32): karmendriyas seize-hold (āharaṇa-dhāraṇa), jñānendriyas illumine (prakāśana), antaḥkaraṇa all three inwardly. Tenfold objects (hārya-dhārya-prakāśya) match thirteen instruments.",
    "keyPoints": ["Seize, hold, illumine — three works.", "Outer present-only; inner all-times (cf. old step-10)."]
  },
  {
    "id": "2.40",
    "number": "2.40",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "pradhānaṃ manaḥ bhṛtyeṣu kaścid iva",
    "devanagari": "प्रधानं मनः भृत्येषु कश्चिद् इव",
    "conceptIds": ["tattva-sutra"],
    "translation": "Manas leads — as one man among servants.",
    "commentary": "Manas-prādhānya among outer organs: all sense-traffic passes its saṅkalpa-desk. Bhṛtya-dṛṣṭānta: servants gather, one presents to master (buddhi). First among equals, not master — buddhi decides (II.41).",
    "keyPoints": ["Manas first among servants.", "Gathers all, decides nothing finally."]
  },
  {
    "id": "2.41",
    "number": "2.41",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "buddheḥ apramoṣāt",
    "devanagari": "बुद्धेः अप्रमोषात्",
    "conceptIds": ["buddhi-sutra"],
    "translation": "Buddhi (is supreme) — for it never strays from its post.",
    "commentary": "Buddhi-prādhānya: apramoṣa (never abandoning decision-duty) — senses stray (sleep, distraction), manas wavers, ahaṅkāra claims falsely; buddhi alone ever-determines. Steadiness = supremacy.",
    "keyPoints": ["Never-off-duty decides supremacy.", "Senses sleep; buddhi persists (even in dream)."]
  },
  {
    "id": "2.42",
    "number": "2.42",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "anantasaṃskārādhāratvāc ca",
    "devanagari": "अनन्तसंस्काराधारत्वाच् च",
    "conceptIds": ["buddhi-sutra"],
    "translation": "And as receptacle of infinite impressions.",
    "commentary": "Ananta-saṃskārādhāra: every experience deposits vāsanā in buddhi across births — infinite archive. Archive = authority: what holds all past decides present. (Smṛti-hetu prepares II.43.)",
    "keyPoints": ["Infinite impression-archive.", "Archive-authority: past stored decides present."]
  },
  {
    "id": "2.43",
    "number": "2.43",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "smṛtyā cānumānāt",
    "devanagari": "स्मृत्या चानुमानात्",
    "conceptIds": ["buddhi-sutra", "pramana-sutra"],
    "translation": "And by inference from memory.",
    "commentary": "Smṛti needs sthira-ādhāra (stable seat): puruṣa is kūṭastha-witness (no impressions), senses momentary — only buddhi persists bearing saṃskāras. Memory proves buddhi's supremacy as saṃskāra-bearer.",
    "keyPoints": ["Memory needs stable bearer.", "Only buddhi bears impressions."]
  },
  {
    "id": "2.44",
    "number": "2.44",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "na puruṣāt smṛtiḥ",
    "devanagari": "न पुरुषात् स्मृतिः",
    "conceptIds": ["purusha-sutra"],
    "translation": "Memory cannot come from puruṣa.",
    "commentary": "Kūṭastha cannot store (storage = pariṇāma). Smṛti-vikāra proves non-puruṣa source — puruṣa's changelessness bars impression-theory (cf. I.146 nirguṇa). Memory's mechanics belong wholly to prakṛti-side.",
    "keyPoints": ["Changeless stores nothing.", "Memory-mechanics are prakṛti-side."]
  },
  {
    "id": "2.45",
    "number": "2.45",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "vṛttibhedād gauṇamukhyavyavasthā",
    "devanagari": "वृत्तिभेदाद् गौणमुख्यव्यवस्था",
    "conceptIds": ["tattva-sutra"],
    "translation": "Secondary/principal rank follows function-distinction.",
    "commentary": "Gauṇa-mukhya is relative (sāpekṣa): manas mukhya among getters, gauṇa before buddhi; buddhi mukhya overall yet gauṇa before puruṣa. Rank = function-scope, never absolute essence — closing the prādhānya inquiry.",
    "keyPoints": ["Rank is functional, relative.", "Every principal is someone's secondary."]
  },
  {
    "id": "2.46",
    "number": "2.46",
    "section": "Adhyāya II · Pradhāna-kārya",
    "iast": "karmakrītasya bhṛtyasya svāmihetutvavat",
    "devanagari": "कर्मक्रीतस्य भृत्यस्य स्वामिहेतुत्ववत्",
    "conceptIds": ["prayojana-sutra", "bhoga-sutra"],
    "translation": "As the purchased servant works his buyer's ends — buddhi, bought by puruṣa's karma mirrored in it, serves him.",
    "commentary": "Karmakrīta-bhṛtya-dṛṣṭānta: puruṣa's karma, reflected in buddhi, 'purchases' her service — parārtha-pravṛtti explained without coercion (cf. I.18, II.4 lots). Why THIS buddhi serves THIS puruṣa: his karma-deposit. Book II ends: mechanism complete.",
    "keyPoints": ["Karma-deposit purchases buddhi's service.", "Why this mind serves this self — answered."]
  }
];
