/**
 * Sāṅkhya-Pravacana-Sūtra, Adhyāya V · Parapakṣa (5.1–5.129) — English.
 * Demolition of counter-theories: maṅgala (1) · īśvara as creator/governor,
 * eternal, inferred, scriptural (2–7) · avidyā/saṃsāra/dharma (8–17) ·
 * perception, arthāpatti, guṇas, objective world, vyāpti (18–26) · word-object,
 * Veda's nature and authority (27–40) · world-status, sphoṭa, varṇas (41–49) ·
 * non-duality refuted, ānanda, manas (50–64) · release-nature negations (65–74) ·
 * indriyas, Vaiśeṣika/Nyāya categories, atoms, genus, sāmānya, samavāya (75–94) ·
 * motion, body, prāṇa, senses (95–113) · Self's work, puruṣas free, Brahman-word,
 * sleep, vāsanā, jīvanmukti, vegetables, bodies, buddhi, siddhis (114–129).
 */
export const samkhyaSutraEn5: any[] = [
  {
    "id": "5.1",
    "number": "5.1",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "maṅgalācaraṇaṃ śiṣṭācārāt",
    "devanagari": "मङ्गलाचरणं शिष्टाचारात्",
    "conceptIds": ["sruti-sutra"],
    "translation": "Invocatory blessing is performed — by cultured practice.",
    "commentary": "Maṅgala (p.388): śiṣṭas begin with maṅgala; śiṣṭācāra is mūla-pramāṇa for duty. Book V opens by honoring convention before demolishing errors — refutation itself begins auspiciously.",
    "keyPoints": ["Auspicious opening by cultured norm.", "Refutation begins reverently."]
  },
  {
    "id": "5.2",
    "number": "5.2",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "neśvaraḥ kartā karmaṇaiva siddheḥ",
    "devanagari": "नेश्वरः कर्ता कर्मणैव सिद्धेः",
    "conceptIds": ["ishvara-sutra"],
    "translation": "Īśvara as world-creator is unproved — karma alone explains the facts.",
    "commentary": "Kartṛtva-niṣedha (389): creation-diversity (vicitratā) is fully explained by karma-vaicitrya (cf. III.51) — positing īśvara adds nothing (gaurava). Explanatory sufficiency of karma bars creator-inference.",
    "keyPoints": ["Karma-diversity explains world-diversity.", "Creator adds nothing — barred by parsimony."]
  },
  {
    "id": "5.3",
    "number": "5.3",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na naitikartā vairāgyādeḥ aprayojanāt",
    "devanagari": "न नैतिकर्ता वैराग्यादेः अप्रयोजनात्",
    "conceptIds": ["ishvara-sutra"],
    "translation": "Nor moral governor — wantlessness bars motive.",
    "commentary": "Naitika-īśvara (390–394): governing needs prayojana (want/karuṇā?) — āpta-kāma (wantless) cannot govern; sa-kāma cannot be supreme. Moral order runs on karma-phala-niyama, needing no magistrate.",
    "keyPoints": ["Wantless cannot govern; wanting cannot reign.", "Karma-law needs no magistrate."]
  },
  {
    "id": "5.4",
    "number": "5.4",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nityaśvaraḥ apramāṇāt",
    "devanagari": "नित्यश्वरः अप्रमाणात्",
    "conceptIds": ["ishvara-sutra"],
    "translation": "No proof of an eternal Īśvara.",
    "commentary": "Nitya-īśvara (394–395): eternity needs pramāṇa — pratyakṣa fails (atīndriya), anumāna fails (no vyāpti), śabda fails (reinterpreted, I.95). Unproved-eternal is unproved, however venerable the word.",
    "keyPoints": ["Eternity-claims need proof.", "All three pramāṇas fail here."]
  },
  {
    "id": "5.5",
    "number": "5.5",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nānumānam īśvare liṅgābhāvāt",
    "devanagari": "नानुमानम् ईश्वरे लिङ्गाभावात्",
    "conceptIds": ["ishvara-sutra", "pramana-sutra"],
    "translation": "Inference of īśvara is impossible — no mark exists.",
    "commentary": "Liṅgābhāva (395–396): alleged liṅgas (world-order, Veda-authorship) prove only cetana-adhiṣṭhāna (puruṣa-plurality, cf. I.142) or buddhi-authorship. No vyāpti links order to ONE eternal maker.",
    "keyPoints": ["Order proves overseers, not one Maker.", "No pervasion links world to single God."]
  },
  {
    "id": "5.6",
    "number": "5.6",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na śabdaḥ kartari",
    "devanagari": "न शब्दः कर्तरि",
    "conceptIds": ["ishvara-sutra", "sruti-sutra"],
    "translation": "No scripture declares a Creator.",
    "commentary": "Śabda-abhāva (396–397): 'tad aikṣata' (Chāndogya VI.ii.3) read as prakṛti-pariṇāmonmukhatva (primordial urge), not divine resolve — aikṣata = īkṣaṇa-sadṛśa pariṇāma. Doubtful texts yield to nirīśvara-samanvaya (method, cf. I.95).",
    "keyPoints": ["'It saw' = urge, not resolve.", "Doubtful texts harmonized creatorlessly."]
  },
  {
    "id": "5.7",
    "number": "5.7",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "chāndogyokteḥ prakṛtiparatvam",
    "devanagari": "छान्दोग्योक्तेः प्रकृतिपरत्वम्",
    "conceptIds": ["sruti-sutra"],
    "translation": "The Chāndogya text concerns prakṛti.",
    "commentary": "VI.ii.3 decided: 'sad eva... tad aikṣata' — sat = pradhāna (existent root), īkṣaṇa = sarga-unmukhatva. Context (Uddālaka teaching substance-continuity, 'vācārambhaṇaṃ vikāro') favors material-cause reading over agent-reading.",
    "keyPoints": ["Sat = root-substance.", "'Seeing' = creation-facing urge."]
  },
  {
    "id": "5.8",
    "number": "5.8",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nāvidyā puruṣe",
    "devanagari": "नाविद्या पुरुषे",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Avidyā does not belong to puruṣa.",
    "commentary": "Avidyā-sthāna (398–400): nirguṇa-cit cannot house avidyā (guṇa/dharma); avidyā belongs to buddhi (antaḥkaraṇa-dharma, cf. I.25–26 padārtha-logic). Locus decided — Vedāntin's Brahman-avidyā barred by nirguṇatva.",
    "keyPoints": ["Attributeless cannot house ignorance.", "Ignorance lodges in buddhi."]
  },
  {
    "id": "5.9",
    "number": "5.9",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "sādiḥ saṃsāraḥ",
    "devanagari": "सादिः संसारः",
    "conceptIds": ["bandha-sutra"],
    "translation": "Saṃsāra is not beginningless (in the objector's sense) —",
    "commentary": "Sāditva-āpatti (p.399): if avidyā (binder) BEGINS (sādi), saṃsāra begins — monist's 'beginningless avidyā' questioned. Stated as pūrvapakṣa pressure; resolved: pravāha-anādi yet vyakti-sādi (stream beginningless, episodes beginning).",
    "keyPoints": ["Stream beginningless, episodes beginning.", "Binder's status decides series' status."]
  },
  {
    "id": "5.10",
    "number": "5.10",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "avidyāsvarūpaṃ buddhidharmaḥ",
    "devanagari": "अविद्यास्वरूपं बुद्धिधर्मः",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Avidyā's nature discussed: a buddhi-mode.",
    "commentary": "Avidyā-svarūpa (400–402): viparyaya-vṛtti (mistaking non-Self for Self), sānta (ending by viveka) — hence kārya (effect), hence buddhi-dharma. Nature-analysis confirms locus (V.8): ending things are produced things.",
    "keyPoints": ["Mistake-mode, ending by knowledge.", "Ending things are produced things."]
  },
  {
    "id": "5.11",
    "number": "5.11",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "tathāpi anāditvaṃ pravāhataḥ",
    "devanagari": "तथापि अनादित्वं प्रवाहतः",
    "conceptIds": ["bandha-sutra"],
    "translation": "Still, beginninglessness holds — as stream.",
    "commentary": "Pravāha-anāditva (p.403): avidyā-episodes begin/end, but avidyā-stream never began (bīja-aṅkura, cf. I.122). Both truths kept: suttas begin (sādi-vyakti), ignorance never began (anādi-pravāha).",
    "keyPoints": ["Episodes begin; stream never did.", "Seed-sprout models beginningless flow."]
  },
  {
    "id": "5.12",
    "number": "5.12",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "dharmaḥ sṛṣṭau nimittam",
    "devanagari": "धर्मः सृष्टौ निमित्तम्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Dharma is creation's occasion-cause.",
    "commentary": "Dharma-nimittatva (p.404): merit/demerit occasion (nimitta, never upādāna, cf. I.81) sarga-vaiṣamya — which lot, which body. Occasion-cause status saves karma's role without making it stuff.",
    "keyPoints": ["Merit occasions; never materializes.", "Which-lot decided by dharma."]
  },
  {
    "id": "5.13",
    "number": "5.13",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "dharmaḥ sukhahetuḥ pramāṇaiḥ",
    "devanagari": "धर्मः सुखहेतुः प्रमाणैः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Dharma is proved — pleasure follows virtue, by proofs.",
    "commentary": "Dharma-siddhi (404–405): sukha-dharma-anvaya observed (virtuous prosper), śāstra declares, arthāpatti confirms — triple proof. Dharma is real buddhi-disposition (V.17), not convention.",
    "keyPoints": ["Virtue-joy regularity observed.", "Triple proof: seen, heard, presumed."]
  },
  {
    "id": "5.14",
    "number": "5.14",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na pratyakṣam eva pramāṇam",
    "devanagari": "न प्रत्यक्षम् एव प्रमाणम्",
    "conceptIds": ["pramana-sutra"],
    "translation": "Perception is not the sole proof of existence.",
    "commentary": "Anti-Cārvāka (p.405): dharma/adharma/paramāṇu/prakṛti exist unperceived — pratyakṣa-ekānta self-refutes (its own rule unperceived). Pramāṇa-traya (I.88) reasserted in refutation-context.",
    "keyPoints": ["Unperceived reals exist.", "Perception-only refutes itself."]
  },
  {
    "id": "5.15",
    "number": "5.15",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "adharmasiddhiḥ duḥkhāt",
    "devanagari": "अधर्मसिद्धिः दुःखात्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Adharma is proved — from suffering.",
    "commentary": "Adharma-siddhi (405–406): duḥkha needs moral occasion as sukha does (symmetry); śāstra declares pāpa-phala. Suffering's moral readability presupposes adharma-reality.",
    "keyPoints": ["Suffering implies demerit.", "Moral readability needs both poles."]
  },
  {
    "id": "5.16",
    "number": "5.16",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nārthāpattiḥ dharmamāne",
    "devanagari": "नार्थापत्तिः धर्ममाने",
    "conceptIds": ["pramana-sutra"],
    "translation": "Presumption is no independent proof of dharma.",
    "commentary": "Arthāpatti-niṣedha (406–407): 'devadatta lives though unseen at home → he is out' reduces to anumāna (vyāpti-based) or śabda. No fourth pramāṇa smuggled for dharma — traya suffices (cf. I.88).",
    "keyPoints": ["Presumption reduces to inference.", "No fourth proof smuggled in."]
  },
  {
    "id": "5.17",
    "number": "5.17",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "antaḥkaraṇadharmā dharmādayaḥ",
    "devanagari": "अन्तःकरणधर्मा धर्मादयः",
    "conceptIds": ["buddhi-sutra"],
    "translation": "Dharma and the rest are inner-organ attributes.",
    "commentary": "Dharmādhikaraṇa (p.407): dharma/adharma inhere in buddhi (not ātman — nirguṇa, I.146; not body — acetana). Locus-seal: moral properties need sentient-process locus — buddhi alone qualifies.",
    "keyPoints": ["Morals inhere in buddhi.", "Neither Self (attributeless) nor body (dull)."]
  },
  {
    "id": "5.18",
    "number": "5.18",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na guṇādyatyantābhāvaḥ",
    "devanagari": "न गुणाद्यत्यन्ताभावः",
    "conceptIds": ["guna-sutra"],
    "translation": "Guṇas and the like are nowhere absolutely denied.",
    "commentary": "Atyantābhāva-niṣedha (407–409): apparent denials (śūnya-śrutis, 'neti') are context-bound (prakṛti-laya states, upāsanā). Doubtful scriptures harmonized — guṇas stand uncancelled in vyavahāra.",
    "keyPoints": ["Denials are context-bound.", "Guṇas uncancelled in practice."]
  },
  {
    "id": "5.19",
    "number": "5.19",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "pramāṇataḥ arthasiddhiḥ",
    "devanagari": "प्रमाणतः अर्थसिद्धिः",
    "conceptIds": ["pramana-sutra"],
    "translation": "Objective existence is established by proof.",
    "commentary": "Artha-siddhi (409–411): pratyakṣa (bāhyatvena pratīti, cf. I.42) + anumāna (sahacāra) + āpta-śabda converge on bāhya-artha. Idealism thrice-barred — objectivity is pramāṇa-phala, not faith.",
    "keyPoints": ["Three proofs converge on objects.", "Objectivity is proof's fruit."]
  },
  {
    "id": "5.20",
    "number": "5.20",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "naikadṛṣṭyā vyāptiḥ",
    "devanagari": "नैकदृष्ट्या व्याप्तिः",
    "conceptIds": ["pramana-sutra"],
    "translation": "Pervasion is not grasped from a single instance.",
    "commentary": "Vyāpti-prakaraṇa opens (411–412): sakṛd-darśana (once-seen concomitance) never yields necessity — bhūyo-darśana (repeated) + tarka (non-deviation reasoning) required. Induction's discipline stated.",
    "keyPoints": ["Once-seen never necessitates.", "Repetition + reasoning ground pervasion."]
  },
  {
    "id": "5.21",
    "number": "5.21",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "vyāptiḥ avinābhāvaḥ",
    "devanagari": "व्याप्तिः अविनाभावः",
    "conceptIds": ["pramana-sutra"],
    "translation": "Pervasion defined: non-separation.",
    "commentary": "Vyāpti-lakṣaṇa (412–413): avinābhāva (hetu never without sādhya) — sāhacarya-niyama. Definition guards inference's nerve (cf. I.100, I.135): without necessity, no anumāna.",
    "keyPoints": ["Never-without = pervasion.", "Necessity is inference's nerve."]
  },
  {
    "id": "5.22",
    "number": "5.22",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na tattvāntaraṃ vyāptiḥ",
    "devanagari": "न तत्त्वान्तरं व्याप्तिः",
    "conceptIds": ["pramana-sutra"],
    "translation": "Pervasion is no separate reality.",
    "commentary": "Tattvāntara-niṣedha (413–414): vyāpti is sambandha-viśeṣa (relation-mode), not new padārtha (vs Nyāya's reifications). Ontological economy: relations ride relata; need no separate seats.",
    "keyPoints": ["Relation-mode, not new entity.", "Relata carry their relations."]
  },
  {
    "id": "5.23",
    "number": "5.23",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "ācāryāṇāṃ vyāptimataṃ",
    "devanagari": "आचार्याणां व्याप्तिमतं",
    "conceptIds": ["pramana-sutra"],
    "translation": "The teachers' view on pervasion (stated).",
    "commentary": "Ācārya-mata (414–415): pūrva-ācāryas hold vyāpti as sahacāra-graha + avyabhicāra-niścaya. Stated respectfully before refinement (24–26) — siddhānta grows from sampradāya, never against it.",
    "keyPoints": ["Tradition's view honored first.", "Growth from, never against, lineage."]
  },
  {
    "id": "5.24",
    "number": "5.24",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "pañcaśikhasya ca",
    "devanagari": "पञ्चशिखस्य च",
    "conceptIds": ["pramana-sutra", "parampara-sutra"],
    "translation": "And Pañcaśikha's (view).",
    "commentary": "Pañcaśikha-mata (p.415): ādi-vidvān holds vyāpti grasped via sāmānya-lakṣaṇa (generality-perception, cf. I.103). Paramparā-citation (Kapila→Āsuri→Pañcaśikha) authorizes the refinement — lineage speaks.",
    "keyPoints": ["Pañcaśikha: generality-perception.", "Lineage authorizes refinement."]
  },
  {
    "id": "5.25",
    "number": "5.25",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na svarūpaśaktiḥ vyāptiḥ",
    "devanagari": "न स्वरूपशक्तिः व्याप्तिः",
    "conceptIds": ["pramana-sutra"],
    "translation": "Pervasion is no essence-inherent power.",
    "commentary": "Svarūpaśakti-niṣedha (415–419): vyāpti isn't smoke's 'power' (then unobservable power-entities multiply); it is observed regularity + tarka-secured necessity. Power-talk reifies; regularity-talk describes.",
    "keyPoints": ["Regularity, not hidden power.", "Description beats reification."]
  },
  {
    "id": "5.26",
    "number": "5.26",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "śabdārthasambandhaḥ",
    "devanagari": "शब्दार्थसम्बन्धः",
    "conceptIds": ["pramana-sutra"],
    "translation": "(Now) word-object relation.",
    "commentary": "Śabda-prakaraṇa opens (419–420): śabda-pramāṇa (I.101) needs śabda-artha-sambandha. Transition: inference secured (20–25), testimony's mechanics next (26–40). Order: meaning-link before Veda-claims.",
    "keyPoints": ["Testimony needs meaning-link.", "Link before Veda-claims."]
  },
  {
    "id": "5.27",
    "number": "5.27",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "saṅketād grahaḥ tatpramāṇam",
    "devanagari": "सङ्केताद् ग्रहः तत्प्रमाणम्",
    "conceptIds": ["pramana-sutra"],
    "translation": "Grasped by convention; its proofs (stated).",
    "commentary": "Saṅketa-vāda (420–421): word-meaning grasped via saṅketa (convention — āpta/śiṣṭa usage); proved by vyavahāra (successful practice), vṛddha-prayoga (elders' use), āptavākya. Convention, not nature, links sound-sense.",
    "keyPoints": ["Convention links sound-sense.", "Practice and elders prove linkage."]
  },
  {
    "id": "5.28",
    "number": "5.28",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na kriyāmātraparaḥ śabdaḥ",
    "devanagari": "न क्रियामात्रपरः शब्दः",
    "conceptIds": ["pramana-sutra"],
    "translation": "Words refer not to acts only.",
    "commentary": "Anti-Prabhākara (421–422): śabda denotes siddha (established entities) too, not kārya (to-be-done) only — else tattva-vākyas ('tat tvam asi') go mute. Siddha-para-śabda secures Vedānta-vākya meaningfulness for Sāṅkhya use.",
    "keyPoints": ["Established entities also denoted.", "Tattva-sentences stay meaningful."]
  },
  {
    "id": "5.29",
    "number": "5.29",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "vidhyarthavādamantrāṇāṃ prāmāṇyam",
    "devanagari": "विध्यर्थवादमन्त्राणां प्रामाण्यम्",
    "conceptIds": ["sruti-sutra"],
    "translation": "Injunctions, eulogies, formulas carry probative force.",
    "commentary": "Vākya-bheda (421–422): vidhi (enjoin), arthavāda (eulogize-motivate), mantra (invoke) — each pramāṇa in function. Kārya-para/akārya-para, sādhya/siddha-para distinctions organize Veda's voices without muting any.",
    "keyPoints": ["Enjoin, eulogize, invoke — all prove.", "Every Vedic voice keeps function."]
  },
  {
    "id": "5.30",
    "number": "5.30",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "laukikavaidikayoḥ tulyārthatvam",
    "devanagari": "लौकिकवैदिकयोः तुल्यार्थत्वम्",
    "conceptIds": ["sruti-sutra"],
    "translation": "Secular and scriptural (words) convey alike.",
    "commentary": "Tulyārthatva (p.423): 'gām ānaya' (bring cow) and 'agnihotraṃ juhuyāt' work by SAME śabda-śakti — Veda needs no miraculous semantics. Continuity of language secures Veda's intelligibility (and criticizability).",
    "keyPoints": ["One language, two literatures.", "Veda intelligible, hence assessable."]
  },
  {
    "id": "5.31",
    "number": "5.31",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "atīndriyārthatvaṃ cet",
    "devanagari": "अतीन्द्रियार्थत्वं चेत्",
    "conceptIds": ["sruti-sutra"],
    "translation": "'But Vedic objects are supra-sensuous' — if objected,",
    "commentary": "Pūrvapakṣa (423–424): dharma/svarga atīndriya — how can ordinary words reach them? Stated; answered (32–34): atīndriya reached via sāmānya (generality), yogi-pratyakṣa confirms possibility (I.90–91).",
    "keyPoints": ["Supra-sensuous objects challenge words.", "Generality-bridge answers."]
  },
  {
    "id": "5.32",
    "number": "5.32",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "sāmānyato gatiḥ",
    "devanagari": "सामान्यतो गतिः",
    "conceptIds": ["sruti-sutra", "pramana-sutra"],
    "translation": "Access is through generality.",
    "commentary": "Sāmānya-gati (425–426): 'svarga' understood via sukha-sāmānya (pleasure-generality) + śabda-viśeṣa. Unknowns entered through known-generals — language's ladder to atīndriya. Vedic objects not absolutely supra-sensuous.",
    "keyPoints": ["Known-generals ladder to unknowns.", "Veda's objects relatively, not absolutely, beyond."]
  },
  {
    "id": "5.33",
    "number": "5.33",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "yogidṛṣṭyā samarthanam",
    "devanagari": "योगिदृष्ट्या समर्थनम्",
    "conceptIds": ["sruti-sutra", "pramana-sutra"],
    "translation": "Confirmed by yogic vision (426).",
    "commentary": "Yogi-dṛṣṭi-samarthana: what śabda indicates generally, yogins perceive particularly (I.90–91) — closing the loop: śabda → sāmānya-bodha → yoga → sākṣātkāra. Testimony verified by higher perception, never left hanging.",
    "keyPoints": ["Testimony's check: yogic sight.", "General word, particular vision."]
  },
  {
    "id": "5.34",
    "number": "5.34",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "śabdaśaktiḥ vaidikānāṃ sahajaiva",
    "devanagari": "शब्दशक्तिः वैदिकानां सहजैव",
    "conceptIds": ["sruti-sutra"],
    "translation": "Denotative power is inherent in Vedic words.",
    "commentary": "Śakti-sahajatva (426–427): Vedic words denote by same sahaja-śakti (natural capacity fixed by saṅketa-paramparā), no miracle needed. Inherence = stability across uses — Veda's reliability is linguistic, not magical.",
    "keyPoints": ["Natural capacity, stable use.", "Reliability linguistic, not magical."]
  },
  {
    "id": "5.35",
    "number": "5.35",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "tatsiddhiḥ vyavahārataḥ",
    "devanagari": "तत्सिद्धिः व्यवहारतः",
    "conceptIds": ["sruti-sutra"],
    "translation": "Its proof: from successful practice (427).",
    "commentary": "Vyavahāra-siddhi: Vedic injunctions practiced yield declared fruits (dṛṣṭa-phala observed, adṛṣṭa trusted by parity) — practice verifies power. Pragmatic proof crowns semantic theory.",
    "keyPoints": ["Practice verifies power.", "Observed fruits ground trusted ones."]
  },
  {
    "id": "5.36",
    "number": "5.36",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na nityo vedaḥ",
    "devanagari": "न नित्यो वेदः",
    "conceptIds": ["sruti-sutra"],
    "translation": "The Veda is not eternal.",
    "commentary": "Anityatva (p.428): varṇa-krama (letter-sequence), pāṭha-bheda (recension-variants), '...iti ha' (historical references) prove producedness. Against Mīmāṁsā-nityatva — eternality would freeze meaning beyond adhikāri-bheda.",
    "keyPoints": ["Sequence, variants, history prove made-ness.", "Eternity would freeze meaning."]
  },
  {
    "id": "5.37",
    "number": "5.37",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na pauruṣeyaḥ āptoktitvāt",
    "devanagari": "न पौरुषेयः आप्तोक्तित्वात्",
    "conceptIds": ["sruti-sutra"],
    "translation": "Nor personal work — being āpta-utterance.",
    "commentary": "Apauruṣeyatva-nuance (428–429): not 'personal' (rāga-dveṣa-motivated) yet not 'eternal' — āpta-okti (seer-utterance): ṛṣis SAW (dṛṣṭa-mantras), didn't invent. Third alternative: beginningless-seer-stream, authorless-yet-voiced.",
    "keyPoints": ["Seen, not invented.", "Authorless yet voiced."]
  },
  {
    "id": "5.38",
    "number": "5.38",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "tathāpi anityatvaṃ pravāhataḥ",
    "devanagari": "तथापि अनित्यत्वं प्रवाहतः",
    "conceptIds": ["sruti-sutra"],
    "translation": "Still, non-eternity holds — as stream (430–431).",
    "commentary": "Pravāha-anityatva: Veda-stream beginningless (no first recitation) yet each recitation produced — bīja-aṅkura logic (cf. I.122, V.11). Eternity-of-flow compatible with producedness-of-drops.",
    "keyPoints": ["Beginningless stream, produced drops.", "Flow-eternal, utterance-made."]
  },
  {
    "id": "5.39",
    "number": "5.39",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "pauruṣeyārthaḥ rāgadveṣamūlatvam",
    "devanagari": "पौरुषेयार्थः रागद्वेषमूलत्वम्",
    "conceptIds": ["sruti-sutra"],
    "translation": "'Personal' means rooted in attraction-aversion (431–432).",
    "commentary": "Pauruṣeya defined: rāga-dveṣa-mūlatva (motive-taint), not mere puruṣa-utterance. Veda, being āpta (taintless), is apauruṣeya in the relevant sense — motive-purity, not authorlessness, is the point.",
    "keyPoints": ["Personal = tainted, not uttered.", "Purity, not authorlessness, matters."]
  },
  {
    "id": "5.40",
    "number": "5.40",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "svataḥprāmāṇyaṃ vedasya",
    "devanagari": "स्वतःप्रामाण्यं वेदस्य",
    "conceptIds": ["sruti-sutra"],
    "translation": "The Veda proves its own authority (432–433).",
    "commentary": "Svataḥ-prāmāṇya: Veda's tattva-declarations self-certify by phala (viveka → śānti observed in practitioners) — like medicine proved by cure. Authority earned by fruit, claimed by none, borrowed from none.",
    "keyPoints": ["Cure proves medicine.", "Fruit certifies text."]
  },
  {
    "id": "5.41",
    "number": "5.41",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "bhūyo 'pi jagatsatyatvam",
    "devanagari": "भूयो ऽपि जगत्सत्यत्वम्",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Again: the world's reality (434).",
    "commentary": "Jagat-satyatva reprise: after securing śabda (26–40), objectivity re-secured against subtler idealisms — bhrama-objects (42), neither-real-nor-unreal (43–44), pratibimba (45), sad-asad (46). Seven-sūtra idealism-siege (41–47).",
    "keyPoints": ["Objectivity re-secured post-śabda.", "Subtler idealisms next."]
  },
  {
    "id": "5.42",
    "number": "5.42",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "bhramaviṣayo 'tyantāsan na",
    "devanagari": "भ्रमविषयो ऽत्यन्तासन् न",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Illusion's object is not absolutely non-existent.",
    "commentary": "Bhrama-viṣaya (p.434): rope-snake's 'snake' has pratibhāsika-being (appearance-being) — enough to frighten. Absolute-non-being (vandhyā-putra) frightens none. Error needs apparent object — sat-khyāti-adjacent realism.",
    "keyPoints": ["Snake frightens; barren-son's son doesn't.", "Error needs apparent being."]
  },
  {
    "id": "5.43",
    "number": "5.43",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nātyantāsat jagat",
    "devanagari": "नात्यन्तासत् जगत्",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Nor is the world absolutely real (434–435) —",
    "commentary": "Concession-with-limits: vyāvahārika (practical) reality granted, pāramārthika (ultimate, kūṭastha) denied to pariṇāmin-world. Two-truth economy without void: real-as-changing, unreal-as-eternal. Precision, not paradox.",
    "keyPoints": ["Real-as-changing; unreal-as-eternal.", "Two truths without void."]
  },
  {
    "id": "5.44",
    "number": "5.44",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na sadasadvilakṣaṇam",
    "devanagari": "न सदसद्विलक्षणम्",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "The world is nothing other than real-and-unreal (435–437) — no third.",
    "commentary": "Sadasadvilakṣaṇa-niṣedha (cf. I.23–24): world = sat (as prakṛti-pariṇāma) + asat (as kūṭastha-ātman-denied). Third category barred — observation knows being and non-being only. Anirvacanīya rejected again.",
    "keyPoints": ["Real-as-change, unreal-as-eternal.", "No third ontological slot."]
  },
  {
    "id": "5.45",
    "number": "5.45",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na pratibimbamātram",
    "devanagari": "न प्रतिबिम्बमात्रम्",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Nor is the world mere reflection of another (437–438).",
    "commentary": "Pratibimba-vāda barred: reflection needs original + medium + seer — positing Brahman-original explains nothing (who sees? where medium?). Reflection-theory multiplies entities beyond Sāṅkhya's two-plus-products.",
    "keyPoints": ["Reflection needs original, medium, seer.", "Two-plus-products suffice."]
  },
  {
    "id": "5.46",
    "number": "5.46",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "sadasadrūpaṃ viśvam",
    "devanagari": "सदसद्रूपं विश्वम्",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "The universe is existent-and-non-existent-formed (439–440).",
    "commentary": "Sadasad-rūpa seal: sat (pariṇāmi-prakṛti side) + asat (kūṭastha-denial side) — world's double form stated positively. Realism-with-degrees replaces both monisms (Advaita's vivarta, Bauddha's śūnya).",
    "keyPoints": ["Double-formed, precisely.", "Degrees replace denials."]
  },
  {
    "id": "5.47",
    "number": "5.47",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "sphoṭaniṣedhaḥ",
    "devanagari": "स्फोटनिषेधः",
    "conceptIds": ["pramana-sutra"],
    "translation": "Sphoṭa refuted (441–442).",
    "commentary": "Sphoṭa (burst-meaning-whole) barred: varṇas + krama suffice for meaning (cf. V.48); positing partless-whole violates lāghava and fails to explain learning (children learn letters, not bursts). Mīmāṁsaka-Vaiyākaraṇa doctrine declined.",
    "keyPoints": ["Letters + order suffice.", "Children learn letters, not bursts."]
  },
  {
    "id": "5.48",
    "number": "5.48",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "anityā varṇāḥ",
    "devanagari": "अनित्या वर्णाः",
    "conceptIds": ["pramana-sutra"],
    "translation": "Letters are non-eternal (442).",
    "commentary": "Varṇa-anityatva: uttered-heard-perishing observed; recognition (same 'ka') is jāti-recognition, not vyakti-permanence (cf. I.35 pratyabhijñā distinguished). Eternity-of-sound (Mīmāṁsā) falls to ears' evidence.",
    "keyPoints": ["Uttered perishes; type recurs.", "Recognition proves type, not token-eternity."]
  },
  {
    "id": "5.49",
    "number": "5.49",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "tatra samādhānam uktam",
    "devanagari": "तत्र समाधानम् उक्तम्",
    "conceptIds": ["pramana-sutra"],
    "translation": "Objection answered (442–443).",
    "commentary": "'If letters perish, how fixed meanings?' — saṃskāra-santāna (impression-series in śiṣya-paramparā, cf. V.38 pravāha) fixes usage. Continuity-of-use, not eternity-of-sound, stabilizes language.",
    "keyPoints": ["Usage-series stabilizes meaning.", "Tradition, not eternity, fixes words."]
  },
  {
    "id": "5.50",
    "number": "5.50",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "advaitakhaṇḍanam",
    "devanagari": "अद्वैतखण्डनम्",
    "conceptIds": ["purusha-sutra", "parapaksa-sutra"],
    "translation": "Non-duality refuted (444–445).",
    "commentary": "Advaita-khaṇḍana opens (50–54): eka-ātman contradicts vyavasthā (cf. I.149–154, III.68), upādhi fails (I.151), śruti-plurality stands (VI.44). Book V's center: plurality re-armed against Vedānta after securing pramāṇas.",
    "keyPoints": ["Distribution refutes oneness.", "Plurality re-armed."]
  },
  {
    "id": "5.51",
    "number": "5.51",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "ātmānātmanaikyaṃ pratyakṣaviruddham",
    "devanagari": "आत्मानात्मनैक्यं प्रत्यक्षविरुद्धम्",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Self/non-Self unity contradicts perception (445–446).",
    "commentary": "Pratyakṣa-virodha: 'I' vs 'this' given as opposed in every cognition — unity asserts against presentation (cf. I.42 method). Bādhaka-less bheda-pratīti stands; abheda needs proof it lacks.",
    "keyPoints": ["'I' vs 'this' given opposed.", "Unity asserts against presentation."]
  },
  {
    "id": "5.52",
    "number": "5.52",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "abhedaśrutīnāṃ samanvayaḥ",
    "devanagari": "अभेदश्रुतीनां समन्वयः",
    "conceptIds": ["sruti-sutra"],
    "translation": "Non-duality śrutis harmonized (446–447).",
    "commentary": "'Tat tvam asi' etc. read as sādṛśya (likeness: uniform consciousness, cf. I.160 ekarūpa) or lakṣaṇā (secondary). Primary sense impossible per vyavasthā (V.50) — samanvaya-method again (cf. I.95, I.147, III.69).",
    "keyPoints": ["'Thou art That' = likeness of nature.", "Uniformity, not unity."]
  },
  {
    "id": "5.53",
    "number": "5.53",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "advaita upādānaṃ na",
    "devanagari": "अद्वैत उपादानं न",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "On non-duality, no material cause of the world (447–449).",
    "commentary": "Upādāna-āpatti: nirguṇa-Brahman cannot be pariṇāmi-upādāna (changeless can't stuff change); māyā-upādāna makes world māyika (unreal — then bondage unreal, śāstra void). Non-dualism strands creation either way.",
    "keyPoints": ["Changeless can't stuff change.", "Māyā-stuff makes bondage unreal."]
  },
  {
    "id": "5.54",
    "number": "5.54",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "sāṅkhyavedāntayoḥ bhedaḥ chadmaśākhā ca",
    "devanagari": "साङ्ख्यवेदान्तयोः भेदः छद्मशाखा च",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Sāṅkhya and Vedānta distinguished; pseudo-Vedāntins condemned (448–449).",
    "commentary": "Bheda + chadma-nindā: authentic Vedānta (Bādarāyaṇa: bahutva-sūtras III.ii.33 etc., cf. I.152) agrees with Sāṅkhya plurality; 'neo-Vedāntins' (māyāvādins) are 'Bauddhas in disguise' (prakchanna-bauddha charge). Lineage-war declared.",
    "keyPoints": ["Bādarāyaṇa agrees with plurality.", "'Neo' non-dualists are disguised Buddhists."]
  },
  {
    "id": "5.55",
    "number": "5.55",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nānanda ātmā",
    "devanagari": "नानन्द आत्मा",
    "conceptIds": ["purusha-sutra"],
    "translation": "The Self is not bliss (449–452).",
    "commentary": "Ānanda-niṣedha: ānanda is vṛtti (sāttvika-buddhi state, cf. II.14 bhāvas) — Self is vṛtti-sākṣī, never vṛtti. 'Ānandamaya' read as prācurya (abundance-near, Taittirīya's kośa-ladder), not svarūpa. Bliss belongs to equipment.",
    "keyPoints": ["Bliss is sattva-state, not Self.", "'Made-of-bliss' means bliss-abounding sheath."]
  },
  {
    "id": "5.56",
    "number": "5.56",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "virodhiśrutīnāṃ nirṇayaḥ yuktisthaḥ",
    "devanagari": "विरोधिश्रुतीनां निर्णयः युक्तिस्थः",
    "conceptIds": ["sruti-sutra"],
    "translation": "Conflicting śrutis decided; reasoning stands (452).",
    "commentary": "Nirṇaya-nyāya: where śrutis conflict (nirguṇa vs saguṇa-ānanda), yukti (vyavasthā, pramāṇa-traya) adjudicates — reason is śruti's interpreter, never rival (cf. I.98 tattva-rūpaṇa). Place of reasoning fixed: hermeneutic, not autonomous.",
    "keyPoints": ["Reason interprets, never rivals.", "Adjudication by coherence."]
  },
  {
    "id": "5.57",
    "number": "5.57",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "ānandaśrutiḥ gauṇī",
    "devanagari": "आनन्दश्रुतिः गौणी",
    "conceptIds": ["sruti-sutra"],
    "translation": "Ānanda-śruti is secondary (452–453).",
    "commentary": "Gauṇatva: 'ānando brahma' = ānanda-prācurya/anukūlatva (favorable association) — lakṣaṇā, since mukhya clashes nirguṇa-śruti (V.56 rule applied). Purpose (V.58): pravṛtti-janana (inducing practice) + brahmānanda-sādṛśya-sūcana.",
    "keyPoints": ["Secondary sense: bliss-associated.", "Induces practice; hints likeness."]
  },
  {
    "id": "5.58",
    "number": "5.58",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "gauṇyāḥ prayojanaṃ pravṛttiḥ",
    "devanagari": "गौण्याः प्रयोजनं प्रवृत्तिः",
    "conceptIds": ["sruti-sutra"],
    "translation": "Secondary texts' purpose: engagement (453–454).",
    "commentary": "Gauṇī-prayojana: arthavāda-like, ānanda-texts draw mumukṣus toward sādhanā (cf. V.29 arthavāda-function). Means-texts motivate; tattva-texts inform — genre decides sense. Hermeneutic maturity sealed.",
    "keyPoints": ["Motivate vs inform distinguished.", "Genre decides sense."]
  },
  {
    "id": "5.59",
    "number": "5.59",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na vibhu manaḥ",
    "devanagari": "न विभु मनः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Manas is not all-pervading (454).",
    "commentary": "Vibhutva-niṣedha (vs Nyāya-Vaiśeṣika): all-pervading mind would cognize all always (atiprasakti); observed selectivity (yugapad-jñāna-abhāva — no simultaneous omniscience) refutes. Aṇu-manas (cf. III.14 liṅga-aṇutva) suffices.",
    "keyPoints": ["All-pervading would know all always.", "Selectivity proves atomicity."]
  },
  {
    "id": "5.60",
    "number": "5.60",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "tadupapattiḥ yugapadgrahaṇābhāvāt",
    "devanagari": "तदुपपत्तिः युगपद्ग्रहणाभावात्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Proof: no simultaneous apprehension (455).",
    "commentary": "Yugapad-grahaṇābhāva: we never cognize all contacts at once (cf. II.32 krama) — vibhu-manas would. Attention's seriality evidences aṇu-manas shuttling (āśu-sañcāra). Phenomenology proves metaphysics.",
    "keyPoints": ["Serial attention evidences atomic mind.", "We never know everything at once."]
  },
  {
    "id": "5.61",
    "number": "5.61",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na niravayavaṃ manaḥ",
    "devanagari": "न निरवयवं मनः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Manas is not partless (455–456).",
    "commentary": "Sāvayavatva: manas acts diversely (saṅkalpa-vikalpa-smṛti), contacts successive objects — partless cannot diversify function. Sāvayava-yet-aṇu (atomic-composite, like paramāṇu-dvyaṇuka logic inverted) — subtle composition.",
    "keyPoints": ["Diverse acts need diverse seats.", "Atomic yet composite."]
  },
  {
    "id": "5.62",
    "number": "5.62",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nityānityavastuvivekaḥ",
    "devanagari": "नित्यानित्यवस्तुविवेकः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Eternal/non-eternal objects distinguished (456).",
    "commentary": "Nitya-anitya-viveka: puruṣa-prakṛti (nitya) vs vyakta (anitya, cf. I.124–125). Criterion: kāraṇa-apekṣā (needing cause) vs tannirapekṣatva. Discrimination's object-list finalized for practice (cf. old 3.4 tattvābhyāsa).",
    "keyPoints": ["Needing-cause vs needing-none.", "Object-list for discrimination finalized."]
  },
  {
    "id": "5.63",
    "number": "5.63",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nityatvaṃ prakṛtipuruṣayoḥ",
    "devanagari": "नित्यत्वं प्रकृतिपुरुषयोः",
    "conceptIds": ["tattva-sutra", "purusha-sutra"],
    "translation": "Eternality of prakṛti and puruṣa defended (456–457).",
    "commentary": "Nityatva-rakṣā: prakṛti (akārya-mūla, cf. I.67) + puruṣa (akārya-cit, cf. I.146) — the only two uncaused (cf. I.129). Attacks (kṣaṇika I.34ff, śūnya I.43ff) already repelled; eternity stands doubly-guarded.",
    "keyPoints": ["Two uncaused, two eternals.", "Attacks already repelled stand repelled."]
  },
  {
    "id": "5.64",
    "number": "5.64",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "śvetāśvatara-caturtha-daśama-samanvayaḥ",
    "devanagari": "श्वेताश्वतरचतुर्थदशमसमन्वयः",
    "conceptIds": ["sruti-sutra"],
    "translation": "Śvetāśvatara IV.10 harmonized (457).",
    "commentary": "'Māyāṃ tu prakṛtiṃ...' read as prakṛti-paratva (prakṛti's glory), not māyā-mithyātva — māyā = vicitra-śakti (wondrous power). Samanvaya again (method V.52, I.95): māyā-words praise power, never unreality.",
    "keyPoints": ["Māyā = wondrous power.", "Praise, not unreality."]
  },
  {
    "id": "5.65",
    "number": "5.65",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na mokṣa ānandāvirbhāvaḥ",
    "devanagari": "न मोक्ष आनन्दाविर्भावः",
    "conceptIds": ["mukti-sutra"],
    "translation": "Release is not bliss-manifestation (457–458).",
    "commentary": "Mokṣa-svarūpa-vicāra opens (65–74, ten negations): ānanda-āvirbhāva would make mokṣa kārya (produced → perishable, cf. I.82). Manifestation-talk smuggles production; kaivalya is svarūpa-sthiti (cf. III.70), never event.",
    "keyPoints": ["Manifestation implies production.", "Release is standing, not event."]
  },
  {
    "id": "5.66",
    "number": "5.66",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na viśeṣaguṇocchedaḥ",
    "devanagari": "न विशेषगुणोच्छेदः",
    "conceptIds": ["mukti-sutra"],
    "translation": "Nor elimination of particular qualities (458–459).",
    "commentary": "Vs Nyāya (apavarga = duḥkha-dhvaṃsa plus guṇoccheda): eliminating qualities leaves śūnya-ātman (cf. V.69–70) — and guṇas belong to buddhi, never ātman (cf. I.146), so 'their' elimination can't BE His release.",
    "keyPoints": ["Qualities belong to buddhi.", "Eliminating another's traits frees none."]
  },
  {
    "id": "5.67",
    "number": "5.67",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na lokaprāptiḥ",
    "devanagari": "न लोकप्राप्तिः",
    "conceptIds": ["mukti-sutra"],
    "translation": "Nor attainment of worlds (459–460).",
    "commentary": "Loka-prāpti (heaven/brahmaloka as mokṣa) barred: prāpta = deśa-bound = parimita = kṣayi (cf. I.6, I.82, III.52). Attainment-language suits sarga, never kaivalya — arrival implies departure-later.",
    "keyPoints": ["Attained worlds end.", "Arrival implies later departure."]
  },
  {
    "id": "5.68",
    "number": "5.68",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na viṣayasaṃyogocchedaḥ",
    "devanagari": "न विषयसंयोगोच्छेदः",
    "conceptIds": ["mukti-sutra"],
    "translation": "Nor mere disconnection from objects (460).",
    "commentary": "Viṣaya-viyoga (sleep-like withdrawal, pralaya, yogic suppression) ≠ mokṣa: connection resumes (cf. III.55 punarutthāna). Mere pause differs from aviveka-dāha — suspension vs solution.",
    "keyPoints": ["Pause resumes; solution ends.", "Withdrawal without wisdom returns."]
  },
  {
    "id": "5.69",
    "number": "5.69",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nātmanāśaḥ",
    "devanagari": "नात्मनाशः",
    "conceptIds": ["mukti-sutra"],
    "translation": "Total Self-extinction is not release (460–461).",
    "commentary": "Ātma-nāśa (Bauddha-charge answered + Cārvāka): extinction can't be puruṣārtha (cf. I.47) — none seeks his own void as 'good.' Seeker survives seeking's end; mokṣa is seeker's rest, never seeker's murder.",
    "keyPoints": ["None seeks self-murder as good.", "Rest of seeker, never murder."]
  },
  {
    "id": "5.70",
    "number": "5.70",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na śūnyam",
    "devanagari": "न शून्यम्",
    "conceptIds": ["mukti-sutra", "parapaksa-sutra"],
    "translation": "The void is not release (461).",
    "commentary": "Śūnya-mokṣa barred (cf. I.43–47): void can't be desired, attained, or distinguished from pre-existing void — sādhanā for śūnya is performative contradiction. Ten-negation midpoint; positives (III.70) already secured.",
    "keyPoints": ["Undesirable, unattainable, indistinguishable.", "Void-release is performative contradiction."]
  },
  {
    "id": "5.71",
    "number": "5.71",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na bhogyaviśeṣaprāptiḥ",
    "devanagari": "न भोग्यविशेषप्राप्तिः",
    "conceptIds": ["mukti-sutra"],
    "translation": "Nor possession of excellent enjoyables (462).",
    "commentary": "Bhogyaprāpti (divine objects, nandana-joys) = bhoga-crown (cf. IV.31 aiśvarya < mokṣa). Possession presumes possessor-need; kaivalya needs nothing — having is bhoga-mode, being-free is mokṣa-mode.",
    "keyPoints": ["Having is bhoga-mode.", "Needing nothing is freedom-mode."]
  },
  {
    "id": "5.72",
    "number": "5.72",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na jīvabrahmaikyam",
    "devanagari": "न जीवब्रह्मैक्यम्",
    "conceptIds": ["mukti-sutra", "parapaksa-sutra"],
    "translation": "Nor jīva-merger into Brahman (462–463).",
    "commentary": "Sāyujya-laya barred: merger presumes pre-division (unproved, cf. V.50–54) and ends the merger-experiencer (cf. V.69). Sāṅkhya kaivalya keeps witness distinct — isolation, not absorption (cf. III.70).",
    "keyPoints": ["Merger presumes unproved division.", "Isolation, not absorption."]
  },
  {
    "id": "5.73",
    "number": "5.73",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na siddhiprāptiḥ",
    "devanagari": "न सिद्धिप्राप्तिः",
    "conceptIds": ["mukti-sutra"],
    "translation": "Nor acquisition of powers (463).",
    "commentary": "Siddhi-prāpti (aṇimā-ādi) = aiśvarya-bhāva (cf. old 3.1–3.2: aiśvarya removes obstruction, never bondage). Powers adorn saṃsāra; never exit it — Rāvaṇa with siddhis stayed bound. Ten-negation nears close.",
    "keyPoints": ["Powers adorn bondage.", "Adorned cage stays cage."]
  },
  {
    "id": "5.74",
    "number": "5.74",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na paraiśvaryam",
    "devanagari": "न परैश्वर्यम्",
    "conceptIds": ["mukti-sutra", "ishvara-sutra"],
    "translation": "Nor supreme lordship (463–464).",
    "commentary": "Paraiśvarya (becoming Īśvara) barred doubly: īśvara unproved (V.2–7), and lordship is aiśvarya-maxima — still bhoga-mode (cf. V.73). Ruling worlds ≠ freedom from worlds. Ten negations complete (65–74).",
    "keyPoints": ["Ruling worlds ≠ free of worlds.", "Lordship is maximal bondage-luxury."]
  },
  {
    "id": "5.75",
    "number": "5.75",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na bhautikānīndriyāṇi",
    "devanagari": "न भौतिकानीन्द्रियाणि",
    "conceptIds": ["tattva-sutra"],
    "translation": "Senses are not elemental products (464).",
    "commentary": "Indriya-prakaraṇa opens (75–113): bhautikatva barred (cf. II.20–22, restated for Vaiśeṣika opponents) — senses withdraw Godward (devatā-laya), function subtly (atīndriya), outlive gross decay. Elementalism fails phenomenology.",
    "keyPoints": ["Godward withdrawal bars earth-origin.", "Subtle function bars gross stuff."]
  },
  {
    "id": "5.76",
    "number": "5.76",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na ṣaṭpadārthajñānān mokṣaḥ",
    "devanagari": "न षट्पदार्थज्ञानान् मोक्षः",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Release comes not through knowing six predicables (465–466).",
    "commentary": "Vs Vaiśeṣika soteriology (tattva-jñānān niḥśreyasa): dravya-ādi categories are kalpita (cf. I.25–26) — knowing fictions frees none. Only vyakta-avyakta-jña-vijñāna (I.4) liberates; padārtha-lists distract.",
    "keyPoints": ["Knowing fictions frees none.", "Only three-knowables knowledge liberates."]
  },
  {
    "id": "5.77",
    "number": "5.77",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na ṣoḍaśapadārthajñānād api",
    "devanagari": "न षोडशपदार्थज्ञानाद् अपि",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Nor through sixteen Nyāya predicables (466–468).",
    "commentary": "Vs Nyāya (pramāṇa-ādi-ṣoḍaśa-tattva-jñāna → apavarga): Nyāya's list mixes pramāṇa (means) with prameya (ends) and misses prakṛti-puruṣa-viveka entirely. Right list, wrong inventory — liberation needs Sāṅkhya's twenty-five, not Gautama's sixteen.",
    "keyPoints": ["Means mixed with ends.", "Missing the liberating distinction."]
  },
  {
    "id": "5.78",
    "number": "5.78",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nāṇavaḥ nityāḥ",
    "devanagari": "नाणवः नित्याः",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Atoms are not eternal (469–470).",
    "commentary": "Paramāṇu-nityatva-khaṇḍana: mūrtatva (formedness, cf. I.50) entails sāvayavatva → ādyantavattva. Eternal-parted is contradiction; partless-yet-productive (dvyaṇuka) is miracle. Śruti against (V.79) + Manu I.27 cited.",
    "keyPoints": ["Formed entails parted entails ending.", "Eternal-parted is contradiction."]
  },
  {
    "id": "5.79",
    "number": "5.79",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "śrutirmanusamhitā ca viruddhā",
    "devanagari": "श्रुतिर्मनुसम्हिता च विरुद्धा",
    "conceptIds": ["sruti-sutra"],
    "translation": "Śruti opposes them; Manu I.27 quoted (469).",
    "commentary": "'...tanmātrāṇy...' — Manu derives creation from tanmātras/avyakta, never atoms. Śruti-smṛti-parigraha: tradition's cosmology is Sāṅkhya's (sūkṣma→sthūla), never Vaiśeṣika's (atom-piling). Textual front opened.",
    "keyPoints": ["Manu: subtle-to-gross, never atom-piling.", "Tradition sides with Sāṅkhya cosmology."]
  },
  {
    "id": "5.80",
    "number": "5.80",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na niravayavā aṇavaḥ",
    "devanagari": "न निरवयवा अणवः",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Atoms are not partless (470).",
    "commentary": "Niravayavatva-niṣedha: partless cannot combine (saṃyoga needs avayava-contact-surfaces; partless contact = identity, no pile). Dvyaṇuka-formation itself testifies atomic complexity. Combination evidences composition.",
    "keyPoints": ["Partless cannot touch-without-merging.", "Piling testifies parts."]
  },
  {
    "id": "5.81",
    "number": "5.81",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "tanmātrāṇi eva aṇubhāgāḥ",
    "devanagari": "तन्मात्राणि एव अणुभागाः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Tanmātras are the atoms' (true) parts (479).",
    "commentary": "Tanmātra-bhāgatva: analysts reaching 'atoms' stop arbitrarily — resolution continues to tanmātras (subtle potentials, cf. I.62). True simples are aviśeṣa-potentials, never mūrtas. Analysis ends at subtle, not small.",
    "keyPoints": ["Resolution continues past atoms.", "True simples are potentials, not particles."]
  },
  {
    "id": "5.82",
    "number": "5.82",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "cākṣuṣapratyakṣavādaḥ dūṣitaḥ",
    "devanagari": "चाक्षुषप्रत्यक्षवादः दूषितः",
    "conceptIds": ["pramana-sutra"],
    "translation": "Vaiśeṣika visual-perception theory criticized (471).",
    "commentary": "Cākṣuṣa-khaṇḍana: mahat-trayeṇu? — visibility-threshold theory (triads visible, dyads not) arbitrary: why three, not two/four? Thresholds describe, never explain. Dṛṣṭi-bheda follows upādhi-bheda (buddhi), not size-arithmetic.",
    "keyPoints": ["Why three, not two?", "Thresholds describe; minds explain."]
  },
  {
    "id": "5.83",
    "number": "5.83",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na caturvidhaṃ mahattvam",
    "devanagari": "न चतुर्विधं महत्त्वम्",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Magnitude is not fourfold (471–472).",
    "commentary": "Parimāṇa-cātuṣṭaya (aṇu/mahat/dīrgha/hrasva as absolutes) barred: magnitude is sva-apekṣa (relative) — mountain-atomic vs atom, atomic vs mountain. Absolutes of size ignore observer-relativity; Sāṅkhya's parimita (I.76, I.130) is relational.",
    "keyPoints": ["Size is relative.", "Absolutes ignore observers."]
  },
  {
    "id": "5.84",
    "number": "5.84",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nityasāmānyakhaṇḍanam",
    "devanagari": "नित्यसामान्यखण्डनम्",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Eternal genus criticized (472–473).",
    "commentary": "Nitya-sāmānya (Vaiśeṣika jāti as eternal entity) barred: jāti neither perceived apart from vyaktis nor needed beyond buddhi-pratyaya (recognition-habit). Entities beyond necessity barred (lāghava, cf. V.2 parsimony).",
    "keyPoints": ["Genus never seen apart.", "Recognition-habit suffices."]
  },
  {
    "id": "5.85",
    "number": "5.85",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "sāmānyam asti buddhirūpam",
    "devanagari": "सामान्यम् अस्ति बुद्धिरूपम्",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Genus exists — as buddhi-form (473–474).",
    "commentary": "Sāmānya-rakṣā (anti-Bauddha apoha-only): common-cognition (gotva-pratyaya) is real buddhi-vṛtti — genus EXISTS as pratyaya-viṣaya (cognition-content), never as dravya (substance). Middle path: pratyaya-sat, dravya-asat.",
    "keyPoints": ["Real as cognition-content.", "Unreal as separate substance."]
  },
  {
    "id": "5.86",
    "number": "5.86",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na niṣedharūpaṃ sāmānyam",
    "devanagari": "न निषेधरूपं सामान्यम्",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Genus is no negative concept (474–475).",
    "commentary": "Vs apoha (exclusion-only universals): 'cow' means cow-presence, not merely non-non-cow — positive pratīti needs positive viṣaya (cf. I.42 method). Double-negation never yields first-affirmation content.",
    "keyPoints": ["'Cow' presents cow, not non-non-cow.", "Positives need positive contents."]
  },
  {
    "id": "5.87",
    "number": "5.87",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na pṛthaktattvaṃ sādṛśyam",
    "devanagari": "न पृथक्तत्त्वं सादृश्यम्",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Similarity is no separate reality (475).",
    "commentary": "Sādṛśya (Nyāya's upamāna-ground, Mīmāṁsā's sādṛśya-pramāṇa?) barred as tattvāntara: similarity = guṇa-sāmya-perception (cf. I.131), reducible to sāmānya-pratyaya + bheda-pratyaya conjunction. No new slot needed.",
    "keyPoints": ["Similarity = shared-quality sight.", "Reduces to genus + difference."]
  },
  {
    "id": "5.88",
    "number": "5.88",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na vastusvabhāvaśaktiḥ",
    "devanagari": "न वस्तुस्वभावशक्तिः",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Nor inherent power of things (476).",
    "commentary": "Svarūpaśakti-niṣedha (cf. V.25 vyāpti): positing occult 'similarity-powers' explains nothing — śakti = unmanifest kārya (cf. I.117), and unmanifest needs no further power behind it. Powers collapse into satkārya.",
    "keyPoints": ["Occult powers explain nothing.", "Power is unmanifest effect."]
  },
  {
    "id": "5.89",
    "number": "5.89",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na nāma-artha-sambandhaḥ",
    "devanagari": "न नामअर्थसम्बन्धः",
    "conceptIds": ["pramana-sutra"],
    "translation": "It is not name-thing relation (476–477) —",
    "commentary": "Nāma-artha as separate tattva barred: relation is saṅketa (convention, cf. V.27), not vastu. 'It' (sādṛśya-śakti debate continued): similarity isn't grounded in eternal name-thing links — links are made, not found.",
    "keyPoints": ["Links made, not found.", "Convention, not essence, joins names."]
  },
  {
    "id": "5.90",
    "number": "5.90",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "anityatvāt sambandhasya",
    "devanagari": "अनित्यत्वात् सम्बन्धस्य",
    "conceptIds": ["pramana-sutra"],
    "translation": "Because relations are non-eternal (477).",
    "commentary": "Sambandha-anityatva: usages begin/end (new words, dead languages) — eternal links would freeze lexicons. Observed language-change proves relation-made-ness. Heraclitus of semantics: all usages flow.",
    "keyPoints": ["Languages change; links begin.", "Flow proves made-ness."]
  },
  {
    "id": "5.91",
    "number": "5.91",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nānāditvam",
    "devanagari": "नानादित्वम्",
    "conceptIds": ["pramana-sutra"],
    "translation": "Nor from eternity (477–478).",
    "commentary": "Anāditva-niṣedha for links: beginningless-usage ≠ eternal-link (cf. V.11 pravāha-logic reversed: stream-patterns persist, tokens begin). Usage-stream beginningless, each link dated. Precision on 'eternal language' claims.",
    "keyPoints": ["Stream old; links dated.", "Beginningless use, produced links."]
  },
  {
    "id": "5.92",
    "number": "5.92",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na samavāyaḥ",
    "devanagari": "न समवायः",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Vaiśeṣika inherence does not exist (478–479).",
    "commentary": "Samavāya-khaṇḍana: 'inseparable relation' relating inseparables is word without work — if relata can't separate, no relation needed; if they can, saṃyoga suffices. Relation-between-inseparables is pseudo-category (cf. I.25–26).",
    "keyPoints": ["Inseparables need no relator.", "Separables use conjunction."]
  },
  {
    "id": "5.93",
    "number": "5.93",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "apramāṇatvāt",
    "devanagari": "अप्रमाणत्वात्",
    "conceptIds": ["parapaksa-sutra", "pramana-sutra"],
    "translation": "For no proof (479–480).",
    "commentary": "Pramāṇābhāva: samavāya perceived never (no separate percept), inferred never (no vyāpti), heard never (no āpta-vacana). Triple-absence seals V.92 — padārtha without pramāṇa is padārtha without passport.",
    "keyPoints": ["Never seen, inferred, or heard.", "No proof, no category."]
  },
  {
    "id": "5.94",
    "number": "5.94",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "aniruddhavyākhyā dūṣitā",
    "devanagari": "अनिरुद्धव्याख्या दूषिता",
    "conceptIds": ["parampara-sutra"],
    "translation": "Aniruddha's reading criticized here (480).",
    "commentary": "Sva-sampradāya-śodhana: even Aniruddha's gloss corrected where it strains sūtra-śabda — Vijñāna/Mahādeva refine. Intellectual honesty modeled: paramparā self-corrects; reverence never suspends nyāya.",
    "keyPoints": ["Lineage corrects itself.", "Reverence never suspends logic."]
  },
  {
    "id": "5.95",
    "number": "5.95",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "gatiḥ pratyakṣāpi",
    "devanagari": "गतिः प्रत्यक्षापि",
    "conceptIds": ["tattva-sutra"],
    "translation": "Motion is perceptible too (481–482).",
    "commentary": "Gati-pratyakṣatva (vs 'inferred-only' motion): successive positions grasped + saṃskāra-linkage = perceived motion. Stroboscope of senses: discrete grasps, continuous percept — motion seen, not merely concluded.",
    "keyPoints": ["Successive grasps yield motion-seen.", "Discrete takes, continuous percept."]
  },
  {
    "id": "5.96",
    "number": "5.96",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na pañcabhautikaṃ śarīram",
    "devanagari": "न पञ्चभौतिकं शरीरम्",
    "conceptIds": ["linga-sutra"],
    "translation": "The body is not five-elemental (482–483) —",
    "commentary": "Objection-stage (96–98 form adhikaraṇa): five-element body challenged — observed bodies show one-element dominance (plants≈earth-water?). Stated to be resolved: dominance (prādhānya) ≠ exclusivity; pañca-bhautikatva stands qualified (cf. III.17–19).",
    "keyPoints": ["Dominance-observation stated.", "Dominance ≠ exclusivity — resolution next."]
  },
  {
    "id": "5.97",
    "number": "5.97",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "ekabhautikatvadarśanāt",
    "devanagari": "एकभौतिकत्वदर्शनात्",
    "conceptIds": ["linga-sutra"],
    "translation": "One-elementality is observed (483).",
    "commentary": "Ekabhautikatva-darśana: analysis reduces bodies toward single stuffs (ash→earth). Observation noted; inference to exclusivity barred (V.96 logic): reduction-endpoint is tanmātra (cf. V.81), never one bhūta.",
    "keyPoints": ["Analysis tends single.", "Endpoint is subtle, not single-gross."]
  },
  {
    "id": "5.98",
    "number": "5.98",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na niyamaḥ sthūlatvasya",
    "devanagari": "न नियमः स्थूलत्वस्य",
    "conceptIds": ["linga-sutra"],
    "translation": "Grossness is no fixed rule for bodies (483–485).",
    "commentary": "Sthaulya-aniyama: deva/liṅga/ativāhika bodies are sūkṣma yet śarīra (function: bhogāyatana, not size). Śarīra-lakṣaṇa = bhoga-sthāna (experience-seat), never sthūlatva. Size-fetish corrected.",
    "keyPoints": ["Seat-of-experience defines body.", "Subtle bodies are bodies."]
  },
  {
    "id": "5.99",
    "number": "5.99",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "ativāhikaṃ liṅgavāhakam",
    "devanagari": "अतिवाहिकं लिङ्गवाहकम्",
    "conceptIds": ["linga-sutra"],
    "translation": "Ativāhika carries across (484).",
    "commentary": "Ativāhika-artha: the vehicle conducting liṅga across deaths (cf. III.12 adhiṣṭhāna). Carrying-function names it — ativahana (transport) is its lakṣaṇa. Terminology fixed for eschatology.",
    "keyPoints": ["Transport defines the vehicle.", "Death-ferry named."]
  },
  {
    "id": "5.100",
    "number": "5.100",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "bhogāyatanaṃ śarīram",
    "devanagari": "भोगायतनं शरीरम्",
    "conceptIds": ["linga-sutra", "bhoga-sutra"],
    "translation": "Body means experience-house (484).",
    "commentary": "Śarīra-lakṣaṇa sealed: bhogāyatana (cf. III.12, V.98). Whatever houses bhoga — gross, subtle, vehicular — is śarīra. Function, not stuff or size, defines. Three bodies unified by one definition.",
    "keyPoints": ["Housing-experience defines.", "Three bodies, one definition."]
  },
  {
    "id": "5.101",
    "number": "5.101",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "tatsiddhiḥ śrutyādibhiḥ",
    "devanagari": "तत्सिद्धिः श्रुत्यादिभिः",
    "conceptIds": ["linga-sutra", "sruti-sutra"],
    "translation": "Its proof: śruti and the rest (484).",
    "commentary": "Ativāhika-siddhi: '...sa enam... ativahanti' śrutis + yukti (need of transport between deaths, cf. III.16 gati-hetu) + siddha-prasiddhi. Triple-proof again (cf. V.13): heard, reasoned, acknowledged.",
    "keyPoints": ["Texts declare the ferry.", "Need proves the ferry."]
  },
  {
    "id": "5.102",
    "number": "5.102",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "indriyāṇāṃ viṣayaprakāśanam",
    "devanagari": "इन्द्रियाणां विषयप्रकाशनम्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Senses illuminate objects — how? (485–487).",
    "commentary": "Prakāśana-praśna: acetana senses 'reveal' — how? By buddhi-adhyāsa-śakti transmitted (indriya = buddhi's extended doors, cf. old step-10 dvāra). Illumination borrowed (cf. I.99 iron), never owned.",
    "keyPoints": ["Doors, not lamps.", "Borrowed light reveals."]
  },
  {
    "id": "5.103",
    "number": "5.103",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "dvāramātraṃ yataḥ",
    "devanagari": "द्वारमात्रं यतः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Mere doors, since (487).",
    "commentary": "Dvāra-mātra (cf. Kārikā 35–36): senses are thresholds (indriya-dvārā buddhi paśyati) — seeing happens IN buddhi THROUGH senses. Revealer-sense clarified: transmission, not origination, is their revealing.",
    "keyPoints": ["Thresholds, not theaters.", "Seeing in buddhi, through senses."]
  },
  {
    "id": "5.104",
    "number": "5.104",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na taijasaṃ cakṣuḥ",
    "devanagari": "न तैजसं चक्षुः",
    "conceptIds": ["tattva-sutra"],
    "translation": "The eye is not made of light (487–488).",
    "commentary": "Taijasatva-niṣedha (vs 'eye is tejas'): blinding light destroys sight (excess destroys, kinship would aid); night-vision needs no flame-kin. Eye is ahaṅkārika (cf. II.20), served BY light, never OF light.",
    "keyPoints": ["Blinding refutes kinship.", "Served by light, not of light."]
  },
  {
    "id": "5.105",
    "number": "5.105",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "indriyavṛttisiddhiḥ",
    "devanagari": "इन्द्रियवृत्तिसिद्धिः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Sense-modification proved (488).",
    "commentary": "Vṛtti-siddhi: senses modify (go out to objects — prāpyakāri, cf. V.106) — proved by selective grasping (eye takes form, never taste). Function-selectivity evidences modification-reality.",
    "keyPoints": ["Selective grasping proves going-forth.", "Each takes its own, never another's."]
  },
  {
    "id": "5.106",
    "number": "5.106",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "prāpyakāritvaṃ vṛtteḥ",
    "devanagari": "प्राप्यकारित्वं वृत्तेः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Modification reaches its object (488–489).",
    "commentary": "Prāpyakāritva: vṛtti travels to viṣaya (Nyāya-Sāṅkhya agreement vs Mīmāṁsā's aprāpyakāritva) — proved by distant grasping (stars seen: vṛtti went). Mind's swiftness (āśu-sañcāra, cf. V.60) enables reaching.",
    "keyPoints": ["Vṛtti travels to object.", "Stars seen prove far-reaching."]
  },
  {
    "id": "5.107",
    "number": "5.107",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "dravyaguṇātmikā vṛttiḥ",
    "devanagari": "द्रव्यगुणात्मिका वृत्तिः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Modification is substance-and-quality-formed (490–491).",
    "commentary": "Vṛtti-svarūpa: vṛtti takes dravya (thing) AND guṇa (quality) — seeing pot AND red. Whole-cognition, not quality-film: senses deliver substances qualified, never bare universals.",
    "keyPoints": ["Things-with-qualities delivered.", "Never bare universals."]
  },
  {
    "id": "5.108",
    "number": "5.108",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "ahaṅkāraḥ sarvatra",
    "devanagari": "अहङ्कारः सर्वत्र",
    "conceptIds": ["tattva-sutra"],
    "translation": "Ahaṅkāra is everywhere the senses' uniform cause (491).",
    "commentary": "Sarvatra-ahaṅkāra: diverse senses, one yoni (cf. II.17) — uniformity of source explains coordination (cf. I.31 parasparākūta). Doubtful śruti harmonized (491–492): 'prāṇa'-texts read ahaṅkārika-prāṇa (sūkṣma), never bhūta-vāyu.",
    "keyPoints": ["One source coordinates many.", "Doubtful texts read subtle."]
  },
  {
    "id": "5.109",
    "number": "5.109",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "saṃdigdhaśruteḥ samanvayaḥ",
    "devanagari": "संदिग्धश्रुतेः समन्वयः",
    "conceptIds": ["sruti-sutra"],
    "translation": "Doubtful śruti harmonized (491–492).",
    "commentary": "Samanvaya-method again (cf. V.52, I.95): prāṇa-ja-śrutis read as ahaṅkāra-parvaka (ego-stage), preserving both texts (origin-texts) and tattva (ahaṅkāra-source). Hermeneutic consistency across the book.",
    "keyPoints": ["Stage-reading preserves both.", "Consistency across harmonizations."]
  },
  {
    "id": "5.110",
    "number": "5.110",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "sthūladehavai citryam",
    "devanagari": "स्थूलदेहवै चित्र्यम्",
    "conceptIds": ["linga-sutra"],
    "translation": "Gross-body varieties (492–493).",
    "commentary": "Sthūla-vaicitrya: jarāyuja/aṇḍaja/svedaja/udbhijja (womb/egg/sweat/soil-born) — four yonis cover observed births. Variety needs no new tattvas — bhūta-proportions + karma-lots (cf. III.51) suffice.",
    "keyPoints": ["Four wombs cover births.", "Proportions + lots explain variety."]
  },
  {
    "id": "5.111",
    "number": "5.111",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "pṛthivī eva sthūlopādānam",
    "devanagari": "पृथिवी एव स्थूलोपादानम्",
    "conceptIds": ["linga-sutra"],
    "translation": "Earth alone is gross body's (chief) stuff (493–494).",
    "commentary": "Pṛthivī-prādhānya (resolving V.96–97): earth dominates (solidity-form), others assist — prādhānya-vyapadeśa (naming by dominant). Pañca-bhautikatva (III.17) stands qualified: five present, earth presides.",
    "keyPoints": ["Five present, earth presides.", "Naming follows dominance."]
  },
  {
    "id": "5.112",
    "number": "5.112",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na prāṇaḥ śarīrakartā",
    "devanagari": "न प्राणः शरीरकर्ता",
    "conceptIds": ["tattva-sutra"],
    "translation": "Prāṇa is no body-maker (494–495).",
    "commentary": "Prāṇa-kartṛtva-niṣedha: prāṇa maintains (dhāraṇa), never builds — building needs cetana-adhiṣṭhāna + karma-niyama (cf. V.114). Fuel ≠ architect. Maintenance and construction distinguished.",
    "keyPoints": ["Fuel, not architect.", "Maintains; never builds."]
  },
  {
    "id": "5.113",
    "number": "5.113",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "indriyavikāraḥ prāṇaḥ",
    "devanagari": "इन्द्रियविकारः प्राणः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Prāṇa is sense-modification (495).",
    "commentary": "Prāṇa = indriya-vṛtti-viśeṣa (sāmānya-vṛtti, cf. II.31): no separate tattva (against 'prāṇa-tattva' schools). Common-function status sealed — prāṇa rides organs, never ranks beside them.",
    "keyPoints": ["Common function, not new entity.", "Rides organs; never beside them."]
  },
  {
    "id": "5.114",
    "number": "5.114",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "ātmanā śarīranirmāṇam",
    "devanagari": "आत्मना शरीरनिर्माणम्",
    "conceptIds": ["purusha-sutra"],
    "translation": "Body-building is by the Self (495–496).",
    "commentary": "Ātma-nirmātṛtva (sānnidhya-sense, cf. I.96–97): puruṣa's proximity + karma-niyama + prakṛti-pariṇāma build bodies — Self as nimitta-occasion (not upādāna, cf. V.30 ⇒ VI.30). Building needs witness-occasion.",
    "keyPoints": ["Witness occasions building.", "Occasion-cause, never material."]
  },
  {
    "id": "5.115",
    "number": "5.115",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "sāpekṣam adhiṣṭhānam",
    "devanagari": "सापेक्षम् अधिष्ठानम्",
    "conceptIds": ["purusha-sutra"],
    "translation": "The Self's superintendence is relative, not absolute (496–497).",
    "commentary": "Sāpekṣa-adhiṣṭhāna: puruṣa 'governs' relative to buddhi-upādhi (vyavahāra), never absolutely (paramārtha, cf. III.76 aupacārika). Two-truth superintendence: functional yes, essential no.",
    "keyPoints": ["Functional yes; essential no.", "Governance is upādhi-relative."]
  },
  {
    "id": "5.116",
    "number": "5.116",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "nityamuktāḥ puruṣāḥ",
    "devanagari": "नित्यमुक्ताः पुरुषाः",
    "conceptIds": ["purusha-sutra", "mukti-sutra"],
    "translation": "Puruṣas are ever free (497–499).",
    "commentary": "Nitya-muktatva seal (cf. I.86, III.5): freedom is svarūpa, never sādhya. 'Brahman'-word uses surveyed (V.117): Sāṅkhya's Brahman = bṛhattva (vastness of puruṣa-plurality?) — Vedānta's eka-Brahman declined with courtesy.",
    "keyPoints": ["Freedom is nature, never product.", "'Brahman' = vastness, not oneness."]
  },
  {
    "id": "5.117",
    "number": "5.117",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "brahmaśabdārthabhedaḥ",
    "devanagari": "ब्रह्मशब्दार्थभेदः",
    "conceptIds": ["sruti-sutra"],
    "translation": "'Brahman'-word uses in Sāṅkhya and Vedānta (498).",
    "commentary": "Brahma-śabda-viveka: bṛṃhati/bṛṃhayati (vast, vast-making) — Sāṅkhya reads vastness (puruṣa-bahutva-mahattva? prakṛti-vibhutva?); Vedānta reads unity. Etymology shared, metaphysics divided — word-study serves truth.",
    "keyPoints": ["Shared root, divided reading.", "Vastness vs unity."]
  },
  {
    "id": "5.118",
    "number": "5.118",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na suṣuptisamādhitulyaṃ muktiḥ",
    "devanagari": "न सुषुप्तिसमाधितुल्यं मुक्तिः",
    "conceptIds": ["mukti-sutra"],
    "translation": "Release differs from sleep and trance (499–500).",
    "commentary": "Suṣupti-samādhi-bheda: sleep/trance suspend aviveka (vṛtti-pause, cf. V.68); mokṣa burns aviveka-bīja (cf. III.55). Pause vs cremation — resemblance is functional, difference radical.",
    "keyPoints": ["Suspended vs burnt.", "Pause resembles; cremation differs."]
  },
  {
    "id": "5.119",
    "number": "5.119",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "mokṣasattvaṃ pramāṇaiḥ",
    "devanagari": "मोक्षसत्त्वं प्रमाणैः",
    "conceptIds": ["mukti-sutra"],
    "translation": "Release's reality demonstrated (500–501).",
    "commentary": "Mokṣa-sattva: śāstra (śruti-smṛti declare), yukti (sahetuka-sānta logic, cf. III.4), dṛṣṭa (jīvanmuktas observed, cf. III.83–84) — triple proof. Denial (Cārvāka/Bauddha) already demolished (I.20–50).",
    "keyPoints": ["Declared, reasoned, observed.", "Triple proof of freedom's fact."]
  },
  {
    "id": "5.120",
    "number": "5.120",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "suṣuptau vāsanāvaśaḥ",
    "devanagari": "सुषुप्तौ वासनावशः",
    "conceptIds": ["bandha-sutra"],
    "translation": "Vāsanā rests powerless in deep sleep (501–503).",
    "commentary": "Suṣupti-vāsanā: impressions persist unmanifest (bīja) — powerless till waking. Proves vāsanā-substance (persists through suspension) AND non-Self-locus (Self never suspends). Sleep psychology serves metaphysics.",
    "keyPoints": ["Seeds persist unmanifest.", "Suspension evidences substance."]
  },
  {
    "id": "5.121",
    "number": "5.121",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "jīvanmuktiḥ siddhā",
    "devanagari": "जीवन्मुक्तिः सिद्धा",
    "conceptIds": ["mukti-sutra"],
    "translation": "Living release defended (503–504).",
    "commentary": "Jīvanmukti-rakṣā (cf. III.83–84): prārabdha-body persists post-jñāna (cf. III.81 apavāda) — embodiment without ownership. Saṃskāra-theory (V.122): momentum explains persistence; ownership-absence explains freedom.",
    "keyPoints": ["Embodiment without ownership.", "Momentum explains persistence."]
  },
  {
    "id": "5.122",
    "number": "5.122",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "saṃskāravegeṇa sthitiḥ",
    "devanagari": "संस्कारवेगेण स्थितिः",
    "conceptIds": ["mukti-sutra"],
    "translation": "Persistence is by impression-momentum (504).",
    "commentary": "Saṃskāra-vega (cf. old 4.4 cakra): potter's wheel spins post-hand — prārabdha-vega spins post-jñāna. Momentum without new impulse: why sages eat, breathe, teach post-release.",
    "keyPoints": ["Wheel spins post-hand.", "Momentum without fresh impulse."]
  },
  {
    "id": "5.123",
    "number": "5.123",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "vanaspatayo 'pi bhogabhūmayaḥ",
    "devanagari": "वनस्पतयो ऽपि भोगभूमयः",
    "conceptIds": ["bhoga-sutra"],
    "translation": "Plants too are experience-fields (504–506).",
    "commentary": "Vanaspti-bhoga: Chāndogya VI.xi.1 (dying tree laments limb-wise) + smṛti + observed tropisms prove liṅga-presence in plants. Bhoga-capacity tracks liṅga, never locomotion — rooted beings feel.",
    "keyPoints": ["Dying tree laments limb-wise.", "Feeling tracks subtle body, not feet."]
  },
  {
    "id": "5.124",
    "number": "5.124",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "chāndogyasmṛtī pramāṇam",
    "devanagari": "छान्दोग्यस्मृती प्रमाणम्",
    "conceptIds": ["sruti-sutra"],
    "translation": "Chāndogya VI.xi.1 and smṛti evidence (505–506).",
    "commentary": "'Jīvāpetam...' — tree lives while sap-Self stays; smṛti (Manu?) confirms plant-sentience. Textual front for plant-bhoga: śruti-smṛti-yukti converge (cf. V.13 triple-proof pattern).",
    "keyPoints": ["Sap-Self stays, tree lives.", "Texts converge with tropisms."]
  },
  {
    "id": "5.125",
    "number": "5.125",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na karmādhikāriṇo vanaspatayaḥ",
    "devanagari": "न कर्माधिकारिणो वनस्पतयः",
    "conceptIds": ["bhoga-sutra"],
    "translation": "Plants are no moral agents (506–507).",
    "commentary": "Karmādhikāra-niṣedha: bhoga (experience) ≠ karma (responsible action) — plants undergo, never initiate (no buddhi-vikalpa). Upabhoga-deha (V.126) without karma-deha: suffering without earning, ripening past lots.",
    "keyPoints": ["Undergo without initiating.", "Suffering without fresh earning."]
  },
  {
    "id": "5.126",
    "number": "5.126",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "trividho dehaḥ karma-upabhoga-ubhayaḥ",
    "devanagari": "त्रिविधो देहः कर्मौपभोगौभयः",
    "conceptIds": ["linga-sutra"],
    "translation": "Three body-kinds: karma-, enjoyment-, both-bodies (507–508).",
    "commentary": "Deha-traividhya: karma-deha (human: earns+undergoes), upabhoga-deha (hell/heaven/plant: undergoes only), ubhaya (mixed). Moral anatomy: earning-capacity distributes bodies — theodicy's instrument.",
    "keyPoints": ["Earners, undergoers, both.", "Earning-capacity distributes bodies."]
  },
  {
    "id": "5.127",
    "number": "5.127",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "caturtho 'pi sambhavati",
    "devanagari": "चतुर्थो ऽपि सम्भवति",
    "conceptIds": ["linga-sutra"],
    "translation": "A fourth kind also possible (508).",
    "commentary": "Caturtha-deha: neither-earning-nor-undergoing? (siddha-dehas? prakṛtilīnas?) — taxonomy left open (cf. I.26 open categories, closed logic). Completeness without closure: kinds admit extension.",
    "keyPoints": ["Taxonomy open-ended.", "Kinds admit extension."]
  },
  {
    "id": "5.128",
    "number": "5.128",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "na vyaktibuddheḥ nityatvam",
    "devanagari": "न व्यक्तिबुद्धेः नित्यत्वम्",
    "conceptIds": ["buddhi-sutra"],
    "translation": "Individual buddhi's eternity refuted (509–510).",
    "commentary": "Vyakti-buddhi-anityatva: individual buddhis begin (birth), transform (learning), end (release/death) — nitya-buddhi would freeze learning and bar release. Mahat-tattva (jāti) persists; vyakti-buddhis perish.",
    "keyPoints": ["Individual minds begin and end.", "Type persists; tokens perish."]
  },
  {
    "id": "5.129",
    "number": "5.129",
    "section": "Adhyāya V · Parapakṣa",
    "iast": "siddhayaḥ santi na caitanyaṃ bhautikam",
    "devanagari": "सिद्धयः सन्ति न चैतन्यं भौतिकम्",
    "conceptIds": ["siddhi-sutra", "purusha-sutra"],
    "translation": "Yogic perfections stand — and consciousness is no elemental product (510–512).",
    "commentary": "Samāpana-double: siddhis defended (pramāṇa-attested, cf. III.29–44) AND caitanya-abhautikatva resealed (cf. III.20–22) — Book V ends where Sāṅkhya stands: powers real yet subordinate; consciousness transcendent yet immanent-as-witness. Next: recapitulation (Book VI).",
    "keyPoints": ["Powers real, subordinate.", "Consciousness transcendent, witnessing."]
  }
];
