/**
 * Sāṅkhya-Pravacana-Sūtra, Adhyāya VI · Tantra (6.1–6.70) — English.
 * Recapitulation: Self exists/distinct/aim (1–9) · aviveka eternity and end
 * (10–16) · release-nature, Veda-harmony, adhikāra, dhyāna, yoga (17–28) ·
 * prakṛti as world-stuff, all-pervading, guṇa-formed, purposive (29–43) ·
 * plurality vs non-duality, self-luminosity (44–50) · world real, ever-existent,
 * ahaṅkāra-agency, rebirth, going, jīva, body (51–66) · ahaṅkāra-not-īśvara,
 * practical īśvaras, mahat-upādhi, eternal tie, Pañcaśikha/Sanandana,
 * tie-dissolution the Good, Kapila one (67–70).
 */
export const samkhyaSutraEn6: any[] = [
  {
    "id": "6.1",
    "number": "6.1",
    "section": "Adhyāya VI · Tantra",
    "iast": "asti ātmā",
    "devanagari": "अस्ति आत्मा",
    "conceptIds": ["purusha-sutra"],
    "translation": "The Self exists (513).",
    "commentary": "Asti-ātmā: Book VI opens re-asserting being — after five books of dissection, existence re-gathered. Undisputed ground (cf. I.138) restated as compendium's foundation: all recapitulation presupposes the Existent.",
    "keyPoints": ["Being re-asserted after dissection.", "Compendium's foundation: the Existent."]
  },
  {
    "id": "6.2",
    "number": "6.2",
    "section": "Adhyāya VI · Tantra",
    "iast": "dehādivyatiriktaḥ",
    "devanagari": "देहादिव्यतिरिक्तः",
    "conceptIds": ["purusha-sutra"],
    "translation": "Different from body and the rest.",
    "commentary": "Dehādi-vyatireka recapped (I.139–144 hetus compressed): saṃghāta-parārthatva, triguṇa-viparyaya, adhiṣṭhāna, bhoktṛtva, kaivalyārtha-pravṛtti — five proofs in one sūtra's ambit. Compendium compresses without dropping.",
    "keyPoints": ["Five proofs compressed.", "Difference re-sealed."]
  },
  {
    "id": "6.3",
    "number": "6.3",
    "section": "Adhyāya VI · Tantra",
    "iast": "puruṣārthaḥ siddhaḥ",
    "devanagari": "पुरुषार्थः सिद्धः",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Puruṣa's aim stands fulfilled (517) — how?",
    "commentary": "Puruṣārtha-siddhi-praśna: if Self is ever-free (V.116), what 'fulfillment'? Answer-frame (4–9): fulfillment = duḥkha-nivṛtti + svarūpa-sthiti as APPARENT gain (cf. III.76 aupacārika) — real as experienced, figurative as metaphysics.",
    "keyPoints": ["Fulfillment questioned for the ever-free.", "Apparent gain, real experience."]
  },
  {
    "id": "6.4",
    "number": "6.4",
    "section": "Adhyāya VI · Tantra",
    "iast": "duḥkham adhikaṃ sukhāt",
    "devanagari": "दुःखम् अधिकं सुखात्",
    "conceptIds": ["duhkha-sutra"],
    "translation": "Pain outweighs pleasure (517–518).",
    "commentary": "Duḥkhādhikya: reckoning — anticipation-anxiety + enjoyment-admixture + loss-grief exceed pleasure-moments. Hedonic audit favors mumukṣutva: the scale itself testifies (cf. I.84, IV.5 hawk).",
    "keyPoints": ["Audit: pain exceeds pleasure.", "Scale testifies for seeking."]
  },
  {
    "id": "6.5",
    "number": "6.5",
    "section": "Adhyāya VI · Tantra",
    "iast": "durlabhaṃ sukham",
    "devanagari": "दुर्लभं सुखम्",
    "conceptIds": ["duhkha-sutra"],
    "translation": "Pleasure is rare (518–519).",
    "commentary": "Sukha-durlabhatva: pure pleasure-moments are statistical exceptions — mostly maintenance (hunger-eating), mostly mixed (cf. IV.5). Rarity + admixture = vairāgya's double ledger.",
    "keyPoints": ["Pure joy statistical exception.", "Rarity ledger for dispassion."]
  },
  {
    "id": "6.6",
    "number": "6.6",
    "section": "Adhyāya VI · Tantra",
    "iast": "sarvaṃ duḥkhamiśram",
    "devanagari": "सर्वं दुःखमिश्रम्",
    "conceptIds": ["duhkha-sutra"],
    "translation": "All is pain-alloyed (519).",
    "commentary": "Sarva-duḥkha-miśratva: pariṇāma (ending), tāpa (fearing), saṃskāra (habituating) duḥkhas lace every sukha (Yoga II.15 quoted, cf. I.4-bhāṣya). Alloy-analysis: no unalloyed bhoga-sample exists.",
    "keyPoints": ["Ending, fearing, habituating lace all joy.", "No unalloyed sample exists."]
  },
  {
    "id": "6.7",
    "number": "6.7",
    "section": "Adhyāya VI · Tantra",
    "iast": "sarvaṃ duḥkhaṃ vivekinaḥ",
    "devanagari": "सर्वं दुःखं विवेकिनः",
    "conceptIds": ["duhkha-sutra"],
    "translation": "All is pain — to the discerner (Yoga II.15).",
    "commentary": "Vivekin's verdict (p.519):BCDiscriminator sees alloy AS pain (duḥkham eva) — not pessimism but precision: what ends/is-feared/habituates IS duḥkha-functionally. Viveka reclassifies, world unchanged.",
    "keyPoints": ["Discerner reclassifies alloy as pain.", "Precision, not pessimism."]
  },
  {
    "id": "6.8",
    "number": "6.8",
    "section": "Adhyāya VI · Tantra",
    "iast": "puruṣārtho dvividhaḥ sukhaṃ duḥkhābhāvaś ca",
    "devanagari": "पुरुषार्थो द्विविधः सुखं दुःखाभावश् च",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Puruṣa's aim is twofold: pleasure and pain's absence (520).",
    "commentary": "Dvividha-puruṣārtha: sukha (bhoga-phase) + duḥkhābhāva (mokṣa-phase) — answering VI.3: fulfillment spans both phases (cf. II.9 rāga/sarga + vairāgya/mokṣa). Aim's duality mirrors path's duality.",
    "keyPoints": ["Pleasure-phase and absence-phase.", "Aim mirrors path's duality."]
  },
  {
    "id": "6.9",
    "number": "6.9",
    "section": "Adhyāya VI · Tantra",
    "iast": "saṃśayacchedaḥ",
    "devanagari": "संशयच्छेदः",
    "conceptIds": ["viveka-sutra"],
    "translation": "A doubt raised and solved (520–522).",
    "commentary": "Saṃśaya (if aim includes sukha, why renounce bhoga?) — cheda: sukha-phase is passage (tīrtha), never residence; duḥkhābhāva alone is ātyantika (cf. I.1). Doubt's raising-and-solving models śāstric pedagogy itself.",
    "keyPoints": ["Pleasure is passage, not residence.", "Doubt modeled and dissolved."]
  },
  {
    "id": "6.10",
    "number": "6.10",
    "section": "Adhyāya VI · Tantra",
    "iast": "anādiḥ avivekaḥ",
    "devanagari": "अनादिः अविवेकः",
    "conceptIds": ["bandha-sutra"],
    "translation": "Aviveka is beginningless (522–523).",
    "commentary": "Aviveka-anāditva: no first mistaking (cf. V.11 pravāha) — beginning would need pre-beginning knower-distinction. Beginninglessness bars 'when did bondage start?' — wrong question dissolved, not answered.",
    "keyPoints": ["No first mistaking.", "'When bound?' is wrong question."]
  },
  {
    "id": "6.11",
    "number": "6.11",
    "section": "Adhyāya VI · Tantra",
    "iast": "na tu nityaḥ",
    "devanagari": "न तु नित्यः",
    "conceptIds": ["bandha-sutra", "viveka-sutra"],
    "translation": "But not eternal (523).",
    "commentary": "Anitya-aviveka: beginningless-yet-ending (cf. bīja-dāha III.55, jñāna-nivartya I.56). Anādi ≠ nitya — stream can cease (cf. V.11 vs V.38 pravāha-nuances). Beginninglessness threatens eternity never.",
    "keyPoints": ["Beginningless yet ending.", "Streams can cease."]
  },
  {
    "id": "6.12",
    "number": "6.12",
    "section": "Adhyāya VI · Tantra",
    "iast": "viveko nāśahetuḥ",
    "devanagari": "विवेको नाशहेतुः",
    "conceptIds": ["viveka-sutra"],
    "translation": "Viveka is its destruction-cause (523–524).",
    "commentary": "Nāśa-hetu-nirdeśa: aviveka's specific destroyer is viveka (niyata-hetu, cf. I.56, III.25) — nothing else qualifies. Cause-of-destruction specified so practice aims precisely: cultivate discrimination, nothing else, for this.",
    "keyPoints": ["Specified destroyer: discrimination.", "Aim precisely; nothing else destroys."]
  },
  {
    "id": "6.13",
    "number": "6.13",
    "section": "Adhyāya VI · Tantra",
    "iast": "viveka eva nāśakaḥ",
    "devanagari": "विवेक एव नाशकः",
    "conceptIds": ["viveka-sutra"],
    "translation": "Viveka alone destroys aviveka (524–525).",
    "commentary": "Eva-kāra (exclusive): viveka ALONE — karma/tapas/upāsanā excluded (cf. I.56, III.23–26, III.82). Exclusivity proved by hetu-niyama (proper-cause logic): darkness yields to light only.",
    "keyPoints": ["Alone — exclusivity proved.", "Darkness yields to light only."]
  },
  {
    "id": "6.14",
    "number": "6.14",
    "section": "Adhyāya VI · Tantra",
    "iast": "aviveka eva bandhahetuḥ",
    "devanagari": "अविवेक एव बन्धहेतुः",
    "conceptIds": ["bandha-sutra"],
    "translation": "Aviveka alone causes bondage (525).",
    "commentary": "Eva reversed: aviveka ALONE binds (cf. III.24, III.79 hetu-vs-state precision) — karma/kāla/deha co-operate never originate. Single-cause doctrine both ways: one binder, one freer.",
    "keyPoints": ["One binder, one freer.", "Co-factors never originate."]
  },
  {
    "id": "6.15",
    "number": "6.15",
    "section": "Adhyāya VI · Tantra",
    "iast": "na punarbandho muktasya",
    "devanagari": "न पुनर्बन्धो मुक्तस्य",
    "conceptIds": ["mukti-sutra"],
    "translation": "The freed never rebind (525–526).",
    "commentary": "Punarbandha-niṣedha: dagdha-bīja (burnt seed, cf. III.55) never sprouts — jñāna burns aviveka-mūla, not merely clips. Opposite view's defects (VI.16): re-binding would make jñāna fruitless and śāstra pointless.",
    "keyPoints": ["Burnt seeds never sprout.", "Re-binding would void śāstra."]
  },
  {
    "id": "6.16",
    "number": "6.16",
    "section": "Adhyāya VI · Tantra",
    "iast": "viparītamatadoṣāḥ",
    "devanagari": "विपरीतमतदोषाः",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Opposite view's defects pointed out (526–527).",
    "commentary": "Viparīta-doṣa: re-birth-after-mokṣa theories (prakṛti-force? īśvara-will? karma-remainder?) each contradict jñāna-dāha (burning) or niyata-hetu (proper-cause). Defects catalogued — irreversibility (ātyantika, cf. I.1) logically sealed.",
    "keyPoints": ["Force? will? remainder? — each fails.", "Irreversibility logically sealed."]
  },
  {
    "id": "6.17",
    "number": "6.17",
    "section": "Adhyāya VI · Tantra",
    "iast": "mokṣasvarūpaṃ kaivalyam eva",
    "devanagari": "मोक्षस्वरूपं कैवल्यम् एव",
    "conceptIds": ["mukti-sutra"],
    "translation": "Release's nature: isolation itself (527–528).",
    "commentary": "Mokṣa-svarūpa restated (cf. III.70, V.65–74 via-negativa completed): kaivalya = draṣṭṛ-sthiti, positively characterized after negations. Compendium gives both faces: NOT-those (Book V), THIS (here).",
    "keyPoints": ["Negations complete; positive stated.", "Isolation itself, nothing added."]
  },
  {
    "id": "6.18",
    "number": "6.18",
    "section": "Adhyāya VI · Tantra",
    "iast": "vedāvirodhaḥ samanvayāt",
    "devanagari": "वेदाविरोधः समन्वयात्",
    "conceptIds": ["sruti-sutra"],
    "translation": "Veda-conflict avoided by harmony (528–529).",
    "commentary": "Veda-avirodha seal: apparent conflicts (saguṇa-texts, karma-texts, ekatva-texts) resolved by samanvaya-rules established (I.95, I.147, III.69, V.52, V.56–58). System-Veda accord declared compendium-complete on authority-front.",
    "keyPoints": ["All conflicts harmonized.", "Authority-front complete."]
  },
  {
    "id": "6.19",
    "number": "6.19",
    "section": "Adhyāya VI · Tantra",
    "iast": "adhikāriṇas trividhāḥ",
    "devanagari": "अधिकारिणस् त्रिविधाः",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Aspirants are three classes (529).",
    "commentary": "Adhikāri-traividhya (cf. I.70): manda/madhyama/uttama — śabda/yukti/sūtra-mātra sufficiency. Compendium serves all three: stories (manda, Book IV), refutations (madhyama, Book V), sūtras (uttama, throughout). Pedagogy total.",
    "keyPoints": ["Dull, middle, keen — all served.", "Stories, refutations, sūtras respectively."]
  },
  {
    "id": "6.20",
    "number": "6.20",
    "section": "Adhyāya VI · Tantra",
    "iast": "śravaṇetarayoḥ api upayogaḥ",
    "devanagari": "श्रवणेतरयोः अपि उपयोगः",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Non-hearing means also useful (530).",
    "commentary": "Śravaṇetara-upayoga: manana (IV.17), nididhyāsana (III.80), sat-saṅga (IV.23), dhyāna (III.29ff) — śravaṇa initiates, others mature (cf. I.59 sākṣātkāra-need). Utility-hierarchy: all useful, none sufficient alone but viveka.",
    "keyPoints": ["Hearing initiates; rest mature.", "All useful; viveka alone sufficient."]
  },
  {
    "id": "6.21",
    "number": "6.21",
    "section": "Adhyāya VI · Tantra",
    "iast": "āsanabhrāntinirāsaḥ",
    "devanagari": "आसनभ्रान्तिनिरासः",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Yogic-posture misconception removed (530).",
    "commentary": "Āsana-bhrānti (cf. III.34): posture-mystique (acrobatic āsana = yoga) corrected — sthira-sukha serves dhyāna; display-āsana serves ahaṅkāra. Means-fetish diagnosed across sādhanas.",
    "keyPoints": ["Posture serves; never substitutes.", "Display-āsana feeds ego."]
  },
  {
    "id": "6.22",
    "number": "6.22",
    "section": "Adhyāya VI · Tantra",
    "iast": "dhyānaṃ cittanirodhaviśeṣaḥ",
    "devanagari": "ध्यानं चित्तनिरोधविशेषः",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Dhyāna defined (531).",
    "commentary": "Dhyāna-lakṣaṇa restated (cf. III.30–31): rāga-kṣaya-pūrvaka taila-dhārāvat cittapravāha (oil-stream mind-flow toward tattva). Definition crowns sādhanas before yoga-defence (VI.23).",
    "keyPoints": ["Oil-stream flow toward reality.", "Passion-cessation first, flow next."]
  },
  {
    "id": "6.23",
    "number": "6.23",
    "section": "Adhyāya VI · Tantra",
    "iast": "yogarakṣā",
    "devanagari": "योगरक्षा",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Yoga defended (531–532).",
    "commentary": "Yoga-rakṣā: Patañjali's aṣṭāṅga as Sāṅkhya-prayoga (practice-wing) — yama-to-samādhi serve viveka (cf. III.29–36 dhyāna-sādhanas). Sāṅkhya-Yoga abheda in prayojana (both puruṣa-viveka), bheda in pradhāna (jñāna vs nirodha-emphasis).",
    "keyPoints": ["Yoga is Sāṅkhya's practice-wing.", "Same aim, complementary emphasis."]
  },
  {
    "id": "6.24",
    "number": "6.24",
    "section": "Adhyāya VI · Tantra",
    "iast": "aviveka uparāgahetuḥ",
    "devanagari": "अविवेक उपरागहेतुः",
    "conceptIds": ["abhasa-sutra"],
    "translation": "Aviveka causes puruṣa's tinting (532).",
    "commentary": "Uparāga-hetu (cf. I.27–29 tint-theories refined): aviveka (not objects, time, karma) is uparāga's cause — tinting is misapprehension-event, never substance-transfer. Causation located precisely: in mis-knowing.",
    "keyPoints": ["Tinting is mis-knowing event.", "Located precisely: in aviveka."]
  },
  {
    "id": "6.25",
    "number": "6.25",
    "section": "Adhyāya VI · Tantra",
    "iast": "uparāgo mithyābhimānaḥ",
    "devanagari": "उपरागो मिथ्याभिमानः",
    "conceptIds": ["abhasa-sutra"],
    "translation": "Tinting is unreal — mere conceit (532–533).",
    "commentary": "Uparāga-mithyātva: tint is abhimāna-mātra (conceit-only, cf. I.58 vāṅmātra, III.76 aupacārika) — crystal never reddens. Ontology of appearance: pratibhāsika, never pāramārthika. Appearance-theory complete.",
    "keyPoints": ["Conceit-only, never substance.", "Crystal never reddens."]
  },
  {
    "id": "6.26",
    "number": "6.26",
    "section": "Adhyāya VI · Tantra",
    "iast": "uparāgopaśamopāyaḥ vivekaḥ",
    "devanagari": "उपरागोपशमोपायः विवेकः",
    "conceptIds": ["viveka-sutra"],
    "translation": "Tint-suppression means: viveka (533–535).",
    "commentary": "Upaśama-upāya: viveka-abhyāsa thins uparāga (vairāgya-abhyāsa, cf. III.36; tattvābhyāsa, cf. III.80) — suppression by replacement (śukla-dhyāna displacing kṛṣṇa-vāsanā), never by force. Ancients' teaching cited (VI.27).",
    "keyPoints": ["Replacement, never force.", "White meditation displaces dark habit."]
  },
  {
    "id": "6.27",
    "number": "6.27",
    "section": "Adhyāya VI · Tantra",
    "iast": "pūrvācāryopadeśaḥ",
    "devanagari": "पूर्वाचार्योपदेशः",
    "conceptIds": ["parampara-sutra"],
    "translation": "Ancients' teaching on this (535–536).",
    "commentary": "Prācīna-upadeśa: Pañcaśikha-ādi (cf. V.24, old 6.2) taught uparāga-śānti by viveka-niṣṭhā — paramparā confirms method (cf. old 6.5 śiṣya-paramparā). Practice-lineage authorizes practice-prescription.",
    "keyPoints": ["Pañcaśikha taught tint-peace.", "Lineage authorizes method."]
  },
  {
    "id": "6.28",
    "number": "6.28",
    "section": "Adhyāya VI · Tantra",
    "iast": "na deśaniyamaḥ yogasya",
    "devanagari": "न देशनियमः योगस्य",
    "conceptIds": ["siddhi-sutra"],
    "translation": "No fixed place needed for yoga (536).",
    "commentary": "Deśa-aniyama: yoga works anywhere citta can turn inward — tīrtha/guhā helpful (upakāraka), never necessary (na niyāmaka). Anti-pilgrimage-dependence: geography serves, never saves (cf. IV.12 needlessness).",
    "keyPoints": ["Helpful, never necessary.", "Geography serves; never saves."]
  },
  {
    "id": "6.29",
    "number": "6.29",
    "section": "Adhyāya VI · Tantra",
    "iast": "prakṛtiḥ jagadupādānam",
    "devanagari": "प्रकृतिः जगदुपादानम्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Prakṛti is the world's material (536–537).",
    "commentary": "Upādānatva-seal (cf. I.65, I.110, I.136, II.6): jagat = prakṛti-pariṇāma — compendium's cosmology restated positively after refutations (Book V). Material-cause doctrine stands demolition-tested.",
    "keyPoints": ["World is prakṛti transformed.", "Stands demolition-tested."]
  },
  {
    "id": "6.30",
    "number": "6.30",
    "section": "Adhyāya VI · Tantra",
    "iast": "na puruṣa upādānam",
    "devanagari": "न पुरुष उपादानम्",
    "conceptIds": ["purusha-sutra"],
    "translation": "Puruṣa cannot be world's material (537).",
    "commentary": "Puruṣa-anupādānatva: kūṭastha-nirguṇa-niṣkriya cannot stuff change (cf. I.146, V.53). Śruti against opposite (VI.31): '...ajan...' — aja (unborn) never becomes. Material-cause needs pariṇāmitva; puruṣa lacks it essentially.",
    "keyPoints": ["Changeless can't stuff change.", "Unborn never becomes."]
  },
  {
    "id": "6.31",
    "number": "6.31",
    "section": "Adhyāya VI · Tantra",
    "iast": "śrutiḥ viparītamataniṣedhe",
    "devanagari": "श्रुतिः विपरीतमतनिषेधे",
    "conceptIds": ["sruti-sutra"],
    "translation": "Śruti opposes the reverse view (537–539).",
    "commentary": "Śruti-niṣedha (aja/avyaya texts) + Vaiśeṣika-condemnation (VI.32: atom-upādāna fails, cf. V.78–81) + Muṇḍaka II.i.5 harmonized (VI.33: '...puruṣa...' read sṛṣṭi-upalakṣaṇa, not upādāna). Triple seal on prakṛti-upādānatva.",
    "keyPoints": ["Unborn-texts bar puruṣa-stuff.", "Muṇḍaka harmonized non-materially."]
  },
  {
    "id": "6.32",
    "number": "6.32",
    "section": "Adhyāya VI · Tantra",
    "iast": "vaiśeṣikā dūṣitāḥ",
    "devanagari": "वैशेषिका दूषिताः",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Vaiśeṣikas condemned (538).",
    "commentary": "Vaiśeṣika-nindā (summary of V.78–94): atom-eternity, samavāya, ṣaṭpadārtha — each demolished; condemnation here is compendium-verdict, not new argument. Systems judged by fruits: atomism yields neither viveka nor mokṣa.",
    "keyPoints": ["Verdict, not new argument.", "Atomism yields no release."]
  },
  {
    "id": "6.33",
    "number": "6.33",
    "section": "Adhyāya VI · Tantra",
    "iast": "muṇḍakokteḥ samanvayaḥ",
    "devanagari": "मुण्डकोक्तेः समन्वयः",
    "conceptIds": ["sruti-sutra"],
    "translation": "Muṇḍaka II.i.5 harmonized (538–539).",
    "commentary": "'Yathorṇanābhiḥ...' (spider-text): spider emits web from body-stuff (upādāna-dṛṣṭānta FOR prakṛti-pariṇāma!) — puruṣa emits nothing. Doubtful text turned witness: emission-analogy suits pariṇāmin, never kūṭastha.",
    "keyPoints": ["Spider emits from body-stuff.", "Analogy suits transformer, not witness."]
  },
  {
    "id": "6.34",
    "number": "6.34",
    "section": "Adhyāya VI · Tantra",
    "iast": "bhrāntinirāsaḥ",
    "devanagari": "भ्रान्तिनिरासः",
    "conceptIds": ["viveka-sutra"],
    "translation": "A misconception removed (539).",
    "commentary": "Bhrānti (puruṣa-as-creator misreading of Muṇḍaka?) removed: sraṣṭṛtva-śrutis are prakṛti-parā (cf. V.7 Chāndogya method). Misconception-removal as standing duty — compendium models self-correction (cf. V.94).",
    "keyPoints": ["Creator-texts read prakṛti-ward.", "Self-correction modeled."]
  },
  {
    "id": "6.35",
    "number": "6.35",
    "section": "Adhyāya VI · Tantra",
    "iast": "vibhutvaṃ prakṛteḥ",
    "devanagari": "विभुत्वं प्रकृतेः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Prakṛti's all-pervading proved (539–540).",
    "commentary": "Vibhutva-siddhi (cf. I.125 avyakta-vyāpi, I.76 sarvopādāna-needs-vibhu): effects everywhere (sarvatra kārya-darśana) → cause everywhere. Ubiquity of products proves ubiquity of producer.",
    "keyPoints": ["Everywhere-effects prove everywhere-cause.", "Ubiquity inferred, not imagined."]
  },
  {
    "id": "6.36",
    "number": "6.36",
    "section": "Adhyāya VI · Tantra",
    "iast": "gatiḥ mūlakāraṇatvāvirodhinī",
    "devanagari": "गतिः मूलकारणत्वाविरोधिनी",
    "conceptIds": ["tattva-sutra"],
    "translation": "Motion conflicts not with primal-causality (540–541).",
    "commentary": "Gati-mūlatva-samanvaya: prakṛti moves (pariṇāma-calana, cf. guṇa-kṣobha) yet stays mūla — motion is avasthā-change, never dravya-loss (cf. I.11 śakti-manifestation). Root moves as ocean waves, stays as ocean.",
    "keyPoints": ["Waves move; ocean stays.", "State-change, never substance-loss."]
  },
  {
    "id": "6.37",
    "number": "6.37",
    "section": "Adhyāya VI · Tantra",
    "iast": "sui generis prakṛtiḥ",
    "devanagari": "सुइ गेनेरिस् प्रकृतिः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Prakṛti is sui generis (541).",
    "commentary": "Asādhāraṇatva: prakṛti resembles nothing (acetana-yet-ordered, eka-yet-vicitra-kāraṇa) — sui generis blocks analogical reduction (na dṛṣṭānta-vaśā tattva-siddhiḥ). Uniqueness claims need pramāṇa (given: I.126–137), never mere assertion.",
    "keyPoints": ["Resembles nothing fully.", "Uniqueness proved, not asserted."]
  },
  {
    "id": "6.38",
    "number": "6.38",
    "section": "Adhyāya VI · Tantra",
    "iast": "guṇāḥ svarūpaṃ na dharmāḥ",
    "devanagari": "गुणाः स्वरूपं न धर्माः",
    "conceptIds": ["guna-sutra"],
    "translation": "Guṇas are her very form, not attributes (542–543).",
    "commentary": "Guṇa-svarūpatva (anti-Vaiśeṣika dharma-reading, cf. I.25–26, V.87–88): sattva-rajas-tamas ARE prakṛti (triguṇātmikā), never HER properties — dharma-dharmi-bheda would dualize the mūla. Substance-strands, not qualities.",
    "keyPoints": ["Strands, not qualities.", "Attribute-reading would dualize root."]
  },
  {
    "id": "6.39",
    "number": "6.39",
    "section": "Adhyāya VI · Tantra",
    "iast": "sṛṣṭiprayojanaṃ vimokṣaḥ",
    "devanagari": "सृष्टिप्रयोजनं विमोक्षः",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Creation's purpose: release (543).",
    "commentary": "Prayojana-seal (cf. II.1, III.60): vimokṣa (bhoga-antargata) — compendium's teleology restated after cosmology secured (29–38). Purpose restated LAST (not first, cf. I.1) — compendium order: being → knowing → serving.",
    "keyPoints": ["Purpose restated after proof.", "Release contains enjoyment-phase."]
  },
  {
    "id": "6.40",
    "number": "6.40",
    "section": "Adhyāya VI · Tantra",
    "iast": "vaicitryahetuḥ karmabhedaḥ",
    "devanagari": "वैचित्र्यहेतुः कर्मभेदः",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Diversity's reason: karma-difference (544).",
    "commentary": "Vaicitrya-hetu (cf. III.51 garbhadasa, I.17 vaicitrya): one prakṛti + many karmas = diverse lots. Diversity needs no many-makers — one cook, many orders (cf. III.51). Theodicy compressed.",
    "keyPoints": ["One cook, many orders.", "Karma-difference diversifies one work."]
  },
  {
    "id": "6.41",
    "number": "6.41",
    "section": "Adhyāya VI · Tantra",
    "iast": "saiva sṛṣṭisaṃhārakartrī",
    "devanagari": "सैव सृष्टिसंहारकर्त्री",
    "conceptIds": ["tattva-sutra"],
    "translation": "She creates and destroys (544–545) — how?",
    "commentary": "Sṛṣṭi-saṃhāra-ekakartṛtva: same prakṛti emits (guṇa-prasāra) and withdraws (guṇa-saṃhāra) — ocean foams and calms. 'How' answered: avasthā-bheda (cf. I.134), never kartṛ-bheda. One doer, two directions.",
    "keyPoints": ["Foams and calms: one ocean.", "State-difference, never doer-difference."]
  },
  {
    "id": "6.42",
    "number": "6.42",
    "section": "Adhyāya VI · Tantra",
    "iast": "pravṛttiḥ na mokṣavirodhinī",
    "devanagari": "प्रवृत्तिः न मोक्षविरोधिनी",
    "conceptIds": ["mukti-sutra"],
    "translation": "Activity bars not release (545).",
    "commentary": "Pravṛtti-avirodha: prakṛti's continuing cosmic activity (for OTHERS, cf. III.68) doesn't touch the freed (cf. III.66–67 nivṛtti-individualized). Worlds spin on; freed stands free — no contradiction, for nivṛtti is per-puruṣa.",
    "keyPoints": ["Worlds spin; freed stands free.", "Withdrawal individualized."]
  },
  {
    "id": "6.43",
    "number": "6.43",
    "section": "Adhyāya VI · Tantra",
    "iast": "ekārthā sṛṣṭiḥ nānyasaṅkrāminī",
    "devanagari": "एकार्था सृष्टिः नान्यसङ्क्रामिनी",
    "conceptIds": ["purusha-sutra"],
    "translation": "Creation for one puruṣa touches not another (545–546).",
    "commentary": "Asaṅkara-sṛṣṭi: buddhi-lots are vyavasthita (cf. I.29, I.152) — my sarga-suite never bills your puruṣa. Individual-series insulation: plurality's practical seal (cf. III.68, III.71 upagrāha-bheda).",
    "keyPoints": ["My suite never bills you.", "Series insulated individually."]
  },
  {
    "id": "6.44",
    "number": "6.44",
    "section": "Adhyāya VI · Tantra",
    "iast": "bahutvaṃ śrutibhiḥ",
    "devanagari": "बहुत्वं श्रुतिभिः",
    "conceptIds": ["purusha-sutra", "sruti-sutra"],
    "translation": "Plurality proved by Veda (546–547).",
    "commentary": "Bahutva-śruti: '...puruṣā bahavaḥ...' texts + deva-martya-bheda presuppositions + Vāmadeva-records (cf. I.157) — śruti-plurality catalogued. Upādhi-insufficiency (VI.45): avaccheda can't seat vyavasthā (cf. I.151).",
    "keyPoints": ["Texts presuppose many.", "Avaccheda can't seat distribution."]
  },
  {
    "id": "6.45",
    "number": "6.45",
    "section": "Adhyāya VI · Tantra",
    "iast": "nopādhinā vyavasthā",
    "devanagari": "नोपाधिना व्यवस्था",
    "conceptIds": ["purusha-sutra"],
    "translation": "Upādhi cannot explain distribution (547–548).",
    "commentary": "Upādhi-ayogyatva restated finally (cf. I.150–152, V.50): all-present Self + differing upādhis STILL leaves distribution unseated (who is bound? the all-present can't be 'here-bound'). Final nail in avaccheda-vāda.",
    "keyPoints": ["All-present can't be here-bound.", "Final nail in limitation-theory."]
  },
  {
    "id": "6.46",
    "number": "6.46",
    "section": "Adhyāya VI · Tantra",
    "iast": "avidyaiva advaitavirodhinī",
    "devanagari": "अविद्यैव अद्वैतविरोधिनी",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Avidyā itself contradicts non-duality (548).",
    "commentary": "Avidyā-virodha (cf. I.20–24): monist's avidyā (real? unreal? both?) contradicts advaita in every alternative — compendium recalls Book I's dilemma as Vedānta's epitaph. Self-refutation complete.",
    "keyPoints": ["Real? unreal? both? — each kills monism.", "Book I's dilemma recalled as epitaph."]
  },
  {
    "id": "6.47",
    "number": "6.47",
    "section": "Adhyāya VI · Tantra",
    "iast": "anye 'pi doṣāḥ",
    "devanagari": "अन्ये ऽपि दोषाः",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Other faults in non-duality (548–549).",
    "commentary": "Doṣa-samuccaya: jīva-brahman-relation unstatable (bheda? abheda? bhedābheda? — each fails), mokṣa-śāstra voided (who seeks? who gains?), bhoga-vyavasthā inexplicable. Faults heaped — advaita collapses under accumulation.",
    "keyPoints": ["Relation unstatable three ways.", "Seeker, gain, distribution — all voided."]
  },
  {
    "id": "6.48",
    "number": "6.48",
    "section": "Adhyāya VI · Tantra",
    "iast": "na svataḥsiddhiḥ",
    "devanagari": "न स्वतःसिद्धिः",
    "conceptIds": ["purusha-sutra", "pramana-sutra"],
    "translation": "The Self cannot prove itself (549–550).",
    "commentary": "Svataḥsiddhi-niṣedha: self-proof is ātmāśraya (self-dependence fallacy) — pramāṇa needs prameya-bheda (cf. I.87 pramā-lakṣaṇa). Self is svayam-prakāśa (self-luminous, cf. I.145) yet pramāṇa-sādhya (proved) — luminosity ≠ self-proof.",
    "keyPoints": ["Luminous, yet proved.", "Self-dependence is fallacy."]
  },
  {
    "id": "6.49",
    "number": "6.49",
    "section": "Adhyāya VI · Tantra",
    "iast": "na prakāśo dharmaḥ",
    "devanagari": "न प्रकाशो धर्मः",
    "conceptIds": ["purusha-sutra"],
    "translation": "Light is no property of Self (550–553).",
    "commentary": "Prakāśa-adharma (cf. I.146): caitanya = svarūpa — property-reading imports dharma-dharmi-bheda, change, duality. Four pages defend essence-identity: light IS, never HAS, shining. Svarūpa-seal of compendium's puruṣa-doctrine.",
    "keyPoints": ["Is shining, never has it.", "Property-reading imports duality."]
  },
  {
    "id": "6.50",
    "number": "6.50",
    "section": "Adhyāya VI · Tantra",
    "iast": "saṃdigdhaśrutivivaraṇam",
    "devanagari": "संदिग्धश्रुतिविवरणम्",
    "conceptIds": ["sruti-sutra"],
    "translation": "Doubtful śrutis explained (553).",
    "commentary": "Saṃdigdha-vivaraṇa (method-summary: I.95, I.147, III.69, V.52, V.56–58, VI.31, VI.33): saguṇa/ekatva/kartrtva texts read lakṣaṇayā/upāsanayā/prakṛti-paratayā. Hermeneutic arc complete — no Veda-text left unharmonized.",
    "keyPoints": ["Every doubt harmonized.", "Hermeneutic arc complete."]
  },
  {
    "id": "6.51",
    "number": "6.51",
    "section": "Adhyāya VI · Tantra",
    "iast": "jagatsatyatvaṃ siddham",
    "devanagari": "जगत्सत्यत्वं सिद्धम्",
    "conceptIds": ["tattva-sutra"],
    "translation": "World's reality established (554–556).",
    "commentary": "Jagat-satyatva seal (cf. I.79, V.41–46): pariṇāma-realism stands — sat (as change) + vyāvahārika-niṣkampa (unsublated practice). Unreal-causes catalogued (VI.52): bhrama? no (cf. V.42); śūnya? no (V.70); vivarta? no (V.43–46).",
    "keyPoints": ["Real-as-change, steady-in-practice.", "Unreality-causes catalogued and barred."]
  },
  {
    "id": "6.52",
    "number": "6.52",
    "section": "Adhyāya VI · Tantra",
    "iast": "asattvahetavo nirastāḥ",
    "devanagari": "असत्त्वहेतवो निरस्ताः",
    "conceptIds": ["parapaksa-sutra"],
    "translation": "Unreality-causes (554).",
    "commentary": "Asattva-hetu-nirāsa: badhitatva? (sublated never — vyavahāra persists); mithyātva-śruti? (harmonized, cf. VI.50); pratibhāsa-mātra? (needs ground, cf. V.45). Causes of unreality-claims severally voided.",
    "keyPoints": ["Never sublated in practice.", "Appearance needs ground."]
  },
  {
    "id": "6.53",
    "number": "6.53",
    "section": "Adhyāya VI · Tantra",
    "iast": "viśvavarṇanam",
    "devanagari": "विश्ववर्णनम्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Universe described (554–555).",
    "commentary": "Viśva-varṇana: caturdaśa-bhuvana (cf. III.46–50) + kāla-cakra (sarga-pralaya-pravāha, cf. III.55, V.11) + tattva-saṃsthāna (25-fold, cf. old 2.2) — compendium's cosmology in one vista. Description crowns proof.",
    "keyPoints": ["Fourteen worlds, time-wheel, twenty-five.", "Cosmology in one vista."]
  },
  {
    "id": "6.54",
    "number": "6.54",
    "section": "Adhyāya VI · Tantra",
    "iast": "chāndogya-brahmabindvoḥ samanvayaḥ",
    "devanagari": "छान्दोग्यब्रह्मबिन्द्वोः समन्वयः",
    "conceptIds": ["sruti-sutra"],
    "translation": "Chāndogya VI.i.4 and Brahmabindu 10 harmonized (556).",
    "commentary": "'Vācārambhaṇaṃ vikāro' (clay-pot-cloth examples): upādāna-paratva confirmed — effects are name-forms (nāmarūpa) of persisting stuff (cf. I.118 kāraṇa-bhāva, I.120 āvirbhāva). Satkārya's śruti-crown.",
    "keyPoints": ["Name-forms of persisting stuff.", "Satkārya's scriptural crown."]
  },
  {
    "id": "6.55",
    "number": "6.55",
    "section": "Adhyāya VI · Tantra",
    "iast": "nityaṃ viśvam akṛtrimam",
    "devanagari": "नित्यं विश्वम् अकृत्रिमम्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Universe ever-existent, never created (556–557).",
    "commentary": "Nitya-viśva (pravāhataḥ): sarga-pralaya cycles beginninglessly (cf. I.122 bīja-aṅkura, V.11) — 'creation' = manifestation-phase (āvirbhāva, cf. I.120), never ex-nihilo-start. Eternity-of-flow, novelty-of-phase.",
    "keyPoints": ["Cycles beginningless.", "Creation = manifestation-phase."]
  },
  {
    "id": "6.56",
    "number": "6.56",
    "section": "Adhyāya VI · Tantra",
    "iast": "ahaṅkārasya kartṛtvam",
    "devanagari": "अहङ्कारस्य कर्तृत्वम्",
    "conceptIds": ["tattva-sutra"],
    "translation": "Agency belongs to ahaṅkāra (557).",
    "commentary": "Ahaṅkāra-kartṛtva seal (cf. I.16, II.16): abhimāna appropriates buddhi-determinations as 'mine-doing' — agency's seat fixed finally. Puruṣa-akartṛtva (cf. I.19-old/VI.17?) stands by exclusion: agency found elsewhere.",
    "keyPoints": ["Appropriation is agency's seat.", "Found elsewhere, denied to Self."]
  },
  {
    "id": "6.57",
    "number": "6.57",
    "section": "Adhyāya VI · Tantra",
    "iast": "bhogoparamaḥ vivekataḥ",
    "devanagari": "भोगोपरमः विवेकतः",
    "conceptIds": ["bhoga-sutra", "viveka-sutra"],
    "translation": "Experience ends — when? By discrimination (557–558).",
    "commentary": "Bhogoparama-kāla: bhoga ends at viveka-khyāti (not at death — corpse of ajñānin? bhoga continues subtly, cf. III.7; not at pralaya — resumes, cf. III.55). End-condition, not end-time: viveka whenever ripened.",
    "keyPoints": ["Ends by discrimination, not date.", "Condition, never calendar."]
  },
  {
    "id": "6.58",
    "number": "6.58",
    "section": "Adhyāya VI · Tantra",
    "iast": "ūrdhvalokāt punarjanma",
    "devanagari": "ऊर्ध्वलोकात् पुनर्जन्म",
    "conceptIds": ["bandha-sutra"],
    "translation": "Rebirth follows higher worlds (558–559).",
    "commentary": "Ūrdhva-punarjanma (cf. I.82–83, III.52–53): kṣīṇa-puṇya falls — heaven-exit mechanics (merit-exhaustion + aviveka-persistence). Higher instruction avails not (VI.59): deva-bhoga distracts from viveka-abhyāsa — heavens are schools without teachers.",
    "keyPoints": ["Merit exhausts; non-wisdom persists.", "Heavens distract from practice."]
  },
  {
    "id": "6.59",
    "number": "6.59",
    "section": "Adhyāya VI · Tantra",
    "iast": "ūrdhvopadeśo na phalati",
    "devanagari": "ऊर्ध्वोपदेशो न फलति",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Higher instruction avails not (559).",
    "commentary": "Ūrdhva-upadeśa-vaiyarthya: devas, drunk on sukha, can't hear duḥkha-upadeśa (cf. III.50 madhuman-liberability) — doubtful śruti harmonized (VI.60: deva-jñāna-texts read arthavāda-praise, cf. V.29). Earth alone is karma-bhūmi.",
    "keyPoints": ["Drunk on joy, deaf to truth.", "Earth alone is deed-ground."]
  },
  {
    "id": "6.60",
    "number": "6.60",
    "section": "Adhyāya VI · Tantra",
    "iast": "saṃdigdhaśrutiḥ arthavādaḥ",
    "devanagari": "संदिग्धश्रुतिः अर्थवादः",
    "conceptIds": ["sruti-sutra"],
    "translation": "Doubtful śruti (on deva-wisdom) is eulogy (559–560).",
    "commentary": "Arthavāda-reading (method V.29, V.58): deva-jñāna praises goad humans (udvejet? — 'even gods seek...'), never assert deva-adhikāra. Praise-function, not doctrine-function — genre decides (cf. V.58).",
    "keyPoints": ["Praise goads; never doctrines.", "Genre decides sense again."]
  },
  {
    "id": "6.61",
    "number": "6.61",
    "section": "Adhyāya VI · Tantra",
    "iast": "vibhoḥ gamanam aupādhikam",
    "devanagari": "विभोः गमनम् औपाधिकम्",
    "conceptIds": ["purusha-sutra", "sruti-sutra"],
    "translation": "The all-present's going is adjunct-based (560–562).",
    "commentary": "Vibhu-gamana (cf. I.48–51): ghaṭākāśa-nyāya restated compendium-final — upādhi-gati, never svarūpa-gati. Three pages settle eschatology's grammar: going-language always vehicle-language.",
    "keyPoints": ["Pot moves; sky 'moves.'", "Going-language always vehicle-language."]
  },
  {
    "id": "6.62",
    "number": "6.62",
    "section": "Adhyāya VI · Tantra",
    "iast": "jīvātmatvaṃ sopādhitvāt",
    "devanagari": "जीवात्मत्वं सोपाधित्वात्",
    "conceptIds": ["purusha-sutra"],
    "translation": "Jīva-hood is adjuncthood (561) — when/why so called.",
    "commentary": "Jīva-lakṣaṇa: sopādhi-puruṣa = jīva (prāṇa-dhāraṇa + bhoga-yogyatā); nirupādhi = paramātman/kevalin. When? — in vyavahāra; why? — bhoga-vyavasthā needs subjects (cf. I.143–144). Terminology final.",
    "keyPoints": ["Adjunct-clad = jīva.", "Unclad = supreme Self."]
  },
  {
    "id": "6.63",
    "number": "6.63",
    "section": "Adhyāya VI · Tantra",
    "iast": "ānandāropas tu bhogānuvādāt",
    "devanagari": "आनन्दारोपस् तु भोगानुवादात्",
    "conceptIds": ["purusha-sutra"],
    "translation": "Ānanda-attribution follows enjoyment-report (562).",
    "commentary": "Ānanda-āropa-hetu (cf. V.55–58): mukta described 'blissful' because duḥkha-nivṛtti FEELS blissful to reporters (bhoga-bhāṣā), never because bliss is svarūpa. Attribution explained without essence-compromise.",
    "keyPoints": ["Report-language, not essence.", "Relief feels blissful; freedom simply is."]
  },
  {
    "id": "6.64",
    "number": "6.64",
    "section": "Adhyāya VI · Tantra",
    "iast": "dehasthitiḥ ātmasāpekṣā",
    "devanagari": "देहस्थितिः आत्मसापेक्षा",
    "conceptIds": ["linga-sutra"],
    "translation": "Body's standing depends on Self (562–563).",
    "commentary": "Deha-ātma-sāpekṣatva: corpse collapses when adhiṣṭhātṛ withdraws (cf. III.8 subtle-proved-by-absence) — body borrows standing, never owns it. Dependence-hierarchy: deha < liṅga < puruṣa-sānnidhya.",
    "keyPoints": ["Corpse proves borrowed standing.", "Body borrows; never owns."]
  },
  {
    "id": "6.65",
    "number": "6.65",
    "section": "Adhyāya VI · Tantra",
    "iast": "nādṛṣṭād dehanirmāṇam",
    "devanagari": "नादृष्टाद् देहनिर्माणम्",
    "conceptIds": ["linga-sutra"],
    "translation": "Body-formation needs more than adṛṣṭa (563–565).",
    "commentary": "Adṛṣṭa-aparyāpti: merit alone builds no bodies (cf. I.30–31 adṛṣṭa-limits, V.114 ātma-nirmātṛtva) — needs prakṛti-upādāna + puruṣa-sānnidhya + karma-niyama. Triumvirate of embodiment: stuff, witness, law.",
    "keyPoints": ["Merit alone builds nothing.", "Stuff, witness, law — three needed."]
  },
  {
    "id": "6.66",
    "number": "6.66",
    "section": "Adhyāya VI · Tantra",
    "iast": "jīvaḥ puruṣaḥ paramātmā ca",
    "devanagari": "जीवः पुरुषः परमात्मा च",
    "conceptIds": ["purusha-sutra"],
    "translation": "Jīva, puruṣa, paramātman distinguished (565–567).",
    "commentary": "Tri-śabda-viveka: jīva (sopādhi-bhoktṛ), puruṣa (tattva-caitanya), paramātman (muktāvasthā-puruṣa / prakarṣa-vivakṣā?) — one reality, three functional names (cf. VI.62). Terminology-triangle closes subject-language.",
    "keyPoints": ["One reality, three functions.", "Clad, conscious, supreme — names, not tiers."]
  },
  {
    "id": "6.67",
    "number": "6.67",
    "section": "Adhyāya VI · Tantra",
    "iast": "ahaṅkāro hetuḥ neśvaraḥ",
    "devanagari": "अहङ्कारो हेतुः नेश्वरः",
    "conceptIds": ["tattva-sutra", "ishvara-sutra"],
    "translation": "Ahaṅkāra, not īśvara, is the cause (567–568).",
    "commentary": "Ahaṅkāra-hetutva seal (cf. I.72–73, VI.56): sarga-agency sits in ahaṅkāra-tattva, never in puruṣa-īśvara (unproved, cf. V.2–7). Brahmā-Viṣṇu-Rudra are vyāvahārika-īśvaras (VI.68): function-lords (sṛṣṭi-sthiti-laya offices), never metaphysical makers.",
    "keyPoints": ["Ego-principle, not God, makes.", "Trimūrti hold offices, not makerhood."]
  },
  {
    "id": "6.68",
    "number": "6.68",
    "section": "Adhyāya VI · Tantra",
    "iast": "vyāvahārikā brahmādayaḥ",
    "devanagari": "व्यावहारिका ब्रह्मादयः",
    "conceptIds": ["ishvara-sutra"],
    "translation": "Brahmā, Viṣṇu, Rudra are practical īśvaras (568).",
    "commentary": "Vyāvahārika-īśvaratva (cf. III.58): office-holders (adhikāri-puruṣas) called īśvara by function-magnitude — worship-worthy (cf. V.117 brahma-śabda), never creator-metaphysical. Devotion honored, metaphysics guarded.",
    "keyPoints": ["Offices honored; makerhood declined.", "Devotion kept; confusion barred."]
  },
  {
    "id": "6.69",
    "number": "6.69",
    "section": "Adhyāya VI · Tantra",
    "iast": "ahaṅkārasya na cetanahetuḥ",
    "devanagari": "अहङ्कारस्य न चेतनहेतुः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Ahaṅkāra has no intelligent cause (568–569).",
    "commentary": "Acetana-hetutva: ahaṅkāra rises from mahat (acetana) by guṇa-kṣobha (cf. I.72–73) — demanding cetana-cause regresses (who caused that cause's causing?). Other īśvara-functions accounted (VI.70): supervision = sānnidhya (cf. I.96), grace = yogyatā-response (cf. III.74).",
    "keyPoints": ["Unconscious rises from unconscious-lawfully.", "Supervision = presence; grace = fitness-response."]
  },
  {
    "id": "6.70",
    "number": "6.70",
    "section": "Adhyāya VI · Tantra",
    "iast": "mahadupādhiḥ viṣṇuḥ nityasambandhaḥ kapila ekaḥ",
    "devanagari": "महदुपाधिः विष्णुः नित्यसम्बन्धः कपिल एकः",
    "conceptIds": ["parampara-sutra"],
    "translation": "Mahat is Viṣṇu's vesture; the tie is eternal; Kapila is one — tie-dissolution is the Good.",
    "commentary": "Samāpana-cluster (570–575): mahat = Viṣṇu's upādhi (causal-Brahman in Sāṅkhya idiom, cf. III.58); prakṛti-puruṣa relation eternal (anādi, cf. VI.10); Pañcaśikha/Sanandana concur (571–573); whatever its form, tie-dissolution (saṃyoga-bhaṅga) is supreme Good (573–575); Kapila is one Viṣṇu-avatāra (not Agni's, 574) — founder-identity sealed. Thus the Ṣaṣṭitantra ends: one Kapila, one tie, one dissolution, one Good.",
    "keyPoints": ["Viṣṇu wears mahat as vesture.", "One Kapila; one tie; one dissolution; one Good."]
  }
];
