/**
 * Sāṅkhya-Pravacana-Sūtra, Adhyāya III · Vairāgya/Viveka-mārga (3.1–3.84).
 * Topics: gross/subtle bodies, liṅga-deha (1–22) · jñāna sole means,
 * dhyāna-sādhanas (23–36) · pratyaya-sarga 5/28/9/8 + subdivisions (37–45) ·
 * vyasti-sarga, three worlds (46–51) · higher worlds/prakṛtilaya refuted,
 * spontaneity, pralaya (52–67) · one/many release, dancer, bandha/mokṣa of
 * prakṛti, viveka-development, jīvanmukta (68–84).
 */
export const samkhyaSutraEn3: any[] = [
  {
    "id": "3.1",
    "number": "3.1",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "sthūlabhūtānāṃ tanmātrebhyaḥ",
    "devanagari": "स्थूलभूतानां तन्मात्रेभ्यः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Gross elements come from the subtle elements.",
    "commentary": "Sthūla-utpatti (pp.278): five mahābhūtas condense from five tanmātras (cf. II.10 krama). Book III opens with embodiment's stuff — body before bondage, cosmology before soteriology.",
    "keyPoints": ["Gross condenses from subtle.", "Embodiment's material basis first."]
  },
  {
    "id": "3.2",
    "number": "3.2",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "tebhyaḥ śarīrasya",
    "devanagari": "तेभ्यः शरीरस्य",
    "conceptIds": ["linga-sutra"],
    "translation": "From them, the body.",
    "commentary": "Śarīra-utpatti (p.279): sthūla-deha coalesces from bhūtas for bhoga. Body is bhogāyatana (experience-house) — built, not given; hence analyzable and transcendable.",
    "keyPoints": ["Body coalesces from elements.", "Built house, not eternal home."]
  },
  {
    "id": "3.3",
    "number": "3.3",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "tataḥ saṃsāraḥ",
    "devanagari": "ततः संसारः",
    "conceptIds": ["bandha-sutra"],
    "translation": "Thence saṃsāra (originates).",
    "commentary": "Saṃsāra-utpatti (279–280): body + aviveka + karma → birth-series. Origination avowed so cessation can be engineered — saṃsāra has hetu, hence has anta (III.4).",
    "keyPoints": ["Saṃsāra has origin — hence end.", "Body + aviveka + karma = series."]
  },
  {
    "id": "3.4",
    "number": "3.4",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "sahetutvāt sāntaḥ",
    "devanagari": "सहेतुत्वात् सान्तः",
    "conceptIds": ["bandha-sutra", "viveka-sutra"],
    "translation": "Being caused, it has an end.",
    "commentary": "Sahetuka → sānta: whatever begins by causes ends by cause-removal (cf. I.121 laya). Saṃsāra's limit (280–281) is viveka — caused-series logic guarantees mokṣa's possibility.",
    "keyPoints": ["Caused things end.", "Saṃsāra's causedness guarantees exit."]
  },
  {
    "id": "3.5",
    "number": "3.5",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "nityamuktaḥ puruṣo 'nubhavāt",
    "devanagari": "नित्यमुक्तः पुरुषो ऽनुभवात्",
    "conceptIds": ["purusha-sutra"],
    "translation": "Puruṣa is ever free from experience (as His nature).",
    "commentary": "Nitya-mukta restated (281–282, cf. I.86): anubhava touches upādhi, never svarūpa. Experience belongs to the series (III.3–4); freedom belongs to eternity. The experiencer-experience split sealed.",
    "keyPoints": ["Experience is serial; freedom eternal.", "Puruṣa never enters the series."]
  },
  {
    "id": "3.6",
    "number": "3.6",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "sthūlasūkṣmayoḥ bhedaḥ",
    "devanagari": "स्थूलसूक्ष्मयोः भेदः",
    "conceptIds": ["linga-sutra"],
    "translation": "Gross and subtle bodies are distinct.",
    "commentary": "Deha-bheda (282–283): sthūla (mātāpitṛja, putrefying) vs sūkṣma/liṅga (persisting vehicle). Confusing them breeds dehātma-bhrama; distinguishing them locates transmigration correctly.",
    "keyPoints": ["Two bodies, two fates.", "Perishing vs persisting distinguished."]
  },
  {
    "id": "3.7",
    "number": "3.7",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "saṃsarato 'py anubhavaḥ",
    "devanagari": "संसरतो ऽप्य् अनुभवः",
    "conceptIds": ["bhoga-sutra"],
    "translation": "Experience occurs even while transmigrating.",
    "commentary": "Garbha-svapna-antara states (p.283): the transmigrating liṅga experiences (dreams, womb-pains, heavens/hells between births). Bhoga isn't body-bound — subtle states also ripen karma.",
    "keyPoints": ["Between-births experience is real.", "Bhoga exceeds gross embodiment."]
  },
  {
    "id": "3.8",
    "number": "3.8",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "sūkṣma eva bhogayati na sthūlaḥ",
    "devanagari": "सूक्ष्म एव भोगयति न स्थूलः",
    "conceptIds": ["linga-sutra", "bhoga-sutra"],
    "translation": "The subtle alone makes puruṣa experience — not the gross.",
    "commentary": "Bhoga-kartṛ is liṅga (283–284): corpse (gross intact, subtle gone) experiences nothing; fainting (gross intact, subtle withdrawn) likewise. Presence/absence test proves subtle-body agency.",
    "keyPoints": ["Corpse proves gross insufficient.", "Subtle presence = experience on/off switch."]
  },
  {
    "id": "3.9",
    "number": "3.9",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "saptadaśakaṃ liṅgam",
    "devanagari": "सप्तदशकं लिङ्गम्",
    "conceptIds": ["linga-sutra"],
    "translation": "The liṅga is seventeenfold — not eighteen.",
    "commentary": "Liṅga-gaṇanā (284–285): buddhi + ahaṅkāra + manas + 10 indriyas + 5 tanmātras = 18? No — seventeen: manas counted within eleven yet liṅga-lists merge (Aniruddha's 18 criticized; siddhānta 17). Count controversy recorded and settled.",
    "keyPoints": ["Seventeen, not eighteen.", "Aniruddha's count corrected."]
  },
  {
    "id": "3.10",
    "number": "3.10",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "dhāryādhārabhedena vividham",
    "devanagari": "धार्याधारभेदेन विविधम्",
    "conceptIds": ["linga-sutra"],
    "translation": "As container and contained, it is twofold.",
    "commentary": "Dhārya (tanmātras/contents carried) vs ādhāra (buddhi-ādi carriers, p.284): liṅga is both vehicle and freight. Container persists across freight-changes (lives) — explaining continuity amid total body-change.",
    "keyPoints": ["Vehicle and freight distinguished.", "Container persists; contents change."]
  },
  {
    "id": "3.11",
    "number": "3.11",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "ekasmād bahūnāṃ vyaktivaiṣamyāt",
    "devanagari": "एकस्माद् बहूनां व्यक्तिवैषम्यात्",
    "conceptIds": ["linga-sutra"],
    "translation": "From one subtle stock, many individuals — by manifestation-variety.",
    "commentary": "Eka-liṅga → bahu-vyakti (286–287): one prakṛti-stock individuates by karma-vaiṣamya (cf. III.51) into countless liṅgas. Manifoldness is vyakti (expression), never mūla-plurality — one ocean, many waves.",
    "keyPoints": ["One stock, many expressions.", "Karma-variety individuates."]
  },
  {
    "id": "3.12",
    "number": "3.12",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "nādhiṣṭhānaṃ vinā liṅgasthitiḥ chāyācitravat",
    "devanagari": "नाधिष्ठानं विना लिङ्गस्थितिः छायाचित्रवत्",
    "conceptIds": ["linga-sutra"],
    "translation": "The liṅga stands not alone without its vehicle — like shadow or picture.",
    "commentary": "Adhiṣṭhāna-deha (vehicular subtle body, 288–290) required: liṅga needs sūkṣma-āśraya as shadow needs surface, picture canvas. Three bodies: liṅga (persists), adhiṣṭhāna (vehicle), sthūla (gross house).",
    "keyPoints": ["Shadow needs wall; liṅga needs vehicle.", "Three bodies: persisting, vehicular, gross."]
  },
  {
    "id": "3.13",
    "number": "3.13",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "saṃhatatvād api piṇḍāpekṣā sūryavat",
    "devanagari": "संहतत्वाद् अपि पिण्डापेक्षा सूर्यवत्",
    "conceptIds": ["linga-sutra"],
    "translation": "Though corporate, it needs mass-association — as the sun (needs orbs to shine through).",
    "commentary": "Saṃhata (composite) liṅga needs piṇḍa (mass) to act through — sūrya needs maṇḍala to burn. Subtlety doesn't mean independence: function needs embodiment at every level.",
    "keyPoints": ["Composite needs mass to act.", "Subtlety ≠ self-sufficiency."]
  },
  {
    "id": "3.14",
    "number": "3.14",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "aṇuparimāṇaṃ kriyāśruteḥ",
    "devanagari": "अणुपरिमाणं क्रियाश्रुतेः",
    "conceptIds": ["linga-sutra"],
    "translation": "Atomic-sized — śruti declares it acts (through narrow passages).",
    "commentary": "Aṇu-parimāṇa (291–292): liṅga traverses nāḍīs, exits by brahmarandhra, enters wombs — atomic mobility. 'Acts' (kriyā-śruti) implies finite locus; vibhu cannot migrate.",
    "keyPoints": ["Migration needs finitude.", "Narrow-passage travel proves atomicity."]
  },
  {
    "id": "3.15",
    "number": "3.15",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "annamayādisiddheḥ",
    "devanagari": "अन्नमयादिसिद्धेः",
    "conceptIds": ["linga-sutra", "sruti-sutra"],
    "translation": "And śruti declares it food-formed (finite).",
    "commentary": "'Annamayaṃ hi saumya manaḥ' (Chāndogya VI): mind fed by food — formed, hence finite. Second finitude-proof (p.293): what food builds, food's measure bounds.",
    "keyPoints": ["Mind is food-built.", "Built things are bounded."]
  },
  {
    "id": "3.16",
    "number": "3.16",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "puruṣārthaṃ liṅgānāṃ gamanāgamanam sūdavat",
    "devanagari": "पुरुषार्थं लिङ्गानां गमनागमनम् सूदवत्",
    "conceptIds": ["linga-sutra", "prayojana-sutra"],
    "translation": "Liṅgas migrate for puruṣa's sake — as the king's cook travels.",
    "commentary": "Gati-hetu (293–294): royal cook moves kitchen-to-kitchen for king's meals; liṅga moves womb-to-womb for puruṣa's bhoga/apavarga. Migration is service-mobility, purposive throughout.",
    "keyPoints": ["Migration serves puruṣa's table.", "Cook travels; king eats."]
  },
  {
    "id": "3.17",
    "number": "3.17",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "pañcabhautikaṃ sthūlam",
    "devanagari": "पञ्चभौतिकं स्थूलम्",
    "conceptIds": ["linga-sutra"],
    "translation": "The gross body is five-elemental.",
    "commentary": "Siddhānta (p.294): sthūla = pañca-bhūta-saṃghāta. Against 4-element (earth-air? excluding ākāśa) and 1-element (earth-only) schools next — siddhānta stated before pūrvapakṣas (18–19).",
    "keyPoints": ["Five elements compose gross body.", "Siddhānta first, rivals next."]
  },
  {
    "id": "3.18",
    "number": "3.18",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "caturbhautikam iti eke ākāśavarjanāt",
    "devanagari": "चतुर्भौतिकम् इति एके आकाशवर्जनात्",
    "conceptIds": ["linga-sutra", "parapaksa-sutra"],
    "translation": "'Four-elemental,' say some — excluding ākāśa.",
    "commentary": "Pūrvapakṣa 1 (294–295): ākāśa gives only room (avakāśa), no stuff — hence 4 stuffs suffice. Answered I.20-style: room IS contributory (enabling conjunction); exclusion arbitrary.",
    "keyPoints": ["Four-stuff view stated.", "Room is also contributory."]
  },
  {
    "id": "3.19",
    "number": "3.19",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "ekabhautikam iti apare pārthivatvadarśanāt",
    "devanagari": "एकभौतिकम् इति अपरे पार्थिवत्वदर्शनात्",
    "conceptIds": ["linga-sutra", "parapaksa-sutra"],
    "translation": "'One-elemental,' say others — earth predominating.",
    "commentary": "Pūrvapakṣa 2: pārthiva-prādhānya (body returns to earth). Answered: predominance ≠ exclusivity — senses show water/fire/air functions (taste, heat, breath) irreducible to earth.",
    "keyPoints": ["Earth-only view stated.", "Predominance is not exclusivity."]
  },
  {
    "id": "3.20",
    "number": "3.20",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "na bhautikaṃ caitanyaṃ pratyekaṃ tadadarśanāt",
    "devanagari": "न भौतिकं चैतन्यं प्रत्येकं तददर्शनात्",
    "conceptIds": ["purusha-sutra", "parapaksa-sutra"],
    "translation": "Consciousness is no elemental product — unseen in each separately.",
    "commentary": "Anti-Cārvāka battery opens (295–298): earth/water/fire/air each acetana — combination can't mint cit (cf. I.42). Emergence needs emergence-precedent; none observed. Whole lacks what parts lack.",
    "keyPoints": ["Parts dull; whole can't glow.", "Emergence without precedent is magic."]
  },
  {
    "id": "3.21",
    "number": "3.21",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "maraṇādivyavasthābhāvaprasaṅgāt",
    "devanagari": "मरणादिव्यवस्थाभावप्रसङ्गात्",
    "conceptIds": ["purusha-sutra"],
    "translation": "Else death and the like would have no regulation.",
    "commentary": "If body were conscious per se, consciousness couldn't leave while body stays (fainting, sleep) nor body persist while 'gone' (corpse-freshness). Maraṇa-vyavasthā (death-regulation) needs separable owner — puruṣa distinct from deha.",
    "keyPoints": ["Fainting unseats body-self.", "Death-regulation needs separable self."]
  },
  {
    "id": "3.22",
    "number": "3.22",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "madanaśaktivad iti cet na pariṇāmaviśeṣāt",
    "devanagari": "मदनशक्तिवद् इति चेत् न परिणामविशेषात्",
    "conceptIds": ["purusha-sutra", "parapaksa-sutra"],
    "translation": "'Like intoxicating power in mixture,' if said — no: that is special transformation (of already-potent parts).",
    "commentary": "Madaśakti-dṛṣṭānta answered: liquors' ingredients each carry latent potency (pariṇāma-viśeṣa); elements carry none of cit. Emergence from zero-potency differs from emergence from latent-potency — satkārya (I.114ff) bars the former.",
    "keyPoints": ["Mixture-potency was latent in parts.", "Zero-potency parts yield zero-potency whole."]
  },
  {
    "id": "3.23",
    "number": "3.23",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "jñānān mokṣaḥ",
    "devanagari": "ज्ञानान् मोक्षः",
    "conceptIds": ["viveka-sutra"],
    "translation": "Through knowledge, release.",
    "commentary": "Mahāvākya of Book III (p.299, Śvetāśvatara III.8 'jñātvā devam...'): jñāna = mokṣa-hetu, sole and sufficient. All sādhanas converge here; what follows (24–36) guards its sole-sufficiency.",
    "keyPoints": ["Knowledge liberates — solely.", "Śvetāśvatara confirms."]
  },
  {
    "id": "3.24",
    "number": "3.24",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "viparyayād bandhaḥ",
    "devanagari": "विपर्ययाद् बन्धः",
    "conceptIds": ["viveka-sutra", "bandha-sutra"],
    "translation": "From mistake, bondage.",
    "commentary": "Viparyaya = bandha-hetu (p.299): mistaking non-Self for Self (prakṛti/buddhi/deha as 'I'). Precise inversion of III.23 — one cause either way: aviveka binds, viveka frees. Aetiology complete.",
    "keyPoints": ["Mistake binds; knowledge frees.", "One pivot: viveka/aviveka."]
  },
  {
    "id": "3.25",
    "number": "3.25",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "niyatahetutvān na sahakāryantaraṃ na vikalpaḥ",
    "devanagari": "नियतहेतुत्वान् न सहकार्यन्तरं न विकल्पः",
    "conceptIds": ["viveka-sutra"],
    "translation": "Being the precise cause, no co-factor helps, no alternative avails.",
    "commentary": "Niyata-hetu logic (pp.299–300): light alone dispels darkness — brooms neither help (sahakāri-niṣedha) nor substitute (vikalpa-niṣedha). Karma-bhakti neither aid jñāna's liberating act nor replace it.",
    "keyPoints": ["No helpers, no substitutes.", "Light needs no broom's help."]
  },
  {
    "id": "3.26",
    "number": "3.26",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "svapnajāgaravat mithyāyathārthābhyāṃ na",
    "devanagari": "स्वप्नजागरवत् मिथ्यायथार्थाभ्यां न",
    "conceptIds": ["viveka-sutra"],
    "translation": "As sleep and waking — illusory and real — never jointly/optionally serve, so karma with knowledge frees none.",
    "commentary": "Svapna-jāgara-dṛṣṭānta (301–302): dream-tiger and real rope never co-operate for one release from fear; only waking-knowledge frees. Jñāna-karma-samuccaya refuted — mithyā cannot assist yathārtha in truth-work.",
    "keyPoints": ["Dream and waking never team up.", "Knowledge-karma synthesis refuted."]
  },
  {
    "id": "3.27",
    "number": "3.27",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "upāsyaviparyāsāt",
    "devanagari": "उपास्यविपर्यासात्",
    "conceptIds": ["viveka-sutra"],
    "translation": "For our worship-object conception is mistaken.",
    "commentary": "Upāsya-viparyāsa (p.302): meditating prakṛti-devatās as supreme mistakes upāya (means-purifiers) for upeya (end). Worship purifies citta (phala, III.28) but liberates none — object-error caps its fruit.",
    "keyPoints": ["Means mistaken for end.", "Worship purifies; it doesn't liberate."]
  },
  {
    "id": "3.28",
    "number": "3.28",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "tadviṣayatvāt phalasya cittaviśuddhiḥ",
    "devanagari": "तद्विषयत्वात् फलस्य चित्तविशुद्धिः",
    "conceptIds": ["viveka-sutra"],
    "translation": "Its fruit, being object-bound, is mind-purity.",
    "commentary": "Wherein faulty + fruit (303–304): saguṇa-upāsanā's phala = citta-śuddhi (fitness for jñāna), never sākṣātkāra. Bounded object, bounded fruit — infinite (nirguṇa) alone yields infinite (mokṣa).",
    "keyPoints": ["Finite object, finite fruit.", "Worship's wage is fitness, not freedom."]
  },
  {
    "id": "3.29",
    "number": "3.29",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "dhyānopagamāt śuddhānāṃ sarvam",
    "devanagari": "ध्यानोपगमात् शुद्धानां सर्वम्",
    "conceptIds": ["siddhi-sutra"],
    "translation": "With meditation's advent, all (powers) come to the pure — as with prakṛti (herself).",
    "commentary": "Dhyāna-accession (pp.304–305): śuddha-citta draws aiśvarya naturally, as prakṛti yields all to the fit. Siddhis arrive unpursued — pursuing them (rāga) forfeits dhyāna (III.30). Powers are by-products, never goals.",
    "keyPoints": ["Powers come unpursued to the pure.", "Pursuit forfeits meditation."]
  },
  {
    "id": "3.30",
    "number": "3.30",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "rāgakṣayo dhyānam",
    "devanagari": "रागक्षयो ध्यानम्",
    "conceptIds": ["siddhi-sutra", "vairagya-sutra"],
    "translation": "Cessation of passion is dhyāna.",
    "commentary": "Dhyāna-lakṣaṇa: rāga-kṣaya (not posture/breath — those are upāya, III.32–36). Meditation = flow of dispassion-stuff toward tattva. Samprajñāta (with seed) and asamprajñāta (seedless) both rāga-ending flows (305–306).",
    "keyPoints": ["Meditation is passion-cessation.", "Postures are means, not meditation."]
  },
  {
    "id": "3.31",
    "number": "3.31",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "vṛttinirodhāt tatsiddhiḥ",
    "devanagari": "वृत्तिनिरोधात् तत्सिद्धिः",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Through modification-inhibition, its perfection.",
    "commentary": "Nirodha → dhyāna-siddhi (305–306): vṛtti-stilling perfects flow. Yoga I.2 imported: Sāṅkhya dhyāna IS citta-vṛtti-nirodha directed to tattva (cf. II.33–34). Means and end share one mechanics.",
    "keyPoints": ["Still waves; deepen flow.", "Sāṅkhya-Yoga mechanics one."]
  },
  {
    "id": "3.32",
    "number": "3.32",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "dhāraṇāsanasvakarmabhiḥ tatsādhanam",
    "devanagari": "धारणासनस्वकर्मभिः तत्साधनम्",
    "conceptIds": ["siddhi-sutra"],
    "translation": "By dhāraṇā, āsana, sva-karma, its effecting.",
    "commentary": "Sādhana-traya (306–307): dhāraṇā (fixing), āsana (steady seat), sva-karma (stage-duties) effect dhyāna. Outer supports inner: settled body, settled breath (III.33), settled duty free mind for flow.",
    "keyPoints": ["Fix, seat, duty — three effectors.", "Outer settlement frees inner flow."]
  },
  {
    "id": "3.33",
    "number": "3.33",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "nirodhaḥ prāṇāyāmena recakapūraṇadhāraṇaiḥ",
    "devanagari": "निरोधः प्राणायामेन रेचकपूरणधारणैः",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Inhibition by breath-restraint — exhaling, inhaling, holding (is dhāraṇā).",
    "commentary": "Dhāraṇā = prāṇāyāma here (307–308): Vijñāna — recaka-pūraka-kumbhaka restrain prāṇa; Aniruddha — restrain vṛttis THROUGH breath. Breath-mind parallelism (citte calite vāyuścalati) is the lever.",
    "keyPoints": ["'Dhāraṇā' here means breath-restraint.", "Still breath; still mind follows."]
  },
  {
    "id": "3.34",
    "number": "3.34",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "sthirasukham āsanam",
    "devanagari": "स्थिरसुखम् आसनम्",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Steady and easeful is āsana (cf. Yoga II.46).",
    "commentary": "Āsana-lakṣaṇa (p.308): sthira (unshaking) + sukha (unefforting). Posture-misconception removed (p.530 → VI): āsana serves dhyāna, never replaces; agony-postures are rājas-tapas, anti-dhyāna.",
    "keyPoints": ["Steady, easeful — both required.", "Posture serves; never substitutes."]
  },
  {
    "id": "3.35",
    "number": "3.35",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "svāśramakarma sva-karma",
    "devanagari": "स्वाश्रमकर्म स्वकर्म",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Sva-karma is own-stage duties.",
    "commentary": "Sva-karma (p.309): varṇāśrama-duties done niṣkāma-style quieten citta (cf. I.85: they bind not-free but settle). Duty done disinterestedly is dhyāna's outer guard — not its substitute.",
    "keyPoints": ["Stage-duties quieten mind.", "Guard of meditation, not replacement."]
  },
  {
    "id": "3.36",
    "number": "3.36",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "vairāgyābhyāsābhyāṃ ca",
    "devanagari": "वैराग्याभ्यासाभ्यां च",
    "conceptIds": ["siddhi-sutra", "vairagya-sutra"],
    "translation": "And by dispassion and constant practice (dhyāna is wrought).",
    "commentary": "Vairāgya-abhyāsa (p.309, cf. Yoga I.12): rāga-kṣaya (vairāgya) + flow-repetition (abhyāsa) complete sādhanas. Two wings: letting-go and returning-to — neither flies alone.",
    "keyPoints": ["Let go and return — two wings.", "Yoga I.12 adopted."]
  },
  {
    "id": "3.37",
    "number": "3.37",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "viparyayabhedāḥ pañca",
    "devanagari": "विपर्ययभेदाः पञ्च",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Mistake's divisions are five (cf. Kārikā 47–48).",
    "commentary": "Viparyaya-pañcaka (310–312): tamas-moha-mahāmoha-tāmisra-andhatāmisra — 8+8+10+18+18=62 sub-varieties (III.41). First of pratyaya-sarga fifty (5+28+9+8, cf. old step-13). Nescience mapped before remedies (38–40).",
    "keyPoints": ["Five mistakes, sixty-two faces.", "Map of nescience precedes remedies."]
  },
  {
    "id": "3.38",
    "number": "3.38",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "aśaktiḥ aṣṭāviṃśatidhā",
    "devanagari": "अशक्तिः अष्टाविंशतिधा",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Incapacity is twenty-eightfold.",
    "commentary": "Aśakti (311–312): 11 organ-defects + 17 buddhi-defects (9 tuṣṭi-failures + 8 siddhi-failures). Cause-of-mistake: incapacity breeds error — structural account of why seers of truth still cannot live it.",
    "keyPoints": ["11 + 17 = 28 incapacities.", "Incapacity mothers mistake."]
  },
  {
    "id": "3.39",
    "number": "3.39",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "tuṣṭiḥ navadhā",
    "devanagari": "तुष्टिः नवधा",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Complacency is ninefold.",
    "commentary": "Tuṣṭi (p.312): 4 inner (prakṛti/upādāna/kāla/bhāgya — resting on nature/means/time/luck) + 5 outer (abstinence-from-objects mistaken for progress). Spiritual indolence: grasping release is nature's end, then stopping.",
    "keyPoints": ["4 inner + 5 outer complacencies.", "Indolence wearing wisdom's clothes."]
  },
  {
    "id": "3.40",
    "number": "3.40",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "siddhiḥ aṣṭadhā",
    "devanagari": "सिद्धिः अष्टधा",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Perfection is eightfold.",
    "commentary": "Siddhi-aṣṭaka (p.312, cf. old 3.3): ūha-śabda-adhyayana, three duḥkha-destroyers, suhṛtprāpti, dāna. Positive paths answering I.1's cry — attainment's eight doors after mapping three rooms of failure (37–39).",
    "keyPoints": ["Eight doors of attainment.", "Reasoning, teaching, study, remedies, friendship, charity."]
  },
  {
    "id": "3.41",
    "number": "3.41",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "teṣāṃ avāntarabhedāḥ dviṣaṣṭiḥ",
    "devanagari": "तेषां अवान्तरभेदाः द्विषष्टिः",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Their sub-divisions: sixty-two of mistake.",
    "commentary": "Dviṣaṣṭi-bheda (312–314): tamas 8 (ātman-mistaking prakṛti/buddhi/ahaṅkāra/tanmātras) + moha 8 + mahāmoha 10 + tāmisra 18 + andhatāmisra 18 = 62. Matches Yoga's kleśa-pañcaka expanded — avidyā-asmitā-rāga-dveṣa-abhiniveśa in Sāṅkhya dress.",
    "keyPoints": ["8+8+10+18+18 = 62.", "Yoga kleśas in Sāṅkhya mapping."]
  },
  {
    "id": "3.42",
    "number": "3.42",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "evam itareṣām api",
    "devanagari": "एवम् इतरेषाम् अपि",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Likewise of the others (sub-divisions).",
    "commentary": "Ati-deśa (314–315): incapacity's sub-varieties (organ-wise + buddhi-wise) similarly detailed — brevity by reference. Method: state paradigm (41), extend by analogy. Complacency/perfection divisions follow (43–44).",
    "keyPoints": ["Paradigm stated, rest by analogy.", "Brevity without incompleteness."]
  },
  {
    "id": "3.43",
    "number": "3.43",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "ādhyātmikādibhedena navadhā tuṣṭiḥ",
    "devanagari": "आध्यात्मिकादिभेदेन नवधा तुष्टिः",
    "conceptIds": ["siddhi-sutra"],
    "translation": "By inner-and-rest distinction, complacency is ninefold.",
    "commentary": "Tuṣṭi-vibhāga (315–319): 4 ādhyātmika (prakṛtyādinibandhanāḥ) + 5 bāhya (śabdādi-nivṛtti-mātra). Resting ON nature/means/time/luck or IN mere abstinence — both mistake pause for arrival.",
    "keyPoints": ["4 resting-on + 5 resting-in.", "Pause mistaken for arrival."]
  },
  {
    "id": "3.44",
    "number": "3.44",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "ūhādibhiḥ siddhiḥ",
    "devanagari": "ऊहादिभिः सिद्धिः",
    "conceptIds": ["siddhi-sutra"],
    "translation": "By reasoning and the rest, perfection.",
    "commentary": "Siddhi-vibhāga (319–321): ūha (Kapila's own), śabda (teaching), adhyayana (study), duḥkha-traya-vighāta-traya, suhṛt, dāna — each detailed. Other 'perfections' (aiśvarya-feats, 322–323) are not real siddhi — bhoga-traps.",
    "keyPoints": ["Eight detailed; feats excluded.", "Real perfection frees; feats bind."]
  },
  {
    "id": "3.45",
    "number": "3.45",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "anyonyābhāvād ṛte na siddhiḥ",
    "devanagari": "अन्योन्याभावाद् ऋते न सिद्धिः",
    "conceptIds": ["siddhi-sutra"],
    "translation": "Without removing each by the other, no perfection.",
    "commentary": "Aniruddha: viparyaya-aśakti-tuṣṭi must each be removed FOR siddhi (aṅkuśa-triple as goads). Vijñāna: no siddhi through alien means without removing error. Hindrances prod as they block (cf. old 3.3 aṅkuśa).",
    "keyPoints": ["Hindrances removed, not bypassed.", "Goads prod toward perfection."]
  },
  {
    "id": "3.46",
    "number": "3.46",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "devādivibhāgā vyaṣṭiḥ",
    "devanagari": "देवादिविभागा व्यष्टिः",
    "conceptIds": ["tattva-sutra"],
    "translation": "Specific creation is marked as divine and the rest.",
    "commentary": "Vyaṣṭi-sarga (323–324): divya (8 celestial), tiryak (5 sub-human), mānuṣa (1) = 14 realms (cf. Kārikās 53–54). Samaṣṭi (cosmic) individuates into lots — vyavasthā's theater built.",
    "keyPoints": ["8 + 5 + 1 = 14 realms.", "Cosmic individuates into lots."]
  },
  {
    "id": "3.47",
    "number": "3.47",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "ābrahmastambaparyantaṃ puruṣārthaṃ vivekaparyantam",
    "devanagari": "आब्रह्मस्तम्बपर्यन्तं पुरुषार्थं विवेकपर्यन्तम्",
    "conceptIds": ["prayojana-sutra"],
    "translation": "From Brahmā to grass-blade, creation serves puruṣa — till discrimination.",
    "commentary": "Bhautika-sarga parārtha (324–325): every grade, highest god to lowest stock, exists FOR puruṣa's bhoga-till-viveka. No grade exempt, none ultimate — all instrumental, all temporary.",
    "keyPoints": ["All grades instrumental.", "Service ends at discrimination."]
  },
  {
    "id": "3.48",
    "number": "3.48",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "ūrdhvaṃ sattvabahulam",
    "devanagari": "ऊर्ध्वं सत्त्वबहुलम्",
    "conceptIds": ["guna-sutra"],
    "translation": "Above, sattva abounds.",
    "commentary": "Ūrdhva-loka (325–326): 8 celestial realms sattva-bhūyiṣṭha — light, long-lived, pleasured. Altitude = sattva-altitude; cosmology maps guṇa-proportion directly onto space.",
    "keyPoints": ["Height is sattva-density.", "Gods are sattva-lots."]
  },
  {
    "id": "3.49",
    "number": "3.49",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "mūle tamobahulam",
    "devanagari": "मूले तमोबहुलम्",
    "conceptIds": ["guna-sutra"],
    "translation": "At the root, tamas abounds.",
    "commentary": "Adho-loka: 5 tiryak/paśu + naraka orders tamo-bhūyiṣṭha — heavy, deluded, suffering. Depth = tamas-density. Symmetry with III.48 completes vertical guṇa-axis.",
    "keyPoints": ["Depth is tamas-density.", "Beasts/hells are tamas-lots."]
  },
  {
    "id": "3.50",
    "number": "3.50",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "madhye rajobahulam",
    "devanagari": "मध्ये रजोबहुलम्",
    "conceptIds": ["guna-sutra"],
    "translation": "In the middle, rajas abounds.",
    "commentary": "Madhya (mānuṣa): rajo-bhūyiṣṭha — restless, mixed pleasure-pain, karma-capable. Middle alone offers mokṣa-yogyatā: enough suffering to seek, enough clarity to find. Human birth's privilege grounded.",
    "keyPoints": ["Middle is rajas-mixed.", "Human lot alone liberable."]
  },
  {
    "id": "3.51",
    "number": "3.51",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "karmavaicitryāt pradhānaceṣṭā garbhadasavat",
    "devanagari": "कर्मवैचित्र्यात् प्रधानचेष्टा गर्भदसवत्",
    "conceptIds": ["prayojana-sutra"],
    "translation": "By karma-diversity, pradhāna's operation varies — like the born slave's.",
    "commentary": "Vicitra-sṛṣṭi-hetu (p.326): one prakṛti, diverse lots — karma-vaicitrya (individual deserts) diversifies, as born-slave's smart service varies by master's need. Guṇa-sāmya + karma-vaiṣamya = ordered diversity.",
    "keyPoints": ["One cooks many dishes by orders.", "Karma-diversity diversifies one prakṛti."]
  },
  {
    "id": "3.52",
    "number": "3.52",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "na devādayaḥ paramārthāḥ",
    "devanagari": "न देवादयः परमार्थाः",
    "conceptIds": ["duhkha-sutra"],
    "translation": "Gods and the like are not the supreme good.",
    "commentary": "Deva-gati-niṣedha (326–327): celestial lots, however long, end (kṣaya, cf. I.6). Supreme (ātyantika) cannot be what exhausts — devayāna is deluxe saṃsāra, not mokṣa.",
    "keyPoints": ["Heaven ends; hence not supreme.", "Deluxe transmigration ≠ release."]
  },
  {
    "id": "3.53",
    "number": "3.53",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "duḥkham ūrdhvaloke 'pi",
    "devanagari": "दुःखम् ऊर्ध्वलोके ऽपि",
    "conceptIds": ["duhkha-sutra"],
    "translation": "Pain exists in higher worlds too.",
    "commentary": "Ūrdhva-duḥkha (p.327): gods fear fall (cyavana-bhaya), envy superiors (atiśaya-matsara), satiate into dullness. Sukha-miśra-duḥkha everywhere below viveka — no pain-free address in sarga.",
    "keyPoints": ["Gods fear falling.", "Envy and satiety pain heaven too."]
  },
  {
    "id": "3.54",
    "number": "3.54",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "na prakṛtilayaḥ paramārthaḥ",
    "devanagari": "न प्रकृतिलयः परमार्थः",
    "conceptIds": ["mukti-sutra"],
    "translation": "Merger in prakṛti is not the supreme good.",
    "commentary": "Prakṛtilaya-niṣedha (327–329): vairāgya-short-of-viveka yields absorption (sleep-like) — blissful, long, but sānta (ending). Mistaking laya for kaivalya is tuṣṭi (III.39) — the subtlest complacency.",
    "keyPoints": ["Absorption ends; hence not supreme.", "Laya mistaken for kaivalya is subtlest tuṣṭi."]
  },
  {
    "id": "3.55",
    "number": "3.55",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "layāt punarutthānam",
    "devanagari": "लयात् पुनरुत्थानम्",
    "conceptIds": ["mukti-sutra", "bandha-sutra"],
    "translation": "After merger, re-rising follows.",
    "commentary": "Punarutthāna (329–330): aviveka-vāsanā survives laya (seedci in mūla), sprouting next sarga — as sleepers wake (cf. I.40's pralaya-rise). Only jñāna-dāha (burning seeds) prevents return.",
    "keyPoints": ["Unburnt seeds sprout after laya.", "Sleep-wake models pralaya-sarga."]
  },
  {
    "id": "3.56",
    "number": "3.56",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "svātantryaṃ prakṛteḥ avighātāt",
    "devanagari": "स्वातन्त्र्यं प्रकृतेः अविघातात्",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Prakṛti's independence stands — unobstructed.",
    "commentary": "Svātantrya (p.329): absorption-and-return don't compromise her autonomy — she merges and re-emits freely. Independence-with-purpose: free yet parārtha (cf. I.18, III.60–62).",
    "keyPoints": ["Free to merge, free to re-emit.", "Autonomy compatible with service."]
  },
  {
    "id": "3.57",
    "number": "3.57",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "punarāvirbhāvaḥ śeṣasaṃskārāt",
    "devanagari": "पुनराविर्भावः शेषसंस्कारात्",
    "conceptIds": ["bandha-sutra"],
    "translation": "Re-appearance follows from residual impressions.",
    "commentary": "Prādurbhāva-hetu (330–331): śeṣa-saṃskāra (unburnt residue) re-projects worlds — proof: śruti/smṛti of repeated sargas + observed vāsanā-persistence. Residue, not will, reboots creation.",
    "keyPoints": ["Residue reboots worlds.", "No reboot without remainder."]
  },
  {
    "id": "3.58",
    "number": "3.58",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "ādipuruṣeśvaravyavahāraḥ",
    "devanagari": "आदिपुरुषेश्वरव्यवहारः",
    "conceptIds": ["ishvara-sutra"],
    "translation": "The 'first puruṣa / īśvara' usage (is practical).",
    "commentary": "Ādi-puruṣa/īśvara-vyavahāra (p.330): Kapila, Hiraṇyagarbha called 'īśvara' — vyāvahārika (practical) supremacy among puruṣas (jñāna-vairāgya-aiśvarya maxima), never pāramārthika creatorhood (cf. I.92–95, VI.67).",
    "keyPoints": ["'Īśvara' honors the foremost puruṣa.", "Practical title, not metaphysical post."]
  },
  {
    "id": "3.59",
    "number": "3.59",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "niṣedho 'pi vyāvahārikaḥ",
    "devanagari": "निषेधो ऽपि व्यावहारिकः",
    "conceptIds": ["ishvara-sutra"],
    "translation": "Denial too is (of creatorhood) — in what sense Sāṅkhya denies īśvara.",
    "commentary": "Niṣedha-maryādā (331–332): denied = nimitta-kartā (creator-governor); affirmed = mukta-puruṣa-prakarṣa (excellent free selves, siddhas). Precision prevents straw-manning both sides.",
    "keyPoints": ["Denied: creator. Affirmed: excellent freed.", "Denial has exact scope."]
  },
  {
    "id": "3.60",
    "number": "3.60",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "puruṣavimokṣārthaṃ prakṛteḥ pravṛttiḥ",
    "devanagari": "पुरुषविमोक्षार्थं प्रकृतेः प्रवृत्तिः",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Prakṛti acts for puruṣa's release.",
    "commentary": "Prayojana-sūtra (333–334): pravṛtti = vimokṣa-artha (bhoga included as release's antechamber). All evolution's telos in one word — vimokṣa. Rest of book (60–67) unpacks its mechanics.",
    "keyPoints": ["Release is evolution's telos.", "Bhoga is release's antechamber."]
  },
  {
    "id": "3.61",
    "number": "3.61",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "puruṣārthe baddhā prakṛtiḥ",
    "devanagari": "पुरुषार्थे बद्धा प्रकृतिः",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Prakṛti's interest is bound up with puruṣa's.",
    "commentary": "Baddhārthatva (p.334): her 'interest' (artha) is tied (baddha) to his — svārtha-iva-parārtha (seeming self-interest, real other-interest, cf. old 2.4/4.1). Bond of service, not of being.",
    "keyPoints": ["Her interest tied to his.", "Self-seeming, other-real."]
  },
  {
    "id": "3.62",
    "number": "3.62",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "svayam eva parārthā pravṛttiḥ",
    "devanagari": "स्वयम् एव परार्था प्रवृत्तिः",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Spontaneously, for another, she acts.",
    "commentary": "Svataḥ-parārthatva (334–335): no deliberation, no commander — milk flows, cows suckle (dṛṣṭāntas). Spontaneity + other-directedness coexist: nature's automatism IS service-automatism.",
    "keyPoints": ["No deliberation, perfect service.", "Automatism is service-automatism."]
  },
  {
    "id": "3.63",
    "number": "3.63",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "dṛṣṭāntaiḥ spaṣṭīkaraṇam",
    "devanagari": "दृष्टान्तैः स्पष्टीकरणम्",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Further illustrated by examples.",
    "commentary": "Dṛṣṭānta-samuccaya (p.335): calf-milk, magnet-iron, rain-field — unconscious fittings to needs. Examples don't prove (I.37) but display: spontaneity-for-other is nature's everyday face.",
    "keyPoints": ["Milk, magnet, rain display it.", "Examples display; proofs establish."]
  },
  {
    "id": "3.64",
    "number": "3.64",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "svabhāvasiddhā pravṛttiḥ",
    "devanagari": "स्वभावसिद्धा प्रवृत्तिः",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Her activity is nature-established.",
    "commentary": "Svabhāva-siddhi (p.336): pravṛtti needs no external hetu — guṇa-kṣobha suffices. Asking 'who moves prakṛti?' mistakes nature for artifact. Motion is her manner, not her command.",
    "keyPoints": ["Motion is manner, not command.", "No mover behind nature's move."]
  },
  {
    "id": "3.65",
    "number": "3.65",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "āvaśyakī spaṣṭatā",
    "devanagari": "आवश्यकी स्पष्टता",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Spontaneity is necessary (not optional).",
    "commentary": "Āvaśyakatva (336–337): commanded-service would need commander (regress to īśvara, refuted I.92–95); spontaneous-service needs none. Necessity, not choice — Sāṅkhya's leanest hypothesis wins.",
    "keyPoints": ["Command needs commander; spontaneity none.", "Leanest hypothesis: self-moving nature."]
  },
  {
    "id": "3.66",
    "number": "3.66",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "nivṛttiḥ api svataḥ",
    "devanagari": "निवृत्तिः अपि स्वतः",
    "conceptIds": ["nivritti-sutra"],
    "translation": "Withdrawal too is spontaneous.",
    "commentary": "Nivṛtti-svataḥ (p.337): as rivers reach sea uncommanded, prakṛti retires purpose-done (kṛtārthatā) uncommanded. Symmetry: unacted beginning, unacted ending — spontaneity all through.",
    "keyPoints": ["Rivers reach sea uncommanded.", "Purpose-done retires purpose-made."]
  },
  {
    "id": "3.67",
    "number": "3.67",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "ātyantikapralayaḥ kṛtārthatāyām",
    "devanagari": "आत्यन्तिकप्रलयः कृतार्थतायाम्",
    "conceptIds": ["nivritti-sutra", "mukti-sutra"],
    "translation": "Final dissolution comes with purpose-accomplished.",
    "commentary": "Ātyantika-pralaya (p.337): individual (not cosmic) final withdrawal per puruṣa at viveka — pralaya privatized. Cosmic pralayas cycle (III.55); ātyantika ends one's series forever.",
    "keyPoints": ["Final dissolution is per-puruṣa.", "Cosmic cycles; personal ends."]
  },
  {
    "id": "3.68",
    "number": "3.68",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "naikasya muktyā sarvamuktiḥ",
    "devanagari": "नैकस्य मुक्त्या सर्वमुक्तिः",
    "conceptIds": ["purusha-sutra"],
    "translation": "One's release is not all's release.",
    "commentary": "Vyavasthā-seal (338–339, cf. I.152–154): eka-mukti → sarva-mukti would follow only on eka-ātman. Observed: Vāmadeva freed, world bound. Plurality's empirical seal; Śvetāśvatara I.10 harmonized (III.69).",
    "keyPoints": ["Vāmadeva freed; world bound.", "One's freedom frees none else."]
  },
  {
    "id": "3.69",
    "number": "3.69",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "śvetāśvatarokteḥ samanvayaḥ",
    "devanagari": "श्वेताश्वतरोक्तेः समन्वयः",
    "conceptIds": ["sruti-sutra"],
    "translation": "The Śvetāśvatara text (I.10) is harmonized.",
    "commentary": "'Kṣarākṣara' śruti (p.338) read as kṣara (prakṛti) + akṣara (puruṣa-plurality) — not eka-Brahman. Samanvaya-method: apparent monism resolved into Sāṅkhya dual-pluralism without śruti-violence.",
    "keyPoints": ["Kṣara + akṣara = prakṛti + puruṣas.", "Apparent monism resolved dual-plural."]
  },
  {
    "id": "3.70",
    "number": "3.70",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "mokṣasvarūpaṃ kaivalyam",
    "devanagari": "मोक्षस्वरूपं कैवल्यम्",
    "conceptIds": ["mukti-sutra"],
    "translation": "Release consists in isolation.",
    "commentary": "Mokṣa-svarūpa (p.339): kaivalya = draṣṭṛ-svarūpa-sthiti (witness resting as witness), all upādhi-nivṛtti. Not ānanda-acquisition (refuted V.44ff), not loka-prāpti — cessation of misattribution, full stop.",
    "keyPoints": ["Isolation, not acquisition.", "Witness resting as witness."]
  },
  {
    "id": "3.71",
    "number": "3.71",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "ekasyaivopagrāho 'nyasya na",
    "devanagari": "एकस्यैवोपग्राहो ऽन्यस्य न",
    "conceptIds": ["abhasa-sutra"],
    "translation": "She grips one puruṣa, not another — how?",
    "commentary": "Upagrāha-vaiṣamya (339–341): same prakṛti binds X, frees Y — by buddhi-bheda (individual media differ in aviveka-density). Rope-snake error (III.72): same rope, snake to one seer, rope to another — media differ, ground one.",
    "keyPoints": ["Same ground, different media.", "Media-density decides grip."]
  },
  {
    "id": "3.72",
    "number": "3.72",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "rajjusarpatvavat",
    "devanagari": "रज्जुसर्पत्ववत्",
    "conceptIds": ["abhasa-sutra"],
    "translation": "As rope-(mistaken-for)-snake.",
    "commentary": "Rajju-sarpa-nyāya (p.341): error needs ground (rope) + defect (dusk) + seer — none is the snake. Aviveka likewise: puruṣa (ground) + buddhi-defect + non-discrimination — bondage is error's snake.",
    "keyPoints": ["Ground, defect, seer — no snake.", "Bondage is error's snake."]
  },
  {
    "id": "3.73",
    "number": "3.73",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "dvairūpyasamarthanam",
    "devanagari": "द्वैरूप्यसमर्थनम्",
    "conceptIds": ["abhasa-sutra", "prayojana-sutra"],
    "translation": "Her double character (binder-liberator) is supported.",
    "commentary": "Dvairūpya (341–342): same prakṛti binds (seven bhāvas) and frees (jñāna) — as same rope frightens and (recognized) reassures. No contradiction: capacity varies by seer's state, not ground's nature.",
    "keyPoints": ["One ground, two capacities.", "Seer's state selects capacity."]
  },
  {
    "id": "3.74",
    "number": "3.74",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "yogyatānusāreṇa varaṇam",
    "devanagari": "योग्यतानुसारेण वरणम्",
    "conceptIds": ["prayojana-sutra"],
    "translation": "Her selection follows fitness.",
    "commentary": "Varaṇa-niyama (342–343): prakṛti 'chooses' puruṣas by yogyatā (adhikāra-fitness, cf. I.70) — ripe buddhis draw viveka-manifestation, unripe draw bhoga-display. Selection is fitness-response, never favoritism.",
    "keyPoints": ["Fitness draws manifestation.", "Ripeness selects display."]
  },
  {
    "id": "3.75",
    "number": "3.75",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "dṛṣṭā mayeti nartakīnivṛttiḥ",
    "devanagari": "दृष्टा मयेति नर्तकीनिवृत्तिः",
    "conceptIds": ["nivritti-sutra"],
    "translation": "'Seen by me' — and the dancer retires.",
    "commentary": "Nartakī-nyāya (343–344, cf. Kārikā 59): performance ends at being-seen. Darśana IS nivṛtti-hetu — no second act needed. Sukumāratā: seen once, never re-entering that puruṣa's view (cf. old 4.2).",
    "keyPoints": ["Being-seen ends performance.", "No second act after darśana."]
  },
  {
    "id": "3.76",
    "number": "3.76",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "puruṣe bandhamokṣāv aupacārikau",
    "devanagari": "पुरुषे बन्धमोक्षाव् औपचारिकौ",
    "conceptIds": ["mukti-sutra", "bandha-sutra"],
    "translation": "Bondage-release in puruṣa are figurative.",
    "commentary": "Aupacārika (p.345): bandha/mokṣa-language for puruṣa is upacāra (courtesy-speech) — real events in prakṛti (III.77). Like 'the king is victorious' (army fought). Grammar of liberation corrected.",
    "keyPoints": ["'King victorious' — army fought.", "Liberation-language is courtesy-speech."]
  },
  {
    "id": "3.77",
    "number": "3.77",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "prakṛteḥ eva tau",
    "devanagari": "प्रकृतेः एव तौ",
    "conceptIds": ["mukti-sutra"],
    "translation": "Both are prakṛti's alone.",
    "commentary": "Prakṛti-bandha-mokṣa (345–346): she transmigrates, binds, releases (nānāśrayā, cf. old 6.4). Puruṣa ever-mukta witnesses her drama — audience never enters stage by watching.",
    "keyPoints": ["She migrates, binds, frees.", "Audience never enters stage."]
  },
  {
    "id": "3.78",
    "number": "3.78",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "saptabhis tāṃ badhnāti ekayā mocayati",
    "devanagari": "सप्तभिस् तां बध्नाति एकया मोचयति",
    "conceptIds": ["viveka-sutra", "buddhi-sutra"],
    "translation": "By seven she binds herself; by one she frees herself.",
    "commentary": "Sapta-eka-nyāya (346–347, cf. Kārikā 63): buddhi's eight bhāvas — dharma/adharma/vairāgya-av... seven bind, jñāna frees. Prakṛti auto-binds/auto-frees — puruṣa uninvolved in both. Mechanism of III.77 detailed.",
    "keyPoints": ["Seven bind, one frees.", "Auto-bondage, auto-release."]
  },
  {
    "id": "3.79",
    "number": "3.79",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "avivekaḥ svayaṃ na bandhaḥ",
    "devanagari": "अविवेकः स्वयं न बन्धः",
    "conceptIds": ["bandha-sutra", "viveka-sutra"],
    "translation": "Non-discrimination itself is not bondage.",
    "commentary": "Aviveka ≠ bandha (347–348): aviveka is hetu (cause), bandha is saṃyoga-phala (cf. I.19). Confusing cause with state breeds sādhanā-errors (fighting thoughts vs removing ignorance). Precision guards practice.",
    "keyPoints": ["Cause distinguished from state.", "Fight ignorance, not thoughts."]
  },
  {
    "id": "3.80",
    "number": "3.80",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "tattvābhyāsāt vivekavṛddhiḥ",
    "devanagari": "तत्त्वाभ्यासात् विवेकवृद्धिः",
    "conceptIds": ["viveka-sutra"],
    "translation": "By tattva-cultivation, discrimination grows.",
    "commentary": "Viveka-vṛddhi-krama (348–352): śravaṇa → manana → tattvābhyāsa (repeated dwelling on 24 non-Self tattvas) → aparokṣa. Growth, not leap — abhyāsa matures (cf. II.2–3 vāsanā-wearing). Five pages detail the ascent.",
    "keyPoints": ["Growth, not leap.", "Dwelling matures into seeing."]
  },
  {
    "id": "3.81",
    "number": "3.81",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "apavādo jñāninaḥ prārabdhe",
    "devanagari": "अपवादो ज्ञानिनः प्रारब्धे",
    "conceptIds": ["mukti-sutra"],
    "translation": "Exception: for the knower, prārabdha (runs on).",
    "commentary": "Apavāda (p.352): viveka burns sañcita/āgāmi, not prārabdha — jñānin lives on (cf. old 4.4 cakra). Exception proves rule's scope: knowledge ends ownership, not embodiment. Jīvanmukti grounded (III.83–84).",
    "keyPoints": ["Burnt seeds, spinning wheel.", "Ownership ends; embodiment lingers."]
  },
  {
    "id": "3.82",
    "number": "3.82",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "śuddhaviveka eva mokṣahetuḥ",
    "devanagari": "शुद्धविवेक एव मोक्षहेतुः",
    "conceptIds": ["viveka-sutra"],
    "translation": "Pure viveka alone causes release.",
    "commentary": "Śuddha-viveka (352–354): unmixed (niṣkāma-karma-free, upāsanā-free) discrimination alone liberates — restating III.23–26 at book's climax. Purity = exclusivity: admixture dilutes, never aids.",
    "keyPoints": ["Pure alone; admixture dilutes.", "Climax restates III.23 with proof-complete."]
  },
  {
    "id": "3.83",
    "number": "3.83",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "asamprajñātāt tatsiddhiḥ jīvanmuktisthitiś ca",
    "devanagari": "असम्प्रज्ञातात् तत्सिद्धिः जीवन्मुक्तिस्थितिश् च",
    "conceptIds": ["viveka-sutra", "mukti-sutra"],
    "translation": "Through seedless (yoga) its perfection — and the living-freed state stands.",
    "commentary": "Asamprajñāta as viveka-siddhy-upāya (p.353): nirbīja-samādhi burns mūla-vāsanā, perfecting viveka into dharmamegha-like irreversibility. Jīvanmukta considered (354): Nāradiya-smṛti definition; only jīvanmuktas guide (355).",
    "keyPoints": ["Seedless burns root-habit.", "Living-freed alone can guide."]
  },
  {
    "id": "3.84",
    "number": "3.84",
    "section": "Adhyāya III · Viveka-mārga",
    "iast": "viveka eva kevalo mokṣamārgaḥ pramāṇaiḥ",
    "devanagari": "विवेक एव केवलो मोक्षमार्गः प्रमाणैः",
    "conceptIds": ["viveka-sutra", "mukti-sutra"],
    "translation": "Viveka alone is release's sole road — by proofs (and lived witnesses).",
    "commentary": "Samāpana (354–360): jīvanmukti proved (śruti/smṛti/yukti — post-release embodiment explained, 356–359: prārabdha-unavoidability), viveka-only sealed (359–360). Book III ends where practice begins: discriminated life. Next: fables for the path (Book IV).",
    "keyPoints": ["Living release proved threefold.", "Viveka-only sealed; fables next."]
  }
];
