// Vijñānabhairava pedagogical thread: flat curated sequence of concepts with
// connective narratives and go-deeper verse links (all 118 verses covered).
export const vijnanabhairavaThreadEn: any[] = [
  {
    id: 'vb-step-1',
    conceptId: 'vb-frame',
    verseIds: ['VB-F1', 'VB-F2', 'VB-F3', 'VB-F4'],
    title: 'The question that wants method',
    narrative: 'Devī already knows scripture and asks for what scripture cannot give: the essence by which Bhairava is known directly. Bhairava’s answer sets the whole text’s contract — one condition (one-pointed attention), then 112 doors. Grace here takes the form of usable practice, and every step below is that grace itemised.',
  },
  {
    id: 'vb-step-2',
    conceptId: 'vb-breath',
    verseIds: ['VB-1', 'VB-2', 'VB-3', 'VB-4', 'VB-5', 'VB-6', 'VB-7', 'VB-8', 'VB-9', 'VB-10', 'VB-11', 'VB-12'],
    title: 'Breath: the pauses that stop the mind',
    narrative: 'Begin where you always are: breathing. The turn-points of breath, its far limit and heart-home, its self-sounding haṃsa, its fullness that neither rises nor falls — each is a door because mind follows breath. Still the breath at the right place and thought, its shadow, stills itself.',
  },
  {
    id: 'vb-step-3',
    conceptId: 'vb-energy-body',
    verseIds: ['VB-13', 'VB-14', 'VB-15', 'VB-16', 'VB-17', 'VB-18', 'VB-19', 'VB-20', 'VB-21', 'VB-22', 'VB-23', 'VB-24'],
    title: 'The subtle body: fire, lotus, ascent',
    narrative: 'From breath to the body of energy: navel-fire rising through the middle channel, the crown-void where ascent settles, heart-lotus and brow-dissolution, inner sound, whole-frame pervasion, skin become space, palate-nectar, the navel’s zodiac, the wakened serpent, the stations past the crown — until the body is rebuilt as living mantra.',
  },
  {
    id: 'vb-step-4',
    conceptId: 'vb-sound',
    verseIds: ['VB-25', 'VB-26', 'VB-27', 'VB-28', 'VB-29', 'VB-30', 'VB-31', 'VB-32', 'VB-33', 'VB-34', 'VB-35', 'VB-36'],
    title: 'Sound: climbing back to the Word',
    narrative: 'Every sound came down four levels; these gates climb them back — fading resonance, OṂ’s after-silence, hearing taken apart level by level, music that melts the listener, sealed-ear thunder led to the crown, the single central tone, japa thinned to intent — until all sounds are heard evenly as one absolute tone.',
  },
  {
    id: 'vb-step-5',
    conceptId: 'vb-void',
    verseIds: ['VB-37', 'VB-38', 'VB-39', 'VB-40', 'VB-41', 'VB-42', 'VB-43', 'VB-44', 'VB-45', 'VB-46', 'VB-47', 'VB-48'],
    title: 'Void: emptiness that is full',
    narrative: 'The great corrective sequence: things as bubbles, body as hollow, outer void mirroring inner, time and direction dissolved, bodilessness, sleep’s threshold, swoon’s aware darkness, moonless nights within and without — rising to the summit that saves the whole series from nihilism: void is plenum, emptiness of objects being fullness of awareness.',
  },
  {
    id: 'vb-step-6',
    conceptId: 'vb-light',
    verseIds: ['VB-49', 'VB-50', 'VB-51', 'VB-52', 'VB-53', 'VB-54', 'VB-55', 'VB-56', 'VB-57', 'VB-58', 'VB-59', 'VB-60'],
    title: 'Light: seeing that sees itself',
    narrative: 'The eye’s education: points that bloom, suns reclaimed as one’s own, aimless gazing, the half-lidded twilight where outer and inner meet, the Self contemplated as self-shining lamp, dawns synchronised, dream-lucidity, fires that burn everything but the witness — until remembrance holds steady: whatever shines is Bhairava shining.',
  },
  {
    id: 'vb-step-7',
    conceptId: 'vb-senses',
    verseIds: ['VB-61', 'VB-62', 'VB-63', 'VB-64', 'VB-65', 'VB-66', 'VB-67', 'VB-68', 'VB-69', 'VB-70'],
    title: 'Senses: immersion without grasping',
    narrative: 'The tantric reversal stated ten ways: instead of withdrawing from sense-life, enter it without the owner-frame — touch without toucher, taste without taster, beauty without naming, the gap before recognition, pain without story, passion’s eye stood inside, satisfaction dwelt in — closing, where needed, with the tortoise-gesture: all doors shut at once, sovereignty within.',
  },
  {
    id: 'vb-step-8',
    conceptId: 'vb-bliss',
    verseIds: ['VB-71', 'VB-72', 'VB-73', 'VB-74', 'VB-75', 'VB-76', 'VB-77', 'VB-78', 'VB-79', 'VB-80'],
    title: 'Bliss: every joy conscripted',
    narrative: 'No joy left unemployed: great joy without its occasion, embrace-feeling, the settled lake after food, art’s transport, contentment anywhere as seat, waking’s first sweetness, bodily ease, laughter that breaks the planner, bliss flooding every limb — rising to world-bliss, existence delighting in existing, held as continuous dwelling.',
  },
  {
    id: 'vb-step-9',
    conceptId: 'vb-mind',
    verseIds: ['VB-81', 'VB-82', 'VB-83', 'VB-84', 'VB-85', 'VB-86', 'VB-87', 'VB-88'],
    title: 'Mind: gaps, witness, burnt offering',
    narrative: 'Attention turns on itself: rest between thoughts, starve the chain, drop every support, discriminate seer from seen until discrimination ripens into identity, catch the bare ‘I’ before predicates — that divine self-touch — melt grasper into grasped, watch desire’s whole life, and offer each memory into awareness-fire.',
  },
  {
    id: 'vb-step-10',
    conceptId: 'vb-states',
    verseIds: ['VB-89', 'VB-90', 'VB-91', 'VB-92', 'VB-93', 'VB-94'],
    title: 'States: the fourth carried through all',
    narrative: 'Waking demoted to day-dream, sleep entered consciously, the fourth caught at thresholds and carried as the thread of all three states, dying rehearsed while alive, all forms ashed in cremation-ground vision — closing in evenness: containing every state, defined by none, which is living freedom stated as posture.',
  },
  {
    id: 'vb-step-11',
    conceptId: 'vb-body',
    verseIds: ['VB-95', 'VB-96', 'VB-97', 'VB-98', 'VB-99', 'VB-100'],
    title: 'Body: joy wearing skin',
    narrative: 'The body reclaimed last and tenderly: flesh as condensed light, each limb visited until it answers as awareness, luminous inner anatomy inhabited instead of the anatomical map, poised ease as posture, fingers looped into circuits — until every cell is claimed as bliss-expanse and the body is joy’s costume, worn knowingly.',
  },
  {
    id: 'vb-step-12',
    conceptId: 'vb-everywhere',
    verseIds: ['VB-101', 'VB-102', 'VB-103', 'VB-104', 'VB-105', 'VB-106'],
    title: 'Everywhere: the wall also preaches',
    narrative: 'Practice leaves the cushion: ten directions at once, a wall contemplated as consciousness-space, pots and stones as condensed awareness, mind poured into sky and ocean, the runaway mind met at its destination — until conviction firms into walking fact: all this indeed is Bhairava, omnipresence as ordinary thoroughfare.',
  },
  {
    id: 'vb-step-13',
    conceptId: 'vb-devotion',
    verseIds: ['VB-107', 'VB-108', 'VB-109', 'VB-110', 'VB-111', 'VB-112'],
    title: 'Devotion: love that ends seeking',
    narrative: 'The 112 close where effort ends: love that melts the lover, one true sentence held in trust until trusted becomes seen, everything offered including the offerer, every mood as flowers, grace contemplated as falling light — and the summit gate that gathers all: unbroken ‘I am Bhairava’ through eating, walking, speaking; life itself as mantra.',
  },
  {
    id: 'vb-step-14',
    conceptId: 'vb-phala',
    verseIds: ['VB-C1', 'VB-C2'],
    title: 'Many doors, one hall',
    narrative: 'Bhairava licenses plurality — choose the gate that suits your nature; temperament is spiritual fact, and every door opens onto the same hall. Devī’s satisfaction seals the text: doubt not merely answered but dissolved. The dialogue ends, as it must, where practice begins: in fulfilled silence.',
  },
];
