import { RawVerse } from '../../factory';

// Vijñānabhairava EN verses, part 2: dhāraṇās 25–70 (sound, void,
// light-and-darkness, sense-gates). Own paraphrase; see part 1 header.
export const vijnanabhairavaVersesEn2: RawVerse[] = [
  // ---------- SOUND (D25–D36) ----------
  {
    id: 'VB-25',
    number: 'Dhāraṇā 25',
    section: 'Sound — mantra and resonance',
    iast: 'mantroccāre ... layadhvani',
    conceptIds: ['vb-sound'],
    translation: 'Utter a seed-syllable slowly and listen to its fading resonance; follow the fading to its end and rest where sound ends.',
    commentary: 'Mantra is used here as a disposable vehicle: utterance, resonance, dissolution. Attention riding the fade-out arrives at the silence from which sound came — the unuttered ground (anuttara) behind every utterance.',
    keyPoints: [
      'Sound’s fading tail is a road into silence.',
      'Mantra is a boat abandoned on reaching the far shore.',
    ],
  },
  {
    id: 'VB-26',
    number: 'Dhāraṇā 26',
    section: 'Sound — mantra and resonance',
    iast: 'oṃkāre ... pluta ... sūkṣmatā',
    conceptIds: ['vb-sound'],
    translation: 'Prolong the syllable OṂ and trace its three measures into the half-measure silence (ardhamātrā); dissolving there, the mind dissolves.',
    commentary: 'OṂ’s a-u-m carry waking, dream and sleep; the trailing bindu-silence carries the fourth (turīya). Resting in that after-sound, the meditator passes through all three states’ deities into the stateless — praṇava-laya in seed-form.',
    keyPoints: [
      'OṂ’s measures map the three states; its silence maps the fourth.',
      'Rest in the after-sound, not in the sounded parts.',
    ],
  },
  {
    id: 'VB-27',
    number: 'Dhāraṇā 27',
    section: 'Sound — mantra and resonance',
    iast: 'varṇodaya ... parā ... paśyantī',
    conceptIds: ['vb-sound'],
    translation: 'Trace any heard sound back through its levels — uttered, mental, visionary — to the supreme Word (parā) where sound is will itself.',
    commentary: 'Trika’s four levels of speech (vaikharī, madhyamā, paśyantī, parā) are climbed in reverse: from heard sound to meaning-intention to pure seeing-will. At parā there is no sound yet nothing is unsaid — willing and knowing are one flash.',
    keyPoints: [
      'Every sound climbs down from four levels; climb them back.',
      'At the supreme level, will and word are one.',
    ],
  },
  {
    id: 'VB-28',
    number: 'Dhāraṇā 28',
    section: 'Sound — mantra and resonance',
    iast: 'gītādau ... svarasa ... tanmayatā',
    conceptIds: ['vb-sound', 'vb-bliss'],
    translation: 'While listening to song or instrument, merge into its essence-tone (svarasa) until listener and music are one continuity.',
    commentary: 'Aesthetic absorption (camatkāra) is a ready-made dhāraṇā: sustained tone dissolves the listener’s separateness without doctrine. Trika honours this — relish (rasa) at its peak is consciousness tasting itself.',
    keyPoints: [
      'Sustained tone dissolves the listener into the heard.',
      'Aesthetic rapture is consciousness tasting itself.',
    ],
  },
  {
    id: 'VB-29',
    number: 'Dhāraṇā 29',
    section: 'Sound — mantra and resonance',
    iast: 'karṇapuṭe ... śabda ... brahmarandhra',
    conceptIds: ['vb-sound'],
    translation: 'Close the ears and hear the inner roar rising to the crown-aperture; absorbed in that thunder, all other sounds fall away.',
    commentary: 'Sealed ears reveal the body’s inner ocean — blood, breath, nerve-hum rising like surf. Led upward to the brahmarandhra, the roar thins into radiance: sound practised as elevator rather than entertainment.',
    keyPoints: [
      'Sealed ears reveal the body’s inner ocean of sound.',
      'Led upward, inner thunder thins into light.',
    ],
  },
  {
    id: 'VB-30',
    number: 'Dhāraṇā 30',
    section: 'Sound — mantra and resonance',
    iast: 'somasūrya ... śabdabheda ... ekadhvani',
    conceptIds: ['vb-sound'],
    translation: 'Unite the left and right inner currents into a single tone heard in the centre; that one tone is the axis of the whole practice.',
    commentary: 'Iḍā and piṅgalā each carry their own hum; their union in suṣumṇā sounds as one (ekadhvani). Hearing it, duality of currents ends — the yogin stands on the axis where opposites are already married.',
    keyPoints: [
      'Two currents, one central tone.',
      'The single tone is the marriage-point of opposites.',
    ],
  },
  {
    id: 'VB-31',
    number: 'Dhāraṇā 31',
    section: 'Sound — the wordless',
    iast: 'aśabde ... śabda ... bhāvanā',
    conceptIds: ['vb-sound', 'vb-void'],
    translation: 'Contemplate sound within soundlessness — hear the silence inside each tone as its true body; resting there, hearing becomes knowing.',
    commentary: 'Each tone carries a womb of silence. Attention shifted from tone to its silent body reverses ordinary hearing: instead of sounds in silence, silence wearing sounds. The hearer meets the unstruck ground of all audition.',
    keyPoints: [
      'Inside every tone sits its silence — contemplate that.',
      'Hearing reversed: silence wearing sounds.',
    ],
  },
  {
    id: 'VB-32',
    number: 'Dhāraṇā 32',
    section: 'Sound — the wordless',
    iast: 'hrīṃ ... bījamantra ... hṛdguhā',
    conceptIds: ['vb-sound'],
    translation: 'Repeat the heart-seed HRĪṂ softly until repeater, repeated and repeating merge in the heart-cave.',
    commentary: 'Bīja-mantra japa ripens in three stages: effortful repetition, spontaneous flow (ajapā), then merger where the triad of repeater–repeated–repeating collapses. HRĪṂ, the heart-seed, is chosen because it names the very cave it opens.',
    keyPoints: [
      'Japa ripens: effort, spontaneity, merger.',
      'The heart-seed opens the heart it names.',
    ],
  },
  {
    id: 'VB-33',
    number: 'Dhāraṇā 33',
    section: 'Sound — the wordless',
    iast: 'uccāra ... rahita ... uccāraṇa',
    conceptIds: ['vb-sound'],
    translation: 'Recite without reciting — let the mantra pulse in feeling alone, no tongue, no sound; that pulsing is the true utterance.',
    commentary: 'Mental japa thins further into bhāvanā-japa: pure pulsation of meaning without syllables. This is mantra returned to its mother (mātṛkā-śakti as sheer intent) — recitation that never leaves silence yet fills it.',
    keyPoints: [
      'True recitation needs neither tongue nor sound.',
      'Mantra as pure intent-pulse is closest to its source.',
    ],
  },
  {
    id: 'VB-34',
    number: 'Dhāraṇā 34',
    section: 'Sound — the wordless',
    iast: 'śakti ... śākta ... śāmbhava uccāra',
    conceptIds: ['vb-sound'],
    translation: 'Rise through the three utterances — embodied, energetic, and divine: from spoken syllable to inner surge to silent will-flash.',
    commentary: 'The text’s ladder of uccāra (utterance-levels): āṇava (with breath/body), śākta (with energy/intent), śāmbhava (sheer will-flash, icchā-mātra). Each higher utterance drops a vehicle until only the will to sound remains — and that is Śiva’s own speech.',
    keyPoints: [
      'Three utterances: bodily, energetic, will-only.',
      'The highest utterance is silent will itself.',
    ],
  },
  {
    id: 'VB-35',
    number: 'Dhāraṇā 35',
    section: 'Sound — thunder and dissolution',
    iast: 'meghaghoṣe ... layacintana',
    conceptIds: ['vb-sound'],
    translation: 'In thunder, waterfall or ocean-roar, contemplate the dissolution-sound — all lesser sounds drowned in the great one; drown with them.',
    commentary: 'Overwhelming natural sound does the work of sealing the ears: the small self’s chatter drowns in the great tone. Surrendered to it, the meditator tastes pralaya (dissolution) while living — the world ending as sound, awareness remaining.',
    keyPoints: [
      'Great natural sound drowns the small self’s noise.',
      'Dissolution contemplated in sound previews final rest.',
    ],
  },
  {
    id: 'VB-36',
    number: 'Dhāraṇā 36',
    section: 'Sound — thunder and dissolution',
    iast: 'sarvaśabda ... brahma ... śravaṇa',
    conceptIds: ['vb-sound', 'vb-everywhere'],
    translation: 'Hear all sounds at once as one Brahman-sound — no near or far, no liked or disliked; in that even hearing, the hearer vanishes.',
    commentary: 'The closing sound-gate universalises hearing: every sound, accepted without preference, becomes the same absolute tone. When no sound is pushed away, the pusher (ego-hearer) has no work left and quietly dissolves.',
    keyPoints: [
      'All sounds heard evenly become one absolute tone.',
      'Hearing without preference dissolves the preferrer.',
    ],
  },
  // ---------- VOID (D37–D48) ----------
  {
    id: 'VB-37',
    number: 'Dhāraṇā 37',
    section: 'Void — emptiness contemplations',
    iast: 'śūnyabhāva ... bhāvana ... sarvagocara',
    conceptIds: ['vb-void'],
    translation: 'Contemplate all things as void-forms floating in awareness — objects as bubbles that never wet the water.',
    commentary: 'The classic śūnya-bhāvanā: things appear but do not stain awareness, like bubbles on water. This is not denial of the world but of its weight — form kept, solidity withdrawn.',
    keyPoints: [
      'Things as bubbles: appearing without staining.',
      'Void-practice removes weight, not world.',
    ],
  },
  {
    id: 'VB-38',
    number: 'Dhāraṇā 38',
    section: 'Void — emptiness contemplations',
    iast: 'deha ... śūnya ... ākāśasama',
    conceptIds: ['vb-void'],
    translation: 'Contemplate the body as hollow space — skin, flesh and bone as walls round emptiness; the owner-sense drains away.',
    commentary: 'The body meditated as hollow (like bamboo or a clay pot) loses its solidity-claim. What owns — the ‘my’-sense — finds no wall to grip; awareness, formerly packed in flesh, spreads through the hollow.',
    keyPoints: [
      'The body as hollow vessel, not solid lump.',
      'Hollowness drains the ownership-sense.',
    ],
  },
  {
    id: 'VB-39',
    number: 'Dhāraṇā 39',
    section: 'Void — emptiness contemplations',
    iast: 'ghaṭādi ... bāhyaśūnya ... antarlaya',
    conceptIds: ['vb-void'],
    translation: 'Gaze at an empty jar or room and enter its emptiness; then find the same emptiness within — the two voids recognise each other.',
    commentary: 'Outer emptiness (pot, room, sky) is the beginner’s mirror for inner emptiness. Attention poured into outer void returns carrying void-feeling inward; at the meeting-point, inner and outer are one expanse.',
    keyPoints: [
      'Outer emptiness mirrors inner emptiness.',
      'Enter one and the other opens.',
    ],
  },
  {
    id: 'VB-40',
    number: 'Dhāraṇā 40',
    section: 'Void — emptiness contemplations',
    iast: 'kāla ... dig ... śūnyayojana',
    conceptIds: ['vb-void'],
    translation: 'Dissolve time and direction into void — no before or after, no here or there; what remains is the timeless present.',
    commentary: 'Time and space are the last scaffolds of ego. Contemplated as void-woven, they collapse into the eternal now (akāla) — Trika’s claim that Bhairava is ‘beyond sequence’ (akrama) made into direct experience.',
    keyPoints: [
      'Time and direction are ego’s last scaffolds.',
      'Their collapse reveals the timeless present.',
    ],
  },
  {
    id: 'VB-41',
    number: 'Dhāraṇā 41',
    section: 'Void — the bodiless',
    iast: 'videha ... bhāvanā ... sarvatra',
    conceptIds: ['vb-void', 'vb-everywhere'],
    translation: 'Feel oneself as bodiless — awareness without location, spread everywhere at once; the body appears within you, not you within it.',
    commentary: 'Reversal of the normal map: instead of awareness inside a body, the body floats inside awareness. Practised steadily, location-sense (deśa) ends and the yogin knows omnipresence as fact, not idea.',
    keyPoints: [
      'Reverse the map: body inside awareness.',
      'Bodiless feeling is omnipresence in seed.',
    ],
  },
  {
    id: 'VB-42',
    number: 'Dhāraṇā 42',
    section: 'Void — the bodiless',
    iast: 'nidrā ... avasthā ... śūnyatāpatti',
    conceptIds: ['vb-void', 'vb-states'],
    translation: 'At sleep’s edge, enter the void between waking and dream deliberately; that threshold-consciousness is the door to the fourth state.',
    commentary: 'The hypnagogic gap — neither waking nor dreaming — is turīya glimpsed nightly. Entering it deliberately (instead of sliding through) converts accident into method: the threshold becomes a dwelling.',
    keyPoints: [
      'Sleep’s threshold is the fourth state in disguise.',
      'Enter deliberately what is usually suffered blindly.',
    ],
  },
  {
    id: 'VB-43',
    number: 'Dhāraṇā 43',
    section: 'Void — the bodiless',
    iast: 'mūrcchā ... tama ... prakāśodaya',
    conceptIds: ['vb-void'],
    translation: 'In faintness, shock or deep swoon, notice the darkness that remains aware; that aware-darkness is the Self wearing tamas as a robe.',
    commentary: 'Even radical traditions use extremity: in swoon, content vanishes but a dim knowing persists. Finding the knower inside unconsciousness proves awareness needs no object — the darkest gate opens onto pure subject.',
    keyPoints: [
      'Even swoon contains a dim knower.',
      'Awareness without object is the Self unveiled.',
    ],
  },
  {
    id: 'VB-44',
    number: 'Dhāraṇā 44',
    section: 'Void — darkness and concealment',
    iast: 'kṛṣṇarātrau ... tama ... bhairavarūpa',
    conceptIds: ['vb-void', 'vb-light'],
    translation: 'On a moonless night, meditate on all-enveloping darkness as Bhairava’s own form; eyes open, see nothing — and know the Seer.',
    commentary: 'Darkness removes every object at once, leaving the subject with nothing to grasp. What panics the beginner liberates the steady: the Seer, deprived of seen, finally sees itself — darkness as Bhairava’s black robe.',
    keyPoints: [
      'Total darkness starves the object-habit.',
      'With nothing to see, the Seer sees itself.',
    ],
  },
  {
    id: 'VB-45',
    number: 'Dhāraṇā 45',
    section: 'Void — darkness and concealment',
    iast: 'nimīlane ... bāhyāndhakāra ... antardṛṣṭi',
    conceptIds: ['vb-void'],
    translation: 'Close the eyes and enter the home-darkness within; whatever forms arise, know them as projections on your own light.',
    commentary: 'Closed-eye darkness is a private night always available. Phosphenes and dream-fragments arise in it; recognised as self-projections, they teach the great lesson — all seeing is self-seeing — in miniature.',
    keyPoints: [
      'Closed-eye darkness is a portable night.',
      'Its forms teach: all seeing is self-projection.',
    ],
  },
  {
    id: 'VB-46',
    number: 'Dhāraṇā 46',
    section: 'Void — darkness and concealment',
    iast: 'āvaraṇa ... bhāva ... anāvṛtatā',
    conceptIds: ['vb-void'],
    translation: 'Contemplate every covering — body, breath, thought — as a veil over the uncovered (anāvṛta); then drop the veils one by one.',
    commentary: 'Spanda’s great word anāvṛta (‘uncovered form’) becomes practice here: each layer named as veil loosens its grip. The Self needs no unveiling — only the recognition that veils never touched it.',
    keyPoints: [
      'Name each layer as veil; naming loosens.',
      'The uncovered was never actually covered.',
    ],
  },
  {
    id: 'VB-47',
    number: 'Dhāraṇā 47',
    section: 'Void — the plenum',
    iast: 'śūnyaṃ ... pūrṇaṃ ... abhedabhāva',
    conceptIds: ['vb-void'],
    translation: 'Know void as plenum — emptiness that is full, fullness that is empty; holding both as one, duality of being and non-being ends.',
    commentary: 'The summit of the void-sequence corrects nihilism: śūnya is pūrṇa (as the Īśa-upaniṣad says, fullness from fullness). Emptiness of objects equals fullness of awareness — one reality, two names, zero contradiction.',
    keyPoints: [
      'Void is plenum: empty of objects, full of awareness.',
      'Being/non-being duality ends in this identity.',
    ],
  },
  {
    id: 'VB-48',
    number: 'Dhāraṇā 48',
    section: 'Void — the plenum',
    iast: 'sarvaṃ śūnyaṃ ... śūnyaṃ sarvam ... iti dhīḥ',
    conceptIds: ['vb-void', 'vb-everywhere'],
    translation: '‘All is void, and void is all’ — resting in this even insight without wavering, the yogin becomes void-like: boundless and stainless.',
    commentary: 'The void-gates close with a formula for continuous awareness: whatever appears, void; whatever void, appearing. Held unbroken through daily life, it converts metaphysics into perception — the world seen as Bhairava’s empty dance.',
    keyPoints: [
      'Carry the void-insight unbroken into daily acts.',
      'Boundlessness becomes character, not occasion.',
    ],
  },
  // ---------- LIGHT & DARK (D49–D60) ----------
  {
    id: 'VB-49',
    number: 'Dhāraṇā 49',
    section: 'Light and Darkness — seeing',
    iast: 'bindu ... dṛṣṭi ... sthiratā',
    conceptIds: ['vb-light'],
    translation: 'Gaze steadily at a single point of light (flame-tip, star) without blinking inwardly; when the point flowers into radiance, enter it.',
    commentary: 'Trāṭaka refined: the point gazed at dissolves its point-ness and blooms (vikāsa) into expanse. Attention follows the bloom outward-inward until gazer, gazing and point are one luminous act.',
    keyPoints: [
      'Steady gazing blooms the point into expanse.',
      'Follow the bloom until seer and seen merge.',
    ],
  },
  {
    id: 'VB-50',
    number: 'Dhāraṇā 50',
    section: 'Light and Darkness — seeing',
    iast: 'bhāskarādi ... tejas ... tanmayībhāva',
    conceptIds: ['vb-light'],
    translation: 'Contemplate sun, moon or fire as one’s own radiance projected outward; withdrawing the projection, know the light as oneself.',
    commentary: 'Outer lights are the inner light lent out. Reclaiming the loan — ‘that brightness is mine’ — reverses cosmic projection (ābhāsa) at its brightest instance; the feared vastness of suns becomes intimate.',
    keyPoints: [
      'Outer lights are inner light projected.',
      'Reclaim the projection: that brightness is oneself.',
    ],
  },
  {
    id: 'VB-51',
    number: 'Dhāraṇā 51',
    section: 'Light and Darkness — seeing',
    iast: 'andhakūpe ... dṛṣṭi ... alabdhalakṣya',
    conceptIds: ['vb-light', 'vb-void'],
    translation: 'Stare into a dark well or night sky with aimless gaze — no object sought; objectless seeing settles into itself.',
    commentary: 'Aimless gaze (alabdhalakṣya-dṛṣṭi) starves the grasping eye. With nowhere to land, seeing lands on itself — dṛṣṭi knowing dṛṣṭi. This is bhairavī-mudrā’s open-eyed half: world present, grasping absent.',
    keyPoints: [
      'Gaze with no object to land on.',
      'Objectless seeing settles into itself.',
    ],
  },
  {
    id: 'VB-52',
    number: 'Dhāraṇā 52',
    section: 'Light and Darkness — seeing',
    iast: 'unmīlana ... nimīlana ... sandhyā',
    conceptIds: ['vb-light'],
    translation: 'Poise attention at the meeting of open and closed eyes — half-lidded, neither seeing out nor in; that twilight is Bhairava’s own gaze.',
    commentary: 'The half-open eye is Trika’s signature mudrā: unmīlana (opening) and nimīlana (closing) held together. Outward forms and inward void are seen simultaneously as one — the twilight (sandhyā) where both lights meet.',
    keyPoints: [
      'Half-lidded gaze holds opening and closing together.',
      'Outer form and inner void seen as one.',
    ],
  },
  {
    id: 'VB-53',
    number: 'Dhāraṇā 53',
    section: 'Light and Darkness — inner radiance',
    iast: 'jyotirūpa ... ātma ... bhāvanā',
    conceptIds: ['vb-light'],
    translation: 'Meditate on the Self as a mass of light (prakāśa) — self-shining, needing no other lamp; abide as that lamp.',
    commentary: 'Prakāśa (light) is Trika’s name for Śiva-as-knowing: light that lights itself. Contemplated steadily, the meditator stops borrowing identity from lit objects and rests as the lighting itself — self-evidence as dwelling.',
    keyPoints: [
      'The Self is self-shining light needing no lamp.',
      'Rest as the lighting, not among lit things.',
    ],
  },
  {
    id: 'VB-54',
    number: 'Dhāraṇā 54',
    section: 'Light and Darkness — inner radiance',
    iast: 'pratyāhāre ... tejas ... ūrdhvadṛṣṭi',
    conceptIds: ['vb-light', 'vb-energy-body'],
    translation: 'Withdraw the senses and lift the inner gaze to the blazing space above the palate; the skull fills with light like a sealed lamp.',
    commentary: 'Sense-withdrawal seals the lamp; upward gaze lights it. The cranial vault (brahmāṇḍa) fills with felt radiance — kevala-jyotis — and thought, having no dark corner left, surrenders.',
    keyPoints: [
      'Sealed senses, lifted gaze: the skull becomes a lamp.',
      'Light with no corner left stills thought.',
    ],
  },
  {
    id: 'VB-55',
    number: 'Dhāraṇā 55',
    section: 'Light and Darkness — inner radiance',
    iast: 'sūryodaya ... hṛdayākāśa ... vyāpti',
    conceptIds: ['vb-light'],
    translation: 'At dawn, feel the rising sun inside the heart-sky; its rays pervade the body — outer dawn and inner dawn as one rising.',
    commentary: 'Outer sunrise is borrowed as timer and symbol: while the visible sun climbs, attention climbs within the heart-space. The two dawns synchronised, the boundary between weather and worship dissolves.',
    keyPoints: [
      'Borrow outer dawn as the clock of inner rising.',
      'Two dawns synchronised dissolve inner/outer.',
    ],
  },
  {
    id: 'VB-56',
    number: 'Dhāraṇā 56',
    section: 'Light and Darkness — dreams of light',
    iast: 'svapne ... jyotirdarśana ... prabodha',
    conceptIds: ['vb-light', 'vb-states'],
    translation: 'In dream, recognise any great light as one’s own consciousness appearing; that recognition wakes the dreamer without breaking the dream.',
    commentary: 'Dream-yoga in seed: light seen in dream, recognised as self-light, converts dream into lucid practice-ground. The dreamer awake inside dream learns the waking lesson too — this world likewise is self-light appearing.',
    keyPoints: [
      'Dream-light recognised as self-light brings lucidity.',
      'Lucid dream previews waking-world recognition.',
    ],
  },
  {
    id: 'VB-57',
    number: 'Dhāraṇā 57',
    section: 'Light and Darkness — the fire of time',
    iast: 'kālāgni ... dahana ... viśva',
    conceptIds: ['vb-light', 'vb-void'],
    translation: 'Contemplate the fire of time (kālāgni) consuming all forms at the world’s end — and oneself as the unconsumed remainder.',
    commentary: 'Dissolution-fire meditation: everything burnable burns — body, world, gods — and attention rests as the unburnable witness. Fear of ending becomes the gate: what survives imagined ending is the deathless.',
    keyPoints: [
      'Burn everything imaginable; note what cannot burn.',
      'The unburnable remainder is the Self.',
    ],
  },
  {
    id: 'VB-58',
    number: 'Dhāraṇā 58',
    section: 'Light and Darkness — the fire of time',
    iast: 'dahyamāna ... deha ... cidvyoman',
    conceptIds: ['vb-light', 'vb-body'],
    translation: 'See this very body burning in that fire while consciousness, like sky, remains untouched; live henceforth as sky wearing a body.',
    commentary: 'Companion practice applied to oneself: the body imagined consumed, awareness remaining like space after a pot breaks. The result is not morbidity but lightness — a body worn loosely, like sky wears clouds.',
    keyPoints: [
      'Imagine the body consumed, awareness remaining.',
      'Live as sky wearing a body, not body owning sky.',
    ],
  },
  {
    id: 'VB-59',
    number: 'Dhāraṇā 59',
    section: 'Light and Darkness — lightning insight',
    iast: 'vidyut ... sphuraṇa ... kṣaṇika',
    conceptIds: ['vb-light', 'vb-mind'],
    translation: 'Catch the lightning-flash of insight between two thoughts — momentary, ungraspable; abide in flashes until flashing is continuous.',
    commentary: 'Unmeṣa (the opening) as lightning-practice: thought-gaps flash and vanish. Instead of mourning their brevity, the yogin collects flashes until, like monsoon lightning joining into day, gaps join into ground.',
    keyPoints: [
      'Thought-gaps flash like lightning — collect them.',
      'Flashes joined become continuous ground.',
    ],
  },
  {
    id: 'VB-60',
    number: 'Dhāraṇā 60',
    section: 'Light and Darkness — lightning insight',
    iast: 'sarvaprakāśa ... bhairava ... iti smṛtiḥ',
    conceptIds: ['vb-light', 'vb-everywhere'],
    translation: '‘Whatever shines is Bhairava shining’ — holding this remembrance toward every light, small or great, the world becomes one lamp.',
    commentary: 'The light-gates close with remembrance (smṛti) as continuous practice: every brightness referred to its source. Repeated until reflexive, it converts perception into worship — seeing itself becomes offering.',
    keyPoints: [
      'Refer every brightness to its source.',
      'Perception converted into continuous offering.',
    ],
  },
  // ---------- SENSES (D61–D70) ----------
  {
    id: 'VB-61',
    number: 'Dhāraṇā 61',
    section: 'Sense Gates — touch and taste',
    iast: 'sparśe ... sparśasukha ... magnatā',
    conceptIds: ['vb-senses', 'vb-bliss'],
    translation: 'In pleasant touch, sink into the pleasure alone — forgetting toucher and touched; pleasure without owner is Bhairava’s bliss.',
    commentary: 'Sensation contemplated without the subject-object frame reveals ānanda underneath. The practice is not indulgence but reduction: subtract owner and object, and what remains is ownerless bliss — the Self’s flavour.',
    keyPoints: [
      'Subtract toucher and touched from touch.',
      'Ownerless pleasure is the Self’s own flavour.',
    ],
  },
  {
    id: 'VB-62',
    number: 'Dhāraṇā 62',
    section: 'Sense Gates — touch and taste',
    iast: 'bhakṣye ... bhojye ... rasāsvāda',
    conceptIds: ['vb-senses', 'vb-bliss'],
    translation: 'While eating or drinking, rest in the taste-essence (rasa) with full attention; in that savouring, the savourer dissolves.',
    commentary: 'Food-yoga: total attention on taste collapses eater into eating. Rasa (sap/essence) is also aesthetic relish — the practice hints that all relish, gross or subtle, is one consciousness tasting itself.',
    keyPoints: [
      'Total attention on taste dissolves the taster.',
      'All relish is consciousness tasting itself.',
    ],
  },
  {
    id: 'VB-63',
    number: 'Dhāraṇā 63',
    section: 'Sense Gates — smell and sight',
    iast: 'gandhe ... saurabha ... ekāgratā',
    conceptIds: ['vb-senses'],
    translation: 'In fine fragrance, become the smelling itself — one-pointed on scent until smeller and smelled are one perfume.',
    commentary: 'Smell, the most memory-laden sense, is stilled by total presence to scent. Past and future, which fragrance usually summons, are refused; only the present perfume remains — and it is vast enough to hold awareness.',
    keyPoints: [
      'Meet scent with total presence; refuse its memories.',
      'One perfume remains: smeller and smelled as one.',
    ],
  },
  {
    id: 'VB-64',
    number: 'Dhāraṇā 64',
    section: 'Sense Gates — smell and sight',
    iast: 'rūpe ... dṛśya ... dṛṅmātratā',
    conceptIds: ['vb-senses'],
    translation: 'Before a beautiful form, rest as seeing alone — no naming, no grasping; pure seeing is the Goddess (dṛk-śakti) unveiled.',
    commentary: 'Beauty arrests the mind — the text exploits the arrest. Naming and grasping suspended, the beautiful object becomes a mirror: dṛśya (seen) dissolves into dṛk (seeing), and seeing knows itself as Śakti.',
    keyPoints: [
      'Before beauty, suspend naming and grasping.',
      'Arrested seeing knows itself as Śakti.',
    ],
  },
  {
    id: 'VB-65',
    number: 'Dhāraṇā 65',
    section: 'Sense Gates — the meeting of senses',
    iast: 'indriyadvāre ... saṃgama ... śūnyatā',
    conceptIds: ['vb-senses', 'vb-void'],
    translation: 'At the instant a sense meets its object, notice the gap before recognition; entering that pre-name gap, rest in the unborn.',
    commentary: 'Between contact and naming lies a hairline gap of pure sensing. The practice catches it — hearing before ‘bell’, seeing before ‘tree’ — and widens it into dwelling: the unborn (aja) moment before the world is born as named.',
    keyPoints: [
      'Between contact and naming lies a gap of pure sensing.',
      'Widen that gap into dwelling.',
    ],
  },
  {
    id: 'VB-66',
    number: 'Dhāraṇā 66',
    section: 'Sense Gates — the meeting of senses',
    iast: 'viṣayapraveśe ... tādātmy ... layakrama',
    conceptIds: ['vb-senses'],
    translation: 'Entering sense-objects fully — as a lover enters embrace — merge until entrant and entered are one; that oneness is the gate.',
    commentary: 'Total immersion instead of withdrawal: the tantric reversal. Sense-objects entered without reservation and without grasping reveal themselves as consciousness-stuff; the merger (tādātmya) intended is knower-known oneness, not indulgence.',
    keyPoints: [
      'Total immersion without grasping reveals oneness.',
      'Objects entered fully confess they are consciousness.',
    ],
  },
  {
    id: 'VB-67',
    number: 'Dhāraṇā 67',
    section: 'Sense Gates — pain and intensity',
    iast: 'tīvrādhau ... vedanā ... dhyāna',
    conceptIds: ['vb-senses'],
    translation: 'In sharp pain or intense sensation, meditate on its very intensity — not its cause; intensity without story becomes pure energy.',
    commentary: 'Pain usually triggers narrative (cause, blame, future). Attention fixed on intensity alone burns the story away; what remains is śakti in fierce form — energy that, met directly, is liberating rather than binding.',
    keyPoints: [
      'Meet intensity without its story.',
      'Storyless intensity is fierce liberating energy.',
    ],
  },
  {
    id: 'VB-68',
    number: 'Dhāraṇā 68',
    section: 'Sense Gates — pain and intensity',
    iast: 'bhaye ... krodhe ... kṣobhe ... sthiti',
    conceptIds: ['vb-senses', 'vb-mind'],
    translation: 'In fear, anger or agitation, stand still within the surge — neither acting nor suppressing; the storm’s eye is motionless awareness.',
    commentary: 'Spanda’s crisis-verse (1.22) generalised: any overwhelming emotion stops the ordinary mind. Poised in the surge without expression or repression, the yogin finds the storm’s eye — unmoving awareness at passion’s centre.',
    keyPoints: [
      'Overwhelm stops the ordinary mind — use the stop.',
      'Neither express nor suppress: stand in the eye.',
    ],
  },
  {
    id: 'VB-69',
    number: 'Dhāraṇā 69',
    section: 'Sense Gates — hunger and thirst',
    iast: 'kṣut ... pipāsā ... nivṛtti ... smṛti',
    conceptIds: ['vb-senses'],
    translation: 'When hunger or thirst ends in satisfaction, rest in the moment of wanting’s end — desire stilled reveals the still ground.',
    commentary: 'Satisfaction-moments are natural samādhis: want ends, fullness dawns. Instead of rushing to the next want, the yogin dwells in the gap — tasting, in miniature, what desirelessness always is: the Self at rest.',
    keyPoints: [
      'Satisfaction is a natural thought-free gap.',
      'Dwell in wanting’s end instead of rushing on.',
    ],
  },
  {
    id: 'VB-70',
    number: 'Dhāraṇā 70',
    section: 'Sense Gates — hunger and thirst',
    iast: 'sarvendriya ... saṃhāra ... hṛdayeśatā',
    conceptIds: ['vb-senses', 'vb-energy-body'],
    translation: 'Withdraw all senses at once into the heart like a tortoise drawing in limbs; lord of that inner chamber, know sovereignty.',
    commentary: 'The sense-gates close with simultaneous withdrawal (kūrmāṅga-saṃkoca, the tortoise-gesture). All doors shut at once, awareness reigns alone in the heart — cakreśvara in miniature: lordship over the circle of powers.',
    keyPoints: [
      'Withdraw all senses at once, like the tortoise.',
      'Alone in the heart, awareness knows sovereignty.',
    ],
  },
];
