// Vijñānabhairava concepts: abstract nodes for the pedagogical thread.
// Summaries are this app's own paraphrase of the Trika line.
export const vijnanabhairavaConceptsEn: any[] = [
  {
    id: 'vb-frame',
    title: 'Devī’s Questions — practice, not doctrine',
    category: 'Frame',
    summary: 'Devī, learned yet unsatisfied, asks for the essence (sāra) by which Bhairava is known directly — not more scripture but upāya. Bhairava’s single condition is one-pointed attention; his answer is 112 gates, grace taking the form of usable method.',
    relatedVerseIds: ['VB-F1', 'VB-F2', 'VB-F3', 'VB-F4'],
    relatedConceptIds: ['vb-devotion', 'vb-phala'],
  },
  {
    id: 'vb-breath',
    title: 'Breath — the two pauses and fullness',
    category: 'Practice',
    summary: 'The opening gates work the breath’s turning-points: the outer and inner pauses, the twelve-finger limit and the heart, the throb between breaths, self-sounding haṃsa, gentle retention, and the fullness (bharitā) in which breath neither rises nor falls. Mind follows breath into stillness.',
    relatedVerseIds: ['VB-1', 'VB-2', 'VB-3', 'VB-4', 'VB-5', 'VB-6', 'VB-7', 'VB-8', 'VB-9', 'VB-10', 'VB-11', 'VB-12'],
    relatedConceptIds: ['vb-energy-body', 'vb-void', 'vb-sound'],
  },
  {
    id: 'vb-energy-body',
    title: 'Energy Body — channels, centres, ascent',
    category: 'Subtle Physiology',
    summary: 'Navel-fire rises through the middle channel piercing the knots; energy settles at the crown-void, dissolves mind at the brow, hums as inner sound, pervades the whole frame, turns skin to space, drips nectar at the palate, wheels time at the navel, wakes the coiled serpent, climbs past the crown to the Transmental, and rebuilds the body as living mantra.',
    relatedVerseIds: ['VB-13', 'VB-14', 'VB-15', 'VB-16', 'VB-17', 'VB-18', 'VB-19', 'VB-20', 'VB-21', 'VB-22', 'VB-23', 'VB-24'],
    relatedConceptIds: ['vb-breath', 'vb-sound', 'vb-bliss'],
  },
  {
    id: 'vb-sound',
    title: 'Sound — from utterance to silence',
    category: 'Philosophy of Language',
    summary: 'Sound-gates climb the ladder in reverse: fading resonance, OṂ’s after-silence, the four levels of Word back to parā, music-absorption, sealed-ear thunder, the single central tone, silence inside tone, seed-japa to merger, recitation without reciting, the three utterances, dissolution-sound in nature, and all sounds heard as one Brahman-tone.',
    relatedVerseIds: ['VB-25', 'VB-26', 'VB-27', 'VB-28', 'VB-29', 'VB-30', 'VB-31', 'VB-32', 'VB-33', 'VB-34', 'VB-35', 'VB-36'],
    relatedConceptIds: ['vb-energy-body', 'vb-void', 'vb-bliss'],
  },
  {
    id: 'vb-void',
    title: 'Void — emptiness as plenum',
    category: 'Metaphysics in Practice',
    summary: 'Twelve void-gates: things as bubbles, body as hollow, outer emptiness mirroring inner, time and direction dissolved, bodiless pervasion, sleep’s threshold, aware darkness in swoon, moonless-night meditation, closed-eye night, veils dropped one by one — closing in the summit identity: void is plenum, held unbroken as daily insight.',
    relatedVerseIds: ['VB-37', 'VB-38', 'VB-39', 'VB-40', 'VB-41', 'VB-42', 'VB-43', 'VB-44', 'VB-45', 'VB-46', 'VB-47', 'VB-48'],
    relatedConceptIds: ['vb-breath', 'vb-light', 'vb-states'],
  },
  {
    id: 'vb-light',
    title: 'Light and Darkness — seeing itself',
    category: 'Practice',
    summary: 'Seeing-gates: the blooming point, outer lights reclaimed as one’s own, aimless gaze, the half-lidded twilight, Self as self-shining lamp, skull filled with light, dawn within and without, dream-light lucidity, time-fire consuming all, one’s own body burning while sky remains, lightning-gaps between thoughts — closing in remembrance that whatever shines is Bhairava.',
    relatedVerseIds: ['VB-49', 'VB-50', 'VB-51', 'VB-52', 'VB-53', 'VB-54', 'VB-55', 'VB-56', 'VB-57', 'VB-58', 'VB-59', 'VB-60'],
    relatedConceptIds: ['vb-void', 'vb-mind', 'vb-states'],
  },
  {
    id: 'vb-senses',
    title: 'Sense Gates — immersion without grasping',
    category: 'Practice',
    summary: 'Ten sense-gates: ownerless touch-pleasure, taste-absorption, scent-presence, beauty without naming, the pre-name gap, total immersion, storyless pain-intensity, poise inside passion’s surge, the satisfaction-gap after hunger, and tortoise-withdrawal of all senses into the heart — ending in sovereignty.',
    relatedVerseIds: ['VB-61', 'VB-62', 'VB-63', 'VB-64', 'VB-65', 'VB-66', 'VB-67', 'VB-68', 'VB-69', 'VB-70'],
    relatedConceptIds: ['vb-bliss', 'vb-mind', 'vb-energy-body'],
  },
  {
    id: 'vb-bliss',
    title: 'Bliss — delight conscripted as method',
    category: 'Soteriology',
    summary: 'Ten bliss-gates leave no joy unemployed: great joy without its occasion, embrace-feeling, post-nourishment contentment, aesthetic rapture, contentment anywhere as seat, waking’s first sweetness, bodily ease, laughter’s upsurge, bliss-flood — closing in world-bliss (jagadānanda): existence delighting in existing.',
    relatedVerseIds: ['VB-71', 'VB-72', 'VB-73', 'VB-74', 'VB-75', 'VB-76', 'VB-77', 'VB-78', 'VB-79', 'VB-80'],
    relatedConceptIds: ['vb-senses', 'vb-body', 'vb-everywhere'],
  },
  {
    id: 'vb-mind',
    title: 'Mind — gaps, witness, offering',
    category: 'Epistemology',
    summary: 'Eight mind-gates: resting between thoughts, starving the thought-chain, dropping all supports, seer/seen discrimination ripening into identity, the bare ‘I’ as divine self-touch, melting grasped and grasper, watching desire’s whole life, and offering every memory into awareness-fire.',
    relatedVerseIds: ['VB-81', 'VB-82', 'VB-83', 'VB-84', 'VB-85', 'VB-86', 'VB-87', 'VB-88'],
    relatedConceptIds: ['vb-light', 'vb-void', 'vb-devotion'],
  },
  {
    id: 'vb-states',
    title: 'States — waking, sleep, death as doors',
    category: 'Soteriology',
    summary: 'Six states-gates: waking as day-dream, conscious entry into deep sleep, catching the fourth at state-joints and carrying it through all, rehearsed dying, cremation-ground vision — closing in even abiding: containing all states, defined by none.',
    relatedVerseIds: ['VB-89', 'VB-90', 'VB-91', 'VB-92', 'VB-93', 'VB-94'],
    relatedConceptIds: ['vb-void', 'vb-light', 'vb-mind'],
  },
  {
    id: 'vb-body',
    title: 'Body — consciousness wearing skin',
    category: 'Subtle Physiology',
    summary: 'Six body-gates: flesh as condensed light, awareness soaked into each limb, dwelling in luminous inner anatomy, poised ease as posture, fingers sealed as energy-circuits — closing in the whole body claimed as bliss-expanse: joy’s costume worn knowingly.',
    relatedVerseIds: ['VB-95', 'VB-96', 'VB-97', 'VB-98', 'VB-99', 'VB-100'],
    relatedConceptIds: ['vb-bliss', 'vb-energy-body', 'vb-light'],
  },
  {
    id: 'vb-everywhere',
    title: 'Everywhere — omnipresence as fact',
    category: 'Metaphysics in Practice',
    summary: 'Six everywhere-gates: ten-directions pervasion, the wall as consciousness-space, pots and stones as condensed awareness, mind poured into sky and ocean, the Absolute met wherever mind runs — closing in firm conviction carried into action: all this indeed is Bhairava.',
    relatedVerseIds: ['VB-101', 'VB-102', 'VB-103', 'VB-104', 'VB-105', 'VB-106'],
    relatedConceptIds: ['vb-void', 'vb-bliss', 'vb-body'],
  },
  {
    id: 'vb-devotion',
    title: 'Devotion — love, trust, offering',
    category: 'Soteriology',
    summary: 'Six devotion-gates close the 112: melting love, the guru’s sentence held in trust, total self-offering, worship with every mood, grace contemplated as falling light — closing in the summit practice: unbroken ‘I am Bhairava’ through eating, walking, speaking; life itself as mantra.',
    relatedVerseIds: ['VB-107', 'VB-108', 'VB-109', 'VB-110', 'VB-111', 'VB-112'],
    relatedConceptIds: ['vb-frame', 'vb-mind', 'vb-phala'],
  },
  {
    id: 'vb-phala',
    title: 'Fruit — many doors, one hall',
    category: 'Frame',
    summary: 'Bhairava closes by licensing plurality: choose the gate that suits your nature — every door opens onto the same hall. Devī’s satisfaction seals the text: doubt dissolved, not merely answered; the dialogue ends where practice begins.',
    relatedVerseIds: ['VB-C1', 'VB-C2'],
    relatedConceptIds: ['vb-devotion', 'vb-frame'],
  },
];
