import { RawVerse } from '../../factory';

// Vijñānabhairava EN verses, part 3: dhāraṇās 71–112 + closing fruit.
// Own paraphrase; see part 1 header.
export const vijnanabhairavaVersesEn3: RawVerse[] = [
  // ---------- BLISS (D71–D80) ----------
  {
    id: 'VB-71',
    number: 'Dhāraṇā 71',
    section: 'Bliss — delight as gate',
    iast: 'ānande ... mahati ... prāpte ... magnatā',
    conceptIds: ['vb-bliss'],
    translation: 'When great joy arises — from meeting, music, or good news — plunge into the joy itself, forgetting its occasion.',
    commentary: 'Joy’s cause is the disposable wrapper; joy itself is the Self’s nature (ānanda) briefly unveiled. Forgetting the occasion keeps the unveiling: the yogin learns joy needs no reason because joy is what he is.',
    keyPoints: [
      'Joy’s occasion is wrapper; joy is the gift.',
      'Reasonless joy remembered is the Self remembered.',
    ],
  },
  {
    id: 'VB-72',
    number: 'Dhāraṇā 72',
    section: 'Bliss — delight as gate',
    iast: 'āliṅgane ... śakti ... sparśānanda',
    conceptIds: ['vb-bliss'],
    translation: 'In loving embrace, rest in the bliss of union-feeling — neither partner, only meeting; that meeting is Śiva and Śakti as one.',
    commentary: 'The embrace-gate, handled with restraint: attention on union-feeling itself, not on persons or craving. Two melting into one previews the metaphysical truth — Śiva and Śakti were never two.',
    keyPoints: [
      'Rest in union-feeling, not in persons or craving.',
      'Two melting into one previews non-duality.',
    ],
  },
  {
    id: 'VB-73',
    number: 'Dhāraṇā 73',
    section: 'Bliss — delight as gate',
    iast: 'amṛta ... pāne ... bhojane ... tuṣṭi',
    conceptIds: ['vb-bliss'],
    translation: 'In the contentment after fine food or drink, dwell in the settled satisfaction; settled mind is the natural seat of the Self.',
    commentary: 'Tuṣṭi (settled contentment) after nourishment stills the seeking currents. The text treats it as earned samādhi-fuel: a calm lake in which the Self’s face appears without being summoned.',
    keyPoints: [
      'Post-nourishment contentment stills seeking.',
      'A settled lake shows the face unbidden.',
    ],
  },
  {
    id: 'VB-74',
    number: 'Dhāraṇā 74',
    section: 'Bliss — delight as gate',
    iast: 'gītādi ... rasāveśa ... tanmayatva',
    conceptIds: ['vb-bliss', 'vb-sound'],
    translation: 'Carried away by song, dance or poetry into aesthetic rapture (rasāveśa), become that rapture wholly — art’s transport is the Self’s transport.',
    commentary: 'Rasa-theory as yoga: the spectator melted into aesthetic bliss (camatkāra) tastes brahmāsvāda — the flavour of the Absolute — in disguise. Trika refuses to rank this below ‘spiritual’ bliss; bliss is one, its excuses many.',
    keyPoints: [
      'Aesthetic rapture is Absolute-flavour in disguise.',
      'Melted into art, the spectator meets the Self.',
    ],
  },
  {
    id: 'VB-75',
    number: 'Dhāraṇā 75',
    section: 'Bliss — delight as gate',
    iast: 'yatra yatra ... tuṣṭi ... tatraiva ... dhāraṇā',
    conceptIds: ['vb-bliss'],
    translation: 'Wherever contentment is found — in rest, in friendship, in solitude — make that very spot the meditation-seat.',
    commentary: 'The universalising rule of the bliss-gates: any tuṣṭi anywhere is usable. This democratises practice — no cave or ritual needed — and teaches the eye that recognises the Self in pleasant moments to find it everywhere.',
    keyPoints: [
      'Any contentment anywhere is a usable seat.',
      'No special place needed: joy consecrates ground.',
    ],
  },
  {
    id: 'VB-76',
    number: 'Dhāraṇā 76',
    section: 'Bliss — sleep and waking joy',
    iast: 'supta ... prabuddha ... ānandasmaraṇa',
    conceptIds: ['vb-bliss', 'vb-states'],
    translation: 'On waking from deep refreshing sleep, hold the lingering bliss before thoughts return; that pre-thought sweetness is the Self unveiled.',
    commentary: 'Waking carries a brief cargo of sleep’s bliss before the mind reboots. Catching it — abiding in pre-thought sweetness — proves bliss needs no object; it is what remains when objects (including thoughts) are absent.',
    keyPoints: [
      'Waking’s first sweetness precedes thought.',
      'Bliss without object is the Self’s signature.',
    ],
  },
  {
    id: 'VB-77',
    number: 'Dhāraṇā 77',
    section: 'Bliss — sleep and waking joy',
    iast: 'śarīra ... sukha ... āveśa ... smṛti',
    conceptIds: ['vb-bliss', 'vb-body'],
    translation: 'In bodily ease — after bathing, in cool breeze, in rest — pervade the ease with awareness until ease and awareness are one.',
    commentary: 'Gross-comfort gates: the text leaves no experience unemployed. Bodily ease pervaded by attention becomes meditation without posture; comfort, usually the enemy of practice, is conscripted as its vehicle.',
    keyPoints: [
      'Bodily ease pervaded by attention becomes meditation.',
      'Comfort conscripted as vehicle, not enemy.',
    ],
  },
  {
    id: 'VB-78',
    number: 'Dhāraṇā 78',
    section: 'Bliss — sleep and waking joy',
    iast: 'hāsye ... kaumāre ... sahaja ... ullāsa',
    conceptIds: ['vb-bliss'],
    translation: 'In spontaneous laughter or childlike wonder, ride the upsurge (ullāsa) — unplanned joy breaks the planner; broken, he sees.',
    commentary: 'Laughter shatters the controlling mind — hence its yogic use. Sahaja (spontaneous) upsurges bypass effort and reveal the natural state: the planner broken, awareness stands naked and grinning.',
    keyPoints: [
      'Spontaneous upsurge breaks the controlling mind.',
      'The broken planner reveals naked awareness.',
    ],
  },
  {
    id: 'VB-79',
    number: 'Dhāraṇā 79',
    section: 'Bliss — the flood',
    iast: 'ānandaghanatā ... sarvāṅga ... plāvana',
    conceptIds: ['vb-bliss', 'vb-everywhere'],
    translation: 'Feel bliss as a flood drowning every limb — awareness floating, bodiless, in its own sweetness.',
    commentary: 'Bliss intensified to inundation (plāvana): the body floats in joy as in water. Limbs forgotten, the yogin is a wave of the bliss-ocean — jagadānanda, world-bliss, in first taste.',
    keyPoints: [
      'Let bliss flood until limbs are forgotten.',
      'Floating in joy previews world-bliss.',
    ],
  },
  {
    id: 'VB-80',
    number: 'Dhāraṇā 80',
    section: 'Bliss — the flood',
    iast: 'jagadānanda ... iti ... bhāvanā',
    conceptIds: ['vb-bliss', 'vb-everywhere'],
    translation: '‘This whole world is bliss-play’ — holding this vision toward all things, the yogin lives inside cosmic joy (jagadānanda).',
    commentary: 'The bliss-gates close with Trika’s highest affect: jagadānanda, the world experienced as bliss-play. Not personal happiness but ontological joy — existence delighting in existing — made into continuous dwelling.',
    keyPoints: [
      'World-as-bliss-play is Trika’s highest affect.',
      'Existence delighting in existing: continuous dwelling.',
    ],
  },
  // ---------- MIND (D81–D88) ----------
  {
    id: 'VB-81',
    number: 'Dhāraṇā 81',
    section: 'Mind — thought and its gaps',
    iast: 'cittavṛtti ... nirodha ... madhya',
    conceptIds: ['vb-mind'],
    translation: 'Between the ending of one thought and the rising of the next, rest in the middle (madhya); that middle is the Self between two waves.',
    commentary: 'Unmeṣa-practice restated: thought-waves part to show the water. Resting in inter-thought gaps widens them until gap becomes ground and thoughts become visitors — the exact reversal of bondage.',
    keyPoints: [
      'Inter-thought gaps are the Self between waves.',
      'Widen gaps until ground and visitor trade places.',
    ],
  },
  {
    id: 'VB-82',
    number: 'Dhāraṇā 82',
    section: 'Mind — thought and its gaps',
    iast: 'vikalpa ... kṣaya ... nirvikalpatā',
    conceptIds: ['vb-mind'],
    translation: 'Let each thought end without starting its successor — starve the chain; in thought-free clarity (nirvikalpa), the knower stands alone.',
    commentary: 'Active non-continuation: thoughts are allowed to end but not to breed. The chain starved, nirvikalpa dawns — not blankness but clarity without division, the knower knowing without splitting into known.',
    keyPoints: [
      'Let thoughts end without breeding successors.',
      'Thought-free clarity is the knower standing alone.',
    ],
  },
  {
    id: 'VB-83',
    number: 'Dhāraṇā 83',
    section: 'Mind — thought and its gaps',
    iast: 'manas ... śūnya ... ālambana ... tyāga',
    conceptIds: ['vb-mind', 'vb-void'],
    translation: 'Drop every mental support — image, word, idea — and let mind rest supportless; supportless mind discovers it is boundless sky.',
    commentary: 'Ālambana-tyāga (abandoning supports): whatever the mind holds, release. Unsupported, mind panics, then spreads — like sky realising it was never held up. Fear of falling becomes flying.',
    keyPoints: [
      'Release every mental support, one by one.',
      'Supportless mind discovers it is sky.',
    ],
  },
  {
    id: 'VB-84',
    number: 'Dhāraṇā 84',
    section: 'Mind — the witness',
    iast: 'sākṣitva ... dṛśya ... dṛk ... viveka',
    conceptIds: ['vb-mind'],
    translation: 'Whatever appears — thought, mood, sensation — know it as seen, and yourself as the Seer; holding this discrimination, the Seer stands free.',
    commentary: 'Dṛg-dṛśya-viveka (seer/seen discrimination) shared with Vedānta but given Trika’s ending: the Seer finally recognised as not apart from seeing — witness that is also the light. Discrimination ripens into identity.',
    keyPoints: [
      'Whatever appears is seen; you are the Seer.',
      'Ripened, witnessing turns into luminous identity.',
    ],
  },
  {
    id: 'VB-85',
    number: 'Dhāraṇā 85',
    section: 'Mind — the witness',
    iast: 'ahaṃ ... vimarśa ... parāmarśa',
    conceptIds: ['vb-mind'],
    translation: 'Rest in the bare ‘I’ before it becomes ‘I am this’ — that pristine self-reference (vimarśa) is the Goddess herself.',
    commentary: 'Vimarśa — the Self’s self-touch as ‘I’ — is Trika’s supreme principle, Śakti herself. Caught before predicates attach, the ‘I’ is not ego but God-throb; resting there is resting in the source of all knowing.',
    keyPoints: [
      'Bare ‘I’ before predicates is divine self-touch.',
      'Resting there is resting in knowledge’s source.',
    ],
  },
  {
    id: 'VB-86',
    number: 'Dhāraṇā 86',
    section: 'Mind — the witness',
    iast: 'grāhya ... grāhaka ... laya ... samvit',
    conceptIds: ['vb-mind'],
    translation: 'Dissolve the grasped and the grasper into each other until only grasping-consciousness (saṃvit) remains.',
    commentary: 'Subject and object are a divided whole; contemplated into mutual dissolution, the division heals. What remains is saṃvit — consciousness as the single stuff that had been playing both parts.',
    keyPoints: [
      'Melt grasped and grasper into each other.',
      'One stuff remains: consciousness playing both parts.',
    ],
  },
  {
    id: 'VB-87',
    number: 'Dhāraṇā 87',
    section: 'Mind — desire and memory',
    iast: 'icchā ... utpatti ... vilaya ... darśana',
    conceptIds: ['vb-mind'],
    translation: 'Watch a desire arise and dissolve without obeying or fighting it; seen through, desire confesses it was energy seeking rest.',
    commentary: 'Desire contemplated at birth and death reveals its secret: icchā-śakti (will-power) bent into lack-shape. Seen without obedience or war, it straightens back into free will — Śiva’s own freedom in miniature.',
    keyPoints: [
      'Watch desire’s whole life without interference.',
      'Desire seen through straightens into free will.',
    ],
  },
  {
    id: 'VB-88',
    number: 'Dhāraṇā 88',
    section: 'Mind — desire and memory',
    iast: 'smṛti ... mānasī ... pūjā ... laya',
    conceptIds: ['vb-mind', 'vb-devotion'],
    translation: 'Offer every memory as it rises into the fire of awareness — a mental sacrifice; the offered past burns, the offerer shines.',
    commentary: 'The mind-gates close with inner yajña: memories as oblations, awareness as fire. The past burned as offering ceases to rule; the offerer — present awareness — stands clarified, worshipper and worshipped as one.',
    keyPoints: [
      'Offer each memory into awareness-fire.',
      'Burned past ceases to rule; present shines.',
    ],
  },
  // ---------- STATES (D89–D94) ----------
  {
    id: 'VB-89',
    number: 'Dhāraṇā 89',
    section: 'States — waking, dream, sleep',
    iast: 'jāgrat ... svapna ... bhealur ... jñāna',
    conceptIds: ['vb-states'],
    translation: 'Know waking and dream as one continuous projection — dream by night, dream by day; the knower of both never sleeps.',
    commentary: 'Waking demoted to day-dream: both states are consciousness projecting forms. The projector never enters its projections — knowing this while active converts ordinary life into lucid living.',
    keyPoints: [
      'Waking is day-dream; dream is night-waking.',
      'The projector never enters its projections.',
    ],
  },
  {
    id: 'VB-90',
    number: 'Dhāraṇā 90',
    section: 'States — waking, dream, sleep',
    iast: 'suṣupta ... gāḍha ... prabodha ... smṛti',
    conceptIds: ['vb-states'],
    translation: 'Enter deep sleep deliberately, keeping the lamp of awareness lit; sleeping consciously, the yogin conquers the last fortress of forgetting.',
    commentary: 'Yoga-nidrā proper: awareness carried intact into dreamless sleep. The void of sleep, met consciously, proves to be not absence but plenitude — the fortress of moha (delusion) stormed from within.',
    keyPoints: [
      'Carry awareness intact into dreamless sleep.',
      'Conscious sleep converts absence into plenitude.',
    ],
  },
  {
    id: 'VB-91',
    number: 'Dhāraṇā 91',
    section: 'States — waking, dream, sleep',
    iast: 'turya ... sandhi ... sarvāvasthā ... anugama',
    conceptIds: ['vb-states'],
    translation: 'Catch the fourth (turīya) in the joints between states — falling asleep, waking, dreaming’s edge; then trace it through all states.',
    commentary: 'Turīya first glimpsed at thresholds (sandhi), then recognised as the thread running through waking, dream and sleep alike. The practice moves from catching to carrying: the fourth becomes the first — background of all.',
    keyPoints: [
      'Catch the fourth at state-joints first.',
      'Then carry it as the thread of all states.',
    ],
  },
  {
    id: 'VB-92',
    number: 'Dhāraṇā 92',
    section: 'States — death and beyond',
    iast: 'maraṇa ... bhāvanā ... amṛtatva',
    conceptIds: ['vb-states'],
    translation: 'Contemplate one’s own dying — senses withdrawing, breath departing — while fully alive; rehearsed death reveals the undying.',
    commentary: 'Maraṇa-bhāvanā: the staged withdrawal proves by preview that awareness outlasts its instruments. Fear of death, the root-knot, loosens when dying has been survived in advance — amṛtatva (deathlessness) as rehearsed fact.',
    keyPoints: [
      'Rehearse dying while fully alive.',
      'What survives rehearsal is the undying.',
    ],
  },
  {
    id: 'VB-93',
    number: 'Dhāraṇā 93',
    section: 'States — death and beyond',
    iast: 'śmaśāna ... vāsī ... bhairava ... dhyāna',
    conceptIds: ['vb-states', 'vb-void'],
    translation: 'Meditate in cremation-ground awareness — all forms as ash, all stories ended; in that ending, the Unended stands revealed.',
    commentary: 'Śmaśāna (cremation-ground) contemplation, Bhairava’s own dwelling: everything compounded reduced to ash in vision. When even the visualiser is ashed, what watches the ash is notorious — the Unended, needing no cremation.',
    keyPoints: [
      'Reduce all forms to ash in vision.',
      'What watches the ash needs no cremation.',
    ],
  },
  {
    id: 'VB-94',
    number: 'Dhāraṇā 94',
    section: 'States — death and beyond',
    iast: 'sarvāvasthā ... sama ... bhairava ... sthiti',
    conceptIds: ['vb-states'],
    translation: 'Abide evenly in all states — waking, dreaming, sleeping, dying — as Bhairava abides: unchanged, all-containing, free.',
    commentary: 'The states-gates close with evenness (samatā): no state preferred, none feared. The yogin’s stance mirrors Bhairava’s — containing all conditions, defined by none — which is jīvanmukti stated as posture.',
    keyPoints: [
      'No state preferred, none feared: even abiding.',
      'Containing all, defined by none — living freedom.',
    ],
  },
  // ---------- BODY (D95–D100) ----------
  {
    id: 'VB-95',
    number: 'Dhāraṇā 95',
    section: 'Body — the body as consciousness',
    iast: 'deha ... cinmaya ... bhāvanā',
    conceptIds: ['vb-body'],
    translation: 'Contemplate the body as made of consciousness (cinmaya) — flesh as condensed light; the body-idea melts into radiance.',
    commentary: 'Deha redefined: not matter housing spirit but spirit densified. Held steadily, heaviness, illness-identity and age-identity loosen — the body experienced as frozen music begins to thaw into hearing.',
    keyPoints: [
      'Body as condensed light, not housing of spirit.',
      'Flesh-identity loosens into radiance.',
    ],
  },
  {
    id: 'VB-96',
    number: 'Dhāraṇā 96',
    section: 'Body — the body as consciousness',
    iast: 'aṅga ... pratyeka ... caitanya ... vyāpti',
    conceptIds: ['vb-body'],
    translation: 'Feel consciousness individually in each limb — hand, foot, brow — until every part is known as awareness wearing shape.',
    commentary: 'Part-by-part pervasion (praty-aṅga-vyāpti): attention soaks each limb until it answers as awareness. The exercise ends the absentee-landlord relation to the body — every province visited by its king.',
    keyPoints: [
      'Soak each limb in attention until it answers.',
      'Every province visited by its king.',
    ],
  },
  {
    id: 'VB-97',
    number: 'Dhāraṇā 97',
    section: 'Body — the body as consciousness',
    iast: 'netra ... avarodha ... antardṛṣṭi ... deha',
    conceptIds: ['vb-body', 'vb-light'],
    translation: 'With eyes softly closed to the outer, see the inner body of light — channels, lotuses, currents; dwell in that luminous anatomy.',
    commentary: 'The subtle body (sūkṣma-deha) visualised from within replaces the anatomical body as dwelling-place. Living in luminous anatomy, gross compulsions weaken — one tends the house one actually inhabits.',
    keyPoints: [
      'Dwell in the luminous inner anatomy.',
      'Inhabited light weakens gross compulsions.',
    ],
  },
  {
    id: 'VB-98',
    number: 'Dhāraṇā 98',
    section: 'Body — postures and gestures',
    iast: 'āsana ... sthiti ... śithilatā ... samāveśa',
    conceptIds: ['vb-body'],
    translation: 'Sit utterly relaxed yet upright — body loose, spine free; in that poised ease, absorption (samāveśa) descends by itself.',
    commentary: 'Posture-gate without acrobatics: śithilatā (utter looseness) plus upright axis. Tension released, energy flows unblocked and attention, with nothing to manage, sinks inward — ease as method, not reward.',
    keyPoints: [
      'Utterly loose body, free spine: poised ease.',
      'With nothing to manage, attention sinks inward.',
    ],
  },
  {
    id: 'VB-99',
    number: 'Dhāraṇā 99',
    section: 'Body — postures and gestures',
    iast: 'mudrā ... kara ... bhāva ... mudraṇa',
    conceptIds: ['vb-body'],
    translation: 'Seal awareness in a hand-gesture (mudrā) — fingers as circuits of energy; the sealed current turns back and floods the heart.',
    commentary: 'Mudrā as energy-circuit: fingers joined redirect prāṇa inward instead of leaking through the hands. The returned current floods the heart — the body’s wiring consciously looped into self-fulfilment.',
    keyPoints: [
      'Fingers joined redirect leaking energy inward.',
      'Returned current floods the heart.',
    ],
  },
  {
    id: 'VB-100',
    number: 'Dhāraṇā 100',
    section: 'Body — postures and gestures',
    iast: 'sarvaśarīra ... ānandavisphāra ... iti dhīḥ',
    conceptIds: ['vb-body', 'vb-bliss'],
    translation: '‘This whole body is bliss-expanse’ — expanding this feeling through every cell, the body becomes joy wearing skin.',
    commentary: 'The body-gates close with bliss-pervasion: every cell claimed as ānanda. The body ceases to be a problem to transcend or indulge — it is joy’s own costume, worn knowingly.',
    keyPoints: [
      'Claim every cell as bliss-expanse.',
      'Body as joy’s costume, worn knowingly.',
    ],
  },
  // ---------- EVERYWHERE (D101–D106) ----------
  {
    id: 'VB-101',
    number: 'Dhāraṇā 101',
    section: 'Everywhere — omnipresence',
    iast: 'diśaḥ ... ākāśa ... vyāpti ... bhāvanā',
    conceptIds: ['vb-everywhere'],
    translation: 'Spread awareness to all directions at once — east, west, above, below — until direction drowns in directionlessness.',
    commentary: 'Ten-directions pervasion (dig-vyāpti): attention stretched everywhere simultaneously snaps the localising habit. With no ‘here’ left, the yogin is nowhere — which is everywhere.',
    keyPoints: [
      'Stretch attention to all directions at once.',
      'No ‘here’ left: nowhere which is everywhere.',
    ],
  },
  {
    id: 'VB-102',
    number: 'Dhāraṇā 102',
    section: 'Everywhere — omnipresence',
    iast: 'bhitti ... kuḍya ... cidākāśa ... abheda',
    conceptIds: ['vb-everywhere'],
    translation: 'Gaze at a wall as pure consciousness-space — no wall, only seeing; the seer-wall division falls and expanse remains.',
    commentary: 'The famous wall-gate: the dullest object chosen deliberately. If even a wall is consciousness-space, nothing is exempt — duality falls at its most defensible post and the whole fortress surrenders.',
    keyPoints: [
      'Even a wall is consciousness-space.',
      'Duality beaten at its strongest post.',
    ],
  },
  {
    id: 'VB-103',
    number: 'Dhāraṇā 103',
    section: 'Everywhere — omnipresence',
    iast: 'ghaṭa ... paṭa ... sarva ... cinmaya',
    conceptIds: ['vb-everywhere'],
    translation: 'See pot, cloth, stone — each common thing — as condensed consciousness; the marketplace becomes a gallery of the Absolute.',
    commentary: 'Common things as ābhāsa (shining-forth) of the one light: practice extended to the marketplace, not reserved for shrines. When pots preach, metaphysics has become perception.',
    keyPoints: [
      'Common things as condensed consciousness.',
      'Practice in the marketplace, not only the shrine.',
    ],
  },
  {
    id: 'VB-104',
    number: 'Dhāraṇā 104',
    section: 'Everywhere — sky and ocean',
    iast: 'ākāśa ... ananta ... manolaya',
    conceptIds: ['vb-everywhere', 'vb-void'],
    translation: 'Merge the mind in boundless sky or ocean-expanse — no shore, no edge; edgeless seeing becomes edgeless being.',
    commentary: 'Vastness-contemplation (vipula-bhāvanā): mind poured into the shoreless takes its shape — formless, unhurried, immense. Small anxieties cannot survive the transfer; they belong to rooms, not skies.',
    keyPoints: [
      'Pour mind into the shoreless; take its shape.',
      'Anxieties belong to rooms, not skies.',
    ],
  },
  {
    id: 'VB-105',
    number: 'Dhāraṇā 105',
    section: 'Everywhere — sky and ocean',
    iast: 'yatra yatra ... manaḥ ... tatraiva ... brahma',
    conceptIds: ['vb-everywhere'],
    translation: 'Wherever the mind goes — to objects high or low — see Brahman there first; the wanderer becomes a pilgrim, every road a shrine-road.',
    commentary: 'The wandering mind conscripted as scout: wherever it runs, the Absolute is already there. Instead of recalling the runaway, the yogin meets it at its destination — and every destination proves to be home.',
    keyPoints: [
      'Wherever mind runs, the Absolute is already there.',
      'Meet the runaway at its destination: home.',
    ],
  },
  {
    id: 'VB-106',
    number: 'Dhāraṇā 106',
    section: 'Everywhere — sky and ocean',
    iast: 'sarvaṃ khalv idaṃ ... iti ... dṛḍhaniścaya',
    conceptIds: ['vb-everywhere'],
    translation: '‘All this, indeed, is Bhairava’ — firm in this settled conviction through all acts, the yogin walks the world as its Self.',
    commentary: 'The everywhere-gates close with firm conviction (dṛḍhaniścaya) carried into action — not mood but stance. Sarvaṃ khalu (all indeed) converts omnipresence from meditation-topic into walking fact.',
    keyPoints: [
      'All this indeed is Bhairava: stance, not mood.',
      'Omnipresence as walking fact, not sitting topic.',
    ],
  },
  // ---------- DEVOTION (D107–D112) ----------
  {
    id: 'VB-107',
    number: 'Dhāraṇā 107',
    section: 'Devotion — grace and surrender',
    iast: 'bhakti ... tīvrā ... bhagavati ... samāveśa',
    conceptIds: ['vb-devotion'],
    translation: 'With intense devotion to the Goddess, melt in love until lover, beloved and love are one flood.',
    commentary: 'Bhakti as solvent: intense love melts the lover’s edges faster than analysis. When triad melts into flood, devotion reveals its secret — it was always union practising separation so as to enjoy reunion.',
    keyPoints: [
      'Intense love melts the lover’s edges.',
      'Devotion is union enjoying reunion.',
    ],
  },
  {
    id: 'VB-108',
    number: 'Dhāraṇā 108',
    section: 'Devotion — grace and surrender',
    iast: 'guruvākya ... śraddhā ... pratyaya ... siddhi',
    conceptIds: ['vb-devotion'],
    translation: 'Trust the guru’s single word with total faith — ‘You are That’ — and rest in that trust; trusted truth ripens into seen truth.',
    commentary: 'Śabda as upāya: the guru’s sentence (mahāvākya) held in śraddhā (trust) works like a seed in soil. Reasoning rests; ripening happens underground — until one dawn the trusted is the seen.',
    keyPoints: [
      'Hold one true sentence in total trust.',
      'Trusted truth ripens into seen truth.',
    ],
  },
  {
    id: 'VB-109',
    number: 'Dhāraṇā 109',
    section: 'Devotion — grace and surrender',
    iast: 'ātmanivedana ... sarvasva ... arpaṇa',
    conceptIds: ['vb-devotion'],
    translation: 'Offer everything — body, acts, thoughts — at Bhairava’s feet, keeping nothing back; the emptied offerer is filled with the offered-to.',
    commentary: 'Ātma-nivedana (self-offering): the last possession — the manager-self — laid down. Keeping nothing back, there is no keeper left; emptiness of claim invites fullness of presence — grace as physics, not favour.',
    keyPoints: [
      'Offer all, keeping nothing — including the keeper.',
      'Emptiness of claim invites fullness of presence.',
    ],
  },
  {
    id: 'VB-110',
    number: 'Dhāraṇā 110',
    section: 'Devotion — worship as recognition',
    iast: 'pūjā ... sarvabhāva ... bhairava ... arpaṇa',
    conceptIds: ['vb-devotion'],
    translation: 'Worship with every state of mind — anger, joy, dullness, clarity — offering each as flowers; nothing is refused at this altar.',
    commentary: 'Sarva-bhāva-pūjā: moods usually confessed become offered. Nothing refused means nothing repressed — the whole psyche altar-dressed. Bhairava accepts all flowers because all are his own energies returning.',
    keyPoints: [
      'Offer every mood as flowers; refuse nothing.',
      'All energies are his own, returning home.',
    ],
  },
  {
    id: 'VB-111',
    number: 'Dhāraṇā 111',
    section: 'Devotion — worship as recognition',
    iast: 'śaktipāta ... tara ... tīvra ... anugraha',
    conceptIds: ['vb-devotion'],
    translation: 'Contemplate the descent of power (śaktipāta) — grace falling like light into the heart’s darkness; received, it ends all seeking.',
    commentary: 'Grace contemplated as fact: śaktipāta in three intensities (mild, middling, intense), the intense ending seeking at once. Even contemplation of grace attracts grace — the thought of light is already dawn.',
    keyPoints: [
      'Grace descends in measures; the intense ends seeking.',
      'Thought of light is already dawn.',
    ],
  },
  {
    id: 'VB-112',
    number: 'Dhāraṇā 112',
    section: 'Devotion — worship as recognition',
    iast: 'ahaṃ bhairava ... iti ... akhaṇḍa ... smṛti',
    conceptIds: ['vb-devotion'],
    translation: '‘I am Bhairava’ — unbroken remembrance of identity through eating, walking, speaking; life itself becomes the mantra.',
    commentary: 'The 112th gate gathers all: akhaṇḍa-smṛti (unbroken remembrance) of identity worn through ordinary acts. Not a practice among practices but practice become life — pratyabhijñā (recognition) as continuous tense.',
    keyPoints: [
      'Unbroken ‘I am That’ through ordinary acts.',
      'Practice become life: recognition as continuous tense.',
    ],
  },
  // ---------- CLOSING ----------
  {
    id: 'VB-C1',
    number: 'Outro 1',
    section: 'Closing — fruit and charge',
    iast: 'etat ... upāyaśataṃ ... uktaṃ ... yathāgama',
    conceptIds: ['vb-phala'],
    translation: 'These 112 gates are declared according to the Āgamas — choose whichever suits your nature; every gate opens onto the same hall.',
    commentary: 'Bhairava’s closing charge democratises the teaching: fitness (adhikāra) decides the gate, not rank. Plurality of doors with unity of hall is Trika’s answer to one-size practice — temperament as spiritual fact.',
    keyPoints: [
      'Choose the gate that suits your nature.',
      'Many doors, one hall: temperament respected.',
    ],
  },
  {
    id: 'VB-C2',
    number: 'Outro 2',
    section: 'Closing — fruit and charge',
    iast: 'devy uvāca ... tṛptāsmi ... mahādeva',
    conceptIds: ['vb-phala'],
    translation: 'Devī answers: I am satisfied, O Great God — doubt cut, essence grasped; the dialogue closes in fulfilled silence.',
    commentary: 'Satisfaction (tṛpti) is the text’s own seal of completeness: the questioner’s doubt dissolved, not merely answered. The frame closes where practice begins — silence after teaching, the student become the teaching.',
    keyPoints: [
      'Doubt dissolved, not merely answered.',
      'The text ends where practice begins.',
    ],
  },
];
