import { RawVerse } from '../../factory';

// Vijñānabhairava-tantra: the Bhairava-Āgama dialogue of 112 dhāraṇās
// (concentration-gates) taught by Bhairava to Devī. Structural source:
// Jaideva Singh's edition, "Vijñānabhairava or Divine Consciousness"
// (MLBD 2002 — Drive source 1h1EsUYNe4dwrUZ5VrjtUbmEaa8apeRZj).
//
// Carry-over policy (copyright + architecture): Singh's translation and
// commentary are NOT reproduced. Sanskrit wording below is limited to short
// traditional seed-phrases; the English renderings, commentaries and key
// points are this app's own concise paraphrase of the Trika line, in EN + ML,
// with original concept/thread overlays. Frame (Devī's questions) and closing
// (fruit) are carried as verses so the dialogue arc is complete: 118 verses.
export const vijnanabhairavaVersesEn1: RawVerse[] = [
  // ---------- OPENING DIALOGUE ----------
  {
    id: 'VB-F1',
    number: 'Intro 1',
    section: 'Opening Dialogue — Devī’s Questions',
    iast: 'śrutaṃ deva mayā sarvaṃ rudrayāmalasaṃbhavam',
    conceptIds: ['vb-frame'],
    translation: 'Devī asks: I have heard the whole Rudra-yāmala teaching — tell me now the essence by which one knows Bhairava directly.',
    commentary: 'The frame sets the whole text: Devī, already learned in scripture, asks not for more doctrine but for upāya — the direct gate. Bhairava will answer with practice, not metaphysics: 112 doors suited to different temperaments.',
    keyPoints: [
      'The question seeks essence (sāra), not further scripture.',
      'Every dhāraṇā that follows is Bhairava’s direct answer.',
    ],
  },
  {
    id: 'VB-F2',
    number: 'Intro 2',
    section: 'Opening Dialogue — Devī’s Questions',
    iast: 'kiṃ rūpaṃ tattvato deva śabdarāśimayaṃ vibho',
    conceptIds: ['vb-frame'],
    translation: 'What is Bhairava’s true form — is it mantra, sound-powers, ritual, or something beyond all of these?',
    commentary: 'Devī lists the candidates — mantra-collection, the ninefold formula, the three energies — and asks what remains when each is set aside. The question clears the ground: Bhairava is not any content of consciousness.',
    keyPoints: [
      'Mantra, ritual and cosmology are all put in question.',
      'The answer must point beyond every object of awareness.',
    ],
  },
  {
    id: 'VB-F3',
    number: 'Intro 3',
    section: 'Opening Dialogue — Devī’s Questions',
    iast: 'prasādaṃ kuru me nātha niḥśeṣaṃ chindhi saṃśayam',
    conceptIds: ['vb-frame'],
    translation: 'Grant me grace, O Lord — cut away my remaining doubt completely.',
    commentary: 'The plea for prasāda (grace) matters doctrinally: in Trika the final opening is śaktipāta, not effort alone. Yet grace here arrives as method — Bhairava gives 112 practices rather than a single secret.',
    keyPoints: [
      'Grace (prasāda/śaktipāta) frames the whole teaching.',
      'Grace takes the form of usable methods, not favour alone.',
    ],
  },
  {
    id: 'VB-F4',
    number: 'Intro 4',
    section: 'Opening Dialogue — Devī’s Questions',
    iast: 'bhairava uvāca: sādhu sādhu tvayā pṛṣṭaṃ tantra sār am idaṃ priye',
    conceptIds: ['vb-frame'],
    translation: 'Bhairava answers: well asked — this essence of Tantra I now declare; listen with one-pointed awareness.',
    commentary: 'Bhairava praises the question because it seeks the universal (sāmānya) gate usable by all. The one condition stated is ekāgratā — gathered attention — which every dhāraṇā then trains in its own way.',
    keyPoints: [
      'One condition only: one-pointed listening attention.',
      'The teaching claims universal fitness (sarvopāya).',
    ],
  },
  // ---------- BREATH (D1–D12) ----------
  {
    id: 'VB-1',
    number: 'Dhāraṇā 1',
    section: 'Breath — the two pauses',
    iast: 'ūrdhve prāṇo hy adho jīvo visargātmanāv ubhāv',
    conceptIds: ['vb-breath'],
    translation: 'Attend to the two pauses — where the outgoing breath ends and where the incoming breath ends; in that still junction, Bhairava-nature shines.',
    commentary: 'The first and most famous gate: breath turns at two points (bāhya/kumbhaka at the outer end, ābhyantara at the inner). Resting attention exactly on the turning, the meditator meets the pause (viśrānti) where neither breath nor thought moves — pure awareness without support.',
    keyPoints: [
      'The turn-points of breath are doors to thought-free awareness.',
      'No control is needed — only exact attendance at the junction.',
    ],
  },
  {
    id: 'VB-2',
    number: 'Dhāraṇā 2',
    section: 'Breath — the two pauses',
    iast: 'dvādaśānte ... madhyamā ... viśrānti',
    conceptIds: ['vb-breath'],
    translation: 'Follow the breath to the far point twelve finger-breadths out (dvādaśānta) and to the heart within; resting in either extreme, awareness steadies.',
    commentary: 'Breath is traced between its outer limit (bāhya dvādaśānta) and its inner home (hṛdaya). The two extremes mirror each other; settling at either end, the middle current (madhyamā) awakens and thought thins out.',
    keyPoints: [
      'Outer twelve-finger point and inner heart are twin anchors.',
      'Tracing dissolves the meditator into the traced current.',
    ],
  },
  {
    id: 'VB-3',
    number: 'Dhāraṇā 3',
    section: 'Breath — the two pauses',
    iast: 'prāṇāpānāntarāle ... sphurattā',
    conceptIds: ['vb-breath'],
    translation: 'In the interval between in-breath and out-breath, sense a subtle throb (sphurattā) — enter that vibration and abide.',
    commentary: 'Between the two breaths a fine pulsation persists — spanda in miniature. Entering it, the practitioner finds the same throb the Spanda-kārikās praise: awareness aware of its own aliveness before it becomes any object.',
    keyPoints: [
      'The breath-gap carries a subtle throb; enter it.',
      'This is spanda met at the doorway of the body.',
    ],
  },
  {
    id: 'VB-4',
    number: 'Dhāraṇā 4',
    section: 'Breath — fullness',
    iast: 'yadā pūrvāparau bhāgau ... bharitā',
    conceptIds: ['vb-breath'],
    translation: 'When breath fills the whole field — neither rising nor falling — know that state of fullness (bharitā); in it the Goddess of consciousness reveals herself.',
    commentary: 'At moments the breath seems to fill everywhere at once and stop. This bharitā (plenitude) is Bhairava’s own epithet (bharitākāra, ‘of full form’); resting in it, the meditator tastes consciousness as all-pervading fullness rather than a point.',
    keyPoints: [
      'Total fullness of breath = the form of Bhairava himself.',
      'Fullness stills the seeking mind by leaving nothing to seek.',
    ],
  },
  {
    id: 'VB-5',
    number: 'Dhāraṇā 5',
    section: 'Breath — sound and touch',
    iast: 'saḥ śabdena ... haṃsadhvani',
    conceptIds: ['vb-breath', 'vb-sound'],
    translation: 'Hear the breath’s own sound — going out as “saḥ”, coming in as “haṃ” — the natural mantra (haṃsa) repeating by itself.',
    commentary: 'No mantra need be imposed: breath already sounds haṃ-sa, the ajapā (unrecited) repetition of every living being. Listening to it turns a bodily function into ceaseless japa, and the listener merges with the heard.',
    keyPoints: [
      'Breath is the self-repeating haṃsa-mantra.',
      'Listening replaces reciting; effort becomes attendance.',
    ],
  },
  {
    id: 'VB-6',
    number: 'Dhāraṇā 6',
    section: 'Breath — the heart centre',
    iast: 'hṛdaye ... prāṇaśaktiḥ pralīyate',
    conceptIds: ['vb-breath', 'vb-energy-body'],
    translation: 'Lead the breath-stream down into the heart-lotus and let it dissolve there; in that dissolution thought dissolves too.',
    commentary: 'The heart (hṛt-padma) is Trika’s seat of the Self. Breath-energy led there and dissolved (laya) drags the thinking mind with it — citta follows prāṇa — leaving heart-awareness without contents.',
    keyPoints: [
      'Mind follows breath: dissolve breath in the heart, mind follows.',
      'The heart-lotus is the Self’s own chamber.',
    ],
  },
  {
    id: 'VB-7',
    number: 'Dhāraṇā 7',
    section: 'Breath — rising energy',
    iast: 'udgacchantīṃ taḍidrūpāṃ ... suṣumṇā',
    conceptIds: ['vb-breath', 'vb-energy-body'],
    translation: 'Sense the breath-energy rising like lightning through the central channel (suṣumṇā); follow its flash upward to the crown.',
    commentary: 'Prāṇa-śakti rising in suṣumṇā is kuṇḍalinī in her subtle form. The lightning image gives the practice its feel — sudden, bright, upward — and the crown (dvādaśānta above) is where the flash resolves into still light.',
    keyPoints: [
      'The central channel is the highway of ascent.',
      'Rising energy gathers scattered mind into one flash.',
    ],
  },
  {
    id: 'VB-8',
    number: 'Dhāraṇā 8',
    section: 'Breath — retention',
    iast: 'kumbhakena ... stambha ... niścalatā',
    conceptIds: ['vb-breath'],
    translation: 'Retain the breath gently at the heart; as breath stands still, mind stands still — in that pillar of stillness, know Bhairava.',
    commentary: 'Retention (kumbhaka/stambha) is used here as mind-mirror: breath stilled, thought stilled. The practice is gentle — a held fullness, not strain — and the stillness itself is the teacher.',
    keyPoints: [
      'Held breath holds thought; stillness teaches directly.',
      'Gentleness matters — strain recreates the restless mind.',
    ],
  },
  {
    id: 'VB-9',
    number: 'Dhāraṇā 9',
    section: 'Breath — the outer void',
    iast: 'bāhye ... śūnye ... layabhāvanā',
    conceptIds: ['vb-breath', 'vb-void'],
    translation: 'Exhale fully and contemplate the outer void — breath poured out into space; resting there, the inner void opens.',
    commentary: 'The exhaled breath dissolves into outer space; attention poured with it finds no object and turns back as void-awareness. Outer and inner śūnya prove to be one expanse entered from either side.',
    keyPoints: [
      'Exhalation is a bridge into outer space.',
      'Outer void contemplated deeply becomes inner void.',
    ],
  },
  {
    id: 'VB-10',
    number: 'Dhāraṇā 10',
    section: 'Breath — the inner void',
    iast: 'antaḥ śūnye ... ānandalīnatā',
    conceptIds: ['vb-breath', 'vb-void'],
    translation: 'Inhale and contemplate the inner void filling with breath-bliss; awareness melting in that bliss knows the supreme.',
    commentary: 'Companion to the last: the inhaled breath fills inner space, and the filling is felt as bliss (ānanda). Awareness resting in that blissful inner expanse discovers that void is not empty but full of feeling-consciousness.',
    keyPoints: [
      'Inner space filled with breath is bliss, not blankness.',
      'Śūnya in Trika is plenum — fullness without form.',
    ],
  },
  {
    id: 'VB-11',
    number: 'Dhāraṇā 11',
    section: 'Breath — the junction point',
    iast: 'nāsāgre ... bindu ... dṛṣṭi',
    conceptIds: ['vb-breath', 'vb-light'],
    translation: 'Fix soft gaze and attention at the tip of the nose (or between the eyebrows) while breath flows; the point steadies into luminous stillness.',
    commentary: 'A fixed subtle point (bindu) gathers the wandering senses. Breath continues but no longer carries attention away; the point begins to glow inwardly — the first taste of bhairavī mudrā, eyes open yet seeing inward.',
    keyPoints: [
      'One subtle point anchors all the senses at once.',
      'Steadied attention begins to shine by itself.',
    ],
  },
  {
    id: 'VB-12',
    number: 'Dhāraṇā 12',
    section: 'Breath — breath as cosmos',
    iast: 'sarvaṃ ... prāṇamayam ... vibhāvayet',
    conceptIds: ['vb-breath', 'vb-everywhere'],
    translation: 'Contemplate the whole universe as made of breath-energy — all forms rising and falling like one great breathing; entering that vision, separation ends.',
    commentary: 'The closing breath-gate universalises the practice: what breathed in the body breathes as the world. Prāṇa becomes the cosmic pulse (sāmānya-spanda); the meditator no longer breathes — breathing happens as the universe.',
    keyPoints: [
      'Individual breath opens into cosmic pulsation.',
      'The world breathed as one body ends the insider/outsider split.',
    ],
  },
  // ---------- ENERGY BODY (D13–D24) ----------
  {
    id: 'VB-13',
    number: 'Dhāraṇā 13',
    section: 'Energy Body — channels and fire',
    iast: 'madhyanāḍī ... vahni ... ūrdhvagamana',
    conceptIds: ['vb-energy-body'],
    translation: 'Kindle the fire in the navel region and lead it up the middle channel; as it pierces each knot, bliss blazes forth.',
    commentary: 'The navel-fire (jāṭharāgni raised to kuṇḍalinī-fire) rises through suṣumṇā, piercing the granthis (knots) where energy stagnates. Each piercing releases the bliss contracted at that centre — practice felt as inner heat turning to light.',
    keyPoints: [
      'Inner fire rises through the middle channel.',
      'Each pierced knot releases contracted bliss.',
    ],
  },
  {
    id: 'VB-14',
    number: 'Dhāraṇā 14',
    section: 'Energy Body — channels and fire',
    iast: 'dvādaśānte ... śaktiḥ ... śāntarūpā',
    conceptIds: ['vb-energy-body'],
    translation: 'Lead the risen energy to the terminal point above the crown and let it settle there in peaceful form; abiding at that summit, the yogin becomes Śiva.',
    commentary: 'The ascent ends at the upper dvādaśānta — the void above the head. Energy arriving there calms (śānta) into pure consciousness; the practitioner, stationed at the summit, looks down on body and world as emanations, not identity.',
    keyPoints: [
      'Ascent completes in the void above the crown.',
      'Stationed there, the yogin witnesses rather than inhabits the body.',
    ],
  },
  {
    id: 'VB-15',
    number: 'Dhāraṇā 15',
    section: 'Energy Body — lotus centres',
    iast: 'hṛtpadme ... dhyāna ... nimīlana',
    conceptIds: ['vb-energy-body'],
    translation: 'Meditate on the eight-petalled lotus of the heart, its centre empty and luminous; closing the senses inward, enter that inner shrine.',
    commentary: 'The heart-lotus with its petals (the eight powers or eightfold awareness) is Trika’s favourite shrine. Its centre is empty — anāvṛta, uncovered — and that emptiness, contemplated, is the Self: a temple with no idol but awareness.',
    keyPoints: [
      'The heart is an eight-petalled shrine with awareness at its centre.',
      'Sense-withdrawal (nimīlana) is the closing of its doors.',
    ],
  },
  {
    id: 'VB-16',
    number: 'Dhāraṇā 16',
    section: 'Energy Body — lotus centres',
    iast: 'bhrūmadhye ... manas ... laya',
    conceptIds: ['vb-energy-body'],
    translation: 'Fix the mind between the eyebrows and let it dissolve there like camphor in flame; nothing remains but seeing itself.',
    commentary: 'The brow-centre (ājñā) dissolves discursive mind (manolaya) the way flame dissolves camphor — without residue. What remains is not blankness but dṛk-mātra, sheer seeing: the witness tasting its own nature.',
    keyPoints: [
      'Mind dissolves at the brow like camphor in flame.',
      'What survives dissolution is pure seeing.',
    ],
  },
  {
    id: 'VB-17',
    number: 'Dhāraṇā 17',
    section: 'Energy Body — tones in the channels',
    iast: 'nāḍīcakre ... nāda ... anāhata',
    conceptIds: ['vb-energy-body', 'vb-sound'],
    translation: 'Listen within the wheel of channels for the unstruck sound (anāhata-nāda) humming by itself; merging with it, the mind goes still.',
    commentary: 'Subtle sound arises uncaused in deep quiet — humming, bell, or thunder. It is heard not with ears but with inward attention; following it inward, sound thins into silence and carries the listener with it — laya through nāda.',
    keyPoints: [
      'Inner sound arises by itself in deep quiet.',
      'Following it inward, sound dissolves into silence.',
    ],
  },
  {
    id: 'VB-18',
    number: 'Dhāraṇā 18',
    section: 'Energy Body — pervading energy',
    iast: 'vyāpinī ... śakti ... sarvadehe',
    conceptIds: ['vb-energy-body', 'vb-everywhere'],
    translation: 'Feel energy pervading the whole body at once — every limb alive with the same current; in that total pervasion, the body-sense melts.',
    commentary: 'Vyāpinī (the Pervasive) is one of Trika’s great rays: energy felt everywhere simultaneously. When the whole body hums as one field, the boundary-sense (this limb, that limb) dissolves and the body is known as condensed consciousness.',
    keyPoints: [
      'Feel the whole body as one energy-field at once.',
      'Total pervasion melts the map of separate limbs.',
    ],
  },
  {
    id: 'VB-19',
    number: 'Dhāraṇā 19',
    section: 'Energy Body — the skin of space',
    iast: 'tvak ... ākāśa ... sparśalaya',
    conceptIds: ['vb-energy-body', 'vb-senses'],
    translation: 'Contemplate the skin as space itself — touch dissolving into expanse; the body’s outer wall falls and awareness spreads.',
    commentary: 'Skin is the boundary-sense. Meditated as ākāśa (space), touch loses its edge: there is no longer inside-skin versus outside-air, only one tactile expanse. The oldest wall of ego — the body’s surface — becomes porous.',
    keyPoints: [
      'Meditate the skin-boundary as space.',
      'When touch has no edge, self has no wall.',
    ],
  },
  {
    id: 'VB-20',
    number: 'Dhāraṇā 20',
    section: 'Energy Body — nectar above',
    iast: 'tālvagre ... amṛta ... āplavana',
    conceptIds: ['vb-energy-body', 'vb-bliss'],
    translation: 'Turn the tongue to the palate’s root and taste the dripping nectar (amṛta); flooded with that sweetness, awareness knows bliss as its own taste.',
    commentary: 'The palate-root (tālu) is the gate of the moon-centre whose nectar drips in advanced practice — kevalam amṛtam. Even imagined, the sweet flooding gathers mind into bliss; bliss recognised as the Self’s flavour is the gate, not the drink.',
    keyPoints: [
      'Inward-turned attention tastes spontaneous sweetness.',
      'Bliss recognised as one’s own flavour stills all seeking.',
    ],
  },
  {
    id: 'VB-21',
    number: 'Dhāraṇā 21',
    section: 'Energy Body — the twelve-petalled lotus',
    iast: 'nābhicakre ... dvādaśāra ... bhāvanā',
    conceptIds: ['vb-energy-body'],
    translation: 'Meditate on the navel wheel with its twelve spokes as the zodiac of inner powers; seeing each energy as a ray of oneself, the centre holds firm.',
    commentary: 'The navel-cakra’s twelve petals mirror cosmic cycles (months, signs). Contemplated as one’s own rays, outer time is drawn inward: the yogin becomes the still hub of a turning wheel rather than a leaf blown round it.',
    keyPoints: [
      'The navel wheel mirrors cosmic time in the body.',
      'Be the hub, not the turning rim.',
    ],
  },
  {
    id: 'VB-22',
    number: 'Dhāraṇā 22',
    section: 'Energy Body — sleeping serpent',
    iast: 'kuṇḍalinī ... suptā ... prabodhana',
    conceptIds: ['vb-energy-body'],
    translation: 'Awaken the coiled power sleeping at the base — rouse her with breath and attention; as she straightens, worlds straighten with her.',
    commentary: 'Kuṇḍalinī sleeps coiled three-and-a-half times round the base-centre, blocking the middle channel with her mouth. Breath, mantra-feeling and attention rouse her; rising straight, she drinks the moon’s nectar above — the classic inner alchemy in seed-form.',
    keyPoints: [
      'The coiled power sleeps at the base blocking ascent.',
      'Roused, she rises straight and floods the crown.',
    ],
  },
  {
    id: 'VB-23',
    number: 'Dhāraṇā 23',
    section: 'Energy Body — the great pervasion',
    iast: 'samanā ... unmanā ... vyāpikā',
    conceptIds: ['vb-energy-body', 'vb-everywhere'],
    translation: 'Rise with energy past the crown through samanā to unmanā — the Transmental; there is no support left, only pervasion without edge.',
    commentary: 'Above the crown lie the subtle stations — vyāpinī, samanā, unmanā — where even the sense of upward movement ends. Unmanā (‘beyond mind’) is supportless awareness: no point, no channel, no direction — the energy-body’s final gate into formlessness.',
    keyPoints: [
      'Above the crown, stations thin out into supportlessness.',
      'Unmanā is pervasion with no centre and no edge.',
    ],
  },
  {
    id: 'VB-24',
    number: 'Dhāraṇā 24',
    section: 'Energy Body — body as mantra',
    iast: 'mātṛkā ... cakranyāsa ... dehabhāva',
    conceptIds: ['vb-energy-body', 'vb-sound'],
    translation: 'Install the mother-letters (mātṛkā) in the body’s centres — each sound a goddess in her station; the body becomes a living mantra.',
    commentary: 'Nyāsa practice: the fifty sounds of the alphabet are placed in body-stations as śaktis. The body ceases to be flesh-map and becomes speech-map — condensed Word (parā-vāk) — and touching any centre touches its goddess.',
    keyPoints: [
      'Each body-centre houses a sound-power.',
      'The nyāsa-body is speech before it is flesh.',
    ],
  },
];
