import { BrahmaSutra } from "./brahma-sutras-en";

export interface BrahmaSutraWithSanskrit extends BrahmaSutra {
  sanskrit: string;
}

export const brahmaSutrasEnAdhyaya3Part1: BrahmaSutraWithSanskrit[] = [
  // ADHYAYA 3: SADHANA ADHYAYA (The Chapter on Spiritual Practice)
  // PADA 1: The Soul's Journey and Reincarnation (Panchagni Vidya)
  {
    id: "3.1.1",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 1,
    sanskrit: "तदन्तरप्रतिपत्तौ रंहति संपरिष्वक्तः प्रश्ननिरूपणाभ्याम् ॥ १ ॥",
    translation: "In obtaining another (body) it goes enveloped (by subtle elements), as appears from the question and explanation (in the scripture).",
    commentary: "The transmigrating soul departs enveloped, not naked: the Pañcāgni question — how does poured water become man in the fifth oblation? — is answered through faith, moon, rain, food and semen offered into heaven, rain-god, earth, man and woman. Water therefore wraps the traveller as seed of the next body, stretching toward it like a leech reaching the next blade. Question and solution together prove the subtle escort."
  },
  {
    id: "3.1.2",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 2,
    sanskrit: "त्र्यात्मकत्वात्तु भूयस्त्वात् ॥ २ ॥",
    translation: "But on account of (water) consisting of three elements and because of the preponderance (of water in the human body).",
    commentary: "Water is named because every element is tripartite — each containing all three — and water preponderates in semen and the body it builds. Naming follows the majority, as settled before. The escort is mixed elements, called water after its chief."
  },
  {
    id: "3.1.3",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 3,
    sanskrit: "प्राणगतेश्च ॥ ३ ॥",
    translation: "And on account of the going of the Pranas (with the soul).",
    commentary: "The prāṇas travel too: when the soul weakens, the organs gather round it, and together they throw off the old body for a newer form. The retinue follows its master. Departure is a household moving, not a solitary flight."
  },
  {
    id: "3.1.4",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 4,
    sanskrit: "अग्न्यादिगतिश्रुतेरिति चेन्न भाक्तत्वात् ॥ ४ ॥",
    translation: "If it be said (that the Pranas do not follow the soul) on account of the scriptural statements as to entering into Agni (fire) etc., (we say) no, on account of its being secondary (figurative).",
    commentary: "'Speech merges into fire' at death is secondary speech for functions withdrawing into their deities — for the same organs must serve the return journey, and what truly dissolved could not reassemble. Figurative merger, not annihilation. The retinue is dismissed in language, not in being."
  },
  {
    id: "3.1.5",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 5,
    sanskrit: "प्रथमेऽश्रवणादिति चेन्न ता एव हि उपपत्तेः ॥ ५ ॥",
    translation: "If it be objected on the ground of water not being mentioned in the first (fire), (we say) no, for that (water) alone is meant, on account of fitness.",
    commentary: "The first oblation names faith, not water — yet water alone is meant, by fitness: the poured oblation-fluid runs through all five fires, and the finale declares water become man in the fifth. What crowns the series governs it. Fitness reads the first fire by the last word."
  },
  {
    id: "3.1.6",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 6,
    sanskrit: "अश्रुतत्वादिति चेन्न इष्टादिकारिणां प्रतीतेः ॥ ६ ॥",
    translation: "If it be said that (the soul is) not stated (in the text), (we say) no, on account of the performers of sacrifices etc. being understood.",
    commentary: "The travelling soul need not be named to be meant: performers of sacrifice and knowers of the fires are understood as the subjects throughout. Context supplies the traveller. Rites without agents are unthinkable, so agents ride within every rite-text."
  },
  {
    id: "3.1.7",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 7,
    sanskrit: "भाक्तं वानात्मवित्त्वात्तथाहि दर्शयति ॥ ७ ॥",
    translation: "Or it is figurative, on account of their not knowing the Self; for thus (the scripture) shows.",
    commentary: "Or the ascent is figurative for those not knowing the Self — passage-language praising the course rather than reporting their literal ride, for thus scripture shows the knower passing beyond while the ignorant merely circle. Eulogy wears the dress of itinerary. The letter serves those who cannot yet read the spirit."
  },
  {
    id: "3.1.8",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 8,
    sanskrit: "कृतात्ययेऽनुशयवान् दृष्टस्मृतिभ्यां यतेतमनेवंच ॥ ८ ॥",
    translation: "On the exhaustion of (good) work, (the soul) with residual Karma (descends), as is known from the Sruti and Smriti, along the path it went by, and differently too.",
    commentary: "Merit spent, the soul descends with a remainder — anuśaya, the unexhausted balance — gliding back down the ascent path and by byways too, as śruti ('having enjoyed, he returns hither') and smṛti agree. Heaven is a sojourn, not a home. The ticket was always a return."
  },
  {
    id: "3.1.9",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 9,
    sanskrit: "चरणादिति चेन्नोपलक्षणार्थेति कार्ष्णाजिनिः ॥ ९ ॥",
    translation: "If it be said (that the soul descends with a remainder of works) on account of conduct, (we say) no, for (the word 'conduct' is used) to indicate (the remainder), so thinks Karshnajini.",
    commentary: "Kārṣṇājini reads the conduct-text as indicator: 'those of good conduct win good birth' points to the karmic remainder, conduct naming the balance it reveals. The word indicates what it cannot state. Behaviour is the visible edge of the unseen remainder."
  },
  {
    id: "3.1.10",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 10,
    sanskrit: "आनर्थक्यमिति चेन्न तदपेक्षत्वात् ॥ १० ॥",
    translation: "If it be said that (conduct would then be) purposeless, (we say) no, on account of (Karma) being dependent on that (conduct).",
    commentary: "Conduct is not purposeless on this reading, for works depend on it — good conduct yields capacity and occasion for good deeds, as soil favours seed. The indicator sustains the indicated. Dependence gives the word its work."
  },
  {
    id: "3.1.11",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 11,
    sanskrit: "सुकृतदुष्कृते एवेति तु बादरिः ॥ ११ ॥",
    translation: "But Badari thinks that (conduct means) good and evil works only.",
    commentary: "Bādari reads it plainer: conduct means good and evil works themselves, not a remainder behind the word. The text says deeds because deeds decide. Simplicity favours the direct sense."
  },
  {
    id: "3.1.12",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 12,
    sanskrit: "अनिष्टादिकारिणामपि च श्रुतम् ॥ १२ ॥",
    translation: "And of those who do not perform sacrifices etc., (the ascent to the moon) is declared by scripture.",
    commentary: "Even non-sacrificers ascend — 'all who depart reach the moon' declares it — rising to receive remainder-fruits or to wane through the fortnights. Scripture leaves none behind at death. The moon gathers all travellers, whatever road they walked."
  },
  {
    id: "3.1.13",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 13,
    sanskrit: "संयमने त्वनुभूयेतरेषामारोहावरोहौ तद्गतिदर्शनात् ॥ १३ ॥",
    translation: "But of the others, after having experienced (the results of their evil deeds) in Yama's abode, there is ascent and descent; for such a course is declared (by scripture).",
    commentary: "The evildoers detour through Yama's abode, suffering their deeds before any ascent and descent — the declared course of dialogues with Death and visions of torment. Justice precedes return. The downward road passes through reckoning."
  },
  {
    id: "3.1.14",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 14,
    sanskrit: "स्मरन्ति च ॥ १४ ॥",
    translation: "And the Smritis also declare (this).",
    commentary: "Smṛtis echo the verdict — Manu's torments, the epics' hells and returns. Both canons describe the same reckoning. Song confirms scripture."
  },
  {
    id: "3.1.15",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 15,
    sanskrit: "अपि च सप्त ॥ १५ ॥",
    translation: "And moreover there are seven (hells).",
    commentary: "Seven hells besides — Raurava and its fellows — ward the variety of evils with matching pains. Manifold deeds need manifold wards. Number follows desert."
  },
  {
    id: "3.1.16",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 16,
    sanskrit: "तत्रापि तद्व्यापारादविरोधः ॥ १६ ॥",
    translation: "Even there (in those hells) there is no contradiction, on account of his (Yama's) control.",
    commentary: "No contradiction troubles even those hells, for Yama's control orders pains — assigns, measures, releases — as a king governs prisons. Governed suffering is coherent suffering. Sovereignty explains the administration."
  },
  {
    id: "3.1.17",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 17,
    sanskrit: "विद्याकर्मणोरिति तु प्रकृतत्वात् ॥ १७ ॥",
    translation: "But (the reference is to) knowledge and work, on account of those two being the subject under discussion.",
    commentary: "The two paths under discussion are knowledge and work — the bright way of the knower and the smoky way of the sacrificer — and the third place is defined against exactly these two. Subject fixes reference. What is discussed decides what is meant."
  },
  {
    id: "3.1.18",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 18,
    sanskrit: "न तृतीये तथोपलब्धेः ॥ १८ ॥",
    translation: "(In the case of) the third (place), not so, because it is thus perceived.",
    commentary: "The third place neither ascends nor descends — worms, moths and sprouts are perceived cycling here, born again on the spot. Direct sight settles it. What never leaves needs no road back."
  },
  {
    id: "3.1.19",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 19,
    sanskrit: "स्मर्यतेऽपि च लोके ॥ १९ ॥",
    translation: "It is also recorded in the Smriti, and in ordinary life.",
    commentary: "Smṛti records it and ordinary life displays it — the epics' insect births, the four wombs of the living seen all around. Record and sight agree. The third place is common knowledge."
  },
  {
    id: "3.1.20",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 20,
    sanskrit: "दर्शनाच्च ॥ २० ॥",
    translation: "And on account of observation.",
    commentary: "Observation clinches it: plant and small-creature rounds proceed visibly without any lunar journey. Experience corroborates the text. What is seen daily needs no distant proof."
  },
  {
    id: "3.1.21",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 21,
    sanskrit: "तृतीयशब्दावरोधः संशोकजस्य ॥ २१ ॥",
    translation: "The third term includes that which springs from heat.",
    commentary: "The sweat-born fall under the third term — heat-born moisture-beings counted with sprouts, so three words cover four births: womb, egg, earth and sweat. Classification bends to include. Nothing living is left homeless."
  },
  {
    id: "3.1.22",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 22,
    sanskrit: "तत्स्वाभाव्यापत्तिरुपपत्तेः ॥ २२ ॥",
    translation: "(On the part of the descending soul) there is becoming of the same nature with them, on account of appropriateness.",
    commentary: "The descender becomes of their nature — rain-like with rain, grain-like with grain — by subtle clinging, as appropriateness dictates. 'Becoming' means contact, not essence. The traveller takes the colour of each station."
  },
  {
    id: "3.1.23",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 23,
    sanskrit: "नातिचिरेण विशेषात् ॥ २३ ॥",
    translation: "(The soul passes through those stages) not in a very long time, on account of special statement.",
    commentary: "The transit is swift, not lingering — special texts time it briefly, rain falling and grain growing on their own schedules while the soul passes quickly through. Stated brevity rules out delay. The stations are touched, not inhabited."
  },
  {
    id: "3.1.24",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 24,
    sanskrit: "अन्याधिष्ठिते पूर्ववदभिलापात् ॥ २४ ॥",
    translation: "(The descending soul entering into plants) is in that which is animated by another (soul), because the statement is as in the previous cases.",
    commentary: "In rice and plants the descender shares a frame already animated by another — the plant-soul — since 'becoming' was already settled as association, not sole tenancy. The language of the previous cases governs. Sharing a house is not owning it, and plant-karma stays unconfused."
  },
  {
    id: "3.1.25",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 25,
    sanskrit: "अशुद्धमिति चेन्न शब्दात् ॥ २५ ॥",
    translation: "If it be said that (sacrificial work is) unholy, (we say) no, on account of scripture.",
    commentary: "Sacrifice is not unholy for its killing: scripture itself enjoins the rite, and the general 'do not injure' yields to the stated exception. The Veda cannot command evil. What is authorized is pure by authorization."
  },
  {
    id: "3.1.26",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 26,
    sanskrit: "रेतःसिग्योगोऽथ ॥ २६ ॥",
    translation: "Then (the soul gets) connected with him who performs the act of generation.",
    commentary: "Then comes union with the generator — the soul entering the father in the act of generation, its final vehicle before the womb. Descent narrows to a point. One connection more, and birth begins."
  },
  {
    id: "3.1.27",
    adhyaya: 3,
    pada: 1,
    sutraNumber: 27,
    sanskrit: "योनेः शरीरम् ॥ २७ ॥",
    translation: "From the womb (comes) the body.",
    commentary: "From the womb comes the body — mother's blood and food building flesh around the entered soul. Birth completes the descent and the cycle closes. The traveller who left enveloped returns embodied."
  },

  // PADA 2: The States of the Soul and the Nature of Brahman
  {
    id: "3.2.1",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 1,
    sanskrit: "सध्ये सृष्टिराह हि ॥ १ ॥",
    translation: "In the intermediate state (i.e., dream) there is (real) creation; for (scripture) says so.",
    commentary: "The second section opens with the objector's triumph: in the intermediate state — dream at the junction of waking and sleep, of this world and the other — creation is real, for 'he creates chariots, animals, roads' says the text. Scripture's creative verb seems to settle it. The doubt is whether seeming making is true making."
  },
  {
    id: "3.2.2",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 2,
    sanskrit: "निर्मातारं चैके पुत्रादयश्च ॥ २ ॥",
    translation: "And some (assert the Supreme Self to be) the creator (of the dream objects); and sons etc. (are the objects desired).",
    commentary: "Some crown the Lord as dream-maker, fashioning sons and delights for the sleeper's wish — divine craftsmanship answering desire. The theory honours both the creative verb and the wished-for objects. Dream becomes providence in miniature."
  },
  {
    id: "3.2.3",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 3,
    sanskrit: "मायामात्रं तु कार्त्स्न्येनानभिव्यक्तस्वरूपत्वात् ॥ ३ ॥",
    translation: "But it (the dream world) is mere illusion, on account of its nature not being manifest in its totality.",
    commentary: "But dream is mere illusion: its nature never manifests in totality — chariots without wood, roads without ground, elephants in a bed's breadth, dawn breaking in a moment. Time, place and material all fail the test. What cannot stand complete cannot stand real."
  },
  {
    id: "3.2.4",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 4,
    sanskrit: "सूचकश्च हि श्रुतेराचक्षते च तद्विदः ॥ ४ ॥",
    translation: "But (the dream) is an omen, on account of scripture; and the experts also declare this.",
    commentary: "Yet dream serves as omen: scripture reads the black-toothed rider as death's herald, and experts in signs agree. Illusory as things, dreams are true as pointers. Falsity of substance leaves room for truth of signal."
  },
  {
    id: "3.2.5",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 5,
    sanskrit: "पराभिध्यानात्तु तिरोहितं ततो ह्यस्य बन्धविपर्ययौ ॥ ५ ॥",
    translation: "But by meditation on the Supreme Lord, that which is hidden (becomes manifest); for from Him are its bondage and release.",
    commentary: "Concealment lifts by meditating the Supreme Lord — the soul's hidden glory manifests, for from Him come both its bondage and its release. The same hand that veils unveils. Grace turns the key it once turned against."
  },
  {
    id: "3.2.6",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 6,
    sanskrit: "देहयोगाद्वा सोऽपि ॥ ६ ॥",
    translation: "And that (concealment) also (results) from its connection with the body.",
    commentary: "Embodiment itself veils: connection with the body dulls senses, tires faculties, narrows reach — the lamp dimmed by its shade. Limitation explains hiddenness without blaming the light. The soul forgets because it wears."
  },
  {
    id: "3.2.7",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 7,
    sanskrit: "तदभावो नाडीषु तच्छ्रुतेरात्मनि च ॥ ७ ॥",
    translation: "The absence of that (i.e., dream) (takes place) in the Nadis and in the Self, according to scriptural statements.",
    commentary: "Deep sleep rests in both the nerves and the Self — 'he rests in the veins,' 'he becomes one with the Existent' — vehicle and ground together, as a traveller both in the house and on the bed. The texts divide the labour. Where sleep happens and what sleep is are different questions with compatible answers."
  },
  {
    id: "3.2.8",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 8,
    sanskrit: "अतः प्रबोधोऽस्मात् ॥ ८ ॥",
    translation: "Therefore the awaking (is) from Him.",
    commentary: "Therefore waking rises from Him — from that Self the sleeper emerges back into the world, as from home into the street. Same source, same returner. The morning's first step starts where the night dissolved."
  },
  {
    id: "3.2.9",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 9,
    sanskrit: "स एव तु कर्मानुस्मृतिशब्दविधिभ्यः ॥ ९ ॥",
    translation: "But the very same (soul returns from deep sleep), on account of work, remembrance, scriptural text, and injunctions.",
    commentary: "The very same soul returns, on fourfold ground: unfinished work awaits its worker, memory owns the rest ('I slept well'), texts declare the return, and injunctions command the same agent to resume. Substitution would orphan duties and memories alike. Identity is what makes morning meaningful."
  },
  {
    id: "3.2.10",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 10,
    sanskrit: "मुग्धेऽर्धसंपत्तिः परिशेषात् ॥ १० ॥",
    translation: "In a swoon (there is) half-union, on account of this remaining (as the only alternative).",
    commentary: "Swoon is half-union: neither waking's full grip nor sleep's full merger — the struck man hangs between, conscious neither here nor there. Alternatives exhausted, this remains the only account. Fainting is the soul's doorway state, and with it the states of the soul stand mapped as far as this volume reaches."
  },
  {
    id: "3.2.11",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 11,
    sanskrit: "न स्थानतोऽपि परस्योभयलिङ्गं सर्वत्र हि ॥ ११ ॥",
    translation: "Not even from place (does any imperfection attach to Brahman), because everywhere (the Supreme Being is described as) having a twofold characteristic.",
    commentary: "A new inquiry opens on Brahman known in sleep: texts describe Him both with qualities, as doer of all deeds and all desires in Ch. III.xiv.2, and without any, as neither gross nor minute in Br. III.viii.8. The opponent would grant Him both aspects together. The siddhānta denies even adjunct-based duality, for a crystal stays transparent beside red lac, error alone painting it opaque, while Ka. I.iii.15 and its kin reveal the attributeless Self as the primary purport.",
  },
  {
    id: "3.2.12",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 12,
    sanskrit: "भेदादिति चेन्न प्रत्येकमतद्वचनात् ॥ १२ ॥",
    translation: "If it be said that (it is not so) on account of difference, (we say) no, because with reference to each (such state) what is not that (i.e., imperfection) is declared.",
    commentary: "The opponent cites meditative differences, four-footed Brahman in Ch. III.xviii.2, sixteen-part in Pr. VI.1, three-worlds-bodied in Br. I.iii.22 and Vaiśvānara, demanding a qualified Brahman lest those texts lose scope. Śaṅkara replies that each difference is individually retracted beside its statement, as in Br. II.v.1 where earth-dweller and body-dweller are declared one Self. Difference serves meditation; non-difference is the intended truth.",
  },
  {
    id: "3.2.13",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 13,
    sanskrit: "अपि चैवमेके ॥ १३ ॥",
    translation: "Moreover some (teach) thus.",
    commentary: "Further, followers of certain branches explicitly condemn duality and teach unity alone. Ka. II.i.11 declares there is no diversity whatsoever and one passing from death to death who sees difference. Sv. I.12 gathers experiencer, experienced and ordainer into Brahman alone. Such summaries confirm that varied forms are provisional, while non-duality is the settled doctrine.",
  },
  {
    id: "3.2.14",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 14,
    sanskrit: "अरूपवदेव हि तत्प्रधानत्वात् ॥ १४ ॥",
    translation: "For (Brahman is) merely without form, on account of that being the main purport.",
    commentary: "Why privilege the formless reading when both classes of text exist? Because formlessness is the dominant note, established already under I.i.4: Br. III.viii.8, Ka. I.iii.15, Ch. VIII.xiv.1, Mu. II.i.2 and Br. II.v.19 all aim directly at the transcendent Self. Passages ascribing mind, prāṇa or effulgence aim chiefly at enjoining meditation. Where meanings clash, what is primary outweighs what is instrumental.",
  },
  {
    id: "3.2.15",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 15,
    sanskrit: "प्रकाशवच्चावैयर्थ्यात् ॥ १५ ॥",
    translation: "And as light (assumes forms), for the sake of non-futility (of the texts).",
    commentary: "Form-texts need not become meaningless. As sunlight spread everywhere still looks straight or bent beside fingers and the like, so Brahman appears with earth and other forms through adjuncts for meditation. Injunctions can fasten on those appearances without touching His essence. Both scriptural classes thus retain validity, one declaring nature, the other guiding worship.",
  },
  {
    id: "3.2.16",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 16,
    sanskrit: "आह च तन्मात्रम् ॥ १६ ॥",
    translation: "And (scripture) declares (Brahman) to consist of that (i.e., intelligence) only.",
    commentary: "Scripture further declares Brahman to be consciousness alone, excluding alien features. Br. IV.v.13 compares the Self to a lump of salt, without inside or outside, wholly saline in taste, even so entire and pure intelligence. No interstice admits a second attribute. Impartite awareness is His whole being, not one quality among others.",
  },
  {
    id: "3.2.17",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 17,
    sanskrit: "दर्शयति चाथो अपि स्मर्यते ॥ १७ ॥",
    translation: "And (scripture) shows (this); so also the Smritis declare.",
    commentary: "Veda reveals the same by negation, as in Br. II.iii.6 not this, not this, Ke. I.4 different from known and above unknown, and Tai. II.ix.1 where words turn back. Bādhva answers Bāṣkali by silence, teaching quiescence itself. Smṛti agrees: Gītā XIII.12 denies gross and subtle of the knowable, while Nārāyaṇa tells Nārada His qualified vision is Māyā alone.",
  },
  {
    id: "3.2.18",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 18,
    sanskrit: "अत एव चोपमा सूर्यकादिवत् ॥ १८ ॥",
    translation: "And therefore the comparisons like the images of the sun etc. (are used).",
    commentary: "Hence liberation texts illustrate the one Self by the sun reflected in many waters. Though one, the sun looks manifold entering divided pots; so the birthless Self-effulgent appears diversified entering bodies. Amṛtabindu 12 says likewise of the moon in water. The figure keeps the conditioned aspect unreal and adjunct-born, while unity remains real.",
  },
  {
    id: "3.2.19",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 19,
    sanskrit: "अम्बुवदग्रहणात्तु न तथात्वम् ॥ १९ ॥",
    translation: "But (the comparison is) not so, on account of the non-apprehension (of Brahman) as (the sun is apprehended) in water.",
    commentary: "An objector rejects the figure: sun and water are separate, remote, material things with form, apt for images, whereas the Self is formless, all-pervasive and non-different from all, with no similarly detached adjunct. The parallel therefore seems inapt. If nothing stands apart like water, reflection language collapses.",
  },
  {
    id: "3.2.20",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 20,
    sanskrit: "वृद्धिह्रासभाक्त्वमन्तर्भावादुभयसामञ्जस्यादेवम् ॥ २० ॥",
    translation: "(Brahman) participates in the increase and decrease (of the limiting adjuncts) on account of its being inside; thus the appropriateness of the two (is maintained).",
    commentary: "The reply concedes partial likeness only, for illustration needs one intended point, not likeness in every respect, else illustration and illustrated would merge. Here the point is sharing increase and decrease: the image swells, wanes and trembles with water while the sun stays unchanged. So Brahman, entering the body, seems to grow and diminish with it while ever the same, and scripture itself having offered the image, scope must be found for it.",
  },
  {
    id: "3.2.21",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 21,
    sanskrit: "दर्शनाच्च ॥ २१ ॥",
    translation: "And on account of the declaration (of scripture).",
    commentary: "Revelation also shows that very entry into adjuncts. Br. II.v.18 says the Supreme first entered bodies as a bird, and Ch. VI.iii.2 says myself entering as this individual Self. Immanence thus grounds the reflection teaching. The conclusion stands: Brahman is distinctionless and single in aspect, not dual or reversed.",
  },
  {
    id: "3.2.22",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 22,
    sanskrit: "प्रकृतैतावत्त्वं हि प्रतिषेधति ततो ब्रवीति च भूयः ॥ २२ ॥",
    translation: "For (the Sruti) denies the having that much only which had been mentioned (as the form of Brahman), and then says something more.",
    commentary: "Br. II.iii.1 begins with two forms, gross and subtle, mortal and immortal, then says not so, not so. The doubt is whether forms, possessor, or both are denied, with two negatives perhaps matching two aspects. Śaṅkara denies the forms alone: total denial would be nihilism, leaving no substratum like rope beneath snake, and would contradict the opening I will tell you of Brahman plus Tai. II.vi.1 and Ka. II.iii.13. What follows, Truth of truth, proves Brahman survives negation as beyond all this much.",
  },
  {
    id: "3.2.23",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 23,
    sanskrit: "तदव्यक्तमाह हि ॥ २३ ॥",
    translation: "That (Brahman) is unmanifest, for (scripture) says so.",
    commentary: "If that superior Brahman exists beyond denied manifestations, why is He not perceived? Because He is unmanifest, the supersensuous witness of all. Mu. III.i.3 denies grasp by eye, speech or austerity; Br. III.ix.26 calls Him never perceived; Mu. I.i.6 and Tai. II.vii.1 echo His bodiless inexpressibility. Gītā II.25 likewise names Him unmanifest, unthinkable and immutable.",
  },
  {
    id: "3.2.24",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 24,
    sanskrit: "अपि संराधने प्रत्यक्षानुमानाभ्याम् ॥ २४ ॥",
    translation: "And (Brahman is apprehended) in perfect meditation, according to Sruti and Smriti.",
    commentary: "Yet yogins realize Him in samrādhana, devotion, contemplation and deep absorption. Ka. II.i.1 says the rare discerner turns senses inward to see the indwelling Self, and Mu. III.i.8 sees the indivisible Self through purified meditation. Smṛti salutes that Effulgence realizable through yoga by the sense-controlled. Direct revelation and Smṛti thus attest experience beyond sense.",
  },
  {
    id: "3.2.25",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 25,
    sanskrit: "प्रकाशादिवच्चावैशेष्यं प्रकाशश्च कर्मण्यभ्यासात् ॥ २५ ॥",
    translation: "And as in the case of light etc. there is non-distinction, and there is the shining (of Brahman) in the work (i.e., meditation) on account of repeated practice.",
    commentary: "Meditator and meditated then seem two, but difference belongs to activity alone. As light, space or sun look diversified beside finger, pail or water yet keep natural unity, so the effulgent Self appears divided during worship through intellect and other adjuncts. Intrinsically there is non-difference, repeated in That thou art through Ch. VI.viii-xvi.",
  },
  {
    id: "3.2.26",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 26,
    sanskrit: "अतोऽनन्तेन तथा हि लिङ्गम् ॥ २६ ॥",
    translation: "Therefore (the individual soul becomes one) with the Infinite; for thus is the indication (in scripture).",
    commentary: "Hence the individual attains unity with the Infinite, since difference is ignorance-born while identity is natural. Knowledge destroys the veil and the eternal conscious Self stands revealed. The mark is scriptural: Mu. III.ii.9 says the knower of supreme Brahman becomes Brahman, and Br. IV.iv.6 says being Brahman he is absorbed in Brahman.",
  },
  {
    id: "3.2.27",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 27,
    sanskrit: "उभयव्यपदेशात्त्वहिकुण्डलवत् ॥ २७ ॥",
    translation: "But on account of twofold designation, (the relation is) like that between the serpent and its coils.",
    commentary: "Another view is rehearsed to clarify our own: texts mention both difference, as seer and seen in Mu. III.i.8, attainer and goal in Mu. III.ii.8, ruler and ruled in Br. III.vii.15, and non-difference in That thou art, I am Brahman in Br. I.iv.10, and the inner ruler passages. To honor both, relation is figured as snake to coil, hood or outstretched posture, one substance with real states.",
  },
  {
    id: "3.2.28",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 28,
    sanskrit: "प्रकाशाश्रयवद्वा तेजस्त्वात् ॥ २८ ॥",
    translation: "Or like that between light and its substratum, on account of their being luminous.",
    commentary: "Or relation is like light to its source: sunlight and sun are both effulgence, not wholly different, yet spoken of as distinct. So supreme and individual Self share luminous being while sustaining distinct reference. The analogy tries to preserve unity without erasing devotional duality.",
  },
  {
    id: "3.2.29",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 29,
    sanskrit: "पूर्ववद्वा ॥ २९ ॥",
    translation: "Or as (explained) before.",
    commentary: "Or it is as already shown in III.ii.25, and this alone is Śaṅkara's verdict. Snake-coil or light-source models make bondage real, and what is real cannot be removed by knowledge, rendering liberation texts useless. Scripture mentions difference only as conventionally recognized, aiming to establish non-difference. Illusory bondage alone makes knowledge liberating.",
  },
  {
    id: "3.2.30",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 30,
    sanskrit: "प्रतिषेधाच्च ॥ ३० ॥",
    translation: "And on account of the denial.",
    commentary: "Denial confirms it: Br. III.vii.23 says there is no other witness but Him, Br. II.iii.6 describes by not so, and Br. II.v.19 leaves Brahman without prior, posterior, interior or exterior. Manifestation denied apart from Brahman leaves Brahman alone as ultimate. Such exclusion seals non-duality.",
  },
  {
    id: "3.2.31",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 31,
    sanskrit: "परमतः सेतून्मानसंबन्धभेदव्यपदेशेभ्यः ॥ ३१ ॥",
    translation: "(There is something) superior to this (Brahman) on account of designations of bridge, measure, connection, and difference.",
    commentary: "A fresh doubt alleges something higher than this Brahman from four idioms. Setu in Ch. VIII.iv.1 calls Self an embankment, with crossing beyond in VIII.iv.2; measure in Ch. III.xviii.2 and IV.v gives four feet and sixteen parts; connection in Ch. VI.viii.1, Tai. II.iii.1 and Br. IV.iii.21 unites soul with Existence; difference in Ch. I.vi.6 and I.vii.5 assigns separate sun- and eye-beings with separate domains. Each seems to imply another beyond Brahman.",
  },
  {
    id: "3.2.32",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 32,
    sanskrit: "सामान्यात्तु ॥ ३२ ॥",
    translation: "But on account of resemblance (it is designated as a bridge).",
    commentary: "But embankment is praise by resemblance, not proof of a beyond. As a barrage holds waters and bounds, the Self holds the world as inner ruler and maintains norms. Inferring an outer would equally demand earth and timber parts, contradicting birthlessness, Ch. VI.ii.1 one without second, and know-one-know-all. Crossing means attaining, as one crosses grammar by mastering it.",
  },
  {
    id: "3.2.33",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 33,
    sanskrit: "बुद्ध्यर्थ उपादानवत् ॥ ३३ ॥",
    translation: "(The designation as measure is) for the sake of easy comprehension, like (wood) serving as a foot (etc.).",
    commentary: "Measure too serves easy grasp, like feet fancied for meditation. As speech and other organs form four feet of mind, and fire and other powers of space, so limited magnitudes are imagined on infinite Brahman for sharp, mediocre and dull intellects. Like a kārṣāpaṇa divided into quarters for varied dealings, division aids use without dividing the real.",
  },
  {
    id: "3.2.34",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 34,
    sanskrit: "स्थानविशेषात्प्रकाशादिवत् ॥ ३४ ॥",
    translation: "(The statements of connection and difference are) on account of special places, as in the case of light etc.",
    commentary: "Connection and difference are spoken from adjunct-place, as with light. Contact with intellect yields particularized knowledge; its cessation at adjunct-rest is metaphorically called union with the Self. Difference likewise reflects diverse adjuncts, not the Self itself. So one light unites when conditions lift and diversifies with them, as outer, inner and heart-space remain one space in Ch. III.xii.7-9.",
  },
  {
    id: "3.2.35",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 35,
    sanskrit: "उपपत्तेश्च ॥ ३५ ॥",
    translation: "And it is reasonable.",
    commentary: "Reason alone supports this reading. He attains his own Self in Ch. VI.viii.1 means self-identity, inalienable by nature, not meeting like man and town. Covering by adjuncts makes attainment language intelligible. Any other difference would contradict divine oneness taught throughout the Upaniṣads.",
  },
  {
    id: "3.2.36",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 36,
    sanskrit: "तथान्यप्रतिषेधात् ॥ ३६ ॥",
    translation: "Similarly on account of the denial of any other (entity).",
    commentary: "Denial of all else likewise proves nothing beyond Brahman. Ch. VII.xxv.1-2 places the Self below, above and everywhere; Br. II.iv.6 casts out the other-knower; Mu. II.ii.11 and Ch. VII.xxv.2 declare all Brahman and Self; Br. IV.iv.19 denies diversity; Sv. III.9 and Br. II.v.19 allow none prior, posterior, interior or exterior. Such contexts leave no room for a second.",
  },
  {
    id: "3.2.37",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 37,
    sanskrit: "अनेन सर्वगतत्वमायामशब्दादिभ्यः ॥ ३७ ॥",
    translation: "By this the omnipresence (of Brahman is established) according to scriptural texts declaring its extent.",
    commentary: "Hereby omnipresence too is secured through extension language. Ch. VIII.i.3 makes heart-space as extensive as outer space; Ch. III.xiv.3 calls Him greater than heaven; Śatapatha X.vi.3.2 greater than space; Gītā II.24 eternal, all-pervading and steady. Literal embankment or a surviving other would bound Him; refuted, they yield the boundless.",
  },
  {
    id: "3.2.38",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 38,
    sanskrit: "फलमत उपपत्तेः ॥ ३८ ॥",
    translation: "From Him (the Lord) is the fruit (of action), on account of reasoning.",
    commentary: "A new topic asks whence the threefold fruits of transmigratory action, desirable, undesirable and mixed, come, whether from rites themselves or God. From Him, the Lord, is the logical reply, for He presides over all and knows place and time fit for creation, sustenance and dissolution, apportioning to merit. Momentary acts perishing at once cannot later birth results from nothing.",
  },
  {
    id: "3.2.39",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 39,
    sanskrit: "श्रुतत्वाच्च ॥ ३९ ॥",
    translation: "And because it is so declared by scripture.",
    commentary: "Scripture agrees, not reason alone. Br. IV.iv.24 calls the great birthless Self bestower of food and giver of wealth, with like texts declaring divine ordainment. The Veda thus names God giver, confirming the inference. Both proofs converge on the Lord as fruit-giver.",
  },
  {
    id: "3.2.40",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 40,
    sanskrit: "धर्मं जैमिनिरत एव ॥ ४० ॥",
    translation: "Jaimini (thinks) for the same reasons that religious merit (is what brings about the fruits of actions).",
    commentary: "Jaimini objects that virtuous deed itself yields fruit, for the same Vedic and rational grounds read oppositely. One wishing heaven shall sacrifice enjoins an act with an end in view, implying sacrifice produces heaven lest injunction lack performers. Momentariness is cured by inferring unseen potency, subtle residue or seed of result. A uniform God, he adds, would breed partiality and make effort vain.",
  },
  {
    id: "3.2.41",
    adhyaya: 3,
    pada: 2,
    sutraNumber: 41,
    sanskrit: "पूर्वं तु बादरायणो हेतुव्यपदेशात् ॥ ४१ ॥",
    translation: "But Badarayana (thinks) the former (i.e., the Lord to be the bestower of fruits), on account of His being designated as the cause (of the actions themselves).",
    commentary: "Bādarāyaṇa restores the earlier One, God, as bestower whether through act or potency, rejecting fruit from inert karma alone. He is declared cause even of action: Kau. III.8 says He makes one do good to raise and bad to cast down, while Gītā VII.21-22 ordains faith and grants desires. Creating beings per individual merit, He varies results without partiality, reckoning each effort.",
  }
];
