// Spanda-kārikā glossary: original concise definitions for this app, standing in
// for the function of Singh's glossary (pp. 178–201). Fresh wording — not
// copied entries. Only terms load-bearing for reading the 53 kārikās.
export interface SpandaGlossaryEntry {
  id: string;
  term: string;
  iast: string;
  summary: string;
}

export const spandaKarikaGlossaryEn: SpandaGlossaryEntry[] = [
  { id: "pg-abhava", term: "Abhāva", iast: "abhāva", summary: "Non-being, absence: cannot become an object of meditation (1.12); the void remembered afterward is content, never the Experient." },
  { id: "pg-avastha-traya", term: "Avasthā-traya", iast: "avasthātraya", summary: "The three states — waking, dream, sleep: differing vessels, identical Experient (1.3); uninterrupted perception across them marks awakening (1.17–1.18)." },
  { id: "pg-atma-labha", term: "Ātma-lābha", iast: "ātmalābha", summary: "Self-gain: particular throbs abiding as the knower's own dividend, unobstructing (1.19)." },
  { id: "pg-adhisthatr", term: "Adhiṣṭhātṛ-bhāva", iast: "adhiṣṭhātṛbhāva", summary: "Presiding principle: beholding one's nature as governor, not governed (1.11); scaled from body to universe (3.7)." },
  { id: "pg-akrama", term: "Ākramaṇa", iast: "ākramaṇa", summary: "Seizing: mantras seize Spanda-strength (2.1); the yogi seizes power to manifest exactly so (3.5); even the weak prevail by seizing (3.6)." },
  { id: "pg-akrtrima", term: "Akṛtrima", iast: "akṛtrima", summary: "Unfabricated, natural: Spanda's freedom everywhere (1.7); the soul's knowing-doing nature (1.10). What is natural needs uncovering, not manufacture." },
  { id: "pg-amrta", term: "Amṛta", iast: "amṛta", summary: "Nectar, immortality: Spanda-nectar relished (Sandoha/Nirṇaya frame); supreme nectar-taste robbed by ideas (3.14); immortality attained as identity (2.7)." },
  { id: "pg-anubhavitr", term: "Anubhavitṛ (Experient)", iast: "anubhavitṛ", summary: "The invariable Subject threading waking, dream, sleep (1.3); eternal, never objectifiable (1.5); distinct from every predicate (1.4)." },
  { id: "pg-aprabuddha", term: "Aprabuddha", iast: "aprabuddha", summary: "Unawakened: mistakes effort's lapse for self-loss (1.15); for him throbs become station-coverers hurling into transmigration (1.20)." },
  { id: "pg-aradhaka", term: "Ārādhaka-citta", iast: "ārādhakacitta", summary: "Worshipper's mind: dissolves into Spanda together with mantras (2.2) — worship consummated in identity." },
  { id: "pg-avarta", term: "Āvaraṇa (svarūpa)", iast: "svarūpāvaraṇa", summary: "Covering of true form by ever-risen powers; no idea without word-penetration (3.15). Language is bondage's loom." },
  { id: "pg-bhairava", term: "Bhairava (implied)", iast: "bhairava", summary: "The awesome plenitude behind unmeṣa/nimeṣa play; the Śiva praised as Śaṅkara (1.1) — grace-maker calming all affliction-heat." },
  { id: "pg-bhogya", term: "Bhoktṛ / Bhogya", iast: "bhoktṛ, bhogya", summary: "Enjoyer and enjoyed: the Enjoyer poses as enjoyed everywhere (2.4); false enjoyership feeds word-powers (3.13); true enjoyership governs the fortress (3.19)." },
  { id: "pg-bindu", term: "Bindu, Nāda, Rūpa, Rasa", iast: "bindu, nāda, rūpa, rasa", summary: "Four supernormal signs after unmeṣa — brow-light, suṣumnā-sound, darkness-glow, tongue-taste — agitators if clung to (3.10)." },
  { id: "pg-cakresvara", term: "Cakreśvara", iast: "cakreśvara", summary: "Lord of the circle: rooted in the One, governing dissolution-emergence, sovereign over all śaktis (3.19). Section III's summit." },
  { id: "pg-dhata", term: "Dhātā", iast: "dhātā", summary: "Ordainer, Supporter: the inner Self fulfilling heart-held desires waking and dreaming (3.1–3.2)." },
  { id: "pg-dhyeya", term: "Dhyeya / Dhyāyin", iast: "dhyeya, dhyāyin", summary: "Meditated and meditator: success is the former's dawn in the latter's mind as identity (2.6)." },
  { id: "pg-dharma", term: "Dharma (akṛtrima)", iast: "dharma", summary: "Unfabricated nature: knowing-doing as the soul's own mark (1.10); mantras bearing Śiva's nature (2.2, śiva-dharmiṇ)." },
  { id: "pg-glani", term: "Glāni", iast: "glāni", summary: "Depression: plunderer of bodily vigor flowing from ignorance; starved when unmeṣa deletes its cause (3.8)." },
  { id: "pg-guru-bharati", term: "Guru-bhāratī", iast: "gurubhāratī", summary: "Guru's Word: ferry across fathomless doubt, manifold in sense and syllable — praised together with the Spanda-state (4.1)." },
  { id: "pg-hrdguha", term: "Hṛd-guhā", iast: "hṛdguhā", summary: "Heart-cave: repository where the knowledge-treasure is secured (4.2) — the reader's heart as the text's final home." },
  { id: "pg-jnatr-kartr", term: "Jñatva / Kartṛtva", iast: "jñatva, kartṛtva", summary: "Knowing and doing: the soul's unfabricated marks when mala dissolves (1.10), mirroring Śiva's cognition-activity." },
  { id: "pg-jnana-jneya", term: "Jñāna / Jñeya", iast: "jñāna, jñeya", summary: "Knowledge and its object: the form of supreme Power in the two states (1.18)." },
  { id: "pg-jivanmukti", term: "Jīvanmukti", iast: "jīvanmukti", summary: "Liberation while living: ever-yoked seeing of the world as play, no doubt (2.5)." },
  { id: "pg-iccha", term: "Icchā", iast: "icchā", summary: "Will, desire: Spanda is not its mere prompter (1.8); the desiring practitioner's longing ends in identity (2.6)." },
  { id: "pg-kala", term: "Kalā", iast: "kalā", summary: "Limited agency eclipsing glory, reducing the soul to word-powers' food (3.13)." },
  { id: "pg-karana-varga", term: "Karaṇa-varga", iast: "karaṇavarga", summary: "Host of senses: insentient instruments behaving as if sentient on borrowed current (1.6)." },
  { id: "pg-karya-kartr", term: "Kārya / Kartṛ", iast: "kārya, kartṛ", summary: "Effect and agent: effect-hood perishable, agency imperishable — Spanda's two faces (1.14)." },
  { id: "pg-kriya-sakti", term: "Kriyā-śakti", iast: "kriyāśakti", summary: "Active Power: Śiva's own, binding outward, perfecting when recognized (3.16); ideation-verbalization derives from it." },
  { id: "pg-kusrti", term: "Kusṛti / Saṃsṛti", iast: "kusṛti, saṃsṛti", summary: "Wretched transmigration: addressless for the enthroned (1.11), dread and hard to cross (1.20), dissolved by the declared cause (3.18)." },
  { id: "pg-karika", term: "Kārikā", iast: "kārikā", summary: "Metrical exposition: verses unfolding a doctrine — here, the Śiva-sūtras' import in fifty-one (+2) verses." },
  { id: "pg-krida", term: "Krīḍā", iast: "krīḍā", summary: "Play: the realized world's genre — beholding all as the Self's sport while seeing is jīvanmukti (2.5)." },
  { id: "pg-ksobha", term: "Kṣobha", iast: "kṣobha", summary: "Agitation: whose dissolution is the supreme state (1.9); the four signs agitate if clung to (3.10). Method is subtractive." },
  { id: "pg-madhya", term: "Madhya", iast: "madhya", summary: "Centre: the middle channel stationing dream-revelation (3.2); the point of mounting all upon the One." },
  { id: "pg-mala-traya", term: "Three malas", iast: "āṇava, māyīya, kārma", summary: "Incompleteness, difference, action-impression: why the empirical person cannot realize Spanda (1.9's background)." },
  { id: "pg-mantra-traya", term: "Mantra / Mantreśvara / Mantramaheśvara", iast: "mantra, mantreśvara, mantramaheśvara", summary: "Grades of mantra-deities, all borrowing Spanda-strength (2.1) and dissolving into it (2.2)." },
  { id: "pg-nimesa", term: "Nimeṣa", iast: "nimeṣa", summary: "Closing: with unmeṣa, the eyelid-act dissolving the world (1.1); read together with emergence as by mere will (Kallaṭa's gloss)." },
  { id: "pg-nirvana-diksa", term: "Nirvāṇa-dīkṣā", iast: "nirvāṇadīkṣā", summary: "Liberating initiation: recognition itself, needing no rite, granting Śiva-being (2.7)." },
  { id: "pg-pariksa", term: "Parīkṣā", iast: "parīkṣā", summary: "Examination: Spanda verified with zealous reverence in own experience (1.7) — empiricism of the sacred." },
  { id: "pg-pasu", term: "Paśu", iast: "paśu", summary: "Bound soul: glory-eclipsed, grazed by word-powers (3.13), nectar-robbed (3.14), fortress-besieged (3.17–3.18) — yet the binding Power is Śiva's own (3.16)." },
  { id: "pg-antahkarana", term: "Manas / Ahaṅkāra / Buddhi", iast: "manas, ahaṅkāra, buddhi", summary: "Mind, I-feeling, intellect: the inner instruments the fortress-city operates through (3.17)." },
  { id: "pg-pranaya", term: "Praṇaya", iast: "praṇaya", summary: "Loving insistence: never transgressed — devotion commands dream-display (3.2)." },
  { id: "pg-prana-apana", term: "Prāṇa / Apāna", iast: "prāṇa, apāna", summary: "Out- and in-breaths, lunar-solar currents: merged into suṣumnā and risen by the upper path (1.24–1.25)." },
  { id: "pg-para-amrta", term: "Parāmṛta-rasa", iast: "parāmṛtarasa", summary: "Supreme nectar-taste: robbed by empirical idea-rise, whose wage is sense-confined unfreedom (3.14)." },
  { id: "pg-pratyaya", term: "Pratyaya", iast: "pratyaya", summary: "Empirical idea: rise betokens immortality-bliss's disappearance; its emergence robs nectar (3.14); none without words (3.15)." },
  { id: "pg-prayatna", term: "Prayatna", iast: "prayatna", summary: "Effort: object-directed effort lapses in sleep (1.15); zealous examination finds the principle (1.7). Effort sleeps; existence doesn't." },
  { id: "pg-puryastaka", term: "Pury-aṣṭaka", iast: "puryaṣṭaka", summary: "City-of-eight: five sense-potentials + mind, ego, intellect — subtle-body fortress harboring residual cravings (3.17); governed at lordship (3.19)." },
  { id: "pg-sadhaka", term: "Sādhaka", iast: "sādhaka", summary: "Practitioner: the desiring one attaining identity with the meditated (2.6)." },
  { id: "pg-sahaja-vidya", term: "Sahaja-vidyā", iast: "sahajavidyā", summary: "Innate wisdom of unity in diversity (Section II): all-made jīva recognizing all-identity (2.3–2.4)." },
  { id: "pg-samapatti", term: "Samāpatti", iast: "samāpatti", summary: "Coalescence: meditator-meditated identity as meditation's dawn (2.6)." },
  { id: "pg-sankara", term: "Śaṅkara", iast: "śaṅkara", summary: "Grace-maker (śam + kara): calming all affliction-heat, enabling recognition of consciousness-expanse — one's own nature lauded (1.1)." },
  { id: "pg-sarvajna", term: "Sarvajñatā", iast: "sarvajñatā", summary: "Omniscience: seat unlapsing (1.16); mantras endowed with its power (2.1); body-presiding scaled to everywhere (3.7)." },
  { id: "pg-smayamana", term: "Smayamāna", iast: "smayamāna", summary: "As if smiling: the enthroned yogi's amazement-posture toward the cosmos-drama (1.11)." },
  { id: "pg-soma-surya", term: "Soma / Sūrya (currents)", iast: "soma, sūrya", summary: "Moon and sun: lunar-solar currents roused to fulfill desires (3.1); set into suṣumnā at ascent (1.24–1.25)." },
  { id: "pg-spanda", term: "Spanda", iast: "spanda", summary: "Throb: dynamic Absolute, Svātantrya-śakti non-distinct from the Lord, slight movement never absent (1.1; intro)." },
  { id: "pg-suprabuddha", term: "Suprabuddha / Para", iast: "suprabuddha, para", summary: "Fully vs partially awakened: uninterrupted vs junction-only perception across states (1.17–1.18)." },
  { id: "pg-susumna", term: "Suṣumnā / Ūrdhva-mārga", iast: "suṣumnā, ūrdhvamārga", summary: "Central channel and upper path: moon-sun merged and risen past the brahmāṇḍa (1.24); dream's projector-room (3.2); nāda's seat (3.10)." },
  { id: "pg-svatantrya", term: "Svātantrya-śakti", iast: "svātantryaśakti", summary: "Absolute freedom-power displaying as I and creation, compact bliss-flash, lettered I-consciousness (intro; 1.5's background)." },
  { id: "pg-tadatmya", term: "Tādātmya", iast: "tādātmya", summary: "Identity: with all through awareness-form (2.3); with the meditated (2.6)." },
  { id: "pg-tanmatra", term: "Tanmātra", iast: "tanmātra", summary: "Sense-potential: sphere confining the unfree (3.14); source-form of the fortress-city (3.17)." },
  { id: "pg-unmesa", term: "Unmeṣa", iast: "unmeṣa", summary: "Opening: world's emergence (1.1); cessation of prior idea birthing the next (Kallaṭa's gloss); junction-flash relating thoughts (3.9); depression's solvent (3.8)." },
  { id: "pg-upalabdhr", term: "Upalabdhi / Upalabdhṛ", iast: "upalabdhi, upalabdhṛ", summary: "Perception and Perceiver: uninterrupted perception marks awakening (1.17); the Perceiver never departs own nature (1.3)." },
  { id: "pg-vibhuti", term: "Vibhūti", iast: "vibhūti", summary: "Glory, power: the circle's glory sourced in Śiva (1.1); glory eclipsed by kalā (3.13); powers from Spanda-hold (Section III)." },
  { id: "pg-viveka", term: "Vivikta / Viveka", iast: "vivikta, viveka", summary: "Discrimination: constant alertness discriminating Spanda attains swiftly while awake (1.21)." },
  { id: "pg-anupaya", term: "Anupāya", iast: "anupāya", summary: "No-means: spontaneous Self-realization without special effort — the pathless path beyond the three upāyas." },
  { id: "pg-anugraha", term: "Anugraha", iast: "anugraha", summary: "Grace: Śiva's fifth act, the descent of power (śaktipāta) awakening recognition." },
  { id: "pg-anuttara", term: "Anuttara", iast: "anuttara", summary: "The Unsurpassable: the Absolute, and the vowel 'a' as its phonic body." },
  { id: "pg-anusandhana", term: "Anusandhāna", iast: "anusandhāna", summary: "Repeated intensive awareness joining each experience to its source; synthetic unity of apperception." },
  { id: "pg-anusandhata", term: "Anusandhātṛ", iast: "anusandhātṛ", summary: "One who joins succeeding experience into unity — the practitioner of anusandhāna." },
  { id: "pg-anusyuta", term: "Anusyūta", iast: "anusyūta", summary: "Strung together, uninterruptedly connected — states threaded on the Experient (cf. 1.4)." },
  { id: "pg-apana", term: "Apāna", iast: "apāna", summary: "In-breath, the downward vital current; merged with prāṇa into suṣumnā at ascent (1.24)." },
  { id: "pg-apavarga", term: "Apavarga", iast: "apavarga", summary: "Liberation, release — the cessation of transmigration (cf. 3.18–3.19)." },
  { id: "pg-abhinna", term: "Abhinna", iast: "abhinna", summary: "Non-different, identical — Spanda flowing undivided through divided states (1.3)." },
  { id: "pg-abhiyoga", term: "Abhiyoga", iast: "abhiyoga", summary: "Sustained application of awareness; by its touch comes certainty of the Experient (1.12)." },
  { id: "pg-amayiya", term: "Amāyīya", iast: "amāyīya", summary: "Beyond Māyā's scope — the pure course untouched by measuring power." },
  { id: "pg-amudha", term: "Amūḍha", iast: "amūḍha", summary: "Sentient, un-deluded — what instruments merely mimic (1.6); absence of insentience in the Real (1.12)." },
  { id: "pg-avadhana", term: "Avadhāna", iast: "avadhāna", summary: "Constant collected awareness; penetrative attention (cf. the Seed-attention of the Āṇava path)." },
  { id: "pg-avikalpa-jnana", term: "Avikalpa (Nirvikalpa) jñāna", iast: "avikalpajñāna", summary: "Direct realization of Reality without mental activity — thought-free knowing." },
  { id: "pg-avikalpa-pratyaksa", term: "Avikalpa pratyakṣa", iast: "avikalpapratyakṣa", summary: "Sense-awareness without perceptual judgment; unparticularized seeing before words divide it." },
  { id: "pg-aviveka", term: "Aviveka", iast: "aviveka", summary: "Non-discernment of the Real — taking coverings for the Self." },
  { id: "pg-avyakta", term: "Avyakta", iast: "avyakta", summary: "The unmanifest — background ground of all manifestation (Guna-theme: near-black indigo)." },
  { id: "pg-asuddha-vidya", term: "Aśuddha-vidyā", iast: "aśuddhavidyā", summary: "Impure knowledge: knowing a few particulars — empirical, fragmented cognition." },
  { id: "pg-asat", term: "Asat", iast: "asat", summary: "Non-being; the void mistaken for the Real and refuted (1.12–1.16)." },
  { id: "pg-asuddhi", term: "Aśuddhi", iast: "aśuddhi", summary: "Impurity, limitation — one's own stain making realization impossible until dissolved (1.9)." },
  { id: "pg-ahamkara", term: "Ahaṅkāra", iast: "ahaṅkāra", summary: "I-making principle, the empirical I-feeling; one wall of the eightfold fortress (3.17)." },
  { id: "pg-ahanta", term: "Ahantā", iast: "ahantā", summary: "I-consciousness — perfect and complete in the Absolute, contracted in the bound soul." },
  { id: "pg-anava-upaya", term: "Āṇava-upāya", iast: "āṇavopāya", summary: "Yoga of the limited soul working through body, breath and mind (cf. Śiva-sūtra Section III)." },
  { id: "pg-anava-samavesa", term: "Āṇava-samāveśa", iast: "āṇavasamāveśa", summary: "Absorption through the atomic means — immersion via supports like breath and body." },
  { id: "pg-atma-visranti", term: "Ātma-viśrānti", iast: "ātmaviśrānti", summary: "Resting in the Self — repose of awareness in its own ground." },
  { id: "pg-atma-vyapti", term: "Ātma-vyāpti", iast: "ātmavyāpti", summary: "Self-pervasion: covering one's own nature universally — exceeded only by Śiva-pervasion." },
  { id: "pg-ananda", term: "Ānanda", iast: "ānanda", summary: "Bliss: the Absolute's compact joy-flash; world-joy recognized as absorption-joy." },
  { id: "pg-ananda-upaya", term: "Ānanda-upāya", iast: "ānandopāya", summary: "Bliss as means — entering through intensified joy (cf. the dead-stop states of 1.22)." },
  { id: "pg-abhoga", term: "Ābhoga", iast: "ābhoga", summary: "Expansive enjoyment; infinite absorption digesting all experience into wisdom." },
  { id: "pg-icchopaya", term: "Icchā-upāya", iast: "icchopāya", summary: "Will as means — the Śāmbhava-adjacent path of pure intent (cf. virgin Umā-will)." },
  { id: "pg-iccha-sakti", term: "Icchā-śakti", iast: "icchāśakti", summary: "Power of Will, first of the triad with knowledge and action; creative urge of the Absolute." },
  { id: "pg-idanta", term: "Idantā", iast: "idantā", summary: "This-ness — the objective pole balanced with I-ness in pure wisdom." },
  { id: "pg-indu", term: "Indu", iast: "indu", summary: "Drop, moon-point: the lunar digit of nectar; bindu's cooling face." },
  { id: "pg-isvara-bhattaraka", term: "Īśvara-bhaṭṭāraka", iast: "īśvarabhaṭṭāraka", summary: "The Lord as revered ruler — Īśvara-tattva's cosmic oversight, This predominant." },
  { id: "pg-uccara", term: "Uccāra", iast: "uccāra", summary: "Rising utterance: the upward surge of breath-mantra from the heart centre." },
  { id: "pg-ucchalatta", term: "Ucchalattā", iast: "ucchalattā", summary: "Up-leaping: consciousness springing beyond its banks in sudden expansion." },
  { id: "pg-udaya", term: "Udaya", iast: "udaya", summary: "Emergence, dawn: world's arising (1.1), another thought's rise (3.9), the meditated's dawn (2.6)." },
  { id: "pg-udana", term: "Udāna", iast: "udāna", summary: "Up-breath, the ascending vital current carrying awareness toward the crown." },
  { id: "pg-udyama", term: "Udyama", iast: "udyama", summary: "Upsurge, upward flight of awareness — never strained exertion on the highest path." },
  { id: "pg-urdhva-marga", term: "Ūrdhva-mārga", iast: "ūrdhvamārga", summary: "Upper path: moon-sun risen past the brahmāṇḍa toward brahmarandhra (1.24)." },
  { id: "pg-kancuka", term: "Kañcuka", iast: "kañcuka", summary: "Covering: Māyā's five (kalā, vidyā, rāga, kāla, niyati) limiting the infinite." },
  { id: "pg-karana", term: "Karaṇa", iast: "karaṇa", summary: "Instrument: senses and inner faculties borrowing sentience (1.6); their creative power (3.37 in Śiva-sūtra line)." },
  { id: "pg-karanesvari", term: "Karaṇeśvarī", iast: "karaṇeśvarī", summary: "Goddess ruling an instrument-group — senses as a pantheon of powers." },
  { id: "pg-kartrtva", term: "Kartṛtva", iast: "kartṛtva", summary: "Agency: imperishable Subject-face of Spanda (1.14); unfabricated doing (1.10)." },
  { id: "pg-karmendriya", term: "Karmendriya", iast: "karmendriya", summary: "Organs of action — speech, hands, feet, excretion, generation; outgoing instruments." },
  { id: "pg-kala-sarira", term: "Kalā-śarīra", iast: "kalāśarīra", summary: "Body built of limited agency — embodiment woven from merit and demerit." },
  { id: "pg-karya", term: "Kārya", iast: "kārya", summary: "Effect: the perishable object-face — states and worlds that change and pass (1.14)." },
  { id: "pg-kala-adhva", term: "Kalā-adhvā", iast: "kalādhvā", summary: "Course of parts: manifestation measured as discrete principles and worlds." },
  { id: "pg-kala-sakti", term: "Kalā-śakti", iast: "kalāśakti", summary: "Power of limited doing — the finite echo of omnipotence." },
  { id: "pg-kundalini", term: "Kuṇḍalinī", iast: "kuṇḍalinī", summary: "Coiled power at the base; risen through the centre, she is Spanda's serpent-form." },
  { id: "pg-kumbhaka", term: "Kumbhaka", iast: "kumbhaka", summary: "Breath-retention: the pot-like holding merging prāṇa-apāna toward the centre." },
  { id: "pg-kula", term: "Kula", iast: "kula", summary: "Family, totality: the collective body of powers; the Kula path honoring immanence." },
  { id: "pg-kulamnaya", term: "Kulāmnāya", iast: "kulāmnāya", summary: "Kula transmission — scriptural lineage of the immanence-school." },
  { id: "pg-kulamarga", term: "Kulamārga", iast: "kulamārga", summary: "Kula path: realization through the totality of energies, not their rejection." },
  { id: "pg-krama", term: "Krama", iast: "krama", summary: "Sequence-path honoring the goddess-cycle (creation to indefinable); Kṣemarāja's lens on 1.1." },
  { id: "pg-krtrima", term: "Kṛtrima", iast: "kṛtrima", summary: "Fabricated, artificial — the void-construct (1.13); opposite of the unfabricated Real." },
  { id: "pg-kriya-yoga", term: "Kriyā-yoga", iast: "kriyāyoga", summary: "Yoga of action: discipline, study, surrender — the active preliminary path." },
  { id: "pg-ksetrajna", term: "Kṣetrajña", iast: "kṣetrajña", summary: "Knower of the field — the Self witnessing the body-field." },
  { id: "pg-khecari", term: "Khecarī", iast: "khecarī", summary: "Sky-farer: consciousness moving unobstructed in limitlessness; Śiva's own state." },
  { id: "pg-khecari-mudra", term: "Khecarī-mudrā", iast: "khecarīmudrā", summary: "Sky-seal: tongue-to-crown lock aiding upward presiding awareness." },
  { id: "pg-khyati", term: "Khyāti", iast: "khyāti", summary: "Manifestation, renown — powers appearing; also the Sāṅkhya theory of manifestation." },
  { id: "pg-gaganangana", term: "Gaganāṅganā", iast: "gaganāṅganā", summary: "Sky-maiden: etheric goddess-figure of unobstructed spaciousness." },
  { id: "pg-garbha", term: "Garbha", iast: "garbha", summary: "Womb: Māyā's interior gestating limited powers and inferior delights." },
  { id: "pg-gunatraya", term: "Guṇatraya", iast: "guṇatraya", summary: "Three strands — sattva, rajas, tamas; particular throbs rooted in the universal (1.19)." },
  { id: "pg-gocari", term: "Gocarī", iast: "gocarī", summary: "Field-ranger: goddess governing the outer sense-field." },
  { id: "pg-granthi", term: "Granthi", iast: "granthi", summary: "Knot: psychic tangles (notably navel) to be pierced in ascent." },
  { id: "pg-grahaka", term: "Grāhaka", iast: "grāhaka", summary: "Grasper, subject: the knower-pole, denied ultimacy apart from grasped (1.5)." },
  { id: "pg-grahya", term: "Grāhya", iast: "grāhya", summary: "Graspable, object: the known-pole, denied ultimacy apart from grasper (1.5)." },
  { id: "pg-ghora", term: "Ghorā śaktis", iast: "ghorā śaktayaḥ", summary: "Terrible powers: energies deluding the bound toward outwardness." },
  { id: "pg-ghoratari", term: "Ghoratarī śaktis", iast: "ghoratarī śaktayaḥ", summary: "More-terrible powers: deeper deluders binding through subtle craving." },
  { id: "pg-cakra", term: "Cakra", iast: "cakra", summary: "Circle, wheel: of powers (1.1, 3.19), letters, channels — joined rightly, mastered wholly." },
  { id: "pg-candra", term: "Candra", iast: "candra", summary: "Moon: lunar current (iḍā/prāṇa) set into the centre at ascent (1.24–1.25); dream's lamp (3.2)." },
  { id: "pg-camatkara", term: "Camatkāra", iast: "camatkāra", summary: "Aesthetic astonishment — stations of absorption arriving as wonder." },
  { id: "pg-caramakala", term: "Caramakalā", iast: "caramakalā", summary: "Final digit: the sixteenth lunar art, completeness beyond measure." },
  { id: "pg-cit", term: "Cit", iast: "cit", summary: "Pure consciousness — the motionless light-face of the Absolute." },
  { id: "pg-citta", term: "Citta", iast: "citta", summary: "Mind-stuff: bound instrument turned ascent-instrument; reflecting, it becomes mantra." },
  { id: "pg-citi", term: "Citi", iast: "citi", summary: "Consciousness-power: awareness as active massing toward form." },
  { id: "pg-cidananda", term: "Cidānanda", iast: "cidānanda", summary: "Consciousness-bliss: the Absolute's indivisible light-joy nature." },
  { id: "pg-cetana", term: "Cetanā", iast: "cetanā", summary: "Sentience, animation — lent to instruments, owned only by the Self." },
  { id: "pg-cetya", term: "Cetya", iast: "cetya", summary: "The sentient-content: whatever is to be illumined by awareness." },
  { id: "pg-caitanya", term: "Caitanya", iast: "caitanya", summary: "Consciousness as knowing-doing freedom — the Self's own definition." },
  { id: "pg-cheda", term: "Cheda", iast: "cheda", summary: "Cutting: cessation of in-out breath by vowelless sound; severing the knot." },
  { id: "pg-jagadananda", term: "Jagadānanda", iast: "jagadānanda", summary: "World-bliss: the Self's joy appearing as universe — divinity made visible." },
  { id: "pg-jagrat-avastha", term: "Jāgrat-avasthā", iast: "jāgradavasthā", summary: "Waking state: outer sense-knowledge shared across perceivers; first field of retention." },
  { id: "pg-jagrat-jnana", term: "Jāgrat-jñāna", iast: "jāgratjñāna", summary: "Waking knowledge: objective cognition common to all in daylight mind." },
  { id: "pg-jagrat", term: "Jāgrat", iast: "jāgrat", summary: "Waking: the state of outward senses; esoterically, undeluded awakening at all levels." },
  { id: "pg-jiva", term: "Jīva", iast: "jīva", summary: "Individual soul: consciousness conditioned by experience-traces, all-made through knowing (2.3)." },
  { id: "pg-jivanmukta", term: "Jīvanmukta", iast: "jīvanmukta", summary: "Liberated while living: seeing the world as play, ever yoked (2.5)." },
  { id: "pg-jnana", term: "Jñāna", iast: "jñāna", summary: "Knowing: bondage when divided, food when offered, ended as compulsion's root." },
  { id: "pg-jnana-yoga", term: "Jñāna-yoga", iast: "jñānayoga", summary: "Yoga of knowledge: ascent-displayed aspects for gnostic yogis (cf. Nirṇaya on 1.1)." },
  { id: "pg-tattva", term: "Tattva", iast: "tattva", summary: "Principle, that-ness: thirty-six rungs from Śiva to earth." },
  { id: "pg-tattva-traya", term: "Tattva-traya", iast: "tattvatraya", summary: "Triad of principles — Śiva, Śakti, Nara; or pure, pure-impure, impure courses." },
  { id: "pg-tatpurusa", term: "Tatpuruṣa", iast: "tatpuruṣa", summary: "That-person: east face of the five-faced Lord; veiling-cum-revealing aspect." },
  { id: "pg-tamas", term: "Tamas", iast: "tamas", summary: "Darkness-strand: inertia and delusion; one particular throb among guṇas (1.19)." },
  { id: "pg-tarka", term: "Tarka-śāstra", iast: "tarkaśāstra", summary: "Logic-discipline: valid reasoning establishing Spanda (1.2–1.5; 1.12–1.16)." },
  { id: "pg-turya", term: "Turya", iast: "turya", summary: "The Fourth: witnessing continuity through waking, dream, sleep." },
  { id: "pg-turyatita", term: "Turyātīta", iast: "turyātīta", summary: "Beyond the Fourth: the Absolute past even witnessing — pure plenitude." },
  { id: "pg-trika", term: "Trika", iast: "trika", summary: "Triad-discipline: Śiva-Śakti-Nara, or para-parāpara-apara; Kashmir non-dual Śaivism." },
  { id: "pg-darsana", term: "Darśana", iast: "darśana", summary: "Viewpoint-system: philosophy as seeing, each school a way of looking." },
  { id: "pg-dik", term: "Dik", iast: "dik", summary: "Direction, quarter: spatial orientation of powers and deities." },
  { id: "pg-dikcari", term: "Dikcarī", iast: "dikcarī", summary: "Quarter-ranger: goddess governing directional expanse." },
  { id: "pg-divya-mudra", term: "Divya-mudrā", iast: "divyamudrā", summary: "Divine seal: gesture attesting identity with the deity invoked." },
  { id: "pg-diksa", term: "Dīkṣā", iast: "dīkṣā", summary: "Initiation: recognition itself when liberating (2.7); rite when preparatory." },
  { id: "pg-desa", term: "Deśa", iast: "deśa", summary: "Place, space: one measure of manifestation alongside time and form." },
  { id: "pg-desa-adhva", term: "Deśa-adhvā", iast: "deśādhvā", summary: "Course of space: manifestation mapped as worlds and regions." },
  { id: "pg-dharana", term: "Dhāraṇā", iast: "dhāraṇā", summary: "Holding: fixed attention binding awareness to one point." },
  { id: "pg-dhruva", term: "Dhruva", iast: "dhruva", summary: "The Fixed: pole-star stillness; unmoving axis of the turning powers." },
  { id: "pg-dhyana-yoga", term: "Dhyāna-yoga", iast: "dhyānayoga", summary: "Yoga of meditation: sustained contemplative absorption." },
  { id: "pg-dhvani-yoga", term: "Dhvani-yoga", iast: "dhvaniyoga", summary: "Yoga of resonance: ascent through inner sound toward silence." },
  { id: "pg-nada", term: "Nāda", iast: "nāda", summary: "Resonance: first stir of Śiva-Śakti toward form; unstruck suṣumnā-sound (3.10)." },
  { id: "pg-nigraha", term: "Nigraha-kṛtya", iast: "nigrahakṛtya", summary: "Act of concealing: the Lord's veiling play producing bound souls." },
  { id: "pg-nimilana", term: "Nimīlana-samādhi", iast: "nimīlanasamādhi", summary: "Closed-eye absorption: introvertive meditation stressing Section I." },
  { id: "pg-niyati", term: "Niyati", iast: "niyati", summary: "Restriction: Māyā's covering fixing place, time and destiny." },
  { id: "pg-nirvana", term: "Nirvāṇa", iast: "nirvāṇa", summary: "Extinction of bondage: liberation as recognition, granted as initiation (2.7)." },
  { id: "pg-nirvikalpa", term: "Nirvikalpa", iast: "nirvikalpa", summary: "Thought-free: awareness without constructs; immersion's diving body (cf. 3.12's guard)." },
  { id: "pg-nirvyutthana", term: "Nirvyutthāna-samādhi", iast: "nirvyutthānasamādhi", summary: "Non-emergent absorption: unbroken contemplation without return to distraction." },
  { id: "pg-pancakrtya", term: "Pañcakṛtya", iast: "pañcakṛtya", summary: "Five acts — creation, maintenance, dissolution, concealment, grace — as Self-rhythm." },
  { id: "pg-pancamantra", term: "Pañcamantrā", iast: "pañcamantrā", summary: "Five mantras: Īśāna to Sadyojāta faces as sonic bodies of the Lord." },
  { id: "pg-pancasakti", term: "Pañcaśakti", iast: "pañcaśakti", summary: "Five powers: awareness, bliss, will, knowledge, action — the Absolute's fingers." },
  { id: "pg-pati", term: "Pati", iast: "pati", summary: "Lord, Master: Śiva as owner of bound creatures; equality with Him is the goal (3.19's fruit)." },
  { id: "pg-para", term: "Para", iast: "para", summary: "Highest: undifferentiated level; also the partially awakened 'other' (1.17)." },
  { id: "pg-para-pramatr", term: "Para-pramātṛ", iast: "parapramātṛ", summary: "Supreme knower: the Absolute as ultimate Subject of all knowing." },
  { id: "pg-parama-siva", term: "Parama-Śiva", iast: "paramaśiva", summary: "Supreme Śiva: the Absolute holding light and freedom indistinguishably." },
  { id: "pg-parapara", term: "Parāpara", iast: "parāpara", summary: "Middle level: identity-in-difference; the goddess bridging highest and lower." },
  { id: "pg-paramartha", term: "Paramārtha", iast: "paramārtha", summary: "Highest truth: a thing's essence, knowing which commands appearance (3.5)." },
  { id: "pg-paramarsa", term: "Parāmarśa", iast: "parāmarśa", summary: "Reflective grasp: I-consciousness seizing itself — vimarśa in act." },
  { id: "pg-paravak", term: "Parāvāk", iast: "parāvāk", summary: "Supreme Word: unspoken speech-power generating worlds; Mātṛkā known, not binding." },
  { id: "pg-parasakti", term: "Paraśakti", iast: "paraśakti", summary: "Supreme Power: the Absolute's freedom-face displaying as I and creation." },
  { id: "pg-parinama", term: "Pariṇāma", iast: "pariṇāma", summary: "Transformation: real modification — world as Spanda's own becoming, not illusion." },
  { id: "pg-pasu-matarah", term: "Paśu-mātaraḥ", iast: "paśumātaraḥ", summary: "Mothers of the bound: letter-goddesses delivering fragmented experience (cf. 3.13's grazers)." },
  { id: "pg-pasyanti", term: "Paśyantī", iast: "paśyantī", summary: "Seeing Word: second speech-level, vision pregnant with undifferentiated meaning." },
  { id: "pg-pasa", term: "Pāśa", iast: "pāśa", summary: "Noose, bond: the three malas as fetters; cut by recognition." },
  { id: "pg-pidhana", term: "Pidhāna-kṛtya", iast: "pidhānakṛtya", summary: "Act of covering: veiling the true form by ever-risen powers (3.15)." },
  { id: "pg-purusa-tattva", term: "Puruṣa-tattva", iast: "puruṣatattva", summary: "Soul-principle: spirit under Māyā's coverings, the bound enjoyer." },
  { id: "pg-purnatva", term: "Pūrṇatva", iast: "pūrṇatva", summary: "Fullness: completeness lacking nothing — the Absolute's and the knower's state." },
  { id: "pg-purnahanta", term: "Pūrṇāhantā", iast: "pūrṇāhantā", summary: "Perfect I-ness: complete self-consciousness flashing through all letters." },
  { id: "pg-prakasa", term: "Prakāśa", iast: "prakāśa", summary: "Light: self-luminous awareness — the sūtras' emphasis, inseparable from vimarśa." },
  { id: "pg-prakrti", term: "Prakṛti (Pradhāna)", iast: "prakṛti", summary: "Primordial matrix: equilibrium-source of worlds under spirit's gaze." },
  { id: "pg-prama", term: "Pramā", iast: "pramā", summary: "Valid cognition: knowledge's fruitful result guiding successful action." },
  { id: "pg-pramana", term: "Pramāṇa", iast: "pramāṇa", summary: "Means of knowing: perception, inference, authority — instruments of valid cognition." },
  { id: "pg-pramatr", term: "Pramātṛ", iast: "pramātṛ", summary: "Knower: subject-pole of cognition, from bound soul to supreme Knower." },
  { id: "pg-prameya", term: "Prameya", iast: "prameya", summary: "Knowable: object-pole; the measured world awaiting true measure." },
  { id: "pg-pratha", term: "Prathā", iast: "prathā", summary: "Expansion, mode of appearance: how the unmanifest shines forth." },
  { id: "pg-pratibha", term: "Pratibhā", iast: "pratibhā", summary: "Ever-creative intuition: flashing insight, goddess of poetic-philosophic genius." },
  { id: "pg-pratimilana", term: "Pratimīlana", iast: "pratimīlana", summary: "Re-closing: recognition alternating inward-outward until alternation dissolves." },
  { id: "pg-pratyabhijna", term: "Pratyabhijñā", iast: "pratyabhijñā", summary: "Recognition: 'I am Śiva' as lived certainty — the system's name for liberation." },
  { id: "pg-pratyahara", term: "Pratyāhāra", iast: "pratyāhāra", summary: "Withdrawal: senses gathered from objects into the centre (cf. 1.6's union)." },
  { id: "pg-pratyavamarsa", term: "Pratyavamarśa", iast: "pratyavamarśa", summary: "Counter-grasp: re-cognition rejoining each object to its Subject (cf. 3.12)." },
  { id: "pg-pralaya", term: "Pralaya", iast: "pralaya", summary: "Dissolution: agitation's settling (1.9), world's submergence (1.1), transmigration's end (3.18)." },
  { id: "pg-pralayakala", term: "Pralayākala", iast: "pralayākala", summary: "Dissolution-state soul: resting bodiless between worlds, awaiting re-emergence." },
  { id: "pg-prasara", term: "Prasāra", iast: "prasāra", summary: "Outflow, spreading: manifestation streaming from the centre." },
  { id: "pg-prana-bija", term: "Prāṇa-bīja", iast: "prāṇabīja", summary: "Life-seed: vital mantra-germ concentrating universal energy." },
  { id: "pg-pranayama", term: "Prāṇāyāma", iast: "prāṇāyāma", summary: "Breath-regulation: channeling vital currents toward central merging." },
  { id: "pg-prasada", term: "Prasāda", iast: "prasāda", summary: "Clarity, gracious favor: serene bestowal crowning practice." },
  { id: "pg-prthivi", term: "Pṛthivī", iast: "pṛthivī", summary: "Earth: grossest principle, noticed from earth to Śiva in the Lord's mirror (frame verses)." },
  { id: "pg-paurusa-ajnana", term: "Pauruṣa-ajñāna", iast: "pauruṣājñāna", summary: "Soul-ignorance: primal self-forgetting, root of the three stains." },
  { id: "pg-paurusa-jnana", term: "Pauruṣa-jñāna", iast: "pauruṣajñāna", summary: "Soul-knowledge: recognition of one's own plenitude dissolving stains." },
  { id: "pg-bandha", term: "Bandha", iast: "bandha", summary: "Bondage: mis-knowing, not misfortune — removable by counter-recognition." },
  { id: "pg-bala", term: "Bala", iast: "bala", summary: "Strength: Self-power seized for office (2.1) and manifestation (3.5–3.6)." },
  { id: "pg-bahirmukhata", term: "Bahirmukhatā", iast: "bahirmukhatā", summary: "Outward-facedness: attention streaming to externals; reversed in introversion." },
  { id: "pg-brahmanirvana", term: "Brahmanirvāṇa", iast: "brahmanirvāṇa", summary: "Extinction in Brahman: Gītā's term for liberation's peace, recognized here as Spanda-rest." },
  { id: "pg-brahmarandhra", term: "Brahmarandhra", iast: "brahmarandhra", summary: "Brahma-aperture: crown gate beyond which currents dissolve into consciousness-ether (1.24)." },
  { id: "pg-brahmavada", term: "Brahmavāda", iast: "brahmavāda", summary: "Brahman-doctrine: Vedāntic absolutism, dialogue-partner and foil." },
  { id: "pg-bija", term: "Bīja", iast: "bīja", summary: "Seed: mantra-germ; supreme Śakti containing manifestation undivided." },
  { id: "pg-buddha", term: "Buddha", iast: "buddha", summary: "Awakened one (cf. suprabuddha, 1.17; prabuddha, 1.25, 3.12)." },
  { id: "pg-buddhi", term: "Buddhi", iast: "buddhi", summary: "Determinative faculty: higher intelligence become mirror (cf. fortress wall, 3.17)." },
  { id: "pg-buddhindriya", term: "Buddhīndriya", iast: "buddhīndriya", summary: "Sense of knowing: ear, skin, eye, tongue, nose — inbound instruments." },
  { id: "pg-baindavi-kala", term: "Baindavī-kalā", iast: "baindavīkalā", summary: "Drop-digit: lunar art of bindu-consciousness in ascent symbolism." },
  { id: "pg-bauddha-ajnana", term: "Bauddha-ajñāna", iast: "bauddhājñāna", summary: "Intellect-ignorance: mind-level nescience distinct from soul-ignorance." },
  { id: "pg-bauddha-jnana", term: "Bauddha-jñāna", iast: "bauddhajñāna", summary: "Intellect-knowledge: mental clarity still below Self-recognition." },
  { id: "pg-bhava", term: "Bhāva", iast: "bhāva", summary: "Being, state: own Being attained (1.21); inward Being never lapsing (1.16)." },
  { id: "pg-bhavana", term: "Bhāvanā", iast: "bhāvanā", summary: "Creative contemplation: dissolving tattvas imaginatively; ripened conviction." },
  { id: "pg-bhuvana", term: "Bhuvana", iast: "bhuvana", summary: "World: inhabited plane among the courses of manifestation." },
  { id: "pg-bhuta", term: "Bhūta", iast: "bhūta", summary: "Element, being: gross principles; worn finally as a mere cloak." },
  { id: "pg-bhucari", term: "Bhūcarī", iast: "bhūcarī", summary: "Earth-ranger: goddess governing the waking objective field." },
  { id: "pg-bhumika", term: "Bhūmikā", iast: "bhūmikā", summary: "Stage, role: stations of yoga arriving as wonder; roles the Self performs." },
  { id: "pg-bhairava-apara", term: "Bhairava (apara)", iast: "bhairava", summary: "Lower Bhairava: the awesome in mantra-form, terrible-beautiful face of power." },
  { id: "pg-bhairava-para", term: "Bhairava (para)", iast: "bhairava", summary: "Supreme Bhairava: plenitude itself — the 1.1 flash, never a later goal." },
  { id: "pg-bhairava-mudra", term: "Bhairava/Bhairavī-mudrā", iast: "bhairavamudrā", summary: "Bhairava-seal: open-eyed absorption holding inner-outer together." },
  { id: "pg-bhairava-samapatti", term: "Bhairava-samāpatti", iast: "bhairavasamāpatti", summary: "Coalescence with Bhairava: identity-attainment with the awesome plenitude." },
  { id: "pg-bhoga", term: "Bhoga", iast: "bhoga", summary: "Enjoyment: the vīra's single savour; total experience digested into wisdom." },
  { id: "pg-madhya-dhama", term: "Madhya-dhāma", iast: "madhyadhāma", summary: "Central abode: the middle station between extremes where revelation occurs." },
  { id: "pg-madhyama", term: "Madhyamā", iast: "madhyamā", summary: "Middle Word: third speech-level, mental word mediating vision and utterance." },
  { id: "pg-madhya-sakti", term: "Madhya-śakti", iast: "madhyaśakti", summary: "Middle power: energy of the centre balancing emission and absorption." },
  { id: "pg-manas", term: "Manas", iast: "manas", summary: "Mind: fluctuating inner sense; one wall of the eightfold fortress (3.17)." },
  { id: "pg-mantra", term: "Mantra", iast: "mantra", summary: "Thought protecting: reflection on the Supreme saving from transmigration; potent only by Spanda (2.1)." },
  { id: "pg-mantra-virya", term: "Mantra-vīrya", iast: "mantravīrya", summary: "Mantra-potency: virility borrowed from Spanda's lake; owned, not merely recited." },
  { id: "pg-manthana-bhairava", term: "Manthana-Bhairava", iast: "manthanabhairava", summary: "Churning Bhairava: the awesome stirring the ocean of consciousness into form." },
  { id: "pg-marici", term: "Marīci", iast: "marīci", summary: "Ray: goddess-rays of the circle; particular gleams of universal light." },
  { id: "pg-mahartha", term: "Mahārtha", iast: "mahārtha", summary: "Great purport: Krama's fivefold-function ideal — Kṣemarāja's lens on 1.1." },
  { id: "pg-mahamantra", term: "Mahāmantra", iast: "mahāmantra", summary: "Great mantra: supreme formula embodying the whole (cf. lettered I-consciousness)." },
  { id: "pg-mahamaya-apara", term: "Mahāmāyā (apara)", iast: "mahāmāyā", summary: "Lower great-illusion: cosmic veiling below the pure course." },
  { id: "pg-mahamaya-para", term: "Mahāmāyā (para)", iast: "mahāmāyā", summary: "Higher great-illusion: the Lord's own screening power, transparent to Him." },
  { id: "pg-mahanaya", term: "Mahānaya", iast: "mahānaya", summary: "Great method: Krama discipline of sequential goddess-worship toward the indefinable." },
  { id: "pg-mahahrada", term: "Mahāhrada", iast: "mahāhrada", summary: "Great lake: highest purest I-consciousness, reservoir of mantra-virility." },
  { id: "pg-matrka", term: "Mātṛkā", iast: "mātṛkā", summary: "Mother of letters: alphabet-power behind words and limited knowing." },
  { id: "pg-matrka-cakra", term: "Mātṛkā-cakra", iast: "mātṛkācakra", summary: "Circle of Mothers: letter-powers as pantheon structuring all experience." },
  { id: "pg-madhyamika", term: "Mādhyamika", iast: "mādhyamika", summary: "Middle-way Buddhist: Nāgārjuna's school; polemical neighbor on void and levels." },
  { id: "pg-maya-tattva", term: "Māyā-tattva", iast: "māyātattva", summary: "Illusion-principle: veil over pure consciousness, material cause of manifestation." },
  { id: "pg-maya", term: "Māyā", iast: "māyā", summary: "Measurer: finitising power making the immeasurable seem finite; womb of difference." },
  { id: "pg-maya-sakti", term: "Māyā-śakti", iast: "māyāśakti", summary: "Śiva's finitising power displaying difference in identity, birthing māyā-tattva." },
  { id: "pg-maya-pramata", term: "Māyā-pramātṛ", iast: "māyāpramātṛ", summary: "Māyā-bound knower: the empirical subject under coverings." },
  { id: "pg-malini", term: "Mālinī", iast: "mālinī", summary: "Garlanded goddess: alphabet-deity whose letter-order empowers mantra (cf. Mālinīvijaya)." },
  { id: "pg-mahesvari", term: "Māheśvarī", iast: "māheśvarī", summary: "Goddess of the Lord: head of the letter-Mothers ruling sound-classes." },
  { id: "pg-mahesvaryadayah", term: "Māheśvaryādayaḥ", iast: "māheśvaryādayaḥ", summary: "Māheśvarī and sisters: presiding mothers of letter-groups, binding or freeing." },
  { id: "pg-mukti", term: "Mukti", iast: "mukti", summary: "Release: freedom as recognition, not escape — enjoyed while living." },
  { id: "pg-mudra", term: "Mudrā", iast: "mudrā", summary: "Seal: gesture-posture attesting and inducing identity with invoked power." },
  { id: "pg-mudra-krama", term: "Mudrā-krama", iast: "mudrākrama", summary: "Seal-sequence: alternating inward-outward recognition until alternation dissolves." },
  { id: "pg-mudra-virya", term: "Mudrā-vīrya", iast: "mudrāvīrya", summary: "Seal-potency: efficacy of sealed awareness in fixing recognition." },
  { id: "pg-meya", term: "Meya (prameya)", iast: "meya", summary: "The measurable: object awaiting true measure by the knower." },
  { id: "pg-moha", term: "Moha", iast: "moha", summary: "Delusion: the veil powers grow from; conquered through total absorption." },
  { id: "pg-moksa", term: "Mokṣa", iast: "mokṣa", summary: "Liberation: final release; in Trika, autonomy (svātantrya) consciously wielded." },
  { id: "pg-yoga", term: "Yoga", iast: "yoga", summary: "Yoking: discipline joining the bound to the free; stages arriving as wonder." },
  { id: "pg-yoginyah", term: "Yoginyaḥ", iast: "yoginyaḥ", summary: "Yoginīs: power-goddesses of the circle; senses as their field-forms." },
  { id: "pg-yoni", term: "Yoni", iast: "yoni", summary: "Womb-source: Māyā as differentiation's origin; letter-source of mantras." },
  { id: "pg-yonivarga", term: "Yonivarga", iast: "yonivarga", summary: "Source-group: Māyā and her brood of principles clothing the universal." },
  { id: "pg-rajas", term: "Rajas", iast: "rajas", summary: "Activity-strand: restlessness and passion; Guna-theme: terracotta drive." },
  { id: "pg-ravi", term: "Ravi", iast: "ravi", summary: "Sun: solar current (piṅgalā/apāna) set into the centre at ascent." },
  { id: "pg-raga", term: "Rāga", iast: "rāga", summary: "Attachment: Māyā's covering of desire; also the 'reddened' coloring of experience." },
  { id: "pg-rudra-kalagni", term: "Rudra (Kālāgni)", iast: "rudra", summary: "Rudra of world-fire: awesome dissolver presiding over lower dissolution planes." },
  { id: "pg-laya", term: "Laya", iast: "laya", summary: "Dissolution: agitation settled, world submerged, fortress governed (3.19)." },
  { id: "pg-loka", term: "Loka", iast: "loka", summary: "World: lived plane; all the world blessed by the secured treasure (4.2)." },
  { id: "pg-varga", term: "Varga", iast: "varga", summary: "Group, class: letter-families and power-hosts under presiding mothers." },
  { id: "pg-varna", term: "Varṇa", iast: "varṇa", summary: "Letter, color: phonic units whose powers the Mothers rule." },
  { id: "pg-vacaka", term: "Vācaka", iast: "vācaka", summary: "Expresser: word as vehicle carrying meaning toward the denoted." },
  { id: "pg-vacya", term: "Vācya", iast: "vācya", summary: "Expressed: meaning denoted; reflection on word-meaning stays Śiva (2.4)." },
  { id: "pg-vamesvari", term: "Vāmā / Vāmeśvarī", iast: "vāmā", summary: "Emitting goddess: power of manifestation; leftward current of creation." },
  { id: "pg-vasana", term: "Vāsanā", iast: "vāsanā", summary: "Residual trace: submerged craving re-awakened lifetimes over (3.17–3.18)." },
  { id: "pg-vaha", term: "Vāha", iast: "vāha", summary: "Flow, vehicle: currents bearing awareness outward or inward." },
  { id: "pg-vikalpa", term: "Vikalpa", iast: "vikalpa", summary: "Thought-construct: binds impure, liberates pure and Śiva-directed." },
  { id: "pg-vikalpa-ksaya", term: "Vikalpa-kṣaya", iast: "vikalpakṣaya", summary: "Dissolution of constructs: their subsiding reveals the throb." },
  { id: "pg-vikalpanam", term: "Vikalpanam", iast: "vikalpanam", summary: "Conceptualizing: the mind's dividing activity; watched, it self-liberates." },
  { id: "pg-vikalpa-suddha", term: "Vikalpa (śuddha)", iast: "śuddhavikalpa", summary: "Pure construct: 'I am Śiva' destroying impure thoughts, then dissolving." },
  { id: "pg-vikasa", term: "Vikāsa", iast: "vikāsa", summary: "Blossoming: expansion of awareness; mind's delight turned toward the Real." },
  { id: "pg-vigraha", term: "Vigraha", iast: "vigraha", summary: "Form, embodiment: the Lord's assumed figure; analysis resolving compounds." },
  { id: "pg-vijnanakala", term: "Vijñānakala", iast: "vijñānakala", summary: "Bodiless knower: pure-jñāna soul devoid of agency, between dissolution and return." },
  { id: "pg-vidya", term: "Vidyā", iast: "vidyā", summary: "Wisdom: pure when balanced, inferior when partial, innate when sahaja." },
  { id: "pg-vimarsa", term: "Vimarśa", iast: "vimarśa", summary: "Reflective freedom: the Self-knowing pulse inseparable from light; the kārikās' emphasis." },
  { id: "pg-visva", term: "Viśva", iast: "viśva", summary: "Universe: all, experienced as one's own power-expansion at lordship." },
  { id: "pg-visarga", term: "Visarga", iast: "visarga", summary: "Emission: creation as out-breathing; the objective pole (idam) displayed." },
  { id: "pg-visargabhumi", term: "Visargabhūmi", iast: "visargabhūmi", summary: "Emission-ground: the plane where creation pours forth." },
  { id: "pg-vedaka", term: "Vedaka", iast: "vedaka", summary: "Knower-as-subject: the experiencing pole distinct from the experienced." },
  { id: "pg-vedya", term: "Vedya", iast: "vedya", summary: "Knowable: object-as-experienced, from vivid dream-forms to earth." },
  { id: "pg-vaikhari", term: "Vaikharī", iast: "vaikharī", summary: "Uttered Word: fourth speech-level, audible language of the bound." },
  { id: "pg-vyapakatva", term: "Vyāpakatva", iast: "vyāpakatva", summary: "All-pervasiveness: the Lord shining in two states and beyond (1.18)." },
  { id: "pg-vyamohitata", term: "Vyamohitatā", iast: "vyamohitatā", summary: "Deludedness: the bound condition under terrible powers' sway." },
  { id: "pg-vyutthana", term: "Vyutthāna", iast: "vyutthāna", summary: "Emergence: rising from absorption into world-activity; its samādhi guards continuity." },
  { id: "pg-sakti", term: "Śakti", iast: "śakti", summary: "Power: Śiva's freedom-face; the circle joined, the Seed attended, the Seat stationed." },
  { id: "pg-sakti-cakra", term: "Śakti-cakra", iast: "śakticakra", summary: "Circle of powers: senses and goddesses; joined, the world reabsorbs (frame); ruled at lordship (3.19)." },
  { id: "pg-sakti-tattva", term: "Śakti-tattva", iast: "śaktitattva", summary: "Power-principle: second tattva, the Absolute's first stirring toward form." },
  { id: "pg-sakti-pancaka", term: "Śakti-pañcaka", iast: "śaktipañcaka", summary: "Five powers: awareness, bliss, will, knowledge, action wielded by the Lord." },
  { id: "pg-sakti-pata", term: "Śaktipāta", iast: "śaktipāta", summary: "Descent of power: grace striking, awakening pure thought through the guru." },
  { id: "pg-saktiman", term: "Śaktimān", iast: "śaktimān", summary: "Power-holder: Maheśvara-Śiva owning all powers non-distinctly." },
  { id: "pg-sabda", term: "Śabda", iast: "śabda", summary: "Sound, word: mass birthing power-hosts (3.13); penetration without which no idea (3.15)." },
  { id: "pg-sabda-rasi", term: "Śabda-rāśi", iast: "śabdarāśi", summary: "Mass of words: the letter-totality whose powers graze the bound soul (3.13)." },
  { id: "pg-sakta-upaya", term: "Śākta-upāya", iast: "śāktopāya", summary: "Power's means: purified thought until mind is mantra; guru-given middle path." },
  { id: "pg-sambhava-upaya", term: "Śāmbhava-upāya", iast: "śāmbhavopāya", summary: "Śiva's means: choiceless awareness flashing as Bhairava; no object, no technique." },
  { id: "pg-siva-parama", term: "Śiva (parama)", iast: "paramaśiva", summary: "Supreme Śiva: the Absolute; transcendent yet throbbing, never without Spanda." },
  { id: "pg-siva-tattva", term: "Śiva-tattva", iast: "śivatattva", summary: "Śiva-principle: first tattva, primal light-source of all manifestation." },
  { id: "pg-suddha-adhva", term: "Śuddhādhvā", iast: "śuddhādhvā", summary: "Pure course: extra-mundane manifestation from Śiva to Śuddhavidyā." },
  { id: "pg-suddha-vikalpa", term: "Śuddha-vikalpa", iast: "śuddhavikalpa", summary: "Pure construct: 'I am Śiva' destroying impure thoughts, then dissolving." },
  { id: "pg-suddha-vidya", term: "Śuddha-vidyā", iast: "śuddhavidyā", summary: "Pure wisdom: fifth tattva where I and This shine equally; balanced identity-in-difference." },
  { id: "pg-sunya-bauddha", term: "Śūnya (Bauddha)", iast: "śūnya", summary: "Buddhist void: absence as ultimate — refuted by the Experient's undeniability." },
  { id: "pg-sunya-saiva", term: "Śūnya (Śaiva)", iast: "śūnya", summary: "Śaiva void: object-free plenitude (cf. 1.25's unveiled void), not nothingness." },
  { id: "pg-sunya-pramata", term: "Śūnya-pramātṛ", iast: "śūnyapramātṛ", summary: "Void-knower: the subject abiding in objectless sleep; mistaken for the Self." },
  { id: "pg-saiva-agama", term: "Śaivāgama", iast: "śaivāgama", summary: "Śaiva revelation: traditional doctrine commanding faith; Trika's scriptural body." },
  { id: "pg-sankoca", term: "Saṅkoca", iast: "saṅkoca", summary: "Contraction: the infinite's self-limitation into soulhood; undone by recognition." },
  { id: "pg-sandhana", term: "Sandhāna", iast: "sandhāna", summary: "Joining: uniting powers with the centre; junction-practice at thought-gaps." },
  { id: "pg-samghatta", term: "Saṅghaṭṭa", iast: "saṅghaṭṭa", summary: "Dashing together: mind collided with the Heart revealing essences." },
  { id: "pg-samvit", term: "Saṃvit", iast: "saṃvit", summary: "Consciousness: awareness as such; beholding all as its play is liberation (2.5)." },
  { id: "pg-samvit-devata", term: "Saṃvit-devatā", iast: "saṃvitdevatā", summary: "Consciousness-deity: awareness worshipped as the goddess herself." },
  { id: "pg-samsara", term: "Saṃsāra (saṃsṛti)", iast: "saṃsāra", summary: "Transmigration: dread hard-to-cross path (1.20); engine subservience (3.18); dissolution declared." },
  { id: "pg-samhara-krtya", term: "Saṃhāra-kṛtya", iast: "saṃhārakṛtya", summary: "Act of reabsorption: withdrawal of manifestation into the ground." },
  { id: "pg-samsarin", term: "Saṃsārin", iast: "saṃsārin", summary: "Transmigrator: the subservient soul circling forms by fortress-fuel (3.17–3.18)." },
  { id: "pg-sakala", term: "Sakala", iast: "sakala", summary: "With-parts: the fully covered soul (body + instruments); lowest subject-grade." },
  { id: "pg-sat", term: "Sat", iast: "sat", summary: "Being, existent: the Real affirmed after every denial (1.5)." },
  { id: "pg-sattva", term: "Sattva", iast: "sattva", summary: "Lucidity-strand; yogically, the throbbing of pure I-ness in purified intellect." },
  { id: "pg-sadvidya", term: "Sadvidyā", iast: "sadvidyā", summary: "True wisdom: balanced I-This consciousness; Śuddhavidyā's other name." },
  { id: "pg-sadasiva", term: "Sadāśiva (Sadākhya-tattva)", iast: "sadāśiva", summary: "Ever-benign: third tattva; I predominant, This nascent — the awakened one's waking mode (1.18)." },
  { id: "pg-samana", term: "Samāna", iast: "samāna", summary: "Balancing breath: equalizing current at the navel centre." },
  { id: "pg-samarasa", term: "Samarasa", iast: "samarasa", summary: "Same-taste: undifferentiated savor of unity; equanimity as ontology." },
  { id: "pg-samadhi", term: "Samādhi", iast: "samādhi", summary: "Absorption: introvertive (nimīlana) then extrovertive (unmīlana) holding of Spanda." },
  { id: "pg-sarva-kartrtva", term: "Sarvakartrtva", iast: "sarvakartrtva", summary: "Omnidoing: universal agency mirrored in the soul's unfabricated doing (1.10)." },
  { id: "pg-savikalpa-jnana", term: "Savikalpa-jñāna", iast: "savikalpajñāna", summary: "Construct-laden knowing: cognition with thought-forms; stepping-stone to the pure construct." },
  { id: "pg-sahaja", term: "Sahaja", iast: "sahaja", summary: "Innate, co-born: one's nature, never manufactured — wisdom recognized, not made." },
  { id: "pg-samarasya", term: "Sāmarasya", iast: "sāmarasya", summary: "Identity of taste: fusion-unity of Śiva-Śakti; non-dual savor." },
  { id: "pg-saksad-upaya", term: "Sākṣād-upāya", iast: "sākṣādupāya", summary: "Direct means: immediacy without supports — Śāmbhava's other name." },
  { id: "pg-saksatkara", term: "Sākṣātkāra", iast: "sākṣātkāra", summary: "Direct realization: face-to-face seeing; self-experience as sole proof (3.11)." },
  { id: "pg-sugata", term: "Sugata", iast: "sugata", summary: "Well-gone: Buddha-epithet; Buddhist polemic neighbor on void and momentariness." },
  { id: "pg-susupti", term: "Suṣupti", iast: "suṣupti", summary: "Deep sleep: objectless state; blank for the deluded, plenitude for the unveiled (1.25)." },
  { id: "pg-susupti-savedya", term: "Suṣupti (sāvedya)", iast: "suṣupti", summary: "Sleep with content: deep sleep retaining subtle objectivity." },
  { id: "pg-susupti-apavedya", term: "Suṣupti (apavedya)", iast: "suṣupti", summary: "Contentless sleep: object-free blank proves the Experient by memory (1.12)." },
  { id: "pg-suksma-sarira", term: "Sūkṣma-śarīra", iast: "sūkṣmaśarīra", summary: "Subtle body: inner frame (fortress-city) carrying traces across lives (3.17)." },
  { id: "pg-saugata", term: "Saugata", iast: "saugata", summary: "Buddhist: of the Sugata's school; refuted on void and flux (1.12–1.16)." },
  { id: "pg-sthana-kalpana", term: "Sthāna-kalpanā", iast: "sthānakalpanā", summary: "Place-imagination: contemplative installation of deities in body-centres." },
  { id: "pg-sthiti-krtya", term: "Sthiti-kṛtya", iast: "sthitikṛtya", summary: "Act of maintenance: the Lord's preserving play within the five acts." },
  { id: "pg-sthula-bhuta", term: "Sthūla-bhūta", iast: "sthūlabhūta", summary: "Gross element: earth to ether in tangible form." },
  { id: "pg-sthula-sarira", term: "Sthūla-śarīra", iast: "sthūlaśarīra", summary: "Gross body: physical frame plundered by depression (3.8), offered as oblation." },
  { id: "pg-sphuratta", term: "Sphurattā", iast: "sphurattā", summary: "Flashing: endless scintillation of complete I-consciousness (frame verses)." },
  { id: "pg-svatantra", term: "Svatantra", iast: "svatantra", summary: "Self-dependent, free: the Lord's unimpeded nature mirrored in the seizer (3.3's contrast)." },
  { id: "pg-svacchanda", term: "Svacchanda", iast: "svacchanda", summary: "Self-willed: free-spirited Tantra of Bhairava's autonomy." },
  { id: "pg-sveccha", term: "Svecchā", iast: "svecchā", summary: "Self-will: acting from own freedom, not compulsion — autonomy in act." },
  { id: "pg-svapna", term: "Svapna", iast: "svapna", summary: "Dream: private constructs (1.9); centre-staged vivid display (3.2); one of three threads." },
  { id: "pg-svarupa", term: "Svarūpa", iast: "svarūpa", summary: "Own form, essence: covered by ever-risen powers (3.15); attained swiftly while awake (1.21)." },
  { id: "pg-svarupapatti", term: "Svarūpāpatti", iast: "svarūpāpatti", summary: "Attaining own nature: settling into true Self — liberation's substance." },
  { id: "pg-svalaksana", term: "Svalakṣaṇa", iast: "svalakṣaṇa", summary: "Own-mark: unique particular, bare percept before judgment." },
  { id: "pg-svasamvedana", term: "Svasaṃvedana", iast: "svasaṃvedana", summary: "Self-awareness: consciousness tasting itself; self-marking at junctions (3.9)." },
  { id: "pg-svatma-satkara", term: "Svātma-sātkāra", iast: "svātmasātkāra", summary: "Making the Self one's own: appropriating own being through presiding (3.7)." },
  { id: "pg-apara-pramata", term: "Apara-pramātṛ", iast: "aparapramātṛ", summary: "Lower knower: bound subject measuring a measured world." },
  { id: "pg-nibhalana", term: "Nibhālana", iast: "nibhālana", summary: "Shining forth: appearance dawning into clarity for the witness." },
  { id: "pg-praga", term: "Praga", iast: "praga", summary: "Prominence: manifestation's forth-standing fullness." },
  { id: "pg-ha", term: "Ha", iast: "ha", summary: "Letter ha: Śakti's expansion phoneme closing the alphabet's arc." },
  { id: "pg-hathapaka", term: "Haṭhapāka", iast: "haṭhapāka", summary: "Forcible ripening: accelerated maturation by intense practice-heat." },
  { id: "pg-hrdaya", term: "Hṛdaya", iast: "hṛdaya", summary: "Heart: central consciousness, not the organ; essence-revealing collision-point." },
  { id: "pg-hetu", term: "Hetu", iast: "hetu", summary: "Cause, reason: valid reasoning establishing Spanda; the middle term of inference." },
  { id: "pg-hetumat", term: "Hetumat", iast: "hetumat", summary: "Caused, reasoned: effects like depression traced to ignorance-cause (3.8)." },
  { id: "pg-hrada", term: "Hrada", iast: "hrada", summary: "Lake: consciousness clear, deep, uncovered — reservoir of mantra-virility." },
  { id: "pg-hamsa", term: "Haṃsa", iast: "haṃsa", summary: "Swan, I-am-That: the natural mantra breathing so'ham-haṃsa." },
  { id: "pg-hamsajapa", term: "Haṃsajapa", iast: "haṃsajapa", summary: "Swan-recitation: ajapa mantra of breath, 21,600 daily rounds unrecited." }
];
