// Viṣṇu Sahasranāma — frame verses: pūrva-pīṭhikā (13), dhyāna (1),
// rakṣā (1) and phalaśruti (22). IAST follows the Mahābhārata
// Anuśāsana-Parva text; translations and commentaries are this project's
// own paraphrases. See vishnu-sahasranama-source-provenance.ts.
export const vsFrameEn: any[] = [
  {
    id: "vs-purva-01",
    number: "Pūrva 1",
    section: "Pūrva-pīṭhikā · The six questions",
    iast: "vaiśampāyana uvāca — śrutvā dharmān aśeṣeṇa pāvanāni ca sarvaśaḥ । yudhiṣṭhiraḥ śāntanavaṃ punar evābhyabhāṣata",
    translation: "Vaiśampāyana said: Having heard all dharmas in full, and all that purifies, Yudhiṣṭhira again addressed the son of Śantanu (Bhīṣma).",
    commentary: "The setting matters: a battlefield's aftermath, a grandsire on arrows, a king who has heard everything yet asks once more. Dharma heard is not dharma settled — the six questions about to come are what remains after all ethics are expounded. Ask once more even after learning much.",
    keyPoints: ["Kurukṣetra aftermath: Bhīṣma on the arrow-bed.", "Heard dharma is not settled dharma.", "Vaiśampāyana narrates to Janamejaya's court."],
  },
  {
    id: "vs-purva-02",
    number: "Pūrva 2",
    section: "Pūrva-pīṭhikā · The six questions",
    iast: "yudhiṣṭhira uvāca — kim ekaṃ daivataṃ loke kiṃ vāpy ekaṃ parāyaṇam । stuvantaḥ kaṃ kam arcantaḥ prāpnuyur mānavāḥ śubham",
    translation: "Yudhiṣṭhira asked: Who is the one God in the world? Who is the one refuge? Praising whom, worshipping whom, may humans attain the good?",
    commentary: "Three questions in one breath — one God, one refuge, one worship: unity of object, shelter and practice. Yudhiṣṭhira, fresh from fratricidal war, asks not for ritual detail but for the single safe address of devotion. Three questions, one thirst: where to stand.",
    keyPoints: ["Questions 1–3: one God, one refuge, one worship.", "Asked by a victor who feels defeated.", "Unity sought in object, shelter, practice."],
  },
  {
    id: "vs-purva-03",
    number: "Pūrva 3",
    section: "Pūrva-pīṭhikā · The six questions",
    iast: "ko dharmaḥ sarva-dharmāṇāṃ bhavataḥ paramo mataḥ । kiṃ japan mucyate jantur janma-saṃsāra-bandhanāt",
    translation: "Which dharma of all dharmas do you hold supreme? Chanting what is a being freed from the bondage of birth and rebirth?",
    commentary: "Two more questions complete the set's practical edge: the highest dharma among many, and the chant (japa) that cuts rebirth's bondage. Theory (what is supreme) and method (what to chant) are demanded together — Yudhiṣṭhira wants liberation with instructions. The whole thousand names are Bhīṣma's answer to 'kiṃ japan'.",
    keyPoints: ["Questions 4–5: highest dharma, freeing chant.", "Theory and method demanded together.", "The Sahasranāma answers 'chanting what?'."],
  },
  {
    id: "vs-purva-04",
    number: "Pūrva 4",
    section: "Pūrva-pīṭhikā · Bhīṣma answers",
    iast: "bhīṣma uvāca — jagat-prabhuṃ deva-devam anantaṃ puruṣottamam । stuvan nāma-sahasreṇa puruṣaḥ satatotthitaḥ",
    translation: "Bhīṣma said: Praising with a thousand names the Lord of worlds, God of gods, the endless, the supreme Person — a man, ever-risen (vigilant)...",
    commentary: "Bhīṣma's answer begins mid-sentence, spilling into the next verses: praise with vigilance (satatotthita, ever-risen) the Lord of worlds. The thousand names are prescribed before they are given — method first, content after. Rise early; praise attentively.",
    keyPoints: ["Bhīṣma's answer begins: praise ever-risen.", "Method prescribed before content given.", "Satatotthita: vigilance as worship's posture."],
  },
  {
    id: "vs-purva-05",
    number: "Pūrva 5",
    section: "Pūrva-pīṭhikā · Bhīṣma answers",
    iast: "tam eva cārcayannityaṃ bhaktyā puruṣam avyayam । dhyāyan stuvan namasyanśca yajamānas tam eva ca",
    translation: "...worshipping Him alone constantly with devotion, the undecaying Person — meditating, praising, bowing, and sacrificing to Him alone...",
    commentary: "Five practices converge on One: worship, meditation, praise, obeisance, sacrifice — the whole ritual spectrum aimed single-pointedly. Bhakti (devotion) is named as the constant medium; frequency (nityam, always) as the method. Unify scattered practices into one address.",
    keyPoints: ["Five practices, one address.", "Bhakti named as the constant medium.", "Nityam: frequency as method."],
  },
  {
    id: "vs-purva-06",
    number: "Pūrva 6",
    section: "Pūrva-pīṭhikā · Bhīṣma answers",
    iast: "anādi-nidhanaṃ viṣṇuṃ sarva-loka-maheśvaram । lokādhyakṣaṃ stuvan nityaṃ sarva-duḥkhātigo bhavet",
    translation: "...Viṣṇu without beginning or end, great Lord of all worlds — praising the world's overseer constantly, one crosses beyond all sorrow...",
    commentary: "The promise is stated plainly: constant praise of the beginningless overseer carries across (atiga) all sorrow. Sorrow is an ocean; praise is the boat; constancy (nityam) the rowing. Anādi-nidhana frames the crossing — the timeless ferries the time-bound. Row daily.",
    keyPoints: ["The promise: praise crosses all sorrow.", "Sorrow as ocean, praise as boat.", "Timeless ferries the time-bound."],
  },
  {
    id: "vs-purva-07",
    number: "Pūrva 7",
    section: "Pūrva-pīṭhikā · Bhīṣma answers",
    iast: "brahmaṇyaṃ sarva-dharma-jñaṃ lokānāṃ kīrti-vardhanam । loka-nāthaṃ mahad-bhūtaṃ sarva-bhūta-bhavodbhavam",
    translation: "...friend of Brahman, knower of all dharmas, increaser of worlds' fame, lord of worlds, the great Being, source of all beings' becoming...",
    commentary: "The Lord's credentials accumulate: friend of the sacred, knower of every duty, fame's increaser, world's lord, great Being, becoming's source. Each epithet answers one anxiety of the questioner — knowledge, reputation, protection, origin. List His credentials before presenting your case.",
    keyPoints: ["Credentials: friend, knower, increaser, lord.", "Each epithet answers an anxiety.", "Mahad-bhūta: greatness as being."],
  },
  {
    id: "vs-purva-08",
    number: "Pūrva 8",
    section: "Pūrva-pīṭhikā · Bhīṣma answers",
    iast: "eṣa me sarva-dharmāṇāṃ dharmo 'dhikatamo mataḥ । yad bhaktyā puṇḍarīkākṣaṃ stavair arcen naraḥ sadā",
    translation: "...this I hold the highest of all dharmas: that a man should always worship the lotus-eyed with hymns of devotion.",
    commentary: "The fourth question answered outright: highest dharma is constant devotional hymning of the lotus-eyed. Not sacrifice, not austerity, not study — praise with bhakti, always (sadā). Lotuses for eyes: compassion you can picture. Make hymning your highest duty.",
    keyPoints: ["Highest dharma declared: constant devotional praise.", "Not rite or rigour, but hymning with love.", "Puṇḍarīkākṣa: compassion pictured."],
  },
  {
    id: "vs-purva-09",
    number: "Pūrva 9",
    section: "Pūrva-pīṭhikā · Bhīṣma answers",
    iast: "paramaṃ yo mahat-tejaḥ paramaṃ yo mahat-tapaḥ । paramaṃ yo mahad-brahma paramaṃ yaḥ parāyaṇam",
    translation: "...who is supreme great radiance, supreme great austerity, supreme great Brahman, supreme final refuge...",
    commentary: "Supremacy quadruples — radiance, austerity, Brahman, refuge: splendour, discipline, reality, shelter as one summit. Parama repeated insists there is no higher court of appeal. When seeking the supreme, check all four: does it shine, discipline, ground, shelter?",
    keyPoints: ["Parama fourfold: radiance, rigour, reality, refuge.", "No higher court of appeal.", "Test supremacy four ways."],
  },
  {
    id: "vs-purva-10",
    number: "Pūrva 10",
    section: "Pūrva-pīṭhikā · Bhīṣma answers",
    iast: "pavitrāṇāṃ pavitraṃ yo maṅgalānāṃ ca maṅgalam । daivataṃ devatānāṃ ca bhūtānāṃ yo 'vyayaḥ pitā",
    translation: "...who is the purest of the pure, most auspicious of the auspicious, God of gods, and undecaying father of beings...",
    commentary: "Purity and auspiciousness superlatived: contact with Him purifies purifiers and blesses blessings. God of gods (even deities have a deity) and father who never decays (avyaya): authority with paternity, worship with childhood. Approach as child, not contractor.",
    keyPoints: ["Purest of pure, auspicious of auspicious.", "Even deities have a deity.", "Fatherhood undecaying: childhood eternal."],
  },
  {
    id: "vs-purva-11",
    number: "Pūrva 11",
    section: "Pūrva-pīṭhikā · Bhīṣma answers",
    iast: "yataḥ sarvāṇi bhūtāni bhavanty ādi-yugāgame । yasmiṃśca pralayaṃ yānti punar eva yuga-kṣaye",
    translation: "...from whom all beings come forth at the coming of the first age, and into whom they merge again at the age's waning...",
    commentary: "Cosmology in two lines: emanation at dawn, reabsorption at dusk of ages. Origin and end share one address, so becoming is a round trip, never exile. History breathes out and in; both motions are His. Trust the return as much as the emergence.",
    keyPoints: ["Emanation at dawn, merger at dusk.", "Becoming as round trip, never exile.", "One address for origin and end."],
  },
  {
    id: "vs-purva-12",
    number: "Pūrva 12",
    section: "Pūrva-pīṭhikā · The commission",
    iast: "tasya loka-pradhānasya jagan-nāthasya bhū-pateḥ । viṣṇor nāma-sahasraṃ me śṛṇu pāpa-bhayāpaham",
    translation: "...of that foremost of worlds, lord of the universe, master of earth — hear from me Viṣṇu's thousand names, dispelling sin and fear.",
    commentary: "The commission proper: hear (śṛṇu) the thousand names that dispel sin and fear. Foremost (pradhāna), universe-lord (jagannātha), earth-master (bhūpati): eminence, vastness, nearness in one line. Listening itself is prescribed as medicine. Listen as treatment.",
    keyPoints: ["Commission: hear the sin-and-fear-dispelling names.", "Eminence, vastness, nearness together.", "Listening prescribed as medicine."],
  },
  {
    id: "vs-purva-13",
    number: "Pūrva 13",
    section: "Pūrva-pīṭhikā · The commission",
    iast: "yāni nāmāni gauṇāni vikhyātāni mahātmanaḥ । ṛṣibhiḥ parigītāni tāni vakṣyāmi bhūtaye । ṛṣir nāmnāṃ sahasrasya vedavyāso mahā-muniḥ । chando 'nuṣṭup tathā devo bhagavān devakī-sutaḥ",
    translation: "The renowned secondary names of the great Self, sung by seers — these I shall tell for welfare. Of the thousand names the seer is the great sage Vedavyāsa; the metre anuṣṭup; the deity lord Devakī's son.",
    commentary: "Bhīṣma names his sources (seer-sung names for welfare) then gives the hymn's ritual passport: seer Vyāsa, metre anuṣṭup, deity Kṛṣṇa Devakīnandana. G Fasten these three before reciting — lineage, rhythm, face. Secondary (gauṇa) names are qualities' names, praising through attributes.",
    keyPoints: ["Ritual passport: seer, metre, deity.", "Gauṇa names: praise through attributes.", "Bhūtaye: told for welfare, not display."],
  },
  {
    id: "vs-dhyana-1",
    number: "Dhyāna",
    section: "Dhyāna",
    iast: "śāntākāraṃ bhuja-gaśayanaṃ padma-nābhaṃ sureśam । viśvādhāraṃ gagana-sadṛśaṃ megha-varṇaṃ śubhāṅgam । lakṣmī-kāntaṃ kamala-nayanaṃ yogibhir dhyāna-gamyam । vande viṣṇuṃ bhava-bhaya-haraṃ sarva-lokaika-nātham",
    conceptIds: ["vs-nama-001", "vs-nama-045", "vs-nama-126", "vs-nama-187"],
    translation: "I bow to Viṣṇu, of peaceful form, reclining on the serpent, lotus-navelled, lord of gods, support of the universe, sky-vast, cloud-hued, fair-limbed, Lakṣmī's beloved, lotus-eyed, reached by yogīs in meditation, remover of birth-fear, sole lord of all worlds.",
    commentary: "The visualization before recitation: peace (śānta) as His shape, serpent-couch on waters, sky-vastness cloud-dark, Lakṣmī beside lotus eyes. Reclining yet supporting (viśvādhāra): rest bearing worlds. Birth-fear's remover (bhavabhayahara) is the fruit held in the image itself. See Him reclining before naming Him striding.",
    keyPoints: ["Peace as shape, serpent as couch.", "Reclining yet world-bearing.", "Hold this image through all thousand names."],
  },
  {
    id: "vs-raksha-1",
    number: "Rakṣā",
    section: "Phalaśruti · The guard",
    iast: "vanamālī gadī śārṅgī śaṅkhī cakrī ca nandakī । śrīmān nārāyaṇo viṣṇur vāsudevo 'bhirakṣatu",
    conceptIds: ["vs-nama-561", "vs-nama-993", "vs-nama-994", "vs-nama-995", "vs-nama-996", "vs-nama-997"],
    translation: "May the garlanded, mace-, bow-, conch-, discus- and sword-bearing glorious Nārāyaṇa Viṣṇu Vāsudeva protect us.",
    commentary: "Tradition stations this guard-verse after the thousand names: six weapons worn, three majesty-names invoked (Nārāyaṇa, Viṣṇu, Vāsudeva), protection (abhirakṣatu) besought. Armour after effort; the reciter exits the temple of names under escort. Close sittings with this guard.",
    keyPoints: ["Six weapons worn, three names invoked.", "Armour after effort.", "Abhirakṣatu: protection besought, not demanded."],
  },
  {
    id: "vs-phala-01",
    number: "Phala 1 (iti idaṃ)",
    section: "Phalaśruti · Fruits of recitation",
    iast: "iti idaṃ kīrtanīyasya keśavasya mahātmanaḥ । nāmnāṃ sahasraṃ divyānām aśeṣeṇa prakīrtitam",
    translation: "Thus the thousand divine names of glorious Keśava, to be sung, have been proclaimed in full.",
    commentary: "Bhīṣma seals the catalogue: sung (kīrtanīya) in full (aśeṣeṇa), nothing withheld. Divine (divya) names differ from labels — each carries charge. What follows (phala) tells the charge's effects. Receive the whole before asking its fruits.",
    keyPoints: ["Seal: proclaimed in full, nothing withheld.", "Divya names carry charge, not labels.", "Kīrtanīya: meant for singing."],
  },
  {
    id: "vs-phala-02",
    number: "Phala 2",
    section: "Phalaśruti · Fruits of recitation",
    iast: "ya idaṃ śṛṇuyān nityaṃ yaś cāpi parikīrtayet । nāśubhaṃ prāpnuyāt kiñcit so 'mutreha ca mānavaḥ",
    translation: "Whoever hears this daily, and whoever chants it forth — no evil befalls that person, here or hereafter.",
    commentary: "Hearing (śravaṇa) and chanting (kīrtana) both qualify: ear and tongue are equal doors. No evil (nāśubham) here or beyond (amutreha): protection spanning worlds. Daily (nityam) is the price — regularity, not intensity. Hear or chant daily; claim both worlds' safety.",
    keyPoints: ["Ear and tongue: equal doors.", "Protection spanning both worlds.", "Nityam: regularity, not intensity."],
  },
  {
    id: "vs-phala-03",
    number: "Phala 3",
    section: "Phalaśruti · Fruits of recitation",
    iast: "vedāntago brāhmaṇaḥ syāt kṣatriyo vijayī bhavet । vaiśyo dhana-samṛddhaḥ syāc chūdraḥ sukham avāpnuyāt",
    translation: "A brāhmaṇa becomes Vedānta-knowing, a kṣatriya victorious, a vaiśya rich in wealth, a śūdra attains happiness.",
    commentary: "Fruits portioned by station yet given to all four orders without exception: knowledge, victory, wealth, happiness — each what its life most lacks. Universality with appropriateness: one hymn, fitting gifts. Whatever your station, your fruit is named.",
    keyPoints: ["All four orders included, none refused.", "Fruits fitted: knowledge, victory, wealth, joy.", "One hymn, appropriate gifts."],
  },
  {
    id: "vs-phala-04",
    number: "Phala 4",
    section: "Phalaśruti · Fruits of recitation",
    iast: "dharmārthī prāpnuyād dharmam arthārthī cārtham āpnuyāt । kāmān avāpnuyāt kāmī prajārthī cāpnuyāt prajām",
    translation: "Desiring dharma one wins dharma, desiring wealth one wins wealth; the desirous wins desires, desiring offspring one wins offspring.",
    commentary: "The four aims (puruṣārthas) minus liberation are all granted — pointedly, mokṣa waits for later verses, as if lesser fruits must be exhausted first. Desire itself is honoured as prayer-fuel. Bring one honest desire to the recitation.",
    keyPoints: ["Dharma, wealth, desire, offspring granted.", "Mokṣa reserved for later verses.", "Desire honoured as prayer-fuel."],
  },
  {
    id: "vs-phala-05",
    number: "Phala 5",
    section: "Phalaśruti · Fruits of recitation",
    iast: "bhaktimān yaḥ sadotthāya śucis tad-gata-mānasah । sahasraṃ vāsudevasya nāmnām etat prakīrtayet",
    translation: "Devoted, rising ever (early), pure, mind gone to Him — who chants this thousand of Vāsudeva's names...",
    commentary: "The practitioner's portrait: devotion (bhaktimān), early rising (sadotthāya), purity (śuci), absorbed mind (tadgatamānasa). Four qualifications, all of conduct, none of birth. Dawn, cleanliness, Richtung: the technology of reception. Rise early, wash, turn mind Godward.",
    keyPoints: ["Four qualifications, all of conduct.", "Dawn, purity, absorption.", "No birth-barrier named."],
  },
  {
    id: "vs-phala-06",
    number: "Phala 6",
    section: "Phalaśruti · Fruits of recitation",
    iast: "yaśaḥ prāpnoti vipulaṃ jñāti-prādhānyam eva ca । acalāṃ śriyam āpnoti śreyaḥ prāpnoty anuttamam",
    translation: "...wins wide fame, pre-eminence among kin, unshaken prosperity, and the highest good.",
    commentary: "...the sentence completes: fame, kinship-honour, unshaken prosperity (acalā śrī), highest good (śreyaḥ anuttamam). Outer and inner fruits braided — reputation with rootedness, wealth with worth. Unshaken (acalā) qualifies prosperity: fortune that cannot slip. Seek prosperity that cannot slip.",
    keyPoints: ["Fame, kin-honour, firm fortune, highest good.", "Outer and inner fruits braided.", "Acalā śrī: wealth that cannot slip."],
  },
  {
    id: "vs-phala-07",
    number: "Phala 7",
    section: "Phalaśruti · Fruits of recitation",
    iast: "na bhayaṃ kvacid āpnoti vīryaṃ tejaśca vindati । bhavaty arogo dyutimān bala-rūpa-guṇānvitaḥ",
    translation: "He meets fear nowhere, and finds vigour and radiance; becomes disease-free, lustrous, endowed with strength, beauty and virtue.",
    commentary: "Fearlessness first, then vigour (vīrya) and radiance (tejas): courage before charisma. Health (aroga), lustre (dyuti), strength, beauty, virtue — the body transfigured as devotion's byproduct, never its aim. Fearlessness is the root prescription.",
    keyPoints: ["Fearlessness first, charisma after.", "Body transfigured as byproduct.", "Aroga: health as devotion's interest."],
  },
  {
    id: "vs-phala-08",
    number: "Phala 8",
    section: "Phalaśruti · Fruits of recitation",
    iast: "rogārto mucyate rogād baddho mucyate bandhanāt । bhayān mucyeta bhītas tu mucyeta āpanna āpadaḥ",
    translation: "The sick is freed from sickness, the bound from bondage; the frightened is freed from fear, the distressed from distress.",
    commentary: "Four freedoms in parallel grammar — sickness, bondage, fear, distress — each met with the same verb (mucyate, is freed): liberation's grammar applied to ordinary ills. The hymn treats daily troubles as worthy of mokṣa-language. Name your bondage; hear the verb.",
    keyPoints: ["Four freedoms, one verb: mucyate.", "Ordinary ills in mokṣa-grammar.", "Sickness, chains, fear, distress covered."],
  },
  {
    id: "vs-phala-09",
    number: "Phala 9",
    section: "Phalaśruti · Fruits of recitation",
    iast: "durgāṇy atitaraty āśu puruṣaḥ puruṣottamam । stuvan nāma-sahasreṇa nityaṃ bhakti-samanvitaḥ",
    translation: "Hard passes are swiftly crossed by the man who praises Puruṣottama with the thousand names, constantly, with devotion.",
    commentary: "Difficulties (durgāṇi) are mountain passes (the word's first sense): praise as mountaineering, devotion as equipment, constancy (nityam) as pace. Swiftly (āśu) promises speed to the steady — paradox of grace. Cross one hard pass with steady praise.",
    keyPoints: ["Durgāṇi: difficulties as mountain passes.", "Devotion as equipment, constancy as pace.", "Swiftly — to the steady."],
  },
  {
    id: "vs-phala-10",
    number: "Phala 10",
    section: "Phalaśruti · Fruits of recitation",
    iast: "vāsudevāśrayo martyo vāsudeva-parāyaṇaḥ । sarva-pāpa-viśuddhātmā yāti brahma sanātanam",
    translation: "The mortal sheltered in Vāsudeva, devoted to Vāsudeva as final goal — his self cleansed of all sin — reaches eternal Brahman.",
    commentary: "Shelter (āśraya) and goal (parāyaṇa): Vāsudeva as both inn and destination, journey and arrival one address. Cleansed of all sin (sarvapāpaviśuddhātmā) the mortal (martya) reaches (yāti) the eternal Brahman (sanātanam): mortality exiting into eternity. Take shelter and goal as one.",
    keyPoints: ["Inn and destination: one address.", "Shelter (āśraya) plus goal (parāyaṇa).", "Mortality exiting into eternity."],
  },
  {
    id: "vs-phala-11",
    number: "Phala 11",
    section: "Phalaśruti · Fruits of recitation",
    iast: "na vāsudeva-bhaktānām aśubhaṃ vidyate kvacit । janma-mṛtyu-jarā-vyādhi-bhayaṃ naivopajāyate",
    translation: "For Vāsudeva's devotees no evil exists anywhere; fear of birth, death, age and disease simply does not arise.",
    commentary: "The boldest promise: evil (aśubha) nowhere (kvacit) for devotees, and the fourfold fear — birth, death, age, disease — not merely conquered but unarisen (naivopajāyate). Prevention outranks cure; devotion as immunity. Live as the immune, not the anxious.",
    keyPoints: ["Evil nowhere for devotees.", "Four fears unarisen, not merely beaten.", "Devotion as immunity."],
  },
  {
    id: "vs-phala-12",
    number: "Phala 12",
    section: "Phalaśruti · Fruits of recitation",
    iast: "imaṃ stavam adhīyānaḥ śraddhā-bhakti-samanvitaḥ । yujyetātma-sukha-kṣānti-śrī-dhṛti-smṛti-kīrtibhiḥ",
    translation: "Studying this hymn with faith and devotion, one is yoked to self-joy, patience, glory, steadiness, memory and fame.",
    commentary: "Study (adhīyāna) with faith (śraddhā) and devotion yokes (yujyate) six goods: self-joy, patience, glory, steadiness, memory, fame — inward pair, outward pair, bridging pair. Yoked like oxen to a plough: goods as harness, not luggage. Study yokes; carry the six.",
    keyPoints: ["Six goods: joy, patience, glory, poise, memory, fame.", "Yoked: goods as harness, not luggage.", "Faith plus devotion as yoke-strap."],
  },
  {
    id: "vs-phala-13",
    number: "Phala 13",
    section: "Phalaśruti · Fruits of recitation",
    iast: "na krodho na ca mātsaryaṃ na lobho nāśubhā matiḥ । bhavanti kṛta-puṇyānāṃ bhaktānāṃ puruṣottame",
    translation: "No anger, no envy, no greed, no evil mind befall the merit-made devotees of Puruṣottama.",
    commentary: "Negatives as fruits: anger, envy, greed, evil-mindedness simply do not occur (bhavanti with na) in devotees — purification by absence, vices starved rather than fought. Merit-made (kṛtapuṇya): goodness accumulated becomes immunity. Starve one vice by devotion, not combat.",
    keyPoints: ["Purification by absence.", "Anger, envy, greed, evil mind: four starved.", "Kṛtapuṇya: merit as immunity."],
  },
  {
    id: "vs-phala-14",
    number: "Phala 14",
    section: "Phalaśruti · Fruits of recitation",
    iast: "dyauḥ sacandrārka-nakṣatrā khaṃ diśo bhūr mahodadhiḥ । vāsudevasya vīryeṇa vidhṛtāni mahātmanaḥ",
    translation: "Heaven with moon, sun and stars, sky, quarters, earth and great ocean — are held firm by the might of great-souled Vāsudeva.",
    commentary: "Cosmology as doxology: seven realms (heaven to ocean) held (vidhṛtāni) by might (vīrya), not mechanism. The universe is carried, not merely caused — maintenance as embrace. Look up once at held, not hanging, stars.",
    keyPoints: ["Seven realms held, not hanging.", "Maintenance as embrace.", "Vīrya: might as carrying."],
  },
  {
    id: "vs-phala-15",
    number: "Phala 15",
    section: "Phalaśruti · Fruits of recitation",
    iast: "sasurāsura-gandharvaṃ sayakṣoraga-rākṣasam । jagad vaśe vartate 'daṃ kṛṣṇasya sacarācaram",
    translation: "With gods, demons, gandharvas, yakṣas, serpents and rākṣasas — this moving-and-unmoving world abides in Kṛṣṇa's control.",
    commentary: "All beings — gods to demons, movers to unmoving — within one control (vaśe): enmity itself administered. Kṛṣṇa named directly here, the pastoral person behind cosmic sway. Even adversaries abide in His order; fear no category.",
    keyPoints: ["Gods to demons: all administered.", "Moving and unmoving: none outside.", "Enmity itself within order."],
  },
  {
    id: "vs-phala-16",
    number: "Phala 16",
    section: "Phalaśruti · Fruits of recitation",
    iast: "indriyāṇi mano buddhiḥ sattvaṃ tejo balaṃ dhṛtiḥ । vāsudevātmakāny āhuḥ kṣetraṃ kṣetrajña eva ca",
    translation: "Senses, mind, intellect, vitality, splendour, strength, patience — these, they say, are Vāsudeva-selfed; and so are field and field-knower.",
    commentary: "Interior cosmology: seven faculties (senses to patience) are declared Vāsudeva-selfed (vāsudevātmakāni) — psychology as theology. Field (kṣetra) and knower (kṣetrajña) both claimed: body and witness one property. The Gītā's chapter thirteen in two lines. Survey your faculties as His.",
    keyPoints: ["Seven faculties Vāsudeva-selfed.", "Field and knower: one property.", "Psychology as theology."],
  },
  {
    id: "vs-phala-17",
    number: "Phala 17",
    section: "Phalaśruti · Fruits of recitation",
    iast: "sarvāgamānām ācāraḥ prathamaṃ parikalpate । ācāra-prabhavo dharmo dharmasya prabhur acyutaḥ",
    translation: "Of all scriptures, conduct is reckoned first; from conduct springs dharma, and dharma's lord is Acyuta.",
    commentary: "Scripture bows to conduct (ācāra first): lived goodness outranks cited texts, conduct sourcing dharma, dharma owned by Acyuta. The hymn that began with questions ends by ranking behaviour above books. Practise one conduct above quoting one text.",
    keyPoints: ["Conduct first, scripture second.", "Dharma sourced in behaviour.", "Acyuta owns dharma: unfailing standard."],
  },
  {
    id: "vs-phala-18",
    number: "Phala 18",
    section: "Phalaśruti · Fruits of recitation",
    iast: "ṛṣayaḥ pitaraḥ devā mahā-bhūtāni dhātavaḥ । jaṅgamājaṅgamaṃ cedaṃ jagan nārāyaṇodbhavam",
    translation: "Seers, fathers, gods, great elements, constituents — and this moving-and-unmoving world — are Nārāyaṇa-born.",
    commentary: "Five orders (seers to constituents) plus the whole moving-unmoving world share one birth (nārāyaṇodbhavam): priest, ancestor, god, element and stone are siblings. Kinship extended to everything relativizes every quarrel. Greet one element as kin today.",
    keyPoints: ["Five orders, one birth.", "Stone as sibling: kinship entire.", "Nārāyaṇodbhava: common natality."],
  },
  {
    id: "vs-phala-19",
    number: "Phala 19",
    section: "Phalaśruti · Fruits of recitation",
    iast: "yogo jñānaṃ tathā sāṅkhyaṃ vidyāḥ śilpādi karma ca । vedāḥ śāstrāṇi vijñānam etat sarvaṃ janārdanāt",
    translation: "Yoga, knowledge, Sāṅkhya, learnings, crafts and works, Vedas, sciences, discernment — all this is from Janārdana.",
    commentary: "Every discipline — yoga to crafts (śilpa), Vedas to applied science (vijñāna) — sourced in Janārdana: no secular remainder, Sāṅkhya and smithcraft equally divine. Churner of men (janārdana) churns out curricula. Learn one craft as from Him.",
    keyPoints: ["Yoga to smithcraft: all sourced.", "No secular remainder.", "Sāṅkhya and crafts equally divine."],
  },
  {
    id: "vs-phala-20",
    number: "Phala 20",
    section: "Phalaśruti · Fruits of recitation",
    iast: "eko viṣṇur mahad-bhūtaṃ pṛthag-bhūtāny anekaśaḥ । tril lokān vyāpya bhūtātmā bhuṅkte viśvabhug avyayaḥ",
    translation: "One Viṣṇu, the great Being; beings manifold and separate. Pervading three worlds as beings' Self, He enjoys — all-enjoyer, undecaying.",
    commentary: "One and many stated together without apology: one Viṣṇu, separate manifold beings, pervasion, enjoyment (bhuṅkte) without decay (avyayaḥ). Enjoyment (viśvabhuk) that never depletes the enjoyed: use without using-up. Enjoy one thing without depleting it.",
    keyPoints: ["One Viṣṇu, manifold beings, no apology.", "Enjoyment without depletion.", "Pervasion as the ground of joy."],
  },
  {
    id: "vs-phala-21",
    number: "Phala 21",
    section: "Phalaśruti · Fruits of recitation",
    iast: "imaṃ stavaṃ bhagavato viṣṇor vyāsena kīrtitam । paṭhan ye icchet puruṣaḥ śreyaḥ prāptum sukhāni ca",
    translation: "This hymn of lord Viṣṇu, sung by Vyāsa — reciting it, should a man wish to win the good and happiness...",
    commentary: "...the sentence completes next verse: reciting (paṭhan) Vyāsa-sung praise wins both good (śreyas) and joys (sukhāni) — the two aims finally named together, welfare and delight unopposed. Authorship credited to Vyāsa: lineage matters. Recite for both good and joy.",
    keyPoints: ["Vyāsa-sung: lineage credited.", "Śreyas and sukhāni together.", "Reciting (paṭhana) as the act."],
  },
  {
    id: "vs-phala-22",
    number: "Phala 22",
    section: "Phalaśruti · Fruits of recitation",
    iast: "viśveśvaram ajaṃ devaṃ jagataḥ prabhavāpyayam । bhajanti ye puṣkarākṣaṃ na te yānti parābhavam",
    translation: "...who worship the lotus-eyed — Viśveśvara, unborn God, world's origin and dissolution — they never meet defeat.",
    commentary: "The finale: worshippers (bhajanti) of the lotus-eyed — lord of the universe, unborn, origin-and-end of worlds — never meet defeat (parābhava). Origin and dissolution (prabhavāpyaya) frame protection; defeat is metaphysically cancelled. End where the hymn ends: undefeated by worship.",
    keyPoints: ["Never defeat for worshippers.", "Origin-and-end framing protection.", "Puṣkarākṣa closing as He opened."],
  },
]